#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.BBS_001_BUY_DETAILS WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.BBS_001_BUY_DETAILS SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_41 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.BBS_001_BUY_DETAILS WHERE 1=0;

--Step2:
INSERT  INTO T_41 (
  ID,
  TASK_TYPE,
  BUY_TYPE,
  BUY_CONTRACT_ID,
  DRAFT_ID,
  BUYBIZ_TYPE,
  CENTRAL_BANKFLG,
  INNER_FLAG,
  SAME_CITY_FLAG,
  VIRTUAL_FLAG,
  PREVIOUS_HAND,
  PAYMENT_DATE,
  POSTPONE_DAYS,
  PAYMENT_DAYS,
  BAN_ENDRSMT_MK,
  RPD_OPEN_DT,
  RPD_DUE_DT,
  RPD_INTRATE,
  INTRST_RATE,
  PAYMENT_MATURITY,
  STTLM_MK,
  REQ_REMARK,
  RCV_REMARK,
  PAYMENT_BY_BUYER,
  PAY_AMOUNT,
  RISK_FEES,
  CREDIT_LINE_ID,
  CREDIT_LINE,
  APPLY_DATE,
  AOACCNINF_ACTNO,
  AOACCNINF_UBANK,
  DSCNT_PROPS_ROLE,
  DSCNT_PROPS_NAME,
  DSCNT_PROPS_CMONID,
  DSCNT_PROPS_ACTNO,
  DSCNT_PROPS_UBANK,
  DSCNT_PROPS_AGCY_UBANK,
  DSCNT_ROLE,
  DSCNT_CMONID,
  DSCNT_NAME,
  DSCNT_ACTNO,
  DSCNT_UBANK,
  CONTRACTNO,
  INVC_NB,
  BTCH_NO,
  CREDIT_LINE_STATUS,
  ACCEPT_STATUS,
  CHECK_STATUS,
  QUERY_ORDER,
  QUERY_CONTENT,
  QUERY_TYPE,
  CHECK_RESULT,
  CHECK_CONTENT,
  QUERY_CHECK_ID,
  FLAW_STATUS,
  DISAFFIRM_STATUS,
  RCV_PRXY_SGNTR,
  ACCOUNT_DATE,
  ACCOUNT_FLAG,
  ACTLOG_ID,
  ACCOUNT,
  ENDST_DATE,
  CANCEL_DATE,
  INTEREST_STATUS,
  CALC_STATUS,
  BUY_STATUS,
  SIG_MK,
  CM_STATUS,
  CM_ERR_PROCD,
  ECDS_PRC_MSG,
  TRF_REF,
  TRF_ID,
  SWT_BIZ_ID,
  ENTITY_REGSTAT,
  ENTITY_REG_ID,
  VALUE1,
  MISC,
  LAST_UPD_OPER_ID,
  LAST_UPD_TIME,
  INTR_OFFSET,
  start_dt,
  end_dt)
SELECT
  N.ID,
  N.TASK_TYPE,
  N.BUY_TYPE,
  N.BUY_CONTRACT_ID,
  N.DRAFT_ID,
  N.BUYBIZ_TYPE,
  N.CENTRAL_BANKFLG,
  N.INNER_FLAG,
  N.SAME_CITY_FLAG,
  N.VIRTUAL_FLAG,
  N.PREVIOUS_HAND,
  N.PAYMENT_DATE,
  N.POSTPONE_DAYS,
  N.PAYMENT_DAYS,
  N.BAN_ENDRSMT_MK,
  N.RPD_OPEN_DT,
  N.RPD_DUE_DT,
  N.RPD_INTRATE,
  N.INTRST_RATE,
  N.PAYMENT_MATURITY,
  N.STTLM_MK,
  N.REQ_REMARK,
  N.RCV_REMARK,
  N.PAYMENT_BY_BUYER,
  N.PAY_AMOUNT,
  N.RISK_FEES,
  N.CREDIT_LINE_ID,
  N.CREDIT_LINE,
  N.APPLY_DATE,
  N.AOACCNINF_ACTNO,
  N.AOACCNINF_UBANK,
  N.DSCNT_PROPS_ROLE,
  N.DSCNT_PROPS_NAME,
  N.DSCNT_PROPS_CMONID,
  N.DSCNT_PROPS_ACTNO,
  N.DSCNT_PROPS_UBANK,
  N.DSCNT_PROPS_AGCY_UBANK,
  N.DSCNT_ROLE,
  N.DSCNT_CMONID,
  N.DSCNT_NAME,
  N.DSCNT_ACTNO,
  N.DSCNT_UBANK,
  N.CONTRACTNO,
  N.INVC_NB,
  N.BTCH_NO,
  N.CREDIT_LINE_STATUS,
  N.ACCEPT_STATUS,
  N.CHECK_STATUS,
  N.QUERY_ORDER,
  N.QUERY_CONTENT,
  N.QUERY_TYPE,
  N.CHECK_RESULT,
  N.CHECK_CONTENT,
  N.QUERY_CHECK_ID,
  N.FLAW_STATUS,
  N.DISAFFIRM_STATUS,
  N.RCV_PRXY_SGNTR,
  N.ACCOUNT_DATE,
  N.ACCOUNT_FLAG,
  N.ACTLOG_ID,
  N.ACCOUNT,
  N.ENDST_DATE,
  N.CANCEL_DATE,
  N.INTEREST_STATUS,
  N.CALC_STATUS,
  N.BUY_STATUS,
  N.SIG_MK,
  N.CM_STATUS,
  N.CM_ERR_PROCD,
  N.ECDS_PRC_MSG,
  N.TRF_REF,
  N.TRF_ID,
  N.SWT_BIZ_ID,
  N.ENTITY_REGSTAT,
  N.ENTITY_REG_ID,
  N.VALUE1,
  N.MISC,
  N.LAST_UPD_OPER_ID,
  N.LAST_UPD_TIME,
  N.INTR_OFFSET,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ID, 0 ) AS ID ,
  COALESCE(TASK_TYPE, '' ) AS TASK_TYPE ,
  COALESCE(BUY_TYPE, '' ) AS BUY_TYPE ,
  COALESCE(BUY_CONTRACT_ID, 0 ) AS BUY_CONTRACT_ID ,
  COALESCE(DRAFT_ID, 0 ) AS DRAFT_ID ,
  COALESCE(BUYBIZ_TYPE, '' ) AS BUYBIZ_TYPE ,
  COALESCE(CENTRAL_BANKFLG, '' ) AS CENTRAL_BANKFLG ,
  COALESCE(INNER_FLAG, '' ) AS INNER_FLAG ,
  COALESCE(SAME_CITY_FLAG, '' ) AS SAME_CITY_FLAG ,
  COALESCE(VIRTUAL_FLAG, '' ) AS VIRTUAL_FLAG ,
  COALESCE(PREVIOUS_HAND, '' ) AS PREVIOUS_HAND ,
  COALESCE(PAYMENT_DATE, '' ) AS PAYMENT_DATE ,
  COALESCE(POSTPONE_DAYS, 0 ) AS POSTPONE_DAYS ,
  COALESCE(PAYMENT_DAYS, 0 ) AS PAYMENT_DAYS ,
  COALESCE(BAN_ENDRSMT_MK, '' ) AS BAN_ENDRSMT_MK ,
  COALESCE(RPD_OPEN_DT, '' ) AS RPD_OPEN_DT ,
  COALESCE(RPD_DUE_DT, '' ) AS RPD_DUE_DT ,
  COALESCE(RPD_INTRATE, 0 ) AS RPD_INTRATE ,
  COALESCE(INTRST_RATE, 0 ) AS INTRST_RATE ,
  COALESCE(PAYMENT_MATURITY, 0 ) AS PAYMENT_MATURITY ,
  COALESCE(STTLM_MK, '' ) AS STTLM_MK ,
  COALESCE(REQ_REMARK, '' ) AS REQ_REMARK ,
  COALESCE(RCV_REMARK, '' ) AS RCV_REMARK ,
  COALESCE(PAYMENT_BY_BUYER, 0 ) AS PAYMENT_BY_BUYER ,
  COALESCE(PAY_AMOUNT, 0 ) AS PAY_AMOUNT ,
  COALESCE(RISK_FEES, 0 ) AS RISK_FEES ,
  COALESCE(CREDIT_LINE_ID, 0 ) AS CREDIT_LINE_ID ,
  COALESCE(CREDIT_LINE, 0 ) AS CREDIT_LINE ,
  COALESCE(APPLY_DATE, '' ) AS APPLY_DATE ,
  COALESCE(AOACCNINF_ACTNO, '' ) AS AOACCNINF_ACTNO ,
  COALESCE(AOACCNINF_UBANK, '' ) AS AOACCNINF_UBANK ,
  COALESCE(DSCNT_PROPS_ROLE, '' ) AS DSCNT_PROPS_ROLE ,
  COALESCE(DSCNT_PROPS_NAME, '' ) AS DSCNT_PROPS_NAME ,
  COALESCE(DSCNT_PROPS_CMONID, '' ) AS DSCNT_PROPS_CMONID ,
  COALESCE(DSCNT_PROPS_ACTNO, '' ) AS DSCNT_PROPS_ACTNO ,
  COALESCE(DSCNT_PROPS_UBANK, '' ) AS DSCNT_PROPS_UBANK ,
  COALESCE(DSCNT_PROPS_AGCY_UBANK, '' ) AS DSCNT_PROPS_AGCY_UBANK ,
  COALESCE(DSCNT_ROLE, '' ) AS DSCNT_ROLE ,
  COALESCE(DSCNT_CMONID, '' ) AS DSCNT_CMONID ,
  COALESCE(DSCNT_NAME, '' ) AS DSCNT_NAME ,
  COALESCE(DSCNT_ACTNO, '' ) AS DSCNT_ACTNO ,
  COALESCE(DSCNT_UBANK, '' ) AS DSCNT_UBANK ,
  COALESCE(CONTRACTNO, '' ) AS CONTRACTNO ,
  COALESCE(INVC_NB, '' ) AS INVC_NB ,
  COALESCE(BTCH_NO, '' ) AS BTCH_NO ,
  COALESCE(CREDIT_LINE_STATUS, '' ) AS CREDIT_LINE_STATUS ,
  COALESCE(ACCEPT_STATUS, '' ) AS ACCEPT_STATUS ,
  COALESCE(CHECK_STATUS, '' ) AS CHECK_STATUS ,
  COALESCE(QUERY_ORDER, 0 ) AS QUERY_ORDER ,
  COALESCE(QUERY_CONTENT, '' ) AS QUERY_CONTENT ,
  COALESCE(QUERY_TYPE, '' ) AS QUERY_TYPE ,
  COALESCE(CHECK_RESULT, '' ) AS CHECK_RESULT ,
  COALESCE(CHECK_CONTENT, '' ) AS CHECK_CONTENT ,
  COALESCE(QUERY_CHECK_ID, 0 ) AS QUERY_CHECK_ID ,
  COALESCE(FLAW_STATUS, '' ) AS FLAW_STATUS ,
  COALESCE(DISAFFIRM_STATUS, '' ) AS DISAFFIRM_STATUS ,
  COALESCE(RCV_PRXY_SGNTR, '' ) AS RCV_PRXY_SGNTR ,
  COALESCE(ACCOUNT_DATE, '' ) AS ACCOUNT_DATE ,
  COALESCE(ACCOUNT_FLAG, '' ) AS ACCOUNT_FLAG ,
  COALESCE(ACTLOG_ID, 0 ) AS ACTLOG_ID ,
  COALESCE(ACCOUNT, '' ) AS ACCOUNT ,
  COALESCE(ENDST_DATE, '' ) AS ENDST_DATE ,
  COALESCE(CANCEL_DATE, '' ) AS CANCEL_DATE ,
  COALESCE(INTEREST_STATUS, '' ) AS INTEREST_STATUS ,
  COALESCE(CALC_STATUS, '' ) AS CALC_STATUS ,
  COALESCE(BUY_STATUS, '' ) AS BUY_STATUS ,
  COALESCE(SIG_MK, '' ) AS SIG_MK ,
  COALESCE(CM_STATUS, '' ) AS CM_STATUS ,
  COALESCE(CM_ERR_PROCD, '' ) AS CM_ERR_PROCD ,
  COALESCE(ECDS_PRC_MSG, '' ) AS ECDS_PRC_MSG ,
  COALESCE(TRF_REF, '' ) AS TRF_REF ,
  COALESCE(TRF_ID, '' ) AS TRF_ID ,
  COALESCE(SWT_BIZ_ID, 0 ) AS SWT_BIZ_ID ,
  COALESCE(ENTITY_REGSTAT, '' ) AS ENTITY_REGSTAT ,
  COALESCE(ENTITY_REG_ID, 0 ) AS ENTITY_REG_ID ,
  COALESCE(VALUE1, '' ) AS VALUE1 ,
  COALESCE(MISC, '' ) AS MISC ,
  COALESCE(LAST_UPD_OPER_ID, 0 ) AS LAST_UPD_OPER_ID ,
  COALESCE(LAST_UPD_TIME, '' ) AS LAST_UPD_TIME ,
  COALESCE(INTR_OFFSET, 0 ) AS INTR_OFFSET 
 FROM  dw_tdata.BBS_001_BUY_DETAILS_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ID ,
  TASK_TYPE ,
  BUY_TYPE ,
  BUY_CONTRACT_ID ,
  DRAFT_ID ,
  BUYBIZ_TYPE ,
  CENTRAL_BANKFLG ,
  INNER_FLAG ,
  SAME_CITY_FLAG ,
  VIRTUAL_FLAG ,
  PREVIOUS_HAND ,
  PAYMENT_DATE ,
  POSTPONE_DAYS ,
  PAYMENT_DAYS ,
  BAN_ENDRSMT_MK ,
  RPD_OPEN_DT ,
  RPD_DUE_DT ,
  RPD_INTRATE ,
  INTRST_RATE ,
  PAYMENT_MATURITY ,
  STTLM_MK ,
  REQ_REMARK ,
  RCV_REMARK ,
  PAYMENT_BY_BUYER ,
  PAY_AMOUNT ,
  RISK_FEES ,
  CREDIT_LINE_ID ,
  CREDIT_LINE ,
  APPLY_DATE ,
  AOACCNINF_ACTNO ,
  AOACCNINF_UBANK ,
  DSCNT_PROPS_ROLE ,
  DSCNT_PROPS_NAME ,
  DSCNT_PROPS_CMONID ,
  DSCNT_PROPS_ACTNO ,
  DSCNT_PROPS_UBANK ,
  DSCNT_PROPS_AGCY_UBANK ,
  DSCNT_ROLE ,
  DSCNT_CMONID ,
  DSCNT_NAME ,
  DSCNT_ACTNO ,
  DSCNT_UBANK ,
  CONTRACTNO ,
  INVC_NB ,
  BTCH_NO ,
  CREDIT_LINE_STATUS ,
  ACCEPT_STATUS ,
  CHECK_STATUS ,
  QUERY_ORDER ,
  QUERY_CONTENT ,
  QUERY_TYPE ,
  CHECK_RESULT ,
  CHECK_CONTENT ,
  QUERY_CHECK_ID ,
  FLAW_STATUS ,
  DISAFFIRM_STATUS ,
  RCV_PRXY_SGNTR ,
  ACCOUNT_DATE ,
  ACCOUNT_FLAG ,
  ACTLOG_ID ,
  ACCOUNT ,
  ENDST_DATE ,
  CANCEL_DATE ,
  INTEREST_STATUS ,
  CALC_STATUS ,
  BUY_STATUS ,
  SIG_MK ,
  CM_STATUS ,
  CM_ERR_PROCD ,
  ECDS_PRC_MSG ,
  TRF_REF ,
  TRF_ID ,
  SWT_BIZ_ID ,
  ENTITY_REGSTAT ,
  ENTITY_REG_ID ,
  VALUE1 ,
  MISC ,
  LAST_UPD_OPER_ID ,
  LAST_UPD_TIME ,
  INTR_OFFSET 
 FROM dw_sdata.BBS_001_BUY_DETAILS 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ID = T.ID
WHERE
(T.ID IS NULL)
 OR N.TASK_TYPE<>T.TASK_TYPE
 OR N.BUY_TYPE<>T.BUY_TYPE
 OR N.BUY_CONTRACT_ID<>T.BUY_CONTRACT_ID
 OR N.DRAFT_ID<>T.DRAFT_ID
 OR N.BUYBIZ_TYPE<>T.BUYBIZ_TYPE
 OR N.CENTRAL_BANKFLG<>T.CENTRAL_BANKFLG
 OR N.INNER_FLAG<>T.INNER_FLAG
 OR N.SAME_CITY_FLAG<>T.SAME_CITY_FLAG
 OR N.VIRTUAL_FLAG<>T.VIRTUAL_FLAG
 OR N.PREVIOUS_HAND<>T.PREVIOUS_HAND
 OR N.PAYMENT_DATE<>T.PAYMENT_DATE
 OR N.POSTPONE_DAYS<>T.POSTPONE_DAYS
 OR N.PAYMENT_DAYS<>T.PAYMENT_DAYS
 OR N.BAN_ENDRSMT_MK<>T.BAN_ENDRSMT_MK
 OR N.RPD_OPEN_DT<>T.RPD_OPEN_DT
 OR N.RPD_DUE_DT<>T.RPD_DUE_DT
 OR N.RPD_INTRATE<>T.RPD_INTRATE
 OR N.INTRST_RATE<>T.INTRST_RATE
 OR N.PAYMENT_MATURITY<>T.PAYMENT_MATURITY
 OR N.STTLM_MK<>T.STTLM_MK
 OR N.REQ_REMARK<>T.REQ_REMARK
 OR N.RCV_REMARK<>T.RCV_REMARK
 OR N.PAYMENT_BY_BUYER<>T.PAYMENT_BY_BUYER
 OR N.PAY_AMOUNT<>T.PAY_AMOUNT
 OR N.RISK_FEES<>T.RISK_FEES
 OR N.CREDIT_LINE_ID<>T.CREDIT_LINE_ID
 OR N.CREDIT_LINE<>T.CREDIT_LINE
 OR N.APPLY_DATE<>T.APPLY_DATE
 OR N.AOACCNINF_ACTNO<>T.AOACCNINF_ACTNO
 OR N.AOACCNINF_UBANK<>T.AOACCNINF_UBANK
 OR N.DSCNT_PROPS_ROLE<>T.DSCNT_PROPS_ROLE
 OR N.DSCNT_PROPS_NAME<>T.DSCNT_PROPS_NAME
 OR N.DSCNT_PROPS_CMONID<>T.DSCNT_PROPS_CMONID
 OR N.DSCNT_PROPS_ACTNO<>T.DSCNT_PROPS_ACTNO
 OR N.DSCNT_PROPS_UBANK<>T.DSCNT_PROPS_UBANK
 OR N.DSCNT_PROPS_AGCY_UBANK<>T.DSCNT_PROPS_AGCY_UBANK
 OR N.DSCNT_ROLE<>T.DSCNT_ROLE
 OR N.DSCNT_CMONID<>T.DSCNT_CMONID
 OR N.DSCNT_NAME<>T.DSCNT_NAME
 OR N.DSCNT_ACTNO<>T.DSCNT_ACTNO
 OR N.DSCNT_UBANK<>T.DSCNT_UBANK
 OR N.CONTRACTNO<>T.CONTRACTNO
 OR N.INVC_NB<>T.INVC_NB
 OR N.BTCH_NO<>T.BTCH_NO
 OR N.CREDIT_LINE_STATUS<>T.CREDIT_LINE_STATUS
 OR N.ACCEPT_STATUS<>T.ACCEPT_STATUS
 OR N.CHECK_STATUS<>T.CHECK_STATUS
 OR N.QUERY_ORDER<>T.QUERY_ORDER
 OR N.QUERY_CONTENT<>T.QUERY_CONTENT
 OR N.QUERY_TYPE<>T.QUERY_TYPE
 OR N.CHECK_RESULT<>T.CHECK_RESULT
 OR N.CHECK_CONTENT<>T.CHECK_CONTENT
 OR N.QUERY_CHECK_ID<>T.QUERY_CHECK_ID
 OR N.FLAW_STATUS<>T.FLAW_STATUS
 OR N.DISAFFIRM_STATUS<>T.DISAFFIRM_STATUS
 OR N.RCV_PRXY_SGNTR<>T.RCV_PRXY_SGNTR
 OR N.ACCOUNT_DATE<>T.ACCOUNT_DATE
 OR N.ACCOUNT_FLAG<>T.ACCOUNT_FLAG
 OR N.ACTLOG_ID<>T.ACTLOG_ID
 OR N.ACCOUNT<>T.ACCOUNT
 OR N.ENDST_DATE<>T.ENDST_DATE
 OR N.CANCEL_DATE<>T.CANCEL_DATE
 OR N.INTEREST_STATUS<>T.INTEREST_STATUS
 OR N.CALC_STATUS<>T.CALC_STATUS
 OR N.BUY_STATUS<>T.BUY_STATUS
 OR N.SIG_MK<>T.SIG_MK
 OR N.CM_STATUS<>T.CM_STATUS
 OR N.CM_ERR_PROCD<>T.CM_ERR_PROCD
 OR N.ECDS_PRC_MSG<>T.ECDS_PRC_MSG
 OR N.TRF_REF<>T.TRF_REF
 OR N.TRF_ID<>T.TRF_ID
 OR N.SWT_BIZ_ID<>T.SWT_BIZ_ID
 OR N.ENTITY_REGSTAT<>T.ENTITY_REGSTAT
 OR N.ENTITY_REG_ID<>T.ENTITY_REG_ID
 OR N.VALUE1<>T.VALUE1
 OR N.MISC<>T.MISC
 OR N.LAST_UPD_OPER_ID<>T.LAST_UPD_OPER_ID
 OR N.LAST_UPD_TIME<>T.LAST_UPD_TIME
 OR N.INTR_OFFSET<>T.INTR_OFFSET
;

--Step3:
UPDATE dw_sdata.BBS_001_BUY_DETAILS P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_41
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ID=T_41.ID
;

--Step4:
INSERT  INTO dw_sdata.BBS_001_BUY_DETAILS SELECT * FROM T_41;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
