#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.BBS_001_DRAFT_INFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.BBS_001_DRAFT_INFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_48 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.BBS_001_DRAFT_INFO WHERE 1=0;

--Step2:
INSERT  INTO T_48 (
  ID,
  DRAFT_NUMBER,
  VOUCHER_NO,
  DRAFT_CLASS,
  DRAFT_TERM,
  DFCLS_CTL,
  SRC_TYPE,
  BUY_CONTRACT_ID,
  END_OR_SEMENT_MK,
  DRAFT_ATTR,
  DRAFT_TYPE,
  REMIT_DATE,
  MATURITY_DATE,
  REMITTER_ID,
  REMITTER_ROLE,
  REMITTER_CMONID,
  REMITTER_NAME,
  REMITTER_ACCOUNT,
  REMITTER_BANK_ID,
  REMITTER_BANK_NAME,
  ACCEPTOR_ROLE,
  ACCEPTOR,
  ACCEPTOR_BANK_ID,
  ACCEPTOR_ACTNO,
  ACCEPTOR_BANK_NAME,
  PAYEE_NAME,
  PAYEE_ACCOUNT,
  PAYEE_BANK_ID,
  PAYEE_BANK_NAME,
  PAYEE_ID,
  PAYEE_ORGAN_CODE,
  FACE_AMOUNT,
  DRAWER_BANK_FLAG,
  BELONG_BRANCH_ID,
  STORE_STATUS,
  STATUS,
  TMP_STATUS,
  COLLZTN_STATUS,
  COLLZTN_ID,
  LOSS_STATUS,
  RPLOSS_ID,
  DEBIT_ORDER,
  MISC,
  LAST_UPD_OPER_ID,
  LAST_UPD_TIME,
  DRFT_REMARK,
  DF_DRWR_CDTRATGS,
  DF_DRWR_CDTRATGSAGCY,
  DF_DRWR_CDTRATGDUEDT,
  FASTENER_CUSTACC_STATUS,
  ACCEPTOR_BANK_NO,
  FASTENER_DATE,
  FASTENER_AMOUNT,
  RETURN_BILL_STATUS,
  DISC_OVERDUE_STATUS,
  ENDORSE_BANK_CATE_ID,
  PAY_CUST_BANK_ACCOUNT,
  PAY_CUST_NAME,
  ACCEPT_CUST_ID,
  ACCEPT_CUST_NO,
  FREEZE_STATUS,
  FLAG_PRINT,
  FLAG_PHOTO,
  FLAG_UPLOAD,
  APU_FLAG_UPLOAD,
  ALL_KEY,
  start_dt,
  end_dt)
SELECT
  N.ID,
  N.DRAFT_NUMBER,
  N.VOUCHER_NO,
  N.DRAFT_CLASS,
  N.DRAFT_TERM,
  N.DFCLS_CTL,
  N.SRC_TYPE,
  N.BUY_CONTRACT_ID,
  N.END_OR_SEMENT_MK,
  N.DRAFT_ATTR,
  N.DRAFT_TYPE,
  N.REMIT_DATE,
  N.MATURITY_DATE,
  N.REMITTER_ID,
  N.REMITTER_ROLE,
  N.REMITTER_CMONID,
  N.REMITTER_NAME,
  N.REMITTER_ACCOUNT,
  N.REMITTER_BANK_ID,
  N.REMITTER_BANK_NAME,
  N.ACCEPTOR_ROLE,
  N.ACCEPTOR,
  N.ACCEPTOR_BANK_ID,
  N.ACCEPTOR_ACTNO,
  N.ACCEPTOR_BANK_NAME,
  N.PAYEE_NAME,
  N.PAYEE_ACCOUNT,
  N.PAYEE_BANK_ID,
  N.PAYEE_BANK_NAME,
  N.PAYEE_ID,
  N.PAYEE_ORGAN_CODE,
  N.FACE_AMOUNT,
  N.DRAWER_BANK_FLAG,
  N.BELONG_BRANCH_ID,
  N.STORE_STATUS,
  N.STATUS,
  N.TMP_STATUS,
  N.COLLZTN_STATUS,
  N.COLLZTN_ID,
  N.LOSS_STATUS,
  N.RPLOSS_ID,
  N.DEBIT_ORDER,
  N.MISC,
  N.LAST_UPD_OPER_ID,
  N.LAST_UPD_TIME,
  N.DRFT_REMARK,
  N.DF_DRWR_CDTRATGS,
  N.DF_DRWR_CDTRATGSAGCY,
  N.DF_DRWR_CDTRATGDUEDT,
  N.FASTENER_CUSTACC_STATUS,
  N.ACCEPTOR_BANK_NO,
  N.FASTENER_DATE,
  N.FASTENER_AMOUNT,
  N.RETURN_BILL_STATUS,
  N.DISC_OVERDUE_STATUS,
  N.ENDORSE_BANK_CATE_ID,
  N.PAY_CUST_BANK_ACCOUNT,
  N.PAY_CUST_NAME,
  N.ACCEPT_CUST_ID,
  N.ACCEPT_CUST_NO,
  N.FREEZE_STATUS,
  N.FLAG_PRINT,
  N.FLAG_PHOTO,
  N.FLAG_UPLOAD,
  N.APU_FLAG_UPLOAD,
  N.ALL_KEY,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ID, 0 ) AS ID ,
  COALESCE(DRAFT_NUMBER, '' ) AS DRAFT_NUMBER ,
  COALESCE(VOUCHER_NO, '' ) AS VOUCHER_NO ,
  COALESCE(DRAFT_CLASS, '' ) AS DRAFT_CLASS ,
  COALESCE(DRAFT_TERM, '' ) AS DRAFT_TERM ,
  COALESCE(DFCLS_CTL, '' ) AS DFCLS_CTL ,
  COALESCE(SRC_TYPE, '' ) AS SRC_TYPE ,
  COALESCE(BUY_CONTRACT_ID, 0 ) AS BUY_CONTRACT_ID ,
  COALESCE(END_OR_SEMENT_MK, '' ) AS END_OR_SEMENT_MK ,
  COALESCE(DRAFT_ATTR, '' ) AS DRAFT_ATTR ,
  COALESCE(DRAFT_TYPE, '' ) AS DRAFT_TYPE ,
  COALESCE(REMIT_DATE, '' ) AS REMIT_DATE ,
  COALESCE(MATURITY_DATE, '' ) AS MATURITY_DATE ,
  COALESCE(REMITTER_ID, 0 ) AS REMITTER_ID ,
  COALESCE(REMITTER_ROLE, '' ) AS REMITTER_ROLE ,
  COALESCE(REMITTER_CMONID, '' ) AS REMITTER_CMONID ,
  COALESCE(REMITTER_NAME, '' ) AS REMITTER_NAME ,
  COALESCE(REMITTER_ACCOUNT, '' ) AS REMITTER_ACCOUNT ,
  COALESCE(REMITTER_BANK_ID, 0 ) AS REMITTER_BANK_ID ,
  COALESCE(REMITTER_BANK_NAME, '' ) AS REMITTER_BANK_NAME ,
  COALESCE(ACCEPTOR_ROLE, '' ) AS ACCEPTOR_ROLE ,
  COALESCE(ACCEPTOR, '' ) AS ACCEPTOR ,
  COALESCE(ACCEPTOR_BANK_ID, 0 ) AS ACCEPTOR_BANK_ID ,
  COALESCE(ACCEPTOR_ACTNO, '' ) AS ACCEPTOR_ACTNO ,
  COALESCE(ACCEPTOR_BANK_NAME, '' ) AS ACCEPTOR_BANK_NAME ,
  COALESCE(PAYEE_NAME, '' ) AS PAYEE_NAME ,
  COALESCE(PAYEE_ACCOUNT, '' ) AS PAYEE_ACCOUNT ,
  COALESCE(PAYEE_BANK_ID, 0 ) AS PAYEE_BANK_ID ,
  COALESCE(PAYEE_BANK_NAME, '' ) AS PAYEE_BANK_NAME ,
  COALESCE(PAYEE_ID, 0 ) AS PAYEE_ID ,
  COALESCE(PAYEE_ORGAN_CODE, '' ) AS PAYEE_ORGAN_CODE ,
  COALESCE(FACE_AMOUNT, 0 ) AS FACE_AMOUNT ,
  COALESCE(DRAWER_BANK_FLAG, '' ) AS DRAWER_BANK_FLAG ,
  COALESCE(BELONG_BRANCH_ID, 0 ) AS BELONG_BRANCH_ID ,
  COALESCE(STORE_STATUS, '' ) AS STORE_STATUS ,
  COALESCE(STATUS, '' ) AS STATUS ,
  COALESCE(TMP_STATUS, '' ) AS TMP_STATUS ,
  COALESCE(COLLZTN_STATUS, '' ) AS COLLZTN_STATUS ,
  COALESCE(COLLZTN_ID, 0 ) AS COLLZTN_ID ,
  COALESCE(LOSS_STATUS, '' ) AS LOSS_STATUS ,
  COALESCE(RPLOSS_ID, 0 ) AS RPLOSS_ID ,
  COALESCE(DEBIT_ORDER, '' ) AS DEBIT_ORDER ,
  COALESCE(MISC, '' ) AS MISC ,
  COALESCE(LAST_UPD_OPER_ID, 0 ) AS LAST_UPD_OPER_ID ,
  COALESCE(LAST_UPD_TIME, '' ) AS LAST_UPD_TIME ,
  COALESCE(DRFT_REMARK, '' ) AS DRFT_REMARK ,
  COALESCE(DF_DRWR_CDTRATGS, '' ) AS DF_DRWR_CDTRATGS ,
  COALESCE(DF_DRWR_CDTRATGSAGCY, '' ) AS DF_DRWR_CDTRATGSAGCY ,
  COALESCE(DF_DRWR_CDTRATGDUEDT, '' ) AS DF_DRWR_CDTRATGDUEDT ,
  COALESCE(FASTENER_CUSTACC_STATUS, '' ) AS FASTENER_CUSTACC_STATUS ,
  COALESCE(ACCEPTOR_BANK_NO, '' ) AS ACCEPTOR_BANK_NO ,
  COALESCE(FASTENER_DATE, '' ) AS FASTENER_DATE ,
  COALESCE(FASTENER_AMOUNT, 0 ) AS FASTENER_AMOUNT ,
  COALESCE(RETURN_BILL_STATUS, '' ) AS RETURN_BILL_STATUS ,
  COALESCE(DISC_OVERDUE_STATUS, '' ) AS DISC_OVERDUE_STATUS ,
  COALESCE(ENDORSE_BANK_CATE_ID, '' ) AS ENDORSE_BANK_CATE_ID ,
  COALESCE(PAY_CUST_BANK_ACCOUNT, '' ) AS PAY_CUST_BANK_ACCOUNT ,
  COALESCE(PAY_CUST_NAME, '' ) AS PAY_CUST_NAME ,
  COALESCE(ACCEPT_CUST_ID, 0 ) AS ACCEPT_CUST_ID ,
  COALESCE(ACCEPT_CUST_NO, '' ) AS ACCEPT_CUST_NO ,
  COALESCE(FREEZE_STATUS, '' ) AS FREEZE_STATUS ,
  COALESCE(FLAG_PRINT, '' ) AS FLAG_PRINT ,
  COALESCE(FLAG_PHOTO, '' ) AS FLAG_PHOTO ,
  COALESCE(FLAG_UPLOAD, '' ) AS FLAG_UPLOAD ,
  COALESCE(APU_FLAG_UPLOAD, '' ) AS APU_FLAG_UPLOAD ,
  COALESCE(ALL_KEY, '' ) AS ALL_KEY 
 FROM  dw_tdata.BBS_001_DRAFT_INFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ID ,
  DRAFT_NUMBER ,
  VOUCHER_NO ,
  DRAFT_CLASS ,
  DRAFT_TERM ,
  DFCLS_CTL ,
  SRC_TYPE ,
  BUY_CONTRACT_ID ,
  END_OR_SEMENT_MK ,
  DRAFT_ATTR ,
  DRAFT_TYPE ,
  REMIT_DATE ,
  MATURITY_DATE ,
  REMITTER_ID ,
  REMITTER_ROLE ,
  REMITTER_CMONID ,
  REMITTER_NAME ,
  REMITTER_ACCOUNT ,
  REMITTER_BANK_ID ,
  REMITTER_BANK_NAME ,
  ACCEPTOR_ROLE ,
  ACCEPTOR ,
  ACCEPTOR_BANK_ID ,
  ACCEPTOR_ACTNO ,
  ACCEPTOR_BANK_NAME ,
  PAYEE_NAME ,
  PAYEE_ACCOUNT ,
  PAYEE_BANK_ID ,
  PAYEE_BANK_NAME ,
  PAYEE_ID ,
  PAYEE_ORGAN_CODE ,
  FACE_AMOUNT ,
  DRAWER_BANK_FLAG ,
  BELONG_BRANCH_ID ,
  STORE_STATUS ,
  STATUS ,
  TMP_STATUS ,
  COLLZTN_STATUS ,
  COLLZTN_ID ,
  LOSS_STATUS ,
  RPLOSS_ID ,
  DEBIT_ORDER ,
  MISC ,
  LAST_UPD_OPER_ID ,
  LAST_UPD_TIME ,
  DRFT_REMARK ,
  DF_DRWR_CDTRATGS ,
  DF_DRWR_CDTRATGSAGCY ,
  DF_DRWR_CDTRATGDUEDT ,
  FASTENER_CUSTACC_STATUS ,
  ACCEPTOR_BANK_NO ,
  FASTENER_DATE ,
  FASTENER_AMOUNT ,
  RETURN_BILL_STATUS ,
  DISC_OVERDUE_STATUS ,
  ENDORSE_BANK_CATE_ID ,
  PAY_CUST_BANK_ACCOUNT ,
  PAY_CUST_NAME ,
  ACCEPT_CUST_ID ,
  ACCEPT_CUST_NO ,
  FREEZE_STATUS ,
  FLAG_PRINT ,
  FLAG_PHOTO ,
  FLAG_UPLOAD ,
  APU_FLAG_UPLOAD ,
  ALL_KEY 
 FROM dw_sdata.BBS_001_DRAFT_INFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ID = T.ID
WHERE
(T.ID IS NULL)
 OR N.DRAFT_NUMBER<>T.DRAFT_NUMBER
 OR N.VOUCHER_NO<>T.VOUCHER_NO
 OR N.DRAFT_CLASS<>T.DRAFT_CLASS
 OR N.DRAFT_TERM<>T.DRAFT_TERM
 OR N.DFCLS_CTL<>T.DFCLS_CTL
 OR N.SRC_TYPE<>T.SRC_TYPE
 OR N.BUY_CONTRACT_ID<>T.BUY_CONTRACT_ID
 OR N.END_OR_SEMENT_MK<>T.END_OR_SEMENT_MK
 OR N.DRAFT_ATTR<>T.DRAFT_ATTR
 OR N.DRAFT_TYPE<>T.DRAFT_TYPE
 OR N.REMIT_DATE<>T.REMIT_DATE
 OR N.MATURITY_DATE<>T.MATURITY_DATE
 OR N.REMITTER_ID<>T.REMITTER_ID
 OR N.REMITTER_ROLE<>T.REMITTER_ROLE
 OR N.REMITTER_CMONID<>T.REMITTER_CMONID
 OR N.REMITTER_NAME<>T.REMITTER_NAME
 OR N.REMITTER_ACCOUNT<>T.REMITTER_ACCOUNT
 OR N.REMITTER_BANK_ID<>T.REMITTER_BANK_ID
 OR N.REMITTER_BANK_NAME<>T.REMITTER_BANK_NAME
 OR N.ACCEPTOR_ROLE<>T.ACCEPTOR_ROLE
 OR N.ACCEPTOR<>T.ACCEPTOR
 OR N.ACCEPTOR_BANK_ID<>T.ACCEPTOR_BANK_ID
 OR N.ACCEPTOR_ACTNO<>T.ACCEPTOR_ACTNO
 OR N.ACCEPTOR_BANK_NAME<>T.ACCEPTOR_BANK_NAME
 OR N.PAYEE_NAME<>T.PAYEE_NAME
 OR N.PAYEE_ACCOUNT<>T.PAYEE_ACCOUNT
 OR N.PAYEE_BANK_ID<>T.PAYEE_BANK_ID
 OR N.PAYEE_BANK_NAME<>T.PAYEE_BANK_NAME
 OR N.PAYEE_ID<>T.PAYEE_ID
 OR N.PAYEE_ORGAN_CODE<>T.PAYEE_ORGAN_CODE
 OR N.FACE_AMOUNT<>T.FACE_AMOUNT
 OR N.DRAWER_BANK_FLAG<>T.DRAWER_BANK_FLAG
 OR N.BELONG_BRANCH_ID<>T.BELONG_BRANCH_ID
 OR N.STORE_STATUS<>T.STORE_STATUS
 OR N.STATUS<>T.STATUS
 OR N.TMP_STATUS<>T.TMP_STATUS
 OR N.COLLZTN_STATUS<>T.COLLZTN_STATUS
 OR N.COLLZTN_ID<>T.COLLZTN_ID
 OR N.LOSS_STATUS<>T.LOSS_STATUS
 OR N.RPLOSS_ID<>T.RPLOSS_ID
 OR N.DEBIT_ORDER<>T.DEBIT_ORDER
 OR N.MISC<>T.MISC
 OR N.LAST_UPD_OPER_ID<>T.LAST_UPD_OPER_ID
 OR N.LAST_UPD_TIME<>T.LAST_UPD_TIME
 OR N.DRFT_REMARK<>T.DRFT_REMARK
 OR N.DF_DRWR_CDTRATGS<>T.DF_DRWR_CDTRATGS
 OR N.DF_DRWR_CDTRATGSAGCY<>T.DF_DRWR_CDTRATGSAGCY
 OR N.DF_DRWR_CDTRATGDUEDT<>T.DF_DRWR_CDTRATGDUEDT
 OR N.FASTENER_CUSTACC_STATUS<>T.FASTENER_CUSTACC_STATUS
 OR N.ACCEPTOR_BANK_NO<>T.ACCEPTOR_BANK_NO
 OR N.FASTENER_DATE<>T.FASTENER_DATE
 OR N.FASTENER_AMOUNT<>T.FASTENER_AMOUNT
 OR N.RETURN_BILL_STATUS<>T.RETURN_BILL_STATUS
 OR N.DISC_OVERDUE_STATUS<>T.DISC_OVERDUE_STATUS
 OR N.ENDORSE_BANK_CATE_ID<>T.ENDORSE_BANK_CATE_ID
 OR N.PAY_CUST_BANK_ACCOUNT<>T.PAY_CUST_BANK_ACCOUNT
 OR N.PAY_CUST_NAME<>T.PAY_CUST_NAME
 OR N.ACCEPT_CUST_ID<>T.ACCEPT_CUST_ID
 OR N.ACCEPT_CUST_NO<>T.ACCEPT_CUST_NO
 OR N.FREEZE_STATUS<>T.FREEZE_STATUS
 OR N.FLAG_PRINT<>T.FLAG_PRINT
 OR N.FLAG_PHOTO<>T.FLAG_PHOTO
 OR N.FLAG_UPLOAD<>T.FLAG_UPLOAD
 OR N.APU_FLAG_UPLOAD<>T.APU_FLAG_UPLOAD
 OR N.ALL_KEY<>T.ALL_KEY
;

--Step3:
UPDATE dw_sdata.BBS_001_DRAFT_INFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_48
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ID=T_48.ID
;

--Step4:
INSERT  INTO dw_sdata.BBS_001_DRAFT_INFO SELECT * FROM T_48;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
