#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.BBS_001_ACCEPT_CONTRACT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.BBS_001_ACCEPT_CONTRACT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_32 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.BBS_001_ACCEPT_CONTRACT WHERE 1=0;

--Step2:
INSERT  INTO T_32 (
  ID,
  BRANCH_ID,
  ACCEPT_PROTOCOL_NO,
  WEBBANK_CONTRACT_ID,
  TASK_TYPE,
  DRAFT_ATTR,
  DRAFT_TYPE,
  REMITTER_CUST_ID,
  APPLY_ACCEPT_AMOUNT,
  APPLY_REMIT_DATE,
  MATURITY_DATE,
  APPLY_REASON,
  FIRST_REPAYMENT_ACCT,
  SECOND_REPAYMENT_ACCT,
  CREDIT_FEE_SCALE,
  BAIL_SCALE,
  CHARGE_SCALE,
  TRANS_AMOUNT,
  DRAWEE_BANK_ID,
  MANAGER_ID,
  DEPART_ID,
  OPERATOR_ID,
  TXN_DATE,
  CONTRACT_STATUS,
  LOGIC_CHECK_STATUS,
  AUDIT_STATUS,
  CREDIT_CHECK_STATUS,
  DATA_SOURCE_TYPE,
  MISC,
  APPNO,
  LAST_UPD_OPER_ID,
  LAST_UPD_TIME,
  POUNDAGE,
  OPEN_CONSENT_CHARGE,
  IMPAWN_PROTOCOL_NO,
  ALLAY_MONEY_PROTOCOL_NO,
  ACCT_BANK_BR_CODE,
  CHILD_ACCT,
  FILE_NAME,
  BAIL_BOUNDED_STATUS,
  ACCT_NAME,
  COLLATERAL_SCALE,
  LOW_RISK,
  ACCEPT_TYPE,
  BAIL_SRC,
  BENEFIT_NUMBER_ONE,
  BENEFIT_NUMBER_TWO,
  MANAGER_ONE,
  MANAGER_TWO,
  BRHID_IN_ONE,
  BRHID_IN_TWO,
  INCOME_PERCENT_ONE,
  INCOME_PERCENT_TWO,
  ACTURALLY_INDUSTY,
  GROUP_FLAG,
  APPNO_DRA,
  DRAFT_CHANGE_STATUS,
  PLEDGE_SCALE,
  PLEDGE_DRAFT,
  PLEDGE_CASH,
  ACCEPT_CORE_ACCOUNT,
  ENT_BANK_STATUS,
  VOLUME_OCCUPANT,
  PARENT_COMPANY_CUST_NO,
  CORE_ENTERPRISE_ACCOUNT,
  REMIT_DRAFT_PRINT_COUNT,
  start_dt,
  end_dt)
SELECT
  N.ID,
  N.BRANCH_ID,
  N.ACCEPT_PROTOCOL_NO,
  N.WEBBANK_CONTRACT_ID,
  N.TASK_TYPE,
  N.DRAFT_ATTR,
  N.DRAFT_TYPE,
  N.REMITTER_CUST_ID,
  N.APPLY_ACCEPT_AMOUNT,
  N.APPLY_REMIT_DATE,
  N.MATURITY_DATE,
  N.APPLY_REASON,
  N.FIRST_REPAYMENT_ACCT,
  N.SECOND_REPAYMENT_ACCT,
  N.CREDIT_FEE_SCALE,
  N.BAIL_SCALE,
  N.CHARGE_SCALE,
  N.TRANS_AMOUNT,
  N.DRAWEE_BANK_ID,
  N.MANAGER_ID,
  N.DEPART_ID,
  N.OPERATOR_ID,
  N.TXN_DATE,
  N.CONTRACT_STATUS,
  N.LOGIC_CHECK_STATUS,
  N.AUDIT_STATUS,
  N.CREDIT_CHECK_STATUS,
  N.DATA_SOURCE_TYPE,
  N.MISC,
  N.APPNO,
  N.LAST_UPD_OPER_ID,
  N.LAST_UPD_TIME,
  N.POUNDAGE,
  N.OPEN_CONSENT_CHARGE,
  N.IMPAWN_PROTOCOL_NO,
  N.ALLAY_MONEY_PROTOCOL_NO,
  N.ACCT_BANK_BR_CODE,
  N.CHILD_ACCT,
  N.FILE_NAME,
  N.BAIL_BOUNDED_STATUS,
  N.ACCT_NAME,
  N.COLLATERAL_SCALE,
  N.LOW_RISK,
  N.ACCEPT_TYPE,
  N.BAIL_SRC,
  N.BENEFIT_NUMBER_ONE,
  N.BENEFIT_NUMBER_TWO,
  N.MANAGER_ONE,
  N.MANAGER_TWO,
  N.BRHID_IN_ONE,
  N.BRHID_IN_TWO,
  N.INCOME_PERCENT_ONE,
  N.INCOME_PERCENT_TWO,
  N.ACTURALLY_INDUSTY,
  N.GROUP_FLAG,
  N.APPNO_DRA,
  N.DRAFT_CHANGE_STATUS,
  N.PLEDGE_SCALE,
  N.PLEDGE_DRAFT,
  N.PLEDGE_CASH,
  N.ACCEPT_CORE_ACCOUNT,
  N.ENT_BANK_STATUS,
  N.VOLUME_OCCUPANT,
  N.PARENT_COMPANY_CUST_NO,
  N.CORE_ENTERPRISE_ACCOUNT,
  N.REMIT_DRAFT_PRINT_COUNT,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ID, 0 ) AS ID ,
  COALESCE(BRANCH_ID, 0 ) AS BRANCH_ID ,
  COALESCE(ACCEPT_PROTOCOL_NO, '' ) AS ACCEPT_PROTOCOL_NO ,
  COALESCE(WEBBANK_CONTRACT_ID, 0 ) AS WEBBANK_CONTRACT_ID ,
  COALESCE(TASK_TYPE, '' ) AS TASK_TYPE ,
  COALESCE(DRAFT_ATTR, '' ) AS DRAFT_ATTR ,
  COALESCE(DRAFT_TYPE, '' ) AS DRAFT_TYPE ,
  COALESCE(REMITTER_CUST_ID, 0 ) AS REMITTER_CUST_ID ,
  COALESCE(APPLY_ACCEPT_AMOUNT, 0 ) AS APPLY_ACCEPT_AMOUNT ,
  COALESCE(APPLY_REMIT_DATE, '' ) AS APPLY_REMIT_DATE ,
  COALESCE(MATURITY_DATE, '' ) AS MATURITY_DATE ,
  COALESCE(APPLY_REASON, '' ) AS APPLY_REASON ,
  COALESCE(FIRST_REPAYMENT_ACCT, '' ) AS FIRST_REPAYMENT_ACCT ,
  COALESCE(SECOND_REPAYMENT_ACCT, '' ) AS SECOND_REPAYMENT_ACCT ,
  COALESCE(CREDIT_FEE_SCALE, 0 ) AS CREDIT_FEE_SCALE ,
  COALESCE(BAIL_SCALE, 0 ) AS BAIL_SCALE ,
  COALESCE(CHARGE_SCALE, 0 ) AS CHARGE_SCALE ,
  COALESCE(TRANS_AMOUNT, 0 ) AS TRANS_AMOUNT ,
  COALESCE(DRAWEE_BANK_ID, 0 ) AS DRAWEE_BANK_ID ,
  COALESCE(MANAGER_ID, 0 ) AS MANAGER_ID ,
  COALESCE(DEPART_ID, 0 ) AS DEPART_ID ,
  COALESCE(OPERATOR_ID, 0 ) AS OPERATOR_ID ,
  COALESCE(TXN_DATE, '' ) AS TXN_DATE ,
  COALESCE(CONTRACT_STATUS, '' ) AS CONTRACT_STATUS ,
  COALESCE(LOGIC_CHECK_STATUS, '' ) AS LOGIC_CHECK_STATUS ,
  COALESCE(AUDIT_STATUS, '' ) AS AUDIT_STATUS ,
  COALESCE(CREDIT_CHECK_STATUS, '' ) AS CREDIT_CHECK_STATUS ,
  COALESCE(DATA_SOURCE_TYPE, '' ) AS DATA_SOURCE_TYPE ,
  COALESCE(MISC, '' ) AS MISC ,
  COALESCE(APPNO, '' ) AS APPNO ,
  COALESCE(LAST_UPD_OPER_ID, 0 ) AS LAST_UPD_OPER_ID ,
  COALESCE(LAST_UPD_TIME, '' ) AS LAST_UPD_TIME ,
  COALESCE(POUNDAGE, 0 ) AS POUNDAGE ,
  COALESCE(OPEN_CONSENT_CHARGE, 0 ) AS OPEN_CONSENT_CHARGE ,
  COALESCE(IMPAWN_PROTOCOL_NO, '' ) AS IMPAWN_PROTOCOL_NO ,
  COALESCE(ALLAY_MONEY_PROTOCOL_NO, '' ) AS ALLAY_MONEY_PROTOCOL_NO ,
  COALESCE(ACCT_BANK_BR_CODE, '' ) AS ACCT_BANK_BR_CODE ,
  COALESCE(CHILD_ACCT, '' ) AS CHILD_ACCT ,
  COALESCE(FILE_NAME, '' ) AS FILE_NAME ,
  COALESCE(BAIL_BOUNDED_STATUS, '' ) AS BAIL_BOUNDED_STATUS ,
  COALESCE(ACCT_NAME, '' ) AS ACCT_NAME ,
  COALESCE(COLLATERAL_SCALE, 0 ) AS COLLATERAL_SCALE ,
  COALESCE(LOW_RISK, '' ) AS LOW_RISK ,
  COALESCE(ACCEPT_TYPE, '' ) AS ACCEPT_TYPE ,
  COALESCE(BAIL_SRC, '' ) AS BAIL_SRC ,
  COALESCE(BENEFIT_NUMBER_ONE, 0 ) AS BENEFIT_NUMBER_ONE ,
  COALESCE(BENEFIT_NUMBER_TWO, 0 ) AS BENEFIT_NUMBER_TWO ,
  COALESCE(MANAGER_ONE, 0 ) AS MANAGER_ONE ,
  COALESCE(MANAGER_TWO, 0 ) AS MANAGER_TWO ,
  COALESCE(BRHID_IN_ONE, 0 ) AS BRHID_IN_ONE ,
  COALESCE(BRHID_IN_TWO, 0 ) AS BRHID_IN_TWO ,
  COALESCE(INCOME_PERCENT_ONE, 0 ) AS INCOME_PERCENT_ONE ,
  COALESCE(INCOME_PERCENT_TWO, 0 ) AS INCOME_PERCENT_TWO ,
  COALESCE(ACTURALLY_INDUSTY, '' ) AS ACTURALLY_INDUSTY ,
  COALESCE(GROUP_FLAG, '' ) AS GROUP_FLAG ,
  COALESCE(APPNO_DRA, '' ) AS APPNO_DRA ,
  COALESCE(DRAFT_CHANGE_STATUS, '' ) AS DRAFT_CHANGE_STATUS ,
  COALESCE(PLEDGE_SCALE, 0 ) AS PLEDGE_SCALE ,
  COALESCE(PLEDGE_DRAFT, 0 ) AS PLEDGE_DRAFT ,
  COALESCE(PLEDGE_CASH, 0 ) AS PLEDGE_CASH ,
  COALESCE(ACCEPT_CORE_ACCOUNT, 0 ) AS ACCEPT_CORE_ACCOUNT ,
  COALESCE(ENT_BANK_STATUS, '' ) AS ENT_BANK_STATUS ,
  COALESCE(VOLUME_OCCUPANT, '' ) AS VOLUME_OCCUPANT ,
  COALESCE(PARENT_COMPANY_CUST_NO, '' ) AS PARENT_COMPANY_CUST_NO ,
  COALESCE(CORE_ENTERPRISE_ACCOUNT, '' ) AS CORE_ENTERPRISE_ACCOUNT ,
  COALESCE(REMIT_DRAFT_PRINT_COUNT, '' ) AS REMIT_DRAFT_PRINT_COUNT 
 FROM  dw_tdata.BBS_001_ACCEPT_CONTRACT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ID ,
  BRANCH_ID ,
  ACCEPT_PROTOCOL_NO ,
  WEBBANK_CONTRACT_ID ,
  TASK_TYPE ,
  DRAFT_ATTR ,
  DRAFT_TYPE ,
  REMITTER_CUST_ID ,
  APPLY_ACCEPT_AMOUNT ,
  APPLY_REMIT_DATE ,
  MATURITY_DATE ,
  APPLY_REASON ,
  FIRST_REPAYMENT_ACCT ,
  SECOND_REPAYMENT_ACCT ,
  CREDIT_FEE_SCALE ,
  BAIL_SCALE ,
  CHARGE_SCALE ,
  TRANS_AMOUNT ,
  DRAWEE_BANK_ID ,
  MANAGER_ID ,
  DEPART_ID ,
  OPERATOR_ID ,
  TXN_DATE ,
  CONTRACT_STATUS ,
  LOGIC_CHECK_STATUS ,
  AUDIT_STATUS ,
  CREDIT_CHECK_STATUS ,
  DATA_SOURCE_TYPE ,
  MISC ,
  APPNO ,
  LAST_UPD_OPER_ID ,
  LAST_UPD_TIME ,
  POUNDAGE ,
  OPEN_CONSENT_CHARGE ,
  IMPAWN_PROTOCOL_NO ,
  ALLAY_MONEY_PROTOCOL_NO ,
  ACCT_BANK_BR_CODE ,
  CHILD_ACCT ,
  FILE_NAME ,
  BAIL_BOUNDED_STATUS ,
  ACCT_NAME ,
  COLLATERAL_SCALE ,
  LOW_RISK ,
  ACCEPT_TYPE ,
  BAIL_SRC ,
  BENEFIT_NUMBER_ONE ,
  BENEFIT_NUMBER_TWO ,
  MANAGER_ONE ,
  MANAGER_TWO ,
  BRHID_IN_ONE ,
  BRHID_IN_TWO ,
  INCOME_PERCENT_ONE ,
  INCOME_PERCENT_TWO ,
  ACTURALLY_INDUSTY ,
  GROUP_FLAG ,
  APPNO_DRA ,
  DRAFT_CHANGE_STATUS ,
  PLEDGE_SCALE ,
  PLEDGE_DRAFT ,
  PLEDGE_CASH ,
  ACCEPT_CORE_ACCOUNT ,
  ENT_BANK_STATUS ,
  VOLUME_OCCUPANT ,
  PARENT_COMPANY_CUST_NO ,
  CORE_ENTERPRISE_ACCOUNT ,
  REMIT_DRAFT_PRINT_COUNT 
 FROM dw_sdata.BBS_001_ACCEPT_CONTRACT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ID = T.ID
WHERE
(T.ID IS NULL)
 OR N.BRANCH_ID<>T.BRANCH_ID
 OR N.ACCEPT_PROTOCOL_NO<>T.ACCEPT_PROTOCOL_NO
 OR N.WEBBANK_CONTRACT_ID<>T.WEBBANK_CONTRACT_ID
 OR N.TASK_TYPE<>T.TASK_TYPE
 OR N.DRAFT_ATTR<>T.DRAFT_ATTR
 OR N.DRAFT_TYPE<>T.DRAFT_TYPE
 OR N.REMITTER_CUST_ID<>T.REMITTER_CUST_ID
 OR N.APPLY_ACCEPT_AMOUNT<>T.APPLY_ACCEPT_AMOUNT
 OR N.APPLY_REMIT_DATE<>T.APPLY_REMIT_DATE
 OR N.MATURITY_DATE<>T.MATURITY_DATE
 OR N.APPLY_REASON<>T.APPLY_REASON
 OR N.FIRST_REPAYMENT_ACCT<>T.FIRST_REPAYMENT_ACCT
 OR N.SECOND_REPAYMENT_ACCT<>T.SECOND_REPAYMENT_ACCT
 OR N.CREDIT_FEE_SCALE<>T.CREDIT_FEE_SCALE
 OR N.BAIL_SCALE<>T.BAIL_SCALE
 OR N.CHARGE_SCALE<>T.CHARGE_SCALE
 OR N.TRANS_AMOUNT<>T.TRANS_AMOUNT
 OR N.DRAWEE_BANK_ID<>T.DRAWEE_BANK_ID
 OR N.MANAGER_ID<>T.MANAGER_ID
 OR N.DEPART_ID<>T.DEPART_ID
 OR N.OPERATOR_ID<>T.OPERATOR_ID
 OR N.TXN_DATE<>T.TXN_DATE
 OR N.CONTRACT_STATUS<>T.CONTRACT_STATUS
 OR N.LOGIC_CHECK_STATUS<>T.LOGIC_CHECK_STATUS
 OR N.AUDIT_STATUS<>T.AUDIT_STATUS
 OR N.CREDIT_CHECK_STATUS<>T.CREDIT_CHECK_STATUS
 OR N.DATA_SOURCE_TYPE<>T.DATA_SOURCE_TYPE
 OR N.MISC<>T.MISC
 OR N.APPNO<>T.APPNO
 OR N.LAST_UPD_OPER_ID<>T.LAST_UPD_OPER_ID
 OR N.LAST_UPD_TIME<>T.LAST_UPD_TIME
 OR N.POUNDAGE<>T.POUNDAGE
 OR N.OPEN_CONSENT_CHARGE<>T.OPEN_CONSENT_CHARGE
 OR N.IMPAWN_PROTOCOL_NO<>T.IMPAWN_PROTOCOL_NO
 OR N.ALLAY_MONEY_PROTOCOL_NO<>T.ALLAY_MONEY_PROTOCOL_NO
 OR N.ACCT_BANK_BR_CODE<>T.ACCT_BANK_BR_CODE
 OR N.CHILD_ACCT<>T.CHILD_ACCT
 OR N.FILE_NAME<>T.FILE_NAME
 OR N.BAIL_BOUNDED_STATUS<>T.BAIL_BOUNDED_STATUS
 OR N.ACCT_NAME<>T.ACCT_NAME
 OR N.COLLATERAL_SCALE<>T.COLLATERAL_SCALE
 OR N.LOW_RISK<>T.LOW_RISK
 OR N.ACCEPT_TYPE<>T.ACCEPT_TYPE
 OR N.BAIL_SRC<>T.BAIL_SRC
 OR N.BENEFIT_NUMBER_ONE<>T.BENEFIT_NUMBER_ONE
 OR N.BENEFIT_NUMBER_TWO<>T.BENEFIT_NUMBER_TWO
 OR N.MANAGER_ONE<>T.MANAGER_ONE
 OR N.MANAGER_TWO<>T.MANAGER_TWO
 OR N.BRHID_IN_ONE<>T.BRHID_IN_ONE
 OR N.BRHID_IN_TWO<>T.BRHID_IN_TWO
 OR N.INCOME_PERCENT_ONE<>T.INCOME_PERCENT_ONE
 OR N.INCOME_PERCENT_TWO<>T.INCOME_PERCENT_TWO
 OR N.ACTURALLY_INDUSTY<>T.ACTURALLY_INDUSTY
 OR N.GROUP_FLAG<>T.GROUP_FLAG
 OR N.APPNO_DRA<>T.APPNO_DRA
 OR N.DRAFT_CHANGE_STATUS<>T.DRAFT_CHANGE_STATUS
 OR N.PLEDGE_SCALE<>T.PLEDGE_SCALE
 OR N.PLEDGE_DRAFT<>T.PLEDGE_DRAFT
 OR N.PLEDGE_CASH<>T.PLEDGE_CASH
 OR N.ACCEPT_CORE_ACCOUNT<>T.ACCEPT_CORE_ACCOUNT
 OR N.ENT_BANK_STATUS<>T.ENT_BANK_STATUS
 OR N.VOLUME_OCCUPANT<>T.VOLUME_OCCUPANT
 OR N.PARENT_COMPANY_CUST_NO<>T.PARENT_COMPANY_CUST_NO
 OR N.CORE_ENTERPRISE_ACCOUNT<>T.CORE_ENTERPRISE_ACCOUNT
 OR N.REMIT_DRAFT_PRINT_COUNT<>T.REMIT_DRAFT_PRINT_COUNT
;

--Step3:
UPDATE dw_sdata.BBS_001_ACCEPT_CONTRACT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_32
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ID=T_32.ID
;

--Step4:
INSERT  INTO dw_sdata.BBS_001_ACCEPT_CONTRACT SELECT * FROM T_32;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
