#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

DELETE FROM dw_sdata.CCB_000_EVENT WHERE etl_dt=DATE('${TX_DATE_YYYYMMDD}');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
INSERT  INTO dw_sdata.CCB_000_EVENT(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  ACCTNBR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BANK ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BATCH_DAY ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BATCH_NO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  INP_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  INP_TIME ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MERCHANT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MICRO_REF ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MONTH_NBR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ORI_TRANNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  XTRANNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRANS_TYPE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  VAL_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACCT_STYLE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACPTOR_ID ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACQMEMB_ID ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACTMTH ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ADN_MSGID ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AFFIN_FLAG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AUTH_CODE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AUTH_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AUTH_SRCE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AUTHD_AMT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AUTHD_RESP ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BANKACCT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BILL_AMT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BILL_AMTFLAG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BRNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CAP_ADDR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CARD_BIN ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CARD_NBR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CARD_PLAN ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CARDHOLDER ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CASHBACK ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CB_RIGHTS ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CHECK_DIG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CUR_EXP ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURRNCY_CD ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CVC_INV ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CWBCRB_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  DEP_DAY ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  DES_LINE1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  DES_LINE2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  DEST_BIN ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  EMPNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ERROR_FLAG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  EXPIRY_DTE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  FL_LIM_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ID_METHOD ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  INPUT_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  INTLFEEIND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ISPEC ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ISSUE_NBR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  XLAST_LINE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  M_P_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MARKET_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MATCHDATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MC_ICCR_DT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MCC_ALLOW ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MCC_ANALY ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MCC_CNTRL ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MCLRSEQ_NO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MCPOS_DATA ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MER_CAT_CD ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MERCH_SEQ ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MERCH_STAT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  MERCH_ZIP ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  NBR_MTHS ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  NTWK_SERV ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ORGN_AMT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ORGN_AMTFLAG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ORGN_CURR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  OTH_AMT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PAYFUND_TR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PCAS_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  POINT_CARD ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  POINT_MRCH ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  POINT_POST ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  POS_DATA ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  POS_ENTRY ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  POS_TERM ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PPAID_CARD ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PRODUCT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PROFIT_AMT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PUR_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PUR_TIME ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PURCHSE_FM ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PURCHSE_ID ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  RECURR_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  REIMBURSE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  REQPMTSERV ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  RETRV_REF ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  REV_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SEC_LVL ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SETTL_AMT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SETTL_CURR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SETTL_FLAG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SETTLE_DAY ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SPEC_COND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SRC_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SRCE_BIN ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  STIP_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TERM_IND ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TERMINALI ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_CODE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_FEE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_FEEC ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_ID ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRANS_SRC ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  VALIDATION ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  VISA_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  EMPNO_NEW ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PIPE1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ADD_COL1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  etl_dt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
SELECT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  COALESCE(ACCTNBR, 0 ) AS ACCTNBR ,
  COALESCE(BANK, 0 ) AS BANK ,
  COALESCE(BATCH_DAY, 0 ) AS BATCH_DAY ,
  COALESCE(BATCH_NO, 0 ) AS BATCH_NO ,
  COALESCE(INP_DATE, 0 ) AS INP_DATE ,
  COALESCE(INP_TIME, 0 ) AS INP_TIME ,
  COALESCE(MERCHANT, '' ) AS MERCHANT ,
  COALESCE(MICRO_REF, '' ) AS MICRO_REF ,
  COALESCE(MONTH_NBR, 0 ) AS MONTH_NBR ,
  COALESCE(ORI_TRANNO, 0 ) AS ORI_TRANNO ,
  COALESCE(XTRANNO, 0 ) AS XTRANNO ,
  COALESCE(TRANS_TYPE, 0 ) AS TRANS_TYPE ,
  COALESCE(VAL_DATE, 0 ) AS VAL_DATE ,
  COALESCE(ACCT_STYLE, '' ) AS ACCT_STYLE ,
  COALESCE(ACPTOR_ID, '' ) AS ACPTOR_ID ,
  COALESCE(ACQMEMB_ID, 0 ) AS ACQMEMB_ID ,
  COALESCE(ACTMTH, 0 ) AS ACTMTH ,
  COALESCE(ADN_MSGID, '' ) AS ADN_MSGID ,
  COALESCE(AFFIN_FLAG, 0 ) AS AFFIN_FLAG ,
  COALESCE(AUTH_CODE, '' ) AS AUTH_CODE ,
  COALESCE(AUTH_IND, '' ) AS AUTH_IND ,
  COALESCE(AUTH_SRCE, '' ) AS AUTH_SRCE ,
  COALESCE(AUTHD_AMT, 0 ) AS AUTHD_AMT ,
  COALESCE(AUTHD_RESP, '' ) AS AUTHD_RESP ,
  COALESCE(BANKACCT, '' ) AS BANKACCT ,
  COALESCE(BILL_AMT, 0 ) AS BILL_AMT ,
  COALESCE(BILL_AMTFLAG, '' ) AS BILL_AMTFLAG ,
  COALESCE(BRNO, '' ) AS BRNO ,
  COALESCE(CAP_ADDR, '' ) AS CAP_ADDR ,
  COALESCE(CARD_BIN, 0 ) AS CARD_BIN ,
  COALESCE(CARD_NBR, '' ) AS CARD_NBR ,
  COALESCE(CARD_PLAN, '' ) AS CARD_PLAN ,
  COALESCE(CARDHOLDER, 0 ) AS CARDHOLDER ,
  COALESCE(CASHBACK, 0 ) AS CASHBACK ,
  COALESCE(CB_RIGHTS, '' ) AS CB_RIGHTS ,
  COALESCE(CHECK_DIG, 0 ) AS CHECK_DIG ,
  COALESCE(CUR_EXP, 0 ) AS CUR_EXP ,
  COALESCE(CURRNCY_CD, 0 ) AS CURRNCY_CD ,
  COALESCE(CVC_INV, '' ) AS CVC_INV ,
  COALESCE(CWBCRB_IND, '' ) AS CWBCRB_IND ,
  COALESCE(DEP_DAY, 0 ) AS DEP_DAY ,
  COALESCE(DES_LINE1, '' ) AS DES_LINE1 ,
  COALESCE(DES_LINE2, '' ) AS DES_LINE2 ,
  COALESCE(DEST_BIN, 0 ) AS DEST_BIN ,
  COALESCE(EMPNO, '' ) AS EMPNO ,
  COALESCE(ERROR_FLAG, 0 ) AS ERROR_FLAG ,
  COALESCE(EXPIRY_DTE, 0 ) AS EXPIRY_DTE ,
  COALESCE(FL_LIM_IND, '' ) AS FL_LIM_IND ,
  COALESCE(ID_METHOD, '' ) AS ID_METHOD ,
  COALESCE(INPUT_DATE, '' ) AS INPUT_DATE ,
  COALESCE(INTLFEEIND, '' ) AS INTLFEEIND ,
  COALESCE(ISPEC, '' ) AS ISPEC ,
  COALESCE(ISSUE_NBR, 0 ) AS ISSUE_NBR ,
  COALESCE(XLAST_LINE, 0 ) AS XLAST_LINE ,
  COALESCE(M_P_IND, '' ) AS M_P_IND ,
  COALESCE(MARKET_IND, '' ) AS MARKET_IND ,
  COALESCE(MATCHDATE, 0 ) AS MATCHDATE ,
  COALESCE(MC_ICCR_DT, '' ) AS MC_ICCR_DT ,
  COALESCE(MCC_ALLOW, '' ) AS MCC_ALLOW ,
  COALESCE(MCC_ANALY, '' ) AS MCC_ANALY ,
  COALESCE(MCC_CNTRL, '' ) AS MCC_CNTRL ,
  COALESCE(MCLRSEQ_NO, 0 ) AS MCLRSEQ_NO ,
  COALESCE(MCPOS_DATA, '' ) AS MCPOS_DATA ,
  COALESCE(MER_CAT_CD, 0 ) AS MER_CAT_CD ,
  COALESCE(MERCH_SEQ, 0 ) AS MERCH_SEQ ,
  COALESCE(MERCH_STAT, '' ) AS MERCH_STAT ,
  COALESCE(MERCH_ZIP, 0 ) AS MERCH_ZIP ,
  COALESCE(NBR_MTHS, 0 ) AS NBR_MTHS ,
  COALESCE(NTWK_SERV, '' ) AS NTWK_SERV ,
  COALESCE(ORGN_AMT, 0 ) AS ORGN_AMT ,
  COALESCE(ORGN_AMTFLAG, '' ) AS ORGN_AMTFLAG ,
  COALESCE(ORGN_CURR, 0 ) AS ORGN_CURR ,
  COALESCE(OTH_AMT, 0 ) AS OTH_AMT ,
  COALESCE(PAYFUND_TR, 0 ) AS PAYFUND_TR ,
  COALESCE(PCAS_IND, '' ) AS PCAS_IND ,
  COALESCE(POINT_CARD, 0 ) AS POINT_CARD ,
  COALESCE(POINT_MRCH, 0 ) AS POINT_MRCH ,
  COALESCE(POINT_POST, '' ) AS POINT_POST ,
  COALESCE(POS_DATA, '' ) AS POS_DATA ,
  COALESCE(POS_ENTRY, '' ) AS POS_ENTRY ,
  COALESCE(POS_TERM, '' ) AS POS_TERM ,
  COALESCE(PPAID_CARD, '' ) AS PPAID_CARD ,
  COALESCE(PRODUCT, 0 ) AS PRODUCT ,
  COALESCE(PROFIT_AMT, 0 ) AS PROFIT_AMT ,
  COALESCE(PUR_DATE, 0 ) AS PUR_DATE ,
  COALESCE(PUR_TIME, 0 ) AS PUR_TIME ,
  COALESCE(PURCHSE_FM, '' ) AS PURCHSE_FM ,
  COALESCE(PURCHSE_ID, '' ) AS PURCHSE_ID ,
  COALESCE(RECURR_IND, '' ) AS RECURR_IND ,
  COALESCE(REIMBURSE, '' ) AS REIMBURSE ,
  COALESCE(REQPMTSERV, '' ) AS REQPMTSERV ,
  COALESCE(RETRV_REF, '' ) AS RETRV_REF ,
  COALESCE(REV_IND, '' ) AS REV_IND ,
  COALESCE(SEC_LVL, '' ) AS SEC_LVL ,
  COALESCE(SETTL_AMT, 0 ) AS SETTL_AMT ,
  COALESCE(SETTL_CURR, '' ) AS SETTL_CURR ,
  COALESCE(SETTL_FLAG, '' ) AS SETTL_FLAG ,
  COALESCE(SETTLE_DAY, 0 ) AS SETTLE_DAY ,
  COALESCE(SPEC_COND, '' ) AS SPEC_COND ,
  COALESCE(SRC_IND, '' ) AS SRC_IND ,
  COALESCE(SRCE_BIN, 0 ) AS SRCE_BIN ,
  COALESCE(STIP_IND, '' ) AS STIP_IND ,
  COALESCE(TERM_IND, '' ) AS TERM_IND ,
  COALESCE(TERMINALI, '' ) AS TERMINALI ,
  COALESCE(TRAN_CODE, 0 ) AS TRAN_CODE ,
  COALESCE(TRAN_FEE, 0 ) AS TRAN_FEE ,
  COALESCE(TRAN_FEEC, 0 ) AS TRAN_FEEC ,
  COALESCE(TRAN_ID, '' ) AS TRAN_ID ,
  COALESCE(TRANS_SRC, '' ) AS TRANS_SRC ,
  COALESCE(VALIDATION, '' ) AS VALIDATION ,
  COALESCE(VISA_DATE, 0 ) AS VISA_DATE ,
  COALESCE(EMPNO_NEW, '' ) AS EMPNO_NEW ,
  COALESCE(PIPE1, '' ) AS PIPE1 ,
  COALESCE(ADD_COL1, '' ) AS ADD_COL1 ,
  DATE('${TX_DATE_YYYYMMDD}')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
FROM  dw_tdata.CCB_000_EVENT_${TX_DATE_YYYYMMDD}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
COMMIT;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
