#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCB_000_CUSTR WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCB_000_CUSTR SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_93 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCB_000_CUSTR WHERE 1=0;

--Step2:
INSERT  INTO T_93 (
  BANK,
  CUSTR_NBR,
  RACE_CODE,
  CUSTR_REF,
  NAME_KEY,
  BUSI_PHONE,
  CLASS_CODE,
  COMP_NAME,
  CRED_LIMIT,
  CREDLIM_X,
  CUST_TYPE,
  DAY_BIRTH,
  EDUCA,
  ELIG_LOYAL,
  EMAIL_ADDR,
  EMPLY_DEPT,
  EMPLY_NBR,
  EXTENSION,
  GENDER,
  HMTEL_AREA,
  HOME_PHONE,
  INCOME_ANN,
  COMP_DUTY,
  IRD_NUMBER,
  LANG_CODE,
  MAIL_CODE,
  MAR_STATUS,
  MO_PHONE,
  MP_LIMIT,
  MTHR_MNAME,
  NATION,
  OCC_CATGRY,
  OCC_CODE,
  POSN_EMPLY,
  SCORE_FLAG,
  SURNAME,
  SECUR_NBR,
  TITLE,
  WORK_CALLS,
  YR_IN_COMP,
  EMPNO,
  MO_AREA,
  BMW_YN,
  BUSI_SERV,
  COLL_EXP,
  PIN_INQFL,
  LAYERCODER1,
  LAYERCODER2,
  CA_PCNT,
  ID_DTE,
  BUSI_LEVEL,
  NATION_CD,
  ID_ISSDT,
  SIGN_DTE,
  REG_DTE,
  COMP_NAME2,
  LAYERCODE3,
  CLYN,
  ISSDEPT_IF,
  ETL_DAY,
  PROMPT_QU,
  PROMPT_AN,
RL_VAL,
TECH_LEVEL,
LAYERCODE4,
OCCU_TYPE,
  start_dt,
  end_dt)
SELECT
  N.BANK,
  N.CUSTR_NBR,
  N.RACE_CODE,
  N.CUSTR_REF,
  N.NAME_KEY,
  N.BUSI_PHONE,
  N.CLASS_CODE,
  N.COMP_NAME,
  N.CRED_LIMIT,
  N.CREDLIM_X,
  N.CUST_TYPE,
  N.DAY_BIRTH,
  N.EDUCA,
  N.ELIG_LOYAL,
  N.EMAIL_ADDR,
  N.EMPLY_DEPT,
  N.EMPLY_NBR,
  N.EXTENSION,
  N.GENDER,
  N.HMTEL_AREA,
  N.HOME_PHONE,
  N.INCOME_ANN,
  N.COMP_DUTY,
  N.IRD_NUMBER,
  N.LANG_CODE,
  N.MAIL_CODE,
  N.MAR_STATUS,
  N.MO_PHONE,
  N.MP_LIMIT,
  N.MTHR_MNAME,
  N.NATION,
  N.OCC_CATGRY,
  N.OCC_CODE,
  N.POSN_EMPLY,
  N.SCORE_FLAG,
  N.SURNAME,
  N.SECUR_NBR,
  N.TITLE,
  N.WORK_CALLS,
  N.YR_IN_COMP,
  N.EMPNO,
  N.MO_AREA,
  N.BMW_YN,
  N.BUSI_SERV,
  N.COLL_EXP,
  N.PIN_INQFL,
  N.LAYERCODER1,
  N.LAYERCODER2,
  N.CA_PCNT,
  N.ID_DTE,
  N.BUSI_LEVEL,
  N.NATION_CD,
  N.ID_ISSDT,
  N.SIGN_DTE,
  N.REG_DTE,
  N.COMP_NAME2,
  N.LAYERCODE3,
  N.CLYN,
  N.ISSDEPT_IF,
  N.ETL_DAY,
  N.PROMPT_QU,
  N.PROMPT_AN,
N.RL_VAL,
N.TECH_LEVEL,
N.LAYERCODE4,
N.OCCU_TYPE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(BANK, '' ) AS BANK ,
  COALESCE(CUSTR_NBR, '' ) AS CUSTR_NBR ,
  COALESCE(RACE_CODE, '' ) AS RACE_CODE ,
  COALESCE(CUSTR_REF, '' ) AS CUSTR_REF ,
  COALESCE(NAME_KEY, '' ) AS NAME_KEY ,
  COALESCE(BUSI_PHONE, '' ) AS BUSI_PHONE ,
  COALESCE(CLASS_CODE, '' ) AS CLASS_CODE ,
  COALESCE(COMP_NAME, '' ) AS COMP_NAME ,
  COALESCE(CRED_LIMIT, 0 ) AS CRED_LIMIT ,
  COALESCE(CREDLIM_X, 0 ) AS CREDLIM_X ,
  COALESCE(CUST_TYPE, '' ) AS CUST_TYPE ,
  COALESCE(DAY_BIRTH, 0 ) AS DAY_BIRTH ,
  COALESCE(EDUCA, '' ) AS EDUCA ,
  COALESCE(ELIG_LOYAL, '' ) AS ELIG_LOYAL ,
  COALESCE(EMAIL_ADDR, '' ) AS EMAIL_ADDR ,
  COALESCE(EMPLY_DEPT, '' ) AS EMPLY_DEPT ,
  COALESCE(EMPLY_NBR, 0 ) AS EMPLY_NBR ,
  COALESCE(EXTENSION, '' ) AS EXTENSION ,
  COALESCE(GENDER, '' ) AS GENDER ,
  COALESCE(HMTEL_AREA, 0 ) AS HMTEL_AREA ,
  COALESCE(HOME_PHONE, '' ) AS HOME_PHONE ,
  COALESCE(INCOME_ANN, 0 ) AS INCOME_ANN ,
  COALESCE(COMP_DUTY, '' ) AS COMP_DUTY ,
  COALESCE(IRD_NUMBER, '' ) AS IRD_NUMBER ,
  COALESCE(LANG_CODE, 0 ) AS LANG_CODE ,
  COALESCE(MAIL_CODE, '' ) AS MAIL_CODE ,
  COALESCE(MAR_STATUS, '' ) AS MAR_STATUS ,
  COALESCE(MO_PHONE, '' ) AS MO_PHONE ,
  COALESCE(MP_LIMIT, 0 ) AS MP_LIMIT ,
  COALESCE(MTHR_MNAME, '' ) AS MTHR_MNAME ,
  COALESCE(NATION, 0 ) AS NATION ,
  COALESCE(OCC_CATGRY, '' ) AS OCC_CATGRY ,
  COALESCE(OCC_CODE, '' ) AS OCC_CODE ,
  COALESCE(POSN_EMPLY, '' ) AS POSN_EMPLY ,
  COALESCE(SCORE_FLAG, 0 ) AS SCORE_FLAG ,
  COALESCE(SURNAME, '' ) AS SURNAME ,
  COALESCE(SECUR_NBR, '' ) AS SECUR_NBR ,
  COALESCE(TITLE, '' ) AS TITLE ,
  COALESCE(WORK_CALLS, '' ) AS WORK_CALLS ,
  COALESCE(YR_IN_COMP, 0 ) AS YR_IN_COMP ,
  COALESCE(EMPNO, '' ) AS EMPNO ,
  COALESCE(MO_AREA, '' ) AS MO_AREA ,
  COALESCE(BMW_YN, '' ) AS BMW_YN ,
  COALESCE(BUSI_SERV, '' ) AS BUSI_SERV ,
  COALESCE(COLL_EXP, '' ) AS COLL_EXP ,
  COALESCE(PIN_INQFL, '' ) AS PIN_INQFL ,
  COALESCE(LAYERCODER1, '' ) AS LAYERCODER1 ,
  COALESCE(LAYERCODER2, '' ) AS LAYERCODER2 ,
  COALESCE(CA_PCNT, 0 ) AS CA_PCNT ,
  COALESCE(ID_DTE, 0 ) AS ID_DTE ,
  COALESCE(BUSI_LEVEL, '' ) AS BUSI_LEVEL ,
  COALESCE(NATION_CD, '' ) AS NATION_CD ,
  COALESCE(ID_ISSDT, 0 ) AS ID_ISSDT ,
  COALESCE(SIGN_DTE, 0 ) AS SIGN_DTE ,
  COALESCE(REG_DTE, 0 ) AS REG_DTE ,
  COALESCE(COMP_NAME2, '' ) AS COMP_NAME2 ,
  COALESCE(LAYERCODE3, '' ) AS LAYERCODE3 ,
  COALESCE(CLYN, '' ) AS CLYN ,
  COALESCE(ISSDEPT_IF, '' ) AS ISSDEPT_IF ,
  COALESCE(ETL_DAY, 0 ) AS ETL_DAY ,
  COALESCE(PROMPT_QU, '' ) AS PROMPT_QU ,
  COALESCE(PROMPT_AN, '' ) AS PROMPT_AN ,
COALESCE(RL_VAL,'') AS RL_VAL,
COALESCE(TECH_LEVEL,'') AS TECH_LEVEL,
COALESCE(LAYERCODE4,'') AS LAYERCODE4,
COALESCE(OCCU_TYPE,'') AS OCCU_TYPE

 FROM  dw_tdata.CCB_000_CUSTR_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  BANK ,
  CUSTR_NBR ,
  RACE_CODE ,
  CUSTR_REF ,
  NAME_KEY ,
  BUSI_PHONE ,
  CLASS_CODE ,
  COMP_NAME ,
  CRED_LIMIT ,
  CREDLIM_X ,
  CUST_TYPE ,
  DAY_BIRTH ,
  EDUCA ,
  ELIG_LOYAL ,
  EMAIL_ADDR ,
  EMPLY_DEPT ,
  EMPLY_NBR ,
  EXTENSION ,
  GENDER ,
  HMTEL_AREA ,
  HOME_PHONE ,
  INCOME_ANN ,
  COMP_DUTY ,
  IRD_NUMBER ,
  LANG_CODE ,
  MAIL_CODE ,
  MAR_STATUS ,
  MO_PHONE ,
  MP_LIMIT ,
  MTHR_MNAME ,
  NATION ,
  OCC_CATGRY ,
  OCC_CODE ,
  POSN_EMPLY ,
  SCORE_FLAG ,
  SURNAME ,
  SECUR_NBR ,
  TITLE ,
  WORK_CALLS ,
  YR_IN_COMP ,
  EMPNO ,
  MO_AREA ,
  BMW_YN ,
  BUSI_SERV ,
  COLL_EXP ,
  PIN_INQFL ,
  LAYERCODER1 ,
  LAYERCODER2 ,
  CA_PCNT ,
  ID_DTE ,
  BUSI_LEVEL ,
  NATION_CD ,
  ID_ISSDT ,
  SIGN_DTE ,
  REG_DTE ,
  COMP_NAME2 ,
  LAYERCODE3 ,
  CLYN ,
  ISSDEPT_IF ,
  ETL_DAY ,
  PROMPT_QU ,
  PROMPT_AN ,
RL_VAL,
TECH_LEVEL,
LAYERCODE4,
OCCU_TYPE
 FROM dw_sdata.CCB_000_CUSTR 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.CUSTR_NBR = T.CUSTR_NBR
WHERE
(T.CUSTR_NBR IS NULL)
 OR N.BANK<>T.BANK
 OR N.RACE_CODE<>T.RACE_CODE
 OR N.CUSTR_REF<>T.CUSTR_REF
 OR N.NAME_KEY<>T.NAME_KEY
 OR N.BUSI_PHONE<>T.BUSI_PHONE
 OR N.CLASS_CODE<>T.CLASS_CODE
 OR N.COMP_NAME<>T.COMP_NAME
 OR N.CRED_LIMIT<>T.CRED_LIMIT
 OR N.CREDLIM_X<>T.CREDLIM_X
 OR N.CUST_TYPE<>T.CUST_TYPE
 OR N.DAY_BIRTH<>T.DAY_BIRTH
 OR N.EDUCA<>T.EDUCA
 OR N.ELIG_LOYAL<>T.ELIG_LOYAL
 OR N.EMAIL_ADDR<>T.EMAIL_ADDR
 OR N.EMPLY_DEPT<>T.EMPLY_DEPT
 OR N.EMPLY_NBR<>T.EMPLY_NBR
 OR N.EXTENSION<>T.EXTENSION
 OR N.GENDER<>T.GENDER
 OR N.HMTEL_AREA<>T.HMTEL_AREA
 OR N.HOME_PHONE<>T.HOME_PHONE
 OR N.INCOME_ANN<>T.INCOME_ANN
 OR N.COMP_DUTY<>T.COMP_DUTY
 OR N.IRD_NUMBER<>T.IRD_NUMBER
 OR N.LANG_CODE<>T.LANG_CODE
 OR N.MAIL_CODE<>T.MAIL_CODE
 OR N.MAR_STATUS<>T.MAR_STATUS
 OR N.MO_PHONE<>T.MO_PHONE
 OR N.MP_LIMIT<>T.MP_LIMIT
 OR N.MTHR_MNAME<>T.MTHR_MNAME
 OR N.NATION<>T.NATION
 OR N.OCC_CATGRY<>T.OCC_CATGRY
 OR N.OCC_CODE<>T.OCC_CODE
 OR N.POSN_EMPLY<>T.POSN_EMPLY
 OR N.SCORE_FLAG<>T.SCORE_FLAG
 OR N.SURNAME<>T.SURNAME
 OR N.SECUR_NBR<>T.SECUR_NBR
 OR N.TITLE<>T.TITLE
 OR N.WORK_CALLS<>T.WORK_CALLS
 OR N.YR_IN_COMP<>T.YR_IN_COMP
 OR N.EMPNO<>T.EMPNO
 OR N.MO_AREA<>T.MO_AREA
 OR N.BMW_YN<>T.BMW_YN
 OR N.BUSI_SERV<>T.BUSI_SERV
 OR N.COLL_EXP<>T.COLL_EXP
 OR N.PIN_INQFL<>T.PIN_INQFL
 OR N.LAYERCODER1<>T.LAYERCODER1
 OR N.LAYERCODER2<>T.LAYERCODER2
 OR N.CA_PCNT<>T.CA_PCNT
 OR N.ID_DTE<>T.ID_DTE
 OR N.BUSI_LEVEL<>T.BUSI_LEVEL
 OR N.NATION_CD<>T.NATION_CD
 OR N.ID_ISSDT<>T.ID_ISSDT
 OR N.SIGN_DTE<>T.SIGN_DTE
 OR N.REG_DTE<>T.REG_DTE
 OR N.COMP_NAME2<>T.COMP_NAME2
 OR N.LAYERCODE3<>T.LAYERCODE3
 OR N.CLYN<>T.CLYN
 OR N.ISSDEPT_IF<>T.ISSDEPT_IF
 OR N.ETL_DAY<>T.ETL_DAY
 OR N.PROMPT_QU<>T.PROMPT_QU
 OR N.PROMPT_AN<>T.PROMPT_AN
OR N.RL_VAL<>T.RL_VAL
OR N.TECH_LEVEL<>T.TECH_LEVEL
OR N.LAYERCODE4<>T.LAYERCODE4
OR N.OCCU_TYPE<>T.OCCU_TYPE
;

--Step3:
UPDATE dw_sdata.CCB_000_CUSTR P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_93
WHERE P.End_Dt=DATE('2100-12-31')
AND P.CUSTR_NBR=T_93.CUSTR_NBR
;

--Step4:
INSERT  INTO dw_sdata.CCB_000_CUSTR SELECT * FROM T_93;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
