#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCB_000_ACCX WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCB_000_ACCX SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_84 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCB_000_ACCX WHERE 1=0;

--Step2:
INSERT  INTO T_84 (
  XACCOUNT,
  BANK,
  BUSINESS,
  AGE1,
  AGE2,
  AGE3,
  AGE4,
  AGE5,
  AGE6,
  AUTH_CASH,
  AUTHS_AMT,
  BAL_CMPINT,
  BAL_FREE,
  BAL_INT,
  BALINTFLAG,
  BAL_NOINT,
  BAL_ORINT,
  CARD_FEES,
  CASH_ADFEE,
  CASH_ADVCE,
  CASH_TDAY,
  CATEGORY,
  CRED_ADJ,
  CRED_VOUCH,
  CURR_NUM,
  DEBIT_ADJ,
  DUTY_CREDT,
  DUTY_DEBIT,
  EXCH_AMT,
  EXCH_AUTH,
  EXCH_INQAM,
  FEES_TAXES,
  HI_CASHADV,
  HI_CASMMYY,
  HI_CRDMMYY,
  HI_CREDIT,
  HI_DEBIT,
  HI_DEBMMYY,
  HI_OLIMIT,
  HI_OLIMMYY,
  HI_PURCHSE,
  HI_PURMMYY,
  INT_CASH,
  INT_CHDCMP,
  INT_CHGD,
  INT_CMPOND,
  INT_CODE,
  INT_CUNOT,
  INT_CURCMP,
  INT_EARNED,
  INT_NOTION,
  INT_PROCDY,
  INT_RATE,
  INT_RATECR,
  INT_UPTODY,
  LAST_TRDAY,
  LASTNTDATE,
  LASTPAYAMT,
  LASTPAYDAY,
  MONTH_NBR,
  MTHS_ODUE,
  NBR_CASHAD,
  NBR_FEEDTY,
  NBR_OLIMIT,
  NBR_OTHERS,
  NBR_PAYMNT,
  NBR_PURCH,
  NBR_TRANS,
  ODUE_FLAG,
  ODUE_HELD,
  OLFLAG,
  OTHER_FEES,
  PAY_FLAG,
  PAYMT_CLRD,
  PAYMT_TDAY,
  PAYMT_UNCL,
  PEN_CHRG,
  PENCHG_ACC,
  PURCHASES,
  QUERY_AMT,
  QUERY_CODE,
  QUERY_STMT,
  STM_AMT_OL,
  STM_BALFRE,
  STM_BALINT,
  STMBALINTFLAG,
  STM_BALNCE,
  STM_BALFLAG,
  STM_BALORI,
  STM_INSTL,
  STM_MINDUE,
  STM_NOINT,
  STM_OLFLAG,
  STM_OVERDU,
  STM_PAY_UN,
  STM_QRYAMT,
  STM_REPAY,
  TODAY_AMT,
  TODAY_AMTFLAG,
  TODAY_REL,
  UNCL_PCT,
  SHADOW_PEN,
  SHADOW_INT,
  SHADOW_CMP,
  BAL_NINT01,
  BAL_NINT02,
  BAL_NINT03,
  BAL_NINT04,
  BAL_NINT05,
  BAL_NINT06,
  BAL_NINT07,
  BAL_NINT08,
  BAL_NINT09,
  BAL_NINT10,
  STM_NINT01,
  STM_NINT02,
  STM_NINT03,
  STM_NINT04,
  STM_NINT05,
  STM_NINT06,
  STM_NINT07,
  STM_NINT08,
  STM_NINT09,
  STM_NINT10,
  MP_AUTHS,
  MP_BAL,
  MP_REM_PPL,
  BAL_MP,
  STM_BALMP,
  start_dt,
  end_dt)
SELECT
  N.XACCOUNT,
  N.BANK,
  N.BUSINESS,
  N.AGE1,
  N.AGE2,
  N.AGE3,
  N.AGE4,
  N.AGE5,
  N.AGE6,
  N.AUTH_CASH,
  N.AUTHS_AMT,
  N.BAL_CMPINT,
  N.BAL_FREE,
  N.BAL_INT,
  N.BALINTFLAG,
  N.BAL_NOINT,
  N.BAL_ORINT,
  N.CARD_FEES,
  N.CASH_ADFEE,
  N.CASH_ADVCE,
  N.CASH_TDAY,
  N.CATEGORY,
  N.CRED_ADJ,
  N.CRED_VOUCH,
  N.CURR_NUM,
  N.DEBIT_ADJ,
  N.DUTY_CREDT,
  N.DUTY_DEBIT,
  N.EXCH_AMT,
  N.EXCH_AUTH,
  N.EXCH_INQAM,
  N.FEES_TAXES,
  N.HI_CASHADV,
  N.HI_CASMMYY,
  N.HI_CRDMMYY,
  N.HI_CREDIT,
  N.HI_DEBIT,
  N.HI_DEBMMYY,
  N.HI_OLIMIT,
  N.HI_OLIMMYY,
  N.HI_PURCHSE,
  N.HI_PURMMYY,
  N.INT_CASH,
  N.INT_CHDCMP,
  N.INT_CHGD,
  N.INT_CMPOND,
  N.INT_CODE,
  N.INT_CUNOT,
  N.INT_CURCMP,
  N.INT_EARNED,
  N.INT_NOTION,
  N.INT_PROCDY,
  N.INT_RATE,
  N.INT_RATECR,
  N.INT_UPTODY,
  N.LAST_TRDAY,
  N.LASTNTDATE,
  N.LASTPAYAMT,
  N.LASTPAYDAY,
  N.MONTH_NBR,
  N.MTHS_ODUE,
  N.NBR_CASHAD,
  N.NBR_FEEDTY,
  N.NBR_OLIMIT,
  N.NBR_OTHERS,
  N.NBR_PAYMNT,
  N.NBR_PURCH,
  N.NBR_TRANS,
  N.ODUE_FLAG,
  N.ODUE_HELD,
  N.OLFLAG,
  N.OTHER_FEES,
  N.PAY_FLAG,
  N.PAYMT_CLRD,
  N.PAYMT_TDAY,
  N.PAYMT_UNCL,
  N.PEN_CHRG,
  N.PENCHG_ACC,
  N.PURCHASES,
  N.QUERY_AMT,
  N.QUERY_CODE,
  N.QUERY_STMT,
  N.STM_AMT_OL,
  N.STM_BALFRE,
  N.STM_BALINT,
  N.STMBALINTFLAG,
  N.STM_BALNCE,
  N.STM_BALFLAG,
  N.STM_BALORI,
  N.STM_INSTL,
  N.STM_MINDUE,
  N.STM_NOINT,
  N.STM_OLFLAG,
  N.STM_OVERDU,
  N.STM_PAY_UN,
  N.STM_QRYAMT,
  N.STM_REPAY,
  N.TODAY_AMT,
  N.TODAY_AMTFLAG,
  N.TODAY_REL,
  N.UNCL_PCT,
  N.SHADOW_PEN,
  N.SHADOW_INT,
  N.SHADOW_CMP,
  N.BAL_NINT01,
  N.BAL_NINT02,
  N.BAL_NINT03,
  N.BAL_NINT04,
  N.BAL_NINT05,
  N.BAL_NINT06,
  N.BAL_NINT07,
  N.BAL_NINT08,
  N.BAL_NINT09,
  N.BAL_NINT10,
  N.STM_NINT01,
  N.STM_NINT02,
  N.STM_NINT03,
  N.STM_NINT04,
  N.STM_NINT05,
  N.STM_NINT06,
  N.STM_NINT07,
  N.STM_NINT08,
  N.STM_NINT09,
  N.STM_NINT10,
  N.MP_AUTHS,
  N.MP_BAL,
  N.MP_REM_PPL,
  N.BAL_MP,
  N.STM_BALMP,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(XACCOUNT, 0 ) AS XACCOUNT ,
  COALESCE(BANK, 0 ) AS BANK ,
  COALESCE(BUSINESS, '' ) AS BUSINESS ,
  COALESCE(AGE1, 0 ) AS AGE1 ,
  COALESCE(AGE2, 0 ) AS AGE2 ,
  COALESCE(AGE3, 0 ) AS AGE3 ,
  COALESCE(AGE4, 0 ) AS AGE4 ,
  COALESCE(AGE5, 0 ) AS AGE5 ,
  COALESCE(AGE6, 0 ) AS AGE6 ,
  COALESCE(AUTH_CASH, 0 ) AS AUTH_CASH ,
  COALESCE(AUTHS_AMT, 0 ) AS AUTHS_AMT ,
  COALESCE(BAL_CMPINT, 0 ) AS BAL_CMPINT ,
  COALESCE(BAL_FREE, 0 ) AS BAL_FREE ,
  COALESCE(BAL_INT, 0 ) AS BAL_INT ,
  COALESCE(BALINTFLAG, '' ) AS BALINTFLAG ,
  COALESCE(BAL_NOINT, 0 ) AS BAL_NOINT ,
  COALESCE(BAL_ORINT, 0 ) AS BAL_ORINT ,
  COALESCE(CARD_FEES, 0 ) AS CARD_FEES ,
  COALESCE(CASH_ADFEE, 0 ) AS CASH_ADFEE ,
  COALESCE(CASH_ADVCE, 0 ) AS CASH_ADVCE ,
  COALESCE(CASH_TDAY, 0 ) AS CASH_TDAY ,
  COALESCE(CATEGORY, 0 ) AS CATEGORY ,
  COALESCE(CRED_ADJ, 0 ) AS CRED_ADJ ,
  COALESCE(CRED_VOUCH, 0 ) AS CRED_VOUCH ,
  COALESCE(CURR_NUM, 0 ) AS CURR_NUM ,
  COALESCE(DEBIT_ADJ, 0 ) AS DEBIT_ADJ ,
  COALESCE(DUTY_CREDT, 0 ) AS DUTY_CREDT ,
  COALESCE(DUTY_DEBIT, 0 ) AS DUTY_DEBIT ,
  COALESCE(EXCH_AMT, 0 ) AS EXCH_AMT ,
  COALESCE(EXCH_AUTH, 0 ) AS EXCH_AUTH ,
  COALESCE(EXCH_INQAM, 0 ) AS EXCH_INQAM ,
  COALESCE(FEES_TAXES, 0 ) AS FEES_TAXES ,
  COALESCE(HI_CASHADV, 0 ) AS HI_CASHADV ,
  COALESCE(HI_CASMMYY, 0 ) AS HI_CASMMYY ,
  COALESCE(HI_CRDMMYY, 0 ) AS HI_CRDMMYY ,
  COALESCE(HI_CREDIT, 0 ) AS HI_CREDIT ,
  COALESCE(HI_DEBIT, 0 ) AS HI_DEBIT ,
  COALESCE(HI_DEBMMYY, 0 ) AS HI_DEBMMYY ,
  COALESCE(HI_OLIMIT, 0 ) AS HI_OLIMIT ,
  COALESCE(HI_OLIMMYY, 0 ) AS HI_OLIMMYY ,
  COALESCE(HI_PURCHSE, 0 ) AS HI_PURCHSE ,
  COALESCE(HI_PURMMYY, 0 ) AS HI_PURMMYY ,
  COALESCE(INT_CASH, 0 ) AS INT_CASH ,
  COALESCE(INT_CHDCMP, 0 ) AS INT_CHDCMP ,
  COALESCE(INT_CHGD, 0 ) AS INT_CHGD ,
  COALESCE(INT_CMPOND, 0 ) AS INT_CMPOND ,
  COALESCE(INT_CODE, 0 ) AS INT_CODE ,
  COALESCE(INT_CUNOT, 0 ) AS INT_CUNOT ,
  COALESCE(INT_CURCMP, 0 ) AS INT_CURCMP ,
  COALESCE(INT_EARNED, 0 ) AS INT_EARNED ,
  COALESCE(INT_NOTION, 0 ) AS INT_NOTION ,
  COALESCE(INT_PROCDY, 0 ) AS INT_PROCDY ,
  COALESCE(INT_RATE, 0 ) AS INT_RATE ,
  COALESCE(INT_RATECR, 0 ) AS INT_RATECR ,
  COALESCE(INT_UPTODY, 0 ) AS INT_UPTODY ,
  COALESCE(LAST_TRDAY, 0 ) AS LAST_TRDAY ,
  COALESCE(LASTNTDATE, 0 ) AS LASTNTDATE ,
  COALESCE(LASTPAYAMT, 0 ) AS LASTPAYAMT ,
  COALESCE(LASTPAYDAY, 0 ) AS LASTPAYDAY ,
  COALESCE(MONTH_NBR, 0 ) AS MONTH_NBR ,
  COALESCE(MTHS_ODUE, 0 ) AS MTHS_ODUE ,
  COALESCE(NBR_CASHAD, 0 ) AS NBR_CASHAD ,
  COALESCE(NBR_FEEDTY, 0 ) AS NBR_FEEDTY ,
  COALESCE(NBR_OLIMIT, 0 ) AS NBR_OLIMIT ,
  COALESCE(NBR_OTHERS, 0 ) AS NBR_OTHERS ,
  COALESCE(NBR_PAYMNT, 0 ) AS NBR_PAYMNT ,
  COALESCE(NBR_PURCH, 0 ) AS NBR_PURCH ,
  COALESCE(NBR_TRANS, 0 ) AS NBR_TRANS ,
  COALESCE(ODUE_FLAG, 0 ) AS ODUE_FLAG ,
  COALESCE(ODUE_HELD, 0 ) AS ODUE_HELD ,
  COALESCE(OLFLAG, 0 ) AS OLFLAG ,
  COALESCE(OTHER_FEES, 0 ) AS OTHER_FEES ,
  COALESCE(PAY_FLAG, '' ) AS PAY_FLAG ,
  COALESCE(PAYMT_CLRD, 0 ) AS PAYMT_CLRD ,
  COALESCE(PAYMT_TDAY, 0 ) AS PAYMT_TDAY ,
  COALESCE(PAYMT_UNCL, 0 ) AS PAYMT_UNCL ,
  COALESCE(PEN_CHRG, 0 ) AS PEN_CHRG ,
  COALESCE(PENCHG_ACC, 0 ) AS PENCHG_ACC ,
  COALESCE(PURCHASES, 0 ) AS PURCHASES ,
  COALESCE(QUERY_AMT, 0 ) AS QUERY_AMT ,
  COALESCE(QUERY_CODE, '' ) AS QUERY_CODE ,
  COALESCE(QUERY_STMT, 0 ) AS QUERY_STMT ,
  COALESCE(STM_AMT_OL, 0 ) AS STM_AMT_OL ,
  COALESCE(STM_BALFRE, 0 ) AS STM_BALFRE ,
  COALESCE(STM_BALINT, 0 ) AS STM_BALINT ,
  COALESCE(STMBALINTFLAG, '' ) AS STMBALINTFLAG ,
  COALESCE(STM_BALNCE, 0 ) AS STM_BALNCE ,
  COALESCE(STM_BALFLAG, '' ) AS STM_BALFLAG ,
  COALESCE(STM_BALORI, 0 ) AS STM_BALORI ,
  COALESCE(STM_INSTL, 0 ) AS STM_INSTL ,
  COALESCE(STM_MINDUE, 0 ) AS STM_MINDUE ,
  COALESCE(STM_NOINT, 0 ) AS STM_NOINT ,
  COALESCE(STM_OLFLAG, 0 ) AS STM_OLFLAG ,
  COALESCE(STM_OVERDU, 0 ) AS STM_OVERDU ,
  COALESCE(STM_PAY_UN, 0 ) AS STM_PAY_UN ,
  COALESCE(STM_QRYAMT, 0 ) AS STM_QRYAMT ,
  COALESCE(STM_REPAY, 0 ) AS STM_REPAY ,
  COALESCE(TODAY_AMT, 0 ) AS TODAY_AMT ,
  COALESCE(TODAY_AMTFLAG, '' ) AS TODAY_AMTFLAG ,
  COALESCE(TODAY_REL, 0 ) AS TODAY_REL ,
  COALESCE(UNCL_PCT, 0 ) AS UNCL_PCT ,
  COALESCE(SHADOW_PEN, 0 ) AS SHADOW_PEN ,
  COALESCE(SHADOW_INT, 0 ) AS SHADOW_INT ,
  COALESCE(SHADOW_CMP, 0 ) AS SHADOW_CMP ,
  COALESCE(BAL_NINT01, 0 ) AS BAL_NINT01 ,
  COALESCE(BAL_NINT02, 0 ) AS BAL_NINT02 ,
  COALESCE(BAL_NINT03, 0 ) AS BAL_NINT03 ,
  COALESCE(BAL_NINT04, 0 ) AS BAL_NINT04 ,
  COALESCE(BAL_NINT05, 0 ) AS BAL_NINT05 ,
  COALESCE(BAL_NINT06, 0 ) AS BAL_NINT06 ,
  COALESCE(BAL_NINT07, 0 ) AS BAL_NINT07 ,
  COALESCE(BAL_NINT08, 0 ) AS BAL_NINT08 ,
  COALESCE(BAL_NINT09, 0 ) AS BAL_NINT09 ,
  COALESCE(BAL_NINT10, 0 ) AS BAL_NINT10 ,
  COALESCE(STM_NINT01, 0 ) AS STM_NINT01 ,
  COALESCE(STM_NINT02, 0 ) AS STM_NINT02 ,
  COALESCE(STM_NINT03, 0 ) AS STM_NINT03 ,
  COALESCE(STM_NINT04, 0 ) AS STM_NINT04 ,
  COALESCE(STM_NINT05, 0 ) AS STM_NINT05 ,
  COALESCE(STM_NINT06, 0 ) AS STM_NINT06 ,
  COALESCE(STM_NINT07, 0 ) AS STM_NINT07 ,
  COALESCE(STM_NINT08, 0 ) AS STM_NINT08 ,
  COALESCE(STM_NINT09, 0 ) AS STM_NINT09 ,
  COALESCE(STM_NINT10, 0 ) AS STM_NINT10 ,
  COALESCE(MP_AUTHS, 0 ) AS MP_AUTHS ,
  COALESCE(MP_BAL, 0 ) AS MP_BAL ,
  COALESCE(MP_REM_PPL, 0 ) AS MP_REM_PPL ,
  COALESCE(BAL_MP, 0 ) AS BAL_MP ,
  COALESCE(STM_BALMP, 0 ) AS STM_BALMP 
 FROM  dw_tdata.CCB_000_ACCX_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  XACCOUNT ,
  BANK ,
  BUSINESS ,
  AGE1 ,
  AGE2 ,
  AGE3 ,
  AGE4 ,
  AGE5 ,
  AGE6 ,
  AUTH_CASH ,
  AUTHS_AMT ,
  BAL_CMPINT ,
  BAL_FREE ,
  BAL_INT ,
  BALINTFLAG ,
  BAL_NOINT ,
  BAL_ORINT ,
  CARD_FEES ,
  CASH_ADFEE ,
  CASH_ADVCE ,
  CASH_TDAY ,
  CATEGORY ,
  CRED_ADJ ,
  CRED_VOUCH ,
  CURR_NUM ,
  DEBIT_ADJ ,
  DUTY_CREDT ,
  DUTY_DEBIT ,
  EXCH_AMT ,
  EXCH_AUTH ,
  EXCH_INQAM ,
  FEES_TAXES ,
  HI_CASHADV ,
  HI_CASMMYY ,
  HI_CRDMMYY ,
  HI_CREDIT ,
  HI_DEBIT ,
  HI_DEBMMYY ,
  HI_OLIMIT ,
  HI_OLIMMYY ,
  HI_PURCHSE ,
  HI_PURMMYY ,
  INT_CASH ,
  INT_CHDCMP ,
  INT_CHGD ,
  INT_CMPOND ,
  INT_CODE ,
  INT_CUNOT ,
  INT_CURCMP ,
  INT_EARNED ,
  INT_NOTION ,
  INT_PROCDY ,
  INT_RATE ,
  INT_RATECR ,
  INT_UPTODY ,
  LAST_TRDAY ,
  LASTNTDATE ,
  LASTPAYAMT ,
  LASTPAYDAY ,
  MONTH_NBR ,
  MTHS_ODUE ,
  NBR_CASHAD ,
  NBR_FEEDTY ,
  NBR_OLIMIT ,
  NBR_OTHERS ,
  NBR_PAYMNT ,
  NBR_PURCH ,
  NBR_TRANS ,
  ODUE_FLAG ,
  ODUE_HELD ,
  OLFLAG ,
  OTHER_FEES ,
  PAY_FLAG ,
  PAYMT_CLRD ,
  PAYMT_TDAY ,
  PAYMT_UNCL ,
  PEN_CHRG ,
  PENCHG_ACC ,
  PURCHASES ,
  QUERY_AMT ,
  QUERY_CODE ,
  QUERY_STMT ,
  STM_AMT_OL ,
  STM_BALFRE ,
  STM_BALINT ,
  STMBALINTFLAG ,
  STM_BALNCE ,
  STM_BALFLAG ,
  STM_BALORI ,
  STM_INSTL ,
  STM_MINDUE ,
  STM_NOINT ,
  STM_OLFLAG ,
  STM_OVERDU ,
  STM_PAY_UN ,
  STM_QRYAMT ,
  STM_REPAY ,
  TODAY_AMT ,
  TODAY_AMTFLAG ,
  TODAY_REL ,
  UNCL_PCT ,
  SHADOW_PEN ,
  SHADOW_INT ,
  SHADOW_CMP ,
  BAL_NINT01 ,
  BAL_NINT02 ,
  BAL_NINT03 ,
  BAL_NINT04 ,
  BAL_NINT05 ,
  BAL_NINT06 ,
  BAL_NINT07 ,
  BAL_NINT08 ,
  BAL_NINT09 ,
  BAL_NINT10 ,
  STM_NINT01 ,
  STM_NINT02 ,
  STM_NINT03 ,
  STM_NINT04 ,
  STM_NINT05 ,
  STM_NINT06 ,
  STM_NINT07 ,
  STM_NINT08 ,
  STM_NINT09 ,
  STM_NINT10 ,
  MP_AUTHS ,
  MP_BAL ,
  MP_REM_PPL ,
  BAL_MP ,
  STM_BALMP 
 FROM dw_sdata.CCB_000_ACCX 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.XACCOUNT = T.XACCOUNT AND N.BANK = T.BANK
WHERE
(T.XACCOUNT IS NULL AND T.BANK IS NULL)
 OR N.BUSINESS<>T.BUSINESS
 OR N.AGE1<>T.AGE1
 OR N.AGE2<>T.AGE2
 OR N.AGE3<>T.AGE3
 OR N.AGE4<>T.AGE4
 OR N.AGE5<>T.AGE5
 OR N.AGE6<>T.AGE6
 OR N.AUTH_CASH<>T.AUTH_CASH
 OR N.AUTHS_AMT<>T.AUTHS_AMT
 OR N.BAL_CMPINT<>T.BAL_CMPINT
 OR N.BAL_FREE<>T.BAL_FREE
 OR N.BAL_INT<>T.BAL_INT
 OR N.BALINTFLAG<>T.BALINTFLAG
 OR N.BAL_NOINT<>T.BAL_NOINT
 OR N.BAL_ORINT<>T.BAL_ORINT
 OR N.CARD_FEES<>T.CARD_FEES
 OR N.CASH_ADFEE<>T.CASH_ADFEE
 OR N.CASH_ADVCE<>T.CASH_ADVCE
 OR N.CASH_TDAY<>T.CASH_TDAY
 OR N.CATEGORY<>T.CATEGORY
 OR N.CRED_ADJ<>T.CRED_ADJ
 OR N.CRED_VOUCH<>T.CRED_VOUCH
 OR N.CURR_NUM<>T.CURR_NUM
 OR N.DEBIT_ADJ<>T.DEBIT_ADJ
 OR N.DUTY_CREDT<>T.DUTY_CREDT
 OR N.DUTY_DEBIT<>T.DUTY_DEBIT
 OR N.EXCH_AMT<>T.EXCH_AMT
 OR N.EXCH_AUTH<>T.EXCH_AUTH
 OR N.EXCH_INQAM<>T.EXCH_INQAM
 OR N.FEES_TAXES<>T.FEES_TAXES
 OR N.HI_CASHADV<>T.HI_CASHADV
 OR N.HI_CASMMYY<>T.HI_CASMMYY
 OR N.HI_CRDMMYY<>T.HI_CRDMMYY
 OR N.HI_CREDIT<>T.HI_CREDIT
 OR N.HI_DEBIT<>T.HI_DEBIT
 OR N.HI_DEBMMYY<>T.HI_DEBMMYY
 OR N.HI_OLIMIT<>T.HI_OLIMIT
 OR N.HI_OLIMMYY<>T.HI_OLIMMYY
 OR N.HI_PURCHSE<>T.HI_PURCHSE
 OR N.HI_PURMMYY<>T.HI_PURMMYY
 OR N.INT_CASH<>T.INT_CASH
 OR N.INT_CHDCMP<>T.INT_CHDCMP
 OR N.INT_CHGD<>T.INT_CHGD
 OR N.INT_CMPOND<>T.INT_CMPOND
 OR N.INT_CODE<>T.INT_CODE
 OR N.INT_CUNOT<>T.INT_CUNOT
 OR N.INT_CURCMP<>T.INT_CURCMP
 OR N.INT_EARNED<>T.INT_EARNED
 OR N.INT_NOTION<>T.INT_NOTION
 OR N.INT_PROCDY<>T.INT_PROCDY
 OR N.INT_RATE<>T.INT_RATE
 OR N.INT_RATECR<>T.INT_RATECR
 OR N.INT_UPTODY<>T.INT_UPTODY
 OR N.LAST_TRDAY<>T.LAST_TRDAY
 OR N.LASTNTDATE<>T.LASTNTDATE
 OR N.LASTPAYAMT<>T.LASTPAYAMT
 OR N.LASTPAYDAY<>T.LASTPAYDAY
 OR N.MONTH_NBR<>T.MONTH_NBR
 OR N.MTHS_ODUE<>T.MTHS_ODUE
 OR N.NBR_CASHAD<>T.NBR_CASHAD
 OR N.NBR_FEEDTY<>T.NBR_FEEDTY
 OR N.NBR_OLIMIT<>T.NBR_OLIMIT
 OR N.NBR_OTHERS<>T.NBR_OTHERS
 OR N.NBR_PAYMNT<>T.NBR_PAYMNT
 OR N.NBR_PURCH<>T.NBR_PURCH
 OR N.NBR_TRANS<>T.NBR_TRANS
 OR N.ODUE_FLAG<>T.ODUE_FLAG
 OR N.ODUE_HELD<>T.ODUE_HELD
 OR N.OLFLAG<>T.OLFLAG
 OR N.OTHER_FEES<>T.OTHER_FEES
 OR N.PAY_FLAG<>T.PAY_FLAG
 OR N.PAYMT_CLRD<>T.PAYMT_CLRD
 OR N.PAYMT_TDAY<>T.PAYMT_TDAY
 OR N.PAYMT_UNCL<>T.PAYMT_UNCL
 OR N.PEN_CHRG<>T.PEN_CHRG
 OR N.PENCHG_ACC<>T.PENCHG_ACC
 OR N.PURCHASES<>T.PURCHASES
 OR N.QUERY_AMT<>T.QUERY_AMT
 OR N.QUERY_CODE<>T.QUERY_CODE
 OR N.QUERY_STMT<>T.QUERY_STMT
 OR N.STM_AMT_OL<>T.STM_AMT_OL
 OR N.STM_BALFRE<>T.STM_BALFRE
 OR N.STM_BALINT<>T.STM_BALINT
 OR N.STMBALINTFLAG<>T.STMBALINTFLAG
 OR N.STM_BALNCE<>T.STM_BALNCE
 OR N.STM_BALFLAG<>T.STM_BALFLAG
 OR N.STM_BALORI<>T.STM_BALORI
 OR N.STM_INSTL<>T.STM_INSTL
 OR N.STM_MINDUE<>T.STM_MINDUE
 OR N.STM_NOINT<>T.STM_NOINT
 OR N.STM_OLFLAG<>T.STM_OLFLAG
 OR N.STM_OVERDU<>T.STM_OVERDU
 OR N.STM_PAY_UN<>T.STM_PAY_UN
 OR N.STM_QRYAMT<>T.STM_QRYAMT
 OR N.STM_REPAY<>T.STM_REPAY
 OR N.TODAY_AMT<>T.TODAY_AMT
 OR N.TODAY_AMTFLAG<>T.TODAY_AMTFLAG
 OR N.TODAY_REL<>T.TODAY_REL
 OR N.UNCL_PCT<>T.UNCL_PCT
 OR N.SHADOW_PEN<>T.SHADOW_PEN
 OR N.SHADOW_INT<>T.SHADOW_INT
 OR N.SHADOW_CMP<>T.SHADOW_CMP
 OR N.BAL_NINT01<>T.BAL_NINT01
 OR N.BAL_NINT02<>T.BAL_NINT02
 OR N.BAL_NINT03<>T.BAL_NINT03
 OR N.BAL_NINT04<>T.BAL_NINT04
 OR N.BAL_NINT05<>T.BAL_NINT05
 OR N.BAL_NINT06<>T.BAL_NINT06
 OR N.BAL_NINT07<>T.BAL_NINT07
 OR N.BAL_NINT08<>T.BAL_NINT08
 OR N.BAL_NINT09<>T.BAL_NINT09
 OR N.BAL_NINT10<>T.BAL_NINT10
 OR N.STM_NINT01<>T.STM_NINT01
 OR N.STM_NINT02<>T.STM_NINT02
 OR N.STM_NINT03<>T.STM_NINT03
 OR N.STM_NINT04<>T.STM_NINT04
 OR N.STM_NINT05<>T.STM_NINT05
 OR N.STM_NINT06<>T.STM_NINT06
 OR N.STM_NINT07<>T.STM_NINT07
 OR N.STM_NINT08<>T.STM_NINT08
 OR N.STM_NINT09<>T.STM_NINT09
 OR N.STM_NINT10<>T.STM_NINT10
 OR N.MP_AUTHS<>T.MP_AUTHS
 OR N.MP_BAL<>T.MP_BAL
 OR N.MP_REM_PPL<>T.MP_REM_PPL
 OR N.BAL_MP<>T.BAL_MP
 OR N.STM_BALMP<>T.STM_BALMP
;

--Step3:
UPDATE dw_sdata.CCB_000_ACCX P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_84
WHERE P.End_Dt=DATE('2100-12-31')
AND P.XACCOUNT=T_84.XACCOUNT
AND P.BANK=T_84.BANK
;

--Step4:
INSERT  INTO dw_sdata.CCB_000_ACCX SELECT * FROM T_84;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
