#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCB_000_MERCH WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCB_000_MERCH SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_96 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCB_000_MERCH WHERE 1=0;

--Step2:
INSERT  INTO T_96 (
  CUSTR_NBR,
  MATRIX,
  MERCHANT,
  OWN_BANK,
  OWN_MERCH,
  A_ADJ_CU,
  A_CRFEE_A1,
  A_CRFEE_A2,
  A_CRV_CU_A1,
  A_CRV_CU_A2,
  A_DEP_CU_A1,
  A_DEP_CU_A2,
  A_DRFEE_A1,
  A_DRFEE_A2,
  A_DRV_CU_A1,
  A_DRV_CU_A2,
  A_ERR_CU_A1,
  A_ERR_CU_A2,
  A_RTFEE_A1,
  A_RTFEE_A2,
  ACPTOR_ID,
  ADMIN_CONT,
  BRANCH,
  CL_IND,
  CLOSE_RSN,
  CONTRACT,
  CORP_NAME,
  CURR_NUM,
  DAY_CLOSED,
  DAY_END,
  DAY_OPENED,
  DAY_START,
  DBA_ADDR1,
  DBA_ADDR2,
  DBA_ADDR3,
  DBA_ADDR4,
  DBA_CITY,
  DBA_CNTRY,
  DBA_NAME,
  DBA_PCODE,
  DBA_PH_NBR,
  DBA_PHAREA,
  DBA_STATEC,
  DEP_ACCT,
  DEP_OVER,
  DISC_RATE,
  HO_MMSFCD,
  HO_RATE,
  INTVL_DAYS,
  MER_TYPE,
  MMSF,
  MON_CODE,
  MP_IND,
  N_CRFEE_A1,
  N_CRFEE_A2,
  N_CRV_CU_A1,
  N_CRV_CU_A,
  N_DEP_CU_A1,
  N_DEP_CU_A2,
  N_DRFEE_A1,
  N_DRFEE_A2,
  N_DRV_CU_A1,
  N_DRV_CU_A2,
  N_ERR_CU_A1,
  N_ERR_CU_A2,
  N_RTFEE_A1,
  N_RTFEE_A2,
  OTH_ADDR,
  REC_TYPE,
  STAT_CODE,
  start_dt,
  end_dt)
SELECT
  N.CUSTR_NBR,
  N.MATRIX,
  N.MERCHANT,
  N.OWN_BANK,
  N.OWN_MERCH,
  N.A_ADJ_CU,
  N.A_CRFEE_A1,
  N.A_CRFEE_A2,
  N.A_CRV_CU_A1,
  N.A_CRV_CU_A2,
  N.A_DEP_CU_A1,
  N.A_DEP_CU_A2,
  N.A_DRFEE_A1,
  N.A_DRFEE_A2,
  N.A_DRV_CU_A1,
  N.A_DRV_CU_A2,
  N.A_ERR_CU_A1,
  N.A_ERR_CU_A2,
  N.A_RTFEE_A1,
  N.A_RTFEE_A2,
  N.ACPTOR_ID,
  N.ADMIN_CONT,
  N.BRANCH,
  N.CL_IND,
  N.CLOSE_RSN,
  N.CONTRACT,
  N.CORP_NAME,
  N.CURR_NUM,
  N.DAY_CLOSED,
  N.DAY_END,
  N.DAY_OPENED,
  N.DAY_START,
  N.DBA_ADDR1,
  N.DBA_ADDR2,
  N.DBA_ADDR3,
  N.DBA_ADDR4,
  N.DBA_CITY,
  N.DBA_CNTRY,
  N.DBA_NAME,
  N.DBA_PCODE,
  N.DBA_PH_NBR,
  N.DBA_PHAREA,
  N.DBA_STATEC,
  N.DEP_ACCT,
  N.DEP_OVER,
  N.DISC_RATE,
  N.HO_MMSFCD,
  N.HO_RATE,
  N.INTVL_DAYS,
  N.MER_TYPE,
  N.MMSF,
  N.MON_CODE,
  N.MP_IND,
  N.N_CRFEE_A1,
  N.N_CRFEE_A2,
  N.N_CRV_CU_A1,
  N.N_CRV_CU_A,
  N.N_DEP_CU_A1,
  N.N_DEP_CU_A2,
  N.N_DRFEE_A1,
  N.N_DRFEE_A2,
  N.N_DRV_CU_A1,
  N.N_DRV_CU_A2,
  N.N_ERR_CU_A1,
  N.N_ERR_CU_A2,
  N.N_RTFEE_A1,
  N.N_RTFEE_A2,
  N.OTH_ADDR,
  N.REC_TYPE,
  N.STAT_CODE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(CUSTR_NBR, '' ) AS CUSTR_NBR ,
  COALESCE(MATRIX, 0 ) AS MATRIX ,
  COALESCE(MERCHANT, '' ) AS MERCHANT ,
  COALESCE(OWN_BANK, 0 ) AS OWN_BANK ,
  COALESCE(OWN_MERCH, '' ) AS OWN_MERCH ,
  COALESCE(A_ADJ_CU, 0 ) AS A_ADJ_CU ,
  COALESCE(A_CRFEE_A1, 0 ) AS A_CRFEE_A1 ,
  COALESCE(A_CRFEE_A2, 0 ) AS A_CRFEE_A2 ,
  COALESCE(A_CRV_CU_A1, 0 ) AS A_CRV_CU_A1 ,
  COALESCE(A_CRV_CU_A2, 0 ) AS A_CRV_CU_A2 ,
  COALESCE(A_DEP_CU_A1, 0 ) AS A_DEP_CU_A1 ,
  COALESCE(A_DEP_CU_A2, 0 ) AS A_DEP_CU_A2 ,
  COALESCE(A_DRFEE_A1, 0 ) AS A_DRFEE_A1 ,
  COALESCE(A_DRFEE_A2, 0 ) AS A_DRFEE_A2 ,
  COALESCE(A_DRV_CU_A1, 0 ) AS A_DRV_CU_A1 ,
  COALESCE(A_DRV_CU_A2, 0 ) AS A_DRV_CU_A2 ,
  COALESCE(A_ERR_CU_A1, 0 ) AS A_ERR_CU_A1 ,
  COALESCE(A_ERR_CU_A2, 0 ) AS A_ERR_CU_A2 ,
  COALESCE(A_RTFEE_A1, 0 ) AS A_RTFEE_A1 ,
  COALESCE(A_RTFEE_A2, 0 ) AS A_RTFEE_A2 ,
  COALESCE(ACPTOR_ID, '' ) AS ACPTOR_ID ,
  COALESCE(ADMIN_CONT, '' ) AS ADMIN_CONT ,
  COALESCE(BRANCH, 0 ) AS BRANCH ,
  COALESCE(CL_IND, '' ) AS CL_IND ,
  COALESCE(CLOSE_RSN, '' ) AS CLOSE_RSN ,
  COALESCE(CONTRACT, '' ) AS CONTRACT ,
  COALESCE(CORP_NAME, '' ) AS CORP_NAME ,
  COALESCE(CURR_NUM, 0 ) AS CURR_NUM ,
  COALESCE(DAY_CLOSED, 0 ) AS DAY_CLOSED ,
  COALESCE(DAY_END, 0 ) AS DAY_END ,
  COALESCE(DAY_OPENED, 0 ) AS DAY_OPENED ,
  COALESCE(DAY_START, 0 ) AS DAY_START ,
  COALESCE(DBA_ADDR1, '' ) AS DBA_ADDR1 ,
  COALESCE(DBA_ADDR2, '' ) AS DBA_ADDR2 ,
  COALESCE(DBA_ADDR3, '' ) AS DBA_ADDR3 ,
  COALESCE(DBA_ADDR4, '' ) AS DBA_ADDR4 ,
  COALESCE(DBA_CITY, '' ) AS DBA_CITY ,
  COALESCE(DBA_CNTRY, '' ) AS DBA_CNTRY ,
  COALESCE(DBA_NAME, '' ) AS DBA_NAME ,
  COALESCE(DBA_PCODE, 0 ) AS DBA_PCODE ,
  COALESCE(DBA_PH_NBR, '' ) AS DBA_PH_NBR ,
  COALESCE(DBA_PHAREA, '' ) AS DBA_PHAREA ,
  COALESCE(DBA_STATEC, '' ) AS DBA_STATEC ,
  COALESCE(DEP_ACCT, '' ) AS DEP_ACCT ,
  COALESCE(DEP_OVER, 0 ) AS DEP_OVER ,
  COALESCE(DISC_RATE, 0 ) AS DISC_RATE ,
  COALESCE(HO_MMSFCD, '' ) AS HO_MMSFCD ,
  COALESCE(HO_RATE, 0 ) AS HO_RATE ,
  COALESCE(INTVL_DAYS, 0 ) AS INTVL_DAYS ,
  COALESCE(MER_TYPE, 0 ) AS MER_TYPE ,
  COALESCE(MMSF, 0 ) AS MMSF ,
  COALESCE(MON_CODE, '' ) AS MON_CODE ,
  COALESCE(MP_IND, '' ) AS MP_IND ,
  COALESCE(N_CRFEE_A1, 0 ) AS N_CRFEE_A1 ,
  COALESCE(N_CRFEE_A2, 0 ) AS N_CRFEE_A2 ,
  COALESCE(N_CRV_CU_A1, 0 ) AS N_CRV_CU_A1 ,
  COALESCE(N_CRV_CU_A, 0 ) AS N_CRV_CU_A ,
  COALESCE(N_DEP_CU_A1, 0 ) AS N_DEP_CU_A1 ,
  COALESCE(N_DEP_CU_A2, 0 ) AS N_DEP_CU_A2 ,
  COALESCE(N_DRFEE_A1, 0 ) AS N_DRFEE_A1 ,
  COALESCE(N_DRFEE_A2, 0 ) AS N_DRFEE_A2 ,
  COALESCE(N_DRV_CU_A1, 0 ) AS N_DRV_CU_A1 ,
  COALESCE(N_DRV_CU_A2, 0 ) AS N_DRV_CU_A2 ,
  COALESCE(N_ERR_CU_A1, 0 ) AS N_ERR_CU_A1 ,
  COALESCE(N_ERR_CU_A2, 0 ) AS N_ERR_CU_A2 ,
  COALESCE(N_RTFEE_A1, 0 ) AS N_RTFEE_A1 ,
  COALESCE(N_RTFEE_A2, 0 ) AS N_RTFEE_A2 ,
  COALESCE(OTH_ADDR, '' ) AS OTH_ADDR ,
  COALESCE(REC_TYPE, '' ) AS REC_TYPE ,
  COALESCE(STAT_CODE, '' ) AS STAT_CODE 
 FROM  dw_tdata.CCB_000_MERCH_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  CUSTR_NBR ,
  MATRIX ,
  MERCHANT ,
  OWN_BANK ,
  OWN_MERCH ,
  A_ADJ_CU ,
  A_CRFEE_A1 ,
  A_CRFEE_A2 ,
  A_CRV_CU_A1 ,
  A_CRV_CU_A2 ,
  A_DEP_CU_A1 ,
  A_DEP_CU_A2 ,
  A_DRFEE_A1 ,
  A_DRFEE_A2 ,
  A_DRV_CU_A1 ,
  A_DRV_CU_A2 ,
  A_ERR_CU_A1 ,
  A_ERR_CU_A2 ,
  A_RTFEE_A1 ,
  A_RTFEE_A2 ,
  ACPTOR_ID ,
  ADMIN_CONT ,
  BRANCH ,
  CL_IND ,
  CLOSE_RSN ,
  CONTRACT ,
  CORP_NAME ,
  CURR_NUM ,
  DAY_CLOSED ,
  DAY_END ,
  DAY_OPENED ,
  DAY_START ,
  DBA_ADDR1 ,
  DBA_ADDR2 ,
  DBA_ADDR3 ,
  DBA_ADDR4 ,
  DBA_CITY ,
  DBA_CNTRY ,
  DBA_NAME ,
  DBA_PCODE ,
  DBA_PH_NBR ,
  DBA_PHAREA ,
  DBA_STATEC ,
  DEP_ACCT ,
  DEP_OVER ,
  DISC_RATE ,
  HO_MMSFCD ,
  HO_RATE ,
  INTVL_DAYS ,
  MER_TYPE ,
  MMSF ,
  MON_CODE ,
  MP_IND ,
  N_CRFEE_A1 ,
  N_CRFEE_A2 ,
  N_CRV_CU_A1 ,
  N_CRV_CU_A ,
  N_DEP_CU_A1 ,
  N_DEP_CU_A2 ,
  N_DRFEE_A1 ,
  N_DRFEE_A2 ,
  N_DRV_CU_A1 ,
  N_DRV_CU_A2 ,
  N_ERR_CU_A1 ,
  N_ERR_CU_A2 ,
  N_RTFEE_A1 ,
  N_RTFEE_A2 ,
  OTH_ADDR ,
  REC_TYPE ,
  STAT_CODE 
 FROM dw_sdata.CCB_000_MERCH 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.MERCHANT = T.MERCHANT
WHERE
(T.MERCHANT IS NULL)
 OR N.CUSTR_NBR<>T.CUSTR_NBR
 OR N.MATRIX<>T.MATRIX
 OR N.OWN_BANK<>T.OWN_BANK
 OR N.OWN_MERCH<>T.OWN_MERCH
 OR N.A_ADJ_CU<>T.A_ADJ_CU
 OR N.A_CRFEE_A1<>T.A_CRFEE_A1
 OR N.A_CRFEE_A2<>T.A_CRFEE_A2
 OR N.A_CRV_CU_A1<>T.A_CRV_CU_A1
 OR N.A_CRV_CU_A2<>T.A_CRV_CU_A2
 OR N.A_DEP_CU_A1<>T.A_DEP_CU_A1
 OR N.A_DEP_CU_A2<>T.A_DEP_CU_A2
 OR N.A_DRFEE_A1<>T.A_DRFEE_A1
 OR N.A_DRFEE_A2<>T.A_DRFEE_A2
 OR N.A_DRV_CU_A1<>T.A_DRV_CU_A1
 OR N.A_DRV_CU_A2<>T.A_DRV_CU_A2
 OR N.A_ERR_CU_A1<>T.A_ERR_CU_A1
 OR N.A_ERR_CU_A2<>T.A_ERR_CU_A2
 OR N.A_RTFEE_A1<>T.A_RTFEE_A1
 OR N.A_RTFEE_A2<>T.A_RTFEE_A2
 OR N.ACPTOR_ID<>T.ACPTOR_ID
 OR N.ADMIN_CONT<>T.ADMIN_CONT
 OR N.BRANCH<>T.BRANCH
 OR N.CL_IND<>T.CL_IND
 OR N.CLOSE_RSN<>T.CLOSE_RSN
 OR N.CONTRACT<>T.CONTRACT
 OR N.CORP_NAME<>T.CORP_NAME
 OR N.CURR_NUM<>T.CURR_NUM
 OR N.DAY_CLOSED<>T.DAY_CLOSED
 OR N.DAY_END<>T.DAY_END
 OR N.DAY_OPENED<>T.DAY_OPENED
 OR N.DAY_START<>T.DAY_START
 OR N.DBA_ADDR1<>T.DBA_ADDR1
 OR N.DBA_ADDR2<>T.DBA_ADDR2
 OR N.DBA_ADDR3<>T.DBA_ADDR3
 OR N.DBA_ADDR4<>T.DBA_ADDR4
 OR N.DBA_CITY<>T.DBA_CITY
 OR N.DBA_CNTRY<>T.DBA_CNTRY
 OR N.DBA_NAME<>T.DBA_NAME
 OR N.DBA_PCODE<>T.DBA_PCODE
 OR N.DBA_PH_NBR<>T.DBA_PH_NBR
 OR N.DBA_PHAREA<>T.DBA_PHAREA
 OR N.DBA_STATEC<>T.DBA_STATEC
 OR N.DEP_ACCT<>T.DEP_ACCT
 OR N.DEP_OVER<>T.DEP_OVER
 OR N.DISC_RATE<>T.DISC_RATE
 OR N.HO_MMSFCD<>T.HO_MMSFCD
 OR N.HO_RATE<>T.HO_RATE
 OR N.INTVL_DAYS<>T.INTVL_DAYS
 OR N.MER_TYPE<>T.MER_TYPE
 OR N.MMSF<>T.MMSF
 OR N.MON_CODE<>T.MON_CODE
 OR N.MP_IND<>T.MP_IND
 OR N.N_CRFEE_A1<>T.N_CRFEE_A1
 OR N.N_CRFEE_A2<>T.N_CRFEE_A2
 OR N.N_CRV_CU_A1<>T.N_CRV_CU_A1
 OR N.N_CRV_CU_A<>T.N_CRV_CU_A
 OR N.N_DEP_CU_A1<>T.N_DEP_CU_A1
 OR N.N_DEP_CU_A2<>T.N_DEP_CU_A2
 OR N.N_DRFEE_A1<>T.N_DRFEE_A1
 OR N.N_DRFEE_A2<>T.N_DRFEE_A2
 OR N.N_DRV_CU_A1<>T.N_DRV_CU_A1
 OR N.N_DRV_CU_A2<>T.N_DRV_CU_A2
 OR N.N_ERR_CU_A1<>T.N_ERR_CU_A1
 OR N.N_ERR_CU_A2<>T.N_ERR_CU_A2
 OR N.N_RTFEE_A1<>T.N_RTFEE_A1
 OR N.N_RTFEE_A2<>T.N_RTFEE_A2
 OR N.OTH_ADDR<>T.OTH_ADDR
 OR N.REC_TYPE<>T.REC_TYPE
 OR N.STAT_CODE<>T.STAT_CODE
;

--Step3:
UPDATE dw_sdata.CCB_000_MERCH P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_96
WHERE P.End_Dt=DATE('2100-12-31')
AND P.MERCHANT=T_96.MERCHANT
;

--Step4:
INSERT  INTO dw_sdata.CCB_000_MERCH SELECT * FROM T_96;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
