#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCB_000_ACCT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCB_000_ACCT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_83 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCB_000_ACCT WHERE 1=0;

--Step2:
INSERT  INTO T_83 (
  XACCOUNT,
  BANK,
  BUSINESS,
  CATEGORY,
  CUSTR_NBR,
  CYCLE_NBR,
  DAY_OPENED,
  ACC_NAME1,
  ACC_TYPE,
  ADD_CHGDAY,
  ADDR_TYPE,
  ADDR_TYPE2,
  AGE1,
  AGE2,
  AGE3,
  AGE4,
  AGE5,
  AGE6,
  APP_SOURCE,
  AUTH_CASH,
  AUTH_OVER,
  AUTHOV_YN,
  AUTHS_AMT,
  BAL_CMPINT,
  BAL_FREE,
  BAL_INT,
  BAL_INTFLAG,
  BAL_NOINT,
  BAL_ORINT,
  BANKACCT1,
  BANKCODE1,
  BANKACCT2,
  BANKCODE2,
  BANKACCT3,
  BANKCODE3,
  BANKACCT4,
  BANKCODE4,
  BRANCH,
  BRANCH_DAY,
  CA_PCNT,
  CARD_FEES,
  CARDS_CANC,
  CARDS_ISSD,
  CASH_1ST,
  CASH_ADFEE,
  CASH_ADVCE,
  CASH_TDAY,
  CASH1STAC,
  CLASS_CHDY,
  CLASS_CODE,
  CLOSE_CHDY,
  CLOSE_CODE,
  COLLS_DAY,
  CRDACT_DAY,
  CRDNXT_DAY,
  CRED_ACTIV,
  CRED_ADJ,
  CRED_CHDAY,
  CRED_LIMIT,
  CRED_VOUCH,
  CREDLIM_X,
  CURR_NUM,
  CUTOFF_DAY,
  CY_CHGCNT,
  CY_CHGDAY,
  CY_EFFDAY,
  CY_YRCNT,
  CYCLE_NEW,
  CYCLE_PRV,
  DEBIT_ADJ,
  DISHNRDAY,
  DUTY_CREDT,
  DUTY_DEBIT,
  EXCH_CODE,
  EXCH_FLAG,
  EXCH_PERC,
  EXCH_RTDT,
  FEE_MONTH,
  FEES_TAXES,
  FIX_EXAMT,
  GUARN_FLAG,
  HI_CASHADV,
  HI_CASMMYY,
  HI_CRDMMYY,
  HI_CREDIT,
  HI_DEBIT,
  HI_DEBMMYY,
  HI_MP_PUR,
  HI_MPMMYY,
  HI_OLIMIT,
  HI_OLIMMYY,
  HI_PURCHSE,
  HI_PURMMYY,
  INT_CASH,
  INT_CHDCMP,
  INT_CHDY,
  INT_CHGD,
  INT_CMPOND,
  INT_CODE,
  INT_CUNOT,
  INT_CURCMP,
  INT_EARNED,
  INT_NOTION,
  INT_PROCDY,
  INT_RATE,
  INT_RATECR,
  INT_UPTODY,
  LANG_CODE,
  LAST_TRDAY,
  LASTAUTHDY,
  LASTNTDATE,
  LASTPAYAMT,
  LASTPAYDAY,
  LOSSES,
  MONTH_NBR,
  MONTR_CHDY,
  MONTR_CODE,
  MP_AM_TDY,
  MP_AUTHS,
  MP_BAL,
  MP_BIL_AMT,
  MP_LIMIT,
  MP_NO_TDY,
  MP_REM_PPL,
  MPLM_CHDAY,
  MTHS_ODUE,
  NBR_CASHAD,
  NBR_FEEDTY,
  NBR_OLIMIT,
  NBR_OTHERS,
  NBR_PAYMNT,
  NBR_PURCH,
  NBR_TRANS,
  OCT_COUNT,
  OCT_DAYIN,
  ODUE_FLAG,
  ODUE_HELD,
  OLFLAG,
  OTHER_FEES,
  PAY_FLAG,
  PAY1ST_IND,
  PAYMT_CLRD,
  PAYMT_TDAY,
  PAYMT_UNCL,
  PEN_CHRG,
  PENCHG_ACC,
  POINT_ADJ,
  PT_ADJFLAG,
  POINT_CLM,
  POINT_CUM,
  PT_CUMFLAG,
  POINT_CUM2,
  POINT_EAR,
  POINT_FREZ,
  POINT_FZDA,
  POST_DD,
  PREV_BRDAY,
  PREV_BRNCH,
  PURCHASES,
  QUERY_AMT,
  QUERY_CODE,
  QUERY_STMT,
  RECLA_CHDY,
  RECLA_CODE,
  RECVRY_AMT,
  REPAY_AMT,
  REPAY_AMTX,
  REPAY_CODE,
  REPAY_CODX,
  REPAY_DAY,
  REPAY_PCT,
  REPAY_PCTX,
  REPY_CHGDY,
  SCORE_PTS,
  STATEMENTS,
  STM_AMT_OL,
  STM_BALFRE,
  STM_BALINT,
  STMBALINTFLAG,
  STM_BALNCE,
  STM_BALFLAG,
  STM_BALORI,
  STM_CLOSDY,
  STM_CODE,
  STM_INSTL,
  STM_MINDUE,
  STM_NOINT,
  STM_OLFLAG,
  STM_OVERDU,
  STM_PAY_UN,
  STM_QRYAMT,
  STM_REPAY,
  STMT_DD,
  STMT_PULL,
  TODAY_AMT,
  TODAY_AMTFLAG,
  TODAY_REL,
  UNCL_PCT,
  WROFF_CHDY,
  WROFF_CODE,
  PROD_LEVEL,
  PROD_NBR,
  ACCT_PRSTS,
  ACCT_STS,
  APP_APQUE,
  POINT_ENC,
  POINT_IMP,
  POINT_EXP,
  PT_EXPFLAG,
  RISK_COUNT,
  RISK_DAYIN,
  BAL_MP,
  BAL_MPFLAG,
  STM_BALMP,
  STM_BMFLAG,
  LMT_RSN,
  POINT_CARD,
  PT_CDFLAG,
  TEMP_LIMIT,
  TLMT_BEG,
  TLMT_END,
  TLMT_NO,
  CANCL_RESN,
  SHADOW_PEN,
  SHADOW_INT,
  SHADOW_CMP,
  BAL_NINT01,
  BAL_NINT02,
  BAL_NINT03,
  BAL_NINT04,
  BAL_NINT05,
  BAL_NINT06,
  BAL_NINT07,
  BAL_NINT08,
  BAL_NINT09,
  BAL_NINT10,
  STM_NINT01,
  STM_NINT02,
  STM_NINT03,
  STM_NINT04,
  STM_NINT05,
  STM_NINT06,
  STM_NINT07,
  STM_NINT08,
  STM_NINT09,
  STM_NINT10,
  CURR_NUM2,
  WROF_FLAG,
  LAYERCODER1,
  LAYERCODER2,
  MCNTRL_YN,
  NCRED_RSN,
  BSC_CRED,
  CUSTR_REF,
  PBC_BRNCH,
  STOPMP_YN,
  CRED_LMT2,
  BAL_CMPFEE,
  BAL_LMP,
  STM_LMP,
  OUT_MONTH,
  ETL_DAY,
  STPAY,
  start_dt,
  end_dt)
SELECT
  N.XACCOUNT,
  N.BANK,
  N.BUSINESS,
  N.CATEGORY,
  N.CUSTR_NBR,
  N.CYCLE_NBR,
  N.DAY_OPENED,
  N.ACC_NAME1,
  N.ACC_TYPE,
  N.ADD_CHGDAY,
  N.ADDR_TYPE,
  N.ADDR_TYPE2,
  N.AGE1,
  N.AGE2,
  N.AGE3,
  N.AGE4,
  N.AGE5,
  N.AGE6,
  N.APP_SOURCE,
  N.AUTH_CASH,
  N.AUTH_OVER,
  N.AUTHOV_YN,
  N.AUTHS_AMT,
  N.BAL_CMPINT,
  N.BAL_FREE,
  N.BAL_INT,
  N.BAL_INTFLAG,
  N.BAL_NOINT,
  N.BAL_ORINT,
  N.BANKACCT1,
  N.BANKCODE1,
  N.BANKACCT2,
  N.BANKCODE2,
  N.BANKACCT3,
  N.BANKCODE3,
  N.BANKACCT4,
  N.BANKCODE4,
  N.BRANCH,
  N.BRANCH_DAY,
  N.CA_PCNT,
  N.CARD_FEES,
  N.CARDS_CANC,
  N.CARDS_ISSD,
  N.CASH_1ST,
  N.CASH_ADFEE,
  N.CASH_ADVCE,
  N.CASH_TDAY,
  N.CASH1STAC,
  N.CLASS_CHDY,
  N.CLASS_CODE,
  N.CLOSE_CHDY,
  N.CLOSE_CODE,
  N.COLLS_DAY,
  N.CRDACT_DAY,
  N.CRDNXT_DAY,
  N.CRED_ACTIV,
  N.CRED_ADJ,
  N.CRED_CHDAY,
  N.CRED_LIMIT,
  N.CRED_VOUCH,
  N.CREDLIM_X,
  N.CURR_NUM,
  N.CUTOFF_DAY,
  N.CY_CHGCNT,
  N.CY_CHGDAY,
  N.CY_EFFDAY,
  N.CY_YRCNT,
  N.CYCLE_NEW,
  N.CYCLE_PRV,
  N.DEBIT_ADJ,
  N.DISHNRDAY,
  N.DUTY_CREDT,
  N.DUTY_DEBIT,
  N.EXCH_CODE,
  N.EXCH_FLAG,
  N.EXCH_PERC,
  N.EXCH_RTDT,
  N.FEE_MONTH,
  N.FEES_TAXES,
  N.FIX_EXAMT,
  N.GUARN_FLAG,
  N.HI_CASHADV,
  N.HI_CASMMYY,
  N.HI_CRDMMYY,
  N.HI_CREDIT,
  N.HI_DEBIT,
  N.HI_DEBMMYY,
  N.HI_MP_PUR,
  N.HI_MPMMYY,
  N.HI_OLIMIT,
  N.HI_OLIMMYY,
  N.HI_PURCHSE,
  N.HI_PURMMYY,
  N.INT_CASH,
  N.INT_CHDCMP,
  N.INT_CHDY,
  N.INT_CHGD,
  N.INT_CMPOND,
  N.INT_CODE,
  N.INT_CUNOT,
  N.INT_CURCMP,
  N.INT_EARNED,
  N.INT_NOTION,
  N.INT_PROCDY,
  N.INT_RATE,
  N.INT_RATECR,
  N.INT_UPTODY,
  N.LANG_CODE,
  N.LAST_TRDAY,
  N.LASTAUTHDY,
  N.LASTNTDATE,
  N.LASTPAYAMT,
  N.LASTPAYDAY,
  N.LOSSES,
  N.MONTH_NBR,
  N.MONTR_CHDY,
  N.MONTR_CODE,
  N.MP_AM_TDY,
  N.MP_AUTHS,
  N.MP_BAL,
  N.MP_BIL_AMT,
  N.MP_LIMIT,
  N.MP_NO_TDY,
  N.MP_REM_PPL,
  N.MPLM_CHDAY,
  N.MTHS_ODUE,
  N.NBR_CASHAD,
  N.NBR_FEEDTY,
  N.NBR_OLIMIT,
  N.NBR_OTHERS,
  N.NBR_PAYMNT,
  N.NBR_PURCH,
  N.NBR_TRANS,
  N.OCT_COUNT,
  N.OCT_DAYIN,
  N.ODUE_FLAG,
  N.ODUE_HELD,
  N.OLFLAG,
  N.OTHER_FEES,
  N.PAY_FLAG,
  N.PAY1ST_IND,
  N.PAYMT_CLRD,
  N.PAYMT_TDAY,
  N.PAYMT_UNCL,
  N.PEN_CHRG,
  N.PENCHG_ACC,
  N.POINT_ADJ,
  N.PT_ADJFLAG,
  N.POINT_CLM,
  N.POINT_CUM,
  N.PT_CUMFLAG,
  N.POINT_CUM2,
  N.POINT_EAR,
  N.POINT_FREZ,
  N.POINT_FZDA,
  N.POST_DD,
  N.PREV_BRDAY,
  N.PREV_BRNCH,
  N.PURCHASES,
  N.QUERY_AMT,
  N.QUERY_CODE,
  N.QUERY_STMT,
  N.RECLA_CHDY,
  N.RECLA_CODE,
  N.RECVRY_AMT,
  N.REPAY_AMT,
  N.REPAY_AMTX,
  N.REPAY_CODE,
  N.REPAY_CODX,
  N.REPAY_DAY,
  N.REPAY_PCT,
  N.REPAY_PCTX,
  N.REPY_CHGDY,
  N.SCORE_PTS,
  N.STATEMENTS,
  N.STM_AMT_OL,
  N.STM_BALFRE,
  N.STM_BALINT,
  N.STMBALINTFLAG,
  N.STM_BALNCE,
  N.STM_BALFLAG,
  N.STM_BALORI,
  N.STM_CLOSDY,
  N.STM_CODE,
  N.STM_INSTL,
  N.STM_MINDUE,
  N.STM_NOINT,
  N.STM_OLFLAG,
  N.STM_OVERDU,
  N.STM_PAY_UN,
  N.STM_QRYAMT,
  N.STM_REPAY,
  N.STMT_DD,
  N.STMT_PULL,
  N.TODAY_AMT,
  N.TODAY_AMTFLAG,
  N.TODAY_REL,
  N.UNCL_PCT,
  N.WROFF_CHDY,
  N.WROFF_CODE,
  N.PROD_LEVEL,
  N.PROD_NBR,
  N.ACCT_PRSTS,
  N.ACCT_STS,
  N.APP_APQUE,
  N.POINT_ENC,
  N.POINT_IMP,
  N.POINT_EXP,
  N.PT_EXPFLAG,
  N.RISK_COUNT,
  N.RISK_DAYIN,
  N.BAL_MP,
  N.BAL_MPFLAG,
  N.STM_BALMP,
  N.STM_BMFLAG,
  N.LMT_RSN,
  N.POINT_CARD,
  N.PT_CDFLAG,
  N.TEMP_LIMIT,
  N.TLMT_BEG,
  N.TLMT_END,
  N.TLMT_NO,
  N.CANCL_RESN,
  N.SHADOW_PEN,
  N.SHADOW_INT,
  N.SHADOW_CMP,
  N.BAL_NINT01,
  N.BAL_NINT02,
  N.BAL_NINT03,
  N.BAL_NINT04,
  N.BAL_NINT05,
  N.BAL_NINT06,
  N.BAL_NINT07,
  N.BAL_NINT08,
  N.BAL_NINT09,
  N.BAL_NINT10,
  N.STM_NINT01,
  N.STM_NINT02,
  N.STM_NINT03,
  N.STM_NINT04,
  N.STM_NINT05,
  N.STM_NINT06,
  N.STM_NINT07,
  N.STM_NINT08,
  N.STM_NINT09,
  N.STM_NINT10,
  N.CURR_NUM2,
  N.WROF_FLAG,
  N.LAYERCODER1,
  N.LAYERCODER2,
  N.MCNTRL_YN,
  N.NCRED_RSN,
  N.BSC_CRED,
  N.CUSTR_REF,
  N.PBC_BRNCH,
  N.STOPMP_YN,
  N.CRED_LMT2,
  N.BAL_CMPFEE,
  N.BAL_LMP,
  N.STM_LMP,
  N.OUT_MONTH,
  N.ETL_DAY,
  N.STPAY,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(XACCOUNT, 0 ) AS XACCOUNT ,
  COALESCE(BANK, 0 ) AS BANK ,
  COALESCE(BUSINESS, '' ) AS BUSINESS ,
  COALESCE(CATEGORY, 0 ) AS CATEGORY ,
  COALESCE(CUSTR_NBR, '' ) AS CUSTR_NBR ,
  COALESCE(CYCLE_NBR, 0 ) AS CYCLE_NBR ,
  COALESCE(DAY_OPENED, 0 ) AS DAY_OPENED ,
  COALESCE(ACC_NAME1, '' ) AS ACC_NAME1 ,
  COALESCE(ACC_TYPE, '' ) AS ACC_TYPE ,
  COALESCE(ADD_CHGDAY, 0 ) AS ADD_CHGDAY ,
  COALESCE(ADDR_TYPE, '' ) AS ADDR_TYPE ,
  COALESCE(ADDR_TYPE2, '' ) AS ADDR_TYPE2 ,
  COALESCE(AGE1, 0 ) AS AGE1 ,
  COALESCE(AGE2, 0 ) AS AGE2 ,
  COALESCE(AGE3, 0 ) AS AGE3 ,
  COALESCE(AGE4, 0 ) AS AGE4 ,
  COALESCE(AGE5, 0 ) AS AGE5 ,
  COALESCE(AGE6, 0 ) AS AGE6 ,
  COALESCE(APP_SOURCE, '' ) AS APP_SOURCE ,
  COALESCE(AUTH_CASH, 0 ) AS AUTH_CASH ,
  COALESCE(AUTH_OVER, 0 ) AS AUTH_OVER ,
  COALESCE(AUTHOV_YN, '' ) AS AUTHOV_YN ,
  COALESCE(AUTHS_AMT, 0 ) AS AUTHS_AMT ,
  COALESCE(BAL_CMPINT, 0 ) AS BAL_CMPINT ,
  COALESCE(BAL_FREE, 0 ) AS BAL_FREE ,
  COALESCE(BAL_INT, 0 ) AS BAL_INT ,
  COALESCE(BAL_INTFLAG, '' ) AS BAL_INTFLAG ,
  COALESCE(BAL_NOINT, 0 ) AS BAL_NOINT ,
  COALESCE(BAL_ORINT, 0 ) AS BAL_ORINT ,
  COALESCE(BANKACCT1, '' ) AS BANKACCT1 ,
  COALESCE(BANKCODE1, '' ) AS BANKCODE1 ,
  COALESCE(BANKACCT2, '' ) AS BANKACCT2 ,
  COALESCE(BANKCODE2, '' ) AS BANKCODE2 ,
  COALESCE(BANKACCT3, '' ) AS BANKACCT3 ,
  COALESCE(BANKCODE3, '' ) AS BANKCODE3 ,
  COALESCE(BANKACCT4, '' ) AS BANKACCT4 ,
  COALESCE(BANKCODE4, '' ) AS BANKCODE4 ,
  COALESCE(BRANCH, 0 ) AS BRANCH ,
  COALESCE(BRANCH_DAY, 0 ) AS BRANCH_DAY ,
  COALESCE(CA_PCNT, 0 ) AS CA_PCNT ,
  COALESCE(CARD_FEES, 0 ) AS CARD_FEES ,
  COALESCE(CARDS_CANC, 0 ) AS CARDS_CANC ,
  COALESCE(CARDS_ISSD, 0 ) AS CARDS_ISSD ,
  COALESCE(CASH_1ST, 0 ) AS CASH_1ST ,
  COALESCE(CASH_ADFEE, 0 ) AS CASH_ADFEE ,
  COALESCE(CASH_ADVCE, 0 ) AS CASH_ADVCE ,
  COALESCE(CASH_TDAY, 0 ) AS CASH_TDAY ,
  COALESCE(CASH1STAC, 0 ) AS CASH1STAC ,
  COALESCE(CLASS_CHDY, 0 ) AS CLASS_CHDY ,
  COALESCE(CLASS_CODE, '' ) AS CLASS_CODE ,
  COALESCE(CLOSE_CHDY, 0 ) AS CLOSE_CHDY ,
  COALESCE(CLOSE_CODE, '' ) AS CLOSE_CODE ,
  COALESCE(COLLS_DAY, 0 ) AS COLLS_DAY ,
  COALESCE(CRDACT_DAY, 0 ) AS CRDACT_DAY ,
  COALESCE(CRDNXT_DAY, 0 ) AS CRDNXT_DAY ,
  COALESCE(CRED_ACTIV, '' ) AS CRED_ACTIV ,
  COALESCE(CRED_ADJ, 0 ) AS CRED_ADJ ,
  COALESCE(CRED_CHDAY, 0 ) AS CRED_CHDAY ,
  COALESCE(CRED_LIMIT, 0 ) AS CRED_LIMIT ,
  COALESCE(CRED_VOUCH, 0 ) AS CRED_VOUCH ,
  COALESCE(CREDLIM_X, 0 ) AS CREDLIM_X ,
  COALESCE(CURR_NUM, 0 ) AS CURR_NUM ,
  COALESCE(CUTOFF_DAY, 0 ) AS CUTOFF_DAY ,
  COALESCE(CY_CHGCNT, 0 ) AS CY_CHGCNT ,
  COALESCE(CY_CHGDAY, 0 ) AS CY_CHGDAY ,
  COALESCE(CY_EFFDAY, 0 ) AS CY_EFFDAY ,
  COALESCE(CY_YRCNT, 0 ) AS CY_YRCNT ,
  COALESCE(CYCLE_NEW, 0 ) AS CYCLE_NEW ,
  COALESCE(CYCLE_PRV, 0 ) AS CYCLE_PRV ,
  COALESCE(DEBIT_ADJ, 0 ) AS DEBIT_ADJ ,
  COALESCE(DISHNRDAY, 0 ) AS DISHNRDAY ,
  COALESCE(DUTY_CREDT, 0 ) AS DUTY_CREDT ,
  COALESCE(DUTY_DEBIT, 0 ) AS DUTY_DEBIT ,
  COALESCE(EXCH_CODE, '' ) AS EXCH_CODE ,
  COALESCE(EXCH_FLAG, '' ) AS EXCH_FLAG ,
  COALESCE(EXCH_PERC, 0 ) AS EXCH_PERC ,
  COALESCE(EXCH_RTDT, 0 ) AS EXCH_RTDT ,
  COALESCE(FEE_MONTH, 0 ) AS FEE_MONTH ,
  COALESCE(FEES_TAXES, 0 ) AS FEES_TAXES ,
  COALESCE(FIX_EXAMT, 0 ) AS FIX_EXAMT ,
  COALESCE(GUARN_FLAG, 0 ) AS GUARN_FLAG ,
  COALESCE(HI_CASHADV, 0 ) AS HI_CASHADV ,
  COALESCE(HI_CASMMYY, 0 ) AS HI_CASMMYY ,
  COALESCE(HI_CRDMMYY, 0 ) AS HI_CRDMMYY ,
  COALESCE(HI_CREDIT, 0 ) AS HI_CREDIT ,
  COALESCE(HI_DEBIT, 0 ) AS HI_DEBIT ,
  COALESCE(HI_DEBMMYY, 0 ) AS HI_DEBMMYY ,
  COALESCE(HI_MP_PUR, 0 ) AS HI_MP_PUR ,
  COALESCE(HI_MPMMYY, 0 ) AS HI_MPMMYY ,
  COALESCE(HI_OLIMIT, 0 ) AS HI_OLIMIT ,
  COALESCE(HI_OLIMMYY, 0 ) AS HI_OLIMMYY ,
  COALESCE(HI_PURCHSE, 0 ) AS HI_PURCHSE ,
  COALESCE(HI_PURMMYY, 0 ) AS HI_PURMMYY ,
  COALESCE(INT_CASH, 0 ) AS INT_CASH ,
  COALESCE(INT_CHDCMP, 0 ) AS INT_CHDCMP ,
  COALESCE(INT_CHDY, 0 ) AS INT_CHDY ,
  COALESCE(INT_CHGD, 0 ) AS INT_CHGD ,
  COALESCE(INT_CMPOND, 0 ) AS INT_CMPOND ,
  COALESCE(INT_CODE, 0 ) AS INT_CODE ,
  COALESCE(INT_CUNOT, 0 ) AS INT_CUNOT ,
  COALESCE(INT_CURCMP, 0 ) AS INT_CURCMP ,
  COALESCE(INT_EARNED, 0 ) AS INT_EARNED ,
  COALESCE(INT_NOTION, 0 ) AS INT_NOTION ,
  COALESCE(INT_PROCDY, 0 ) AS INT_PROCDY ,
  COALESCE(INT_RATE, 0 ) AS INT_RATE ,
  COALESCE(INT_RATECR, 0 ) AS INT_RATECR ,
  COALESCE(INT_UPTODY, 0 ) AS INT_UPTODY ,
  COALESCE(LANG_CODE, 0 ) AS LANG_CODE ,
  COALESCE(LAST_TRDAY, 0 ) AS LAST_TRDAY ,
  COALESCE(LASTAUTHDY, 0 ) AS LASTAUTHDY ,
  COALESCE(LASTNTDATE, 0 ) AS LASTNTDATE ,
  COALESCE(LASTPAYAMT, 0 ) AS LASTPAYAMT ,
  COALESCE(LASTPAYDAY, 0 ) AS LASTPAYDAY ,
  COALESCE(LOSSES, 0 ) AS LOSSES ,
  COALESCE(MONTH_NBR, 0 ) AS MONTH_NBR ,
  COALESCE(MONTR_CHDY, 0 ) AS MONTR_CHDY ,
  COALESCE(MONTR_CODE, '' ) AS MONTR_CODE ,
  COALESCE(MP_AM_TDY, 0 ) AS MP_AM_TDY ,
  COALESCE(MP_AUTHS, 0 ) AS MP_AUTHS ,
  COALESCE(MP_BAL, 0 ) AS MP_BAL ,
  COALESCE(MP_BIL_AMT, 0 ) AS MP_BIL_AMT ,
  COALESCE(MP_LIMIT, 0 ) AS MP_LIMIT ,
  COALESCE(MP_NO_TDY, 0 ) AS MP_NO_TDY ,
  COALESCE(MP_REM_PPL, 0 ) AS MP_REM_PPL ,
  COALESCE(MPLM_CHDAY, 0 ) AS MPLM_CHDAY ,
  COALESCE(MTHS_ODUE, 0 ) AS MTHS_ODUE ,
  COALESCE(NBR_CASHAD, 0 ) AS NBR_CASHAD ,
  COALESCE(NBR_FEEDTY, 0 ) AS NBR_FEEDTY ,
  COALESCE(NBR_OLIMIT, 0 ) AS NBR_OLIMIT ,
  COALESCE(NBR_OTHERS, 0 ) AS NBR_OTHERS ,
  COALESCE(NBR_PAYMNT, 0 ) AS NBR_PAYMNT ,
  COALESCE(NBR_PURCH, 0 ) AS NBR_PURCH ,
  COALESCE(NBR_TRANS, 0 ) AS NBR_TRANS ,
  COALESCE(OCT_COUNT, 0 ) AS OCT_COUNT ,
  COALESCE(OCT_DAYIN, 0 ) AS OCT_DAYIN ,
  COALESCE(ODUE_FLAG, 0 ) AS ODUE_FLAG ,
  COALESCE(ODUE_HELD, 0 ) AS ODUE_HELD ,
  COALESCE(OLFLAG, 0 ) AS OLFLAG ,
  COALESCE(OTHER_FEES, 0 ) AS OTHER_FEES ,
  COALESCE(PAY_FLAG, '' ) AS PAY_FLAG ,
  COALESCE(PAY1ST_IND, '' ) AS PAY1ST_IND ,
  COALESCE(PAYMT_CLRD, 0 ) AS PAYMT_CLRD ,
  COALESCE(PAYMT_TDAY, 0 ) AS PAYMT_TDAY ,
  COALESCE(PAYMT_UNCL, 0 ) AS PAYMT_UNCL ,
  COALESCE(PEN_CHRG, 0 ) AS PEN_CHRG ,
  COALESCE(PENCHG_ACC, 0 ) AS PENCHG_ACC ,
  COALESCE(POINT_ADJ, 0 ) AS POINT_ADJ ,
  COALESCE(PT_ADJFLAG, '' ) AS PT_ADJFLAG ,
  COALESCE(POINT_CLM, 0 ) AS POINT_CLM ,
  COALESCE(POINT_CUM, 0 ) AS POINT_CUM ,
  COALESCE(PT_CUMFLAG, '' ) AS PT_CUMFLAG ,
  COALESCE(POINT_CUM2, 0 ) AS POINT_CUM2 ,
  COALESCE(POINT_EAR, 0 ) AS POINT_EAR ,
  COALESCE(POINT_FREZ, '' ) AS POINT_FREZ ,
  COALESCE(POINT_FZDA, 0 ) AS POINT_FZDA ,
  COALESCE(POST_DD, 0 ) AS POST_DD ,
  COALESCE(PREV_BRDAY, 0 ) AS PREV_BRDAY ,
  COALESCE(PREV_BRNCH, 0 ) AS PREV_BRNCH ,
  COALESCE(PURCHASES, 0 ) AS PURCHASES ,
  COALESCE(QUERY_AMT, 0 ) AS QUERY_AMT ,
  COALESCE(QUERY_CODE, '' ) AS QUERY_CODE ,
  COALESCE(QUERY_STMT, 0 ) AS QUERY_STMT ,
  COALESCE(RECLA_CHDY, 0 ) AS RECLA_CHDY ,
  COALESCE(RECLA_CODE, '' ) AS RECLA_CODE ,
  COALESCE(RECVRY_AMT, 0 ) AS RECVRY_AMT ,
  COALESCE(REPAY_AMT, 0 ) AS REPAY_AMT ,
  COALESCE(REPAY_AMTX, 0 ) AS REPAY_AMTX ,
  COALESCE(REPAY_CODE, '' ) AS REPAY_CODE ,
  COALESCE(REPAY_CODX, '' ) AS REPAY_CODX ,
  COALESCE(REPAY_DAY, 0 ) AS REPAY_DAY ,
  COALESCE(REPAY_PCT, 0 ) AS REPAY_PCT ,
  COALESCE(REPAY_PCTX, 0 ) AS REPAY_PCTX ,
  COALESCE(REPY_CHGDY, 0 ) AS REPY_CHGDY ,
  COALESCE(SCORE_PTS, 0 ) AS SCORE_PTS ,
  COALESCE(STATEMENTS, 0 ) AS STATEMENTS ,
  COALESCE(STM_AMT_OL, 0 ) AS STM_AMT_OL ,
  COALESCE(STM_BALFRE, 0 ) AS STM_BALFRE ,
  COALESCE(STM_BALINT, 0 ) AS STM_BALINT ,
  COALESCE(STMBALINTFLAG, '' ) AS STMBALINTFLAG ,
  COALESCE(STM_BALNCE, 0 ) AS STM_BALNCE ,
  COALESCE(STM_BALFLAG, '' ) AS STM_BALFLAG ,
  COALESCE(STM_BALORI, 0 ) AS STM_BALORI ,
  COALESCE(STM_CLOSDY, 0 ) AS STM_CLOSDY ,
  COALESCE(STM_CODE, '' ) AS STM_CODE ,
  COALESCE(STM_INSTL, 0 ) AS STM_INSTL ,
  COALESCE(STM_MINDUE, 0 ) AS STM_MINDUE ,
  COALESCE(STM_NOINT, 0 ) AS STM_NOINT ,
  COALESCE(STM_OLFLAG, 0 ) AS STM_OLFLAG ,
  COALESCE(STM_OVERDU, 0 ) AS STM_OVERDU ,
  COALESCE(STM_PAY_UN, 0 ) AS STM_PAY_UN ,
  COALESCE(STM_QRYAMT, 0 ) AS STM_QRYAMT ,
  COALESCE(STM_REPAY, 0 ) AS STM_REPAY ,
  COALESCE(STMT_DD, 0 ) AS STMT_DD ,
  COALESCE(STMT_PULL, '' ) AS STMT_PULL ,
  COALESCE(TODAY_AMT, 0 ) AS TODAY_AMT ,
  COALESCE(TODAY_AMTFLAG, '' ) AS TODAY_AMTFLAG ,
  COALESCE(TODAY_REL, 0 ) AS TODAY_REL ,
  COALESCE(UNCL_PCT, 0 ) AS UNCL_PCT ,
  COALESCE(WROFF_CHDY, 0 ) AS WROFF_CHDY ,
  COALESCE(WROFF_CODE, '' ) AS WROFF_CODE ,
  COALESCE(PROD_LEVEL, 0 ) AS PROD_LEVEL ,
  COALESCE(PROD_NBR, 0 ) AS PROD_NBR ,
  COALESCE(ACCT_PRSTS, '' ) AS ACCT_PRSTS ,
  COALESCE(ACCT_STS, '' ) AS ACCT_STS ,
  COALESCE(APP_APQUE, '' ) AS APP_APQUE ,
  COALESCE(POINT_ENC, 0 ) AS POINT_ENC ,
  COALESCE(POINT_IMP, 0 ) AS POINT_IMP ,
  COALESCE(POINT_EXP, 0 ) AS POINT_EXP ,
  COALESCE(PT_EXPFLAG, '' ) AS PT_EXPFLAG ,
  COALESCE(RISK_COUNT, 0 ) AS RISK_COUNT ,
  COALESCE(RISK_DAYIN, 0 ) AS RISK_DAYIN ,
  COALESCE(BAL_MP, 0 ) AS BAL_MP ,
  COALESCE(BAL_MPFLAG, '' ) AS BAL_MPFLAG ,
  COALESCE(STM_BALMP, 0 ) AS STM_BALMP ,
  COALESCE(STM_BMFLAG, '' ) AS STM_BMFLAG ,
  COALESCE(LMT_RSN, '' ) AS LMT_RSN ,
  COALESCE(POINT_CARD, 0 ) AS POINT_CARD ,
  COALESCE(PT_CDFLAG, '' ) AS PT_CDFLAG ,
  COALESCE(TEMP_LIMIT, 0 ) AS TEMP_LIMIT ,
  COALESCE(TLMT_BEG, 0 ) AS TLMT_BEG ,
  COALESCE(TLMT_END, 0 ) AS TLMT_END ,
  COALESCE(TLMT_NO, 0 ) AS TLMT_NO ,
  COALESCE(CANCL_RESN, '' ) AS CANCL_RESN ,
  COALESCE(SHADOW_PEN, 0 ) AS SHADOW_PEN ,
  COALESCE(SHADOW_INT, 0 ) AS SHADOW_INT ,
  COALESCE(SHADOW_CMP, 0 ) AS SHADOW_CMP ,
  COALESCE(BAL_NINT01, 0 ) AS BAL_NINT01 ,
  COALESCE(BAL_NINT02, 0 ) AS BAL_NINT02 ,
  COALESCE(BAL_NINT03, 0 ) AS BAL_NINT03 ,
  COALESCE(BAL_NINT04, 0 ) AS BAL_NINT04 ,
  COALESCE(BAL_NINT05, 0 ) AS BAL_NINT05 ,
  COALESCE(BAL_NINT06, 0 ) AS BAL_NINT06 ,
  COALESCE(BAL_NINT07, 0 ) AS BAL_NINT07 ,
  COALESCE(BAL_NINT08, 0 ) AS BAL_NINT08 ,
  COALESCE(BAL_NINT09, 0 ) AS BAL_NINT09 ,
  COALESCE(BAL_NINT10, 0 ) AS BAL_NINT10 ,
  COALESCE(STM_NINT01, 0 ) AS STM_NINT01 ,
  COALESCE(STM_NINT02, 0 ) AS STM_NINT02 ,
  COALESCE(STM_NINT03, 0 ) AS STM_NINT03 ,
  COALESCE(STM_NINT04, 0 ) AS STM_NINT04 ,
  COALESCE(STM_NINT05, 0 ) AS STM_NINT05 ,
  COALESCE(STM_NINT06, 0 ) AS STM_NINT06 ,
  COALESCE(STM_NINT07, 0 ) AS STM_NINT07 ,
  COALESCE(STM_NINT08, 0 ) AS STM_NINT08 ,
  COALESCE(STM_NINT09, 0 ) AS STM_NINT09 ,
  COALESCE(STM_NINT10, 0 ) AS STM_NINT10 ,
  COALESCE(CURR_NUM2, 0 ) AS CURR_NUM2 ,
  COALESCE(WROF_FLAG, 0 ) AS WROF_FLAG ,
  COALESCE(LAYERCODER1, '' ) AS LAYERCODER1 ,
  COALESCE(LAYERCODER2, '' ) AS LAYERCODER2 ,
  COALESCE(MCNTRL_YN, '' ) AS MCNTRL_YN ,
  COALESCE(NCRED_RSN, '' ) AS NCRED_RSN ,
  COALESCE(BSC_CRED, 0 ) AS BSC_CRED ,
  COALESCE(CUSTR_REF, '' ) AS CUSTR_REF ,
  COALESCE(PBC_BRNCH, '' ) AS PBC_BRNCH ,
  COALESCE(STOPMP_YN, 0 ) AS STOPMP_YN ,
  COALESCE(CRED_LMT2, 0 ) AS CRED_LMT2 ,
  COALESCE(BAL_CMPFEE, 0 ) AS BAL_CMPFEE ,
  COALESCE(BAL_LMP, 0 ) AS BAL_LMP ,
  COALESCE(STM_LMP, 0 ) AS STM_LMP ,
  COALESCE(OUT_MONTH, 0 ) AS OUT_MONTH ,
  COALESCE(ETL_DAY, 0 ) AS ETL_DAY,
  COALESCE(STPAY,0) AS STPAY 
 FROM  dw_tdata.CCB_000_ACCT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  XACCOUNT ,
  BANK ,
  BUSINESS ,
  CATEGORY ,
  CUSTR_NBR ,
  CYCLE_NBR ,
  DAY_OPENED ,
  ACC_NAME1 ,
  ACC_TYPE ,
  ADD_CHGDAY ,
  ADDR_TYPE ,
  ADDR_TYPE2 ,
  AGE1 ,
  AGE2 ,
  AGE3 ,
  AGE4 ,
  AGE5 ,
  AGE6 ,
  APP_SOURCE ,
  AUTH_CASH ,
  AUTH_OVER ,
  AUTHOV_YN ,
  AUTHS_AMT ,
  BAL_CMPINT ,
  BAL_FREE ,
  BAL_INT ,
  BAL_INTFLAG ,
  BAL_NOINT ,
  BAL_ORINT ,
  BANKACCT1 ,
  BANKCODE1 ,
  BANKACCT2 ,
  BANKCODE2 ,
  BANKACCT3 ,
  BANKCODE3 ,
  BANKACCT4 ,
  BANKCODE4 ,
  BRANCH ,
  BRANCH_DAY ,
  CA_PCNT ,
  CARD_FEES ,
  CARDS_CANC ,
  CARDS_ISSD ,
  CASH_1ST ,
  CASH_ADFEE ,
  CASH_ADVCE ,
  CASH_TDAY ,
  CASH1STAC ,
  CLASS_CHDY ,
  CLASS_CODE ,
  CLOSE_CHDY ,
  CLOSE_CODE ,
  COLLS_DAY ,
  CRDACT_DAY ,
  CRDNXT_DAY ,
  CRED_ACTIV ,
  CRED_ADJ ,
  CRED_CHDAY ,
  CRED_LIMIT ,
  CRED_VOUCH ,
  CREDLIM_X ,
  CURR_NUM ,
  CUTOFF_DAY ,
  CY_CHGCNT ,
  CY_CHGDAY ,
  CY_EFFDAY ,
  CY_YRCNT ,
  CYCLE_NEW ,
  CYCLE_PRV ,
  DEBIT_ADJ ,
  DISHNRDAY ,
  DUTY_CREDT ,
  DUTY_DEBIT ,
  EXCH_CODE ,
  EXCH_FLAG ,
  EXCH_PERC ,
  EXCH_RTDT ,
  FEE_MONTH ,
  FEES_TAXES ,
  FIX_EXAMT ,
  GUARN_FLAG ,
  HI_CASHADV ,
  HI_CASMMYY ,
  HI_CRDMMYY ,
  HI_CREDIT ,
  HI_DEBIT ,
  HI_DEBMMYY ,
  HI_MP_PUR ,
  HI_MPMMYY ,
  HI_OLIMIT ,
  HI_OLIMMYY ,
  HI_PURCHSE ,
  HI_PURMMYY ,
  INT_CASH ,
  INT_CHDCMP ,
  INT_CHDY ,
  INT_CHGD ,
  INT_CMPOND ,
  INT_CODE ,
  INT_CUNOT ,
  INT_CURCMP ,
  INT_EARNED ,
  INT_NOTION ,
  INT_PROCDY ,
  INT_RATE ,
  INT_RATECR ,
  INT_UPTODY ,
  LANG_CODE ,
  LAST_TRDAY ,
  LASTAUTHDY ,
  LASTNTDATE ,
  LASTPAYAMT ,
  LASTPAYDAY ,
  LOSSES ,
  MONTH_NBR ,
  MONTR_CHDY ,
  MONTR_CODE ,
  MP_AM_TDY ,
  MP_AUTHS ,
  MP_BAL ,
  MP_BIL_AMT ,
  MP_LIMIT ,
  MP_NO_TDY ,
  MP_REM_PPL ,
  MPLM_CHDAY ,
  MTHS_ODUE ,
  NBR_CASHAD ,
  NBR_FEEDTY ,
  NBR_OLIMIT ,
  NBR_OTHERS ,
  NBR_PAYMNT ,
  NBR_PURCH ,
  NBR_TRANS ,
  OCT_COUNT ,
  OCT_DAYIN ,
  ODUE_FLAG ,
  ODUE_HELD ,
  OLFLAG ,
  OTHER_FEES ,
  PAY_FLAG ,
  PAY1ST_IND ,
  PAYMT_CLRD ,
  PAYMT_TDAY ,
  PAYMT_UNCL ,
  PEN_CHRG ,
  PENCHG_ACC ,
  POINT_ADJ ,
  PT_ADJFLAG ,
  POINT_CLM ,
  POINT_CUM ,
  PT_CUMFLAG ,
  POINT_CUM2 ,
  POINT_EAR ,
  POINT_FREZ ,
  POINT_FZDA ,
  POST_DD ,
  PREV_BRDAY ,
  PREV_BRNCH ,
  PURCHASES ,
  QUERY_AMT ,
  QUERY_CODE ,
  QUERY_STMT ,
  RECLA_CHDY ,
  RECLA_CODE ,
  RECVRY_AMT ,
  REPAY_AMT ,
  REPAY_AMTX ,
  REPAY_CODE ,
  REPAY_CODX ,
  REPAY_DAY ,
  REPAY_PCT ,
  REPAY_PCTX ,
  REPY_CHGDY ,
  SCORE_PTS ,
  STATEMENTS ,
  STM_AMT_OL ,
  STM_BALFRE ,
  STM_BALINT ,
  STMBALINTFLAG ,
  STM_BALNCE ,
  STM_BALFLAG ,
  STM_BALORI ,
  STM_CLOSDY ,
  STM_CODE ,
  STM_INSTL ,
  STM_MINDUE ,
  STM_NOINT ,
  STM_OLFLAG ,
  STM_OVERDU ,
  STM_PAY_UN ,
  STM_QRYAMT ,
  STM_REPAY ,
  STMT_DD ,
  STMT_PULL ,
  TODAY_AMT ,
  TODAY_AMTFLAG ,
  TODAY_REL ,
  UNCL_PCT ,
  WROFF_CHDY ,
  WROFF_CODE ,
  PROD_LEVEL ,
  PROD_NBR ,
  ACCT_PRSTS ,
  ACCT_STS ,
  APP_APQUE ,
  POINT_ENC ,
  POINT_IMP ,
  POINT_EXP ,
  PT_EXPFLAG ,
  RISK_COUNT ,
  RISK_DAYIN ,
  BAL_MP ,
  BAL_MPFLAG ,
  STM_BALMP ,
  STM_BMFLAG ,
  LMT_RSN ,
  POINT_CARD ,
  PT_CDFLAG ,
  TEMP_LIMIT ,
  TLMT_BEG ,
  TLMT_END ,
  TLMT_NO ,
  CANCL_RESN ,
  SHADOW_PEN ,
  SHADOW_INT ,
  SHADOW_CMP ,
  BAL_NINT01 ,
  BAL_NINT02 ,
  BAL_NINT03 ,
  BAL_NINT04 ,
  BAL_NINT05 ,
  BAL_NINT06 ,
  BAL_NINT07 ,
  BAL_NINT08 ,
  BAL_NINT09 ,
  BAL_NINT10 ,
  STM_NINT01 ,
  STM_NINT02 ,
  STM_NINT03 ,
  STM_NINT04 ,
  STM_NINT05 ,
  STM_NINT06 ,
  STM_NINT07 ,
  STM_NINT08 ,
  STM_NINT09 ,
  STM_NINT10 ,
  CURR_NUM2 ,
  WROF_FLAG ,
  LAYERCODER1 ,
  LAYERCODER2 ,
  MCNTRL_YN ,
  NCRED_RSN ,
  BSC_CRED ,
  CUSTR_REF ,
  PBC_BRNCH ,
  STOPMP_YN ,
  CRED_LMT2 ,
  BAL_CMPFEE ,
  BAL_LMP ,
  STM_LMP ,
  OUT_MONTH ,
  ETL_DAY,
  STPAY 
 FROM dw_sdata.CCB_000_ACCT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.XACCOUNT = T.XACCOUNT AND N.BANK = T.BANK
WHERE
(T.XACCOUNT IS NULL AND T.BANK IS NULL)
 OR N.BUSINESS<>T.BUSINESS
 OR N.CATEGORY<>T.CATEGORY
 OR N.CUSTR_NBR<>T.CUSTR_NBR
 OR N.CYCLE_NBR<>T.CYCLE_NBR
 OR N.DAY_OPENED<>T.DAY_OPENED
 OR N.ACC_NAME1<>T.ACC_NAME1
 OR N.ACC_TYPE<>T.ACC_TYPE
 OR N.ADD_CHGDAY<>T.ADD_CHGDAY
 OR N.ADDR_TYPE<>T.ADDR_TYPE
 OR N.ADDR_TYPE2<>T.ADDR_TYPE2
 OR N.AGE1<>T.AGE1
 OR N.AGE2<>T.AGE2
 OR N.AGE3<>T.AGE3
 OR N.AGE4<>T.AGE4
 OR N.AGE5<>T.AGE5
 OR N.AGE6<>T.AGE6
 OR N.APP_SOURCE<>T.APP_SOURCE
 OR N.AUTH_CASH<>T.AUTH_CASH
 OR N.AUTH_OVER<>T.AUTH_OVER
 OR N.AUTHOV_YN<>T.AUTHOV_YN
 OR N.AUTHS_AMT<>T.AUTHS_AMT
 OR N.BAL_CMPINT<>T.BAL_CMPINT
 OR N.BAL_FREE<>T.BAL_FREE
 OR N.BAL_INT<>T.BAL_INT
 OR N.BAL_INTFLAG<>T.BAL_INTFLAG
 OR N.BAL_NOINT<>T.BAL_NOINT
 OR N.BAL_ORINT<>T.BAL_ORINT
 OR N.BANKACCT1<>T.BANKACCT1
 OR N.BANKCODE1<>T.BANKCODE1
 OR N.BANKACCT2<>T.BANKACCT2
 OR N.BANKCODE2<>T.BANKCODE2
 OR N.BANKACCT3<>T.BANKACCT3
 OR N.BANKCODE3<>T.BANKCODE3
 OR N.BANKACCT4<>T.BANKACCT4
 OR N.BANKCODE4<>T.BANKCODE4
 OR N.BRANCH<>T.BRANCH
 OR N.BRANCH_DAY<>T.BRANCH_DAY
 OR N.CA_PCNT<>T.CA_PCNT
 OR N.CARD_FEES<>T.CARD_FEES
 OR N.CARDS_CANC<>T.CARDS_CANC
 OR N.CARDS_ISSD<>T.CARDS_ISSD
 OR N.CASH_1ST<>T.CASH_1ST
 OR N.CASH_ADFEE<>T.CASH_ADFEE
 OR N.CASH_ADVCE<>T.CASH_ADVCE
 OR N.CASH_TDAY<>T.CASH_TDAY
 OR N.CASH1STAC<>T.CASH1STAC
 OR N.CLASS_CHDY<>T.CLASS_CHDY
 OR N.CLASS_CODE<>T.CLASS_CODE
 OR N.CLOSE_CHDY<>T.CLOSE_CHDY
 OR N.CLOSE_CODE<>T.CLOSE_CODE
 OR N.COLLS_DAY<>T.COLLS_DAY
 OR N.CRDACT_DAY<>T.CRDACT_DAY
 OR N.CRDNXT_DAY<>T.CRDNXT_DAY
 OR N.CRED_ACTIV<>T.CRED_ACTIV
 OR N.CRED_ADJ<>T.CRED_ADJ
 OR N.CRED_CHDAY<>T.CRED_CHDAY
 OR N.CRED_LIMIT<>T.CRED_LIMIT
 OR N.CRED_VOUCH<>T.CRED_VOUCH
 OR N.CREDLIM_X<>T.CREDLIM_X
 OR N.CURR_NUM<>T.CURR_NUM
 OR N.CUTOFF_DAY<>T.CUTOFF_DAY
 OR N.CY_CHGCNT<>T.CY_CHGCNT
 OR N.CY_CHGDAY<>T.CY_CHGDAY
 OR N.CY_EFFDAY<>T.CY_EFFDAY
 OR N.CY_YRCNT<>T.CY_YRCNT
 OR N.CYCLE_NEW<>T.CYCLE_NEW
 OR N.CYCLE_PRV<>T.CYCLE_PRV
 OR N.DEBIT_ADJ<>T.DEBIT_ADJ
 OR N.DISHNRDAY<>T.DISHNRDAY
 OR N.DUTY_CREDT<>T.DUTY_CREDT
 OR N.DUTY_DEBIT<>T.DUTY_DEBIT
 OR N.EXCH_CODE<>T.EXCH_CODE
 OR N.EXCH_FLAG<>T.EXCH_FLAG
 OR N.EXCH_PERC<>T.EXCH_PERC
 OR N.EXCH_RTDT<>T.EXCH_RTDT
 OR N.FEE_MONTH<>T.FEE_MONTH
 OR N.FEES_TAXES<>T.FEES_TAXES
 OR N.FIX_EXAMT<>T.FIX_EXAMT
 OR N.GUARN_FLAG<>T.GUARN_FLAG
 OR N.HI_CASHADV<>T.HI_CASHADV
 OR N.HI_CASMMYY<>T.HI_CASMMYY
 OR N.HI_CRDMMYY<>T.HI_CRDMMYY
 OR N.HI_CREDIT<>T.HI_CREDIT
 OR N.HI_DEBIT<>T.HI_DEBIT
 OR N.HI_DEBMMYY<>T.HI_DEBMMYY
 OR N.HI_MP_PUR<>T.HI_MP_PUR
 OR N.HI_MPMMYY<>T.HI_MPMMYY
 OR N.HI_OLIMIT<>T.HI_OLIMIT
 OR N.HI_OLIMMYY<>T.HI_OLIMMYY
 OR N.HI_PURCHSE<>T.HI_PURCHSE
 OR N.HI_PURMMYY<>T.HI_PURMMYY
 OR N.INT_CASH<>T.INT_CASH
 OR N.INT_CHDCMP<>T.INT_CHDCMP
 OR N.INT_CHDY<>T.INT_CHDY
 OR N.INT_CHGD<>T.INT_CHGD
 OR N.INT_CMPOND<>T.INT_CMPOND
 OR N.INT_CODE<>T.INT_CODE
 OR N.INT_CUNOT<>T.INT_CUNOT
 OR N.INT_CURCMP<>T.INT_CURCMP
 OR N.INT_EARNED<>T.INT_EARNED
 OR N.INT_NOTION<>T.INT_NOTION
 OR N.INT_PROCDY<>T.INT_PROCDY
 OR N.INT_RATE<>T.INT_RATE
 OR N.INT_RATECR<>T.INT_RATECR
 OR N.INT_UPTODY<>T.INT_UPTODY
 OR N.LANG_CODE<>T.LANG_CODE
 OR N.LAST_TRDAY<>T.LAST_TRDAY
 OR N.LASTAUTHDY<>T.LASTAUTHDY
 OR N.LASTNTDATE<>T.LASTNTDATE
 OR N.LASTPAYAMT<>T.LASTPAYAMT
 OR N.LASTPAYDAY<>T.LASTPAYDAY
 OR N.LOSSES<>T.LOSSES
 OR N.MONTH_NBR<>T.MONTH_NBR
 OR N.MONTR_CHDY<>T.MONTR_CHDY
 OR N.MONTR_CODE<>T.MONTR_CODE
 OR N.MP_AM_TDY<>T.MP_AM_TDY
 OR N.MP_AUTHS<>T.MP_AUTHS
 OR N.MP_BAL<>T.MP_BAL
 OR N.MP_BIL_AMT<>T.MP_BIL_AMT
 OR N.MP_LIMIT<>T.MP_LIMIT
 OR N.MP_NO_TDY<>T.MP_NO_TDY
 OR N.MP_REM_PPL<>T.MP_REM_PPL
 OR N.MPLM_CHDAY<>T.MPLM_CHDAY
 OR N.MTHS_ODUE<>T.MTHS_ODUE
 OR N.NBR_CASHAD<>T.NBR_CASHAD
 OR N.NBR_FEEDTY<>T.NBR_FEEDTY
 OR N.NBR_OLIMIT<>T.NBR_OLIMIT
 OR N.NBR_OTHERS<>T.NBR_OTHERS
 OR N.NBR_PAYMNT<>T.NBR_PAYMNT
 OR N.NBR_PURCH<>T.NBR_PURCH
 OR N.NBR_TRANS<>T.NBR_TRANS
 OR N.OCT_COUNT<>T.OCT_COUNT
 OR N.OCT_DAYIN<>T.OCT_DAYIN
 OR N.ODUE_FLAG<>T.ODUE_FLAG
 OR N.ODUE_HELD<>T.ODUE_HELD
 OR N.OLFLAG<>T.OLFLAG
 OR N.OTHER_FEES<>T.OTHER_FEES
 OR N.PAY_FLAG<>T.PAY_FLAG
 OR N.PAY1ST_IND<>T.PAY1ST_IND
 OR N.PAYMT_CLRD<>T.PAYMT_CLRD
 OR N.PAYMT_TDAY<>T.PAYMT_TDAY
 OR N.PAYMT_UNCL<>T.PAYMT_UNCL
 OR N.PEN_CHRG<>T.PEN_CHRG
 OR N.PENCHG_ACC<>T.PENCHG_ACC
 OR N.POINT_ADJ<>T.POINT_ADJ
 OR N.PT_ADJFLAG<>T.PT_ADJFLAG
 OR N.POINT_CLM<>T.POINT_CLM
 OR N.POINT_CUM<>T.POINT_CUM
 OR N.PT_CUMFLAG<>T.PT_CUMFLAG
 OR N.POINT_CUM2<>T.POINT_CUM2
 OR N.POINT_EAR<>T.POINT_EAR
 OR N.POINT_FREZ<>T.POINT_FREZ
 OR N.POINT_FZDA<>T.POINT_FZDA
 OR N.POST_DD<>T.POST_DD
 OR N.PREV_BRDAY<>T.PREV_BRDAY
 OR N.PREV_BRNCH<>T.PREV_BRNCH
 OR N.PURCHASES<>T.PURCHASES
 OR N.QUERY_AMT<>T.QUERY_AMT
 OR N.QUERY_CODE<>T.QUERY_CODE
 OR N.QUERY_STMT<>T.QUERY_STMT
 OR N.RECLA_CHDY<>T.RECLA_CHDY
 OR N.RECLA_CODE<>T.RECLA_CODE
 OR N.RECVRY_AMT<>T.RECVRY_AMT
 OR N.REPAY_AMT<>T.REPAY_AMT
 OR N.REPAY_AMTX<>T.REPAY_AMTX
 OR N.REPAY_CODE<>T.REPAY_CODE
 OR N.REPAY_CODX<>T.REPAY_CODX
 OR N.REPAY_DAY<>T.REPAY_DAY
 OR N.REPAY_PCT<>T.REPAY_PCT
 OR N.REPAY_PCTX<>T.REPAY_PCTX
 OR N.REPY_CHGDY<>T.REPY_CHGDY
 OR N.SCORE_PTS<>T.SCORE_PTS
 OR N.STATEMENTS<>T.STATEMENTS
 OR N.STM_AMT_OL<>T.STM_AMT_OL
 OR N.STM_BALFRE<>T.STM_BALFRE
 OR N.STM_BALINT<>T.STM_BALINT
 OR N.STMBALINTFLAG<>T.STMBALINTFLAG
 OR N.STM_BALNCE<>T.STM_BALNCE
 OR N.STM_BALFLAG<>T.STM_BALFLAG
 OR N.STM_BALORI<>T.STM_BALORI
 OR N.STM_CLOSDY<>T.STM_CLOSDY
 OR N.STM_CODE<>T.STM_CODE
 OR N.STM_INSTL<>T.STM_INSTL
 OR N.STM_MINDUE<>T.STM_MINDUE
 OR N.STM_NOINT<>T.STM_NOINT
 OR N.STM_OLFLAG<>T.STM_OLFLAG
 OR N.STM_OVERDU<>T.STM_OVERDU
 OR N.STM_PAY_UN<>T.STM_PAY_UN
 OR N.STM_QRYAMT<>T.STM_QRYAMT
 OR N.STM_REPAY<>T.STM_REPAY
 OR N.STMT_DD<>T.STMT_DD
 OR N.STMT_PULL<>T.STMT_PULL
 OR N.TODAY_AMT<>T.TODAY_AMT
 OR N.TODAY_AMTFLAG<>T.TODAY_AMTFLAG
 OR N.TODAY_REL<>T.TODAY_REL
 OR N.UNCL_PCT<>T.UNCL_PCT
 OR N.WROFF_CHDY<>T.WROFF_CHDY
 OR N.WROFF_CODE<>T.WROFF_CODE
 OR N.PROD_LEVEL<>T.PROD_LEVEL
 OR N.PROD_NBR<>T.PROD_NBR
 OR N.ACCT_PRSTS<>T.ACCT_PRSTS
 OR N.ACCT_STS<>T.ACCT_STS
 OR N.APP_APQUE<>T.APP_APQUE
 OR N.POINT_ENC<>T.POINT_ENC
 OR N.POINT_IMP<>T.POINT_IMP
 OR N.POINT_EXP<>T.POINT_EXP
 OR N.PT_EXPFLAG<>T.PT_EXPFLAG
 OR N.RISK_COUNT<>T.RISK_COUNT
 OR N.RISK_DAYIN<>T.RISK_DAYIN
 OR N.BAL_MP<>T.BAL_MP
 OR N.BAL_MPFLAG<>T.BAL_MPFLAG
 OR N.STM_BALMP<>T.STM_BALMP
 OR N.STM_BMFLAG<>T.STM_BMFLAG
 OR N.LMT_RSN<>T.LMT_RSN
 OR N.POINT_CARD<>T.POINT_CARD
 OR N.PT_CDFLAG<>T.PT_CDFLAG
 OR N.TEMP_LIMIT<>T.TEMP_LIMIT
 OR N.TLMT_BEG<>T.TLMT_BEG
 OR N.TLMT_END<>T.TLMT_END
 OR N.TLMT_NO<>T.TLMT_NO
 OR N.CANCL_RESN<>T.CANCL_RESN
 OR N.SHADOW_PEN<>T.SHADOW_PEN
 OR N.SHADOW_INT<>T.SHADOW_INT
 OR N.SHADOW_CMP<>T.SHADOW_CMP
 OR N.BAL_NINT01<>T.BAL_NINT01
 OR N.BAL_NINT02<>T.BAL_NINT02
 OR N.BAL_NINT03<>T.BAL_NINT03
 OR N.BAL_NINT04<>T.BAL_NINT04
 OR N.BAL_NINT05<>T.BAL_NINT05
 OR N.BAL_NINT06<>T.BAL_NINT06
 OR N.BAL_NINT07<>T.BAL_NINT07
 OR N.BAL_NINT08<>T.BAL_NINT08
 OR N.BAL_NINT09<>T.BAL_NINT09
 OR N.BAL_NINT10<>T.BAL_NINT10
 OR N.STM_NINT01<>T.STM_NINT01
 OR N.STM_NINT02<>T.STM_NINT02
 OR N.STM_NINT03<>T.STM_NINT03
 OR N.STM_NINT04<>T.STM_NINT04
 OR N.STM_NINT05<>T.STM_NINT05
 OR N.STM_NINT06<>T.STM_NINT06
 OR N.STM_NINT07<>T.STM_NINT07
 OR N.STM_NINT08<>T.STM_NINT08
 OR N.STM_NINT09<>T.STM_NINT09
 OR N.STM_NINT10<>T.STM_NINT10
 OR N.CURR_NUM2<>T.CURR_NUM2
 OR N.WROF_FLAG<>T.WROF_FLAG
 OR N.LAYERCODER1<>T.LAYERCODER1
 OR N.LAYERCODER2<>T.LAYERCODER2
 OR N.MCNTRL_YN<>T.MCNTRL_YN
 OR N.NCRED_RSN<>T.NCRED_RSN
 OR N.BSC_CRED<>T.BSC_CRED
 OR N.CUSTR_REF<>T.CUSTR_REF
 OR N.PBC_BRNCH<>T.PBC_BRNCH
 OR N.STOPMP_YN<>T.STOPMP_YN
 OR N.CRED_LMT2<>T.CRED_LMT2
 OR N.BAL_CMPFEE<>T.BAL_CMPFEE
 OR N.BAL_LMP<>T.BAL_LMP
 OR N.STM_LMP<>T.STM_LMP
 OR N.OUT_MONTH<>T.OUT_MONTH
 OR N.ETL_DAY<>T.ETL_DAY
 OR N.STPAY<>T.STPAY
;

--Step3:
UPDATE dw_sdata.CCB_000_ACCT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_83
WHERE P.End_Dt=DATE('2100-12-31')
AND P.XACCOUNT=T_83.XACCOUNT
AND P.BANK=T_83.BANK
;

--Step4:
INSERT  INTO dw_sdata.CCB_000_ACCT SELECT * FROM T_83;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
