#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCB_000_STMT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCB_000_STMT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_104 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCB_000_STMT WHERE 1=0;

--Step2:
INSERT  INTO T_104 (
  XACCOUNT,
  BANK,
  CATEGORY,
  CYCLE_NBR,
  MONTH_NBR,
  POST_DD,
  AGE1,
  AGE2,
  AGE3,
  AGE4,
  AGE5,
  AGE6,
  BAL_CMPINT,
  BAL_FREE,
  BAL_INT,
  BALINTFLAG,
  BAL_NOINT,
  BAL_ORINT,
  BRANCH,
  BUSINESS,
  CARD_FEES,
  CASH_ADFEE,
  CASH_ADVCE,
  CLOSE_BAL,
  CLSBAL_FLAG,
  CLOSE_CODE,
  CLOSE_DATE,
  CRED_ADJ,
  CRED_LIMIT,
  CRED_VOUCH,
  CREDLIM_X,
  CY_CHGCNT,
  CY_CHGDAY,
  CY_EFFDAY,
  CYCLE_NEW,
  DAYSPAY,
  DEBIT_ADJ,
  DUNCODE1,
  DUNCODE2,
  DUNCODEB,
  DUNLETR1,
  DUNLETR2,
  DUNLETRB,
  DUTY_CREDT,
  DUTY_DEBIT,
  FEES_TAXES,
  INSTL_AMT,
  INT_CHDCMP,
  INT_CHGD,
  INT_CMPOND,
  INT_CUNOT,
  INT_CURCMP,
  INT_EARNED,
  INT_RATE,
  INT_TAXRTE,
  LETR_CODE1,
  LETR_CODE2,
  LOSSES,
  MIN_DUE,
  MIN_DUE_DT,
  MINDUE_R,
  MSG_KEY,
  NBR_CASHAD,
  NBR_FEEDTY,
  NBR_OTHERS,
  NBR_PAYMNT,
  NBR_PURCH,
  ODUE_FLAG,
  ODUE_HELD,
  OPEN_BAL,
  OPBAL_FLAG,
  OPEN_DATE,
  OTHER_FEES,
  PAYMENT,
  PAYMT_UNCL,
  PEN_CHRG,
  POINT_ADJ,
  PTADJ_FLAG,
  POINT_CLM,
  POINT_CUM,
  PTFLAG,
  POINT_EAR,
  POINT_ENC,
  POINT_IMP,
  POINT_EXP,
  PRIOR_NO,
  PURCHASES,
  QUERY_AMT,
  QUERY_CODE,
  RECVRY_AMT,
  REVCRY_AMT,
  STM_AMT_OL,
  STMT_CODE,
  REPAY_AAMT,
  REPAY_ACCT,
  REPAY_ADAY,
  REPAY_DAMT,
  REPAY_DDAY,
  REPAY_IDNO,
  REPAY_IDTY,
  REPAY_NAME,
  REPAY_RESP,
  BAL_MP,
  POINT_CARD,
  PAY_FLAG,
  BAL_NINT01,
  BAL_NINT02,
  BAL_NINT03,
  BAL_NINT04,
  BAL_NINT05,
  BAL_NINT06,
  BAL_NINT07,
  BAL_NINT08,
  BAL_NINT09,
  BAL_NINT10,
  NBR_CASHAD_NEW,
  NBR_FEEDTY_NEW,
  NBR_OTHERS_NEW,
  NBR_PAYMNT_NEW,
  NBR_PURCH_NEW,
  BAL_CMPFEE,
  MTHS_ODUE,
  PURCHASES_FLAG,
  start_dt,
  end_dt)
SELECT
  N.XACCOUNT,
  N.BANK,
  N.CATEGORY,
  N.CYCLE_NBR,
  N.MONTH_NBR,
  N.POST_DD,
  N.AGE1,
  N.AGE2,
  N.AGE3,
  N.AGE4,
  N.AGE5,
  N.AGE6,
  N.BAL_CMPINT,
  N.BAL_FREE,
  N.BAL_INT,
  N.BALINTFLAG,
  N.BAL_NOINT,
  N.BAL_ORINT,
  N.BRANCH,
  N.BUSINESS,
  N.CARD_FEES,
  N.CASH_ADFEE,
  N.CASH_ADVCE,
  N.CLOSE_BAL,
  N.CLSBAL_FLAG,
  N.CLOSE_CODE,
  N.CLOSE_DATE,
  N.CRED_ADJ,
  N.CRED_LIMIT,
  N.CRED_VOUCH,
  N.CREDLIM_X,
  N.CY_CHGCNT,
  N.CY_CHGDAY,
  N.CY_EFFDAY,
  N.CYCLE_NEW,
  N.DAYSPAY,
  N.DEBIT_ADJ,
  N.DUNCODE1,
  N.DUNCODE2,
  N.DUNCODEB,
  N.DUNLETR1,
  N.DUNLETR2,
  N.DUNLETRB,
  N.DUTY_CREDT,
  N.DUTY_DEBIT,
  N.FEES_TAXES,
  N.INSTL_AMT,
  N.INT_CHDCMP,
  N.INT_CHGD,
  N.INT_CMPOND,
  N.INT_CUNOT,
  N.INT_CURCMP,
  N.INT_EARNED,
  N.INT_RATE,
  N.INT_TAXRTE,
  N.LETR_CODE1,
  N.LETR_CODE2,
  N.LOSSES,
  N.MIN_DUE,
  N.MIN_DUE_DT,
  N.MINDUE_R,
  N.MSG_KEY,
  N.NBR_CASHAD,
  N.NBR_FEEDTY,
  N.NBR_OTHERS,
  N.NBR_PAYMNT,
  N.NBR_PURCH,
  N.ODUE_FLAG,
  N.ODUE_HELD,
  N.OPEN_BAL,
  N.OPBAL_FLAG,
  N.OPEN_DATE,
  N.OTHER_FEES,
  N.PAYMENT,
  N.PAYMT_UNCL,
  N.PEN_CHRG,
  N.POINT_ADJ,
  N.PTADJ_FLAG,
  N.POINT_CLM,
  N.POINT_CUM,
  N.PTFLAG,
  N.POINT_EAR,
  N.POINT_ENC,
  N.POINT_IMP,
  N.POINT_EXP,
  N.PRIOR_NO,
  N.PURCHASES,
  N.QUERY_AMT,
  N.QUERY_CODE,
  N.RECVRY_AMT,
  N.REVCRY_AMT,
  N.STM_AMT_OL,
  N.STMT_CODE,
  N.REPAY_AAMT,
  N.REPAY_ACCT,
  N.REPAY_ADAY,
  N.REPAY_DAMT,
  N.REPAY_DDAY,
  N.REPAY_IDNO,
  N.REPAY_IDTY,
  N.REPAY_NAME,
  N.REPAY_RESP,
  N.BAL_MP,
  N.POINT_CARD,
  N.PAY_FLAG,
  N.BAL_NINT01,
  N.BAL_NINT02,
  N.BAL_NINT03,
  N.BAL_NINT04,
  N.BAL_NINT05,
  N.BAL_NINT06,
  N.BAL_NINT07,
  N.BAL_NINT08,
  N.BAL_NINT09,
  N.BAL_NINT10,
  N.NBR_CASHAD_NEW,
  N.NBR_FEEDTY_NEW,
  N.NBR_OTHERS_NEW,
  N.NBR_PAYMNT_NEW,
  N.NBR_PURCH_NEW,
  N.BAL_CMPFEE,
  N.MTHS_ODUE,
  N.PURCHASES_FLAG,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(XACCOUNT, 0 ) AS XACCOUNT ,
  COALESCE(BANK, 0 ) AS BANK ,
  COALESCE(CATEGORY, 0 ) AS CATEGORY ,
  COALESCE(CYCLE_NBR, 0 ) AS CYCLE_NBR ,
  COALESCE(MONTH_NBR, 0 ) AS MONTH_NBR ,
  COALESCE(POST_DD, 0 ) AS POST_DD ,
  COALESCE(AGE1, 0 ) AS AGE1 ,
  COALESCE(AGE2, 0 ) AS AGE2 ,
  COALESCE(AGE3, 0 ) AS AGE3 ,
  COALESCE(AGE4, 0 ) AS AGE4 ,
  COALESCE(AGE5, 0 ) AS AGE5 ,
  COALESCE(AGE6, 0 ) AS AGE6 ,
  COALESCE(BAL_CMPINT, 0 ) AS BAL_CMPINT ,
  COALESCE(BAL_FREE, 0 ) AS BAL_FREE ,
  COALESCE(BAL_INT, 0 ) AS BAL_INT ,
  COALESCE(BALINTFLAG, '' ) AS BALINTFLAG ,
  COALESCE(BAL_NOINT, 0 ) AS BAL_NOINT ,
  COALESCE(BAL_ORINT, 0 ) AS BAL_ORINT ,
  COALESCE(BRANCH, 0 ) AS BRANCH ,
  COALESCE(BUSINESS, '' ) AS BUSINESS ,
  COALESCE(CARD_FEES, 0 ) AS CARD_FEES ,
  COALESCE(CASH_ADFEE, 0 ) AS CASH_ADFEE ,
  COALESCE(CASH_ADVCE, 0 ) AS CASH_ADVCE ,
  COALESCE(CLOSE_BAL, 0 ) AS CLOSE_BAL ,
  COALESCE(CLSBAL_FLAG, '' ) AS CLSBAL_FLAG ,
  COALESCE(CLOSE_CODE, '' ) AS CLOSE_CODE ,
  COALESCE(CLOSE_DATE, '' ) AS CLOSE_DATE ,
  COALESCE(CRED_ADJ, 0 ) AS CRED_ADJ ,
  COALESCE(CRED_LIMIT, 0 ) AS CRED_LIMIT ,
  COALESCE(CRED_VOUCH, 0 ) AS CRED_VOUCH ,
  COALESCE(CREDLIM_X, 0 ) AS CREDLIM_X ,
  COALESCE(CY_CHGCNT, 0 ) AS CY_CHGCNT ,
  COALESCE(CY_CHGDAY, 0 ) AS CY_CHGDAY ,
  COALESCE(CY_EFFDAY, 0 ) AS CY_EFFDAY ,
  COALESCE(CYCLE_NEW, 0 ) AS CYCLE_NEW ,
  COALESCE(DAYSPAY, 0 ) AS DAYSPAY ,
  COALESCE(DEBIT_ADJ, 0 ) AS DEBIT_ADJ ,
  COALESCE(DUNCODE1, '' ) AS DUNCODE1 ,
  COALESCE(DUNCODE2, '' ) AS DUNCODE2 ,
  COALESCE(DUNCODEB, '' ) AS DUNCODEB ,
  COALESCE(DUNLETR1, '' ) AS DUNLETR1 ,
  COALESCE(DUNLETR2, '' ) AS DUNLETR2 ,
  COALESCE(DUNLETRB, '' ) AS DUNLETRB ,
  COALESCE(DUTY_CREDT, 0 ) AS DUTY_CREDT ,
  COALESCE(DUTY_DEBIT, 0 ) AS DUTY_DEBIT ,
  COALESCE(FEES_TAXES, 0 ) AS FEES_TAXES ,
  COALESCE(INSTL_AMT, 0 ) AS INSTL_AMT ,
  COALESCE(INT_CHDCMP, 0 ) AS INT_CHDCMP ,
  COALESCE(INT_CHGD, 0 ) AS INT_CHGD ,
  COALESCE(INT_CMPOND, 0 ) AS INT_CMPOND ,
  COALESCE(INT_CUNOT, 0 ) AS INT_CUNOT ,
  COALESCE(INT_CURCMP, 0 ) AS INT_CURCMP ,
  COALESCE(INT_EARNED, 0 ) AS INT_EARNED ,
  COALESCE(INT_RATE, 0 ) AS INT_RATE ,
  COALESCE(INT_TAXRTE, 0 ) AS INT_TAXRTE ,
  COALESCE(LETR_CODE1, '' ) AS LETR_CODE1 ,
  COALESCE(LETR_CODE2, '' ) AS LETR_CODE2 ,
  COALESCE(LOSSES, 0 ) AS LOSSES ,
  COALESCE(MIN_DUE, 0 ) AS MIN_DUE ,
  COALESCE(MIN_DUE_DT, '' ) AS MIN_DUE_DT ,
  COALESCE(MINDUE_R, 0 ) AS MINDUE_R ,
  COALESCE(MSG_KEY, '' ) AS MSG_KEY ,
  COALESCE(NBR_CASHAD, 0 ) AS NBR_CASHAD ,
  COALESCE(NBR_FEEDTY, 0 ) AS NBR_FEEDTY ,
  COALESCE(NBR_OTHERS, 0 ) AS NBR_OTHERS ,
  COALESCE(NBR_PAYMNT, 0 ) AS NBR_PAYMNT ,
  COALESCE(NBR_PURCH, 0 ) AS NBR_PURCH ,
  COALESCE(ODUE_FLAG, 0 ) AS ODUE_FLAG ,
  COALESCE(ODUE_HELD, 0 ) AS ODUE_HELD ,
  COALESCE(OPEN_BAL, 0 ) AS OPEN_BAL ,
  COALESCE(OPBAL_FLAG, '' ) AS OPBAL_FLAG ,
  COALESCE(OPEN_DATE, '' ) AS OPEN_DATE ,
  COALESCE(OTHER_FEES, 0 ) AS OTHER_FEES ,
  COALESCE(PAYMENT, 0 ) AS PAYMENT ,
  COALESCE(PAYMT_UNCL, 0 ) AS PAYMT_UNCL ,
  COALESCE(PEN_CHRG, 0 ) AS PEN_CHRG ,
  COALESCE(POINT_ADJ, 0 ) AS POINT_ADJ ,
  COALESCE(PTADJ_FLAG, '' ) AS PTADJ_FLAG ,
  COALESCE(POINT_CLM, 0 ) AS POINT_CLM ,
  COALESCE(POINT_CUM, 0 ) AS POINT_CUM ,
  COALESCE(PTFLAG, '' ) AS PTFLAG ,
  COALESCE(POINT_EAR, 0 ) AS POINT_EAR ,
  COALESCE(POINT_ENC, 0 ) AS POINT_ENC ,
  COALESCE(POINT_IMP, 0 ) AS POINT_IMP ,
  COALESCE(POINT_EXP, 0 ) AS POINT_EXP ,
  COALESCE(PRIOR_NO, 0 ) AS PRIOR_NO ,
  COALESCE(PURCHASES, 0 ) AS PURCHASES ,
  COALESCE(QUERY_AMT, 0 ) AS QUERY_AMT ,
  COALESCE(QUERY_CODE, '' ) AS QUERY_CODE ,
  COALESCE(RECVRY_AMT, 0 ) AS RECVRY_AMT ,
  COALESCE(REVCRY_AMT, 0 ) AS REVCRY_AMT ,
  COALESCE(STM_AMT_OL, 0 ) AS STM_AMT_OL ,
  COALESCE(STMT_CODE, '' ) AS STMT_CODE ,
  COALESCE(REPAY_AAMT, 0 ) AS REPAY_AAMT ,
  COALESCE(REPAY_ACCT, '' ) AS REPAY_ACCT ,
  COALESCE(REPAY_ADAY, 0 ) AS REPAY_ADAY ,
  COALESCE(REPAY_DAMT, 0 ) AS REPAY_DAMT ,
  COALESCE(REPAY_DDAY, 0 ) AS REPAY_DDAY ,
  COALESCE(REPAY_IDNO, '' ) AS REPAY_IDNO ,
  COALESCE(REPAY_IDTY, '' ) AS REPAY_IDTY ,
  COALESCE(REPAY_NAME, '' ) AS REPAY_NAME ,
  COALESCE(REPAY_RESP, '' ) AS REPAY_RESP ,
  COALESCE(BAL_MP, 0 ) AS BAL_MP ,
  COALESCE(POINT_CARD, 0 ) AS POINT_CARD ,
  COALESCE(PAY_FLAG, '' ) AS PAY_FLAG ,
  COALESCE(BAL_NINT01, 0 ) AS BAL_NINT01 ,
  COALESCE(BAL_NINT02, 0 ) AS BAL_NINT02 ,
  COALESCE(BAL_NINT03, 0 ) AS BAL_NINT03 ,
  COALESCE(BAL_NINT04, 0 ) AS BAL_NINT04 ,
  COALESCE(BAL_NINT05, 0 ) AS BAL_NINT05 ,
  COALESCE(BAL_NINT06, 0 ) AS BAL_NINT06 ,
  COALESCE(BAL_NINT07, 0 ) AS BAL_NINT07 ,
  COALESCE(BAL_NINT08, 0 ) AS BAL_NINT08 ,
  COALESCE(BAL_NINT09, 0 ) AS BAL_NINT09 ,
  COALESCE(BAL_NINT10, 0 ) AS BAL_NINT10 ,
  COALESCE(NBR_CASHAD_NEW, 0 ) AS NBR_CASHAD_NEW ,
  COALESCE(NBR_FEEDTY_NEW, 0 ) AS NBR_FEEDTY_NEW ,
  COALESCE(NBR_OTHERS_NEW, 0 ) AS NBR_OTHERS_NEW ,
  COALESCE(NBR_PAYMNT_NEW, 0 ) AS NBR_PAYMNT_NEW ,
  COALESCE(NBR_PURCH_NEW, 0 ) AS NBR_PURCH_NEW ,
  COALESCE(BAL_CMPFEE, 0 ) AS BAL_CMPFEE ,
  COALESCE(MTHS_ODUE, 0 ) AS MTHS_ODUE ,
  COALESCE(PURCHASES_FLAG,'') AS PURCHASES_FLAG
 FROM  dw_tdata.CCB_000_STMT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  XACCOUNT ,
  BANK ,
  CATEGORY ,
  CYCLE_NBR ,
  MONTH_NBR ,
  POST_DD ,
  AGE1 ,
  AGE2 ,
  AGE3 ,
  AGE4 ,
  AGE5 ,
  AGE6 ,
  BAL_CMPINT ,
  BAL_FREE ,
  BAL_INT ,
  BALINTFLAG ,
  BAL_NOINT ,
  BAL_ORINT ,
  BRANCH ,
  BUSINESS ,
  CARD_FEES ,
  CASH_ADFEE ,
  CASH_ADVCE ,
  CLOSE_BAL ,
  CLSBAL_FLAG ,
  CLOSE_CODE ,
  CLOSE_DATE ,
  CRED_ADJ ,
  CRED_LIMIT ,
  CRED_VOUCH ,
  CREDLIM_X ,
  CY_CHGCNT ,
  CY_CHGDAY ,
  CY_EFFDAY ,
  CYCLE_NEW ,
  DAYSPAY ,
  DEBIT_ADJ ,
  DUNCODE1 ,
  DUNCODE2 ,
  DUNCODEB ,
  DUNLETR1 ,
  DUNLETR2 ,
  DUNLETRB ,
  DUTY_CREDT ,
  DUTY_DEBIT ,
  FEES_TAXES ,
  INSTL_AMT ,
  INT_CHDCMP ,
  INT_CHGD ,
  INT_CMPOND ,
  INT_CUNOT ,
  INT_CURCMP ,
  INT_EARNED ,
  INT_RATE ,
  INT_TAXRTE ,
  LETR_CODE1 ,
  LETR_CODE2 ,
  LOSSES ,
  MIN_DUE ,
  MIN_DUE_DT ,
  MINDUE_R ,
  MSG_KEY ,
  NBR_CASHAD ,
  NBR_FEEDTY ,
  NBR_OTHERS ,
  NBR_PAYMNT ,
  NBR_PURCH ,
  ODUE_FLAG ,
  ODUE_HELD ,
  OPEN_BAL ,
  OPBAL_FLAG ,
  OPEN_DATE ,
  OTHER_FEES ,
  PAYMENT ,
  PAYMT_UNCL ,
  PEN_CHRG ,
  POINT_ADJ ,
  PTADJ_FLAG ,
  POINT_CLM ,
  POINT_CUM ,
  PTFLAG ,
  POINT_EAR ,
  POINT_ENC ,
  POINT_IMP ,
  POINT_EXP ,
  PRIOR_NO ,
  PURCHASES ,
  QUERY_AMT ,
  QUERY_CODE ,
  RECVRY_AMT ,
  REVCRY_AMT ,
  STM_AMT_OL ,
  STMT_CODE ,
  REPAY_AAMT ,
  REPAY_ACCT ,
  REPAY_ADAY ,
  REPAY_DAMT ,
  REPAY_DDAY ,
  REPAY_IDNO ,
  REPAY_IDTY ,
  REPAY_NAME ,
  REPAY_RESP ,
  BAL_MP ,
  POINT_CARD ,
  PAY_FLAG ,
  BAL_NINT01 ,
  BAL_NINT02 ,
  BAL_NINT03 ,
  BAL_NINT04 ,
  BAL_NINT05 ,
  BAL_NINT06 ,
  BAL_NINT07 ,
  BAL_NINT08 ,
  BAL_NINT09 ,
  BAL_NINT10 ,
  NBR_CASHAD_NEW ,
  NBR_FEEDTY_NEW ,
  NBR_OTHERS_NEW ,
  NBR_PAYMNT_NEW ,
  NBR_PURCH_NEW ,
  BAL_CMPFEE ,
  MTHS_ODUE ,
  PURCHASES_FLAG
 FROM dw_sdata.CCB_000_STMT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.XACCOUNT = T.XACCOUNT
WHERE
(T.XACCOUNT IS NULL)
 OR N.BANK<>T.BANK
 OR N.CATEGORY<>T.CATEGORY
 OR N.CYCLE_NBR<>T.CYCLE_NBR
 OR N.MONTH_NBR<>T.MONTH_NBR
 OR N.POST_DD<>T.POST_DD
 OR N.AGE1<>T.AGE1
 OR N.AGE2<>T.AGE2
 OR N.AGE3<>T.AGE3
 OR N.AGE4<>T.AGE4
 OR N.AGE5<>T.AGE5
 OR N.AGE6<>T.AGE6
 OR N.BAL_CMPINT<>T.BAL_CMPINT
 OR N.BAL_FREE<>T.BAL_FREE
 OR N.BAL_INT<>T.BAL_INT
 OR N.BALINTFLAG<>T.BALINTFLAG
 OR N.BAL_NOINT<>T.BAL_NOINT
 OR N.BAL_ORINT<>T.BAL_ORINT
 OR N.BRANCH<>T.BRANCH
 OR N.BUSINESS<>T.BUSINESS
 OR N.CARD_FEES<>T.CARD_FEES
 OR N.CASH_ADFEE<>T.CASH_ADFEE
 OR N.CASH_ADVCE<>T.CASH_ADVCE
 OR N.CLOSE_BAL<>T.CLOSE_BAL
 OR N.CLSBAL_FLAG<>T.CLSBAL_FLAG
 OR N.CLOSE_CODE<>T.CLOSE_CODE
 OR N.CLOSE_DATE<>T.CLOSE_DATE
 OR N.CRED_ADJ<>T.CRED_ADJ
 OR N.CRED_LIMIT<>T.CRED_LIMIT
 OR N.CRED_VOUCH<>T.CRED_VOUCH
 OR N.CREDLIM_X<>T.CREDLIM_X
 OR N.CY_CHGCNT<>T.CY_CHGCNT
 OR N.CY_CHGDAY<>T.CY_CHGDAY
 OR N.CY_EFFDAY<>T.CY_EFFDAY
 OR N.CYCLE_NEW<>T.CYCLE_NEW
 OR N.DAYSPAY<>T.DAYSPAY
 OR N.DEBIT_ADJ<>T.DEBIT_ADJ
 OR N.DUNCODE1<>T.DUNCODE1
 OR N.DUNCODE2<>T.DUNCODE2
 OR N.DUNCODEB<>T.DUNCODEB
 OR N.DUNLETR1<>T.DUNLETR1
 OR N.DUNLETR2<>T.DUNLETR2
 OR N.DUNLETRB<>T.DUNLETRB
 OR N.DUTY_CREDT<>T.DUTY_CREDT
 OR N.DUTY_DEBIT<>T.DUTY_DEBIT
 OR N.FEES_TAXES<>T.FEES_TAXES
 OR N.INSTL_AMT<>T.INSTL_AMT
 OR N.INT_CHDCMP<>T.INT_CHDCMP
 OR N.INT_CHGD<>T.INT_CHGD
 OR N.INT_CMPOND<>T.INT_CMPOND
 OR N.INT_CUNOT<>T.INT_CUNOT
 OR N.INT_CURCMP<>T.INT_CURCMP
 OR N.INT_EARNED<>T.INT_EARNED
 OR N.INT_RATE<>T.INT_RATE
 OR N.INT_TAXRTE<>T.INT_TAXRTE
 OR N.LETR_CODE1<>T.LETR_CODE1
 OR N.LETR_CODE2<>T.LETR_CODE2
 OR N.LOSSES<>T.LOSSES
 OR N.MIN_DUE<>T.MIN_DUE
 OR N.MIN_DUE_DT<>T.MIN_DUE_DT
 OR N.MINDUE_R<>T.MINDUE_R
 OR N.MSG_KEY<>T.MSG_KEY
 OR N.NBR_CASHAD<>T.NBR_CASHAD
 OR N.NBR_FEEDTY<>T.NBR_FEEDTY
 OR N.NBR_OTHERS<>T.NBR_OTHERS
 OR N.NBR_PAYMNT<>T.NBR_PAYMNT
 OR N.NBR_PURCH<>T.NBR_PURCH
 OR N.ODUE_FLAG<>T.ODUE_FLAG
 OR N.ODUE_HELD<>T.ODUE_HELD
 OR N.OPEN_BAL<>T.OPEN_BAL
 OR N.OPBAL_FLAG<>T.OPBAL_FLAG
 OR N.OPEN_DATE<>T.OPEN_DATE
 OR N.OTHER_FEES<>T.OTHER_FEES
 OR N.PAYMENT<>T.PAYMENT
 OR N.PAYMT_UNCL<>T.PAYMT_UNCL
 OR N.PEN_CHRG<>T.PEN_CHRG
 OR N.POINT_ADJ<>T.POINT_ADJ
 OR N.PTADJ_FLAG<>T.PTADJ_FLAG
 OR N.POINT_CLM<>T.POINT_CLM
 OR N.POINT_CUM<>T.POINT_CUM
 OR N.PTFLAG<>T.PTFLAG
 OR N.POINT_EAR<>T.POINT_EAR
 OR N.POINT_ENC<>T.POINT_ENC
 OR N.POINT_IMP<>T.POINT_IMP
 OR N.POINT_EXP<>T.POINT_EXP
 OR N.PRIOR_NO<>T.PRIOR_NO
 OR N.PURCHASES<>T.PURCHASES
 OR N.QUERY_AMT<>T.QUERY_AMT
 OR N.QUERY_CODE<>T.QUERY_CODE
 OR N.RECVRY_AMT<>T.RECVRY_AMT
 OR N.REVCRY_AMT<>T.REVCRY_AMT
 OR N.STM_AMT_OL<>T.STM_AMT_OL
 OR N.STMT_CODE<>T.STMT_CODE
 OR N.REPAY_AAMT<>T.REPAY_AAMT
 OR N.REPAY_ACCT<>T.REPAY_ACCT
 OR N.REPAY_ADAY<>T.REPAY_ADAY
 OR N.REPAY_DAMT<>T.REPAY_DAMT
 OR N.REPAY_DDAY<>T.REPAY_DDAY
 OR N.REPAY_IDNO<>T.REPAY_IDNO
 OR N.REPAY_IDTY<>T.REPAY_IDTY
 OR N.REPAY_NAME<>T.REPAY_NAME
 OR N.REPAY_RESP<>T.REPAY_RESP
 OR N.BAL_MP<>T.BAL_MP
 OR N.POINT_CARD<>T.POINT_CARD
 OR N.PAY_FLAG<>T.PAY_FLAG
 OR N.BAL_NINT01<>T.BAL_NINT01
 OR N.BAL_NINT02<>T.BAL_NINT02
 OR N.BAL_NINT03<>T.BAL_NINT03
 OR N.BAL_NINT04<>T.BAL_NINT04
 OR N.BAL_NINT05<>T.BAL_NINT05
 OR N.BAL_NINT06<>T.BAL_NINT06
 OR N.BAL_NINT07<>T.BAL_NINT07
 OR N.BAL_NINT08<>T.BAL_NINT08
 OR N.BAL_NINT09<>T.BAL_NINT09
 OR N.BAL_NINT10<>T.BAL_NINT10
 OR N.NBR_CASHAD_NEW<>T.NBR_CASHAD_NEW
 OR N.NBR_FEEDTY_NEW<>T.NBR_FEEDTY_NEW
 OR N.NBR_OTHERS_NEW<>T.NBR_OTHERS_NEW
 OR N.NBR_PAYMNT_NEW<>T.NBR_PAYMNT_NEW
 OR N.NBR_PURCH_NEW<>T.NBR_PURCH_NEW
 OR N.BAL_CMPFEE<>T.BAL_CMPFEE
 OR N.MTHS_ODUE<>T.MTHS_ODUE
 OR N.PURCHASES_FLAG<>T.PURCHASES_FLAG
;

--Step3:
UPDATE dw_sdata.CCB_000_STMT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_104
WHERE P.End_Dt=DATE('2100-12-31')
AND P.XACCOUNT=T_104.XACCOUNT
;

--Step4:
INSERT  INTO dw_sdata.CCB_000_STMT SELECT * FROM T_104;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
