#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_CRD_CREDIT_LIMIT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_CRD_CREDIT_LIMIT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_117 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_CRD_CREDIT_LIMIT WHERE 1=0;

--Step2:
INSERT  INTO T_117 (
  LIMIT_ID,
  CREDIT_LIMIT_NUM,
  PARTY_TYPE,
  CUSTOMER_NUM,
  CURRENCY,
  CREDIT_LIMIT,
  SUGGEST_LIMIT,
  SUGGEST_CURRENCY_CD,
  EXCHANGE_RATE,
  APPROVED_LIMIT,
  APPROVE_CREDIT_LIMIT,
  START_DATE,
  APPROVED_FREE_LIMIT,
  END_DATE,
  APPROVED_USED_LIMIT,
  STATE,
  LIMIT_TYPE,
  CIRCULAR,
  GUARANTEE_TYPE,
  INVALID_DATE,
  GUARANTEE_NOTE,
  ACCUMULATIVE_USED_LIMIT,
  ACCUMULATIVE_RESTORE_LIMIT,
  BRANCH,
  OVER_RATE,
  OVER_MONEY,
  GRACE_PERIOD,
  GRACE_PERIOD_UNIT,
  MANAGER,
  FROZEN,
  FREEZED_LIMIT,
  LAST_UPDATE_DATE,
  PARTY_ID,
  TERM,
  TERM_UNIT,
  GROUP_LIMIT_ID,
  GROUP_LIMIT_NUM,
  OLD_CREDIT_LIMIT_NUM,
  CREDIT_GRADE,
  RISK_LIMIT,
  BIZ_KIND_CD,
  RESON_CAUSE,
  BIZ_TYPE_CD,
  CONCLUSION_CD,
  APPROVE_USER,
  APPROVE_ORG,
  TIME_MARK,
  CUSTOMER_NAME,
  FINANCE_TYPE_CD,
  FINANCE_CREDIT_RATING,
  RATING_TERM,
  RATING_START_DATE,
  RATING_END_DATE,
  REGISTER_TYPE_CD,
  CREDIT_RISK_LIMIT,
  AVAILABLE_RISK_LIMIT,
  OCCU_RISK_LIMIT,
  ADVISE_COMPANY_BALANCE,
  ADVISE_CREDIT_BALANCE,
  HANDLING_DATE,
  IF_AUTO_FREEZE,
  IF_BIZ_INSERT,
  TARGER_PEER_RATE,
  ESTIMATE_CASH_FLOW_RATE,
  ESTIMATE_NET_ASSETS_RATE,
  CREDIT_END_REASON,
  CREDIT_END_REMARK,
  RISK_LIMIT_TWO,
  CREDIT_REMARKS,
  CHECK_CONCLUSION_CD,
  FINAL_COMMENTS,
  REPLY_COMMENTS,
  AUTO_FLAG,
  TERM_APPLY,
  IF_EVAL_IND,
  OLD_CREDIT_LIMIT_ID,
  CONTRACT_NUM,
  CREDIT_CHANGE_TIMES,
  DETAIL_LEVEL,
  GUARANTY_MEASURE,
  PRICING_STRUCTURE,
  CONTINUE_CONDITION,
  CREDIT_USE_PREMISE_CONDITION,
  BIZ_NUM,
  LIMIT_MODE,
  BUSINESS_MODE,
  REQUIREMENT_LIMIT,
  IMPAWN_LIMIT,
  NORMAL_APPROVED_LIMIT,
  SPECIAL_APPROVED_LIMIT,
  NORMAL_APPROVED_FREE_LIMIT,
  SPECIAL_APPROVED_FREE_LIMIT,
  NORMAL_APPROVED_USED_LIMIT,
  SPECIAL_APPROVED_USED_LIMIT,
  USED_CURRENCY_NAME,
  GUARANTYDES,
  GUARANTY_TYPE_APPROVE,
  PRICING_STRUCTURE_APPROVE,
  CONTINUE_CONDITION_APPROVE,
  CREDIT_USE_PREMISE_APPROVE,
  GUARANTYDES_APPROVE,
  LIMIT_WAY,
  INTER_CHANGABLE_RULE,
  INTER_CHANGABLE_RULE_APPR,
  START_DATE_APPL,
  END_DATE_APPL,
  TERM_UNIT_CD_APPL,
  LIMIT_NATURE,
  CREDIT_RISK_LIMIT_APPL,
  UNION_CREDIT_NUM,
  PRE_OCCUPATION_AMT,
  PRE_OCCUPY_RISK_LIMIT,
  IS_OLD_CREDIT_LIMIT,
  UNION_CREDIT_LIMIT,
  UNOIN_APPROVE_CREDIT_LIMIT,
  IF_EVAL_IND_SL,
  CONST_CREDIT_LIMIT_NUM,
  MEETING_COMMENTS,
  APPROVED_LIMIT_OLD,
  IS_HAVE_OLD_BUSINESS,
  IS_HAND_AUDIT,
  FXBS_TIME_MARK,
  OLD_GROUP_LIMIT_NUM,
  FITTED_INTO_GROUP_CRE_APPL,
  FITTED_INTO_GROUP_CRE_APPR,
  FITTED_INTO_GROUP_CRE,
  OLD_FITTED_INTO_GROUP_CRE,
  GYL_RISK_LMT_APPL,
  GYL_RISK_LMT_APPR,
  IF_CREDIT_BUSINESS,
  IF_FINANCE_CREDIT_FLAG,
  CREDIT_ADJUST_RISK_CD,
  CREDIT_ADJUST_CHANGE_CD,
  CREDIT_RECHECK_TYPE_CD,
  OLD_CUR_LIMIT_APPROVED_LIMIT,
  EVAL_NUM,
  GUARANTEE_TOTAL_LIMIT,
  GUARANTEE_USED_LIMIT,
  GUARANTEE_FREE_LIMIT,
  COMPANY_MANAGE_MODE,
  GUARANTEE_OCCUPY_LIMIT,
  GUARANTEE_PREOCCUPY_LIMIT,
  IS_CONTINUE_RECONSIDER_LIMIT,
  CONTINUE_RECONSIDER_MODE,
  FINANCE_LIMIT_TOTAL,
  BALANCE_LIMIT_TOTAL,
  RISK_LIMIT_TOTAL,
  COMMONLY_RISK_LIMIT_TOTAL,
  GUARANTEE_TOTAL_LIMIT_REPLY,
  OLD_CUR_LIMIT_RISK_LIMIT,
  GUARANTEE_TOTAL_LIMIT_APPL,
  start_dt,
  end_dt)
SELECT
  N.LIMIT_ID,
  N.CREDIT_LIMIT_NUM,
  N.PARTY_TYPE,
  N.CUSTOMER_NUM,
  N.CURRENCY,
  N.CREDIT_LIMIT,
  N.SUGGEST_LIMIT,
  N.SUGGEST_CURRENCY_CD,
  N.EXCHANGE_RATE,
  N.APPROVED_LIMIT,
  N.APPROVE_CREDIT_LIMIT,
  N.START_DATE,
  N.APPROVED_FREE_LIMIT,
  N.END_DATE,
  N.APPROVED_USED_LIMIT,
  N.STATE,
  N.LIMIT_TYPE,
  N.CIRCULAR,
  N.GUARANTEE_TYPE,
  N.INVALID_DATE,
  N.GUARANTEE_NOTE,
  N.ACCUMULATIVE_USED_LIMIT,
  N.ACCUMULATIVE_RESTORE_LIMIT,
  N.BRANCH,
  N.OVER_RATE,
  N.OVER_MONEY,
  N.GRACE_PERIOD,
  N.GRACE_PERIOD_UNIT,
  N.MANAGER,
  N.FROZEN,
  N.FREEZED_LIMIT,
  N.LAST_UPDATE_DATE,
  N.PARTY_ID,
  N.TERM,
  N.TERM_UNIT,
  N.GROUP_LIMIT_ID,
  N.GROUP_LIMIT_NUM,
  N.OLD_CREDIT_LIMIT_NUM,
  N.CREDIT_GRADE,
  N.RISK_LIMIT,
  N.BIZ_KIND_CD,
  N.RESON_CAUSE,
  N.BIZ_TYPE_CD,
  N.CONCLUSION_CD,
  N.APPROVE_USER,
  N.APPROVE_ORG,
  N.TIME_MARK,
  N.CUSTOMER_NAME,
  N.FINANCE_TYPE_CD,
  N.FINANCE_CREDIT_RATING,
  N.RATING_TERM,
  N.RATING_START_DATE,
  N.RATING_END_DATE,
  N.REGISTER_TYPE_CD,
  N.CREDIT_RISK_LIMIT,
  N.AVAILABLE_RISK_LIMIT,
  N.OCCU_RISK_LIMIT,
  N.ADVISE_COMPANY_BALANCE,
  N.ADVISE_CREDIT_BALANCE,
  N.HANDLING_DATE,
  N.IF_AUTO_FREEZE,
  N.IF_BIZ_INSERT,
  N.TARGER_PEER_RATE,
  N.ESTIMATE_CASH_FLOW_RATE,
  N.ESTIMATE_NET_ASSETS_RATE,
  N.CREDIT_END_REASON,
  N.CREDIT_END_REMARK,
  N.RISK_LIMIT_TWO,
  N.CREDIT_REMARKS,
  N.CHECK_CONCLUSION_CD,
  N.FINAL_COMMENTS,
  N.REPLY_COMMENTS,
  N.AUTO_FLAG,
  N.TERM_APPLY,
  N.IF_EVAL_IND,
  N.OLD_CREDIT_LIMIT_ID,
  N.CONTRACT_NUM,
  N.CREDIT_CHANGE_TIMES,
  N.DETAIL_LEVEL,
  N.GUARANTY_MEASURE,
  N.PRICING_STRUCTURE,
  N.CONTINUE_CONDITION,
  N.CREDIT_USE_PREMISE_CONDITION,
  N.BIZ_NUM,
  N.LIMIT_MODE,
  N.BUSINESS_MODE,
  N.REQUIREMENT_LIMIT,
  N.IMPAWN_LIMIT,
  N.NORMAL_APPROVED_LIMIT,
  N.SPECIAL_APPROVED_LIMIT,
  N.NORMAL_APPROVED_FREE_LIMIT,
  N.SPECIAL_APPROVED_FREE_LIMIT,
  N.NORMAL_APPROVED_USED_LIMIT,
  N.SPECIAL_APPROVED_USED_LIMIT,
  N.USED_CURRENCY_NAME,
  N.GUARANTYDES,
  N.GUARANTY_TYPE_APPROVE,
  N.PRICING_STRUCTURE_APPROVE,
  N.CONTINUE_CONDITION_APPROVE,
  N.CREDIT_USE_PREMISE_APPROVE,
  N.GUARANTYDES_APPROVE,
  N.LIMIT_WAY,
  N.INTER_CHANGABLE_RULE,
  N.INTER_CHANGABLE_RULE_APPR,
  N.START_DATE_APPL,
  N.END_DATE_APPL,
  N.TERM_UNIT_CD_APPL,
  N.LIMIT_NATURE,
  N.CREDIT_RISK_LIMIT_APPL,
  N.UNION_CREDIT_NUM,
  N.PRE_OCCUPATION_AMT,
  N.PRE_OCCUPY_RISK_LIMIT,
  N.IS_OLD_CREDIT_LIMIT,
  N.UNION_CREDIT_LIMIT,
  N.UNOIN_APPROVE_CREDIT_LIMIT,
  N.IF_EVAL_IND_SL,
  N.CONST_CREDIT_LIMIT_NUM,
  N.MEETING_COMMENTS,
  N.APPROVED_LIMIT_OLD,
  N.IS_HAVE_OLD_BUSINESS,
  N.IS_HAND_AUDIT,
  N.FXBS_TIME_MARK,
  N.OLD_GROUP_LIMIT_NUM,
  N.FITTED_INTO_GROUP_CRE_APPL,
  N.FITTED_INTO_GROUP_CRE_APPR,
  N.FITTED_INTO_GROUP_CRE,
  N.OLD_FITTED_INTO_GROUP_CRE,
  N.GYL_RISK_LMT_APPL,
  N.GYL_RISK_LMT_APPR,
  N.IF_CREDIT_BUSINESS,
  N.IF_FINANCE_CREDIT_FLAG,
  N.CREDIT_ADJUST_RISK_CD,
  N.CREDIT_ADJUST_CHANGE_CD,
  N.CREDIT_RECHECK_TYPE_CD,
  N.OLD_CUR_LIMIT_APPROVED_LIMIT,
  N.EVAL_NUM,
  N.GUARANTEE_TOTAL_LIMIT,
  N.GUARANTEE_USED_LIMIT,
  N.GUARANTEE_FREE_LIMIT,
  N.COMPANY_MANAGE_MODE,
  N.GUARANTEE_OCCUPY_LIMIT,
  N.GUARANTEE_PREOCCUPY_LIMIT,
  N.IS_CONTINUE_RECONSIDER_LIMIT,
  N.CONTINUE_RECONSIDER_MODE,
  N.FINANCE_LIMIT_TOTAL,
  N.BALANCE_LIMIT_TOTAL,
  N.RISK_LIMIT_TOTAL,
  N.COMMONLY_RISK_LIMIT_TOTAL,
  N.GUARANTEE_TOTAL_LIMIT_REPLY,
  N.OLD_CUR_LIMIT_RISK_LIMIT,
  N.GUARANTEE_TOTAL_LIMIT_APPL,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(LIMIT_ID, '' ) AS LIMIT_ID ,
  COALESCE(CREDIT_LIMIT_NUM, '' ) AS CREDIT_LIMIT_NUM ,
  COALESCE(PARTY_TYPE, '' ) AS PARTY_TYPE ,
  COALESCE(CUSTOMER_NUM, '' ) AS CUSTOMER_NUM ,
  COALESCE(CURRENCY, '' ) AS CURRENCY ,
  COALESCE(CREDIT_LIMIT, 0 ) AS CREDIT_LIMIT ,
  COALESCE(SUGGEST_LIMIT, 0 ) AS SUGGEST_LIMIT ,
  COALESCE(SUGGEST_CURRENCY_CD, '' ) AS SUGGEST_CURRENCY_CD ,
  COALESCE(EXCHANGE_RATE, 0 ) AS EXCHANGE_RATE ,
  COALESCE(APPROVED_LIMIT, 0 ) AS APPROVED_LIMIT ,
  COALESCE(APPROVE_CREDIT_LIMIT, 0 ) AS APPROVE_CREDIT_LIMIT ,
  COALESCE(START_DATE,'4999-12-31 00:00:00' ) AS START_DATE ,
  COALESCE(APPROVED_FREE_LIMIT, 0 ) AS APPROVED_FREE_LIMIT ,
  COALESCE(END_DATE,'4999-12-31 00:00:00' ) AS END_DATE ,
  COALESCE(APPROVED_USED_LIMIT, 0 ) AS APPROVED_USED_LIMIT ,
  COALESCE(STATE, '' ) AS STATE ,
  COALESCE(LIMIT_TYPE, '' ) AS LIMIT_TYPE ,
  COALESCE(CIRCULAR, '' ) AS CIRCULAR ,
  COALESCE(GUARANTEE_TYPE, '' ) AS GUARANTEE_TYPE ,
  COALESCE(INVALID_DATE,'4999-12-31 00:00:00' ) AS INVALID_DATE ,
  COALESCE(GUARANTEE_NOTE, '' ) AS GUARANTEE_NOTE ,
  COALESCE(ACCUMULATIVE_USED_LIMIT, 0 ) AS ACCUMULATIVE_USED_LIMIT ,
  COALESCE(ACCUMULATIVE_RESTORE_LIMIT, 0 ) AS ACCUMULATIVE_RESTORE_LIMIT ,
  COALESCE(BRANCH, '' ) AS BRANCH ,
  COALESCE(OVER_RATE, 0 ) AS OVER_RATE ,
  COALESCE(OVER_MONEY, 0 ) AS OVER_MONEY ,
  COALESCE(GRACE_PERIOD, 0 ) AS GRACE_PERIOD ,
  COALESCE(GRACE_PERIOD_UNIT, '' ) AS GRACE_PERIOD_UNIT ,
  COALESCE(MANAGER, '' ) AS MANAGER ,
  COALESCE(FROZEN, '' ) AS FROZEN ,
  COALESCE(FREEZED_LIMIT, 0 ) AS FREEZED_LIMIT ,
  COALESCE(LAST_UPDATE_DATE,'4999-12-31 00:00:00' ) AS LAST_UPDATE_DATE ,
  COALESCE(PARTY_ID, '' ) AS PARTY_ID ,
  COALESCE(TERM, 0 ) AS TERM ,
  COALESCE(TERM_UNIT, '' ) AS TERM_UNIT ,
  COALESCE(GROUP_LIMIT_ID, '' ) AS GROUP_LIMIT_ID ,
  COALESCE(GROUP_LIMIT_NUM, '' ) AS GROUP_LIMIT_NUM ,
  COALESCE(OLD_CREDIT_LIMIT_NUM, '' ) AS OLD_CREDIT_LIMIT_NUM ,
  COALESCE(CREDIT_GRADE, '' ) AS CREDIT_GRADE ,
  COALESCE(RISK_LIMIT, 0 ) AS RISK_LIMIT ,
  COALESCE(BIZ_KIND_CD, '' ) AS BIZ_KIND_CD ,
  COALESCE(RESON_CAUSE, '' ) AS RESON_CAUSE ,
  COALESCE(BIZ_TYPE_CD, '' ) AS BIZ_TYPE_CD ,
  COALESCE(CONCLUSION_CD, '' ) AS CONCLUSION_CD ,
  COALESCE(APPROVE_USER, '' ) AS APPROVE_USER ,
  COALESCE(APPROVE_ORG, '' ) AS APPROVE_ORG ,
  COALESCE(TIME_MARK,'4999-12-31 00:00:00' ) AS TIME_MARK ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(FINANCE_TYPE_CD, '' ) AS FINANCE_TYPE_CD ,
  COALESCE(FINANCE_CREDIT_RATING, '' ) AS FINANCE_CREDIT_RATING ,
  COALESCE(RATING_TERM, 0 ) AS RATING_TERM ,
  COALESCE(RATING_START_DATE,'4999-12-31 00:00:00' ) AS RATING_START_DATE ,
  COALESCE(RATING_END_DATE,'4999-12-31 00:00:00' ) AS RATING_END_DATE ,
  COALESCE(REGISTER_TYPE_CD, '' ) AS REGISTER_TYPE_CD ,
  COALESCE(CREDIT_RISK_LIMIT, 0 ) AS CREDIT_RISK_LIMIT ,
  COALESCE(AVAILABLE_RISK_LIMIT, 0 ) AS AVAILABLE_RISK_LIMIT ,
  COALESCE(OCCU_RISK_LIMIT, 0 ) AS OCCU_RISK_LIMIT ,
  COALESCE(ADVISE_COMPANY_BALANCE, 0 ) AS ADVISE_COMPANY_BALANCE ,
  COALESCE(ADVISE_CREDIT_BALANCE, 0 ) AS ADVISE_CREDIT_BALANCE ,
  COALESCE(HANDLING_DATE,'4999-12-31 00:00:00' ) AS HANDLING_DATE ,
  COALESCE(IF_AUTO_FREEZE, '' ) AS IF_AUTO_FREEZE ,
  COALESCE(IF_BIZ_INSERT, '' ) AS IF_BIZ_INSERT ,
  COALESCE(TARGER_PEER_RATE, 0 ) AS TARGER_PEER_RATE ,
  COALESCE(ESTIMATE_CASH_FLOW_RATE, 0 ) AS ESTIMATE_CASH_FLOW_RATE ,
  COALESCE(ESTIMATE_NET_ASSETS_RATE, 0 ) AS ESTIMATE_NET_ASSETS_RATE ,
  COALESCE(CREDIT_END_REASON, '' ) AS CREDIT_END_REASON ,
  COALESCE(CREDIT_END_REMARK, '' ) AS CREDIT_END_REMARK ,
  COALESCE(RISK_LIMIT_TWO, 0 ) AS RISK_LIMIT_TWO ,
  COALESCE(CREDIT_REMARKS, '' ) AS CREDIT_REMARKS ,
  COALESCE(CHECK_CONCLUSION_CD, '' ) AS CHECK_CONCLUSION_CD ,
  COALESCE(FINAL_COMMENTS, '' ) AS FINAL_COMMENTS ,
  COALESCE(REPLY_COMMENTS, '' ) AS REPLY_COMMENTS ,
  COALESCE(AUTO_FLAG, '' ) AS AUTO_FLAG ,
  COALESCE(TERM_APPLY, 0 ) AS TERM_APPLY ,
  COALESCE(IF_EVAL_IND, '' ) AS IF_EVAL_IND ,
  COALESCE(OLD_CREDIT_LIMIT_ID, '' ) AS OLD_CREDIT_LIMIT_ID ,
  COALESCE(CONTRACT_NUM, '' ) AS CONTRACT_NUM ,
  COALESCE(CREDIT_CHANGE_TIMES, 0 ) AS CREDIT_CHANGE_TIMES ,
  COALESCE(DETAIL_LEVEL, '' ) AS DETAIL_LEVEL ,
  COALESCE(GUARANTY_MEASURE, '' ) AS GUARANTY_MEASURE ,
  COALESCE(PRICING_STRUCTURE, '' ) AS PRICING_STRUCTURE ,
  COALESCE(CONTINUE_CONDITION, '' ) AS CONTINUE_CONDITION ,
  COALESCE(CREDIT_USE_PREMISE_CONDITION, '' ) AS CREDIT_USE_PREMISE_CONDITION ,
  COALESCE(BIZ_NUM, '' ) AS BIZ_NUM ,
  COALESCE(LIMIT_MODE, '' ) AS LIMIT_MODE ,
  COALESCE(BUSINESS_MODE, '' ) AS BUSINESS_MODE ,
  COALESCE(REQUIREMENT_LIMIT, 0 ) AS REQUIREMENT_LIMIT ,
  COALESCE(IMPAWN_LIMIT, 0 ) AS IMPAWN_LIMIT ,
  COALESCE(NORMAL_APPROVED_LIMIT, 0 ) AS NORMAL_APPROVED_LIMIT ,
  COALESCE(SPECIAL_APPROVED_LIMIT, 0 ) AS SPECIAL_APPROVED_LIMIT ,
  COALESCE(NORMAL_APPROVED_FREE_LIMIT, 0 ) AS NORMAL_APPROVED_FREE_LIMIT ,
  COALESCE(SPECIAL_APPROVED_FREE_LIMIT, 0 ) AS SPECIAL_APPROVED_FREE_LIMIT ,
  COALESCE(NORMAL_APPROVED_USED_LIMIT, 0 ) AS NORMAL_APPROVED_USED_LIMIT ,
  COALESCE(SPECIAL_APPROVED_USED_LIMIT, 0 ) AS SPECIAL_APPROVED_USED_LIMIT ,
  COALESCE(USED_CURRENCY_NAME, '' ) AS USED_CURRENCY_NAME ,
  COALESCE(GUARANTYDES, '' ) AS GUARANTYDES ,
  COALESCE(GUARANTY_TYPE_APPROVE, '' ) AS GUARANTY_TYPE_APPROVE ,
  COALESCE(PRICING_STRUCTURE_APPROVE, '' ) AS PRICING_STRUCTURE_APPROVE ,
  COALESCE(CONTINUE_CONDITION_APPROVE, '' ) AS CONTINUE_CONDITION_APPROVE ,
  COALESCE(CREDIT_USE_PREMISE_APPROVE, '' ) AS CREDIT_USE_PREMISE_APPROVE ,
  COALESCE(GUARANTYDES_APPROVE, '' ) AS GUARANTYDES_APPROVE ,
  COALESCE(LIMIT_WAY, '' ) AS LIMIT_WAY ,
  COALESCE(INTER_CHANGABLE_RULE, '' ) AS INTER_CHANGABLE_RULE ,
  COALESCE(INTER_CHANGABLE_RULE_APPR, '' ) AS INTER_CHANGABLE_RULE_APPR ,
  COALESCE(START_DATE_APPL,'4999-12-31 00:00:00' ) AS START_DATE_APPL ,
  COALESCE(END_DATE_APPL,'4999-12-31 00:00:00' ) AS END_DATE_APPL ,
  COALESCE(TERM_UNIT_CD_APPL, '' ) AS TERM_UNIT_CD_APPL ,
  COALESCE(LIMIT_NATURE, '' ) AS LIMIT_NATURE ,
  COALESCE(CREDIT_RISK_LIMIT_APPL, 0 ) AS CREDIT_RISK_LIMIT_APPL ,
  COALESCE(UNION_CREDIT_NUM, '' ) AS UNION_CREDIT_NUM ,
  COALESCE(PRE_OCCUPATION_AMT, 0 ) AS PRE_OCCUPATION_AMT ,
  COALESCE(PRE_OCCUPY_RISK_LIMIT, 0 ) AS PRE_OCCUPY_RISK_LIMIT ,
  COALESCE(IS_OLD_CREDIT_LIMIT, '' ) AS IS_OLD_CREDIT_LIMIT ,
  COALESCE(UNION_CREDIT_LIMIT, 0 ) AS UNION_CREDIT_LIMIT ,
  COALESCE(UNOIN_APPROVE_CREDIT_LIMIT, 0 ) AS UNOIN_APPROVE_CREDIT_LIMIT ,
  COALESCE(IF_EVAL_IND_SL, '' ) AS IF_EVAL_IND_SL ,
  COALESCE(CONST_CREDIT_LIMIT_NUM, '' ) AS CONST_CREDIT_LIMIT_NUM ,
  COALESCE(MEETING_COMMENTS, '' ) AS MEETING_COMMENTS ,
  COALESCE(APPROVED_LIMIT_OLD, 0 ) AS APPROVED_LIMIT_OLD ,
  COALESCE(IS_HAVE_OLD_BUSINESS, '' ) AS IS_HAVE_OLD_BUSINESS ,
  COALESCE(IS_HAND_AUDIT, '' ) AS IS_HAND_AUDIT ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(OLD_GROUP_LIMIT_NUM, '' ) AS OLD_GROUP_LIMIT_NUM ,
  COALESCE(FITTED_INTO_GROUP_CRE_APPL, '' ) AS FITTED_INTO_GROUP_CRE_APPL ,
  COALESCE(FITTED_INTO_GROUP_CRE_APPR, '' ) AS FITTED_INTO_GROUP_CRE_APPR ,
  COALESCE(FITTED_INTO_GROUP_CRE, '' ) AS FITTED_INTO_GROUP_CRE ,
  COALESCE(OLD_FITTED_INTO_GROUP_CRE, '' ) AS OLD_FITTED_INTO_GROUP_CRE ,
  COALESCE(GYL_RISK_LMT_APPL, 0 ) AS GYL_RISK_LMT_APPL ,
  COALESCE(GYL_RISK_LMT_APPR, 0 ) AS GYL_RISK_LMT_APPR ,
  COALESCE(IF_CREDIT_BUSINESS, '' ) AS IF_CREDIT_BUSINESS ,
  COALESCE(IF_FINANCE_CREDIT_FLAG, '' ) AS IF_FINANCE_CREDIT_FLAG ,
  COALESCE(CREDIT_ADJUST_RISK_CD, '' ) AS CREDIT_ADJUST_RISK_CD ,
  COALESCE(CREDIT_ADJUST_CHANGE_CD, '' ) AS CREDIT_ADJUST_CHANGE_CD ,
  COALESCE(CREDIT_RECHECK_TYPE_CD, '' ) AS CREDIT_RECHECK_TYPE_CD ,
  COALESCE(OLD_CUR_LIMIT_APPROVED_LIMIT, 0 ) AS OLD_CUR_LIMIT_APPROVED_LIMIT ,
  COALESCE(EVAL_NUM, '' ) AS EVAL_NUM ,
  COALESCE(GUARANTEE_TOTAL_LIMIT, 0 ) AS GUARANTEE_TOTAL_LIMIT ,
  COALESCE(GUARANTEE_USED_LIMIT, 0 ) AS GUARANTEE_USED_LIMIT ,
  COALESCE(GUARANTEE_FREE_LIMIT, 0 ) AS GUARANTEE_FREE_LIMIT ,
  COALESCE(COMPANY_MANAGE_MODE, '' ) AS COMPANY_MANAGE_MODE ,
  COALESCE(GUARANTEE_OCCUPY_LIMIT, 0 ) AS GUARANTEE_OCCUPY_LIMIT ,
  COALESCE(GUARANTEE_PREOCCUPY_LIMIT, 0 ) AS GUARANTEE_PREOCCUPY_LIMIT ,
  COALESCE(IS_CONTINUE_RECONSIDER_LIMIT, '' ) AS IS_CONTINUE_RECONSIDER_LIMIT ,
  COALESCE(CONTINUE_RECONSIDER_MODE, '' ) AS CONTINUE_RECONSIDER_MODE ,
  COALESCE(FINANCE_LIMIT_TOTAL, 0 ) AS FINANCE_LIMIT_TOTAL ,
  COALESCE(BALANCE_LIMIT_TOTAL, 0 ) AS BALANCE_LIMIT_TOTAL ,
  COALESCE(RISK_LIMIT_TOTAL, 0 ) AS RISK_LIMIT_TOTAL ,
  COALESCE(COMMONLY_RISK_LIMIT_TOTAL, 0 ) AS COMMONLY_RISK_LIMIT_TOTAL ,
  COALESCE(GUARANTEE_TOTAL_LIMIT_REPLY, 0 ) AS GUARANTEE_TOTAL_LIMIT_REPLY ,
  COALESCE(OLD_CUR_LIMIT_RISK_LIMIT, 0 ) AS OLD_CUR_LIMIT_RISK_LIMIT ,
  COALESCE(GUARANTEE_TOTAL_LIMIT_APPL, 0 ) AS GUARANTEE_TOTAL_LIMIT_APPL 
 FROM  dw_tdata.CCS_004_TB_CRD_CREDIT_LIMIT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  LIMIT_ID ,
  CREDIT_LIMIT_NUM ,
  PARTY_TYPE ,
  CUSTOMER_NUM ,
  CURRENCY ,
  CREDIT_LIMIT ,
  SUGGEST_LIMIT ,
  SUGGEST_CURRENCY_CD ,
  EXCHANGE_RATE ,
  APPROVED_LIMIT ,
  APPROVE_CREDIT_LIMIT ,
  START_DATE ,
  APPROVED_FREE_LIMIT ,
  END_DATE ,
  APPROVED_USED_LIMIT ,
  STATE ,
  LIMIT_TYPE ,
  CIRCULAR ,
  GUARANTEE_TYPE ,
  INVALID_DATE ,
  GUARANTEE_NOTE ,
  ACCUMULATIVE_USED_LIMIT ,
  ACCUMULATIVE_RESTORE_LIMIT ,
  BRANCH ,
  OVER_RATE ,
  OVER_MONEY ,
  GRACE_PERIOD ,
  GRACE_PERIOD_UNIT ,
  MANAGER ,
  FROZEN ,
  FREEZED_LIMIT ,
  LAST_UPDATE_DATE ,
  PARTY_ID ,
  TERM ,
  TERM_UNIT ,
  GROUP_LIMIT_ID ,
  GROUP_LIMIT_NUM ,
  OLD_CREDIT_LIMIT_NUM ,
  CREDIT_GRADE ,
  RISK_LIMIT ,
  BIZ_KIND_CD ,
  RESON_CAUSE ,
  BIZ_TYPE_CD ,
  CONCLUSION_CD ,
  APPROVE_USER ,
  APPROVE_ORG ,
  TIME_MARK ,
  CUSTOMER_NAME ,
  FINANCE_TYPE_CD ,
  FINANCE_CREDIT_RATING ,
  RATING_TERM ,
  RATING_START_DATE ,
  RATING_END_DATE ,
  REGISTER_TYPE_CD ,
  CREDIT_RISK_LIMIT ,
  AVAILABLE_RISK_LIMIT ,
  OCCU_RISK_LIMIT ,
  ADVISE_COMPANY_BALANCE ,
  ADVISE_CREDIT_BALANCE ,
  HANDLING_DATE ,
  IF_AUTO_FREEZE ,
  IF_BIZ_INSERT ,
  TARGER_PEER_RATE ,
  ESTIMATE_CASH_FLOW_RATE ,
  ESTIMATE_NET_ASSETS_RATE ,
  CREDIT_END_REASON ,
  CREDIT_END_REMARK ,
  RISK_LIMIT_TWO ,
  CREDIT_REMARKS ,
  CHECK_CONCLUSION_CD ,
  FINAL_COMMENTS ,
  REPLY_COMMENTS ,
  AUTO_FLAG ,
  TERM_APPLY ,
  IF_EVAL_IND ,
  OLD_CREDIT_LIMIT_ID ,
  CONTRACT_NUM ,
  CREDIT_CHANGE_TIMES ,
  DETAIL_LEVEL ,
  GUARANTY_MEASURE ,
  PRICING_STRUCTURE ,
  CONTINUE_CONDITION ,
  CREDIT_USE_PREMISE_CONDITION ,
  BIZ_NUM ,
  LIMIT_MODE ,
  BUSINESS_MODE ,
  REQUIREMENT_LIMIT ,
  IMPAWN_LIMIT ,
  NORMAL_APPROVED_LIMIT ,
  SPECIAL_APPROVED_LIMIT ,
  NORMAL_APPROVED_FREE_LIMIT ,
  SPECIAL_APPROVED_FREE_LIMIT ,
  NORMAL_APPROVED_USED_LIMIT ,
  SPECIAL_APPROVED_USED_LIMIT ,
  USED_CURRENCY_NAME ,
  GUARANTYDES ,
  GUARANTY_TYPE_APPROVE ,
  PRICING_STRUCTURE_APPROVE ,
  CONTINUE_CONDITION_APPROVE ,
  CREDIT_USE_PREMISE_APPROVE ,
  GUARANTYDES_APPROVE ,
  LIMIT_WAY ,
  INTER_CHANGABLE_RULE ,
  INTER_CHANGABLE_RULE_APPR ,
  START_DATE_APPL ,
  END_DATE_APPL ,
  TERM_UNIT_CD_APPL ,
  LIMIT_NATURE ,
  CREDIT_RISK_LIMIT_APPL ,
  UNION_CREDIT_NUM ,
  PRE_OCCUPATION_AMT ,
  PRE_OCCUPY_RISK_LIMIT ,
  IS_OLD_CREDIT_LIMIT ,
  UNION_CREDIT_LIMIT ,
  UNOIN_APPROVE_CREDIT_LIMIT ,
  IF_EVAL_IND_SL ,
  CONST_CREDIT_LIMIT_NUM ,
  MEETING_COMMENTS ,
  APPROVED_LIMIT_OLD ,
  IS_HAVE_OLD_BUSINESS ,
  IS_HAND_AUDIT ,
  FXBS_TIME_MARK ,
  OLD_GROUP_LIMIT_NUM ,
  FITTED_INTO_GROUP_CRE_APPL ,
  FITTED_INTO_GROUP_CRE_APPR ,
  FITTED_INTO_GROUP_CRE ,
  OLD_FITTED_INTO_GROUP_CRE ,
  GYL_RISK_LMT_APPL ,
  GYL_RISK_LMT_APPR ,
  IF_CREDIT_BUSINESS ,
  IF_FINANCE_CREDIT_FLAG ,
  CREDIT_ADJUST_RISK_CD ,
  CREDIT_ADJUST_CHANGE_CD ,
  CREDIT_RECHECK_TYPE_CD ,
  OLD_CUR_LIMIT_APPROVED_LIMIT ,
  EVAL_NUM ,
  GUARANTEE_TOTAL_LIMIT ,
  GUARANTEE_USED_LIMIT ,
  GUARANTEE_FREE_LIMIT ,
  COMPANY_MANAGE_MODE ,
  GUARANTEE_OCCUPY_LIMIT ,
  GUARANTEE_PREOCCUPY_LIMIT ,
  IS_CONTINUE_RECONSIDER_LIMIT ,
  CONTINUE_RECONSIDER_MODE ,
  FINANCE_LIMIT_TOTAL ,
  BALANCE_LIMIT_TOTAL ,
  RISK_LIMIT_TOTAL ,
  COMMONLY_RISK_LIMIT_TOTAL ,
  GUARANTEE_TOTAL_LIMIT_REPLY ,
  OLD_CUR_LIMIT_RISK_LIMIT ,
  GUARANTEE_TOTAL_LIMIT_APPL 
 FROM dw_sdata.CCS_004_TB_CRD_CREDIT_LIMIT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.LIMIT_ID = T.LIMIT_ID
WHERE
(T.LIMIT_ID IS NULL)
 OR N.CREDIT_LIMIT_NUM<>T.CREDIT_LIMIT_NUM
 OR N.PARTY_TYPE<>T.PARTY_TYPE
 OR N.CUSTOMER_NUM<>T.CUSTOMER_NUM
 OR N.CURRENCY<>T.CURRENCY
 OR N.CREDIT_LIMIT<>T.CREDIT_LIMIT
 OR N.SUGGEST_LIMIT<>T.SUGGEST_LIMIT
 OR N.SUGGEST_CURRENCY_CD<>T.SUGGEST_CURRENCY_CD
 OR N.EXCHANGE_RATE<>T.EXCHANGE_RATE
 OR N.APPROVED_LIMIT<>T.APPROVED_LIMIT
 OR N.APPROVE_CREDIT_LIMIT<>T.APPROVE_CREDIT_LIMIT
 OR N.START_DATE<>T.START_DATE
 OR N.APPROVED_FREE_LIMIT<>T.APPROVED_FREE_LIMIT
 OR N.END_DATE<>T.END_DATE
 OR N.APPROVED_USED_LIMIT<>T.APPROVED_USED_LIMIT
 OR N.STATE<>T.STATE
 OR N.LIMIT_TYPE<>T.LIMIT_TYPE
 OR N.CIRCULAR<>T.CIRCULAR
 OR N.GUARANTEE_TYPE<>T.GUARANTEE_TYPE
 OR N.INVALID_DATE<>T.INVALID_DATE
 OR N.GUARANTEE_NOTE<>T.GUARANTEE_NOTE
 OR N.ACCUMULATIVE_USED_LIMIT<>T.ACCUMULATIVE_USED_LIMIT
 OR N.ACCUMULATIVE_RESTORE_LIMIT<>T.ACCUMULATIVE_RESTORE_LIMIT
 OR N.BRANCH<>T.BRANCH
 OR N.OVER_RATE<>T.OVER_RATE
 OR N.OVER_MONEY<>T.OVER_MONEY
 OR N.GRACE_PERIOD<>T.GRACE_PERIOD
 OR N.GRACE_PERIOD_UNIT<>T.GRACE_PERIOD_UNIT
 OR N.MANAGER<>T.MANAGER
 OR N.FROZEN<>T.FROZEN
 OR N.FREEZED_LIMIT<>T.FREEZED_LIMIT
 OR N.LAST_UPDATE_DATE<>T.LAST_UPDATE_DATE
 OR N.PARTY_ID<>T.PARTY_ID
 OR N.TERM<>T.TERM
 OR N.TERM_UNIT<>T.TERM_UNIT
 OR N.GROUP_LIMIT_ID<>T.GROUP_LIMIT_ID
 OR N.GROUP_LIMIT_NUM<>T.GROUP_LIMIT_NUM
 OR N.OLD_CREDIT_LIMIT_NUM<>T.OLD_CREDIT_LIMIT_NUM
 OR N.CREDIT_GRADE<>T.CREDIT_GRADE
 OR N.RISK_LIMIT<>T.RISK_LIMIT
 OR N.BIZ_KIND_CD<>T.BIZ_KIND_CD
 OR N.RESON_CAUSE<>T.RESON_CAUSE
 OR N.BIZ_TYPE_CD<>T.BIZ_TYPE_CD
 OR N.CONCLUSION_CD<>T.CONCLUSION_CD
 OR N.APPROVE_USER<>T.APPROVE_USER
 OR N.APPROVE_ORG<>T.APPROVE_ORG
 OR N.TIME_MARK<>T.TIME_MARK
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.FINANCE_TYPE_CD<>T.FINANCE_TYPE_CD
 OR N.FINANCE_CREDIT_RATING<>T.FINANCE_CREDIT_RATING
 OR N.RATING_TERM<>T.RATING_TERM
 OR N.RATING_START_DATE<>T.RATING_START_DATE
 OR N.RATING_END_DATE<>T.RATING_END_DATE
 OR N.REGISTER_TYPE_CD<>T.REGISTER_TYPE_CD
 OR N.CREDIT_RISK_LIMIT<>T.CREDIT_RISK_LIMIT
 OR N.AVAILABLE_RISK_LIMIT<>T.AVAILABLE_RISK_LIMIT
 OR N.OCCU_RISK_LIMIT<>T.OCCU_RISK_LIMIT
 OR N.ADVISE_COMPANY_BALANCE<>T.ADVISE_COMPANY_BALANCE
 OR N.ADVISE_CREDIT_BALANCE<>T.ADVISE_CREDIT_BALANCE
 OR N.HANDLING_DATE<>T.HANDLING_DATE
 OR N.IF_AUTO_FREEZE<>T.IF_AUTO_FREEZE
 OR N.IF_BIZ_INSERT<>T.IF_BIZ_INSERT
 OR N.TARGER_PEER_RATE<>T.TARGER_PEER_RATE
 OR N.ESTIMATE_CASH_FLOW_RATE<>T.ESTIMATE_CASH_FLOW_RATE
 OR N.ESTIMATE_NET_ASSETS_RATE<>T.ESTIMATE_NET_ASSETS_RATE
 OR N.CREDIT_END_REASON<>T.CREDIT_END_REASON
 OR N.CREDIT_END_REMARK<>T.CREDIT_END_REMARK
 OR N.RISK_LIMIT_TWO<>T.RISK_LIMIT_TWO
 OR N.CREDIT_REMARKS<>T.CREDIT_REMARKS
 OR N.CHECK_CONCLUSION_CD<>T.CHECK_CONCLUSION_CD
 OR N.FINAL_COMMENTS<>T.FINAL_COMMENTS
 OR N.REPLY_COMMENTS<>T.REPLY_COMMENTS
 OR N.AUTO_FLAG<>T.AUTO_FLAG
 OR N.TERM_APPLY<>T.TERM_APPLY
 OR N.IF_EVAL_IND<>T.IF_EVAL_IND
 OR N.OLD_CREDIT_LIMIT_ID<>T.OLD_CREDIT_LIMIT_ID
 OR N.CONTRACT_NUM<>T.CONTRACT_NUM
 OR N.CREDIT_CHANGE_TIMES<>T.CREDIT_CHANGE_TIMES
 OR N.DETAIL_LEVEL<>T.DETAIL_LEVEL
 OR N.GUARANTY_MEASURE<>T.GUARANTY_MEASURE
 OR N.PRICING_STRUCTURE<>T.PRICING_STRUCTURE
 OR N.CONTINUE_CONDITION<>T.CONTINUE_CONDITION
 OR N.CREDIT_USE_PREMISE_CONDITION<>T.CREDIT_USE_PREMISE_CONDITION
 OR N.BIZ_NUM<>T.BIZ_NUM
 OR N.LIMIT_MODE<>T.LIMIT_MODE
 OR N.BUSINESS_MODE<>T.BUSINESS_MODE
 OR N.REQUIREMENT_LIMIT<>T.REQUIREMENT_LIMIT
 OR N.IMPAWN_LIMIT<>T.IMPAWN_LIMIT
 OR N.NORMAL_APPROVED_LIMIT<>T.NORMAL_APPROVED_LIMIT
 OR N.SPECIAL_APPROVED_LIMIT<>T.SPECIAL_APPROVED_LIMIT
 OR N.NORMAL_APPROVED_FREE_LIMIT<>T.NORMAL_APPROVED_FREE_LIMIT
 OR N.SPECIAL_APPROVED_FREE_LIMIT<>T.SPECIAL_APPROVED_FREE_LIMIT
 OR N.NORMAL_APPROVED_USED_LIMIT<>T.NORMAL_APPROVED_USED_LIMIT
 OR N.SPECIAL_APPROVED_USED_LIMIT<>T.SPECIAL_APPROVED_USED_LIMIT
 OR N.USED_CURRENCY_NAME<>T.USED_CURRENCY_NAME
 OR N.GUARANTYDES<>T.GUARANTYDES
 OR N.GUARANTY_TYPE_APPROVE<>T.GUARANTY_TYPE_APPROVE
 OR N.PRICING_STRUCTURE_APPROVE<>T.PRICING_STRUCTURE_APPROVE
 OR N.CONTINUE_CONDITION_APPROVE<>T.CONTINUE_CONDITION_APPROVE
 OR N.CREDIT_USE_PREMISE_APPROVE<>T.CREDIT_USE_PREMISE_APPROVE
 OR N.GUARANTYDES_APPROVE<>T.GUARANTYDES_APPROVE
 OR N.LIMIT_WAY<>T.LIMIT_WAY
 OR N.INTER_CHANGABLE_RULE<>T.INTER_CHANGABLE_RULE
 OR N.INTER_CHANGABLE_RULE_APPR<>T.INTER_CHANGABLE_RULE_APPR
 OR N.START_DATE_APPL<>T.START_DATE_APPL
 OR N.END_DATE_APPL<>T.END_DATE_APPL
 OR N.TERM_UNIT_CD_APPL<>T.TERM_UNIT_CD_APPL
 OR N.LIMIT_NATURE<>T.LIMIT_NATURE
 OR N.CREDIT_RISK_LIMIT_APPL<>T.CREDIT_RISK_LIMIT_APPL
 OR N.UNION_CREDIT_NUM<>T.UNION_CREDIT_NUM
 OR N.PRE_OCCUPATION_AMT<>T.PRE_OCCUPATION_AMT
 OR N.PRE_OCCUPY_RISK_LIMIT<>T.PRE_OCCUPY_RISK_LIMIT
 OR N.IS_OLD_CREDIT_LIMIT<>T.IS_OLD_CREDIT_LIMIT
 OR N.UNION_CREDIT_LIMIT<>T.UNION_CREDIT_LIMIT
 OR N.UNOIN_APPROVE_CREDIT_LIMIT<>T.UNOIN_APPROVE_CREDIT_LIMIT
 OR N.IF_EVAL_IND_SL<>T.IF_EVAL_IND_SL
 OR N.CONST_CREDIT_LIMIT_NUM<>T.CONST_CREDIT_LIMIT_NUM
 OR N.MEETING_COMMENTS<>T.MEETING_COMMENTS
 OR N.APPROVED_LIMIT_OLD<>T.APPROVED_LIMIT_OLD
 OR N.IS_HAVE_OLD_BUSINESS<>T.IS_HAVE_OLD_BUSINESS
 OR N.IS_HAND_AUDIT<>T.IS_HAND_AUDIT
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.OLD_GROUP_LIMIT_NUM<>T.OLD_GROUP_LIMIT_NUM
 OR N.FITTED_INTO_GROUP_CRE_APPL<>T.FITTED_INTO_GROUP_CRE_APPL
 OR N.FITTED_INTO_GROUP_CRE_APPR<>T.FITTED_INTO_GROUP_CRE_APPR
 OR N.FITTED_INTO_GROUP_CRE<>T.FITTED_INTO_GROUP_CRE
 OR N.OLD_FITTED_INTO_GROUP_CRE<>T.OLD_FITTED_INTO_GROUP_CRE
 OR N.GYL_RISK_LMT_APPL<>T.GYL_RISK_LMT_APPL
 OR N.GYL_RISK_LMT_APPR<>T.GYL_RISK_LMT_APPR
 OR N.IF_CREDIT_BUSINESS<>T.IF_CREDIT_BUSINESS
 OR N.IF_FINANCE_CREDIT_FLAG<>T.IF_FINANCE_CREDIT_FLAG
 OR N.CREDIT_ADJUST_RISK_CD<>T.CREDIT_ADJUST_RISK_CD
 OR N.CREDIT_ADJUST_CHANGE_CD<>T.CREDIT_ADJUST_CHANGE_CD
 OR N.CREDIT_RECHECK_TYPE_CD<>T.CREDIT_RECHECK_TYPE_CD
 OR N.OLD_CUR_LIMIT_APPROVED_LIMIT<>T.OLD_CUR_LIMIT_APPROVED_LIMIT
 OR N.EVAL_NUM<>T.EVAL_NUM
 OR N.GUARANTEE_TOTAL_LIMIT<>T.GUARANTEE_TOTAL_LIMIT
 OR N.GUARANTEE_USED_LIMIT<>T.GUARANTEE_USED_LIMIT
 OR N.GUARANTEE_FREE_LIMIT<>T.GUARANTEE_FREE_LIMIT
 OR N.COMPANY_MANAGE_MODE<>T.COMPANY_MANAGE_MODE
 OR N.GUARANTEE_OCCUPY_LIMIT<>T.GUARANTEE_OCCUPY_LIMIT
 OR N.GUARANTEE_PREOCCUPY_LIMIT<>T.GUARANTEE_PREOCCUPY_LIMIT
 OR N.IS_CONTINUE_RECONSIDER_LIMIT<>T.IS_CONTINUE_RECONSIDER_LIMIT
 OR N.CONTINUE_RECONSIDER_MODE<>T.CONTINUE_RECONSIDER_MODE
 OR N.FINANCE_LIMIT_TOTAL<>T.FINANCE_LIMIT_TOTAL
 OR N.BALANCE_LIMIT_TOTAL<>T.BALANCE_LIMIT_TOTAL
 OR N.RISK_LIMIT_TOTAL<>T.RISK_LIMIT_TOTAL
 OR N.COMMONLY_RISK_LIMIT_TOTAL<>T.COMMONLY_RISK_LIMIT_TOTAL
 OR N.GUARANTEE_TOTAL_LIMIT_REPLY<>T.GUARANTEE_TOTAL_LIMIT_REPLY
 OR N.OLD_CUR_LIMIT_RISK_LIMIT<>T.OLD_CUR_LIMIT_RISK_LIMIT
 OR N.GUARANTEE_TOTAL_LIMIT_APPL<>T.GUARANTEE_TOTAL_LIMIT_APPL
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_CRD_CREDIT_LIMIT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_117
WHERE P.End_Dt=DATE('2100-12-31')
AND P.LIMIT_ID=T_117.LIMIT_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_CRD_CREDIT_LIMIT SELECT * FROM T_117;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
