#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_354 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL WHERE 1=0;

--Step2:
INSERT  INTO T_354 (
  TERM_CHANGE_ID,
  TERM_CHANGE_DETAIL_ID,
  TERM_CHANGE_NUM,
  CONTRACT_NUM,
  BORROW_NUM,
  CUSTOMER_NUM,
  TERM_CHANGE_FLAG,
  OLD_CONTRACT_TERM,
  OLD_START_DATE,
  OLD_END_DATE,
  OLD_REPAY_PLAY,
  OLD_GUARANTY_TYPE,
  OLD_IR_GIST_STYLE_CD,
  OLD_IR_FLOAT_KIND_APPROVE,
  OLD_IR_GRADE_CD_APPROVE,
  OLD_IR_NEGO_RATE_APPROVE,
  OLD_IR_ADJUST_MODE,
  OLD_DAY_RATE,
  OLD_RATE_CHANGE_DATE_CHANGE,
  OLD_LATE_FLOAT_RATE,
  OLD_PECUL_FLOAT_RATE,
  CONTRACT_TERM,
  START_DATE,
  END_DATE,
  REPAY_PLAY,
  GUARANTY_TYPE,
  IR_GIST_STYLE_CD,
  IR_FLOAT_KIND_APPROVE,
  IR_GRADE_CD_APPROVE,
  IR_NEGO_RATE_APPROVE,
  IR_ADJUST_MODE,
  DAY_RATE,
  RATE_CHANGE_DATE_CHANGE,
  LATE_FLOAT_RATE,
  PECUL_FLOAT_RATE,
  TERM_CHANGE_REASON,
  VOUCHER_SUGGEST,
  APPLY_SUGGEST,
  DEAL_STATUS,
  DEAL_DATE,
  FXBS_TIME_MARK,
  TE_CHANGE_FLAG,
  TE_CHANGE_TYPE,
  OLD_RATE_CHANGE_MONTH,
  OLD_CHANGE_DATE_TYPE,
  RATE_CHANGE_MONTH,
  CHANGE_DATE_TYPE,
  OLD_RATE_APPLY_TYPE,
  RATE_APPLY_TYPE,
  OLD_IR_RATE_YEAR,
  IR_RATE_YEAR,
  start_dt,
  end_dt)
SELECT
  N.TERM_CHANGE_ID,
  N.TERM_CHANGE_DETAIL_ID,
  N.TERM_CHANGE_NUM,
  N.CONTRACT_NUM,
  N.BORROW_NUM,
  N.CUSTOMER_NUM,
  N.TERM_CHANGE_FLAG,
  N.OLD_CONTRACT_TERM,
  N.OLD_START_DATE,
  N.OLD_END_DATE,
  N.OLD_REPAY_PLAY,
  N.OLD_GUARANTY_TYPE,
  N.OLD_IR_GIST_STYLE_CD,
  N.OLD_IR_FLOAT_KIND_APPROVE,
  N.OLD_IR_GRADE_CD_APPROVE,
  N.OLD_IR_NEGO_RATE_APPROVE,
  N.OLD_IR_ADJUST_MODE,
  N.OLD_DAY_RATE,
  N.OLD_RATE_CHANGE_DATE_CHANGE,
  N.OLD_LATE_FLOAT_RATE,
  N.OLD_PECUL_FLOAT_RATE,
  N.CONTRACT_TERM,
  N.START_DATE,
  N.END_DATE,
  N.REPAY_PLAY,
  N.GUARANTY_TYPE,
  N.IR_GIST_STYLE_CD,
  N.IR_FLOAT_KIND_APPROVE,
  N.IR_GRADE_CD_APPROVE,
  N.IR_NEGO_RATE_APPROVE,
  N.IR_ADJUST_MODE,
  N.DAY_RATE,
  N.RATE_CHANGE_DATE_CHANGE,
  N.LATE_FLOAT_RATE,
  N.PECUL_FLOAT_RATE,
  N.TERM_CHANGE_REASON,
  N.VOUCHER_SUGGEST,
  N.APPLY_SUGGEST,
  N.DEAL_STATUS,
  N.DEAL_DATE,
  N.FXBS_TIME_MARK,
  N.TE_CHANGE_FLAG,
  N.TE_CHANGE_TYPE,
  N.OLD_RATE_CHANGE_MONTH,
  N.OLD_CHANGE_DATE_TYPE,
  N.RATE_CHANGE_MONTH,
  N.CHANGE_DATE_TYPE,
  N.OLD_RATE_APPLY_TYPE,
  N.RATE_APPLY_TYPE,
  N.OLD_IR_RATE_YEAR,
  N.IR_RATE_YEAR,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(TERM_CHANGE_ID, '' ) AS TERM_CHANGE_ID ,
  COALESCE(TERM_CHANGE_DETAIL_ID, '' ) AS TERM_CHANGE_DETAIL_ID ,
  COALESCE(TERM_CHANGE_NUM, '' ) AS TERM_CHANGE_NUM ,
  COALESCE(CONTRACT_NUM, '' ) AS CONTRACT_NUM ,
  COALESCE(BORROW_NUM, '' ) AS BORROW_NUM ,
  COALESCE(CUSTOMER_NUM, '' ) AS CUSTOMER_NUM ,
  COALESCE(TERM_CHANGE_FLAG, '' ) AS TERM_CHANGE_FLAG ,
  COALESCE(OLD_CONTRACT_TERM, 0 ) AS OLD_CONTRACT_TERM ,
  COALESCE(OLD_START_DATE,'4999-12-31 00:00:00' ) AS OLD_START_DATE ,
  COALESCE(OLD_END_DATE,'4999-12-31 00:00:00' ) AS OLD_END_DATE ,
  COALESCE(OLD_REPAY_PLAY, '' ) AS OLD_REPAY_PLAY ,
  COALESCE(OLD_GUARANTY_TYPE, '' ) AS OLD_GUARANTY_TYPE ,
  COALESCE(OLD_IR_GIST_STYLE_CD, '' ) AS OLD_IR_GIST_STYLE_CD ,
  COALESCE(OLD_IR_FLOAT_KIND_APPROVE, '' ) AS OLD_IR_FLOAT_KIND_APPROVE ,
  COALESCE(OLD_IR_GRADE_CD_APPROVE, '' ) AS OLD_IR_GRADE_CD_APPROVE ,
  COALESCE(OLD_IR_NEGO_RATE_APPROVE, 0 ) AS OLD_IR_NEGO_RATE_APPROVE ,
  COALESCE(OLD_IR_ADJUST_MODE, '' ) AS OLD_IR_ADJUST_MODE ,
  COALESCE(OLD_DAY_RATE, '' ) AS OLD_DAY_RATE ,
  COALESCE(OLD_RATE_CHANGE_DATE_CHANGE, '' ) AS OLD_RATE_CHANGE_DATE_CHANGE ,
  COALESCE(OLD_LATE_FLOAT_RATE, 0 ) AS OLD_LATE_FLOAT_RATE ,
  COALESCE(OLD_PECUL_FLOAT_RATE, 0 ) AS OLD_PECUL_FLOAT_RATE ,
  COALESCE(CONTRACT_TERM, 0 ) AS CONTRACT_TERM ,
  COALESCE(START_DATE,'4999-12-31 00:00:00' ) AS START_DATE ,
  COALESCE(END_DATE,'4999-12-31 00:00:00' ) AS END_DATE ,
  COALESCE(REPAY_PLAY, '' ) AS REPAY_PLAY ,
  COALESCE(GUARANTY_TYPE, '' ) AS GUARANTY_TYPE ,
  COALESCE(IR_GIST_STYLE_CD, '' ) AS IR_GIST_STYLE_CD ,
  COALESCE(IR_FLOAT_KIND_APPROVE, '' ) AS IR_FLOAT_KIND_APPROVE ,
  COALESCE(IR_GRADE_CD_APPROVE, '' ) AS IR_GRADE_CD_APPROVE ,
  COALESCE(IR_NEGO_RATE_APPROVE, 0 ) AS IR_NEGO_RATE_APPROVE ,
  COALESCE(IR_ADJUST_MODE, '' ) AS IR_ADJUST_MODE ,
  COALESCE(DAY_RATE, '' ) AS DAY_RATE ,
  COALESCE(RATE_CHANGE_DATE_CHANGE, '' ) AS RATE_CHANGE_DATE_CHANGE ,
  COALESCE(LATE_FLOAT_RATE, 0 ) AS LATE_FLOAT_RATE ,
  COALESCE(PECUL_FLOAT_RATE, 0 ) AS PECUL_FLOAT_RATE ,
  COALESCE(TERM_CHANGE_REASON, '' ) AS TERM_CHANGE_REASON ,
  COALESCE(VOUCHER_SUGGEST, '' ) AS VOUCHER_SUGGEST ,
  COALESCE(APPLY_SUGGEST, '' ) AS APPLY_SUGGEST ,
  COALESCE(DEAL_STATUS, '' ) AS DEAL_STATUS ,
  COALESCE(DEAL_DATE,'4999-12-31 00:00:00' ) AS DEAL_DATE ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(TE_CHANGE_FLAG, '' ) AS TE_CHANGE_FLAG ,
  COALESCE(TE_CHANGE_TYPE, '' ) AS TE_CHANGE_TYPE ,
  COALESCE(OLD_RATE_CHANGE_MONTH, '' ) AS OLD_RATE_CHANGE_MONTH ,
  COALESCE(OLD_CHANGE_DATE_TYPE, '' ) AS OLD_CHANGE_DATE_TYPE ,
  COALESCE(RATE_CHANGE_MONTH, '' ) AS RATE_CHANGE_MONTH ,
  COALESCE(CHANGE_DATE_TYPE, '' ) AS CHANGE_DATE_TYPE ,
  COALESCE(OLD_RATE_APPLY_TYPE, '' ) AS OLD_RATE_APPLY_TYPE ,
  COALESCE(RATE_APPLY_TYPE, '' ) AS RATE_APPLY_TYPE ,
  COALESCE(OLD_IR_RATE_YEAR, 0 ) AS OLD_IR_RATE_YEAR ,
  COALESCE(IR_RATE_YEAR, 0 ) AS IR_RATE_YEAR 
 FROM  dw_tdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  TERM_CHANGE_ID ,
  TERM_CHANGE_DETAIL_ID ,
  TERM_CHANGE_NUM ,
  CONTRACT_NUM ,
  BORROW_NUM ,
  CUSTOMER_NUM ,
  TERM_CHANGE_FLAG ,
  OLD_CONTRACT_TERM ,
  OLD_START_DATE ,
  OLD_END_DATE ,
  OLD_REPAY_PLAY ,
  OLD_GUARANTY_TYPE ,
  OLD_IR_GIST_STYLE_CD ,
  OLD_IR_FLOAT_KIND_APPROVE ,
  OLD_IR_GRADE_CD_APPROVE ,
  OLD_IR_NEGO_RATE_APPROVE ,
  OLD_IR_ADJUST_MODE ,
  OLD_DAY_RATE ,
  OLD_RATE_CHANGE_DATE_CHANGE ,
  OLD_LATE_FLOAT_RATE ,
  OLD_PECUL_FLOAT_RATE ,
  CONTRACT_TERM ,
  START_DATE ,
  END_DATE ,
  REPAY_PLAY ,
  GUARANTY_TYPE ,
  IR_GIST_STYLE_CD ,
  IR_FLOAT_KIND_APPROVE ,
  IR_GRADE_CD_APPROVE ,
  IR_NEGO_RATE_APPROVE ,
  IR_ADJUST_MODE ,
  DAY_RATE ,
  RATE_CHANGE_DATE_CHANGE ,
  LATE_FLOAT_RATE ,
  PECUL_FLOAT_RATE ,
  TERM_CHANGE_REASON ,
  VOUCHER_SUGGEST ,
  APPLY_SUGGEST ,
  DEAL_STATUS ,
  DEAL_DATE ,
  FXBS_TIME_MARK ,
  TE_CHANGE_FLAG ,
  TE_CHANGE_TYPE ,
  OLD_RATE_CHANGE_MONTH ,
  OLD_CHANGE_DATE_TYPE ,
  RATE_CHANGE_MONTH ,
  CHANGE_DATE_TYPE ,
  OLD_RATE_APPLY_TYPE ,
  RATE_APPLY_TYPE ,
  OLD_IR_RATE_YEAR ,
  IR_RATE_YEAR 
 FROM dw_sdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.TERM_CHANGE_DETAIL_ID = T.TERM_CHANGE_DETAIL_ID
WHERE
(T.TERM_CHANGE_DETAIL_ID IS NULL)
 OR N.TERM_CHANGE_ID<>T.TERM_CHANGE_ID
 OR N.TERM_CHANGE_NUM<>T.TERM_CHANGE_NUM
 OR N.CONTRACT_NUM<>T.CONTRACT_NUM
 OR N.BORROW_NUM<>T.BORROW_NUM
 OR N.CUSTOMER_NUM<>T.CUSTOMER_NUM
 OR N.TERM_CHANGE_FLAG<>T.TERM_CHANGE_FLAG
 OR N.OLD_CONTRACT_TERM<>T.OLD_CONTRACT_TERM
 OR N.OLD_START_DATE<>T.OLD_START_DATE
 OR N.OLD_END_DATE<>T.OLD_END_DATE
 OR N.OLD_REPAY_PLAY<>T.OLD_REPAY_PLAY
 OR N.OLD_GUARANTY_TYPE<>T.OLD_GUARANTY_TYPE
 OR N.OLD_IR_GIST_STYLE_CD<>T.OLD_IR_GIST_STYLE_CD
 OR N.OLD_IR_FLOAT_KIND_APPROVE<>T.OLD_IR_FLOAT_KIND_APPROVE
 OR N.OLD_IR_GRADE_CD_APPROVE<>T.OLD_IR_GRADE_CD_APPROVE
 OR N.OLD_IR_NEGO_RATE_APPROVE<>T.OLD_IR_NEGO_RATE_APPROVE
 OR N.OLD_IR_ADJUST_MODE<>T.OLD_IR_ADJUST_MODE
 OR N.OLD_DAY_RATE<>T.OLD_DAY_RATE
 OR N.OLD_RATE_CHANGE_DATE_CHANGE<>T.OLD_RATE_CHANGE_DATE_CHANGE
 OR N.OLD_LATE_FLOAT_RATE<>T.OLD_LATE_FLOAT_RATE
 OR N.OLD_PECUL_FLOAT_RATE<>T.OLD_PECUL_FLOAT_RATE
 OR N.CONTRACT_TERM<>T.CONTRACT_TERM
 OR N.START_DATE<>T.START_DATE
 OR N.END_DATE<>T.END_DATE
 OR N.REPAY_PLAY<>T.REPAY_PLAY
 OR N.GUARANTY_TYPE<>T.GUARANTY_TYPE
 OR N.IR_GIST_STYLE_CD<>T.IR_GIST_STYLE_CD
 OR N.IR_FLOAT_KIND_APPROVE<>T.IR_FLOAT_KIND_APPROVE
 OR N.IR_GRADE_CD_APPROVE<>T.IR_GRADE_CD_APPROVE
 OR N.IR_NEGO_RATE_APPROVE<>T.IR_NEGO_RATE_APPROVE
 OR N.IR_ADJUST_MODE<>T.IR_ADJUST_MODE
 OR N.DAY_RATE<>T.DAY_RATE
 OR N.RATE_CHANGE_DATE_CHANGE<>T.RATE_CHANGE_DATE_CHANGE
 OR N.LATE_FLOAT_RATE<>T.LATE_FLOAT_RATE
 OR N.PECUL_FLOAT_RATE<>T.PECUL_FLOAT_RATE
 OR N.TERM_CHANGE_REASON<>T.TERM_CHANGE_REASON
 OR N.VOUCHER_SUGGEST<>T.VOUCHER_SUGGEST
 OR N.APPLY_SUGGEST<>T.APPLY_SUGGEST
 OR N.DEAL_STATUS<>T.DEAL_STATUS
 OR N.DEAL_DATE<>T.DEAL_DATE
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.TE_CHANGE_FLAG<>T.TE_CHANGE_FLAG
 OR N.TE_CHANGE_TYPE<>T.TE_CHANGE_TYPE
 OR N.OLD_RATE_CHANGE_MONTH<>T.OLD_RATE_CHANGE_MONTH
 OR N.OLD_CHANGE_DATE_TYPE<>T.OLD_CHANGE_DATE_TYPE
 OR N.RATE_CHANGE_MONTH<>T.RATE_CHANGE_MONTH
 OR N.CHANGE_DATE_TYPE<>T.CHANGE_DATE_TYPE
 OR N.OLD_RATE_APPLY_TYPE<>T.OLD_RATE_APPLY_TYPE
 OR N.RATE_APPLY_TYPE<>T.RATE_APPLY_TYPE
 OR N.OLD_IR_RATE_YEAR<>T.OLD_IR_RATE_YEAR
 OR N.IR_RATE_YEAR<>T.IR_RATE_YEAR
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_354
WHERE P.End_Dt=DATE('2100-12-31')
AND P.TERM_CHANGE_DETAIL_ID=T_354.TERM_CHANGE_DETAIL_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_AFT_TERM_CHANGE_DETAIL SELECT * FROM T_354;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
