#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_CON_BIZ_DETAIL WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_CON_BIZ_DETAIL SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_108 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_CON_BIZ_DETAIL WHERE 1=0;

--Step2:
INSERT  INTO T_108 (
  CONTRACT_BIZ_DETAIL_ID,
  BIZ_DETAIL_TYPE_CD,
  BIZ_DETAIL_ID,
  CONTRACT_NUM,
  BIZ_NUM,
  CREDIT_PRODUCT_CD,
  CURRENCY_CD,
  CONTRACT_CREDIT_AMT,
  CONTRACT_TERM,
  START_DATE,
  EXPIRATION_DATE,
  EXCHANGE_RATE,
  OUTSTANDING_AMT,
  COMMISSION_BAL,
  REVERT_TERM_M_SUM,
  USE_AMT_CD,
  REVERT_CD,
  CONTRACT_CYCLE_IND,
  LOWEST_PAY_AMT,
  AMT_TYPE_CD,
  ZS_RMB_AMT,
  APPLY_USE_AMT,
  WIDTH_TERM,
  COMPR_BIZ_CONTRACT_IND,
  BAL_ACCT,
  BAL_ACCT_NAME,
  BAL_ACCT_BANK_NAME,
  BAL_ACCT_NO,
  ECONOMY_HOUSE_CYCLE_IND,
  RATE_YEAR,
  EXPENSE_RATE,
  OLD_CONTRACT_BIZ_DETAIL_ID,
  LOW_RISK_IND,
  CONTRACT_ID,
  CONTRACT_TERM_UNIT_CD,
  TIME_MARK,
  PAY_CD,
  IS_TRUST_PAY,
  PAY_NAME,
  PAY_NO,
  REVERT_SPACE_MONTH,
  ACCRUAL_MONTH,
  ONLY_ACCRUAL_MONTH,
  REVERT_LIMIT,
  REVERT_NAME,
  REVERT_NO,
  LOW_REVERT_LIMT,
  LOW_REVERT_UNIT,
  IS_REVERT,
  REVERT_FAITH,
  DRAW_STYLE,
  REVERT_APP_DATE_DES,
  DELAY_REVERT_APP_DES,
  EXTEND_APP_DATE_DES,
  ACCRUAL_DAYS,
  COLLECT_SUM,
  SPECIFIC_DATE,
  PAY_SUM,
  DISCOUNT_CD,
  DISCOUNT_COUNT,
  DISCOUNT_SUM,
  DISCOUNT_WAY,
  BUY_BACK_FREEZE_DATE,
  BUY_BACK_END_DATE,
  IS_BUY_BACK_RATE,
  BUY_BACK_RATE,
  CUSTOMER_NAME,
  KEEP_BUSINESS_SORT,
  KEEP_AREA,
  IF_ADJUST_DATE,
  ADJUST_DATE,
  PAYOUT_ACCOUNT_NO,
  PAYOUT_ACCOUNT_BANK,
  REPAY_ACCOUNT_NO,
  REPAY_ACCOUNT_BANK,
  REPAY_PLAN_CREATE_CD,
  SHORT_PAY_NO,
  SUPER_PRODUCT_CD,
  PRODUCT_LEVEL,
  BANDING_STATUS_CD,
  FLOW_NO,
  DEDUCT_AGREMENT_NUM,
  SUPERVISION_CORP_CD,
  SUPERVISION_CORP_NAME,
  ENTRUST_PAY_FIRST_AMT,
  IF_FIRST_LOAN_DATE,
  FIRST_DRAWINGS_DATE,
  IF_BANK_ACCOUNT_NUMBER,
  IF_EXPENSE_PAY,
  CON_PAY_ACCOUNT_TYPE,
  RISK_CLASS_RESULT,
  IF_RELY_DATE,
  FXBS_TIME_MARK,
  REPAY_ACCOUNT_OPEN_ORG_CODE,
  REPAY_ACCOUNT_OPEN_ORG_NAME,
  CORE_ENTERPRISE_NAME,
  CORE_ENTERPRISE_NUM,
  ENTERPRISE_IND,
  ENTERPRISE_RELATION,
  SUPERVISE_ENTERPRISE_RESPONSE,
  DUTY_CD,
  IF_SUPERVISE_ENTERPRISE,
  ORDER_FINANCE_TYPE,
  DIRECT_TO_INTERNAL_FLAG,
  PAY_ACCOUNT_OPEN_ORG_CODE,
  FINANCING_PERCENT,
  BUSINESS_TYPE,
  FEES_COLLECTION_POINT,
  CONTRACT_ITEMIZE_MONEY,
  IS_SPECIAL_CREDIT,
  GUARANTY_TYPE,
  CREDIT_TERM,
  ORI_CONTRACT_BIZ_DETAIL_ID,
  REVERT_AMT_LIMIT,
  CRD_LIMIT_PRODUCT_CD,
  USED_CURRENCY_NAME,
  ADD_GUARANTY_NEGO_RATE,
  CUSTOMER_PAY_NAME,
  CUSTOMER_PAY_NO,
  ACCOUNT_OPENING_BANK,
  start_dt,
  end_dt)
SELECT
  N.CONTRACT_BIZ_DETAIL_ID,
  N.BIZ_DETAIL_TYPE_CD,
  N.BIZ_DETAIL_ID,
  N.CONTRACT_NUM,
  N.BIZ_NUM,
  N.CREDIT_PRODUCT_CD,
  N.CURRENCY_CD,
  N.CONTRACT_CREDIT_AMT,
  N.CONTRACT_TERM,
  N.START_DATE,
  N.EXPIRATION_DATE,
  N.EXCHANGE_RATE,
  N.OUTSTANDING_AMT,
  N.COMMISSION_BAL,
  N.REVERT_TERM_M_SUM,
  N.USE_AMT_CD,
  N.REVERT_CD,
  N.CONTRACT_CYCLE_IND,
  N.LOWEST_PAY_AMT,
  N.AMT_TYPE_CD,
  N.ZS_RMB_AMT,
  N.APPLY_USE_AMT,
  N.WIDTH_TERM,
  N.COMPR_BIZ_CONTRACT_IND,
  N.BAL_ACCT,
  N.BAL_ACCT_NAME,
  N.BAL_ACCT_BANK_NAME,
  N.BAL_ACCT_NO,
  N.ECONOMY_HOUSE_CYCLE_IND,
  N.RATE_YEAR,
  N.EXPENSE_RATE,
  N.OLD_CONTRACT_BIZ_DETAIL_ID,
  N.LOW_RISK_IND,
  N.CONTRACT_ID,
  N.CONTRACT_TERM_UNIT_CD,
  N.TIME_MARK,
  N.PAY_CD,
  N.IS_TRUST_PAY,
  N.PAY_NAME,
  N.PAY_NO,
  N.REVERT_SPACE_MONTH,
  N.ACCRUAL_MONTH,
  N.ONLY_ACCRUAL_MONTH,
  N.REVERT_LIMIT,
  N.REVERT_NAME,
  N.REVERT_NO,
  N.LOW_REVERT_LIMT,
  N.LOW_REVERT_UNIT,
  N.IS_REVERT,
  N.REVERT_FAITH,
  N.DRAW_STYLE,
  N.REVERT_APP_DATE_DES,
  N.DELAY_REVERT_APP_DES,
  N.EXTEND_APP_DATE_DES,
  N.ACCRUAL_DAYS,
  N.COLLECT_SUM,
  N.SPECIFIC_DATE,
  N.PAY_SUM,
  N.DISCOUNT_CD,
  N.DISCOUNT_COUNT,
  N.DISCOUNT_SUM,
  N.DISCOUNT_WAY,
  N.BUY_BACK_FREEZE_DATE,
  N.BUY_BACK_END_DATE,
  N.IS_BUY_BACK_RATE,
  N.BUY_BACK_RATE,
  N.CUSTOMER_NAME,
  N.KEEP_BUSINESS_SORT,
  N.KEEP_AREA,
  N.IF_ADJUST_DATE,
  N.ADJUST_DATE,
  N.PAYOUT_ACCOUNT_NO,
  N.PAYOUT_ACCOUNT_BANK,
  N.REPAY_ACCOUNT_NO,
  N.REPAY_ACCOUNT_BANK,
  N.REPAY_PLAN_CREATE_CD,
  N.SHORT_PAY_NO,
  N.SUPER_PRODUCT_CD,
  N.PRODUCT_LEVEL,
  N.BANDING_STATUS_CD,
  N.FLOW_NO,
  N.DEDUCT_AGREMENT_NUM,
  N.SUPERVISION_CORP_CD,
  N.SUPERVISION_CORP_NAME,
  N.ENTRUST_PAY_FIRST_AMT,
  N.IF_FIRST_LOAN_DATE,
  N.FIRST_DRAWINGS_DATE,
  N.IF_BANK_ACCOUNT_NUMBER,
  N.IF_EXPENSE_PAY,
  N.CON_PAY_ACCOUNT_TYPE,
  N.RISK_CLASS_RESULT,
  N.IF_RELY_DATE,
  N.FXBS_TIME_MARK,
  N.REPAY_ACCOUNT_OPEN_ORG_CODE,
  N.REPAY_ACCOUNT_OPEN_ORG_NAME,
  N.CORE_ENTERPRISE_NAME,
  N.CORE_ENTERPRISE_NUM,
  N.ENTERPRISE_IND,
  N.ENTERPRISE_RELATION,
  N.SUPERVISE_ENTERPRISE_RESPONSE,
  N.DUTY_CD,
  N.IF_SUPERVISE_ENTERPRISE,
  N.ORDER_FINANCE_TYPE,
  N.DIRECT_TO_INTERNAL_FLAG,
  N.PAY_ACCOUNT_OPEN_ORG_CODE,
  N.FINANCING_PERCENT,
  N.BUSINESS_TYPE,
  N.FEES_COLLECTION_POINT,
  N.CONTRACT_ITEMIZE_MONEY,
  N.IS_SPECIAL_CREDIT,
  N.GUARANTY_TYPE,
  N.CREDIT_TERM,
  N.ORI_CONTRACT_BIZ_DETAIL_ID,
  N.REVERT_AMT_LIMIT,
  N.CRD_LIMIT_PRODUCT_CD,
  N.USED_CURRENCY_NAME,
  N.ADD_GUARANTY_NEGO_RATE,
  N.CUSTOMER_PAY_NAME,
  N.CUSTOMER_PAY_NO,
  N.ACCOUNT_OPENING_BANK,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(CONTRACT_BIZ_DETAIL_ID, '' ) AS CONTRACT_BIZ_DETAIL_ID ,
  COALESCE(BIZ_DETAIL_TYPE_CD, '' ) AS BIZ_DETAIL_TYPE_CD ,
  COALESCE(BIZ_DETAIL_ID, '' ) AS BIZ_DETAIL_ID ,
  COALESCE(CONTRACT_NUM, '' ) AS CONTRACT_NUM ,
  COALESCE(BIZ_NUM, '' ) AS BIZ_NUM ,
  COALESCE(CREDIT_PRODUCT_CD, '' ) AS CREDIT_PRODUCT_CD ,
  COALESCE(CURRENCY_CD, '' ) AS CURRENCY_CD ,
  COALESCE(CONTRACT_CREDIT_AMT, 0 ) AS CONTRACT_CREDIT_AMT ,
  COALESCE(CONTRACT_TERM, 0 ) AS CONTRACT_TERM ,
  COALESCE(START_DATE,'4999-12-31 00:00:00' ) AS START_DATE ,
  COALESCE(EXPIRATION_DATE,'4999-12-31 00:00:00' ) AS EXPIRATION_DATE ,
  COALESCE(EXCHANGE_RATE, 0 ) AS EXCHANGE_RATE ,
  COALESCE(OUTSTANDING_AMT, 0 ) AS OUTSTANDING_AMT ,
  COALESCE(COMMISSION_BAL, 0 ) AS COMMISSION_BAL ,
  COALESCE(REVERT_TERM_M_SUM, 0 ) AS REVERT_TERM_M_SUM ,
  COALESCE(USE_AMT_CD, '' ) AS USE_AMT_CD ,
  COALESCE(REVERT_CD, '' ) AS REVERT_CD ,
  COALESCE(CONTRACT_CYCLE_IND, '' ) AS CONTRACT_CYCLE_IND ,
  COALESCE(LOWEST_PAY_AMT, 0 ) AS LOWEST_PAY_AMT ,
  COALESCE(AMT_TYPE_CD, '' ) AS AMT_TYPE_CD ,
  COALESCE(ZS_RMB_AMT, 0 ) AS ZS_RMB_AMT ,
  COALESCE(APPLY_USE_AMT, 0 ) AS APPLY_USE_AMT ,
  COALESCE(WIDTH_TERM, 0 ) AS WIDTH_TERM ,
  COALESCE(COMPR_BIZ_CONTRACT_IND, '' ) AS COMPR_BIZ_CONTRACT_IND ,
  COALESCE(BAL_ACCT, '' ) AS BAL_ACCT ,
  COALESCE(BAL_ACCT_NAME, '' ) AS BAL_ACCT_NAME ,
  COALESCE(BAL_ACCT_BANK_NAME, '' ) AS BAL_ACCT_BANK_NAME ,
  COALESCE(BAL_ACCT_NO, '' ) AS BAL_ACCT_NO ,
  COALESCE(ECONOMY_HOUSE_CYCLE_IND, '' ) AS ECONOMY_HOUSE_CYCLE_IND ,
  COALESCE(RATE_YEAR, 0 ) AS RATE_YEAR ,
  COALESCE(EXPENSE_RATE, 0 ) AS EXPENSE_RATE ,
  COALESCE(OLD_CONTRACT_BIZ_DETAIL_ID, '' ) AS OLD_CONTRACT_BIZ_DETAIL_ID ,
  COALESCE(LOW_RISK_IND, '' ) AS LOW_RISK_IND ,
  COALESCE(CONTRACT_ID, '' ) AS CONTRACT_ID ,
  COALESCE(CONTRACT_TERM_UNIT_CD, '' ) AS CONTRACT_TERM_UNIT_CD ,
  COALESCE(TIME_MARK,'4999-12-31 00:00:00' ) AS TIME_MARK ,
  COALESCE(PAY_CD, '' ) AS PAY_CD ,
  COALESCE(IS_TRUST_PAY, '' ) AS IS_TRUST_PAY ,
  COALESCE(PAY_NAME, '' ) AS PAY_NAME ,
  COALESCE(PAY_NO, '' ) AS PAY_NO ,
  COALESCE(REVERT_SPACE_MONTH, '' ) AS REVERT_SPACE_MONTH ,
  COALESCE(ACCRUAL_MONTH, '' ) AS ACCRUAL_MONTH ,
  COALESCE(ONLY_ACCRUAL_MONTH, 0 ) AS ONLY_ACCRUAL_MONTH ,
  COALESCE(REVERT_LIMIT, 0 ) AS REVERT_LIMIT ,
  COALESCE(REVERT_NAME, '' ) AS REVERT_NAME ,
  COALESCE(REVERT_NO, '' ) AS REVERT_NO ,
  COALESCE(LOW_REVERT_LIMT, 0 ) AS LOW_REVERT_LIMT ,
  COALESCE(LOW_REVERT_UNIT, 0 ) AS LOW_REVERT_UNIT ,
  COALESCE(IS_REVERT, '' ) AS IS_REVERT ,
  COALESCE(REVERT_FAITH, 0 ) AS REVERT_FAITH ,
  COALESCE(DRAW_STYLE, '' ) AS DRAW_STYLE ,
  COALESCE(REVERT_APP_DATE_DES, '' ) AS REVERT_APP_DATE_DES ,
  COALESCE(DELAY_REVERT_APP_DES, '' ) AS DELAY_REVERT_APP_DES ,
  COALESCE(EXTEND_APP_DATE_DES, '' ) AS EXTEND_APP_DATE_DES ,
  COALESCE(ACCRUAL_DAYS, 0 ) AS ACCRUAL_DAYS ,
  COALESCE(COLLECT_SUM, 0 ) AS COLLECT_SUM ,
  COALESCE(SPECIFIC_DATE,'4999-12-31 00:00:00' ) AS SPECIFIC_DATE ,
  COALESCE(PAY_SUM, 0 ) AS PAY_SUM ,
  COALESCE(DISCOUNT_CD, '' ) AS DISCOUNT_CD ,
  COALESCE(DISCOUNT_COUNT, 0 ) AS DISCOUNT_COUNT ,
  COALESCE(DISCOUNT_SUM, 0 ) AS DISCOUNT_SUM ,
  COALESCE(DISCOUNT_WAY, '' ) AS DISCOUNT_WAY ,
  COALESCE(BUY_BACK_FREEZE_DATE,'4999-12-31 00:00:00' ) AS BUY_BACK_FREEZE_DATE ,
  COALESCE(BUY_BACK_END_DATE,'4999-12-31 00:00:00' ) AS BUY_BACK_END_DATE ,
  COALESCE(IS_BUY_BACK_RATE, '' ) AS IS_BUY_BACK_RATE ,
  COALESCE(BUY_BACK_RATE, 0 ) AS BUY_BACK_RATE ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(KEEP_BUSINESS_SORT, '' ) AS KEEP_BUSINESS_SORT ,
  COALESCE(KEEP_AREA, '' ) AS KEEP_AREA ,
  COALESCE(IF_ADJUST_DATE, '' ) AS IF_ADJUST_DATE ,
  COALESCE(ADJUST_DATE, '' ) AS ADJUST_DATE ,
  COALESCE(PAYOUT_ACCOUNT_NO, '' ) AS PAYOUT_ACCOUNT_NO ,
  COALESCE(PAYOUT_ACCOUNT_BANK, '' ) AS PAYOUT_ACCOUNT_BANK ,
  COALESCE(REPAY_ACCOUNT_NO, '' ) AS REPAY_ACCOUNT_NO ,
  COALESCE(REPAY_ACCOUNT_BANK, '' ) AS REPAY_ACCOUNT_BANK ,
  COALESCE(REPAY_PLAN_CREATE_CD, '' ) AS REPAY_PLAN_CREATE_CD ,
  COALESCE(SHORT_PAY_NO, '' ) AS SHORT_PAY_NO ,
  COALESCE(SUPER_PRODUCT_CD, '' ) AS SUPER_PRODUCT_CD ,
  COALESCE(PRODUCT_LEVEL, '' ) AS PRODUCT_LEVEL ,
  COALESCE(BANDING_STATUS_CD, '' ) AS BANDING_STATUS_CD ,
  COALESCE(FLOW_NO, '' ) AS FLOW_NO ,
  COALESCE(DEDUCT_AGREMENT_NUM, '' ) AS DEDUCT_AGREMENT_NUM ,
  COALESCE(SUPERVISION_CORP_CD, '' ) AS SUPERVISION_CORP_CD ,
  COALESCE(SUPERVISION_CORP_NAME, '' ) AS SUPERVISION_CORP_NAME ,
  COALESCE(ENTRUST_PAY_FIRST_AMT, 0 ) AS ENTRUST_PAY_FIRST_AMT ,
  COALESCE(IF_FIRST_LOAN_DATE, '' ) AS IF_FIRST_LOAN_DATE ,
  COALESCE(FIRST_DRAWINGS_DATE,'4999-12-31 00:00:00' ) AS FIRST_DRAWINGS_DATE ,
  COALESCE(IF_BANK_ACCOUNT_NUMBER, '' ) AS IF_BANK_ACCOUNT_NUMBER ,
  COALESCE(IF_EXPENSE_PAY, '' ) AS IF_EXPENSE_PAY ,
  COALESCE(CON_PAY_ACCOUNT_TYPE, '' ) AS CON_PAY_ACCOUNT_TYPE ,
  COALESCE(RISK_CLASS_RESULT, '' ) AS RISK_CLASS_RESULT ,
  COALESCE(IF_RELY_DATE, '' ) AS IF_RELY_DATE ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(REPAY_ACCOUNT_OPEN_ORG_CODE, '' ) AS REPAY_ACCOUNT_OPEN_ORG_CODE ,
  COALESCE(REPAY_ACCOUNT_OPEN_ORG_NAME, '' ) AS REPAY_ACCOUNT_OPEN_ORG_NAME ,
  COALESCE(CORE_ENTERPRISE_NAME, '' ) AS CORE_ENTERPRISE_NAME ,
  COALESCE(CORE_ENTERPRISE_NUM, '' ) AS CORE_ENTERPRISE_NUM ,
  COALESCE(ENTERPRISE_IND, '' ) AS ENTERPRISE_IND ,
  COALESCE(ENTERPRISE_RELATION, '' ) AS ENTERPRISE_RELATION ,
  COALESCE(SUPERVISE_ENTERPRISE_RESPONSE, '' ) AS SUPERVISE_ENTERPRISE_RESPONSE ,
  COALESCE(DUTY_CD, '' ) AS DUTY_CD ,
  COALESCE(IF_SUPERVISE_ENTERPRISE, '' ) AS IF_SUPERVISE_ENTERPRISE ,
  COALESCE(ORDER_FINANCE_TYPE, '' ) AS ORDER_FINANCE_TYPE ,
  COALESCE(DIRECT_TO_INTERNAL_FLAG, '' ) AS DIRECT_TO_INTERNAL_FLAG ,
  COALESCE(PAY_ACCOUNT_OPEN_ORG_CODE, '' ) AS PAY_ACCOUNT_OPEN_ORG_CODE ,
  COALESCE(FINANCING_PERCENT, 0 ) AS FINANCING_PERCENT ,
  COALESCE(BUSINESS_TYPE, '' ) AS BUSINESS_TYPE ,
  COALESCE(FEES_COLLECTION_POINT, '' ) AS FEES_COLLECTION_POINT ,
  COALESCE(CONTRACT_ITEMIZE_MONEY, 0 ) AS CONTRACT_ITEMIZE_MONEY ,
  COALESCE(IS_SPECIAL_CREDIT, '' ) AS IS_SPECIAL_CREDIT ,
  COALESCE(GUARANTY_TYPE, '' ) AS GUARANTY_TYPE ,
  COALESCE(CREDIT_TERM, 0 ) AS CREDIT_TERM ,
  COALESCE(ORI_CONTRACT_BIZ_DETAIL_ID, '' ) AS ORI_CONTRACT_BIZ_DETAIL_ID ,
  COALESCE(REVERT_AMT_LIMIT, 0 ) AS REVERT_AMT_LIMIT ,
  COALESCE(CRD_LIMIT_PRODUCT_CD, '' ) AS CRD_LIMIT_PRODUCT_CD ,
  COALESCE(USED_CURRENCY_NAME, '' ) AS USED_CURRENCY_NAME ,
  COALESCE(ADD_GUARANTY_NEGO_RATE, 0 ) AS ADD_GUARANTY_NEGO_RATE ,
  COALESCE(CUSTOMER_PAY_NAME, '' ) AS CUSTOMER_PAY_NAME ,
  COALESCE(CUSTOMER_PAY_NO, '' ) AS CUSTOMER_PAY_NO ,
  COALESCE(ACCOUNT_OPENING_BANK, '' ) AS ACCOUNT_OPENING_BANK 
 FROM  dw_tdata.CCS_004_TB_CON_BIZ_DETAIL_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  CONTRACT_BIZ_DETAIL_ID ,
  BIZ_DETAIL_TYPE_CD ,
  BIZ_DETAIL_ID ,
  CONTRACT_NUM ,
  BIZ_NUM ,
  CREDIT_PRODUCT_CD ,
  CURRENCY_CD ,
  CONTRACT_CREDIT_AMT ,
  CONTRACT_TERM ,
  START_DATE ,
  EXPIRATION_DATE ,
  EXCHANGE_RATE ,
  OUTSTANDING_AMT ,
  COMMISSION_BAL ,
  REVERT_TERM_M_SUM ,
  USE_AMT_CD ,
  REVERT_CD ,
  CONTRACT_CYCLE_IND ,
  LOWEST_PAY_AMT ,
  AMT_TYPE_CD ,
  ZS_RMB_AMT ,
  APPLY_USE_AMT ,
  WIDTH_TERM ,
  COMPR_BIZ_CONTRACT_IND ,
  BAL_ACCT ,
  BAL_ACCT_NAME ,
  BAL_ACCT_BANK_NAME ,
  BAL_ACCT_NO ,
  ECONOMY_HOUSE_CYCLE_IND ,
  RATE_YEAR ,
  EXPENSE_RATE ,
  OLD_CONTRACT_BIZ_DETAIL_ID ,
  LOW_RISK_IND ,
  CONTRACT_ID ,
  CONTRACT_TERM_UNIT_CD ,
  TIME_MARK ,
  PAY_CD ,
  IS_TRUST_PAY ,
  PAY_NAME ,
  PAY_NO ,
  REVERT_SPACE_MONTH ,
  ACCRUAL_MONTH ,
  ONLY_ACCRUAL_MONTH ,
  REVERT_LIMIT ,
  REVERT_NAME ,
  REVERT_NO ,
  LOW_REVERT_LIMT ,
  LOW_REVERT_UNIT ,
  IS_REVERT ,
  REVERT_FAITH ,
  DRAW_STYLE ,
  REVERT_APP_DATE_DES ,
  DELAY_REVERT_APP_DES ,
  EXTEND_APP_DATE_DES ,
  ACCRUAL_DAYS ,
  COLLECT_SUM ,
  SPECIFIC_DATE ,
  PAY_SUM ,
  DISCOUNT_CD ,
  DISCOUNT_COUNT ,
  DISCOUNT_SUM ,
  DISCOUNT_WAY ,
  BUY_BACK_FREEZE_DATE ,
  BUY_BACK_END_DATE ,
  IS_BUY_BACK_RATE ,
  BUY_BACK_RATE ,
  CUSTOMER_NAME ,
  KEEP_BUSINESS_SORT ,
  KEEP_AREA ,
  IF_ADJUST_DATE ,
  ADJUST_DATE ,
  PAYOUT_ACCOUNT_NO ,
  PAYOUT_ACCOUNT_BANK ,
  REPAY_ACCOUNT_NO ,
  REPAY_ACCOUNT_BANK ,
  REPAY_PLAN_CREATE_CD ,
  SHORT_PAY_NO ,
  SUPER_PRODUCT_CD ,
  PRODUCT_LEVEL ,
  BANDING_STATUS_CD ,
  FLOW_NO ,
  DEDUCT_AGREMENT_NUM ,
  SUPERVISION_CORP_CD ,
  SUPERVISION_CORP_NAME ,
  ENTRUST_PAY_FIRST_AMT ,
  IF_FIRST_LOAN_DATE ,
  FIRST_DRAWINGS_DATE ,
  IF_BANK_ACCOUNT_NUMBER ,
  IF_EXPENSE_PAY ,
  CON_PAY_ACCOUNT_TYPE ,
  RISK_CLASS_RESULT ,
  IF_RELY_DATE ,
  FXBS_TIME_MARK ,
  REPAY_ACCOUNT_OPEN_ORG_CODE ,
  REPAY_ACCOUNT_OPEN_ORG_NAME ,
  CORE_ENTERPRISE_NAME ,
  CORE_ENTERPRISE_NUM ,
  ENTERPRISE_IND ,
  ENTERPRISE_RELATION ,
  SUPERVISE_ENTERPRISE_RESPONSE ,
  DUTY_CD ,
  IF_SUPERVISE_ENTERPRISE ,
  ORDER_FINANCE_TYPE ,
  DIRECT_TO_INTERNAL_FLAG ,
  PAY_ACCOUNT_OPEN_ORG_CODE ,
  FINANCING_PERCENT ,
  BUSINESS_TYPE ,
  FEES_COLLECTION_POINT ,
  CONTRACT_ITEMIZE_MONEY ,
  IS_SPECIAL_CREDIT ,
  GUARANTY_TYPE ,
  CREDIT_TERM ,
  ORI_CONTRACT_BIZ_DETAIL_ID ,
  REVERT_AMT_LIMIT ,
  CRD_LIMIT_PRODUCT_CD ,
  USED_CURRENCY_NAME ,
  ADD_GUARANTY_NEGO_RATE ,
  CUSTOMER_PAY_NAME ,
  CUSTOMER_PAY_NO ,
  ACCOUNT_OPENING_BANK 
 FROM dw_sdata.CCS_004_TB_CON_BIZ_DETAIL 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.CONTRACT_BIZ_DETAIL_ID = T.CONTRACT_BIZ_DETAIL_ID
WHERE
(T.CONTRACT_BIZ_DETAIL_ID IS NULL)
 OR N.BIZ_DETAIL_TYPE_CD<>T.BIZ_DETAIL_TYPE_CD
 OR N.BIZ_DETAIL_ID<>T.BIZ_DETAIL_ID
 OR N.CONTRACT_NUM<>T.CONTRACT_NUM
 OR N.BIZ_NUM<>T.BIZ_NUM
 OR N.CREDIT_PRODUCT_CD<>T.CREDIT_PRODUCT_CD
 OR N.CURRENCY_CD<>T.CURRENCY_CD
 OR N.CONTRACT_CREDIT_AMT<>T.CONTRACT_CREDIT_AMT
 OR N.CONTRACT_TERM<>T.CONTRACT_TERM
 OR N.START_DATE<>T.START_DATE
 OR N.EXPIRATION_DATE<>T.EXPIRATION_DATE
 OR N.EXCHANGE_RATE<>T.EXCHANGE_RATE
 OR N.OUTSTANDING_AMT<>T.OUTSTANDING_AMT
 OR N.COMMISSION_BAL<>T.COMMISSION_BAL
 OR N.REVERT_TERM_M_SUM<>T.REVERT_TERM_M_SUM
 OR N.USE_AMT_CD<>T.USE_AMT_CD
 OR N.REVERT_CD<>T.REVERT_CD
 OR N.CONTRACT_CYCLE_IND<>T.CONTRACT_CYCLE_IND
 OR N.LOWEST_PAY_AMT<>T.LOWEST_PAY_AMT
 OR N.AMT_TYPE_CD<>T.AMT_TYPE_CD
 OR N.ZS_RMB_AMT<>T.ZS_RMB_AMT
 OR N.APPLY_USE_AMT<>T.APPLY_USE_AMT
 OR N.WIDTH_TERM<>T.WIDTH_TERM
 OR N.COMPR_BIZ_CONTRACT_IND<>T.COMPR_BIZ_CONTRACT_IND
 OR N.BAL_ACCT<>T.BAL_ACCT
 OR N.BAL_ACCT_NAME<>T.BAL_ACCT_NAME
 OR N.BAL_ACCT_BANK_NAME<>T.BAL_ACCT_BANK_NAME
 OR N.BAL_ACCT_NO<>T.BAL_ACCT_NO
 OR N.ECONOMY_HOUSE_CYCLE_IND<>T.ECONOMY_HOUSE_CYCLE_IND
 OR N.RATE_YEAR<>T.RATE_YEAR
 OR N.EXPENSE_RATE<>T.EXPENSE_RATE
 OR N.OLD_CONTRACT_BIZ_DETAIL_ID<>T.OLD_CONTRACT_BIZ_DETAIL_ID
 OR N.LOW_RISK_IND<>T.LOW_RISK_IND
 OR N.CONTRACT_ID<>T.CONTRACT_ID
 OR N.CONTRACT_TERM_UNIT_CD<>T.CONTRACT_TERM_UNIT_CD
 OR N.TIME_MARK<>T.TIME_MARK
 OR N.PAY_CD<>T.PAY_CD
 OR N.IS_TRUST_PAY<>T.IS_TRUST_PAY
 OR N.PAY_NAME<>T.PAY_NAME
 OR N.PAY_NO<>T.PAY_NO
 OR N.REVERT_SPACE_MONTH<>T.REVERT_SPACE_MONTH
 OR N.ACCRUAL_MONTH<>T.ACCRUAL_MONTH
 OR N.ONLY_ACCRUAL_MONTH<>T.ONLY_ACCRUAL_MONTH
 OR N.REVERT_LIMIT<>T.REVERT_LIMIT
 OR N.REVERT_NAME<>T.REVERT_NAME
 OR N.REVERT_NO<>T.REVERT_NO
 OR N.LOW_REVERT_LIMT<>T.LOW_REVERT_LIMT
 OR N.LOW_REVERT_UNIT<>T.LOW_REVERT_UNIT
 OR N.IS_REVERT<>T.IS_REVERT
 OR N.REVERT_FAITH<>T.REVERT_FAITH
 OR N.DRAW_STYLE<>T.DRAW_STYLE
 OR N.REVERT_APP_DATE_DES<>T.REVERT_APP_DATE_DES
 OR N.DELAY_REVERT_APP_DES<>T.DELAY_REVERT_APP_DES
 OR N.EXTEND_APP_DATE_DES<>T.EXTEND_APP_DATE_DES
 OR N.ACCRUAL_DAYS<>T.ACCRUAL_DAYS
 OR N.COLLECT_SUM<>T.COLLECT_SUM
 OR N.SPECIFIC_DATE<>T.SPECIFIC_DATE
 OR N.PAY_SUM<>T.PAY_SUM
 OR N.DISCOUNT_CD<>T.DISCOUNT_CD
 OR N.DISCOUNT_COUNT<>T.DISCOUNT_COUNT
 OR N.DISCOUNT_SUM<>T.DISCOUNT_SUM
 OR N.DISCOUNT_WAY<>T.DISCOUNT_WAY
 OR N.BUY_BACK_FREEZE_DATE<>T.BUY_BACK_FREEZE_DATE
 OR N.BUY_BACK_END_DATE<>T.BUY_BACK_END_DATE
 OR N.IS_BUY_BACK_RATE<>T.IS_BUY_BACK_RATE
 OR N.BUY_BACK_RATE<>T.BUY_BACK_RATE
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.KEEP_BUSINESS_SORT<>T.KEEP_BUSINESS_SORT
 OR N.KEEP_AREA<>T.KEEP_AREA
 OR N.IF_ADJUST_DATE<>T.IF_ADJUST_DATE
 OR N.ADJUST_DATE<>T.ADJUST_DATE
 OR N.PAYOUT_ACCOUNT_NO<>T.PAYOUT_ACCOUNT_NO
 OR N.PAYOUT_ACCOUNT_BANK<>T.PAYOUT_ACCOUNT_BANK
 OR N.REPAY_ACCOUNT_NO<>T.REPAY_ACCOUNT_NO
 OR N.REPAY_ACCOUNT_BANK<>T.REPAY_ACCOUNT_BANK
 OR N.REPAY_PLAN_CREATE_CD<>T.REPAY_PLAN_CREATE_CD
 OR N.SHORT_PAY_NO<>T.SHORT_PAY_NO
 OR N.SUPER_PRODUCT_CD<>T.SUPER_PRODUCT_CD
 OR N.PRODUCT_LEVEL<>T.PRODUCT_LEVEL
 OR N.BANDING_STATUS_CD<>T.BANDING_STATUS_CD
 OR N.FLOW_NO<>T.FLOW_NO
 OR N.DEDUCT_AGREMENT_NUM<>T.DEDUCT_AGREMENT_NUM
 OR N.SUPERVISION_CORP_CD<>T.SUPERVISION_CORP_CD
 OR N.SUPERVISION_CORP_NAME<>T.SUPERVISION_CORP_NAME
 OR N.ENTRUST_PAY_FIRST_AMT<>T.ENTRUST_PAY_FIRST_AMT
 OR N.IF_FIRST_LOAN_DATE<>T.IF_FIRST_LOAN_DATE
 OR N.FIRST_DRAWINGS_DATE<>T.FIRST_DRAWINGS_DATE
 OR N.IF_BANK_ACCOUNT_NUMBER<>T.IF_BANK_ACCOUNT_NUMBER
 OR N.IF_EXPENSE_PAY<>T.IF_EXPENSE_PAY
 OR N.CON_PAY_ACCOUNT_TYPE<>T.CON_PAY_ACCOUNT_TYPE
 OR N.RISK_CLASS_RESULT<>T.RISK_CLASS_RESULT
 OR N.IF_RELY_DATE<>T.IF_RELY_DATE
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.REPAY_ACCOUNT_OPEN_ORG_CODE<>T.REPAY_ACCOUNT_OPEN_ORG_CODE
 OR N.REPAY_ACCOUNT_OPEN_ORG_NAME<>T.REPAY_ACCOUNT_OPEN_ORG_NAME
 OR N.CORE_ENTERPRISE_NAME<>T.CORE_ENTERPRISE_NAME
 OR N.CORE_ENTERPRISE_NUM<>T.CORE_ENTERPRISE_NUM
 OR N.ENTERPRISE_IND<>T.ENTERPRISE_IND
 OR N.ENTERPRISE_RELATION<>T.ENTERPRISE_RELATION
 OR N.SUPERVISE_ENTERPRISE_RESPONSE<>T.SUPERVISE_ENTERPRISE_RESPONSE
 OR N.DUTY_CD<>T.DUTY_CD
 OR N.IF_SUPERVISE_ENTERPRISE<>T.IF_SUPERVISE_ENTERPRISE
 OR N.ORDER_FINANCE_TYPE<>T.ORDER_FINANCE_TYPE
 OR N.DIRECT_TO_INTERNAL_FLAG<>T.DIRECT_TO_INTERNAL_FLAG
 OR N.PAY_ACCOUNT_OPEN_ORG_CODE<>T.PAY_ACCOUNT_OPEN_ORG_CODE
 OR N.FINANCING_PERCENT<>T.FINANCING_PERCENT
 OR N.BUSINESS_TYPE<>T.BUSINESS_TYPE
 OR N.FEES_COLLECTION_POINT<>T.FEES_COLLECTION_POINT
 OR N.CONTRACT_ITEMIZE_MONEY<>T.CONTRACT_ITEMIZE_MONEY
 OR N.IS_SPECIAL_CREDIT<>T.IS_SPECIAL_CREDIT
 OR N.GUARANTY_TYPE<>T.GUARANTY_TYPE
 OR N.CREDIT_TERM<>T.CREDIT_TERM
 OR N.ORI_CONTRACT_BIZ_DETAIL_ID<>T.ORI_CONTRACT_BIZ_DETAIL_ID
 OR N.REVERT_AMT_LIMIT<>T.REVERT_AMT_LIMIT
 OR N.CRD_LIMIT_PRODUCT_CD<>T.CRD_LIMIT_PRODUCT_CD
 OR N.USED_CURRENCY_NAME<>T.USED_CURRENCY_NAME
 OR N.ADD_GUARANTY_NEGO_RATE<>T.ADD_GUARANTY_NEGO_RATE
 OR N.CUSTOMER_PAY_NAME<>T.CUSTOMER_PAY_NAME
 OR N.CUSTOMER_PAY_NO<>T.CUSTOMER_PAY_NO
 OR N.ACCOUNT_OPENING_BANK<>T.ACCOUNT_OPENING_BANK
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_CON_BIZ_DETAIL P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_108
WHERE P.End_Dt=DATE('2100-12-31')
AND P.CONTRACT_BIZ_DETAIL_ID=T_108.CONTRACT_BIZ_DETAIL_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_CON_BIZ_DETAIL SELECT * FROM T_108;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
