#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_113 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL WHERE 1=0;

--Step2:
INSERT  INTO T_113 (
  PAYOUT_INFO_DETAIL_ID,
  CREDIT_PRODUCT_CD,
  PAYOUT_NOTICE_NUM,
  AMT,
  CONTRACT_NUM,
  CONTRACT_BIZ_DETAIL_ID,
  CURRENCY_CD,
  QUOTE_DETAIL_ID,
  BIZ_DETAIL_TYPE_CD,
  TERM,
  TERM_UNIT_CD,
  START_DATE,
  PAYOUT_APP_FORM_NUM,
  EXPIRATION_DATE,
  EXTEND_DATE,
  PAYOUT_INFO_ID,
  ACCOUNTANT_KIND_CD,
  BIZ_SYMBOL_CD,
  HANDLING_ORG_CD,
  HANDLING_USER_NUM,
  PAYOUT_DETAIL_STATUS_CD,
  POST_PONEMENT_IND,
  TIME_MARK,
  BYD_ORG_CD,
  CHP_ORG_CD,
  PAYOUT_ACCOUNT,
  CUSTOMER_NUM,
  CUSTOMER_NAME,
  ISSUE_TYPE_CD,
  PAYOUT_ACCOUNT_BANK,
  PAYOUT_ACCOUNT_NAME,
  REPAY_ACCOUNT_BANK,
  REPAY_ACCOUNT_NAME,
  REPAY_ACCOUNT_NUMBER,
  CONTRACT_ID,
  SEND_STATUS_CD,
  REVERT_CD,
  BORROW_NUM,
  REVERT_SPACE_MONTH,
  ACCRUAL_MONTH,
  ONLY_ACCRUAL_MONTH,
  IF_ADJUST_DATE,
  ADJUST_DATE,
  IF_PROXY_PAY,
  IF_MY_BANK,
  PAY_OBJECT_NAME,
  PAY_OBJECT_ACCT_NO,
  PAY_OBJECT_ORG_CD,
  PAY_OBJECT_ACCT_BANK,
  PAYOUT_ACCOUNT_NO,
  REPAY_ACCOUNT_NO,
  REPAY_PLAN_CREATE_CD,
  ASSETS_BORR_ID,
  RECEPTION_CENTER_BANK_NAME,
  RECEPTION_CENTER_BANK_NUM,
  POSTING_ACCOUNT,
  OTHER_HANDING_USER_CD,
  OTHER_APPROVE_USER_CD,
  EDIT_LCGU_DATE,
  IF_MYBK_REPAYACCTNO,
  IF_LATEST_EXTENDBORR,
  PAY_ACCOUNT_TYPE,
  BIG_PAYMENT_IND,
  IF_RELY_DATE,
  FIRST_JIEXI_DATE,
  IF_HAVE_BILL,
  OUTER_GUARANTEE_CD,
  FXBS_TIME_MARK,
  BANK_GROUP_TOTAL_AMT,
  BANK_GROUP_ADVANCE_ORG_CD,
  EXCHANGE_RATE_TYPE,
  EXCHANGE_RATE,
  OUGHT_BAIL_AMT,
  BAIL_AMT,
  OUGHT_BAIL_AMT_RATIO,
  DELIVER_DATE,
  DELIVER_AMT,
  DELIVER_RATIO,
  ADJUST_COEFFICIENT,
  DIRECT_TO_INTERNAL_FLAG,
  LOAN_ADOWN_MARK,
  start_dt,
  end_dt)
SELECT
  N.PAYOUT_INFO_DETAIL_ID,
  N.CREDIT_PRODUCT_CD,
  N.PAYOUT_NOTICE_NUM,
  N.AMT,
  N.CONTRACT_NUM,
  N.CONTRACT_BIZ_DETAIL_ID,
  N.CURRENCY_CD,
  N.QUOTE_DETAIL_ID,
  N.BIZ_DETAIL_TYPE_CD,
  N.TERM,
  N.TERM_UNIT_CD,
  N.START_DATE,
  N.PAYOUT_APP_FORM_NUM,
  N.EXPIRATION_DATE,
  N.EXTEND_DATE,
  N.PAYOUT_INFO_ID,
  N.ACCOUNTANT_KIND_CD,
  N.BIZ_SYMBOL_CD,
  N.HANDLING_ORG_CD,
  N.HANDLING_USER_NUM,
  N.PAYOUT_DETAIL_STATUS_CD,
  N.POST_PONEMENT_IND,
  N.TIME_MARK,
  N.BYD_ORG_CD,
  N.CHP_ORG_CD,
  N.PAYOUT_ACCOUNT,
  N.CUSTOMER_NUM,
  N.CUSTOMER_NAME,
  N.ISSUE_TYPE_CD,
  N.PAYOUT_ACCOUNT_BANK,
  N.PAYOUT_ACCOUNT_NAME,
  N.REPAY_ACCOUNT_BANK,
  N.REPAY_ACCOUNT_NAME,
  N.REPAY_ACCOUNT_NUMBER,
  N.CONTRACT_ID,
  N.SEND_STATUS_CD,
  N.REVERT_CD,
  N.BORROW_NUM,
  N.REVERT_SPACE_MONTH,
  N.ACCRUAL_MONTH,
  N.ONLY_ACCRUAL_MONTH,
  N.IF_ADJUST_DATE,
  N.ADJUST_DATE,
  N.IF_PROXY_PAY,
  N.IF_MY_BANK,
  N.PAY_OBJECT_NAME,
  N.PAY_OBJECT_ACCT_NO,
  N.PAY_OBJECT_ORG_CD,
  N.PAY_OBJECT_ACCT_BANK,
  N.PAYOUT_ACCOUNT_NO,
  N.REPAY_ACCOUNT_NO,
  N.REPAY_PLAN_CREATE_CD,
  N.ASSETS_BORR_ID,
  N.RECEPTION_CENTER_BANK_NAME,
  N.RECEPTION_CENTER_BANK_NUM,
  N.POSTING_ACCOUNT,
  N.OTHER_HANDING_USER_CD,
  N.OTHER_APPROVE_USER_CD,
  N.EDIT_LCGU_DATE,
  N.IF_MYBK_REPAYACCTNO,
  N.IF_LATEST_EXTENDBORR,
  N.PAY_ACCOUNT_TYPE,
  N.BIG_PAYMENT_IND,
  N.IF_RELY_DATE,
  N.FIRST_JIEXI_DATE,
  N.IF_HAVE_BILL,
  N.OUTER_GUARANTEE_CD,
  N.FXBS_TIME_MARK,
  N.BANK_GROUP_TOTAL_AMT,
  N.BANK_GROUP_ADVANCE_ORG_CD,
  N.EXCHANGE_RATE_TYPE,
  N.EXCHANGE_RATE,
  N.OUGHT_BAIL_AMT,
  N.BAIL_AMT,
  N.OUGHT_BAIL_AMT_RATIO,
  N.DELIVER_DATE,
  N.DELIVER_AMT,
  N.DELIVER_RATIO,
  N.ADJUST_COEFFICIENT,
  N.DIRECT_TO_INTERNAL_FLAG,
  N.LOAN_ADOWN_MARK,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PAYOUT_INFO_DETAIL_ID, '' ) AS PAYOUT_INFO_DETAIL_ID ,
  COALESCE(CREDIT_PRODUCT_CD, '' ) AS CREDIT_PRODUCT_CD ,
  COALESCE(PAYOUT_NOTICE_NUM, '' ) AS PAYOUT_NOTICE_NUM ,
  COALESCE(AMT, 0 ) AS AMT ,
  COALESCE(CONTRACT_NUM, '' ) AS CONTRACT_NUM ,
  COALESCE(CONTRACT_BIZ_DETAIL_ID, '' ) AS CONTRACT_BIZ_DETAIL_ID ,
  COALESCE(CURRENCY_CD, '' ) AS CURRENCY_CD ,
  COALESCE(QUOTE_DETAIL_ID, '' ) AS QUOTE_DETAIL_ID ,
  COALESCE(BIZ_DETAIL_TYPE_CD, '' ) AS BIZ_DETAIL_TYPE_CD ,
  COALESCE(TERM, 0 ) AS TERM ,
  COALESCE(TERM_UNIT_CD, '' ) AS TERM_UNIT_CD ,
  COALESCE(START_DATE,'4999-12-31 00:00:00' ) AS START_DATE ,
  COALESCE(PAYOUT_APP_FORM_NUM, '' ) AS PAYOUT_APP_FORM_NUM ,
  COALESCE(EXPIRATION_DATE,'4999-12-31 00:00:00' ) AS EXPIRATION_DATE ,
  COALESCE(EXTEND_DATE,'4999-12-31 00:00:00' ) AS EXTEND_DATE ,
  COALESCE(PAYOUT_INFO_ID, '' ) AS PAYOUT_INFO_ID ,
  COALESCE(ACCOUNTANT_KIND_CD, '' ) AS ACCOUNTANT_KIND_CD ,
  COALESCE(BIZ_SYMBOL_CD, '' ) AS BIZ_SYMBOL_CD ,
  COALESCE(HANDLING_ORG_CD, '' ) AS HANDLING_ORG_CD ,
  COALESCE(HANDLING_USER_NUM, '' ) AS HANDLING_USER_NUM ,
  COALESCE(PAYOUT_DETAIL_STATUS_CD, '' ) AS PAYOUT_DETAIL_STATUS_CD ,
  COALESCE(POST_PONEMENT_IND, '' ) AS POST_PONEMENT_IND ,
  COALESCE(TIME_MARK,'4999-12-31 00:00:00' ) AS TIME_MARK ,
  COALESCE(BYD_ORG_CD, '' ) AS BYD_ORG_CD ,
  COALESCE(CHP_ORG_CD, '' ) AS CHP_ORG_CD ,
  COALESCE(PAYOUT_ACCOUNT, '' ) AS PAYOUT_ACCOUNT ,
  COALESCE(CUSTOMER_NUM, '' ) AS CUSTOMER_NUM ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(ISSUE_TYPE_CD, '' ) AS ISSUE_TYPE_CD ,
  COALESCE(PAYOUT_ACCOUNT_BANK, '' ) AS PAYOUT_ACCOUNT_BANK ,
  COALESCE(PAYOUT_ACCOUNT_NAME, '' ) AS PAYOUT_ACCOUNT_NAME ,
  COALESCE(REPAY_ACCOUNT_BANK, '' ) AS REPAY_ACCOUNT_BANK ,
  COALESCE(REPAY_ACCOUNT_NAME, '' ) AS REPAY_ACCOUNT_NAME ,
  COALESCE(REPAY_ACCOUNT_NUMBER, '' ) AS REPAY_ACCOUNT_NUMBER ,
  COALESCE(CONTRACT_ID, '' ) AS CONTRACT_ID ,
  COALESCE(SEND_STATUS_CD, '' ) AS SEND_STATUS_CD ,
  COALESCE(REVERT_CD, '' ) AS REVERT_CD ,
  COALESCE(BORROW_NUM, '' ) AS BORROW_NUM ,
  COALESCE(REVERT_SPACE_MONTH, '' ) AS REVERT_SPACE_MONTH ,
  COALESCE(ACCRUAL_MONTH, '' ) AS ACCRUAL_MONTH ,
  COALESCE(ONLY_ACCRUAL_MONTH, 0 ) AS ONLY_ACCRUAL_MONTH ,
  COALESCE(IF_ADJUST_DATE, '' ) AS IF_ADJUST_DATE ,
  COALESCE(ADJUST_DATE, '' ) AS ADJUST_DATE ,
  COALESCE(IF_PROXY_PAY, '' ) AS IF_PROXY_PAY ,
  COALESCE(IF_MY_BANK, '' ) AS IF_MY_BANK ,
  COALESCE(PAY_OBJECT_NAME, '' ) AS PAY_OBJECT_NAME ,
  COALESCE(PAY_OBJECT_ACCT_NO, '' ) AS PAY_OBJECT_ACCT_NO ,
  COALESCE(PAY_OBJECT_ORG_CD, '' ) AS PAY_OBJECT_ORG_CD ,
  COALESCE(PAY_OBJECT_ACCT_BANK, '' ) AS PAY_OBJECT_ACCT_BANK ,
  COALESCE(PAYOUT_ACCOUNT_NO, '' ) AS PAYOUT_ACCOUNT_NO ,
  COALESCE(REPAY_ACCOUNT_NO, '' ) AS REPAY_ACCOUNT_NO ,
  COALESCE(REPAY_PLAN_CREATE_CD, '' ) AS REPAY_PLAN_CREATE_CD ,
  COALESCE(ASSETS_BORR_ID, '' ) AS ASSETS_BORR_ID ,
  COALESCE(RECEPTION_CENTER_BANK_NAME, '' ) AS RECEPTION_CENTER_BANK_NAME ,
  COALESCE(RECEPTION_CENTER_BANK_NUM, '' ) AS RECEPTION_CENTER_BANK_NUM ,
  COALESCE(POSTING_ACCOUNT, '' ) AS POSTING_ACCOUNT ,
  COALESCE(OTHER_HANDING_USER_CD, '' ) AS OTHER_HANDING_USER_CD ,
  COALESCE(OTHER_APPROVE_USER_CD, '' ) AS OTHER_APPROVE_USER_CD ,
  COALESCE(EDIT_LCGU_DATE,'4999-12-31 00:00:00' ) AS EDIT_LCGU_DATE ,
  COALESCE(IF_MYBK_REPAYACCTNO, '' ) AS IF_MYBK_REPAYACCTNO ,
  COALESCE(IF_LATEST_EXTENDBORR, '' ) AS IF_LATEST_EXTENDBORR ,
  COALESCE(PAY_ACCOUNT_TYPE, '' ) AS PAY_ACCOUNT_TYPE ,
  COALESCE(BIG_PAYMENT_IND, '' ) AS BIG_PAYMENT_IND ,
  COALESCE(IF_RELY_DATE, '' ) AS IF_RELY_DATE ,
  COALESCE(FIRST_JIEXI_DATE,'4999-12-31 00:00:00' ) AS FIRST_JIEXI_DATE ,
  COALESCE(IF_HAVE_BILL, '' ) AS IF_HAVE_BILL ,
  COALESCE(OUTER_GUARANTEE_CD, '' ) AS OUTER_GUARANTEE_CD ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(BANK_GROUP_TOTAL_AMT, 0 ) AS BANK_GROUP_TOTAL_AMT ,
  COALESCE(BANK_GROUP_ADVANCE_ORG_CD, '' ) AS BANK_GROUP_ADVANCE_ORG_CD ,
  COALESCE(EXCHANGE_RATE_TYPE, '' ) AS EXCHANGE_RATE_TYPE ,
  COALESCE(EXCHANGE_RATE, 0 ) AS EXCHANGE_RATE ,
  COALESCE(OUGHT_BAIL_AMT, 0 ) AS OUGHT_BAIL_AMT ,
  COALESCE(BAIL_AMT, 0 ) AS BAIL_AMT ,
  COALESCE(OUGHT_BAIL_AMT_RATIO, 0 ) AS OUGHT_BAIL_AMT_RATIO ,
  COALESCE(DELIVER_DATE,'4999-12-31 00:00:00' ) AS DELIVER_DATE ,
  COALESCE(DELIVER_AMT, 0 ) AS DELIVER_AMT ,
  COALESCE(DELIVER_RATIO, 0 ) AS DELIVER_RATIO ,
  COALESCE(ADJUST_COEFFICIENT, 0 ) AS ADJUST_COEFFICIENT ,
  COALESCE(DIRECT_TO_INTERNAL_FLAG, '' ) AS DIRECT_TO_INTERNAL_FLAG ,
  COALESCE(LOAN_ADOWN_MARK, '' ) AS LOAN_ADOWN_MARK 
 FROM  dw_tdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PAYOUT_INFO_DETAIL_ID ,
  CREDIT_PRODUCT_CD ,
  PAYOUT_NOTICE_NUM ,
  AMT ,
  CONTRACT_NUM ,
  CONTRACT_BIZ_DETAIL_ID ,
  CURRENCY_CD ,
  QUOTE_DETAIL_ID ,
  BIZ_DETAIL_TYPE_CD ,
  TERM ,
  TERM_UNIT_CD ,
  START_DATE ,
  PAYOUT_APP_FORM_NUM ,
  EXPIRATION_DATE ,
  EXTEND_DATE ,
  PAYOUT_INFO_ID ,
  ACCOUNTANT_KIND_CD ,
  BIZ_SYMBOL_CD ,
  HANDLING_ORG_CD ,
  HANDLING_USER_NUM ,
  PAYOUT_DETAIL_STATUS_CD ,
  POST_PONEMENT_IND ,
  TIME_MARK ,
  BYD_ORG_CD ,
  CHP_ORG_CD ,
  PAYOUT_ACCOUNT ,
  CUSTOMER_NUM ,
  CUSTOMER_NAME ,
  ISSUE_TYPE_CD ,
  PAYOUT_ACCOUNT_BANK ,
  PAYOUT_ACCOUNT_NAME ,
  REPAY_ACCOUNT_BANK ,
  REPAY_ACCOUNT_NAME ,
  REPAY_ACCOUNT_NUMBER ,
  CONTRACT_ID ,
  SEND_STATUS_CD ,
  REVERT_CD ,
  BORROW_NUM ,
  REVERT_SPACE_MONTH ,
  ACCRUAL_MONTH ,
  ONLY_ACCRUAL_MONTH ,
  IF_ADJUST_DATE ,
  ADJUST_DATE ,
  IF_PROXY_PAY ,
  IF_MY_BANK ,
  PAY_OBJECT_NAME ,
  PAY_OBJECT_ACCT_NO ,
  PAY_OBJECT_ORG_CD ,
  PAY_OBJECT_ACCT_BANK ,
  PAYOUT_ACCOUNT_NO ,
  REPAY_ACCOUNT_NO ,
  REPAY_PLAN_CREATE_CD ,
  ASSETS_BORR_ID ,
  RECEPTION_CENTER_BANK_NAME ,
  RECEPTION_CENTER_BANK_NUM ,
  POSTING_ACCOUNT ,
  OTHER_HANDING_USER_CD ,
  OTHER_APPROVE_USER_CD ,
  EDIT_LCGU_DATE ,
  IF_MYBK_REPAYACCTNO ,
  IF_LATEST_EXTENDBORR ,
  PAY_ACCOUNT_TYPE ,
  BIG_PAYMENT_IND ,
  IF_RELY_DATE ,
  FIRST_JIEXI_DATE ,
  IF_HAVE_BILL ,
  OUTER_GUARANTEE_CD ,
  FXBS_TIME_MARK ,
  BANK_GROUP_TOTAL_AMT ,
  BANK_GROUP_ADVANCE_ORG_CD ,
  EXCHANGE_RATE_TYPE ,
  EXCHANGE_RATE ,
  OUGHT_BAIL_AMT ,
  BAIL_AMT ,
  OUGHT_BAIL_AMT_RATIO ,
  DELIVER_DATE ,
  DELIVER_AMT ,
  DELIVER_RATIO ,
  ADJUST_COEFFICIENT ,
  DIRECT_TO_INTERNAL_FLAG ,
  LOAN_ADOWN_MARK 
 FROM dw_sdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.PAYOUT_INFO_DETAIL_ID = T.PAYOUT_INFO_DETAIL_ID
WHERE
(T.PAYOUT_INFO_DETAIL_ID IS NULL)
 OR N.CREDIT_PRODUCT_CD<>T.CREDIT_PRODUCT_CD
 OR N.PAYOUT_NOTICE_NUM<>T.PAYOUT_NOTICE_NUM
 OR N.AMT<>T.AMT
 OR N.CONTRACT_NUM<>T.CONTRACT_NUM
 OR N.CONTRACT_BIZ_DETAIL_ID<>T.CONTRACT_BIZ_DETAIL_ID
 OR N.CURRENCY_CD<>T.CURRENCY_CD
 OR N.QUOTE_DETAIL_ID<>T.QUOTE_DETAIL_ID
 OR N.BIZ_DETAIL_TYPE_CD<>T.BIZ_DETAIL_TYPE_CD
 OR N.TERM<>T.TERM
 OR N.TERM_UNIT_CD<>T.TERM_UNIT_CD
 OR N.START_DATE<>T.START_DATE
 OR N.PAYOUT_APP_FORM_NUM<>T.PAYOUT_APP_FORM_NUM
 OR N.EXPIRATION_DATE<>T.EXPIRATION_DATE
 OR N.EXTEND_DATE<>T.EXTEND_DATE
 OR N.PAYOUT_INFO_ID<>T.PAYOUT_INFO_ID
 OR N.ACCOUNTANT_KIND_CD<>T.ACCOUNTANT_KIND_CD
 OR N.BIZ_SYMBOL_CD<>T.BIZ_SYMBOL_CD
 OR N.HANDLING_ORG_CD<>T.HANDLING_ORG_CD
 OR N.HANDLING_USER_NUM<>T.HANDLING_USER_NUM
 OR N.PAYOUT_DETAIL_STATUS_CD<>T.PAYOUT_DETAIL_STATUS_CD
 OR N.POST_PONEMENT_IND<>T.POST_PONEMENT_IND
 OR N.TIME_MARK<>T.TIME_MARK
 OR N.BYD_ORG_CD<>T.BYD_ORG_CD
 OR N.CHP_ORG_CD<>T.CHP_ORG_CD
 OR N.PAYOUT_ACCOUNT<>T.PAYOUT_ACCOUNT
 OR N.CUSTOMER_NUM<>T.CUSTOMER_NUM
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.ISSUE_TYPE_CD<>T.ISSUE_TYPE_CD
 OR N.PAYOUT_ACCOUNT_BANK<>T.PAYOUT_ACCOUNT_BANK
 OR N.PAYOUT_ACCOUNT_NAME<>T.PAYOUT_ACCOUNT_NAME
 OR N.REPAY_ACCOUNT_BANK<>T.REPAY_ACCOUNT_BANK
 OR N.REPAY_ACCOUNT_NAME<>T.REPAY_ACCOUNT_NAME
 OR N.REPAY_ACCOUNT_NUMBER<>T.REPAY_ACCOUNT_NUMBER
 OR N.CONTRACT_ID<>T.CONTRACT_ID
 OR N.SEND_STATUS_CD<>T.SEND_STATUS_CD
 OR N.REVERT_CD<>T.REVERT_CD
 OR N.BORROW_NUM<>T.BORROW_NUM
 OR N.REVERT_SPACE_MONTH<>T.REVERT_SPACE_MONTH
 OR N.ACCRUAL_MONTH<>T.ACCRUAL_MONTH
 OR N.ONLY_ACCRUAL_MONTH<>T.ONLY_ACCRUAL_MONTH
 OR N.IF_ADJUST_DATE<>T.IF_ADJUST_DATE
 OR N.ADJUST_DATE<>T.ADJUST_DATE
 OR N.IF_PROXY_PAY<>T.IF_PROXY_PAY
 OR N.IF_MY_BANK<>T.IF_MY_BANK
 OR N.PAY_OBJECT_NAME<>T.PAY_OBJECT_NAME
 OR N.PAY_OBJECT_ACCT_NO<>T.PAY_OBJECT_ACCT_NO
 OR N.PAY_OBJECT_ORG_CD<>T.PAY_OBJECT_ORG_CD
 OR N.PAY_OBJECT_ACCT_BANK<>T.PAY_OBJECT_ACCT_BANK
 OR N.PAYOUT_ACCOUNT_NO<>T.PAYOUT_ACCOUNT_NO
 OR N.REPAY_ACCOUNT_NO<>T.REPAY_ACCOUNT_NO
 OR N.REPAY_PLAN_CREATE_CD<>T.REPAY_PLAN_CREATE_CD
 OR N.ASSETS_BORR_ID<>T.ASSETS_BORR_ID
 OR N.RECEPTION_CENTER_BANK_NAME<>T.RECEPTION_CENTER_BANK_NAME
 OR N.RECEPTION_CENTER_BANK_NUM<>T.RECEPTION_CENTER_BANK_NUM
 OR N.POSTING_ACCOUNT<>T.POSTING_ACCOUNT
 OR N.OTHER_HANDING_USER_CD<>T.OTHER_HANDING_USER_CD
 OR N.OTHER_APPROVE_USER_CD<>T.OTHER_APPROVE_USER_CD
 OR N.EDIT_LCGU_DATE<>T.EDIT_LCGU_DATE
 OR N.IF_MYBK_REPAYACCTNO<>T.IF_MYBK_REPAYACCTNO
 OR N.IF_LATEST_EXTENDBORR<>T.IF_LATEST_EXTENDBORR
 OR N.PAY_ACCOUNT_TYPE<>T.PAY_ACCOUNT_TYPE
 OR N.BIG_PAYMENT_IND<>T.BIG_PAYMENT_IND
 OR N.IF_RELY_DATE<>T.IF_RELY_DATE
 OR N.FIRST_JIEXI_DATE<>T.FIRST_JIEXI_DATE
 OR N.IF_HAVE_BILL<>T.IF_HAVE_BILL
 OR N.OUTER_GUARANTEE_CD<>T.OUTER_GUARANTEE_CD
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.BANK_GROUP_TOTAL_AMT<>T.BANK_GROUP_TOTAL_AMT
 OR N.BANK_GROUP_ADVANCE_ORG_CD<>T.BANK_GROUP_ADVANCE_ORG_CD
 OR N.EXCHANGE_RATE_TYPE<>T.EXCHANGE_RATE_TYPE
 OR N.EXCHANGE_RATE<>T.EXCHANGE_RATE
 OR N.OUGHT_BAIL_AMT<>T.OUGHT_BAIL_AMT
 OR N.BAIL_AMT<>T.BAIL_AMT
 OR N.OUGHT_BAIL_AMT_RATIO<>T.OUGHT_BAIL_AMT_RATIO
 OR N.DELIVER_DATE<>T.DELIVER_DATE
 OR N.DELIVER_AMT<>T.DELIVER_AMT
 OR N.DELIVER_RATIO<>T.DELIVER_RATIO
 OR N.ADJUST_COEFFICIENT<>T.ADJUST_COEFFICIENT
 OR N.DIRECT_TO_INTERNAL_FLAG<>T.DIRECT_TO_INTERNAL_FLAG
 OR N.LOAN_ADOWN_MARK<>T.LOAN_ADOWN_MARK
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_113
WHERE P.End_Dt=DATE('2100-12-31')
AND P.PAYOUT_INFO_DETAIL_ID=T_113.PAYOUT_INFO_DETAIL_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_CON_PAYOUT_INFO_DETAIL SELECT * FROM T_113;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
