#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_BIZ_EXPENSE_RATE WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_BIZ_EXPENSE_RATE SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_106 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_BIZ_EXPENSE_RATE WHERE 1=0;

--Step2:
INSERT  INTO T_106 (
  BIZ_EXPENSE_RATE_ID,
  BIZ_NUM,
  CREDIT_PRODUCT_CD_APPLY,
  CREDIT_PRODUCT_CD_APPROVE,
  EXPENSE_NAME,
  EXPENSE_BENCHMARK,
  STANDARD_EXPENSE_RATE,
  EXPENSE_RATE_APPLY,
  EXPENSE_RATE_APPROVE,
  EXPENSE_AMT_APPLY,
  EXPENSE_AMT_APPROVE,
  CURRENCY_CD_APPLY,
  CURRENCY_CD_APPROVE,
  FEE_CHARGING_WAY_APPLY,
  FEE_CHARGING_WAY_APPROVE,
  DERATION_TERM_APPLY,
  DERATION_TERM_APPROVE,
  TERM_UNIT_CD_APPLY,
  TERM_UNIT_CD_APPROVE,
  BIZ_DETAIL_ID,
  SYS_UPDATE_TIME,
  EXPENSE_NAME_APPROVE,
  EXPENSE_BENCHMARK_APPROVE,
  STANDARD_EXPENSE_RATE_APPROVE,
  PAY_AMOUNT_APPLY,
  PAY_AMOUNT_APPROVE,
  PAYOUT_PERSON_APPLY,
  PAYOUT_PERSON_APPROVE,
  EXPENSE_PAY_TYPE_CD_APPL,
  EXPENSE_PAY_TYPE_CD,
  ER_VALIDITY_TERM,
  RATE_PAY_CD,
  RATE_PAY_DATE_CD,
  DAY_RATE_WAY,
  RATE_FIXED_WAY,
  RATE_CHANGE_DATE,
  EXPENSE_WAY_CD,
  CHANGE_STATE,
  REMARKS,
  FEE_CHARGE_DIRECTION,
  FXBS_TIME_MARK,
  PAY_ACCT_NAME,
  IF_FIXED_DATE,
  FIXED_DATE,
  start_dt,
  end_dt)
SELECT
  N.BIZ_EXPENSE_RATE_ID,
  N.BIZ_NUM,
  N.CREDIT_PRODUCT_CD_APPLY,
  N.CREDIT_PRODUCT_CD_APPROVE,
  N.EXPENSE_NAME,
  N.EXPENSE_BENCHMARK,
  N.STANDARD_EXPENSE_RATE,
  N.EXPENSE_RATE_APPLY,
  N.EXPENSE_RATE_APPROVE,
  N.EXPENSE_AMT_APPLY,
  N.EXPENSE_AMT_APPROVE,
  N.CURRENCY_CD_APPLY,
  N.CURRENCY_CD_APPROVE,
  N.FEE_CHARGING_WAY_APPLY,
  N.FEE_CHARGING_WAY_APPROVE,
  N.DERATION_TERM_APPLY,
  N.DERATION_TERM_APPROVE,
  N.TERM_UNIT_CD_APPLY,
  N.TERM_UNIT_CD_APPROVE,
  N.BIZ_DETAIL_ID,
  N.SYS_UPDATE_TIME,
  N.EXPENSE_NAME_APPROVE,
  N.EXPENSE_BENCHMARK_APPROVE,
  N.STANDARD_EXPENSE_RATE_APPROVE,
  N.PAY_AMOUNT_APPLY,
  N.PAY_AMOUNT_APPROVE,
  N.PAYOUT_PERSON_APPLY,
  N.PAYOUT_PERSON_APPROVE,
  N.EXPENSE_PAY_TYPE_CD_APPL,
  N.EXPENSE_PAY_TYPE_CD,
  N.ER_VALIDITY_TERM,
  N.RATE_PAY_CD,
  N.RATE_PAY_DATE_CD,
  N.DAY_RATE_WAY,
  N.RATE_FIXED_WAY,
  N.RATE_CHANGE_DATE,
  N.EXPENSE_WAY_CD,
  N.CHANGE_STATE,
  N.REMARKS,
  N.FEE_CHARGE_DIRECTION,
  N.FXBS_TIME_MARK,
  N.PAY_ACCT_NAME,
  N.IF_FIXED_DATE,
  N.FIXED_DATE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(BIZ_EXPENSE_RATE_ID, '' ) AS BIZ_EXPENSE_RATE_ID ,
  COALESCE(BIZ_NUM, '' ) AS BIZ_NUM ,
  COALESCE(CREDIT_PRODUCT_CD_APPLY, '' ) AS CREDIT_PRODUCT_CD_APPLY ,
  COALESCE(CREDIT_PRODUCT_CD_APPROVE, '' ) AS CREDIT_PRODUCT_CD_APPROVE ,
  COALESCE(EXPENSE_NAME, '' ) AS EXPENSE_NAME ,
  COALESCE(EXPENSE_BENCHMARK, 0 ) AS EXPENSE_BENCHMARK ,
  COALESCE(STANDARD_EXPENSE_RATE, 0 ) AS STANDARD_EXPENSE_RATE ,
  COALESCE(EXPENSE_RATE_APPLY, 0 ) AS EXPENSE_RATE_APPLY ,
  COALESCE(EXPENSE_RATE_APPROVE, 0 ) AS EXPENSE_RATE_APPROVE ,
  COALESCE(EXPENSE_AMT_APPLY, 0 ) AS EXPENSE_AMT_APPLY ,
  COALESCE(EXPENSE_AMT_APPROVE, 0 ) AS EXPENSE_AMT_APPROVE ,
  COALESCE(CURRENCY_CD_APPLY, '' ) AS CURRENCY_CD_APPLY ,
  COALESCE(CURRENCY_CD_APPROVE, '' ) AS CURRENCY_CD_APPROVE ,
  COALESCE(FEE_CHARGING_WAY_APPLY, '' ) AS FEE_CHARGING_WAY_APPLY ,
  COALESCE(FEE_CHARGING_WAY_APPROVE, '' ) AS FEE_CHARGING_WAY_APPROVE ,
  COALESCE(DERATION_TERM_APPLY, 0 ) AS DERATION_TERM_APPLY ,
  COALESCE(DERATION_TERM_APPROVE, 0 ) AS DERATION_TERM_APPROVE ,
  COALESCE(TERM_UNIT_CD_APPLY, '' ) AS TERM_UNIT_CD_APPLY ,
  COALESCE(TERM_UNIT_CD_APPROVE, '' ) AS TERM_UNIT_CD_APPROVE ,
  COALESCE(BIZ_DETAIL_ID, '' ) AS BIZ_DETAIL_ID ,
  COALESCE(SYS_UPDATE_TIME,'4999-12-31 00:00:00' ) AS SYS_UPDATE_TIME ,
  COALESCE(EXPENSE_NAME_APPROVE, '' ) AS EXPENSE_NAME_APPROVE ,
  COALESCE(EXPENSE_BENCHMARK_APPROVE, 0 ) AS EXPENSE_BENCHMARK_APPROVE ,
  COALESCE(STANDARD_EXPENSE_RATE_APPROVE, 0 ) AS STANDARD_EXPENSE_RATE_APPROVE ,
  COALESCE(PAY_AMOUNT_APPLY, '' ) AS PAY_AMOUNT_APPLY ,
  COALESCE(PAY_AMOUNT_APPROVE, '' ) AS PAY_AMOUNT_APPROVE ,
  COALESCE(PAYOUT_PERSON_APPLY, '' ) AS PAYOUT_PERSON_APPLY ,
  COALESCE(PAYOUT_PERSON_APPROVE, '' ) AS PAYOUT_PERSON_APPROVE ,
  COALESCE(EXPENSE_PAY_TYPE_CD_APPL, '' ) AS EXPENSE_PAY_TYPE_CD_APPL ,
  COALESCE(EXPENSE_PAY_TYPE_CD, '' ) AS EXPENSE_PAY_TYPE_CD ,
  COALESCE(ER_VALIDITY_TERM, 0 ) AS ER_VALIDITY_TERM ,
  COALESCE(RATE_PAY_CD, '' ) AS RATE_PAY_CD ,
  COALESCE(RATE_PAY_DATE_CD, '' ) AS RATE_PAY_DATE_CD ,
  COALESCE(DAY_RATE_WAY, '' ) AS DAY_RATE_WAY ,
  COALESCE(RATE_FIXED_WAY, '' ) AS RATE_FIXED_WAY ,
  COALESCE(RATE_CHANGE_DATE,'4999-12-31 00:00:00' ) AS RATE_CHANGE_DATE ,
  COALESCE(EXPENSE_WAY_CD, '' ) AS EXPENSE_WAY_CD ,
  COALESCE(CHANGE_STATE, '' ) AS CHANGE_STATE ,
  COALESCE(REMARKS, '' ) AS REMARKS ,
  COALESCE(FEE_CHARGE_DIRECTION, '' ) AS FEE_CHARGE_DIRECTION ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(PAY_ACCT_NAME, '' ) AS PAY_ACCT_NAME ,
  COALESCE(IF_FIXED_DATE, '' ) AS IF_FIXED_DATE ,
  COALESCE(FIXED_DATE, '' ) AS FIXED_DATE 
 FROM  dw_tdata.CCS_004_TB_BIZ_EXPENSE_RATE_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  BIZ_EXPENSE_RATE_ID ,
  BIZ_NUM ,
  CREDIT_PRODUCT_CD_APPLY ,
  CREDIT_PRODUCT_CD_APPROVE ,
  EXPENSE_NAME ,
  EXPENSE_BENCHMARK ,
  STANDARD_EXPENSE_RATE ,
  EXPENSE_RATE_APPLY ,
  EXPENSE_RATE_APPROVE ,
  EXPENSE_AMT_APPLY ,
  EXPENSE_AMT_APPROVE ,
  CURRENCY_CD_APPLY ,
  CURRENCY_CD_APPROVE ,
  FEE_CHARGING_WAY_APPLY ,
  FEE_CHARGING_WAY_APPROVE ,
  DERATION_TERM_APPLY ,
  DERATION_TERM_APPROVE ,
  TERM_UNIT_CD_APPLY ,
  TERM_UNIT_CD_APPROVE ,
  BIZ_DETAIL_ID ,
  SYS_UPDATE_TIME ,
  EXPENSE_NAME_APPROVE ,
  EXPENSE_BENCHMARK_APPROVE ,
  STANDARD_EXPENSE_RATE_APPROVE ,
  PAY_AMOUNT_APPLY ,
  PAY_AMOUNT_APPROVE ,
  PAYOUT_PERSON_APPLY ,
  PAYOUT_PERSON_APPROVE ,
  EXPENSE_PAY_TYPE_CD_APPL ,
  EXPENSE_PAY_TYPE_CD ,
  ER_VALIDITY_TERM ,
  RATE_PAY_CD ,
  RATE_PAY_DATE_CD ,
  DAY_RATE_WAY ,
  RATE_FIXED_WAY ,
  RATE_CHANGE_DATE ,
  EXPENSE_WAY_CD ,
  CHANGE_STATE ,
  REMARKS ,
  FEE_CHARGE_DIRECTION ,
  FXBS_TIME_MARK ,
  PAY_ACCT_NAME ,
  IF_FIXED_DATE ,
  FIXED_DATE 
 FROM dw_sdata.CCS_004_TB_BIZ_EXPENSE_RATE 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.BIZ_EXPENSE_RATE_ID = T.BIZ_EXPENSE_RATE_ID
WHERE
(T.BIZ_EXPENSE_RATE_ID IS NULL)
 OR N.BIZ_NUM<>T.BIZ_NUM
 OR N.CREDIT_PRODUCT_CD_APPLY<>T.CREDIT_PRODUCT_CD_APPLY
 OR N.CREDIT_PRODUCT_CD_APPROVE<>T.CREDIT_PRODUCT_CD_APPROVE
 OR N.EXPENSE_NAME<>T.EXPENSE_NAME
 OR N.EXPENSE_BENCHMARK<>T.EXPENSE_BENCHMARK
 OR N.STANDARD_EXPENSE_RATE<>T.STANDARD_EXPENSE_RATE
 OR N.EXPENSE_RATE_APPLY<>T.EXPENSE_RATE_APPLY
 OR N.EXPENSE_RATE_APPROVE<>T.EXPENSE_RATE_APPROVE
 OR N.EXPENSE_AMT_APPLY<>T.EXPENSE_AMT_APPLY
 OR N.EXPENSE_AMT_APPROVE<>T.EXPENSE_AMT_APPROVE
 OR N.CURRENCY_CD_APPLY<>T.CURRENCY_CD_APPLY
 OR N.CURRENCY_CD_APPROVE<>T.CURRENCY_CD_APPROVE
 OR N.FEE_CHARGING_WAY_APPLY<>T.FEE_CHARGING_WAY_APPLY
 OR N.FEE_CHARGING_WAY_APPROVE<>T.FEE_CHARGING_WAY_APPROVE
 OR N.DERATION_TERM_APPLY<>T.DERATION_TERM_APPLY
 OR N.DERATION_TERM_APPROVE<>T.DERATION_TERM_APPROVE
 OR N.TERM_UNIT_CD_APPLY<>T.TERM_UNIT_CD_APPLY
 OR N.TERM_UNIT_CD_APPROVE<>T.TERM_UNIT_CD_APPROVE
 OR N.BIZ_DETAIL_ID<>T.BIZ_DETAIL_ID
 OR N.SYS_UPDATE_TIME<>T.SYS_UPDATE_TIME
 OR N.EXPENSE_NAME_APPROVE<>T.EXPENSE_NAME_APPROVE
 OR N.EXPENSE_BENCHMARK_APPROVE<>T.EXPENSE_BENCHMARK_APPROVE
 OR N.STANDARD_EXPENSE_RATE_APPROVE<>T.STANDARD_EXPENSE_RATE_APPROVE
 OR N.PAY_AMOUNT_APPLY<>T.PAY_AMOUNT_APPLY
 OR N.PAY_AMOUNT_APPROVE<>T.PAY_AMOUNT_APPROVE
 OR N.PAYOUT_PERSON_APPLY<>T.PAYOUT_PERSON_APPLY
 OR N.PAYOUT_PERSON_APPROVE<>T.PAYOUT_PERSON_APPROVE
 OR N.EXPENSE_PAY_TYPE_CD_APPL<>T.EXPENSE_PAY_TYPE_CD_APPL
 OR N.EXPENSE_PAY_TYPE_CD<>T.EXPENSE_PAY_TYPE_CD
 OR N.ER_VALIDITY_TERM<>T.ER_VALIDITY_TERM
 OR N.RATE_PAY_CD<>T.RATE_PAY_CD
 OR N.RATE_PAY_DATE_CD<>T.RATE_PAY_DATE_CD
 OR N.DAY_RATE_WAY<>T.DAY_RATE_WAY
 OR N.RATE_FIXED_WAY<>T.RATE_FIXED_WAY
 OR N.RATE_CHANGE_DATE<>T.RATE_CHANGE_DATE
 OR N.EXPENSE_WAY_CD<>T.EXPENSE_WAY_CD
 OR N.CHANGE_STATE<>T.CHANGE_STATE
 OR N.REMARKS<>T.REMARKS
 OR N.FEE_CHARGE_DIRECTION<>T.FEE_CHARGE_DIRECTION
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.PAY_ACCT_NAME<>T.PAY_ACCT_NAME
 OR N.IF_FIXED_DATE<>T.IF_FIXED_DATE
 OR N.FIXED_DATE<>T.FIXED_DATE
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_BIZ_EXPENSE_RATE P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_106
WHERE P.End_Dt=DATE('2100-12-31')
AND P.BIZ_EXPENSE_RATE_ID=T_106.BIZ_EXPENSE_RATE_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_BIZ_EXPENSE_RATE SELECT * FROM T_106;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
