#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_CON_CONTRACT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_CON_CONTRACT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_110 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_CON_CONTRACT WHERE 1=0;

--Step2:
INSERT  INTO T_110 (
  CONTRACT_ID,
  CONTRACT_NUM,
  CONTRACT_MANUAL_NUM,
  CUSTOMER_NUM,
  BIZ_NUM,
  CREDIT_LIMIT_NUM,
  CONTRACT_SIGN_DATE,
  COMPR_BIZ_CONTRACT_IND,
  CREDIT_PRODUCT_CD,
  SUPER_CONTRACT_NUM,
  CURRENCY_CD,
  CONTRACT_TOTAL_AMT,
  APPROVE_NUM,
  CONTRACT_TERM_UNIT_CD,
  START_DATE,
  EXPIRATION_DATE,
  CONTRACT_TERM,
  CONTRACT_LOAN_CD,
  CONTRACT_PROVIDE_PURPOSE,
  EXCHANGE_RATE,
  REMIT_P_SUM,
  CONTRACT_TYPE_CD,
  CONTRACT_NATURE_CD,
  CONTRACT_STATUS_CD,
  CONTRACT_TERMINATION_WAY_CD,
  LOW_RISK_IND,
  LOW_RISK_BIZ_TYPE_CD,
  CONTRACT_CYCLE_IND,
  CONTRACT_TERMINATION_DATE,
  HANDLING_ORG_CD,
  HANDLING_USER_NUM,
  DISB_ORG_CD,
  TRANSFERED_TO_WR_IND,
  IF_CORP_HOUST_LOAN,
  WR_ORG_CD,
  CLASSIFICATION_RESULT,
  ORIGINAL_GUARANTY_CONTRACT_NUM,
  TOP_GUARANTY_IND,
  ORIGINAL_CONTRACT_MANUAL_NUM,
  EXTEND_FIELD,
  EXTEND_FLAG_FIELD,
  CREDIT_LIMIT_ID,
  FREEZEN_IND,
  LC_NUM,
  LAST_MAINTAIN_DATE,
  LOAN_TYPE_INSTRUCTION_CD,
  DEBT_REFORM_TYPE_CD,
  POST_PONEMENT_TYPE_CD,
  CONTRACT_SIGN_PLACE,
  CONTRACT_OTHER_CONDITION,
  CONTRACT_SUPPLEMENT,
  PAY_DISCOUNT_AMT,
  TOP_FINANCING_START_DATE,
  TOP_FINANCING_END_DATE,
  SHORT_OPERATION_MATURE_TERM,
  FIRST_PAY_START_TERM,
  TIP_FINANCING_AMT_TERM,
  MAIN_SURETY_MODE,
  MAIN_SUERTY_SUBCHILD,
  OTHER_BANK_SUERTY_MODE,
  OTHER_BANK_SUERTY_SUBCHILD,
  SUERTY_CD,
  PREREQUISITION_COMMENT,
  GUARANTY_NOTE,
  GUARANTY_TYPE,
  REPORT_SUERTY_MODE,
  REPORT_SUERTY_SUBCHILD,
  CONTRACT_CHANGE_IND,
  GUARANTY_RATE,
  WIDTH_TERM,
  PROMISES_AMT,
  PROMISES_AMT_COLLECTION_TYPE,
  YH_CURRENCY_CD,
  TERM_END_DATE,
  RELA_BIZ_NUM,
  PAYOUT_APPROVE_LEVEL,
  OLD_CONTRACT_DETAIL_ID,
  ORIGINAL_CONTRACT_EXP_DATE,
  POSTPONEMENT_IND,
  OLD_BIZ_DETAIL_ID,
  IF_PERSONAL_LOAN_IND,
  CON_HOUSE_MANUAL_NUM,
  APPROVE_USER,
  APPROVE_ORG,
  POST_PONEMENT_CAUSATION,
  LOAN_ACCOUNTS,
  DEDUCTLOAN_ACCOUNTS,
  LOAN_CLASS,
  GOV_RELATION_TPYE_CD,
  GOV_RELATION_WITH_ORGTYPELV,
  TIME_MARK,
  FOURCLASSIFY_CD,
  LOAN_TERM,
  CORE_CONTRACT_CD,
  LOAN_TYPE_INSTRUCT_DETAIL_CD,
  CONTRACT_NAME,
  CONTRACT_BIG,
  CONTRACT_SMALL,
  HANDING_USER_DEP,
  OFFEND_DUTY,
  SEARCH_AREA,
  CONTRACT_PAGE,
  CONTRACT_VALID_DAYS,
  TRANSACT_DATE,
  BANK_GROUP_STYLE,
  MY_BANK_CONSENT_SUM,
  MY_BANK_CONSENT_SCALE,
  LIMIT_LOW_BALANCE,
  LIMIT_CHANGE_UNIT,
  LIMIT_CHANGE_FAITH,
  LIMIT_CHANGE_APP_DES,
  BORROW_ALL_NAME,
  PLAN_OLD_CONTRACT_NUM,
  OLD_SIGN_DATE,
  OLD_CONTRACT_SUM,
  OLD_START_DATE,
  OLD_END_DATE,
  OLD_GUARANTEE_CONTRACT_NUM,
  OLD_GUARANTEE_SIGN_DATE,
  GUARANTEER,
  FARM_SUM,
  FARM_DES,
  BACK_DAYS,
  BUY_NAME,
  BUY_CREDIT_SUM,
  PUBLIC_OBJECT_NAME,
  IS_LOAN_FIRST_CHECK,
  PARTY_ID,
  CUSTOMER_NAME,
  BANKROLL_POOL_KIND,
  IF_LOAN_CONTRACT,
  CLASS_LEVEL,
  TERM_CHANGE_TIME,
  ENTRY_SFD_STATUS_CD,
  LOAN_USE_CD,
  LOAN_USE_SUB_CD,
  RESOLVE_DISPUTED_PLACE,
  LOAN_PURPOSE,
  BANK_GROUP_CREDIT_LOAN_IND,
  IS_TERM_BANKGROUP_FRAME,
  IF_PART_TIME_AGENTS,
  SYNDICATED_DISTRIB,
  ASSETS_TYPE_CD,
  TERM_STATE,
  IF_LOANS_TERM,
  LOANS_TERM,
  LOANS_START_DATE,
  LOANS_END_DATE,
  LOANS_TERM_STATE,
  EXTEND_TERM,
  EXTEND_START_DATE,
  EXTEND_END_DATE,
  EXTEND_TERM_STATE,
  IF_EXTEND_TERM,
  IF_CHANGE_GRT_IND,
  IF_DIVISION_GUARANTEE,
  IF_ASSETS_TRANSFER,
  TRANSFER_TYPE_CD,
  TRANSFER_WAY_CD,
  BUYOUT_TYPE_CD,
  REPAY_RESOURCE,
  IF_TRADE,
  FSE_SF,
  FLAG,
  IF_FINANCING,
  PAY_TYPE_CD,
  TOP_PLEDGE_RATE,
  PLEDGE_WAREHOUSING_CD,
  NET_SCHEME_ID,
  FINANCING_MODEL,
  BDC_DUTY_CD,
  ESTATE_LOAN_CD1,
  ESTATE_LOAN_CD_NAME1,
  ESTATE_LOAN_CD2,
  ESTATE_LOAN_CD_NAME2,
  ESTATE_LOAN_CD3,
  ESTATE_LOAN_CD_NAME3,
  ESTATE_LOAN_CD4,
  ESTATE_LOAN_CD_NAME4,
  ESTATE_LOAN_CD5,
  ESTATE_LOAN_CD_NAME5,
  ESTATE_LOAN_CD6,
  ESTATE_LOAN_CD_NAME6,
  ESTATE_LOAN_CD7,
  ESTATE_LOAN_CD_NAME7,
  POSTPONEMENT_NUM,
  TRANSFER_ASSET_TYPE,
  ORGANIZATION_MODE,
  APPLY_MODE_CODE,
  FXBS_TIME_MARK,
  DIRECT_TO_INTERNAL_FLAG,
  IS_RENEW,
  CONTINUE_OVERDRAFT_TERM,
  REVERT_EXTEND_TERM,
  EMPLOY_CONTRACT_LIMIT,
  CONTINUE_CONTRACT_LIMIT,
  START_EMPLOY_CONTRACT_LIMIT,
  END_EMPLOY_CONTRACT_LIMIT,
  START_CONTINUE_CONTRACT_LIMIT,
  END_CONTINUE_CONTRACT_LIMIT,
  REVERT_PLANNING,
  IF_REVERT_PLANNING,
  CON_TEXT_TYPE,
  IF_STAIR_BRANCH_LAW_CHECK,
  IF_HEAD_BANK_LAW_CHECK,
  CON_TEXT_PROPER,
  GUARANTEE_TEST_UNANIMOUS,
  EXAMINE_PRACTICABLE,
  CON_MESSAGE_UNANIMOUS,
  CON_WRITE_NORM,
  CON_PRACTICABLE_LAW,
  BEFORE_CLASS_MODE,
  BEFORE_CLASS_GRADE,
  BEFORE_CLASS_TIME,
  IF_EJD_LOAN,
  EJD_CREDIT_NUM,
  ZCYL_BIZ_NUM,
  CLOUD_BUSINESS,
  EJD_ID,
  YLD_BIZ_INFO_NUM,
  start_dt,
  end_dt)
SELECT
  N.CONTRACT_ID,
  N.CONTRACT_NUM,
  N.CONTRACT_MANUAL_NUM,
  N.CUSTOMER_NUM,
  N.BIZ_NUM,
  N.CREDIT_LIMIT_NUM,
  N.CONTRACT_SIGN_DATE,
  N.COMPR_BIZ_CONTRACT_IND,
  N.CREDIT_PRODUCT_CD,
  N.SUPER_CONTRACT_NUM,
  N.CURRENCY_CD,
  N.CONTRACT_TOTAL_AMT,
  N.APPROVE_NUM,
  N.CONTRACT_TERM_UNIT_CD,
  N.START_DATE,
  N.EXPIRATION_DATE,
  N.CONTRACT_TERM,
  N.CONTRACT_LOAN_CD,
  N.CONTRACT_PROVIDE_PURPOSE,
  N.EXCHANGE_RATE,
  N.REMIT_P_SUM,
  N.CONTRACT_TYPE_CD,
  N.CONTRACT_NATURE_CD,
  N.CONTRACT_STATUS_CD,
  N.CONTRACT_TERMINATION_WAY_CD,
  N.LOW_RISK_IND,
  N.LOW_RISK_BIZ_TYPE_CD,
  N.CONTRACT_CYCLE_IND,
  N.CONTRACT_TERMINATION_DATE,
  N.HANDLING_ORG_CD,
  N.HANDLING_USER_NUM,
  N.DISB_ORG_CD,
  N.TRANSFERED_TO_WR_IND,
  N.IF_CORP_HOUST_LOAN,
  N.WR_ORG_CD,
  N.CLASSIFICATION_RESULT,
  N.ORIGINAL_GUARANTY_CONTRACT_NUM,
  N.TOP_GUARANTY_IND,
  N.ORIGINAL_CONTRACT_MANUAL_NUM,
  N.EXTEND_FIELD,
  N.EXTEND_FLAG_FIELD,
  N.CREDIT_LIMIT_ID,
  N.FREEZEN_IND,
  N.LC_NUM,
  N.LAST_MAINTAIN_DATE,
  N.LOAN_TYPE_INSTRUCTION_CD,
  N.DEBT_REFORM_TYPE_CD,
  N.POST_PONEMENT_TYPE_CD,
  N.CONTRACT_SIGN_PLACE,
  N.CONTRACT_OTHER_CONDITION,
  N.CONTRACT_SUPPLEMENT,
  N.PAY_DISCOUNT_AMT,
  N.TOP_FINANCING_START_DATE,
  N.TOP_FINANCING_END_DATE,
  N.SHORT_OPERATION_MATURE_TERM,
  N.FIRST_PAY_START_TERM,
  N.TIP_FINANCING_AMT_TERM,
  N.MAIN_SURETY_MODE,
  N.MAIN_SUERTY_SUBCHILD,
  N.OTHER_BANK_SUERTY_MODE,
  N.OTHER_BANK_SUERTY_SUBCHILD,
  N.SUERTY_CD,
  N.PREREQUISITION_COMMENT,
  N.GUARANTY_NOTE,
  N.GUARANTY_TYPE,
  N.REPORT_SUERTY_MODE,
  N.REPORT_SUERTY_SUBCHILD,
  N.CONTRACT_CHANGE_IND,
  N.GUARANTY_RATE,
  N.WIDTH_TERM,
  N.PROMISES_AMT,
  N.PROMISES_AMT_COLLECTION_TYPE,
  N.YH_CURRENCY_CD,
  N.TERM_END_DATE,
  N.RELA_BIZ_NUM,
  N.PAYOUT_APPROVE_LEVEL,
  N.OLD_CONTRACT_DETAIL_ID,
  N.ORIGINAL_CONTRACT_EXP_DATE,
  N.POSTPONEMENT_IND,
  N.OLD_BIZ_DETAIL_ID,
  N.IF_PERSONAL_LOAN_IND,
  N.CON_HOUSE_MANUAL_NUM,
  N.APPROVE_USER,
  N.APPROVE_ORG,
  N.POST_PONEMENT_CAUSATION,
  N.LOAN_ACCOUNTS,
  N.DEDUCTLOAN_ACCOUNTS,
  N.LOAN_CLASS,
  N.GOV_RELATION_TPYE_CD,
  N.GOV_RELATION_WITH_ORGTYPELV,
  N.TIME_MARK,
  N.FOURCLASSIFY_CD,
  N.LOAN_TERM,
  N.CORE_CONTRACT_CD,
  N.LOAN_TYPE_INSTRUCT_DETAIL_CD,
  N.CONTRACT_NAME,
  N.CONTRACT_BIG,
  N.CONTRACT_SMALL,
  N.HANDING_USER_DEP,
  N.OFFEND_DUTY,
  N.SEARCH_AREA,
  N.CONTRACT_PAGE,
  N.CONTRACT_VALID_DAYS,
  N.TRANSACT_DATE,
  N.BANK_GROUP_STYLE,
  N.MY_BANK_CONSENT_SUM,
  N.MY_BANK_CONSENT_SCALE,
  N.LIMIT_LOW_BALANCE,
  N.LIMIT_CHANGE_UNIT,
  N.LIMIT_CHANGE_FAITH,
  N.LIMIT_CHANGE_APP_DES,
  N.BORROW_ALL_NAME,
  N.PLAN_OLD_CONTRACT_NUM,
  N.OLD_SIGN_DATE,
  N.OLD_CONTRACT_SUM,
  N.OLD_START_DATE,
  N.OLD_END_DATE,
  N.OLD_GUARANTEE_CONTRACT_NUM,
  N.OLD_GUARANTEE_SIGN_DATE,
  N.GUARANTEER,
  N.FARM_SUM,
  N.FARM_DES,
  N.BACK_DAYS,
  N.BUY_NAME,
  N.BUY_CREDIT_SUM,
  N.PUBLIC_OBJECT_NAME,
  N.IS_LOAN_FIRST_CHECK,
  N.PARTY_ID,
  N.CUSTOMER_NAME,
  N.BANKROLL_POOL_KIND,
  N.IF_LOAN_CONTRACT,
  N.CLASS_LEVEL,
  N.TERM_CHANGE_TIME,
  N.ENTRY_SFD_STATUS_CD,
  N.LOAN_USE_CD,
  N.LOAN_USE_SUB_CD,
  N.RESOLVE_DISPUTED_PLACE,
  N.LOAN_PURPOSE,
  N.BANK_GROUP_CREDIT_LOAN_IND,
  N.IS_TERM_BANKGROUP_FRAME,
  N.IF_PART_TIME_AGENTS,
  N.SYNDICATED_DISTRIB,
  N.ASSETS_TYPE_CD,
  N.TERM_STATE,
  N.IF_LOANS_TERM,
  N.LOANS_TERM,
  N.LOANS_START_DATE,
  N.LOANS_END_DATE,
  N.LOANS_TERM_STATE,
  N.EXTEND_TERM,
  N.EXTEND_START_DATE,
  N.EXTEND_END_DATE,
  N.EXTEND_TERM_STATE,
  N.IF_EXTEND_TERM,
  N.IF_CHANGE_GRT_IND,
  N.IF_DIVISION_GUARANTEE,
  N.IF_ASSETS_TRANSFER,
  N.TRANSFER_TYPE_CD,
  N.TRANSFER_WAY_CD,
  N.BUYOUT_TYPE_CD,
  N.REPAY_RESOURCE,
  N.IF_TRADE,
  N.FSE_SF,
  N.FLAG,
  N.IF_FINANCING,
  N.PAY_TYPE_CD,
  N.TOP_PLEDGE_RATE,
  N.PLEDGE_WAREHOUSING_CD,
  N.NET_SCHEME_ID,
  N.FINANCING_MODEL,
  N.BDC_DUTY_CD,
  N.ESTATE_LOAN_CD1,
  N.ESTATE_LOAN_CD_NAME1,
  N.ESTATE_LOAN_CD2,
  N.ESTATE_LOAN_CD_NAME2,
  N.ESTATE_LOAN_CD3,
  N.ESTATE_LOAN_CD_NAME3,
  N.ESTATE_LOAN_CD4,
  N.ESTATE_LOAN_CD_NAME4,
  N.ESTATE_LOAN_CD5,
  N.ESTATE_LOAN_CD_NAME5,
  N.ESTATE_LOAN_CD6,
  N.ESTATE_LOAN_CD_NAME6,
  N.ESTATE_LOAN_CD7,
  N.ESTATE_LOAN_CD_NAME7,
  N.POSTPONEMENT_NUM,
  N.TRANSFER_ASSET_TYPE,
  N.ORGANIZATION_MODE,
  N.APPLY_MODE_CODE,
  N.FXBS_TIME_MARK,
  N.DIRECT_TO_INTERNAL_FLAG,
  N.IS_RENEW,
  N.CONTINUE_OVERDRAFT_TERM,
  N.REVERT_EXTEND_TERM,
  N.EMPLOY_CONTRACT_LIMIT,
  N.CONTINUE_CONTRACT_LIMIT,
  N.START_EMPLOY_CONTRACT_LIMIT,
  N.END_EMPLOY_CONTRACT_LIMIT,
  N.START_CONTINUE_CONTRACT_LIMIT,
  N.END_CONTINUE_CONTRACT_LIMIT,
  N.REVERT_PLANNING,
  N.IF_REVERT_PLANNING,
  N.CON_TEXT_TYPE,
  N.IF_STAIR_BRANCH_LAW_CHECK,
  N.IF_HEAD_BANK_LAW_CHECK,
  N.CON_TEXT_PROPER,
  N.GUARANTEE_TEST_UNANIMOUS,
  N.EXAMINE_PRACTICABLE,
  N.CON_MESSAGE_UNANIMOUS,
  N.CON_WRITE_NORM,
  N.CON_PRACTICABLE_LAW,
  N.BEFORE_CLASS_MODE,
  N.BEFORE_CLASS_GRADE,
  N.BEFORE_CLASS_TIME,
  N.IF_EJD_LOAN,
  N.EJD_CREDIT_NUM,
  N.ZCYL_BIZ_NUM,
  N.CLOUD_BUSINESS,
  N.EJD_ID,
  N.YLD_BIZ_INFO_NUM,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(CONTRACT_ID, '' ) AS CONTRACT_ID ,
  COALESCE(CONTRACT_NUM, '' ) AS CONTRACT_NUM ,
  COALESCE(CONTRACT_MANUAL_NUM, '' ) AS CONTRACT_MANUAL_NUM ,
  COALESCE(CUSTOMER_NUM, '' ) AS CUSTOMER_NUM ,
  COALESCE(BIZ_NUM, '' ) AS BIZ_NUM ,
  COALESCE(CREDIT_LIMIT_NUM, '' ) AS CREDIT_LIMIT_NUM ,
  COALESCE(CONTRACT_SIGN_DATE,'4999-12-31 00:00:00' ) AS CONTRACT_SIGN_DATE ,
  COALESCE(COMPR_BIZ_CONTRACT_IND, '' ) AS COMPR_BIZ_CONTRACT_IND ,
  COALESCE(CREDIT_PRODUCT_CD, '' ) AS CREDIT_PRODUCT_CD ,
  COALESCE(SUPER_CONTRACT_NUM, '' ) AS SUPER_CONTRACT_NUM ,
  COALESCE(CURRENCY_CD, '' ) AS CURRENCY_CD ,
  COALESCE(CONTRACT_TOTAL_AMT, 0 ) AS CONTRACT_TOTAL_AMT ,
  COALESCE(APPROVE_NUM, '' ) AS APPROVE_NUM ,
  COALESCE(CONTRACT_TERM_UNIT_CD, '' ) AS CONTRACT_TERM_UNIT_CD ,
  COALESCE(START_DATE,'4999-12-31 00:00:00' ) AS START_DATE ,
  COALESCE(EXPIRATION_DATE,'4999-12-31 00:00:00' ) AS EXPIRATION_DATE ,
  COALESCE(CONTRACT_TERM, 0 ) AS CONTRACT_TERM ,
  COALESCE(CONTRACT_LOAN_CD, '' ) AS CONTRACT_LOAN_CD ,
  COALESCE(CONTRACT_PROVIDE_PURPOSE, '' ) AS CONTRACT_PROVIDE_PURPOSE ,
  COALESCE(EXCHANGE_RATE, 0 ) AS EXCHANGE_RATE ,
  COALESCE(REMIT_P_SUM, 0 ) AS REMIT_P_SUM ,
  COALESCE(CONTRACT_TYPE_CD, '' ) AS CONTRACT_TYPE_CD ,
  COALESCE(CONTRACT_NATURE_CD, '' ) AS CONTRACT_NATURE_CD ,
  COALESCE(CONTRACT_STATUS_CD, '' ) AS CONTRACT_STATUS_CD ,
  COALESCE(CONTRACT_TERMINATION_WAY_CD, '' ) AS CONTRACT_TERMINATION_WAY_CD ,
  COALESCE(LOW_RISK_IND, '' ) AS LOW_RISK_IND ,
  COALESCE(LOW_RISK_BIZ_TYPE_CD, '' ) AS LOW_RISK_BIZ_TYPE_CD ,
  COALESCE(CONTRACT_CYCLE_IND, '' ) AS CONTRACT_CYCLE_IND ,
  COALESCE(CONTRACT_TERMINATION_DATE,'4999-12-31 00:00:00' ) AS CONTRACT_TERMINATION_DATE ,
  COALESCE(HANDLING_ORG_CD, '' ) AS HANDLING_ORG_CD ,
  COALESCE(HANDLING_USER_NUM, '' ) AS HANDLING_USER_NUM ,
  COALESCE(DISB_ORG_CD, '' ) AS DISB_ORG_CD ,
  COALESCE(TRANSFERED_TO_WR_IND, '' ) AS TRANSFERED_TO_WR_IND ,
  COALESCE(IF_CORP_HOUST_LOAN, '' ) AS IF_CORP_HOUST_LOAN ,
  COALESCE(WR_ORG_CD, '' ) AS WR_ORG_CD ,
  COALESCE(CLASSIFICATION_RESULT, '' ) AS CLASSIFICATION_RESULT ,
  COALESCE(ORIGINAL_GUARANTY_CONTRACT_NUM, '' ) AS ORIGINAL_GUARANTY_CONTRACT_NUM ,
  COALESCE(TOP_GUARANTY_IND, '' ) AS TOP_GUARANTY_IND ,
  COALESCE(ORIGINAL_CONTRACT_MANUAL_NUM, '' ) AS ORIGINAL_CONTRACT_MANUAL_NUM ,
  COALESCE(EXTEND_FIELD, '' ) AS EXTEND_FIELD ,
  COALESCE(EXTEND_FLAG_FIELD, '' ) AS EXTEND_FLAG_FIELD ,
  COALESCE(CREDIT_LIMIT_ID, '' ) AS CREDIT_LIMIT_ID ,
  COALESCE(FREEZEN_IND, '' ) AS FREEZEN_IND ,
  COALESCE(LC_NUM, '' ) AS LC_NUM ,
  COALESCE(LAST_MAINTAIN_DATE,'4999-12-31 00:00:00' ) AS LAST_MAINTAIN_DATE ,
  COALESCE(LOAN_TYPE_INSTRUCTION_CD, '' ) AS LOAN_TYPE_INSTRUCTION_CD ,
  COALESCE(DEBT_REFORM_TYPE_CD, '' ) AS DEBT_REFORM_TYPE_CD ,
  COALESCE(POST_PONEMENT_TYPE_CD, '' ) AS POST_PONEMENT_TYPE_CD ,
  COALESCE(CONTRACT_SIGN_PLACE, '' ) AS CONTRACT_SIGN_PLACE ,
  COALESCE(CONTRACT_OTHER_CONDITION, '' ) AS CONTRACT_OTHER_CONDITION ,
  COALESCE(CONTRACT_SUPPLEMENT, '' ) AS CONTRACT_SUPPLEMENT ,
  COALESCE(PAY_DISCOUNT_AMT, 0 ) AS PAY_DISCOUNT_AMT ,
  COALESCE(TOP_FINANCING_START_DATE,'4999-12-31 00:00:00' ) AS TOP_FINANCING_START_DATE ,
  COALESCE(TOP_FINANCING_END_DATE,'4999-12-31 00:00:00' ) AS TOP_FINANCING_END_DATE ,
  COALESCE(SHORT_OPERATION_MATURE_TERM, 0 ) AS SHORT_OPERATION_MATURE_TERM ,
  COALESCE(FIRST_PAY_START_TERM,'4999-12-31 00:00:00' ) AS FIRST_PAY_START_TERM ,
  COALESCE(TIP_FINANCING_AMT_TERM, 0 ) AS TIP_FINANCING_AMT_TERM ,
  COALESCE(MAIN_SURETY_MODE, '' ) AS MAIN_SURETY_MODE ,
  COALESCE(MAIN_SUERTY_SUBCHILD, '' ) AS MAIN_SUERTY_SUBCHILD ,
  COALESCE(OTHER_BANK_SUERTY_MODE, '' ) AS OTHER_BANK_SUERTY_MODE ,
  COALESCE(OTHER_BANK_SUERTY_SUBCHILD, '' ) AS OTHER_BANK_SUERTY_SUBCHILD ,
  COALESCE(SUERTY_CD, '' ) AS SUERTY_CD ,
  COALESCE(PREREQUISITION_COMMENT, '' ) AS PREREQUISITION_COMMENT ,
  COALESCE(GUARANTY_NOTE, '' ) AS GUARANTY_NOTE ,
  COALESCE(GUARANTY_TYPE, '' ) AS GUARANTY_TYPE ,
  COALESCE(REPORT_SUERTY_MODE, '' ) AS REPORT_SUERTY_MODE ,
  COALESCE(REPORT_SUERTY_SUBCHILD, '' ) AS REPORT_SUERTY_SUBCHILD ,
  COALESCE(CONTRACT_CHANGE_IND, '' ) AS CONTRACT_CHANGE_IND ,
  COALESCE(GUARANTY_RATE, 0 ) AS GUARANTY_RATE ,
  COALESCE(WIDTH_TERM, 0 ) AS WIDTH_TERM ,
  COALESCE(PROMISES_AMT, 0 ) AS PROMISES_AMT ,
  COALESCE(PROMISES_AMT_COLLECTION_TYPE, '' ) AS PROMISES_AMT_COLLECTION_TYPE ,
  COALESCE(YH_CURRENCY_CD, '' ) AS YH_CURRENCY_CD ,
  COALESCE(TERM_END_DATE,'4999-12-31 00:00:00' ) AS TERM_END_DATE ,
  COALESCE(RELA_BIZ_NUM, '' ) AS RELA_BIZ_NUM ,
  COALESCE(PAYOUT_APPROVE_LEVEL, '' ) AS PAYOUT_APPROVE_LEVEL ,
  COALESCE(OLD_CONTRACT_DETAIL_ID, '' ) AS OLD_CONTRACT_DETAIL_ID ,
  COALESCE(ORIGINAL_CONTRACT_EXP_DATE,'4999-12-31 00:00:00' ) AS ORIGINAL_CONTRACT_EXP_DATE ,
  COALESCE(POSTPONEMENT_IND, '' ) AS POSTPONEMENT_IND ,
  COALESCE(OLD_BIZ_DETAIL_ID, '' ) AS OLD_BIZ_DETAIL_ID ,
  COALESCE(IF_PERSONAL_LOAN_IND, '' ) AS IF_PERSONAL_LOAN_IND ,
  COALESCE(CON_HOUSE_MANUAL_NUM, '' ) AS CON_HOUSE_MANUAL_NUM ,
  COALESCE(APPROVE_USER, '' ) AS APPROVE_USER ,
  COALESCE(APPROVE_ORG, '' ) AS APPROVE_ORG ,
  COALESCE(POST_PONEMENT_CAUSATION, '' ) AS POST_PONEMENT_CAUSATION ,
  COALESCE(LOAN_ACCOUNTS, '' ) AS LOAN_ACCOUNTS ,
  COALESCE(DEDUCTLOAN_ACCOUNTS, '' ) AS DEDUCTLOAN_ACCOUNTS ,
  COALESCE(LOAN_CLASS, '' ) AS LOAN_CLASS ,
  COALESCE(GOV_RELATION_TPYE_CD, '' ) AS GOV_RELATION_TPYE_CD ,
  COALESCE(GOV_RELATION_WITH_ORGTYPELV, '' ) AS GOV_RELATION_WITH_ORGTYPELV ,
  COALESCE(TIME_MARK,'4999-12-31 00:00:00' ) AS TIME_MARK ,
  COALESCE(FOURCLASSIFY_CD, '' ) AS FOURCLASSIFY_CD ,
  COALESCE(LOAN_TERM, '' ) AS LOAN_TERM ,
  COALESCE(CORE_CONTRACT_CD, '' ) AS CORE_CONTRACT_CD ,
  COALESCE(LOAN_TYPE_INSTRUCT_DETAIL_CD, '' ) AS LOAN_TYPE_INSTRUCT_DETAIL_CD ,
  COALESCE(CONTRACT_NAME, '' ) AS CONTRACT_NAME ,
  COALESCE(CONTRACT_BIG, '' ) AS CONTRACT_BIG ,
  COALESCE(CONTRACT_SMALL, '' ) AS CONTRACT_SMALL ,
  COALESCE(HANDING_USER_DEP, '' ) AS HANDING_USER_DEP ,
  COALESCE(OFFEND_DUTY, '' ) AS OFFEND_DUTY ,
  COALESCE(SEARCH_AREA, '' ) AS SEARCH_AREA ,
  COALESCE(CONTRACT_PAGE, 0 ) AS CONTRACT_PAGE ,
  COALESCE(CONTRACT_VALID_DAYS, 0 ) AS CONTRACT_VALID_DAYS ,
  COALESCE(TRANSACT_DATE,'4999-12-31 00:00:00' ) AS TRANSACT_DATE ,
  COALESCE(BANK_GROUP_STYLE, '' ) AS BANK_GROUP_STYLE ,
  COALESCE(MY_BANK_CONSENT_SUM, 0 ) AS MY_BANK_CONSENT_SUM ,
  COALESCE(MY_BANK_CONSENT_SCALE, 0 ) AS MY_BANK_CONSENT_SCALE ,
  COALESCE(LIMIT_LOW_BALANCE, 0 ) AS LIMIT_LOW_BALANCE ,
  COALESCE(LIMIT_CHANGE_UNIT, 0 ) AS LIMIT_CHANGE_UNIT ,
  COALESCE(LIMIT_CHANGE_FAITH, 0 ) AS LIMIT_CHANGE_FAITH ,
  COALESCE(LIMIT_CHANGE_APP_DES, '' ) AS LIMIT_CHANGE_APP_DES ,
  COALESCE(BORROW_ALL_NAME, '' ) AS BORROW_ALL_NAME ,
  COALESCE(PLAN_OLD_CONTRACT_NUM, '' ) AS PLAN_OLD_CONTRACT_NUM ,
  COALESCE(OLD_SIGN_DATE,'4999-12-31 00:00:00' ) AS OLD_SIGN_DATE ,
  COALESCE(OLD_CONTRACT_SUM, 0 ) AS OLD_CONTRACT_SUM ,
  COALESCE(OLD_START_DATE,'4999-12-31 00:00:00' ) AS OLD_START_DATE ,
  COALESCE(OLD_END_DATE,'4999-12-31 00:00:00' ) AS OLD_END_DATE ,
  COALESCE(OLD_GUARANTEE_CONTRACT_NUM, '' ) AS OLD_GUARANTEE_CONTRACT_NUM ,
  COALESCE(OLD_GUARANTEE_SIGN_DATE,'4999-12-31 00:00:00' ) AS OLD_GUARANTEE_SIGN_DATE ,
  COALESCE(GUARANTEER, '' ) AS GUARANTEER ,
  COALESCE(FARM_SUM, 0 ) AS FARM_SUM ,
  COALESCE(FARM_DES, '' ) AS FARM_DES ,
  COALESCE(BACK_DAYS, 0 ) AS BACK_DAYS ,
  COALESCE(BUY_NAME, '' ) AS BUY_NAME ,
  COALESCE(BUY_CREDIT_SUM, 0 ) AS BUY_CREDIT_SUM ,
  COALESCE(PUBLIC_OBJECT_NAME, '' ) AS PUBLIC_OBJECT_NAME ,
  COALESCE(IS_LOAN_FIRST_CHECK, '' ) AS IS_LOAN_FIRST_CHECK ,
  COALESCE(PARTY_ID, '' ) AS PARTY_ID ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(BANKROLL_POOL_KIND, '' ) AS BANKROLL_POOL_KIND ,
  COALESCE(IF_LOAN_CONTRACT, '' ) AS IF_LOAN_CONTRACT ,
  COALESCE(CLASS_LEVEL, '' ) AS CLASS_LEVEL ,
  COALESCE(TERM_CHANGE_TIME, 0 ) AS TERM_CHANGE_TIME ,
  COALESCE(ENTRY_SFD_STATUS_CD, '' ) AS ENTRY_SFD_STATUS_CD ,
  COALESCE(LOAN_USE_CD, '' ) AS LOAN_USE_CD ,
  COALESCE(LOAN_USE_SUB_CD, '' ) AS LOAN_USE_SUB_CD ,
  COALESCE(RESOLVE_DISPUTED_PLACE, '' ) AS RESOLVE_DISPUTED_PLACE ,
  COALESCE(LOAN_PURPOSE, '' ) AS LOAN_PURPOSE ,
  COALESCE(BANK_GROUP_CREDIT_LOAN_IND, '' ) AS BANK_GROUP_CREDIT_LOAN_IND ,
  COALESCE(IS_TERM_BANKGROUP_FRAME, '' ) AS IS_TERM_BANKGROUP_FRAME ,
  COALESCE(IF_PART_TIME_AGENTS, '' ) AS IF_PART_TIME_AGENTS ,
  COALESCE(SYNDICATED_DISTRIB, '' ) AS SYNDICATED_DISTRIB ,
  COALESCE(ASSETS_TYPE_CD, '' ) AS ASSETS_TYPE_CD ,
  COALESCE(TERM_STATE, '' ) AS TERM_STATE ,
  COALESCE(IF_LOANS_TERM, '' ) AS IF_LOANS_TERM ,
  COALESCE(LOANS_TERM, 0 ) AS LOANS_TERM ,
  COALESCE(LOANS_START_DATE,'4999-12-31 00:00:00' ) AS LOANS_START_DATE ,
  COALESCE(LOANS_END_DATE,'4999-12-31 00:00:00' ) AS LOANS_END_DATE ,
  COALESCE(LOANS_TERM_STATE, '' ) AS LOANS_TERM_STATE ,
  COALESCE(EXTEND_TERM, 0 ) AS EXTEND_TERM ,
  COALESCE(EXTEND_START_DATE,'4999-12-31 00:00:00' ) AS EXTEND_START_DATE ,
  COALESCE(EXTEND_END_DATE,'4999-12-31 00:00:00' ) AS EXTEND_END_DATE ,
  COALESCE(EXTEND_TERM_STATE, '' ) AS EXTEND_TERM_STATE ,
  COALESCE(IF_EXTEND_TERM, '' ) AS IF_EXTEND_TERM ,
  COALESCE(IF_CHANGE_GRT_IND, '' ) AS IF_CHANGE_GRT_IND ,
  COALESCE(IF_DIVISION_GUARANTEE, '' ) AS IF_DIVISION_GUARANTEE ,
  COALESCE(IF_ASSETS_TRANSFER, '' ) AS IF_ASSETS_TRANSFER ,
  COALESCE(TRANSFER_TYPE_CD, '' ) AS TRANSFER_TYPE_CD ,
  COALESCE(TRANSFER_WAY_CD, '' ) AS TRANSFER_WAY_CD ,
  COALESCE(BUYOUT_TYPE_CD, '' ) AS BUYOUT_TYPE_CD ,
  COALESCE(REPAY_RESOURCE, '' ) AS REPAY_RESOURCE ,
  COALESCE(IF_TRADE, '' ) AS IF_TRADE ,
  COALESCE(FSE_SF, 0 ) AS FSE_SF ,
  COALESCE(FLAG, '' ) AS FLAG ,
  COALESCE(IF_FINANCING, '' ) AS IF_FINANCING ,
  COALESCE(PAY_TYPE_CD, '' ) AS PAY_TYPE_CD ,
  COALESCE(TOP_PLEDGE_RATE, 0 ) AS TOP_PLEDGE_RATE ,
  COALESCE(PLEDGE_WAREHOUSING_CD, '' ) AS PLEDGE_WAREHOUSING_CD ,
  COALESCE(NET_SCHEME_ID, '' ) AS NET_SCHEME_ID ,
  COALESCE(FINANCING_MODEL, '' ) AS FINANCING_MODEL ,
  COALESCE(BDC_DUTY_CD, '' ) AS BDC_DUTY_CD ,
  COALESCE(ESTATE_LOAN_CD1, '' ) AS ESTATE_LOAN_CD1 ,
  COALESCE(ESTATE_LOAN_CD_NAME1, '' ) AS ESTATE_LOAN_CD_NAME1 ,
  COALESCE(ESTATE_LOAN_CD2, '' ) AS ESTATE_LOAN_CD2 ,
  COALESCE(ESTATE_LOAN_CD_NAME2, '' ) AS ESTATE_LOAN_CD_NAME2 ,
  COALESCE(ESTATE_LOAN_CD3, '' ) AS ESTATE_LOAN_CD3 ,
  COALESCE(ESTATE_LOAN_CD_NAME3, '' ) AS ESTATE_LOAN_CD_NAME3 ,
  COALESCE(ESTATE_LOAN_CD4, '' ) AS ESTATE_LOAN_CD4 ,
  COALESCE(ESTATE_LOAN_CD_NAME4, '' ) AS ESTATE_LOAN_CD_NAME4 ,
  COALESCE(ESTATE_LOAN_CD5, '' ) AS ESTATE_LOAN_CD5 ,
  COALESCE(ESTATE_LOAN_CD_NAME5, '' ) AS ESTATE_LOAN_CD_NAME5 ,
  COALESCE(ESTATE_LOAN_CD6, '' ) AS ESTATE_LOAN_CD6 ,
  COALESCE(ESTATE_LOAN_CD_NAME6, '' ) AS ESTATE_LOAN_CD_NAME6 ,
  COALESCE(ESTATE_LOAN_CD7, '' ) AS ESTATE_LOAN_CD7 ,
  COALESCE(ESTATE_LOAN_CD_NAME7, '' ) AS ESTATE_LOAN_CD_NAME7 ,
  COALESCE(POSTPONEMENT_NUM, '' ) AS POSTPONEMENT_NUM ,
  COALESCE(TRANSFER_ASSET_TYPE, '' ) AS TRANSFER_ASSET_TYPE ,
  COALESCE(ORGANIZATION_MODE, '' ) AS ORGANIZATION_MODE ,
  COALESCE(APPLY_MODE_CODE, '' ) AS APPLY_MODE_CODE ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(DIRECT_TO_INTERNAL_FLAG, '' ) AS DIRECT_TO_INTERNAL_FLAG ,
  COALESCE(IS_RENEW, '' ) AS IS_RENEW ,
  COALESCE(CONTINUE_OVERDRAFT_TERM, 0 ) AS CONTINUE_OVERDRAFT_TERM ,
  COALESCE(REVERT_EXTEND_TERM, 0 ) AS REVERT_EXTEND_TERM ,
  COALESCE(EMPLOY_CONTRACT_LIMIT, 0 ) AS EMPLOY_CONTRACT_LIMIT ,
  COALESCE(CONTINUE_CONTRACT_LIMIT, 0 ) AS CONTINUE_CONTRACT_LIMIT ,
  COALESCE(START_EMPLOY_CONTRACT_LIMIT,'4999-12-31 00:00:00' ) AS START_EMPLOY_CONTRACT_LIMIT ,
  COALESCE(END_EMPLOY_CONTRACT_LIMIT,'4999-12-31 00:00:00' ) AS END_EMPLOY_CONTRACT_LIMIT ,
  COALESCE(START_CONTINUE_CONTRACT_LIMIT,'4999-12-31 00:00:00' ) AS START_CONTINUE_CONTRACT_LIMIT ,
  COALESCE(END_CONTINUE_CONTRACT_LIMIT,'4999-12-31 00:00:00' ) AS END_CONTINUE_CONTRACT_LIMIT ,
  COALESCE(REVERT_PLANNING, '' ) AS REVERT_PLANNING ,
  COALESCE(IF_REVERT_PLANNING, '' ) AS IF_REVERT_PLANNING ,
  COALESCE(CON_TEXT_TYPE, '' ) AS CON_TEXT_TYPE ,
  COALESCE(IF_STAIR_BRANCH_LAW_CHECK, '' ) AS IF_STAIR_BRANCH_LAW_CHECK ,
  COALESCE(IF_HEAD_BANK_LAW_CHECK, '' ) AS IF_HEAD_BANK_LAW_CHECK ,
  COALESCE(CON_TEXT_PROPER, '' ) AS CON_TEXT_PROPER ,
  COALESCE(GUARANTEE_TEST_UNANIMOUS, '' ) AS GUARANTEE_TEST_UNANIMOUS ,
  COALESCE(EXAMINE_PRACTICABLE, '' ) AS EXAMINE_PRACTICABLE ,
  COALESCE(CON_MESSAGE_UNANIMOUS, '' ) AS CON_MESSAGE_UNANIMOUS ,
  COALESCE(CON_WRITE_NORM, '' ) AS CON_WRITE_NORM ,
  COALESCE(CON_PRACTICABLE_LAW, '' ) AS CON_PRACTICABLE_LAW ,
  COALESCE(BEFORE_CLASS_MODE, '' ) AS BEFORE_CLASS_MODE ,
  COALESCE(BEFORE_CLASS_GRADE, '' ) AS BEFORE_CLASS_GRADE ,
  COALESCE(BEFORE_CLASS_TIME,'4999-12-31 00:00:00' ) AS BEFORE_CLASS_TIME ,
  COALESCE(IF_EJD_LOAN, '' ) AS IF_EJD_LOAN ,
  COALESCE(EJD_CREDIT_NUM, '' ) AS EJD_CREDIT_NUM ,
  COALESCE(ZCYL_BIZ_NUM, '' ) AS ZCYL_BIZ_NUM ,
  COALESCE(CLOUD_BUSINESS, '' ) AS CLOUD_BUSINESS ,
  COALESCE(EJD_ID, '' ) AS EJD_ID ,
  COALESCE(YLD_BIZ_INFO_NUM, '' ) AS YLD_BIZ_INFO_NUM 
 FROM  dw_tdata.CCS_004_TB_CON_CONTRACT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  CONTRACT_ID ,
  CONTRACT_NUM ,
  CONTRACT_MANUAL_NUM ,
  CUSTOMER_NUM ,
  BIZ_NUM ,
  CREDIT_LIMIT_NUM ,
  CONTRACT_SIGN_DATE ,
  COMPR_BIZ_CONTRACT_IND ,
  CREDIT_PRODUCT_CD ,
  SUPER_CONTRACT_NUM ,
  CURRENCY_CD ,
  CONTRACT_TOTAL_AMT ,
  APPROVE_NUM ,
  CONTRACT_TERM_UNIT_CD ,
  START_DATE ,
  EXPIRATION_DATE ,
  CONTRACT_TERM ,
  CONTRACT_LOAN_CD ,
  CONTRACT_PROVIDE_PURPOSE ,
  EXCHANGE_RATE ,
  REMIT_P_SUM ,
  CONTRACT_TYPE_CD ,
  CONTRACT_NATURE_CD ,
  CONTRACT_STATUS_CD ,
  CONTRACT_TERMINATION_WAY_CD ,
  LOW_RISK_IND ,
  LOW_RISK_BIZ_TYPE_CD ,
  CONTRACT_CYCLE_IND ,
  CONTRACT_TERMINATION_DATE ,
  HANDLING_ORG_CD ,
  HANDLING_USER_NUM ,
  DISB_ORG_CD ,
  TRANSFERED_TO_WR_IND ,
  IF_CORP_HOUST_LOAN ,
  WR_ORG_CD ,
  CLASSIFICATION_RESULT ,
  ORIGINAL_GUARANTY_CONTRACT_NUM ,
  TOP_GUARANTY_IND ,
  ORIGINAL_CONTRACT_MANUAL_NUM ,
  EXTEND_FIELD ,
  EXTEND_FLAG_FIELD ,
  CREDIT_LIMIT_ID ,
  FREEZEN_IND ,
  LC_NUM ,
  LAST_MAINTAIN_DATE ,
  LOAN_TYPE_INSTRUCTION_CD ,
  DEBT_REFORM_TYPE_CD ,
  POST_PONEMENT_TYPE_CD ,
  CONTRACT_SIGN_PLACE ,
  CONTRACT_OTHER_CONDITION ,
  CONTRACT_SUPPLEMENT ,
  PAY_DISCOUNT_AMT ,
  TOP_FINANCING_START_DATE ,
  TOP_FINANCING_END_DATE ,
  SHORT_OPERATION_MATURE_TERM ,
  FIRST_PAY_START_TERM ,
  TIP_FINANCING_AMT_TERM ,
  MAIN_SURETY_MODE ,
  MAIN_SUERTY_SUBCHILD ,
  OTHER_BANK_SUERTY_MODE ,
  OTHER_BANK_SUERTY_SUBCHILD ,
  SUERTY_CD ,
  PREREQUISITION_COMMENT ,
  GUARANTY_NOTE ,
  GUARANTY_TYPE ,
  REPORT_SUERTY_MODE ,
  REPORT_SUERTY_SUBCHILD ,
  CONTRACT_CHANGE_IND ,
  GUARANTY_RATE ,
  WIDTH_TERM ,
  PROMISES_AMT ,
  PROMISES_AMT_COLLECTION_TYPE ,
  YH_CURRENCY_CD ,
  TERM_END_DATE ,
  RELA_BIZ_NUM ,
  PAYOUT_APPROVE_LEVEL ,
  OLD_CONTRACT_DETAIL_ID ,
  ORIGINAL_CONTRACT_EXP_DATE ,
  POSTPONEMENT_IND ,
  OLD_BIZ_DETAIL_ID ,
  IF_PERSONAL_LOAN_IND ,
  CON_HOUSE_MANUAL_NUM ,
  APPROVE_USER ,
  APPROVE_ORG ,
  POST_PONEMENT_CAUSATION ,
  LOAN_ACCOUNTS ,
  DEDUCTLOAN_ACCOUNTS ,
  LOAN_CLASS ,
  GOV_RELATION_TPYE_CD ,
  GOV_RELATION_WITH_ORGTYPELV ,
  TIME_MARK ,
  FOURCLASSIFY_CD ,
  LOAN_TERM ,
  CORE_CONTRACT_CD ,
  LOAN_TYPE_INSTRUCT_DETAIL_CD ,
  CONTRACT_NAME ,
  CONTRACT_BIG ,
  CONTRACT_SMALL ,
  HANDING_USER_DEP ,
  OFFEND_DUTY ,
  SEARCH_AREA ,
  CONTRACT_PAGE ,
  CONTRACT_VALID_DAYS ,
  TRANSACT_DATE ,
  BANK_GROUP_STYLE ,
  MY_BANK_CONSENT_SUM ,
  MY_BANK_CONSENT_SCALE ,
  LIMIT_LOW_BALANCE ,
  LIMIT_CHANGE_UNIT ,
  LIMIT_CHANGE_FAITH ,
  LIMIT_CHANGE_APP_DES ,
  BORROW_ALL_NAME ,
  PLAN_OLD_CONTRACT_NUM ,
  OLD_SIGN_DATE ,
  OLD_CONTRACT_SUM ,
  OLD_START_DATE ,
  OLD_END_DATE ,
  OLD_GUARANTEE_CONTRACT_NUM ,
  OLD_GUARANTEE_SIGN_DATE ,
  GUARANTEER ,
  FARM_SUM ,
  FARM_DES ,
  BACK_DAYS ,
  BUY_NAME ,
  BUY_CREDIT_SUM ,
  PUBLIC_OBJECT_NAME ,
  IS_LOAN_FIRST_CHECK ,
  PARTY_ID ,
  CUSTOMER_NAME ,
  BANKROLL_POOL_KIND ,
  IF_LOAN_CONTRACT ,
  CLASS_LEVEL ,
  TERM_CHANGE_TIME ,
  ENTRY_SFD_STATUS_CD ,
  LOAN_USE_CD ,
  LOAN_USE_SUB_CD ,
  RESOLVE_DISPUTED_PLACE ,
  LOAN_PURPOSE ,
  BANK_GROUP_CREDIT_LOAN_IND ,
  IS_TERM_BANKGROUP_FRAME ,
  IF_PART_TIME_AGENTS ,
  SYNDICATED_DISTRIB ,
  ASSETS_TYPE_CD ,
  TERM_STATE ,
  IF_LOANS_TERM ,
  LOANS_TERM ,
  LOANS_START_DATE ,
  LOANS_END_DATE ,
  LOANS_TERM_STATE ,
  EXTEND_TERM ,
  EXTEND_START_DATE ,
  EXTEND_END_DATE ,
  EXTEND_TERM_STATE ,
  IF_EXTEND_TERM ,
  IF_CHANGE_GRT_IND ,
  IF_DIVISION_GUARANTEE ,
  IF_ASSETS_TRANSFER ,
  TRANSFER_TYPE_CD ,
  TRANSFER_WAY_CD ,
  BUYOUT_TYPE_CD ,
  REPAY_RESOURCE ,
  IF_TRADE ,
  FSE_SF ,
  FLAG ,
  IF_FINANCING ,
  PAY_TYPE_CD ,
  TOP_PLEDGE_RATE ,
  PLEDGE_WAREHOUSING_CD ,
  NET_SCHEME_ID ,
  FINANCING_MODEL ,
  BDC_DUTY_CD ,
  ESTATE_LOAN_CD1 ,
  ESTATE_LOAN_CD_NAME1 ,
  ESTATE_LOAN_CD2 ,
  ESTATE_LOAN_CD_NAME2 ,
  ESTATE_LOAN_CD3 ,
  ESTATE_LOAN_CD_NAME3 ,
  ESTATE_LOAN_CD4 ,
  ESTATE_LOAN_CD_NAME4 ,
  ESTATE_LOAN_CD5 ,
  ESTATE_LOAN_CD_NAME5 ,
  ESTATE_LOAN_CD6 ,
  ESTATE_LOAN_CD_NAME6 ,
  ESTATE_LOAN_CD7 ,
  ESTATE_LOAN_CD_NAME7 ,
  POSTPONEMENT_NUM ,
  TRANSFER_ASSET_TYPE ,
  ORGANIZATION_MODE ,
  APPLY_MODE_CODE ,
  FXBS_TIME_MARK ,
  DIRECT_TO_INTERNAL_FLAG ,
  IS_RENEW ,
  CONTINUE_OVERDRAFT_TERM ,
  REVERT_EXTEND_TERM ,
  EMPLOY_CONTRACT_LIMIT ,
  CONTINUE_CONTRACT_LIMIT ,
  START_EMPLOY_CONTRACT_LIMIT ,
  END_EMPLOY_CONTRACT_LIMIT ,
  START_CONTINUE_CONTRACT_LIMIT ,
  END_CONTINUE_CONTRACT_LIMIT ,
  REVERT_PLANNING ,
  IF_REVERT_PLANNING ,
  CON_TEXT_TYPE ,
  IF_STAIR_BRANCH_LAW_CHECK ,
  IF_HEAD_BANK_LAW_CHECK ,
  CON_TEXT_PROPER ,
  GUARANTEE_TEST_UNANIMOUS ,
  EXAMINE_PRACTICABLE ,
  CON_MESSAGE_UNANIMOUS ,
  CON_WRITE_NORM ,
  CON_PRACTICABLE_LAW ,
  BEFORE_CLASS_MODE ,
  BEFORE_CLASS_GRADE ,
  BEFORE_CLASS_TIME ,
  IF_EJD_LOAN ,
  EJD_CREDIT_NUM ,
  ZCYL_BIZ_NUM ,
  CLOUD_BUSINESS ,
  EJD_ID ,
  YLD_BIZ_INFO_NUM 
 FROM dw_sdata.CCS_004_TB_CON_CONTRACT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.CONTRACT_ID = T.CONTRACT_ID
WHERE
(T.CONTRACT_ID IS NULL)
 OR N.CONTRACT_NUM<>T.CONTRACT_NUM
 OR N.CONTRACT_MANUAL_NUM<>T.CONTRACT_MANUAL_NUM
 OR N.CUSTOMER_NUM<>T.CUSTOMER_NUM
 OR N.BIZ_NUM<>T.BIZ_NUM
 OR N.CREDIT_LIMIT_NUM<>T.CREDIT_LIMIT_NUM
 OR N.CONTRACT_SIGN_DATE<>T.CONTRACT_SIGN_DATE
 OR N.COMPR_BIZ_CONTRACT_IND<>T.COMPR_BIZ_CONTRACT_IND
 OR N.CREDIT_PRODUCT_CD<>T.CREDIT_PRODUCT_CD
 OR N.SUPER_CONTRACT_NUM<>T.SUPER_CONTRACT_NUM
 OR N.CURRENCY_CD<>T.CURRENCY_CD
 OR N.CONTRACT_TOTAL_AMT<>T.CONTRACT_TOTAL_AMT
 OR N.APPROVE_NUM<>T.APPROVE_NUM
 OR N.CONTRACT_TERM_UNIT_CD<>T.CONTRACT_TERM_UNIT_CD
 OR N.START_DATE<>T.START_DATE
 OR N.EXPIRATION_DATE<>T.EXPIRATION_DATE
 OR N.CONTRACT_TERM<>T.CONTRACT_TERM
 OR N.CONTRACT_LOAN_CD<>T.CONTRACT_LOAN_CD
 OR N.CONTRACT_PROVIDE_PURPOSE<>T.CONTRACT_PROVIDE_PURPOSE
 OR N.EXCHANGE_RATE<>T.EXCHANGE_RATE
 OR N.REMIT_P_SUM<>T.REMIT_P_SUM
 OR N.CONTRACT_TYPE_CD<>T.CONTRACT_TYPE_CD
 OR N.CONTRACT_NATURE_CD<>T.CONTRACT_NATURE_CD
 OR N.CONTRACT_STATUS_CD<>T.CONTRACT_STATUS_CD
 OR N.CONTRACT_TERMINATION_WAY_CD<>T.CONTRACT_TERMINATION_WAY_CD
 OR N.LOW_RISK_IND<>T.LOW_RISK_IND
 OR N.LOW_RISK_BIZ_TYPE_CD<>T.LOW_RISK_BIZ_TYPE_CD
 OR N.CONTRACT_CYCLE_IND<>T.CONTRACT_CYCLE_IND
 OR N.CONTRACT_TERMINATION_DATE<>T.CONTRACT_TERMINATION_DATE
 OR N.HANDLING_ORG_CD<>T.HANDLING_ORG_CD
 OR N.HANDLING_USER_NUM<>T.HANDLING_USER_NUM
 OR N.DISB_ORG_CD<>T.DISB_ORG_CD
 OR N.TRANSFERED_TO_WR_IND<>T.TRANSFERED_TO_WR_IND
 OR N.IF_CORP_HOUST_LOAN<>T.IF_CORP_HOUST_LOAN
 OR N.WR_ORG_CD<>T.WR_ORG_CD
 OR N.CLASSIFICATION_RESULT<>T.CLASSIFICATION_RESULT
 OR N.ORIGINAL_GUARANTY_CONTRACT_NUM<>T.ORIGINAL_GUARANTY_CONTRACT_NUM
 OR N.TOP_GUARANTY_IND<>T.TOP_GUARANTY_IND
 OR N.ORIGINAL_CONTRACT_MANUAL_NUM<>T.ORIGINAL_CONTRACT_MANUAL_NUM
 OR N.EXTEND_FIELD<>T.EXTEND_FIELD
 OR N.EXTEND_FLAG_FIELD<>T.EXTEND_FLAG_FIELD
 OR N.CREDIT_LIMIT_ID<>T.CREDIT_LIMIT_ID
 OR N.FREEZEN_IND<>T.FREEZEN_IND
 OR N.LC_NUM<>T.LC_NUM
 OR N.LAST_MAINTAIN_DATE<>T.LAST_MAINTAIN_DATE
 OR N.LOAN_TYPE_INSTRUCTION_CD<>T.LOAN_TYPE_INSTRUCTION_CD
 OR N.DEBT_REFORM_TYPE_CD<>T.DEBT_REFORM_TYPE_CD
 OR N.POST_PONEMENT_TYPE_CD<>T.POST_PONEMENT_TYPE_CD
 OR N.CONTRACT_SIGN_PLACE<>T.CONTRACT_SIGN_PLACE
 OR N.CONTRACT_OTHER_CONDITION<>T.CONTRACT_OTHER_CONDITION
 OR N.CONTRACT_SUPPLEMENT<>T.CONTRACT_SUPPLEMENT
 OR N.PAY_DISCOUNT_AMT<>T.PAY_DISCOUNT_AMT
 OR N.TOP_FINANCING_START_DATE<>T.TOP_FINANCING_START_DATE
 OR N.TOP_FINANCING_END_DATE<>T.TOP_FINANCING_END_DATE
 OR N.SHORT_OPERATION_MATURE_TERM<>T.SHORT_OPERATION_MATURE_TERM
 OR N.FIRST_PAY_START_TERM<>T.FIRST_PAY_START_TERM
 OR N.TIP_FINANCING_AMT_TERM<>T.TIP_FINANCING_AMT_TERM
 OR N.MAIN_SURETY_MODE<>T.MAIN_SURETY_MODE
 OR N.MAIN_SUERTY_SUBCHILD<>T.MAIN_SUERTY_SUBCHILD
 OR N.OTHER_BANK_SUERTY_MODE<>T.OTHER_BANK_SUERTY_MODE
 OR N.OTHER_BANK_SUERTY_SUBCHILD<>T.OTHER_BANK_SUERTY_SUBCHILD
 OR N.SUERTY_CD<>T.SUERTY_CD
 OR N.PREREQUISITION_COMMENT<>T.PREREQUISITION_COMMENT
 OR N.GUARANTY_NOTE<>T.GUARANTY_NOTE
 OR N.GUARANTY_TYPE<>T.GUARANTY_TYPE
 OR N.REPORT_SUERTY_MODE<>T.REPORT_SUERTY_MODE
 OR N.REPORT_SUERTY_SUBCHILD<>T.REPORT_SUERTY_SUBCHILD
 OR N.CONTRACT_CHANGE_IND<>T.CONTRACT_CHANGE_IND
 OR N.GUARANTY_RATE<>T.GUARANTY_RATE
 OR N.WIDTH_TERM<>T.WIDTH_TERM
 OR N.PROMISES_AMT<>T.PROMISES_AMT
 OR N.PROMISES_AMT_COLLECTION_TYPE<>T.PROMISES_AMT_COLLECTION_TYPE
 OR N.YH_CURRENCY_CD<>T.YH_CURRENCY_CD
 OR N.TERM_END_DATE<>T.TERM_END_DATE
 OR N.RELA_BIZ_NUM<>T.RELA_BIZ_NUM
 OR N.PAYOUT_APPROVE_LEVEL<>T.PAYOUT_APPROVE_LEVEL
 OR N.OLD_CONTRACT_DETAIL_ID<>T.OLD_CONTRACT_DETAIL_ID
 OR N.ORIGINAL_CONTRACT_EXP_DATE<>T.ORIGINAL_CONTRACT_EXP_DATE
 OR N.POSTPONEMENT_IND<>T.POSTPONEMENT_IND
 OR N.OLD_BIZ_DETAIL_ID<>T.OLD_BIZ_DETAIL_ID
 OR N.IF_PERSONAL_LOAN_IND<>T.IF_PERSONAL_LOAN_IND
 OR N.CON_HOUSE_MANUAL_NUM<>T.CON_HOUSE_MANUAL_NUM
 OR N.APPROVE_USER<>T.APPROVE_USER
 OR N.APPROVE_ORG<>T.APPROVE_ORG
 OR N.POST_PONEMENT_CAUSATION<>T.POST_PONEMENT_CAUSATION
 OR N.LOAN_ACCOUNTS<>T.LOAN_ACCOUNTS
 OR N.DEDUCTLOAN_ACCOUNTS<>T.DEDUCTLOAN_ACCOUNTS
 OR N.LOAN_CLASS<>T.LOAN_CLASS
 OR N.GOV_RELATION_TPYE_CD<>T.GOV_RELATION_TPYE_CD
 OR N.GOV_RELATION_WITH_ORGTYPELV<>T.GOV_RELATION_WITH_ORGTYPELV
 OR N.TIME_MARK<>T.TIME_MARK
 OR N.FOURCLASSIFY_CD<>T.FOURCLASSIFY_CD
 OR N.LOAN_TERM<>T.LOAN_TERM
 OR N.CORE_CONTRACT_CD<>T.CORE_CONTRACT_CD
 OR N.LOAN_TYPE_INSTRUCT_DETAIL_CD<>T.LOAN_TYPE_INSTRUCT_DETAIL_CD
 OR N.CONTRACT_NAME<>T.CONTRACT_NAME
 OR N.CONTRACT_BIG<>T.CONTRACT_BIG
 OR N.CONTRACT_SMALL<>T.CONTRACT_SMALL
 OR N.HANDING_USER_DEP<>T.HANDING_USER_DEP
 OR N.OFFEND_DUTY<>T.OFFEND_DUTY
 OR N.SEARCH_AREA<>T.SEARCH_AREA
 OR N.CONTRACT_PAGE<>T.CONTRACT_PAGE
 OR N.CONTRACT_VALID_DAYS<>T.CONTRACT_VALID_DAYS
 OR N.TRANSACT_DATE<>T.TRANSACT_DATE
 OR N.BANK_GROUP_STYLE<>T.BANK_GROUP_STYLE
 OR N.MY_BANK_CONSENT_SUM<>T.MY_BANK_CONSENT_SUM
 OR N.MY_BANK_CONSENT_SCALE<>T.MY_BANK_CONSENT_SCALE
 OR N.LIMIT_LOW_BALANCE<>T.LIMIT_LOW_BALANCE
 OR N.LIMIT_CHANGE_UNIT<>T.LIMIT_CHANGE_UNIT
 OR N.LIMIT_CHANGE_FAITH<>T.LIMIT_CHANGE_FAITH
 OR N.LIMIT_CHANGE_APP_DES<>T.LIMIT_CHANGE_APP_DES
 OR N.BORROW_ALL_NAME<>T.BORROW_ALL_NAME
 OR N.PLAN_OLD_CONTRACT_NUM<>T.PLAN_OLD_CONTRACT_NUM
 OR N.OLD_SIGN_DATE<>T.OLD_SIGN_DATE
 OR N.OLD_CONTRACT_SUM<>T.OLD_CONTRACT_SUM
 OR N.OLD_START_DATE<>T.OLD_START_DATE
 OR N.OLD_END_DATE<>T.OLD_END_DATE
 OR N.OLD_GUARANTEE_CONTRACT_NUM<>T.OLD_GUARANTEE_CONTRACT_NUM
 OR N.OLD_GUARANTEE_SIGN_DATE<>T.OLD_GUARANTEE_SIGN_DATE
 OR N.GUARANTEER<>T.GUARANTEER
 OR N.FARM_SUM<>T.FARM_SUM
 OR N.FARM_DES<>T.FARM_DES
 OR N.BACK_DAYS<>T.BACK_DAYS
 OR N.BUY_NAME<>T.BUY_NAME
 OR N.BUY_CREDIT_SUM<>T.BUY_CREDIT_SUM
 OR N.PUBLIC_OBJECT_NAME<>T.PUBLIC_OBJECT_NAME
 OR N.IS_LOAN_FIRST_CHECK<>T.IS_LOAN_FIRST_CHECK
 OR N.PARTY_ID<>T.PARTY_ID
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.BANKROLL_POOL_KIND<>T.BANKROLL_POOL_KIND
 OR N.IF_LOAN_CONTRACT<>T.IF_LOAN_CONTRACT
 OR N.CLASS_LEVEL<>T.CLASS_LEVEL
 OR N.TERM_CHANGE_TIME<>T.TERM_CHANGE_TIME
 OR N.ENTRY_SFD_STATUS_CD<>T.ENTRY_SFD_STATUS_CD
 OR N.LOAN_USE_CD<>T.LOAN_USE_CD
 OR N.LOAN_USE_SUB_CD<>T.LOAN_USE_SUB_CD
 OR N.RESOLVE_DISPUTED_PLACE<>T.RESOLVE_DISPUTED_PLACE
 OR N.LOAN_PURPOSE<>T.LOAN_PURPOSE
 OR N.BANK_GROUP_CREDIT_LOAN_IND<>T.BANK_GROUP_CREDIT_LOAN_IND
 OR N.IS_TERM_BANKGROUP_FRAME<>T.IS_TERM_BANKGROUP_FRAME
 OR N.IF_PART_TIME_AGENTS<>T.IF_PART_TIME_AGENTS
 OR N.SYNDICATED_DISTRIB<>T.SYNDICATED_DISTRIB
 OR N.ASSETS_TYPE_CD<>T.ASSETS_TYPE_CD
 OR N.TERM_STATE<>T.TERM_STATE
 OR N.IF_LOANS_TERM<>T.IF_LOANS_TERM
 OR N.LOANS_TERM<>T.LOANS_TERM
 OR N.LOANS_START_DATE<>T.LOANS_START_DATE
 OR N.LOANS_END_DATE<>T.LOANS_END_DATE
 OR N.LOANS_TERM_STATE<>T.LOANS_TERM_STATE
 OR N.EXTEND_TERM<>T.EXTEND_TERM
 OR N.EXTEND_START_DATE<>T.EXTEND_START_DATE
 OR N.EXTEND_END_DATE<>T.EXTEND_END_DATE
 OR N.EXTEND_TERM_STATE<>T.EXTEND_TERM_STATE
 OR N.IF_EXTEND_TERM<>T.IF_EXTEND_TERM
 OR N.IF_CHANGE_GRT_IND<>T.IF_CHANGE_GRT_IND
 OR N.IF_DIVISION_GUARANTEE<>T.IF_DIVISION_GUARANTEE
 OR N.IF_ASSETS_TRANSFER<>T.IF_ASSETS_TRANSFER
 OR N.TRANSFER_TYPE_CD<>T.TRANSFER_TYPE_CD
 OR N.TRANSFER_WAY_CD<>T.TRANSFER_WAY_CD
 OR N.BUYOUT_TYPE_CD<>T.BUYOUT_TYPE_CD
 OR N.REPAY_RESOURCE<>T.REPAY_RESOURCE
 OR N.IF_TRADE<>T.IF_TRADE
 OR N.FSE_SF<>T.FSE_SF
 OR N.FLAG<>T.FLAG
 OR N.IF_FINANCING<>T.IF_FINANCING
 OR N.PAY_TYPE_CD<>T.PAY_TYPE_CD
 OR N.TOP_PLEDGE_RATE<>T.TOP_PLEDGE_RATE
 OR N.PLEDGE_WAREHOUSING_CD<>T.PLEDGE_WAREHOUSING_CD
 OR N.NET_SCHEME_ID<>T.NET_SCHEME_ID
 OR N.FINANCING_MODEL<>T.FINANCING_MODEL
 OR N.BDC_DUTY_CD<>T.BDC_DUTY_CD
 OR N.ESTATE_LOAN_CD1<>T.ESTATE_LOAN_CD1
 OR N.ESTATE_LOAN_CD_NAME1<>T.ESTATE_LOAN_CD_NAME1
 OR N.ESTATE_LOAN_CD2<>T.ESTATE_LOAN_CD2
 OR N.ESTATE_LOAN_CD_NAME2<>T.ESTATE_LOAN_CD_NAME2
 OR N.ESTATE_LOAN_CD3<>T.ESTATE_LOAN_CD3
 OR N.ESTATE_LOAN_CD_NAME3<>T.ESTATE_LOAN_CD_NAME3
 OR N.ESTATE_LOAN_CD4<>T.ESTATE_LOAN_CD4
 OR N.ESTATE_LOAN_CD_NAME4<>T.ESTATE_LOAN_CD_NAME4
 OR N.ESTATE_LOAN_CD5<>T.ESTATE_LOAN_CD5
 OR N.ESTATE_LOAN_CD_NAME5<>T.ESTATE_LOAN_CD_NAME5
 OR N.ESTATE_LOAN_CD6<>T.ESTATE_LOAN_CD6
 OR N.ESTATE_LOAN_CD_NAME6<>T.ESTATE_LOAN_CD_NAME6
 OR N.ESTATE_LOAN_CD7<>T.ESTATE_LOAN_CD7
 OR N.ESTATE_LOAN_CD_NAME7<>T.ESTATE_LOAN_CD_NAME7
 OR N.POSTPONEMENT_NUM<>T.POSTPONEMENT_NUM
 OR N.TRANSFER_ASSET_TYPE<>T.TRANSFER_ASSET_TYPE
 OR N.ORGANIZATION_MODE<>T.ORGANIZATION_MODE
 OR N.APPLY_MODE_CODE<>T.APPLY_MODE_CODE
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.DIRECT_TO_INTERNAL_FLAG<>T.DIRECT_TO_INTERNAL_FLAG
 OR N.IS_RENEW<>T.IS_RENEW
 OR N.CONTINUE_OVERDRAFT_TERM<>T.CONTINUE_OVERDRAFT_TERM
 OR N.REVERT_EXTEND_TERM<>T.REVERT_EXTEND_TERM
 OR N.EMPLOY_CONTRACT_LIMIT<>T.EMPLOY_CONTRACT_LIMIT
 OR N.CONTINUE_CONTRACT_LIMIT<>T.CONTINUE_CONTRACT_LIMIT
 OR N.START_EMPLOY_CONTRACT_LIMIT<>T.START_EMPLOY_CONTRACT_LIMIT
 OR N.END_EMPLOY_CONTRACT_LIMIT<>T.END_EMPLOY_CONTRACT_LIMIT
 OR N.START_CONTINUE_CONTRACT_LIMIT<>T.START_CONTINUE_CONTRACT_LIMIT
 OR N.END_CONTINUE_CONTRACT_LIMIT<>T.END_CONTINUE_CONTRACT_LIMIT
 OR N.REVERT_PLANNING<>T.REVERT_PLANNING
 OR N.IF_REVERT_PLANNING<>T.IF_REVERT_PLANNING
 OR N.CON_TEXT_TYPE<>T.CON_TEXT_TYPE
 OR N.IF_STAIR_BRANCH_LAW_CHECK<>T.IF_STAIR_BRANCH_LAW_CHECK
 OR N.IF_HEAD_BANK_LAW_CHECK<>T.IF_HEAD_BANK_LAW_CHECK
 OR N.CON_TEXT_PROPER<>T.CON_TEXT_PROPER
 OR N.GUARANTEE_TEST_UNANIMOUS<>T.GUARANTEE_TEST_UNANIMOUS
 OR N.EXAMINE_PRACTICABLE<>T.EXAMINE_PRACTICABLE
 OR N.CON_MESSAGE_UNANIMOUS<>T.CON_MESSAGE_UNANIMOUS
 OR N.CON_WRITE_NORM<>T.CON_WRITE_NORM
 OR N.CON_PRACTICABLE_LAW<>T.CON_PRACTICABLE_LAW
 OR N.BEFORE_CLASS_MODE<>T.BEFORE_CLASS_MODE
 OR N.BEFORE_CLASS_GRADE<>T.BEFORE_CLASS_GRADE
 OR N.BEFORE_CLASS_TIME<>T.BEFORE_CLASS_TIME
 OR N.IF_EJD_LOAN<>T.IF_EJD_LOAN
 OR N.EJD_CREDIT_NUM<>T.EJD_CREDIT_NUM
 OR N.ZCYL_BIZ_NUM<>T.ZCYL_BIZ_NUM
 OR N.CLOUD_BUSINESS<>T.CLOUD_BUSINESS
 OR N.EJD_ID<>T.EJD_ID
 OR N.YLD_BIZ_INFO_NUM<>T.YLD_BIZ_INFO_NUM
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_CON_CONTRACT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_110
WHERE P.End_Dt=DATE('2100-12-31')
AND P.CONTRACT_ID=T_110.CONTRACT_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_CON_CONTRACT SELECT * FROM T_110;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
