#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_109 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY WHERE 1=0;

--Step2:
INSERT  INTO T_109 (
  PAYOUT_ACCT_SUMMARY_ID,
  PAYOUT_APP_FORM_NUM,
  BORROW_NUM,
  CONTRACT_NUM,
  CUSTOMER_NUM,
  EXPIRATION_DATE,
  CREDIT_BALANCE,
  LOAN_BALANCE,
  INTEREST_RATE,
  DISCOUNT_SIGN,
  BANK_GUARANTEE_TYPE,
  BANK_GUARANTEE_STATE,
  REFUND_SUM,
  RE_SPONSION_WITHDRAWAL_SUM,
  POSTAL_ORDER_STATE,
  UNDERTAKE_PAY_SUM,
  UNTREAD_SUM,
  BAIL_ACCOUNTS,
  BAIL_SUM,
  COMMISSION_CHARGE_RATIO,
  THIS_YEAR_TOTAL_REQUITAL,
  LAST_YEAR_TOTAL_REQUITAL,
  TOTAL_SHOULD_ACCRUAL,
  TOTAL_FACT_ACCRUAL,
  IN_OWE_ACCOUNTS,
  OUT_OWE_ACCOUNTS,
  TOTAL_EXPIRATION_CORPUS,
  TOTAL_EXP_IN_OWE_ACCOUNTS,
  TOTAL_EXP_OUT_OWE_ACCOUNTS,
  TOTAL_OVDUE_SUM,
  TOTAL_PRIMNESS_SUM,
  TOTAL_BAD_DEBT_SUM,
  ADD_PERIOD_DATE,
  FIRST_OVDUE_DATE,
  FIRST_PRIMNESS_DATE,
  FIRST_BAD_DEBT_DATE,
  BALANCE_ACCOUNTS,
  IN_GEAR_ACCOUNTS,
  ADD_PERIOD_ACCOUNTS,
  OVDUE_ACCOUNTS,
  PRIMNESS_ACCOUNTS,
  BAD_DEBT_ACCOUNTS,
  FOUR_SORT,
  REC_STATE,
  OLD_CONTRACT_NUM,
  LAST_MAINTAIN_DATE,
  CURRENCY_CD,
  WRITE_OFF_DATE,
  PAYOUT_INFO_DETAIL_ID,
  IN_GEAR_BALANCE,
  OVERDUE_BALANCE,
  PRIMNESS_BALANCE,
  BAD_DEBT_BALANCE,
  EXPIRATION_BALANCE,
  LAST_REQUITAL_SUM,
  CLASSIFICATION_RESULT,
  REPLACEMENT_SIGN,
  ENTER_ACCOUNTS_ORGAN,
  EXPIRATION_ACCOUNTS,
  REPLACEMENT_ACCOUNTS,
  REPLACEMENT_BALANCE,
  FINANCING_IND,
  LETTER_OF_CREDIT_STATE,
  TIME_MARK,
  EXTEND_DATE,
  CORPUS_EXP_START_DATE,
  ACCRUAL_EXP_START_DATE,
  INFRACT_NUMBER,
  CUSTOMER_NAME,
  BORROW_TYPE,
  ADD_PERIOD_BORROW_STATUS,
  ADD_PERIOD_TIME,
  TERM,
  PAYOUT_NOTICE_NUM,
  LAST_OVDUE_DATE,
  MAX_OVDUE_DAYS,
  LAST_OVDUE_DAYS,
  OLD_SUM_OVDUE_DAYS,
  IS_STOP_INTEREST,
  FXBS_TIME_MARK,
  BANK_GROUP_TOTAL_AMT,
  BANK_GROUP_TOTAL_AMT_BALANCE,
  OWE_CORPUS_AMT,
  OWE_CORPUS_DATE,
  OWE_CORPUS_DAYS,
  OWE_ACCRUAL_AMT,
  OWE_ACCRUAL_DATE,
  OWE_ACCRUAL_DAYS,
  start_dt,
  end_dt)
SELECT
  N.PAYOUT_ACCT_SUMMARY_ID,
  N.PAYOUT_APP_FORM_NUM,
  N.BORROW_NUM,
  N.CONTRACT_NUM,
  N.CUSTOMER_NUM,
  N.EXPIRATION_DATE,
  N.CREDIT_BALANCE,
  N.LOAN_BALANCE,
  N.INTEREST_RATE,
  N.DISCOUNT_SIGN,
  N.BANK_GUARANTEE_TYPE,
  N.BANK_GUARANTEE_STATE,
  N.REFUND_SUM,
  N.RE_SPONSION_WITHDRAWAL_SUM,
  N.POSTAL_ORDER_STATE,
  N.UNDERTAKE_PAY_SUM,
  N.UNTREAD_SUM,
  N.BAIL_ACCOUNTS,
  N.BAIL_SUM,
  N.COMMISSION_CHARGE_RATIO,
  N.THIS_YEAR_TOTAL_REQUITAL,
  N.LAST_YEAR_TOTAL_REQUITAL,
  N.TOTAL_SHOULD_ACCRUAL,
  N.TOTAL_FACT_ACCRUAL,
  N.IN_OWE_ACCOUNTS,
  N.OUT_OWE_ACCOUNTS,
  N.TOTAL_EXPIRATION_CORPUS,
  N.TOTAL_EXP_IN_OWE_ACCOUNTS,
  N.TOTAL_EXP_OUT_OWE_ACCOUNTS,
  N.TOTAL_OVDUE_SUM,
  N.TOTAL_PRIMNESS_SUM,
  N.TOTAL_BAD_DEBT_SUM,
  N.ADD_PERIOD_DATE,
  N.FIRST_OVDUE_DATE,
  N.FIRST_PRIMNESS_DATE,
  N.FIRST_BAD_DEBT_DATE,
  N.BALANCE_ACCOUNTS,
  N.IN_GEAR_ACCOUNTS,
  N.ADD_PERIOD_ACCOUNTS,
  N.OVDUE_ACCOUNTS,
  N.PRIMNESS_ACCOUNTS,
  N.BAD_DEBT_ACCOUNTS,
  N.FOUR_SORT,
  N.REC_STATE,
  N.OLD_CONTRACT_NUM,
  N.LAST_MAINTAIN_DATE,
  N.CURRENCY_CD,
  N.WRITE_OFF_DATE,
  N.PAYOUT_INFO_DETAIL_ID,
  N.IN_GEAR_BALANCE,
  N.OVERDUE_BALANCE,
  N.PRIMNESS_BALANCE,
  N.BAD_DEBT_BALANCE,
  N.EXPIRATION_BALANCE,
  N.LAST_REQUITAL_SUM,
  N.CLASSIFICATION_RESULT,
  N.REPLACEMENT_SIGN,
  N.ENTER_ACCOUNTS_ORGAN,
  N.EXPIRATION_ACCOUNTS,
  N.REPLACEMENT_ACCOUNTS,
  N.REPLACEMENT_BALANCE,
  N.FINANCING_IND,
  N.LETTER_OF_CREDIT_STATE,
  N.TIME_MARK,
  N.EXTEND_DATE,
  N.CORPUS_EXP_START_DATE,
  N.ACCRUAL_EXP_START_DATE,
  N.INFRACT_NUMBER,
  N.CUSTOMER_NAME,
  N.BORROW_TYPE,
  N.ADD_PERIOD_BORROW_STATUS,
  N.ADD_PERIOD_TIME,
  N.TERM,
  N.PAYOUT_NOTICE_NUM,
  N.LAST_OVDUE_DATE,
  N.MAX_OVDUE_DAYS,
  N.LAST_OVDUE_DAYS,
  N.OLD_SUM_OVDUE_DAYS,
  N.IS_STOP_INTEREST,
  N.FXBS_TIME_MARK,
  N.BANK_GROUP_TOTAL_AMT,
  N.BANK_GROUP_TOTAL_AMT_BALANCE,
  N.OWE_CORPUS_AMT,
  N.OWE_CORPUS_DATE,
  N.OWE_CORPUS_DAYS,
  N.OWE_ACCRUAL_AMT,
  N.OWE_ACCRUAL_DATE,
  N.OWE_ACCRUAL_DAYS,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PAYOUT_ACCT_SUMMARY_ID, '' ) AS PAYOUT_ACCT_SUMMARY_ID ,
  COALESCE(PAYOUT_APP_FORM_NUM, '' ) AS PAYOUT_APP_FORM_NUM ,
  COALESCE(BORROW_NUM, '' ) AS BORROW_NUM ,
  COALESCE(CONTRACT_NUM, '' ) AS CONTRACT_NUM ,
  COALESCE(CUSTOMER_NUM, '' ) AS CUSTOMER_NUM ,
  COALESCE(EXPIRATION_DATE,'4999-12-31 00:00:00' ) AS EXPIRATION_DATE ,
  COALESCE(CREDIT_BALANCE, 0 ) AS CREDIT_BALANCE ,
  COALESCE(LOAN_BALANCE, 0 ) AS LOAN_BALANCE ,
  COALESCE(INTEREST_RATE, 0 ) AS INTEREST_RATE ,
  COALESCE(DISCOUNT_SIGN, '' ) AS DISCOUNT_SIGN ,
  COALESCE(BANK_GUARANTEE_TYPE, '' ) AS BANK_GUARANTEE_TYPE ,
  COALESCE(BANK_GUARANTEE_STATE, '' ) AS BANK_GUARANTEE_STATE ,
  COALESCE(REFUND_SUM, 0 ) AS REFUND_SUM ,
  COALESCE(RE_SPONSION_WITHDRAWAL_SUM, 0 ) AS RE_SPONSION_WITHDRAWAL_SUM ,
  COALESCE(POSTAL_ORDER_STATE, '' ) AS POSTAL_ORDER_STATE ,
  COALESCE(UNDERTAKE_PAY_SUM, 0 ) AS UNDERTAKE_PAY_SUM ,
  COALESCE(UNTREAD_SUM, 0 ) AS UNTREAD_SUM ,
  COALESCE(BAIL_ACCOUNTS, '' ) AS BAIL_ACCOUNTS ,
  COALESCE(BAIL_SUM, 0 ) AS BAIL_SUM ,
  COALESCE(COMMISSION_CHARGE_RATIO, 0 ) AS COMMISSION_CHARGE_RATIO ,
  COALESCE(THIS_YEAR_TOTAL_REQUITAL, 0 ) AS THIS_YEAR_TOTAL_REQUITAL ,
  COALESCE(LAST_YEAR_TOTAL_REQUITAL, 0 ) AS LAST_YEAR_TOTAL_REQUITAL ,
  COALESCE(TOTAL_SHOULD_ACCRUAL, 0 ) AS TOTAL_SHOULD_ACCRUAL ,
  COALESCE(TOTAL_FACT_ACCRUAL, 0 ) AS TOTAL_FACT_ACCRUAL ,
  COALESCE(IN_OWE_ACCOUNTS, 0 ) AS IN_OWE_ACCOUNTS ,
  COALESCE(OUT_OWE_ACCOUNTS, 0 ) AS OUT_OWE_ACCOUNTS ,
  COALESCE(TOTAL_EXPIRATION_CORPUS, 0 ) AS TOTAL_EXPIRATION_CORPUS ,
  COALESCE(TOTAL_EXP_IN_OWE_ACCOUNTS, 0 ) AS TOTAL_EXP_IN_OWE_ACCOUNTS ,
  COALESCE(TOTAL_EXP_OUT_OWE_ACCOUNTS, 0 ) AS TOTAL_EXP_OUT_OWE_ACCOUNTS ,
  COALESCE(TOTAL_OVDUE_SUM, 0 ) AS TOTAL_OVDUE_SUM ,
  COALESCE(TOTAL_PRIMNESS_SUM, 0 ) AS TOTAL_PRIMNESS_SUM ,
  COALESCE(TOTAL_BAD_DEBT_SUM, 0 ) AS TOTAL_BAD_DEBT_SUM ,
  COALESCE(ADD_PERIOD_DATE,'4999-12-31 00:00:00' ) AS ADD_PERIOD_DATE ,
  COALESCE(FIRST_OVDUE_DATE,'4999-12-31 00:00:00' ) AS FIRST_OVDUE_DATE ,
  COALESCE(FIRST_PRIMNESS_DATE,'4999-12-31 00:00:00' ) AS FIRST_PRIMNESS_DATE ,
  COALESCE(FIRST_BAD_DEBT_DATE,'4999-12-31 00:00:00' ) AS FIRST_BAD_DEBT_DATE ,
  COALESCE(BALANCE_ACCOUNTS, '' ) AS BALANCE_ACCOUNTS ,
  COALESCE(IN_GEAR_ACCOUNTS, '' ) AS IN_GEAR_ACCOUNTS ,
  COALESCE(ADD_PERIOD_ACCOUNTS, '' ) AS ADD_PERIOD_ACCOUNTS ,
  COALESCE(OVDUE_ACCOUNTS, '' ) AS OVDUE_ACCOUNTS ,
  COALESCE(PRIMNESS_ACCOUNTS, '' ) AS PRIMNESS_ACCOUNTS ,
  COALESCE(BAD_DEBT_ACCOUNTS, '' ) AS BAD_DEBT_ACCOUNTS ,
  COALESCE(FOUR_SORT, '' ) AS FOUR_SORT ,
  COALESCE(REC_STATE, '' ) AS REC_STATE ,
  COALESCE(OLD_CONTRACT_NUM, '' ) AS OLD_CONTRACT_NUM ,
  COALESCE(LAST_MAINTAIN_DATE,'4999-12-31 00:00:00' ) AS LAST_MAINTAIN_DATE ,
  COALESCE(CURRENCY_CD, '' ) AS CURRENCY_CD ,
  COALESCE(WRITE_OFF_DATE,'4999-12-31 00:00:00' ) AS WRITE_OFF_DATE ,
  COALESCE(PAYOUT_INFO_DETAIL_ID, '' ) AS PAYOUT_INFO_DETAIL_ID ,
  COALESCE(IN_GEAR_BALANCE, 0 ) AS IN_GEAR_BALANCE ,
  COALESCE(OVERDUE_BALANCE, 0 ) AS OVERDUE_BALANCE ,
  COALESCE(PRIMNESS_BALANCE, 0 ) AS PRIMNESS_BALANCE ,
  COALESCE(BAD_DEBT_BALANCE, 0 ) AS BAD_DEBT_BALANCE ,
  COALESCE(EXPIRATION_BALANCE, 0 ) AS EXPIRATION_BALANCE ,
  COALESCE(LAST_REQUITAL_SUM, 0 ) AS LAST_REQUITAL_SUM ,
  COALESCE(CLASSIFICATION_RESULT, '' ) AS CLASSIFICATION_RESULT ,
  COALESCE(REPLACEMENT_SIGN, '' ) AS REPLACEMENT_SIGN ,
  COALESCE(ENTER_ACCOUNTS_ORGAN, '' ) AS ENTER_ACCOUNTS_ORGAN ,
  COALESCE(EXPIRATION_ACCOUNTS, '' ) AS EXPIRATION_ACCOUNTS ,
  COALESCE(REPLACEMENT_ACCOUNTS, '' ) AS REPLACEMENT_ACCOUNTS ,
  COALESCE(REPLACEMENT_BALANCE, 0 ) AS REPLACEMENT_BALANCE ,
  COALESCE(FINANCING_IND, '' ) AS FINANCING_IND ,
  COALESCE(LETTER_OF_CREDIT_STATE, '' ) AS LETTER_OF_CREDIT_STATE ,
  COALESCE(TIME_MARK,'4999-12-31 00:00:00' ) AS TIME_MARK ,
  COALESCE(EXTEND_DATE,'4999-12-31 00:00:00' ) AS EXTEND_DATE ,
  COALESCE(CORPUS_EXP_START_DATE,'4999-12-31 00:00:00' ) AS CORPUS_EXP_START_DATE ,
  COALESCE(ACCRUAL_EXP_START_DATE,'4999-12-31 00:00:00' ) AS ACCRUAL_EXP_START_DATE ,
  COALESCE(INFRACT_NUMBER, 0 ) AS INFRACT_NUMBER ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(BORROW_TYPE, '' ) AS BORROW_TYPE ,
  COALESCE(ADD_PERIOD_BORROW_STATUS, '' ) AS ADD_PERIOD_BORROW_STATUS ,
  COALESCE(ADD_PERIOD_TIME, 0 ) AS ADD_PERIOD_TIME ,
  COALESCE(TERM, 0 ) AS TERM ,
  COALESCE(PAYOUT_NOTICE_NUM, '' ) AS PAYOUT_NOTICE_NUM ,
  COALESCE(LAST_OVDUE_DATE,'4999-12-31 00:00:00' ) AS LAST_OVDUE_DATE ,
  COALESCE(MAX_OVDUE_DAYS, 0 ) AS MAX_OVDUE_DAYS ,
  COALESCE(LAST_OVDUE_DAYS, 0 ) AS LAST_OVDUE_DAYS ,
  COALESCE(OLD_SUM_OVDUE_DAYS, 0 ) AS OLD_SUM_OVDUE_DAYS ,
  COALESCE(IS_STOP_INTEREST, '' ) AS IS_STOP_INTEREST ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(BANK_GROUP_TOTAL_AMT, 0 ) AS BANK_GROUP_TOTAL_AMT ,
  COALESCE(BANK_GROUP_TOTAL_AMT_BALANCE, 0 ) AS BANK_GROUP_TOTAL_AMT_BALANCE ,
  COALESCE(OWE_CORPUS_AMT, 0 ) AS OWE_CORPUS_AMT ,
  COALESCE(OWE_CORPUS_DATE,'4999-12-31 00:00:00' ) AS OWE_CORPUS_DATE ,
  COALESCE(OWE_CORPUS_DAYS, 0 ) AS OWE_CORPUS_DAYS ,
  COALESCE(OWE_ACCRUAL_AMT, 0 ) AS OWE_ACCRUAL_AMT ,
  COALESCE(OWE_ACCRUAL_DATE,'4999-12-31 00:00:00' ) AS OWE_ACCRUAL_DATE ,
  COALESCE(OWE_ACCRUAL_DAYS, 0 ) AS OWE_ACCRUAL_DAYS 
 FROM  dw_tdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PAYOUT_ACCT_SUMMARY_ID ,
  PAYOUT_APP_FORM_NUM ,
  BORROW_NUM ,
  CONTRACT_NUM ,
  CUSTOMER_NUM ,
  EXPIRATION_DATE ,
  CREDIT_BALANCE ,
  LOAN_BALANCE ,
  INTEREST_RATE ,
  DISCOUNT_SIGN ,
  BANK_GUARANTEE_TYPE ,
  BANK_GUARANTEE_STATE ,
  REFUND_SUM ,
  RE_SPONSION_WITHDRAWAL_SUM ,
  POSTAL_ORDER_STATE ,
  UNDERTAKE_PAY_SUM ,
  UNTREAD_SUM ,
  BAIL_ACCOUNTS ,
  BAIL_SUM ,
  COMMISSION_CHARGE_RATIO ,
  THIS_YEAR_TOTAL_REQUITAL ,
  LAST_YEAR_TOTAL_REQUITAL ,
  TOTAL_SHOULD_ACCRUAL ,
  TOTAL_FACT_ACCRUAL ,
  IN_OWE_ACCOUNTS ,
  OUT_OWE_ACCOUNTS ,
  TOTAL_EXPIRATION_CORPUS ,
  TOTAL_EXP_IN_OWE_ACCOUNTS ,
  TOTAL_EXP_OUT_OWE_ACCOUNTS ,
  TOTAL_OVDUE_SUM ,
  TOTAL_PRIMNESS_SUM ,
  TOTAL_BAD_DEBT_SUM ,
  ADD_PERIOD_DATE ,
  FIRST_OVDUE_DATE ,
  FIRST_PRIMNESS_DATE ,
  FIRST_BAD_DEBT_DATE ,
  BALANCE_ACCOUNTS ,
  IN_GEAR_ACCOUNTS ,
  ADD_PERIOD_ACCOUNTS ,
  OVDUE_ACCOUNTS ,
  PRIMNESS_ACCOUNTS ,
  BAD_DEBT_ACCOUNTS ,
  FOUR_SORT ,
  REC_STATE ,
  OLD_CONTRACT_NUM ,
  LAST_MAINTAIN_DATE ,
  CURRENCY_CD ,
  WRITE_OFF_DATE ,
  PAYOUT_INFO_DETAIL_ID ,
  IN_GEAR_BALANCE ,
  OVERDUE_BALANCE ,
  PRIMNESS_BALANCE ,
  BAD_DEBT_BALANCE ,
  EXPIRATION_BALANCE ,
  LAST_REQUITAL_SUM ,
  CLASSIFICATION_RESULT ,
  REPLACEMENT_SIGN ,
  ENTER_ACCOUNTS_ORGAN ,
  EXPIRATION_ACCOUNTS ,
  REPLACEMENT_ACCOUNTS ,
  REPLACEMENT_BALANCE ,
  FINANCING_IND ,
  LETTER_OF_CREDIT_STATE ,
  TIME_MARK ,
  EXTEND_DATE ,
  CORPUS_EXP_START_DATE ,
  ACCRUAL_EXP_START_DATE ,
  INFRACT_NUMBER ,
  CUSTOMER_NAME ,
  BORROW_TYPE ,
  ADD_PERIOD_BORROW_STATUS ,
  ADD_PERIOD_TIME ,
  TERM ,
  PAYOUT_NOTICE_NUM ,
  LAST_OVDUE_DATE ,
  MAX_OVDUE_DAYS ,
  LAST_OVDUE_DAYS ,
  OLD_SUM_OVDUE_DAYS ,
  IS_STOP_INTEREST ,
  FXBS_TIME_MARK ,
  BANK_GROUP_TOTAL_AMT ,
  BANK_GROUP_TOTAL_AMT_BALANCE ,
  OWE_CORPUS_AMT ,
  OWE_CORPUS_DATE ,
  OWE_CORPUS_DAYS ,
  OWE_ACCRUAL_AMT ,
  OWE_ACCRUAL_DATE ,
  OWE_ACCRUAL_DAYS 
 FROM dw_sdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.PAYOUT_ACCT_SUMMARY_ID = T.PAYOUT_ACCT_SUMMARY_ID
WHERE
(T.PAYOUT_ACCT_SUMMARY_ID IS NULL)
 OR N.PAYOUT_APP_FORM_NUM<>T.PAYOUT_APP_FORM_NUM
 OR N.BORROW_NUM<>T.BORROW_NUM
 OR N.CONTRACT_NUM<>T.CONTRACT_NUM
 OR N.CUSTOMER_NUM<>T.CUSTOMER_NUM
 OR N.EXPIRATION_DATE<>T.EXPIRATION_DATE
 OR N.CREDIT_BALANCE<>T.CREDIT_BALANCE
 OR N.LOAN_BALANCE<>T.LOAN_BALANCE
 OR N.INTEREST_RATE<>T.INTEREST_RATE
 OR N.DISCOUNT_SIGN<>T.DISCOUNT_SIGN
 OR N.BANK_GUARANTEE_TYPE<>T.BANK_GUARANTEE_TYPE
 OR N.BANK_GUARANTEE_STATE<>T.BANK_GUARANTEE_STATE
 OR N.REFUND_SUM<>T.REFUND_SUM
 OR N.RE_SPONSION_WITHDRAWAL_SUM<>T.RE_SPONSION_WITHDRAWAL_SUM
 OR N.POSTAL_ORDER_STATE<>T.POSTAL_ORDER_STATE
 OR N.UNDERTAKE_PAY_SUM<>T.UNDERTAKE_PAY_SUM
 OR N.UNTREAD_SUM<>T.UNTREAD_SUM
 OR N.BAIL_ACCOUNTS<>T.BAIL_ACCOUNTS
 OR N.BAIL_SUM<>T.BAIL_SUM
 OR N.COMMISSION_CHARGE_RATIO<>T.COMMISSION_CHARGE_RATIO
 OR N.THIS_YEAR_TOTAL_REQUITAL<>T.THIS_YEAR_TOTAL_REQUITAL
 OR N.LAST_YEAR_TOTAL_REQUITAL<>T.LAST_YEAR_TOTAL_REQUITAL
 OR N.TOTAL_SHOULD_ACCRUAL<>T.TOTAL_SHOULD_ACCRUAL
 OR N.TOTAL_FACT_ACCRUAL<>T.TOTAL_FACT_ACCRUAL
 OR N.IN_OWE_ACCOUNTS<>T.IN_OWE_ACCOUNTS
 OR N.OUT_OWE_ACCOUNTS<>T.OUT_OWE_ACCOUNTS
 OR N.TOTAL_EXPIRATION_CORPUS<>T.TOTAL_EXPIRATION_CORPUS
 OR N.TOTAL_EXP_IN_OWE_ACCOUNTS<>T.TOTAL_EXP_IN_OWE_ACCOUNTS
 OR N.TOTAL_EXP_OUT_OWE_ACCOUNTS<>T.TOTAL_EXP_OUT_OWE_ACCOUNTS
 OR N.TOTAL_OVDUE_SUM<>T.TOTAL_OVDUE_SUM
 OR N.TOTAL_PRIMNESS_SUM<>T.TOTAL_PRIMNESS_SUM
 OR N.TOTAL_BAD_DEBT_SUM<>T.TOTAL_BAD_DEBT_SUM
 OR N.ADD_PERIOD_DATE<>T.ADD_PERIOD_DATE
 OR N.FIRST_OVDUE_DATE<>T.FIRST_OVDUE_DATE
 OR N.FIRST_PRIMNESS_DATE<>T.FIRST_PRIMNESS_DATE
 OR N.FIRST_BAD_DEBT_DATE<>T.FIRST_BAD_DEBT_DATE
 OR N.BALANCE_ACCOUNTS<>T.BALANCE_ACCOUNTS
 OR N.IN_GEAR_ACCOUNTS<>T.IN_GEAR_ACCOUNTS
 OR N.ADD_PERIOD_ACCOUNTS<>T.ADD_PERIOD_ACCOUNTS
 OR N.OVDUE_ACCOUNTS<>T.OVDUE_ACCOUNTS
 OR N.PRIMNESS_ACCOUNTS<>T.PRIMNESS_ACCOUNTS
 OR N.BAD_DEBT_ACCOUNTS<>T.BAD_DEBT_ACCOUNTS
 OR N.FOUR_SORT<>T.FOUR_SORT
 OR N.REC_STATE<>T.REC_STATE
 OR N.OLD_CONTRACT_NUM<>T.OLD_CONTRACT_NUM
 OR N.LAST_MAINTAIN_DATE<>T.LAST_MAINTAIN_DATE
 OR N.CURRENCY_CD<>T.CURRENCY_CD
 OR N.WRITE_OFF_DATE<>T.WRITE_OFF_DATE
 OR N.PAYOUT_INFO_DETAIL_ID<>T.PAYOUT_INFO_DETAIL_ID
 OR N.IN_GEAR_BALANCE<>T.IN_GEAR_BALANCE
 OR N.OVERDUE_BALANCE<>T.OVERDUE_BALANCE
 OR N.PRIMNESS_BALANCE<>T.PRIMNESS_BALANCE
 OR N.BAD_DEBT_BALANCE<>T.BAD_DEBT_BALANCE
 OR N.EXPIRATION_BALANCE<>T.EXPIRATION_BALANCE
 OR N.LAST_REQUITAL_SUM<>T.LAST_REQUITAL_SUM
 OR N.CLASSIFICATION_RESULT<>T.CLASSIFICATION_RESULT
 OR N.REPLACEMENT_SIGN<>T.REPLACEMENT_SIGN
 OR N.ENTER_ACCOUNTS_ORGAN<>T.ENTER_ACCOUNTS_ORGAN
 OR N.EXPIRATION_ACCOUNTS<>T.EXPIRATION_ACCOUNTS
 OR N.REPLACEMENT_ACCOUNTS<>T.REPLACEMENT_ACCOUNTS
 OR N.REPLACEMENT_BALANCE<>T.REPLACEMENT_BALANCE
 OR N.FINANCING_IND<>T.FINANCING_IND
 OR N.LETTER_OF_CREDIT_STATE<>T.LETTER_OF_CREDIT_STATE
 OR N.TIME_MARK<>T.TIME_MARK
 OR N.EXTEND_DATE<>T.EXTEND_DATE
 OR N.CORPUS_EXP_START_DATE<>T.CORPUS_EXP_START_DATE
 OR N.ACCRUAL_EXP_START_DATE<>T.ACCRUAL_EXP_START_DATE
 OR N.INFRACT_NUMBER<>T.INFRACT_NUMBER
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.BORROW_TYPE<>T.BORROW_TYPE
 OR N.ADD_PERIOD_BORROW_STATUS<>T.ADD_PERIOD_BORROW_STATUS
 OR N.ADD_PERIOD_TIME<>T.ADD_PERIOD_TIME
 OR N.TERM<>T.TERM
 OR N.PAYOUT_NOTICE_NUM<>T.PAYOUT_NOTICE_NUM
 OR N.LAST_OVDUE_DATE<>T.LAST_OVDUE_DATE
 OR N.MAX_OVDUE_DAYS<>T.MAX_OVDUE_DAYS
 OR N.LAST_OVDUE_DAYS<>T.LAST_OVDUE_DAYS
 OR N.OLD_SUM_OVDUE_DAYS<>T.OLD_SUM_OVDUE_DAYS
 OR N.IS_STOP_INTEREST<>T.IS_STOP_INTEREST
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.BANK_GROUP_TOTAL_AMT<>T.BANK_GROUP_TOTAL_AMT
 OR N.BANK_GROUP_TOTAL_AMT_BALANCE<>T.BANK_GROUP_TOTAL_AMT_BALANCE
 OR N.OWE_CORPUS_AMT<>T.OWE_CORPUS_AMT
 OR N.OWE_CORPUS_DATE<>T.OWE_CORPUS_DATE
 OR N.OWE_CORPUS_DAYS<>T.OWE_CORPUS_DAYS
 OR N.OWE_ACCRUAL_AMT<>T.OWE_ACCRUAL_AMT
 OR N.OWE_ACCRUAL_DATE<>T.OWE_ACCRUAL_DATE
 OR N.OWE_ACCRUAL_DAYS<>T.OWE_ACCRUAL_DAYS
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_109
WHERE P.End_Dt=DATE('2100-12-31')
AND P.PAYOUT_ACCT_SUMMARY_ID=T_109.PAYOUT_ACCT_SUMMARY_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_CON_BORR_ACCT_SUMMARY SELECT * FROM T_109;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
