#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.COS_000_SECTYPE WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.COS_000_SECTYPE SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_159 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.COS_000_SECTYPE WHERE 1=0;

--Step2:
INSERT  INTO T_159 (
  THEKEY,
  NAME,
  CODE,
  EXT_NAME,
  TRANSTYPE,
  OWNER,
  THELEVEL,
  FORMULA,
  RATENAME,
  BOR_INVEST,
  CCY,
  FACILITY,
  DEALER,
  MATURE_TYP,
  TO_MATURE,
  ISSUE_DT,
  MATURE_DT,
  N_MAT_TYP,
  N_TO_MAT,
  NOTION_DT,
  STMTEND,
  STMTDUE,
  STMTQTR,
  TO_SETTLE,
  RATE_OFF,
  COUPON,
  COUPON_FRQ,
  ACC_ISS,
  ISS_PAY_AGENT,
  SHOW_ISS_PAY_AGENT,
  ISS_PAY_AGENT_REQ,
  ALL_CFS_WITH_IPA,
  EX_INT_DAY,
  PRICE_METH,
  SHOW_BOTH,
  PRICE_TYPE,
  MODIFIABLE,
  PPH_ROUND,
  PPH_CAPTAL,
  PPH_INCOME,
  PPH_CAPITAL_METHOD,
  PPH_CAPITAL_DP,
  PPH_INCOME_METHOD,
  PPH_INCOME_DP,
  PPH_SETTLE_METHOD,
  PPH_SETTLE_DP,
  PPH_DERIVE,
  FIX_FLOAT,
  INT_TIMING,
  INT_CALC,
  INT_DAYS,
  CD_SELECT,
  RD_SELECT,
  ED_SELECT,
  TRADABLE,
  DRAWERS,
  CLOSEOUT,
  SETTLEMENT,
  BASIS_RATE,
  ASSET_LIAB,
  CROSS_CCY,
  DEAL_RATE,
  FRA_ADV,
  COUP_TYPE,
  COUP_DATES,
  MM_OR_SEC,
  MARGIN,
  MARGIN_ACT,
  OPTSTYLE,
  STOCKLOCAT,
  NEW_ISSUE,
  STOCKTYPE,
  TOT_ISSUE,
  BASIS_FREQ,
  DELIVERY,
  CCY_CONTR,
  PRICE_FORM,
  EXCHANGE,
  ENTITY,
  CLEAR_BROK,
  EXEC_BROK,
  SPAN_ID,
  FUNGIBLE,
  RATENOTYPE,
  EURO_STYLE,
  ASSET_BACK,
  LEGAL_MAT,
  SETT_TYPE,
  SETT_TIME,
  PREM_TIME,
  OPTTYPE,
  SETT_INST,
  INDX_NAME,
  ANNUITY,
  ISS_INDX,
  ISS_YIELD,
  YIELD_TYPE,
  FRAC_UNIT,
  CF_NOTION,
  SEC_DEF1,
  SEC_DEF2,
  TIME_OPT,
  LC_TYPE,
  CFSTATUS,
  STRIKESPOT,
  FPP_METHOD,
  NOM_EFF,
  COMP_FREQ,
  SHOW_IRR,
  PPH_AFTER,
  MOD_FLAGS,
  SHOW_BROK,
  BROK_REQ,
  INC_NOTION,
  PRINC_EXCH,
  FUT_DAYS,
  PAY_FREQ,
  REVIEW_FRQ,
  CDI_DISC,
  FUFTDAYS,
  P_SECTYPE,
  P_LINK,
  P_DETAIL,
  R_SECTYPE,
  R_LINK,
  R_DETAIL,
  FT_KEY,
  CUSIP_DEF,
  ISIN_DEF,
  CUSIN_SHOW,
  CUSIN_REQ,
  MOD_MASK,
  MAND_MASK,
  SHOW_MASK,
  ISS_MOD,
  INRNDMETH,
  INRNDPLACE,
  OPTCLASS,
  DAY_WEIGHT,
  REBATE_AT,
  HEDGE_DDES,
  ANALYSE01,
  ANALYSE02,
  ANALYSE03,
  ANALYSE04,
  ANALYSE05,
  ANALYSE06,
  ANALYSE07,
  ANALYSE08,
  ANALYSE09,
  ANALYSE10,
  ANALYSE11,
  ANALYSE12,
  ANALYSE13,
  ANALYSE14,
  ANALYSE15,
  ANALYSE16,
  ANALYSE17,
  ANALYSE18,
  ANALYSE19,
  ANALYSE20,
  HEDGETYPE,
  NAT_RISK,
  EFF_TYPE,
  EFF_FREQ,
  EF_PERIODS,
  LOW_LIMIT,
  UP_LIMIT,
  SHORTCUT,
  DOC_NO,
  TRAN_OCI,
  FREZ_OCI,
  REL_OCI,
  TR_OS_ST,
  FR_OS_ST,
  RE_OS_ST,
  TR_OFSET,
  FR_OFSET,
  RE_OFSET,
  TR_R_OFSET,
  TR_R_OS_ST,
  TRAN_ENT,
  REL_ENT,
  RATETYPE,
  EF_PROSPEC,
  EF_RANGE,
  STD_INTERV,
  S_METHOD,
  S_SIZE,
  R_SQUARED,
  T_SLOPE,
  T_SLOPE_UPPER,
  TINTERCEPT,
  TINTERCEPT_UPPER,
  C_LEVEL,
  STD_DEV,
  T_METHOD,
  EF_RETRO,
  RETRO_INTERVAL,
  RETRO_R_SQUARED,
  RETRO_SLOPE_LOWER,
  RETRO_SLOPE_UPPER,
  RETRO_INTERCEPT_LOWER,
  RETRO_INTERCEPT_UPPER,
  RETRO_C_LEVEL,
  RETRO_STD_DEV,
  RETRO_T_METHOD,
  F_REG_DATE,
  DUAL_CCY,
  COUPON_CCY,
  SEPARATE_RATESET,
  ASYMM_CUR_HOL,
  INT_CALC_LOC,
  USAGE,
  IN_USE,
  BTREE_LOW,
  BTREE_HIGH,
  SETTLE_NBD_RULE,
  DATED_DATE,
  FNL_PRD_METHOD,
  FPP_EARLY_DISCOUNT,
  FPP_ADJ_MATURITY,
  FPP_NO_PPH_ROUNDING,
  FPP_DAYS_BASIS,
  FIRST_COUPON_DATE,
  INCOME_ACCRUAL_BASIS,
  ODD_FIRST_COUPON,
  ODD_LAST_COUPON,
  PENULTIMATE_COUPON_DATE,
  YIELD_CONVENTION_ID,
  DISCOUNT_DAYS_BASIS,
  PRODUCT_ID,
  NON_BUS_DEALS,
  TEMPLATE,
  NO_COUPON_ON_MATURITY,
  GEN_STOCK_FLOW,
  ACC_ISS_REQD,
  ACC_ISS_PRI_IDENT,
  ACC_ISS_FORM_OF_STOCK,
  ACC_ISS_OTHER_IDENT,
  DEAL_SET_RULE_ID,
  DEAL_SET_RULE_MODIFY,
  DEAL_SET_MODE_FORECAST,
  DEAL_SET_RECURRING_CF,
  DEAL_SET_MODE_DS,
  EMBEDDED_OPTION,
  EXSTYLE,
  STRIKPRICE,
  ISSUE_FEE_APPLICABLE,
  DEF_PYMT_MSG_TYPE,
  EFFINNATURALCCY,
  COUPON_DAYS_BASIS,
  USE_DP_BASIS_PRICING,
  PAY_RECEIVE_TYPE,
  POSTING_TYPE,
  STAMP,
  FINAL_CASHFLOW_ROUNDING,
  FCR_SETTLEMENT_METHOD,
  FCR_SETTLEMENT_DP,
  FCR_INCOME_METHOD,
  FCR_INCOME_DP,
  FCR_CAPITAL_METHOD,
  FCR_CAPITAL_DP,
  PRI_IDENT_FILTER_BY,
  PRI_IDENT_FILTER_VAL,
  SPLIT_SETTLEMENT,
  SECISSUE_ID,
  SECISSUE_DISPLAY,
  SECISSUE_REQUIRED,
  DEFAULT_IPA_FROM_CPARTY,
  USE_SECISSUE_FOR_DEFAULTING,
  CPARTY,
  ALLOW_ESTIMATED_PRICE,
  ESTIMATED_SETTLE_HANDLING,
  ALLOW_PARTIAL_UNIT,
  PARTIAL_UNIT_DP,
  PARTIAL_UNIT_ROUND_METHOD,
  PRICE_DP,
  PRICE_ROUND_METHOD,
  UNIT_INSTRUMENT,
  TRADING_STYLE,
  WARN_IF_SHORT,
  ADDITIONAL_TRADING_INFO,
  ACTION_NBD_RULE,
  CALCULATION_NBD_RULE,
  UNIT_CPARTY,
  UNIT_BROKER,
  CLS_SETTLEMENT,
  BARRIER_VALIDATION,
  DEFAULT_LATEST_PRICE,
  SETTLEMENT_TYPE,
  SETTLEMENT_CCY,
  INTERCEPT_PASSFAIL,
  C_LEVEL_PASSFAIL,
  T_STATISTIC_PASSFAIL,
  T_STATISTIC_C_LEVEL,
  T_STATISTIC_T_METHOD,
  RETRO_INTERCEPT_PASSFAIL,
  RETRO_C_LEVEL_PASSFAIL,
  RETRO_T_STATISTIC_PASSFAIL,
  RETRO_T_STATISTIC_C_LEVEL,
  RETRO_T_STATISTIC_T_METHOD,
  RETRO_S_SIZE,
  RETRO_S_METHOD,
  ALLOW_MULTIPLE_RATESETS,
  start_dt,
  end_dt)
SELECT
  N.THEKEY,
  N.NAME,
  N.CODE,
  N.EXT_NAME,
  N.TRANSTYPE,
  N.OWNER,
  N.THELEVEL,
  N.FORMULA,
  N.RATENAME,
  N.BOR_INVEST,
  N.CCY,
  N.FACILITY,
  N.DEALER,
  N.MATURE_TYP,
  N.TO_MATURE,
  N.ISSUE_DT,
  N.MATURE_DT,
  N.N_MAT_TYP,
  N.N_TO_MAT,
  N.NOTION_DT,
  N.STMTEND,
  N.STMTDUE,
  N.STMTQTR,
  N.TO_SETTLE,
  N.RATE_OFF,
  N.COUPON,
  N.COUPON_FRQ,
  N.ACC_ISS,
  N.ISS_PAY_AGENT,
  N.SHOW_ISS_PAY_AGENT,
  N.ISS_PAY_AGENT_REQ,
  N.ALL_CFS_WITH_IPA,
  N.EX_INT_DAY,
  N.PRICE_METH,
  N.SHOW_BOTH,
  N.PRICE_TYPE,
  N.MODIFIABLE,
  N.PPH_ROUND,
  N.PPH_CAPTAL,
  N.PPH_INCOME,
  N.PPH_CAPITAL_METHOD,
  N.PPH_CAPITAL_DP,
  N.PPH_INCOME_METHOD,
  N.PPH_INCOME_DP,
  N.PPH_SETTLE_METHOD,
  N.PPH_SETTLE_DP,
  N.PPH_DERIVE,
  N.FIX_FLOAT,
  N.INT_TIMING,
  N.INT_CALC,
  N.INT_DAYS,
  N.CD_SELECT,
  N.RD_SELECT,
  N.ED_SELECT,
  N.TRADABLE,
  N.DRAWERS,
  N.CLOSEOUT,
  N.SETTLEMENT,
  N.BASIS_RATE,
  N.ASSET_LIAB,
  N.CROSS_CCY,
  N.DEAL_RATE,
  N.FRA_ADV,
  N.COUP_TYPE,
  N.COUP_DATES,
  N.MM_OR_SEC,
  N.MARGIN,
  N.MARGIN_ACT,
  N.OPTSTYLE,
  N.STOCKLOCAT,
  N.NEW_ISSUE,
  N.STOCKTYPE,
  N.TOT_ISSUE,
  N.BASIS_FREQ,
  N.DELIVERY,
  N.CCY_CONTR,
  N.PRICE_FORM,
  N.EXCHANGE,
  N.ENTITY,
  N.CLEAR_BROK,
  N.EXEC_BROK,
  N.SPAN_ID,
  N.FUNGIBLE,
  N.RATENOTYPE,
  N.EURO_STYLE,
  N.ASSET_BACK,
  N.LEGAL_MAT,
  N.SETT_TYPE,
  N.SETT_TIME,
  N.PREM_TIME,
  N.OPTTYPE,
  N.SETT_INST,
  N.INDX_NAME,
  N.ANNUITY,
  N.ISS_INDX,
  N.ISS_YIELD,
  N.YIELD_TYPE,
  N.FRAC_UNIT,
  N.CF_NOTION,
  N.SEC_DEF1,
  N.SEC_DEF2,
  N.TIME_OPT,
  N.LC_TYPE,
  N.CFSTATUS,
  N.STRIKESPOT,
  N.FPP_METHOD,
  N.NOM_EFF,
  N.COMP_FREQ,
  N.SHOW_IRR,
  N.PPH_AFTER,
  N.MOD_FLAGS,
  N.SHOW_BROK,
  N.BROK_REQ,
  N.INC_NOTION,
  N.PRINC_EXCH,
  N.FUT_DAYS,
  N.PAY_FREQ,
  N.REVIEW_FRQ,
  N.CDI_DISC,
  N.FUFTDAYS,
  N.P_SECTYPE,
  N.P_LINK,
  N.P_DETAIL,
  N.R_SECTYPE,
  N.R_LINK,
  N.R_DETAIL,
  N.FT_KEY,
  N.CUSIP_DEF,
  N.ISIN_DEF,
  N.CUSIN_SHOW,
  N.CUSIN_REQ,
  N.MOD_MASK,
  N.MAND_MASK,
  N.SHOW_MASK,
  N.ISS_MOD,
  N.INRNDMETH,
  N.INRNDPLACE,
  N.OPTCLASS,
  N.DAY_WEIGHT,
  N.REBATE_AT,
  N.HEDGE_DDES,
  N.ANALYSE01,
  N.ANALYSE02,
  N.ANALYSE03,
  N.ANALYSE04,
  N.ANALYSE05,
  N.ANALYSE06,
  N.ANALYSE07,
  N.ANALYSE08,
  N.ANALYSE09,
  N.ANALYSE10,
  N.ANALYSE11,
  N.ANALYSE12,
  N.ANALYSE13,
  N.ANALYSE14,
  N.ANALYSE15,
  N.ANALYSE16,
  N.ANALYSE17,
  N.ANALYSE18,
  N.ANALYSE19,
  N.ANALYSE20,
  N.HEDGETYPE,
  N.NAT_RISK,
  N.EFF_TYPE,
  N.EFF_FREQ,
  N.EF_PERIODS,
  N.LOW_LIMIT,
  N.UP_LIMIT,
  N.SHORTCUT,
  N.DOC_NO,
  N.TRAN_OCI,
  N.FREZ_OCI,
  N.REL_OCI,
  N.TR_OS_ST,
  N.FR_OS_ST,
  N.RE_OS_ST,
  N.TR_OFSET,
  N.FR_OFSET,
  N.RE_OFSET,
  N.TR_R_OFSET,
  N.TR_R_OS_ST,
  N.TRAN_ENT,
  N.REL_ENT,
  N.RATETYPE,
  N.EF_PROSPEC,
  N.EF_RANGE,
  N.STD_INTERV,
  N.S_METHOD,
  N.S_SIZE,
  N.R_SQUARED,
  N.T_SLOPE,
  N.T_SLOPE_UPPER,
  N.TINTERCEPT,
  N.TINTERCEPT_UPPER,
  N.C_LEVEL,
  N.STD_DEV,
  N.T_METHOD,
  N.EF_RETRO,
  N.RETRO_INTERVAL,
  N.RETRO_R_SQUARED,
  N.RETRO_SLOPE_LOWER,
  N.RETRO_SLOPE_UPPER,
  N.RETRO_INTERCEPT_LOWER,
  N.RETRO_INTERCEPT_UPPER,
  N.RETRO_C_LEVEL,
  N.RETRO_STD_DEV,
  N.RETRO_T_METHOD,
  N.F_REG_DATE,
  N.DUAL_CCY,
  N.COUPON_CCY,
  N.SEPARATE_RATESET,
  N.ASYMM_CUR_HOL,
  N.INT_CALC_LOC,
  N.USAGE,
  N.IN_USE,
  N.BTREE_LOW,
  N.BTREE_HIGH,
  N.SETTLE_NBD_RULE,
  N.DATED_DATE,
  N.FNL_PRD_METHOD,
  N.FPP_EARLY_DISCOUNT,
  N.FPP_ADJ_MATURITY,
  N.FPP_NO_PPH_ROUNDING,
  N.FPP_DAYS_BASIS,
  N.FIRST_COUPON_DATE,
  N.INCOME_ACCRUAL_BASIS,
  N.ODD_FIRST_COUPON,
  N.ODD_LAST_COUPON,
  N.PENULTIMATE_COUPON_DATE,
  N.YIELD_CONVENTION_ID,
  N.DISCOUNT_DAYS_BASIS,
  N.PRODUCT_ID,
  N.NON_BUS_DEALS,
  N.TEMPLATE,
  N.NO_COUPON_ON_MATURITY,
  N.GEN_STOCK_FLOW,
  N.ACC_ISS_REQD,
  N.ACC_ISS_PRI_IDENT,
  N.ACC_ISS_FORM_OF_STOCK,
  N.ACC_ISS_OTHER_IDENT,
  N.DEAL_SET_RULE_ID,
  N.DEAL_SET_RULE_MODIFY,
  N.DEAL_SET_MODE_FORECAST,
  N.DEAL_SET_RECURRING_CF,
  N.DEAL_SET_MODE_DS,
  N.EMBEDDED_OPTION,
  N.EXSTYLE,
  N.STRIKPRICE,
  N.ISSUE_FEE_APPLICABLE,
  N.DEF_PYMT_MSG_TYPE,
  N.EFFINNATURALCCY,
  N.COUPON_DAYS_BASIS,
  N.USE_DP_BASIS_PRICING,
  N.PAY_RECEIVE_TYPE,
  N.POSTING_TYPE,
  N.STAMP,
  N.FINAL_CASHFLOW_ROUNDING,
  N.FCR_SETTLEMENT_METHOD,
  N.FCR_SETTLEMENT_DP,
  N.FCR_INCOME_METHOD,
  N.FCR_INCOME_DP,
  N.FCR_CAPITAL_METHOD,
  N.FCR_CAPITAL_DP,
  N.PRI_IDENT_FILTER_BY,
  N.PRI_IDENT_FILTER_VAL,
  N.SPLIT_SETTLEMENT,
  N.SECISSUE_ID,
  N.SECISSUE_DISPLAY,
  N.SECISSUE_REQUIRED,
  N.DEFAULT_IPA_FROM_CPARTY,
  N.USE_SECISSUE_FOR_DEFAULTING,
  N.CPARTY,
  N.ALLOW_ESTIMATED_PRICE,
  N.ESTIMATED_SETTLE_HANDLING,
  N.ALLOW_PARTIAL_UNIT,
  N.PARTIAL_UNIT_DP,
  N.PARTIAL_UNIT_ROUND_METHOD,
  N.PRICE_DP,
  N.PRICE_ROUND_METHOD,
  N.UNIT_INSTRUMENT,
  N.TRADING_STYLE,
  N.WARN_IF_SHORT,
  N.ADDITIONAL_TRADING_INFO,
  N.ACTION_NBD_RULE,
  N.CALCULATION_NBD_RULE,
  N.UNIT_CPARTY,
  N.UNIT_BROKER,
  N.CLS_SETTLEMENT,
  N.BARRIER_VALIDATION,
  N.DEFAULT_LATEST_PRICE,
  N.SETTLEMENT_TYPE,
  N.SETTLEMENT_CCY,
  N.INTERCEPT_PASSFAIL,
  N.C_LEVEL_PASSFAIL,
  N.T_STATISTIC_PASSFAIL,
  N.T_STATISTIC_C_LEVEL,
  N.T_STATISTIC_T_METHOD,
  N.RETRO_INTERCEPT_PASSFAIL,
  N.RETRO_C_LEVEL_PASSFAIL,
  N.RETRO_T_STATISTIC_PASSFAIL,
  N.RETRO_T_STATISTIC_C_LEVEL,
  N.RETRO_T_STATISTIC_T_METHOD,
  N.RETRO_S_SIZE,
  N.RETRO_S_METHOD,
  N.ALLOW_MULTIPLE_RATESETS,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(THEKEY, '' ) AS THEKEY ,
  COALESCE(NAME, '' ) AS NAME ,
  COALESCE(CODE, '' ) AS CODE ,
  COALESCE(EXT_NAME, '' ) AS EXT_NAME ,
  COALESCE(TRANSTYPE, '' ) AS TRANSTYPE ,
  COALESCE(OWNER, '' ) AS OWNER ,
  COALESCE(THELEVEL, '' ) AS THELEVEL ,
  COALESCE(FORMULA, '' ) AS FORMULA ,
  COALESCE(RATENAME, '' ) AS RATENAME ,
  COALESCE(BOR_INVEST, '' ) AS BOR_INVEST ,
  COALESCE(CCY, '' ) AS CCY ,
  COALESCE(FACILITY, '' ) AS FACILITY ,
  COALESCE(DEALER, '' ) AS DEALER ,
  COALESCE(MATURE_TYP, '' ) AS MATURE_TYP ,
  COALESCE(TO_MATURE, 0 ) AS TO_MATURE ,
  COALESCE(ISSUE_DT, '' ) AS ISSUE_DT ,
  COALESCE(MATURE_DT, '' ) AS MATURE_DT ,
  COALESCE(N_MAT_TYP, '' ) AS N_MAT_TYP ,
  COALESCE(N_TO_MAT, 0 ) AS N_TO_MAT ,
  COALESCE(NOTION_DT, '' ) AS NOTION_DT ,
  COALESCE(STMTEND, '' ) AS STMTEND ,
  COALESCE(STMTDUE, '' ) AS STMTDUE ,
  COALESCE(STMTQTR, '' ) AS STMTQTR ,
  COALESCE(TO_SETTLE, 0 ) AS TO_SETTLE ,
  COALESCE(RATE_OFF, 0 ) AS RATE_OFF ,
  COALESCE(COUPON, 0 ) AS COUPON ,
  COALESCE(COUPON_FRQ, '' ) AS COUPON_FRQ ,
  COALESCE(ACC_ISS, '' ) AS ACC_ISS ,
  COALESCE(ISS_PAY_AGENT, '' ) AS ISS_PAY_AGENT ,
  COALESCE(SHOW_ISS_PAY_AGENT, 0 ) AS SHOW_ISS_PAY_AGENT ,
  COALESCE(ISS_PAY_AGENT_REQ, 0 ) AS ISS_PAY_AGENT_REQ ,
  COALESCE(ALL_CFS_WITH_IPA, 0 ) AS ALL_CFS_WITH_IPA ,
  COALESCE(EX_INT_DAY, '' ) AS EX_INT_DAY ,
  COALESCE(PRICE_METH, '' ) AS PRICE_METH ,
  COALESCE(SHOW_BOTH, '' ) AS SHOW_BOTH ,
  COALESCE(PRICE_TYPE, '' ) AS PRICE_TYPE ,
  COALESCE(MODIFIABLE, '' ) AS MODIFIABLE ,
  COALESCE(PPH_ROUND, '' ) AS PPH_ROUND ,
  COALESCE(PPH_CAPTAL, '' ) AS PPH_CAPTAL ,
  COALESCE(PPH_INCOME, '' ) AS PPH_INCOME ,
  COALESCE(PPH_CAPITAL_METHOD, 0 ) AS PPH_CAPITAL_METHOD ,
  COALESCE(PPH_CAPITAL_DP, 0 ) AS PPH_CAPITAL_DP ,
  COALESCE(PPH_INCOME_METHOD, 0 ) AS PPH_INCOME_METHOD ,
  COALESCE(PPH_INCOME_DP, 0 ) AS PPH_INCOME_DP ,
  COALESCE(PPH_SETTLE_METHOD, 0 ) AS PPH_SETTLE_METHOD ,
  COALESCE(PPH_SETTLE_DP, 0 ) AS PPH_SETTLE_DP ,
  COALESCE(PPH_DERIVE, '' ) AS PPH_DERIVE ,
  COALESCE(FIX_FLOAT, '' ) AS FIX_FLOAT ,
  COALESCE(INT_TIMING, '' ) AS INT_TIMING ,
  COALESCE(INT_CALC, '' ) AS INT_CALC ,
  COALESCE(INT_DAYS, '' ) AS INT_DAYS ,
  COALESCE(CD_SELECT, '' ) AS CD_SELECT ,
  COALESCE(RD_SELECT, '' ) AS RD_SELECT ,
  COALESCE(ED_SELECT, '' ) AS ED_SELECT ,
  COALESCE(TRADABLE, '' ) AS TRADABLE ,
  COALESCE(DRAWERS, '' ) AS DRAWERS ,
  COALESCE(CLOSEOUT, '' ) AS CLOSEOUT ,
  COALESCE(SETTLEMENT, '' ) AS SETTLEMENT ,
  COALESCE(BASIS_RATE, '' ) AS BASIS_RATE ,
  COALESCE(ASSET_LIAB, '' ) AS ASSET_LIAB ,
  COALESCE(CROSS_CCY, '' ) AS CROSS_CCY ,
  COALESCE(DEAL_RATE, '' ) AS DEAL_RATE ,
  COALESCE(FRA_ADV, '' ) AS FRA_ADV ,
  COALESCE(COUP_TYPE, '' ) AS COUP_TYPE ,
  COALESCE(COUP_DATES, '' ) AS COUP_DATES ,
  COALESCE(MM_OR_SEC, '' ) AS MM_OR_SEC ,
  COALESCE(MARGIN, 0 ) AS MARGIN ,
  COALESCE(MARGIN_ACT, '' ) AS MARGIN_ACT ,
  COALESCE(OPTSTYLE, '' ) AS OPTSTYLE ,
  COALESCE(STOCKLOCAT, '' ) AS STOCKLOCAT ,
  COALESCE(NEW_ISSUE, '' ) AS NEW_ISSUE ,
  COALESCE(STOCKTYPE, '' ) AS STOCKTYPE ,
  COALESCE(TOT_ISSUE, 0 ) AS TOT_ISSUE ,
  COALESCE(BASIS_FREQ, '' ) AS BASIS_FREQ ,
  COALESCE(DELIVERY, '' ) AS DELIVERY ,
  COALESCE(CCY_CONTR, '' ) AS CCY_CONTR ,
  COALESCE(PRICE_FORM, '' ) AS PRICE_FORM ,
  COALESCE(EXCHANGE, '' ) AS EXCHANGE ,
  COALESCE(ENTITY, '' ) AS ENTITY ,
  COALESCE(CLEAR_BROK, '' ) AS CLEAR_BROK ,
  COALESCE(EXEC_BROK, '' ) AS EXEC_BROK ,
  COALESCE(SPAN_ID, '' ) AS SPAN_ID ,
  COALESCE(FUNGIBLE, '' ) AS FUNGIBLE ,
  COALESCE(RATENOTYPE, '' ) AS RATENOTYPE ,
  COALESCE(EURO_STYLE, '' ) AS EURO_STYLE ,
  COALESCE(ASSET_BACK, '' ) AS ASSET_BACK ,
  COALESCE(LEGAL_MAT, '' ) AS LEGAL_MAT ,
  COALESCE(SETT_TYPE, '' ) AS SETT_TYPE ,
  COALESCE(SETT_TIME, '' ) AS SETT_TIME ,
  COALESCE(PREM_TIME, '' ) AS PREM_TIME ,
  COALESCE(OPTTYPE, '' ) AS OPTTYPE ,
  COALESCE(SETT_INST, '' ) AS SETT_INST ,
  COALESCE(INDX_NAME, '' ) AS INDX_NAME ,
  COALESCE(ANNUITY, 0 ) AS ANNUITY ,
  COALESCE(ISS_INDX, 0 ) AS ISS_INDX ,
  COALESCE(ISS_YIELD, 0 ) AS ISS_YIELD ,
  COALESCE(YIELD_TYPE, '' ) AS YIELD_TYPE ,
  COALESCE(FRAC_UNIT, 0 ) AS FRAC_UNIT ,
  COALESCE(CF_NOTION, '' ) AS CF_NOTION ,
  COALESCE(SEC_DEF1, '' ) AS SEC_DEF1 ,
  COALESCE(SEC_DEF2, '' ) AS SEC_DEF2 ,
  COALESCE(TIME_OPT, '' ) AS TIME_OPT ,
  COALESCE(LC_TYPE, '' ) AS LC_TYPE ,
  COALESCE(CFSTATUS, '' ) AS CFSTATUS ,
  COALESCE(STRIKESPOT, '' ) AS STRIKESPOT ,
  COALESCE(FPP_METHOD, '' ) AS FPP_METHOD ,
  COALESCE(NOM_EFF, '' ) AS NOM_EFF ,
  COALESCE(COMP_FREQ, '' ) AS COMP_FREQ ,
  COALESCE(SHOW_IRR, '' ) AS SHOW_IRR ,
  COALESCE(PPH_AFTER, '' ) AS PPH_AFTER ,
  COALESCE(MOD_FLAGS, '' ) AS MOD_FLAGS ,
  COALESCE(SHOW_BROK, '' ) AS SHOW_BROK ,
  COALESCE(BROK_REQ, '' ) AS BROK_REQ ,
  COALESCE(INC_NOTION, '' ) AS INC_NOTION ,
  COALESCE(PRINC_EXCH, '' ) AS PRINC_EXCH ,
  COALESCE(FUT_DAYS, '' ) AS FUT_DAYS ,
  COALESCE(PAY_FREQ, '' ) AS PAY_FREQ ,
  COALESCE(REVIEW_FRQ, '' ) AS REVIEW_FRQ ,
  COALESCE(CDI_DISC, 0 ) AS CDI_DISC ,
  COALESCE(FUFTDAYS, '' ) AS FUFTDAYS ,
  COALESCE(P_SECTYPE, '' ) AS P_SECTYPE ,
  COALESCE(P_LINK, '' ) AS P_LINK ,
  COALESCE(P_DETAIL, '' ) AS P_DETAIL ,
  COALESCE(R_SECTYPE, '' ) AS R_SECTYPE ,
  COALESCE(R_LINK, '' ) AS R_LINK ,
  COALESCE(R_DETAIL, '' ) AS R_DETAIL ,
  COALESCE(FT_KEY, 0 ) AS FT_KEY ,
  COALESCE(CUSIP_DEF, '' ) AS CUSIP_DEF ,
  COALESCE(ISIN_DEF, '' ) AS ISIN_DEF ,
  COALESCE(CUSIN_SHOW, '' ) AS CUSIN_SHOW ,
  COALESCE(CUSIN_REQ, '' ) AS CUSIN_REQ ,
  COALESCE(MOD_MASK, '' ) AS MOD_MASK ,
  COALESCE(MAND_MASK, '' ) AS MAND_MASK ,
  COALESCE(SHOW_MASK, '' ) AS SHOW_MASK ,
  COALESCE(ISS_MOD, '' ) AS ISS_MOD ,
  COALESCE(INRNDMETH, '' ) AS INRNDMETH ,
  COALESCE(INRNDPLACE, 0 ) AS INRNDPLACE ,
  COALESCE(OPTCLASS, '' ) AS OPTCLASS ,
  COALESCE(DAY_WEIGHT, '' ) AS DAY_WEIGHT ,
  COALESCE(REBATE_AT, '' ) AS REBATE_AT ,
  COALESCE(HEDGE_DDES, '' ) AS HEDGE_DDES ,
  COALESCE(ANALYSE01, '' ) AS ANALYSE01 ,
  COALESCE(ANALYSE02, '' ) AS ANALYSE02 ,
  COALESCE(ANALYSE03, '' ) AS ANALYSE03 ,
  COALESCE(ANALYSE04, '' ) AS ANALYSE04 ,
  COALESCE(ANALYSE05, '' ) AS ANALYSE05 ,
  COALESCE(ANALYSE06, '' ) AS ANALYSE06 ,
  COALESCE(ANALYSE07, '' ) AS ANALYSE07 ,
  COALESCE(ANALYSE08, '' ) AS ANALYSE08 ,
  COALESCE(ANALYSE09, '' ) AS ANALYSE09 ,
  COALESCE(ANALYSE10, '' ) AS ANALYSE10 ,
  COALESCE(ANALYSE11, '' ) AS ANALYSE11 ,
  COALESCE(ANALYSE12, '' ) AS ANALYSE12 ,
  COALESCE(ANALYSE13, '' ) AS ANALYSE13 ,
  COALESCE(ANALYSE14, '' ) AS ANALYSE14 ,
  COALESCE(ANALYSE15, '' ) AS ANALYSE15 ,
  COALESCE(ANALYSE16, '' ) AS ANALYSE16 ,
  COALESCE(ANALYSE17, '' ) AS ANALYSE17 ,
  COALESCE(ANALYSE18, '' ) AS ANALYSE18 ,
  COALESCE(ANALYSE19, '' ) AS ANALYSE19 ,
  COALESCE(ANALYSE20, '' ) AS ANALYSE20 ,
  COALESCE(HEDGETYPE, '' ) AS HEDGETYPE ,
  COALESCE(NAT_RISK, '' ) AS NAT_RISK ,
  COALESCE(EFF_TYPE, '' ) AS EFF_TYPE ,
  COALESCE(EFF_FREQ, '' ) AS EFF_FREQ ,
  COALESCE(EF_PERIODS, 0 ) AS EF_PERIODS ,
  COALESCE(LOW_LIMIT, 0 ) AS LOW_LIMIT ,
  COALESCE(UP_LIMIT, 0 ) AS UP_LIMIT ,
  COALESCE(SHORTCUT, '' ) AS SHORTCUT ,
  COALESCE(DOC_NO, 0 ) AS DOC_NO ,
  COALESCE(TRAN_OCI, '' ) AS TRAN_OCI ,
  COALESCE(FREZ_OCI, '' ) AS FREZ_OCI ,
  COALESCE(REL_OCI, '' ) AS REL_OCI ,
  COALESCE(TR_OS_ST, '' ) AS TR_OS_ST ,
  COALESCE(FR_OS_ST, '' ) AS FR_OS_ST ,
  COALESCE(RE_OS_ST, '' ) AS RE_OS_ST ,
  COALESCE(TR_OFSET, '' ) AS TR_OFSET ,
  COALESCE(FR_OFSET, '' ) AS FR_OFSET ,
  COALESCE(RE_OFSET, '' ) AS RE_OFSET ,
  COALESCE(TR_R_OFSET, '' ) AS TR_R_OFSET ,
  COALESCE(TR_R_OS_ST, '' ) AS TR_R_OS_ST ,
  COALESCE(TRAN_ENT, '' ) AS TRAN_ENT ,
  COALESCE(REL_ENT, '' ) AS REL_ENT ,
  COALESCE(RATETYPE, '' ) AS RATETYPE ,
  COALESCE(EF_PROSPEC, '' ) AS EF_PROSPEC ,
  COALESCE(EF_RANGE, '' ) AS EF_RANGE ,
  COALESCE(STD_INTERV, '' ) AS STD_INTERV ,
  COALESCE(S_METHOD, '' ) AS S_METHOD ,
  COALESCE(S_SIZE, 0 ) AS S_SIZE ,
  COALESCE(R_SQUARED, 0 ) AS R_SQUARED ,
  COALESCE(T_SLOPE, 0 ) AS T_SLOPE ,
  COALESCE(T_SLOPE_UPPER, 0 ) AS T_SLOPE_UPPER ,
  COALESCE(TINTERCEPT, 0 ) AS TINTERCEPT ,
  COALESCE(TINTERCEPT_UPPER, 0 ) AS TINTERCEPT_UPPER ,
  COALESCE(C_LEVEL, 0 ) AS C_LEVEL ,
  COALESCE(STD_DEV, '' ) AS STD_DEV ,
  COALESCE(T_METHOD, '' ) AS T_METHOD ,
  COALESCE(EF_RETRO, '' ) AS EF_RETRO ,
  COALESCE(RETRO_INTERVAL, '' ) AS RETRO_INTERVAL ,
  COALESCE(RETRO_R_SQUARED, 0 ) AS RETRO_R_SQUARED ,
  COALESCE(RETRO_SLOPE_LOWER, 0 ) AS RETRO_SLOPE_LOWER ,
  COALESCE(RETRO_SLOPE_UPPER, 0 ) AS RETRO_SLOPE_UPPER ,
  COALESCE(RETRO_INTERCEPT_LOWER, 0 ) AS RETRO_INTERCEPT_LOWER ,
  COALESCE(RETRO_INTERCEPT_UPPER, 0 ) AS RETRO_INTERCEPT_UPPER ,
  COALESCE(RETRO_C_LEVEL, 0 ) AS RETRO_C_LEVEL ,
  COALESCE(RETRO_STD_DEV, '' ) AS RETRO_STD_DEV ,
  COALESCE(RETRO_T_METHOD, '' ) AS RETRO_T_METHOD ,
  COALESCE(F_REG_DATE, '' ) AS F_REG_DATE ,
  COALESCE(DUAL_CCY, '' ) AS DUAL_CCY ,
  COALESCE(COUPON_CCY, '' ) AS COUPON_CCY ,
  COALESCE(SEPARATE_RATESET, '' ) AS SEPARATE_RATESET ,
  COALESCE(ASYMM_CUR_HOL, '' ) AS ASYMM_CUR_HOL ,
  COALESCE(INT_CALC_LOC, 0 ) AS INT_CALC_LOC ,
  COALESCE(USAGE, 0 ) AS USAGE ,
  COALESCE(IN_USE, '' ) AS IN_USE ,
  COALESCE(BTREE_LOW, 0 ) AS BTREE_LOW ,
  COALESCE(BTREE_HIGH, 0 ) AS BTREE_HIGH ,
  COALESCE(SETTLE_NBD_RULE, 0 ) AS SETTLE_NBD_RULE ,
  COALESCE(DATED_DATE, '' ) AS DATED_DATE ,
  COALESCE(FNL_PRD_METHOD, 0 ) AS FNL_PRD_METHOD ,
  COALESCE(FPP_EARLY_DISCOUNT, 0 ) AS FPP_EARLY_DISCOUNT ,
  COALESCE(FPP_ADJ_MATURITY, 0 ) AS FPP_ADJ_MATURITY ,
  COALESCE(FPP_NO_PPH_ROUNDING, 0 ) AS FPP_NO_PPH_ROUNDING ,
  COALESCE(FPP_DAYS_BASIS, 0 ) AS FPP_DAYS_BASIS ,
  COALESCE(FIRST_COUPON_DATE, '' ) AS FIRST_COUPON_DATE ,
  COALESCE(INCOME_ACCRUAL_BASIS, 0 ) AS INCOME_ACCRUAL_BASIS ,
  COALESCE(ODD_FIRST_COUPON, 0 ) AS ODD_FIRST_COUPON ,
  COALESCE(ODD_LAST_COUPON, 0 ) AS ODD_LAST_COUPON ,
  COALESCE(PENULTIMATE_COUPON_DATE, '' ) AS PENULTIMATE_COUPON_DATE ,
  COALESCE(YIELD_CONVENTION_ID, 0 ) AS YIELD_CONVENTION_ID ,
  COALESCE(DISCOUNT_DAYS_BASIS, 0 ) AS DISCOUNT_DAYS_BASIS ,
  COALESCE(PRODUCT_ID, 0 ) AS PRODUCT_ID ,
  COALESCE(NON_BUS_DEALS, 0 ) AS NON_BUS_DEALS ,
  COALESCE(TEMPLATE, '' ) AS TEMPLATE ,
  COALESCE(NO_COUPON_ON_MATURITY, 0 ) AS NO_COUPON_ON_MATURITY ,
  COALESCE(GEN_STOCK_FLOW, 0 ) AS GEN_STOCK_FLOW ,
  COALESCE(ACC_ISS_REQD, 0 ) AS ACC_ISS_REQD ,
  COALESCE(ACC_ISS_PRI_IDENT, 0 ) AS ACC_ISS_PRI_IDENT ,
  COALESCE(ACC_ISS_FORM_OF_STOCK, 0 ) AS ACC_ISS_FORM_OF_STOCK ,
  COALESCE(ACC_ISS_OTHER_IDENT, '' ) AS ACC_ISS_OTHER_IDENT ,
  COALESCE(DEAL_SET_RULE_ID, 0 ) AS DEAL_SET_RULE_ID ,
  COALESCE(DEAL_SET_RULE_MODIFY, 0 ) AS DEAL_SET_RULE_MODIFY ,
  COALESCE(DEAL_SET_MODE_FORECAST, 0 ) AS DEAL_SET_MODE_FORECAST ,
  COALESCE(DEAL_SET_RECURRING_CF, 0 ) AS DEAL_SET_RECURRING_CF ,
  COALESCE(DEAL_SET_MODE_DS, 0 ) AS DEAL_SET_MODE_DS ,
  COALESCE(EMBEDDED_OPTION, 0 ) AS EMBEDDED_OPTION ,
  COALESCE(EXSTYLE, 0 ) AS EXSTYLE ,
  COALESCE(STRIKPRICE, 0 ) AS STRIKPRICE ,
  COALESCE(ISSUE_FEE_APPLICABLE, 0 ) AS ISSUE_FEE_APPLICABLE ,
  COALESCE(DEF_PYMT_MSG_TYPE, 0 ) AS DEF_PYMT_MSG_TYPE ,
  COALESCE(EFFINNATURALCCY, '' ) AS EFFINNATURALCCY ,
  COALESCE(COUPON_DAYS_BASIS, 0 ) AS COUPON_DAYS_BASIS ,
  COALESCE(USE_DP_BASIS_PRICING, 0 ) AS USE_DP_BASIS_PRICING ,
  COALESCE(PAY_RECEIVE_TYPE, 0 ) AS PAY_RECEIVE_TYPE ,
  COALESCE(POSTING_TYPE, 0 ) AS POSTING_TYPE ,
  COALESCE(STAMP, 0 ) AS STAMP ,
  COALESCE(FINAL_CASHFLOW_ROUNDING, 0 ) AS FINAL_CASHFLOW_ROUNDING ,
  COALESCE(FCR_SETTLEMENT_METHOD, 0 ) AS FCR_SETTLEMENT_METHOD ,
  COALESCE(FCR_SETTLEMENT_DP, 0 ) AS FCR_SETTLEMENT_DP ,
  COALESCE(FCR_INCOME_METHOD, 0 ) AS FCR_INCOME_METHOD ,
  COALESCE(FCR_INCOME_DP, 0 ) AS FCR_INCOME_DP ,
  COALESCE(FCR_CAPITAL_METHOD, 0 ) AS FCR_CAPITAL_METHOD ,
  COALESCE(FCR_CAPITAL_DP, 0 ) AS FCR_CAPITAL_DP ,
  COALESCE(PRI_IDENT_FILTER_BY, 0 ) AS PRI_IDENT_FILTER_BY ,
  COALESCE(PRI_IDENT_FILTER_VAL, '' ) AS PRI_IDENT_FILTER_VAL ,
  COALESCE(SPLIT_SETTLEMENT, 0 ) AS SPLIT_SETTLEMENT ,
  COALESCE(SECISSUE_ID, '' ) AS SECISSUE_ID ,
  COALESCE(SECISSUE_DISPLAY, 0 ) AS SECISSUE_DISPLAY ,
  COALESCE(SECISSUE_REQUIRED, 0 ) AS SECISSUE_REQUIRED ,
  COALESCE(DEFAULT_IPA_FROM_CPARTY, 0 ) AS DEFAULT_IPA_FROM_CPARTY ,
  COALESCE(USE_SECISSUE_FOR_DEFAULTING, 0 ) AS USE_SECISSUE_FOR_DEFAULTING ,
  COALESCE(CPARTY, '' ) AS CPARTY ,
  COALESCE(ALLOW_ESTIMATED_PRICE, 0 ) AS ALLOW_ESTIMATED_PRICE ,
  COALESCE(ESTIMATED_SETTLE_HANDLING, 0 ) AS ESTIMATED_SETTLE_HANDLING ,
  COALESCE(ALLOW_PARTIAL_UNIT, 0 ) AS ALLOW_PARTIAL_UNIT ,
  COALESCE(PARTIAL_UNIT_DP, 0 ) AS PARTIAL_UNIT_DP ,
  COALESCE(PARTIAL_UNIT_ROUND_METHOD, 0 ) AS PARTIAL_UNIT_ROUND_METHOD ,
  COALESCE(PRICE_DP, 0 ) AS PRICE_DP ,
  COALESCE(PRICE_ROUND_METHOD, 0 ) AS PRICE_ROUND_METHOD ,
  COALESCE(UNIT_INSTRUMENT, '' ) AS UNIT_INSTRUMENT ,
  COALESCE(TRADING_STYLE, 0 ) AS TRADING_STYLE ,
  COALESCE(WARN_IF_SHORT, 0 ) AS WARN_IF_SHORT ,
  COALESCE(ADDITIONAL_TRADING_INFO, '' ) AS ADDITIONAL_TRADING_INFO ,
  COALESCE(ACTION_NBD_RULE, 0 ) AS ACTION_NBD_RULE ,
  COALESCE(CALCULATION_NBD_RULE, 0 ) AS CALCULATION_NBD_RULE ,
  COALESCE(UNIT_CPARTY, '' ) AS UNIT_CPARTY ,
  COALESCE(UNIT_BROKER, '' ) AS UNIT_BROKER ,
  COALESCE(CLS_SETTLEMENT, 0 ) AS CLS_SETTLEMENT ,
  COALESCE(BARRIER_VALIDATION, 0 ) AS BARRIER_VALIDATION ,
  COALESCE(DEFAULT_LATEST_PRICE, 0 ) AS DEFAULT_LATEST_PRICE ,
  COALESCE(SETTLEMENT_TYPE, 0 ) AS SETTLEMENT_TYPE ,
  COALESCE(SETTLEMENT_CCY, '' ) AS SETTLEMENT_CCY ,
  COALESCE(INTERCEPT_PASSFAIL, '' ) AS INTERCEPT_PASSFAIL ,
  COALESCE(C_LEVEL_PASSFAIL, '' ) AS C_LEVEL_PASSFAIL ,
  COALESCE(T_STATISTIC_PASSFAIL, '' ) AS T_STATISTIC_PASSFAIL ,
  COALESCE(T_STATISTIC_C_LEVEL, 0 ) AS T_STATISTIC_C_LEVEL ,
  COALESCE(T_STATISTIC_T_METHOD, '' ) AS T_STATISTIC_T_METHOD ,
  COALESCE(RETRO_INTERCEPT_PASSFAIL, '' ) AS RETRO_INTERCEPT_PASSFAIL ,
  COALESCE(RETRO_C_LEVEL_PASSFAIL, '' ) AS RETRO_C_LEVEL_PASSFAIL ,
  COALESCE(RETRO_T_STATISTIC_PASSFAIL, '' ) AS RETRO_T_STATISTIC_PASSFAIL ,
  COALESCE(RETRO_T_STATISTIC_C_LEVEL, 0 ) AS RETRO_T_STATISTIC_C_LEVEL ,
  COALESCE(RETRO_T_STATISTIC_T_METHOD, '' ) AS RETRO_T_STATISTIC_T_METHOD ,
  COALESCE(RETRO_S_SIZE, 0 ) AS RETRO_S_SIZE ,
  COALESCE(RETRO_S_METHOD, '' ) AS RETRO_S_METHOD ,
  COALESCE(ALLOW_MULTIPLE_RATESETS, 0 ) AS ALLOW_MULTIPLE_RATESETS 
 FROM  dw_tdata.COS_000_SECTYPE_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  THEKEY ,
  NAME ,
  CODE ,
  EXT_NAME ,
  TRANSTYPE ,
  OWNER ,
  THELEVEL ,
  FORMULA ,
  RATENAME ,
  BOR_INVEST ,
  CCY ,
  FACILITY ,
  DEALER ,
  MATURE_TYP ,
  TO_MATURE ,
  ISSUE_DT ,
  MATURE_DT ,
  N_MAT_TYP ,
  N_TO_MAT ,
  NOTION_DT ,
  STMTEND ,
  STMTDUE ,
  STMTQTR ,
  TO_SETTLE ,
  RATE_OFF ,
  COUPON ,
  COUPON_FRQ ,
  ACC_ISS ,
  ISS_PAY_AGENT ,
  SHOW_ISS_PAY_AGENT ,
  ISS_PAY_AGENT_REQ ,
  ALL_CFS_WITH_IPA ,
  EX_INT_DAY ,
  PRICE_METH ,
  SHOW_BOTH ,
  PRICE_TYPE ,
  MODIFIABLE ,
  PPH_ROUND ,
  PPH_CAPTAL ,
  PPH_INCOME ,
  PPH_CAPITAL_METHOD ,
  PPH_CAPITAL_DP ,
  PPH_INCOME_METHOD ,
  PPH_INCOME_DP ,
  PPH_SETTLE_METHOD ,
  PPH_SETTLE_DP ,
  PPH_DERIVE ,
  FIX_FLOAT ,
  INT_TIMING ,
  INT_CALC ,
  INT_DAYS ,
  CD_SELECT ,
  RD_SELECT ,
  ED_SELECT ,
  TRADABLE ,
  DRAWERS ,
  CLOSEOUT ,
  SETTLEMENT ,
  BASIS_RATE ,
  ASSET_LIAB ,
  CROSS_CCY ,
  DEAL_RATE ,
  FRA_ADV ,
  COUP_TYPE ,
  COUP_DATES ,
  MM_OR_SEC ,
  MARGIN ,
  MARGIN_ACT ,
  OPTSTYLE ,
  STOCKLOCAT ,
  NEW_ISSUE ,
  STOCKTYPE ,
  TOT_ISSUE ,
  BASIS_FREQ ,
  DELIVERY ,
  CCY_CONTR ,
  PRICE_FORM ,
  EXCHANGE ,
  ENTITY ,
  CLEAR_BROK ,
  EXEC_BROK ,
  SPAN_ID ,
  FUNGIBLE ,
  RATENOTYPE ,
  EURO_STYLE ,
  ASSET_BACK ,
  LEGAL_MAT ,
  SETT_TYPE ,
  SETT_TIME ,
  PREM_TIME ,
  OPTTYPE ,
  SETT_INST ,
  INDX_NAME ,
  ANNUITY ,
  ISS_INDX ,
  ISS_YIELD ,
  YIELD_TYPE ,
  FRAC_UNIT ,
  CF_NOTION ,
  SEC_DEF1 ,
  SEC_DEF2 ,
  TIME_OPT ,
  LC_TYPE ,
  CFSTATUS ,
  STRIKESPOT ,
  FPP_METHOD ,
  NOM_EFF ,
  COMP_FREQ ,
  SHOW_IRR ,
  PPH_AFTER ,
  MOD_FLAGS ,
  SHOW_BROK ,
  BROK_REQ ,
  INC_NOTION ,
  PRINC_EXCH ,
  FUT_DAYS ,
  PAY_FREQ ,
  REVIEW_FRQ ,
  CDI_DISC ,
  FUFTDAYS ,
  P_SECTYPE ,
  P_LINK ,
  P_DETAIL ,
  R_SECTYPE ,
  R_LINK ,
  R_DETAIL ,
  FT_KEY ,
  CUSIP_DEF ,
  ISIN_DEF ,
  CUSIN_SHOW ,
  CUSIN_REQ ,
  MOD_MASK ,
  MAND_MASK ,
  SHOW_MASK ,
  ISS_MOD ,
  INRNDMETH ,
  INRNDPLACE ,
  OPTCLASS ,
  DAY_WEIGHT ,
  REBATE_AT ,
  HEDGE_DDES ,
  ANALYSE01 ,
  ANALYSE02 ,
  ANALYSE03 ,
  ANALYSE04 ,
  ANALYSE05 ,
  ANALYSE06 ,
  ANALYSE07 ,
  ANALYSE08 ,
  ANALYSE09 ,
  ANALYSE10 ,
  ANALYSE11 ,
  ANALYSE12 ,
  ANALYSE13 ,
  ANALYSE14 ,
  ANALYSE15 ,
  ANALYSE16 ,
  ANALYSE17 ,
  ANALYSE18 ,
  ANALYSE19 ,
  ANALYSE20 ,
  HEDGETYPE ,
  NAT_RISK ,
  EFF_TYPE ,
  EFF_FREQ ,
  EF_PERIODS ,
  LOW_LIMIT ,
  UP_LIMIT ,
  SHORTCUT ,
  DOC_NO ,
  TRAN_OCI ,
  FREZ_OCI ,
  REL_OCI ,
  TR_OS_ST ,
  FR_OS_ST ,
  RE_OS_ST ,
  TR_OFSET ,
  FR_OFSET ,
  RE_OFSET ,
  TR_R_OFSET ,
  TR_R_OS_ST ,
  TRAN_ENT ,
  REL_ENT ,
  RATETYPE ,
  EF_PROSPEC ,
  EF_RANGE ,
  STD_INTERV ,
  S_METHOD ,
  S_SIZE ,
  R_SQUARED ,
  T_SLOPE ,
  T_SLOPE_UPPER ,
  TINTERCEPT ,
  TINTERCEPT_UPPER ,
  C_LEVEL ,
  STD_DEV ,
  T_METHOD ,
  EF_RETRO ,
  RETRO_INTERVAL ,
  RETRO_R_SQUARED ,
  RETRO_SLOPE_LOWER ,
  RETRO_SLOPE_UPPER ,
  RETRO_INTERCEPT_LOWER ,
  RETRO_INTERCEPT_UPPER ,
  RETRO_C_LEVEL ,
  RETRO_STD_DEV ,
  RETRO_T_METHOD ,
  F_REG_DATE ,
  DUAL_CCY ,
  COUPON_CCY ,
  SEPARATE_RATESET ,
  ASYMM_CUR_HOL ,
  INT_CALC_LOC ,
  USAGE ,
  IN_USE ,
  BTREE_LOW ,
  BTREE_HIGH ,
  SETTLE_NBD_RULE ,
  DATED_DATE ,
  FNL_PRD_METHOD ,
  FPP_EARLY_DISCOUNT ,
  FPP_ADJ_MATURITY ,
  FPP_NO_PPH_ROUNDING ,
  FPP_DAYS_BASIS ,
  FIRST_COUPON_DATE ,
  INCOME_ACCRUAL_BASIS ,
  ODD_FIRST_COUPON ,
  ODD_LAST_COUPON ,
  PENULTIMATE_COUPON_DATE ,
  YIELD_CONVENTION_ID ,
  DISCOUNT_DAYS_BASIS ,
  PRODUCT_ID ,
  NON_BUS_DEALS ,
  TEMPLATE ,
  NO_COUPON_ON_MATURITY ,
  GEN_STOCK_FLOW ,
  ACC_ISS_REQD ,
  ACC_ISS_PRI_IDENT ,
  ACC_ISS_FORM_OF_STOCK ,
  ACC_ISS_OTHER_IDENT ,
  DEAL_SET_RULE_ID ,
  DEAL_SET_RULE_MODIFY ,
  DEAL_SET_MODE_FORECAST ,
  DEAL_SET_RECURRING_CF ,
  DEAL_SET_MODE_DS ,
  EMBEDDED_OPTION ,
  EXSTYLE ,
  STRIKPRICE ,
  ISSUE_FEE_APPLICABLE ,
  DEF_PYMT_MSG_TYPE ,
  EFFINNATURALCCY ,
  COUPON_DAYS_BASIS ,
  USE_DP_BASIS_PRICING ,
  PAY_RECEIVE_TYPE ,
  POSTING_TYPE ,
  STAMP ,
  FINAL_CASHFLOW_ROUNDING ,
  FCR_SETTLEMENT_METHOD ,
  FCR_SETTLEMENT_DP ,
  FCR_INCOME_METHOD ,
  FCR_INCOME_DP ,
  FCR_CAPITAL_METHOD ,
  FCR_CAPITAL_DP ,
  PRI_IDENT_FILTER_BY ,
  PRI_IDENT_FILTER_VAL ,
  SPLIT_SETTLEMENT ,
  SECISSUE_ID ,
  SECISSUE_DISPLAY ,
  SECISSUE_REQUIRED ,
  DEFAULT_IPA_FROM_CPARTY ,
  USE_SECISSUE_FOR_DEFAULTING ,
  CPARTY ,
  ALLOW_ESTIMATED_PRICE ,
  ESTIMATED_SETTLE_HANDLING ,
  ALLOW_PARTIAL_UNIT ,
  PARTIAL_UNIT_DP ,
  PARTIAL_UNIT_ROUND_METHOD ,
  PRICE_DP ,
  PRICE_ROUND_METHOD ,
  UNIT_INSTRUMENT ,
  TRADING_STYLE ,
  WARN_IF_SHORT ,
  ADDITIONAL_TRADING_INFO ,
  ACTION_NBD_RULE ,
  CALCULATION_NBD_RULE ,
  UNIT_CPARTY ,
  UNIT_BROKER ,
  CLS_SETTLEMENT ,
  BARRIER_VALIDATION ,
  DEFAULT_LATEST_PRICE ,
  SETTLEMENT_TYPE ,
  SETTLEMENT_CCY ,
  INTERCEPT_PASSFAIL ,
  C_LEVEL_PASSFAIL ,
  T_STATISTIC_PASSFAIL ,
  T_STATISTIC_C_LEVEL ,
  T_STATISTIC_T_METHOD ,
  RETRO_INTERCEPT_PASSFAIL ,
  RETRO_C_LEVEL_PASSFAIL ,
  RETRO_T_STATISTIC_PASSFAIL ,
  RETRO_T_STATISTIC_C_LEVEL ,
  RETRO_T_STATISTIC_T_METHOD ,
  RETRO_S_SIZE ,
  RETRO_S_METHOD ,
  ALLOW_MULTIPLE_RATESETS 
 FROM dw_sdata.COS_000_SECTYPE 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.THEKEY = T.THEKEY
WHERE
(T.THEKEY IS NULL)
 OR N.NAME<>T.NAME
 OR N.CODE<>T.CODE
 OR N.EXT_NAME<>T.EXT_NAME
 OR N.TRANSTYPE<>T.TRANSTYPE
 OR N.OWNER<>T.OWNER
 OR N.THELEVEL<>T.THELEVEL
 OR N.FORMULA<>T.FORMULA
 OR N.RATENAME<>T.RATENAME
 OR N.BOR_INVEST<>T.BOR_INVEST
 OR N.CCY<>T.CCY
 OR N.FACILITY<>T.FACILITY
 OR N.DEALER<>T.DEALER
 OR N.MATURE_TYP<>T.MATURE_TYP
 OR N.TO_MATURE<>T.TO_MATURE
 OR N.ISSUE_DT<>T.ISSUE_DT
 OR N.MATURE_DT<>T.MATURE_DT
 OR N.N_MAT_TYP<>T.N_MAT_TYP
 OR N.N_TO_MAT<>T.N_TO_MAT
 OR N.NOTION_DT<>T.NOTION_DT
 OR N.STMTEND<>T.STMTEND
 OR N.STMTDUE<>T.STMTDUE
 OR N.STMTQTR<>T.STMTQTR
 OR N.TO_SETTLE<>T.TO_SETTLE
 OR N.RATE_OFF<>T.RATE_OFF
 OR N.COUPON<>T.COUPON
 OR N.COUPON_FRQ<>T.COUPON_FRQ
 OR N.ACC_ISS<>T.ACC_ISS
 OR N.ISS_PAY_AGENT<>T.ISS_PAY_AGENT
 OR N.SHOW_ISS_PAY_AGENT<>T.SHOW_ISS_PAY_AGENT
 OR N.ISS_PAY_AGENT_REQ<>T.ISS_PAY_AGENT_REQ
 OR N.ALL_CFS_WITH_IPA<>T.ALL_CFS_WITH_IPA
 OR N.EX_INT_DAY<>T.EX_INT_DAY
 OR N.PRICE_METH<>T.PRICE_METH
 OR N.SHOW_BOTH<>T.SHOW_BOTH
 OR N.PRICE_TYPE<>T.PRICE_TYPE
 OR N.MODIFIABLE<>T.MODIFIABLE
 OR N.PPH_ROUND<>T.PPH_ROUND
 OR N.PPH_CAPTAL<>T.PPH_CAPTAL
 OR N.PPH_INCOME<>T.PPH_INCOME
 OR N.PPH_CAPITAL_METHOD<>T.PPH_CAPITAL_METHOD
 OR N.PPH_CAPITAL_DP<>T.PPH_CAPITAL_DP
 OR N.PPH_INCOME_METHOD<>T.PPH_INCOME_METHOD
 OR N.PPH_INCOME_DP<>T.PPH_INCOME_DP
 OR N.PPH_SETTLE_METHOD<>T.PPH_SETTLE_METHOD
 OR N.PPH_SETTLE_DP<>T.PPH_SETTLE_DP
 OR N.PPH_DERIVE<>T.PPH_DERIVE
 OR N.FIX_FLOAT<>T.FIX_FLOAT
 OR N.INT_TIMING<>T.INT_TIMING
 OR N.INT_CALC<>T.INT_CALC
 OR N.INT_DAYS<>T.INT_DAYS
 OR N.CD_SELECT<>T.CD_SELECT
 OR N.RD_SELECT<>T.RD_SELECT
 OR N.ED_SELECT<>T.ED_SELECT
 OR N.TRADABLE<>T.TRADABLE
 OR N.DRAWERS<>T.DRAWERS
 OR N.CLOSEOUT<>T.CLOSEOUT
 OR N.SETTLEMENT<>T.SETTLEMENT
 OR N.BASIS_RATE<>T.BASIS_RATE
 OR N.ASSET_LIAB<>T.ASSET_LIAB
 OR N.CROSS_CCY<>T.CROSS_CCY
 OR N.DEAL_RATE<>T.DEAL_RATE
 OR N.FRA_ADV<>T.FRA_ADV
 OR N.COUP_TYPE<>T.COUP_TYPE
 OR N.COUP_DATES<>T.COUP_DATES
 OR N.MM_OR_SEC<>T.MM_OR_SEC
 OR N.MARGIN<>T.MARGIN
 OR N.MARGIN_ACT<>T.MARGIN_ACT
 OR N.OPTSTYLE<>T.OPTSTYLE
 OR N.STOCKLOCAT<>T.STOCKLOCAT
 OR N.NEW_ISSUE<>T.NEW_ISSUE
 OR N.STOCKTYPE<>T.STOCKTYPE
 OR N.TOT_ISSUE<>T.TOT_ISSUE
 OR N.BASIS_FREQ<>T.BASIS_FREQ
 OR N.DELIVERY<>T.DELIVERY
 OR N.CCY_CONTR<>T.CCY_CONTR
 OR N.PRICE_FORM<>T.PRICE_FORM
 OR N.EXCHANGE<>T.EXCHANGE
 OR N.ENTITY<>T.ENTITY
 OR N.CLEAR_BROK<>T.CLEAR_BROK
 OR N.EXEC_BROK<>T.EXEC_BROK
 OR N.SPAN_ID<>T.SPAN_ID
 OR N.FUNGIBLE<>T.FUNGIBLE
 OR N.RATENOTYPE<>T.RATENOTYPE
 OR N.EURO_STYLE<>T.EURO_STYLE
 OR N.ASSET_BACK<>T.ASSET_BACK
 OR N.LEGAL_MAT<>T.LEGAL_MAT
 OR N.SETT_TYPE<>T.SETT_TYPE
 OR N.SETT_TIME<>T.SETT_TIME
 OR N.PREM_TIME<>T.PREM_TIME
 OR N.OPTTYPE<>T.OPTTYPE
 OR N.SETT_INST<>T.SETT_INST
 OR N.INDX_NAME<>T.INDX_NAME
 OR N.ANNUITY<>T.ANNUITY
 OR N.ISS_INDX<>T.ISS_INDX
 OR N.ISS_YIELD<>T.ISS_YIELD
 OR N.YIELD_TYPE<>T.YIELD_TYPE
 OR N.FRAC_UNIT<>T.FRAC_UNIT
 OR N.CF_NOTION<>T.CF_NOTION
 OR N.SEC_DEF1<>T.SEC_DEF1
 OR N.SEC_DEF2<>T.SEC_DEF2
 OR N.TIME_OPT<>T.TIME_OPT
 OR N.LC_TYPE<>T.LC_TYPE
 OR N.CFSTATUS<>T.CFSTATUS
 OR N.STRIKESPOT<>T.STRIKESPOT
 OR N.FPP_METHOD<>T.FPP_METHOD
 OR N.NOM_EFF<>T.NOM_EFF
 OR N.COMP_FREQ<>T.COMP_FREQ
 OR N.SHOW_IRR<>T.SHOW_IRR
 OR N.PPH_AFTER<>T.PPH_AFTER
 OR N.MOD_FLAGS<>T.MOD_FLAGS
 OR N.SHOW_BROK<>T.SHOW_BROK
 OR N.BROK_REQ<>T.BROK_REQ
 OR N.INC_NOTION<>T.INC_NOTION
 OR N.PRINC_EXCH<>T.PRINC_EXCH
 OR N.FUT_DAYS<>T.FUT_DAYS
 OR N.PAY_FREQ<>T.PAY_FREQ
 OR N.REVIEW_FRQ<>T.REVIEW_FRQ
 OR N.CDI_DISC<>T.CDI_DISC
 OR N.FUFTDAYS<>T.FUFTDAYS
 OR N.P_SECTYPE<>T.P_SECTYPE
 OR N.P_LINK<>T.P_LINK
 OR N.P_DETAIL<>T.P_DETAIL
 OR N.R_SECTYPE<>T.R_SECTYPE
 OR N.R_LINK<>T.R_LINK
 OR N.R_DETAIL<>T.R_DETAIL
 OR N.FT_KEY<>T.FT_KEY
 OR N.CUSIP_DEF<>T.CUSIP_DEF
 OR N.ISIN_DEF<>T.ISIN_DEF
 OR N.CUSIN_SHOW<>T.CUSIN_SHOW
 OR N.CUSIN_REQ<>T.CUSIN_REQ
 OR N.MOD_MASK<>T.MOD_MASK
 OR N.MAND_MASK<>T.MAND_MASK
 OR N.SHOW_MASK<>T.SHOW_MASK
 OR N.ISS_MOD<>T.ISS_MOD
 OR N.INRNDMETH<>T.INRNDMETH
 OR N.INRNDPLACE<>T.INRNDPLACE
 OR N.OPTCLASS<>T.OPTCLASS
 OR N.DAY_WEIGHT<>T.DAY_WEIGHT
 OR N.REBATE_AT<>T.REBATE_AT
 OR N.HEDGE_DDES<>T.HEDGE_DDES
 OR N.ANALYSE01<>T.ANALYSE01
 OR N.ANALYSE02<>T.ANALYSE02
 OR N.ANALYSE03<>T.ANALYSE03
 OR N.ANALYSE04<>T.ANALYSE04
 OR N.ANALYSE05<>T.ANALYSE05
 OR N.ANALYSE06<>T.ANALYSE06
 OR N.ANALYSE07<>T.ANALYSE07
 OR N.ANALYSE08<>T.ANALYSE08
 OR N.ANALYSE09<>T.ANALYSE09
 OR N.ANALYSE10<>T.ANALYSE10
 OR N.ANALYSE11<>T.ANALYSE11
 OR N.ANALYSE12<>T.ANALYSE12
 OR N.ANALYSE13<>T.ANALYSE13
 OR N.ANALYSE14<>T.ANALYSE14
 OR N.ANALYSE15<>T.ANALYSE15
 OR N.ANALYSE16<>T.ANALYSE16
 OR N.ANALYSE17<>T.ANALYSE17
 OR N.ANALYSE18<>T.ANALYSE18
 OR N.ANALYSE19<>T.ANALYSE19
 OR N.ANALYSE20<>T.ANALYSE20
 OR N.HEDGETYPE<>T.HEDGETYPE
 OR N.NAT_RISK<>T.NAT_RISK
 OR N.EFF_TYPE<>T.EFF_TYPE
 OR N.EFF_FREQ<>T.EFF_FREQ
 OR N.EF_PERIODS<>T.EF_PERIODS
 OR N.LOW_LIMIT<>T.LOW_LIMIT
 OR N.UP_LIMIT<>T.UP_LIMIT
 OR N.SHORTCUT<>T.SHORTCUT
 OR N.DOC_NO<>T.DOC_NO
 OR N.TRAN_OCI<>T.TRAN_OCI
 OR N.FREZ_OCI<>T.FREZ_OCI
 OR N.REL_OCI<>T.REL_OCI
 OR N.TR_OS_ST<>T.TR_OS_ST
 OR N.FR_OS_ST<>T.FR_OS_ST
 OR N.RE_OS_ST<>T.RE_OS_ST
 OR N.TR_OFSET<>T.TR_OFSET
 OR N.FR_OFSET<>T.FR_OFSET
 OR N.RE_OFSET<>T.RE_OFSET
 OR N.TR_R_OFSET<>T.TR_R_OFSET
 OR N.TR_R_OS_ST<>T.TR_R_OS_ST
 OR N.TRAN_ENT<>T.TRAN_ENT
 OR N.REL_ENT<>T.REL_ENT
 OR N.RATETYPE<>T.RATETYPE
 OR N.EF_PROSPEC<>T.EF_PROSPEC
 OR N.EF_RANGE<>T.EF_RANGE
 OR N.STD_INTERV<>T.STD_INTERV
 OR N.S_METHOD<>T.S_METHOD
 OR N.S_SIZE<>T.S_SIZE
 OR N.R_SQUARED<>T.R_SQUARED
 OR N.T_SLOPE<>T.T_SLOPE
 OR N.T_SLOPE_UPPER<>T.T_SLOPE_UPPER
 OR N.TINTERCEPT<>T.TINTERCEPT
 OR N.TINTERCEPT_UPPER<>T.TINTERCEPT_UPPER
 OR N.C_LEVEL<>T.C_LEVEL
 OR N.STD_DEV<>T.STD_DEV
 OR N.T_METHOD<>T.T_METHOD
 OR N.EF_RETRO<>T.EF_RETRO
 OR N.RETRO_INTERVAL<>T.RETRO_INTERVAL
 OR N.RETRO_R_SQUARED<>T.RETRO_R_SQUARED
 OR N.RETRO_SLOPE_LOWER<>T.RETRO_SLOPE_LOWER
 OR N.RETRO_SLOPE_UPPER<>T.RETRO_SLOPE_UPPER
 OR N.RETRO_INTERCEPT_LOWER<>T.RETRO_INTERCEPT_LOWER
 OR N.RETRO_INTERCEPT_UPPER<>T.RETRO_INTERCEPT_UPPER
 OR N.RETRO_C_LEVEL<>T.RETRO_C_LEVEL
 OR N.RETRO_STD_DEV<>T.RETRO_STD_DEV
 OR N.RETRO_T_METHOD<>T.RETRO_T_METHOD
 OR N.F_REG_DATE<>T.F_REG_DATE
 OR N.DUAL_CCY<>T.DUAL_CCY
 OR N.COUPON_CCY<>T.COUPON_CCY
 OR N.SEPARATE_RATESET<>T.SEPARATE_RATESET
 OR N.ASYMM_CUR_HOL<>T.ASYMM_CUR_HOL
 OR N.INT_CALC_LOC<>T.INT_CALC_LOC
 OR N.USAGE<>T.USAGE
 OR N.IN_USE<>T.IN_USE
 OR N.BTREE_LOW<>T.BTREE_LOW
 OR N.BTREE_HIGH<>T.BTREE_HIGH
 OR N.SETTLE_NBD_RULE<>T.SETTLE_NBD_RULE
 OR N.DATED_DATE<>T.DATED_DATE
 OR N.FNL_PRD_METHOD<>T.FNL_PRD_METHOD
 OR N.FPP_EARLY_DISCOUNT<>T.FPP_EARLY_DISCOUNT
 OR N.FPP_ADJ_MATURITY<>T.FPP_ADJ_MATURITY
 OR N.FPP_NO_PPH_ROUNDING<>T.FPP_NO_PPH_ROUNDING
 OR N.FPP_DAYS_BASIS<>T.FPP_DAYS_BASIS
 OR N.FIRST_COUPON_DATE<>T.FIRST_COUPON_DATE
 OR N.INCOME_ACCRUAL_BASIS<>T.INCOME_ACCRUAL_BASIS
 OR N.ODD_FIRST_COUPON<>T.ODD_FIRST_COUPON
 OR N.ODD_LAST_COUPON<>T.ODD_LAST_COUPON
 OR N.PENULTIMATE_COUPON_DATE<>T.PENULTIMATE_COUPON_DATE
 OR N.YIELD_CONVENTION_ID<>T.YIELD_CONVENTION_ID
 OR N.DISCOUNT_DAYS_BASIS<>T.DISCOUNT_DAYS_BASIS
 OR N.PRODUCT_ID<>T.PRODUCT_ID
 OR N.NON_BUS_DEALS<>T.NON_BUS_DEALS
 OR N.TEMPLATE<>T.TEMPLATE
 OR N.NO_COUPON_ON_MATURITY<>T.NO_COUPON_ON_MATURITY
 OR N.GEN_STOCK_FLOW<>T.GEN_STOCK_FLOW
 OR N.ACC_ISS_REQD<>T.ACC_ISS_REQD
 OR N.ACC_ISS_PRI_IDENT<>T.ACC_ISS_PRI_IDENT
 OR N.ACC_ISS_FORM_OF_STOCK<>T.ACC_ISS_FORM_OF_STOCK
 OR N.ACC_ISS_OTHER_IDENT<>T.ACC_ISS_OTHER_IDENT
 OR N.DEAL_SET_RULE_ID<>T.DEAL_SET_RULE_ID
 OR N.DEAL_SET_RULE_MODIFY<>T.DEAL_SET_RULE_MODIFY
 OR N.DEAL_SET_MODE_FORECAST<>T.DEAL_SET_MODE_FORECAST
 OR N.DEAL_SET_RECURRING_CF<>T.DEAL_SET_RECURRING_CF
 OR N.DEAL_SET_MODE_DS<>T.DEAL_SET_MODE_DS
 OR N.EMBEDDED_OPTION<>T.EMBEDDED_OPTION
 OR N.EXSTYLE<>T.EXSTYLE
 OR N.STRIKPRICE<>T.STRIKPRICE
 OR N.ISSUE_FEE_APPLICABLE<>T.ISSUE_FEE_APPLICABLE
 OR N.DEF_PYMT_MSG_TYPE<>T.DEF_PYMT_MSG_TYPE
 OR N.EFFINNATURALCCY<>T.EFFINNATURALCCY
 OR N.COUPON_DAYS_BASIS<>T.COUPON_DAYS_BASIS
 OR N.USE_DP_BASIS_PRICING<>T.USE_DP_BASIS_PRICING
 OR N.PAY_RECEIVE_TYPE<>T.PAY_RECEIVE_TYPE
 OR N.POSTING_TYPE<>T.POSTING_TYPE
 OR N.STAMP<>T.STAMP
 OR N.FINAL_CASHFLOW_ROUNDING<>T.FINAL_CASHFLOW_ROUNDING
 OR N.FCR_SETTLEMENT_METHOD<>T.FCR_SETTLEMENT_METHOD
 OR N.FCR_SETTLEMENT_DP<>T.FCR_SETTLEMENT_DP
 OR N.FCR_INCOME_METHOD<>T.FCR_INCOME_METHOD
 OR N.FCR_INCOME_DP<>T.FCR_INCOME_DP
 OR N.FCR_CAPITAL_METHOD<>T.FCR_CAPITAL_METHOD
 OR N.FCR_CAPITAL_DP<>T.FCR_CAPITAL_DP
 OR N.PRI_IDENT_FILTER_BY<>T.PRI_IDENT_FILTER_BY
 OR N.PRI_IDENT_FILTER_VAL<>T.PRI_IDENT_FILTER_VAL
 OR N.SPLIT_SETTLEMENT<>T.SPLIT_SETTLEMENT
 OR N.SECISSUE_ID<>T.SECISSUE_ID
 OR N.SECISSUE_DISPLAY<>T.SECISSUE_DISPLAY
 OR N.SECISSUE_REQUIRED<>T.SECISSUE_REQUIRED
 OR N.DEFAULT_IPA_FROM_CPARTY<>T.DEFAULT_IPA_FROM_CPARTY
 OR N.USE_SECISSUE_FOR_DEFAULTING<>T.USE_SECISSUE_FOR_DEFAULTING
 OR N.CPARTY<>T.CPARTY
 OR N.ALLOW_ESTIMATED_PRICE<>T.ALLOW_ESTIMATED_PRICE
 OR N.ESTIMATED_SETTLE_HANDLING<>T.ESTIMATED_SETTLE_HANDLING
 OR N.ALLOW_PARTIAL_UNIT<>T.ALLOW_PARTIAL_UNIT
 OR N.PARTIAL_UNIT_DP<>T.PARTIAL_UNIT_DP
 OR N.PARTIAL_UNIT_ROUND_METHOD<>T.PARTIAL_UNIT_ROUND_METHOD
 OR N.PRICE_DP<>T.PRICE_DP
 OR N.PRICE_ROUND_METHOD<>T.PRICE_ROUND_METHOD
 OR N.UNIT_INSTRUMENT<>T.UNIT_INSTRUMENT
 OR N.TRADING_STYLE<>T.TRADING_STYLE
 OR N.WARN_IF_SHORT<>T.WARN_IF_SHORT
 OR N.ADDITIONAL_TRADING_INFO<>T.ADDITIONAL_TRADING_INFO
 OR N.ACTION_NBD_RULE<>T.ACTION_NBD_RULE
 OR N.CALCULATION_NBD_RULE<>T.CALCULATION_NBD_RULE
 OR N.UNIT_CPARTY<>T.UNIT_CPARTY
 OR N.UNIT_BROKER<>T.UNIT_BROKER
 OR N.CLS_SETTLEMENT<>T.CLS_SETTLEMENT
 OR N.BARRIER_VALIDATION<>T.BARRIER_VALIDATION
 OR N.DEFAULT_LATEST_PRICE<>T.DEFAULT_LATEST_PRICE
 OR N.SETTLEMENT_TYPE<>T.SETTLEMENT_TYPE
 OR N.SETTLEMENT_CCY<>T.SETTLEMENT_CCY
 OR N.INTERCEPT_PASSFAIL<>T.INTERCEPT_PASSFAIL
 OR N.C_LEVEL_PASSFAIL<>T.C_LEVEL_PASSFAIL
 OR N.T_STATISTIC_PASSFAIL<>T.T_STATISTIC_PASSFAIL
 OR N.T_STATISTIC_C_LEVEL<>T.T_STATISTIC_C_LEVEL
 OR N.T_STATISTIC_T_METHOD<>T.T_STATISTIC_T_METHOD
 OR N.RETRO_INTERCEPT_PASSFAIL<>T.RETRO_INTERCEPT_PASSFAIL
 OR N.RETRO_C_LEVEL_PASSFAIL<>T.RETRO_C_LEVEL_PASSFAIL
 OR N.RETRO_T_STATISTIC_PASSFAIL<>T.RETRO_T_STATISTIC_PASSFAIL
 OR N.RETRO_T_STATISTIC_C_LEVEL<>T.RETRO_T_STATISTIC_C_LEVEL
 OR N.RETRO_T_STATISTIC_T_METHOD<>T.RETRO_T_STATISTIC_T_METHOD
 OR N.RETRO_S_SIZE<>T.RETRO_S_SIZE
 OR N.RETRO_S_METHOD<>T.RETRO_S_METHOD
 OR N.ALLOW_MULTIPLE_RATESETS<>T.ALLOW_MULTIPLE_RATESETS
;

--Step3:
UPDATE dw_sdata.COS_000_SECTYPE P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_159
WHERE P.End_Dt=DATE('2100-12-31')
AND P.THEKEY=T_159.THEKEY
;

--Step4:
INSERT  INTO dw_sdata.COS_000_SECTYPE SELECT * FROM T_159;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
