#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.COS_000_MMDEALS WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.COS_000_MMDEALS SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_156 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.COS_000_MMDEALS WHERE 1=0;

--Step2:
INSERT  INTO T_156 (
  DEAL_NO,
  BOR_INVEST,
  BUY_SELL,
  REMAIN_FV,
  INT_RATE,
  INT_MARGIN,
  ACT_MARGIN,
  ISS_INDX,
  FIX_FLOAT,
  FT_KEY,
  FORMULA,
  ACCOUNTING,
  INT_CALC_LOC,
  INT_TIMING,
  INT_DAYS,
  PREVCOUP,
  NEXTCOUP,
  ISSUE_DT,
  REVIEW_DT,
  RATE_OFF,
  REVIEW_FRQ,
  PAY_DT,
  PAY_FRQ,
  COUPON,
  LAST_COUP,
  EX_DAYS,
  COUP_TYPE,
  COUP_DATES,
  COUPON_FRQ,
  FUFTDAYS,
  PRICE_METH,
  PRICE_TYPE,
  PPH_ROUND,
  PPH_CAPTAL,
  PPH_INCOME,
  PPH_CAPITAL_METHOD,
  PPH_CAPITAL_DP,
  PPH_INCOME_METHOD,
  PPH_INCOME_DP,
  PPH_SETTLE_METHOD,
  PPH_SETTLE_DP,
  PPH_AFTER,
  PPH_DERIVE,
  FINAL_CASHFLOW_ROUNDING,
  FCR_SETTLEMENT_METHOD,
  FCR_SETTLEMENT_DP,
  FCR_INCOME_METHOD,
  FCR_INCOME_DP,
  FCR_CAPITAL_METHOD,
  FCR_CAPITAL_DP,
  CAPITALPPH,
  INCOMEPPH,
  SETTLEPPH,
  BOND_PRICE,
  SHOW_BOTH,
  EX_CUM_NEW,
  ACC_ISS,
  ISS_PAY_AGENT,
  SHOW_ISS_PAY_AGENT,
  ISS_PAY_AGENT_REQ,
  ALL_CFS_WITH_IPA,
  MATURE_TYP,
  CLOSEOUT,
  TRADABLE,
  STMTEND,
  STMTDUE,
  STMTQTR,
  MM_OR_SEC,
  DEF_BORINV,
  INT_AMT,
  SETTLEMENT,
  BASIS,
  BASIS_FREQ,
  COUP_MARGN,
  PURCH_YLD,
  STOCKLOCAT,
  NOTION_DT,
  REPO_TYPE,
  REPO_LINK,
  STCKMATURE,
  ASSET_BACK,
  LEGAL_MAT,
  IODEAL_NO,
  YIELD_TYPE,
  FRAC_UNIT,
  INTPAYMETH,
  FPP_METHOD,
  NOM_EFF,
  COMP_FREQ,
  CDI_DISC,
  ORIG_IRR,
  SHOW_IRR,
  CALLABLE,
  CALL_OPEN,
  BSACCTMETH,
  CONTINGENT,
  INRNDMETH,
  INRNDPLACE,
  SEPARATE_RATESET,
  DUAL_CCY,
  COUPON_CCY,
  COUPON_FV,
  EXCH_RATE,
  DATED_DATE,
  FNL_PRD_METHOD,
  FPP_EARLY_DISCOUNT,
  FPP_ADJ_MATURITY,
  FPP_NO_PPH_ROUNDING,
  FPP_DAYS_BASIS,
  FIRST_COUPON_DATE,
  INCOME_ACCRUAL_BASIS,
  ODD_FIRST_COUPON,
  ODD_LAST_COUPON,
  PENULTIMATE_COUPON_DATE,
  YIELD_METHOD,
  YIELD_COMPOUND_FREQ,
  YIELD_NETT_OF_TAX,
  DISCOUNT_DAYS_BASIS,
  NO_COUPON_ON_MATURITY,
  GEN_STOCK_FLOW,
  OPTTYPE,
  EXSTYLE,
  STRIKPRICE,
  YIELD_TO_FIRST_EXERCISE,
  PREM_ACRLP,
  COUPON_DAYS_BASIS,
  ANALYSE01,
  ANALYSE02,
  ANALYSE03,
  ANALYSE04,
  ANALYSE05,
  ANALYSE06,
  ANALYSE07,
  ANALYSE08,
  ANALYSE09,
  ANALYSE10,
  CAPITAL_ACCRUAL_METHOD,
  ISSUE_FEE_ACCRUAL_METHOD,
  ISSUE_FEE,
  ISSUE_FEE_PAYMENT_TYPE,
  ISSUE_FEE_ACRL_TRANS_DT,
  AMORT_COST_CALENDAR_ID,
  USE_DP_BASIS_PRICING,
  ACRL_SL_DAYS_RULE,
  DO_CONTINGENT_SETTLEMENT,
  CONTINGENT_SETTLEMENT_METHOD,
  DO_CONTINGENT_MATURITY,
  CONTINGENT_MATURITY_METHOD,
  INT_ACCR_AMORT,
  FV_INDEX_ACCRUAL_METHOD,
  FV_INDEX_ACRL_TRANS_DT,
  DEFAULT_IPA_FROM_CPARTY,
  USE_SECISSUE_FOR_DEFAULTING,
  STAMP,
  ALLOW_MULTIPLE_RATESETS,
  start_dt,
  end_dt)
SELECT
  N.DEAL_NO,
  N.BOR_INVEST,
  N.BUY_SELL,
  N.REMAIN_FV,
  N.INT_RATE,
  N.INT_MARGIN,
  N.ACT_MARGIN,
  N.ISS_INDX,
  N.FIX_FLOAT,
  N.FT_KEY,
  N.FORMULA,
  N.ACCOUNTING,
  N.INT_CALC_LOC,
  N.INT_TIMING,
  N.INT_DAYS,
  N.PREVCOUP,
  N.NEXTCOUP,
  N.ISSUE_DT,
  N.REVIEW_DT,
  N.RATE_OFF,
  N.REVIEW_FRQ,
  N.PAY_DT,
  N.PAY_FRQ,
  N.COUPON,
  N.LAST_COUP,
  N.EX_DAYS,
  N.COUP_TYPE,
  N.COUP_DATES,
  N.COUPON_FRQ,
  N.FUFTDAYS,
  N.PRICE_METH,
  N.PRICE_TYPE,
  N.PPH_ROUND,
  N.PPH_CAPTAL,
  N.PPH_INCOME,
  N.PPH_CAPITAL_METHOD,
  N.PPH_CAPITAL_DP,
  N.PPH_INCOME_METHOD,
  N.PPH_INCOME_DP,
  N.PPH_SETTLE_METHOD,
  N.PPH_SETTLE_DP,
  N.PPH_AFTER,
  N.PPH_DERIVE,
  N.FINAL_CASHFLOW_ROUNDING,
  N.FCR_SETTLEMENT_METHOD,
  N.FCR_SETTLEMENT_DP,
  N.FCR_INCOME_METHOD,
  N.FCR_INCOME_DP,
  N.FCR_CAPITAL_METHOD,
  N.FCR_CAPITAL_DP,
  N.CAPITALPPH,
  N.INCOMEPPH,
  N.SETTLEPPH,
  N.BOND_PRICE,
  N.SHOW_BOTH,
  N.EX_CUM_NEW,
  N.ACC_ISS,
  N.ISS_PAY_AGENT,
  N.SHOW_ISS_PAY_AGENT,
  N.ISS_PAY_AGENT_REQ,
  N.ALL_CFS_WITH_IPA,
  N.MATURE_TYP,
  N.CLOSEOUT,
  N.TRADABLE,
  N.STMTEND,
  N.STMTDUE,
  N.STMTQTR,
  N.MM_OR_SEC,
  N.DEF_BORINV,
  N.INT_AMT,
  N.SETTLEMENT,
  N.BASIS,
  N.BASIS_FREQ,
  N.COUP_MARGN,
  N.PURCH_YLD,
  N.STOCKLOCAT,
  N.NOTION_DT,
  N.REPO_TYPE,
  N.REPO_LINK,
  N.STCKMATURE,
  N.ASSET_BACK,
  N.LEGAL_MAT,
  N.IODEAL_NO,
  N.YIELD_TYPE,
  N.FRAC_UNIT,
  N.INTPAYMETH,
  N.FPP_METHOD,
  N.NOM_EFF,
  N.COMP_FREQ,
  N.CDI_DISC,
  N.ORIG_IRR,
  N.SHOW_IRR,
  N.CALLABLE,
  N.CALL_OPEN,
  N.BSACCTMETH,
  N.CONTINGENT,
  N.INRNDMETH,
  N.INRNDPLACE,
  N.SEPARATE_RATESET,
  N.DUAL_CCY,
  N.COUPON_CCY,
  N.COUPON_FV,
  N.EXCH_RATE,
  N.DATED_DATE,
  N.FNL_PRD_METHOD,
  N.FPP_EARLY_DISCOUNT,
  N.FPP_ADJ_MATURITY,
  N.FPP_NO_PPH_ROUNDING,
  N.FPP_DAYS_BASIS,
  N.FIRST_COUPON_DATE,
  N.INCOME_ACCRUAL_BASIS,
  N.ODD_FIRST_COUPON,
  N.ODD_LAST_COUPON,
  N.PENULTIMATE_COUPON_DATE,
  N.YIELD_METHOD,
  N.YIELD_COMPOUND_FREQ,
  N.YIELD_NETT_OF_TAX,
  N.DISCOUNT_DAYS_BASIS,
  N.NO_COUPON_ON_MATURITY,
  N.GEN_STOCK_FLOW,
  N.OPTTYPE,
  N.EXSTYLE,
  N.STRIKPRICE,
  N.YIELD_TO_FIRST_EXERCISE,
  N.PREM_ACRLP,
  N.COUPON_DAYS_BASIS,
  N.ANALYSE01,
  N.ANALYSE02,
  N.ANALYSE03,
  N.ANALYSE04,
  N.ANALYSE05,
  N.ANALYSE06,
  N.ANALYSE07,
  N.ANALYSE08,
  N.ANALYSE09,
  N.ANALYSE10,
  N.CAPITAL_ACCRUAL_METHOD,
  N.ISSUE_FEE_ACCRUAL_METHOD,
  N.ISSUE_FEE,
  N.ISSUE_FEE_PAYMENT_TYPE,
  N.ISSUE_FEE_ACRL_TRANS_DT,
  N.AMORT_COST_CALENDAR_ID,
  N.USE_DP_BASIS_PRICING,
  N.ACRL_SL_DAYS_RULE,
  N.DO_CONTINGENT_SETTLEMENT,
  N.CONTINGENT_SETTLEMENT_METHOD,
  N.DO_CONTINGENT_MATURITY,
  N.CONTINGENT_MATURITY_METHOD,
  N.INT_ACCR_AMORT,
  N.FV_INDEX_ACCRUAL_METHOD,
  N.FV_INDEX_ACRL_TRANS_DT,
  N.DEFAULT_IPA_FROM_CPARTY,
  N.USE_SECISSUE_FOR_DEFAULTING,
  N.STAMP,
  N.ALLOW_MULTIPLE_RATESETS,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(DEAL_NO, 0 ) AS DEAL_NO ,
  COALESCE(BOR_INVEST, '' ) AS BOR_INVEST ,
  COALESCE(BUY_SELL, '' ) AS BUY_SELL ,
  COALESCE(REMAIN_FV, 0 ) AS REMAIN_FV ,
  COALESCE(INT_RATE, 0 ) AS INT_RATE ,
  COALESCE(INT_MARGIN, 0 ) AS INT_MARGIN ,
  COALESCE(ACT_MARGIN, 0 ) AS ACT_MARGIN ,
  COALESCE(ISS_INDX, 0 ) AS ISS_INDX ,
  COALESCE(FIX_FLOAT, '' ) AS FIX_FLOAT ,
  COALESCE(FT_KEY, 0 ) AS FT_KEY ,
  COALESCE(FORMULA, '' ) AS FORMULA ,
  COALESCE(ACCOUNTING, '' ) AS ACCOUNTING ,
  COALESCE(INT_CALC_LOC, 0 ) AS INT_CALC_LOC ,
  COALESCE(INT_TIMING, '' ) AS INT_TIMING ,
  COALESCE(INT_DAYS, '' ) AS INT_DAYS ,
  COALESCE(PREVCOUP, '' ) AS PREVCOUP ,
  COALESCE(NEXTCOUP, '' ) AS NEXTCOUP ,
  COALESCE(ISSUE_DT, '' ) AS ISSUE_DT ,
  COALESCE(REVIEW_DT, '' ) AS REVIEW_DT ,
  COALESCE(RATE_OFF, 0 ) AS RATE_OFF ,
  COALESCE(REVIEW_FRQ, '' ) AS REVIEW_FRQ ,
  COALESCE(PAY_DT, '' ) AS PAY_DT ,
  COALESCE(PAY_FRQ, '' ) AS PAY_FRQ ,
  COALESCE(COUPON, 0 ) AS COUPON ,
  COALESCE(LAST_COUP, 0 ) AS LAST_COUP ,
  COALESCE(EX_DAYS, '' ) AS EX_DAYS ,
  COALESCE(COUP_TYPE, '' ) AS COUP_TYPE ,
  COALESCE(COUP_DATES, '' ) AS COUP_DATES ,
  COALESCE(COUPON_FRQ, '' ) AS COUPON_FRQ ,
  COALESCE(FUFTDAYS, '' ) AS FUFTDAYS ,
  COALESCE(PRICE_METH, '' ) AS PRICE_METH ,
  COALESCE(PRICE_TYPE, '' ) AS PRICE_TYPE ,
  COALESCE(PPH_ROUND, '' ) AS PPH_ROUND ,
  COALESCE(PPH_CAPTAL, '' ) AS PPH_CAPTAL ,
  COALESCE(PPH_INCOME, '' ) AS PPH_INCOME ,
  COALESCE(PPH_CAPITAL_METHOD, 0 ) AS PPH_CAPITAL_METHOD ,
  COALESCE(PPH_CAPITAL_DP, 0 ) AS PPH_CAPITAL_DP ,
  COALESCE(PPH_INCOME_METHOD, 0 ) AS PPH_INCOME_METHOD ,
  COALESCE(PPH_INCOME_DP, 0 ) AS PPH_INCOME_DP ,
  COALESCE(PPH_SETTLE_METHOD, 0 ) AS PPH_SETTLE_METHOD ,
  COALESCE(PPH_SETTLE_DP, 0 ) AS PPH_SETTLE_DP ,
  COALESCE(PPH_AFTER, '' ) AS PPH_AFTER ,
  COALESCE(PPH_DERIVE, '' ) AS PPH_DERIVE ,
  COALESCE(FINAL_CASHFLOW_ROUNDING, 0 ) AS FINAL_CASHFLOW_ROUNDING ,
  COALESCE(FCR_SETTLEMENT_METHOD, 0 ) AS FCR_SETTLEMENT_METHOD ,
  COALESCE(FCR_SETTLEMENT_DP, 0 ) AS FCR_SETTLEMENT_DP ,
  COALESCE(FCR_INCOME_METHOD, 0 ) AS FCR_INCOME_METHOD ,
  COALESCE(FCR_INCOME_DP, 0 ) AS FCR_INCOME_DP ,
  COALESCE(FCR_CAPITAL_METHOD, 0 ) AS FCR_CAPITAL_METHOD ,
  COALESCE(FCR_CAPITAL_DP, 0 ) AS FCR_CAPITAL_DP ,
  COALESCE(CAPITALPPH, 0 ) AS CAPITALPPH ,
  COALESCE(INCOMEPPH, 0 ) AS INCOMEPPH ,
  COALESCE(SETTLEPPH, 0 ) AS SETTLEPPH ,
  COALESCE(BOND_PRICE, 0 ) AS BOND_PRICE ,
  COALESCE(SHOW_BOTH, '' ) AS SHOW_BOTH ,
  COALESCE(EX_CUM_NEW, '' ) AS EX_CUM_NEW ,
  COALESCE(ACC_ISS, '' ) AS ACC_ISS ,
  COALESCE(ISS_PAY_AGENT, '' ) AS ISS_PAY_AGENT ,
  COALESCE(SHOW_ISS_PAY_AGENT, 0 ) AS SHOW_ISS_PAY_AGENT ,
  COALESCE(ISS_PAY_AGENT_REQ, 0 ) AS ISS_PAY_AGENT_REQ ,
  COALESCE(ALL_CFS_WITH_IPA, 0 ) AS ALL_CFS_WITH_IPA ,
  COALESCE(MATURE_TYP, '' ) AS MATURE_TYP ,
  COALESCE(CLOSEOUT, '' ) AS CLOSEOUT ,
  COALESCE(TRADABLE, '' ) AS TRADABLE ,
  COALESCE(STMTEND, '' ) AS STMTEND ,
  COALESCE(STMTDUE, '' ) AS STMTDUE ,
  COALESCE(STMTQTR, '' ) AS STMTQTR ,
  COALESCE(MM_OR_SEC, '' ) AS MM_OR_SEC ,
  COALESCE(DEF_BORINV, '' ) AS DEF_BORINV ,
  COALESCE(INT_AMT, 0 ) AS INT_AMT ,
  COALESCE(SETTLEMENT, 0 ) AS SETTLEMENT ,
  COALESCE(BASIS, '' ) AS BASIS ,
  COALESCE(BASIS_FREQ, '' ) AS BASIS_FREQ ,
  COALESCE(COUP_MARGN, 0 ) AS COUP_MARGN ,
  COALESCE(PURCH_YLD, 0 ) AS PURCH_YLD ,
  COALESCE(STOCKLOCAT, '' ) AS STOCKLOCAT ,
  COALESCE(NOTION_DT, '' ) AS NOTION_DT ,
  COALESCE(REPO_TYPE, '' ) AS REPO_TYPE ,
  COALESCE(REPO_LINK, 0 ) AS REPO_LINK ,
  COALESCE(STCKMATURE, '' ) AS STCKMATURE ,
  COALESCE(ASSET_BACK, '' ) AS ASSET_BACK ,
  COALESCE(LEGAL_MAT, '' ) AS LEGAL_MAT ,
  COALESCE(IODEAL_NO, 0 ) AS IODEAL_NO ,
  COALESCE(YIELD_TYPE, '' ) AS YIELD_TYPE ,
  COALESCE(FRAC_UNIT, 0 ) AS FRAC_UNIT ,
  COALESCE(INTPAYMETH, '' ) AS INTPAYMETH ,
  COALESCE(FPP_METHOD, '' ) AS FPP_METHOD ,
  COALESCE(NOM_EFF, '' ) AS NOM_EFF ,
  COALESCE(COMP_FREQ, '' ) AS COMP_FREQ ,
  COALESCE(CDI_DISC, 0 ) AS CDI_DISC ,
  COALESCE(ORIG_IRR, 0 ) AS ORIG_IRR ,
  COALESCE(SHOW_IRR, '' ) AS SHOW_IRR ,
  COALESCE(CALLABLE, '' ) AS CALLABLE ,
  COALESCE(CALL_OPEN, '' ) AS CALL_OPEN ,
  COALESCE(BSACCTMETH, '' ) AS BSACCTMETH ,
  COALESCE(CONTINGENT, '' ) AS CONTINGENT ,
  COALESCE(INRNDMETH, '' ) AS INRNDMETH ,
  COALESCE(INRNDPLACE, 0 ) AS INRNDPLACE ,
  COALESCE(SEPARATE_RATESET, '' ) AS SEPARATE_RATESET ,
  COALESCE(DUAL_CCY, '' ) AS DUAL_CCY ,
  COALESCE(COUPON_CCY, '' ) AS COUPON_CCY ,
  COALESCE(COUPON_FV, 0 ) AS COUPON_FV ,
  COALESCE(EXCH_RATE, 0 ) AS EXCH_RATE ,
  COALESCE(DATED_DATE, '' ) AS DATED_DATE ,
  COALESCE(FNL_PRD_METHOD, 0 ) AS FNL_PRD_METHOD ,
  COALESCE(FPP_EARLY_DISCOUNT, 0 ) AS FPP_EARLY_DISCOUNT ,
  COALESCE(FPP_ADJ_MATURITY, 0 ) AS FPP_ADJ_MATURITY ,
  COALESCE(FPP_NO_PPH_ROUNDING, 0 ) AS FPP_NO_PPH_ROUNDING ,
  COALESCE(FPP_DAYS_BASIS, 0 ) AS FPP_DAYS_BASIS ,
  COALESCE(FIRST_COUPON_DATE, '' ) AS FIRST_COUPON_DATE ,
  COALESCE(INCOME_ACCRUAL_BASIS, 0 ) AS INCOME_ACCRUAL_BASIS ,
  COALESCE(ODD_FIRST_COUPON, 0 ) AS ODD_FIRST_COUPON ,
  COALESCE(ODD_LAST_COUPON, 0 ) AS ODD_LAST_COUPON ,
  COALESCE(PENULTIMATE_COUPON_DATE, '' ) AS PENULTIMATE_COUPON_DATE ,
  COALESCE(YIELD_METHOD, 0 ) AS YIELD_METHOD ,
  COALESCE(YIELD_COMPOUND_FREQ, 0 ) AS YIELD_COMPOUND_FREQ ,
  COALESCE(YIELD_NETT_OF_TAX, 0 ) AS YIELD_NETT_OF_TAX ,
  COALESCE(DISCOUNT_DAYS_BASIS, 0 ) AS DISCOUNT_DAYS_BASIS ,
  COALESCE(NO_COUPON_ON_MATURITY, 0 ) AS NO_COUPON_ON_MATURITY ,
  COALESCE(GEN_STOCK_FLOW, 0 ) AS GEN_STOCK_FLOW ,
  COALESCE(OPTTYPE, '' ) AS OPTTYPE ,
  COALESCE(EXSTYLE, 0 ) AS EXSTYLE ,
  COALESCE(STRIKPRICE, 0 ) AS STRIKPRICE ,
  COALESCE(YIELD_TO_FIRST_EXERCISE, 0 ) AS YIELD_TO_FIRST_EXERCISE ,
  COALESCE(PREM_ACRLP, '' ) AS PREM_ACRLP ,
  COALESCE(COUPON_DAYS_BASIS, 0 ) AS COUPON_DAYS_BASIS ,
  COALESCE(ANALYSE01, '' ) AS ANALYSE01 ,
  COALESCE(ANALYSE02, '' ) AS ANALYSE02 ,
  COALESCE(ANALYSE03, '' ) AS ANALYSE03 ,
  COALESCE(ANALYSE04, '' ) AS ANALYSE04 ,
  COALESCE(ANALYSE05, '' ) AS ANALYSE05 ,
  COALESCE(ANALYSE06, '' ) AS ANALYSE06 ,
  COALESCE(ANALYSE07, '' ) AS ANALYSE07 ,
  COALESCE(ANALYSE08, '' ) AS ANALYSE08 ,
  COALESCE(ANALYSE09, '' ) AS ANALYSE09 ,
  COALESCE(ANALYSE10, '' ) AS ANALYSE10 ,
  COALESCE(CAPITAL_ACCRUAL_METHOD, 0 ) AS CAPITAL_ACCRUAL_METHOD ,
  COALESCE(ISSUE_FEE_ACCRUAL_METHOD, 0 ) AS ISSUE_FEE_ACCRUAL_METHOD ,
  COALESCE(ISSUE_FEE, 0 ) AS ISSUE_FEE ,
  COALESCE(ISSUE_FEE_PAYMENT_TYPE, 0 ) AS ISSUE_FEE_PAYMENT_TYPE ,
  COALESCE(ISSUE_FEE_ACRL_TRANS_DT, 0 ) AS ISSUE_FEE_ACRL_TRANS_DT ,
  COALESCE(AMORT_COST_CALENDAR_ID, 0 ) AS AMORT_COST_CALENDAR_ID ,
  COALESCE(USE_DP_BASIS_PRICING, 0 ) AS USE_DP_BASIS_PRICING ,
  COALESCE(ACRL_SL_DAYS_RULE, 0 ) AS ACRL_SL_DAYS_RULE ,
  COALESCE(DO_CONTINGENT_SETTLEMENT, 0 ) AS DO_CONTINGENT_SETTLEMENT ,
  COALESCE(CONTINGENT_SETTLEMENT_METHOD, 0 ) AS CONTINGENT_SETTLEMENT_METHOD ,
  COALESCE(DO_CONTINGENT_MATURITY, 0 ) AS DO_CONTINGENT_MATURITY ,
  COALESCE(CONTINGENT_MATURITY_METHOD, 0 ) AS CONTINGENT_MATURITY_METHOD ,
  COALESCE(INT_ACCR_AMORT, 0 ) AS INT_ACCR_AMORT ,
  COALESCE(FV_INDEX_ACCRUAL_METHOD, 0 ) AS FV_INDEX_ACCRUAL_METHOD ,
  COALESCE(FV_INDEX_ACRL_TRANS_DT, 0 ) AS FV_INDEX_ACRL_TRANS_DT ,
  COALESCE(DEFAULT_IPA_FROM_CPARTY, 0 ) AS DEFAULT_IPA_FROM_CPARTY ,
  COALESCE(USE_SECISSUE_FOR_DEFAULTING, 0 ) AS USE_SECISSUE_FOR_DEFAULTING ,
  COALESCE(STAMP, 0 ) AS STAMP ,
  COALESCE(ALLOW_MULTIPLE_RATESETS, 0 ) AS ALLOW_MULTIPLE_RATESETS 
 FROM  dw_tdata.COS_000_MMDEALS_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  DEAL_NO ,
  BOR_INVEST ,
  BUY_SELL ,
  REMAIN_FV ,
  INT_RATE ,
  INT_MARGIN ,
  ACT_MARGIN ,
  ISS_INDX ,
  FIX_FLOAT ,
  FT_KEY ,
  FORMULA ,
  ACCOUNTING ,
  INT_CALC_LOC ,
  INT_TIMING ,
  INT_DAYS ,
  PREVCOUP ,
  NEXTCOUP ,
  ISSUE_DT ,
  REVIEW_DT ,
  RATE_OFF ,
  REVIEW_FRQ ,
  PAY_DT ,
  PAY_FRQ ,
  COUPON ,
  LAST_COUP ,
  EX_DAYS ,
  COUP_TYPE ,
  COUP_DATES ,
  COUPON_FRQ ,
  FUFTDAYS ,
  PRICE_METH ,
  PRICE_TYPE ,
  PPH_ROUND ,
  PPH_CAPTAL ,
  PPH_INCOME ,
  PPH_CAPITAL_METHOD ,
  PPH_CAPITAL_DP ,
  PPH_INCOME_METHOD ,
  PPH_INCOME_DP ,
  PPH_SETTLE_METHOD ,
  PPH_SETTLE_DP ,
  PPH_AFTER ,
  PPH_DERIVE ,
  FINAL_CASHFLOW_ROUNDING ,
  FCR_SETTLEMENT_METHOD ,
  FCR_SETTLEMENT_DP ,
  FCR_INCOME_METHOD ,
  FCR_INCOME_DP ,
  FCR_CAPITAL_METHOD ,
  FCR_CAPITAL_DP ,
  CAPITALPPH ,
  INCOMEPPH ,
  SETTLEPPH ,
  BOND_PRICE ,
  SHOW_BOTH ,
  EX_CUM_NEW ,
  ACC_ISS ,
  ISS_PAY_AGENT ,
  SHOW_ISS_PAY_AGENT ,
  ISS_PAY_AGENT_REQ ,
  ALL_CFS_WITH_IPA ,
  MATURE_TYP ,
  CLOSEOUT ,
  TRADABLE ,
  STMTEND ,
  STMTDUE ,
  STMTQTR ,
  MM_OR_SEC ,
  DEF_BORINV ,
  INT_AMT ,
  SETTLEMENT ,
  BASIS ,
  BASIS_FREQ ,
  COUP_MARGN ,
  PURCH_YLD ,
  STOCKLOCAT ,
  NOTION_DT ,
  REPO_TYPE ,
  REPO_LINK ,
  STCKMATURE ,
  ASSET_BACK ,
  LEGAL_MAT ,
  IODEAL_NO ,
  YIELD_TYPE ,
  FRAC_UNIT ,
  INTPAYMETH ,
  FPP_METHOD ,
  NOM_EFF ,
  COMP_FREQ ,
  CDI_DISC ,
  ORIG_IRR ,
  SHOW_IRR ,
  CALLABLE ,
  CALL_OPEN ,
  BSACCTMETH ,
  CONTINGENT ,
  INRNDMETH ,
  INRNDPLACE ,
  SEPARATE_RATESET ,
  DUAL_CCY ,
  COUPON_CCY ,
  COUPON_FV ,
  EXCH_RATE ,
  DATED_DATE ,
  FNL_PRD_METHOD ,
  FPP_EARLY_DISCOUNT ,
  FPP_ADJ_MATURITY ,
  FPP_NO_PPH_ROUNDING ,
  FPP_DAYS_BASIS ,
  FIRST_COUPON_DATE ,
  INCOME_ACCRUAL_BASIS ,
  ODD_FIRST_COUPON ,
  ODD_LAST_COUPON ,
  PENULTIMATE_COUPON_DATE ,
  YIELD_METHOD ,
  YIELD_COMPOUND_FREQ ,
  YIELD_NETT_OF_TAX ,
  DISCOUNT_DAYS_BASIS ,
  NO_COUPON_ON_MATURITY ,
  GEN_STOCK_FLOW ,
  OPTTYPE ,
  EXSTYLE ,
  STRIKPRICE ,
  YIELD_TO_FIRST_EXERCISE ,
  PREM_ACRLP ,
  COUPON_DAYS_BASIS ,
  ANALYSE01 ,
  ANALYSE02 ,
  ANALYSE03 ,
  ANALYSE04 ,
  ANALYSE05 ,
  ANALYSE06 ,
  ANALYSE07 ,
  ANALYSE08 ,
  ANALYSE09 ,
  ANALYSE10 ,
  CAPITAL_ACCRUAL_METHOD ,
  ISSUE_FEE_ACCRUAL_METHOD ,
  ISSUE_FEE ,
  ISSUE_FEE_PAYMENT_TYPE ,
  ISSUE_FEE_ACRL_TRANS_DT ,
  AMORT_COST_CALENDAR_ID ,
  USE_DP_BASIS_PRICING ,
  ACRL_SL_DAYS_RULE ,
  DO_CONTINGENT_SETTLEMENT ,
  CONTINGENT_SETTLEMENT_METHOD ,
  DO_CONTINGENT_MATURITY ,
  CONTINGENT_MATURITY_METHOD ,
  INT_ACCR_AMORT ,
  FV_INDEX_ACCRUAL_METHOD ,
  FV_INDEX_ACRL_TRANS_DT ,
  DEFAULT_IPA_FROM_CPARTY ,
  USE_SECISSUE_FOR_DEFAULTING ,
  STAMP ,
  ALLOW_MULTIPLE_RATESETS 
 FROM dw_sdata.COS_000_MMDEALS 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.DEAL_NO = T.DEAL_NO
WHERE
(T.DEAL_NO IS NULL)
 OR N.BOR_INVEST<>T.BOR_INVEST
 OR N.BUY_SELL<>T.BUY_SELL
 OR N.REMAIN_FV<>T.REMAIN_FV
 OR N.INT_RATE<>T.INT_RATE
 OR N.INT_MARGIN<>T.INT_MARGIN
 OR N.ACT_MARGIN<>T.ACT_MARGIN
 OR N.ISS_INDX<>T.ISS_INDX
 OR N.FIX_FLOAT<>T.FIX_FLOAT
 OR N.FT_KEY<>T.FT_KEY
 OR N.FORMULA<>T.FORMULA
 OR N.ACCOUNTING<>T.ACCOUNTING
 OR N.INT_CALC_LOC<>T.INT_CALC_LOC
 OR N.INT_TIMING<>T.INT_TIMING
 OR N.INT_DAYS<>T.INT_DAYS
 OR N.PREVCOUP<>T.PREVCOUP
 OR N.NEXTCOUP<>T.NEXTCOUP
 OR N.ISSUE_DT<>T.ISSUE_DT
 OR N.REVIEW_DT<>T.REVIEW_DT
 OR N.RATE_OFF<>T.RATE_OFF
 OR N.REVIEW_FRQ<>T.REVIEW_FRQ
 OR N.PAY_DT<>T.PAY_DT
 OR N.PAY_FRQ<>T.PAY_FRQ
 OR N.COUPON<>T.COUPON
 OR N.LAST_COUP<>T.LAST_COUP
 OR N.EX_DAYS<>T.EX_DAYS
 OR N.COUP_TYPE<>T.COUP_TYPE
 OR N.COUP_DATES<>T.COUP_DATES
 OR N.COUPON_FRQ<>T.COUPON_FRQ
 OR N.FUFTDAYS<>T.FUFTDAYS
 OR N.PRICE_METH<>T.PRICE_METH
 OR N.PRICE_TYPE<>T.PRICE_TYPE
 OR N.PPH_ROUND<>T.PPH_ROUND
 OR N.PPH_CAPTAL<>T.PPH_CAPTAL
 OR N.PPH_INCOME<>T.PPH_INCOME
 OR N.PPH_CAPITAL_METHOD<>T.PPH_CAPITAL_METHOD
 OR N.PPH_CAPITAL_DP<>T.PPH_CAPITAL_DP
 OR N.PPH_INCOME_METHOD<>T.PPH_INCOME_METHOD
 OR N.PPH_INCOME_DP<>T.PPH_INCOME_DP
 OR N.PPH_SETTLE_METHOD<>T.PPH_SETTLE_METHOD
 OR N.PPH_SETTLE_DP<>T.PPH_SETTLE_DP
 OR N.PPH_AFTER<>T.PPH_AFTER
 OR N.PPH_DERIVE<>T.PPH_DERIVE
 OR N.FINAL_CASHFLOW_ROUNDING<>T.FINAL_CASHFLOW_ROUNDING
 OR N.FCR_SETTLEMENT_METHOD<>T.FCR_SETTLEMENT_METHOD
 OR N.FCR_SETTLEMENT_DP<>T.FCR_SETTLEMENT_DP
 OR N.FCR_INCOME_METHOD<>T.FCR_INCOME_METHOD
 OR N.FCR_INCOME_DP<>T.FCR_INCOME_DP
 OR N.FCR_CAPITAL_METHOD<>T.FCR_CAPITAL_METHOD
 OR N.FCR_CAPITAL_DP<>T.FCR_CAPITAL_DP
 OR N.CAPITALPPH<>T.CAPITALPPH
 OR N.INCOMEPPH<>T.INCOMEPPH
 OR N.SETTLEPPH<>T.SETTLEPPH
 OR N.BOND_PRICE<>T.BOND_PRICE
 OR N.SHOW_BOTH<>T.SHOW_BOTH
 OR N.EX_CUM_NEW<>T.EX_CUM_NEW
 OR N.ACC_ISS<>T.ACC_ISS
 OR N.ISS_PAY_AGENT<>T.ISS_PAY_AGENT
 OR N.SHOW_ISS_PAY_AGENT<>T.SHOW_ISS_PAY_AGENT
 OR N.ISS_PAY_AGENT_REQ<>T.ISS_PAY_AGENT_REQ
 OR N.ALL_CFS_WITH_IPA<>T.ALL_CFS_WITH_IPA
 OR N.MATURE_TYP<>T.MATURE_TYP
 OR N.CLOSEOUT<>T.CLOSEOUT
 OR N.TRADABLE<>T.TRADABLE
 OR N.STMTEND<>T.STMTEND
 OR N.STMTDUE<>T.STMTDUE
 OR N.STMTQTR<>T.STMTQTR
 OR N.MM_OR_SEC<>T.MM_OR_SEC
 OR N.DEF_BORINV<>T.DEF_BORINV
 OR N.INT_AMT<>T.INT_AMT
 OR N.SETTLEMENT<>T.SETTLEMENT
 OR N.BASIS<>T.BASIS
 OR N.BASIS_FREQ<>T.BASIS_FREQ
 OR N.COUP_MARGN<>T.COUP_MARGN
 OR N.PURCH_YLD<>T.PURCH_YLD
 OR N.STOCKLOCAT<>T.STOCKLOCAT
 OR N.NOTION_DT<>T.NOTION_DT
 OR N.REPO_TYPE<>T.REPO_TYPE
 OR N.REPO_LINK<>T.REPO_LINK
 OR N.STCKMATURE<>T.STCKMATURE
 OR N.ASSET_BACK<>T.ASSET_BACK
 OR N.LEGAL_MAT<>T.LEGAL_MAT
 OR N.IODEAL_NO<>T.IODEAL_NO
 OR N.YIELD_TYPE<>T.YIELD_TYPE
 OR N.FRAC_UNIT<>T.FRAC_UNIT
 OR N.INTPAYMETH<>T.INTPAYMETH
 OR N.FPP_METHOD<>T.FPP_METHOD
 OR N.NOM_EFF<>T.NOM_EFF
 OR N.COMP_FREQ<>T.COMP_FREQ
 OR N.CDI_DISC<>T.CDI_DISC
 OR N.ORIG_IRR<>T.ORIG_IRR
 OR N.SHOW_IRR<>T.SHOW_IRR
 OR N.CALLABLE<>T.CALLABLE
 OR N.CALL_OPEN<>T.CALL_OPEN
 OR N.BSACCTMETH<>T.BSACCTMETH
 OR N.CONTINGENT<>T.CONTINGENT
 OR N.INRNDMETH<>T.INRNDMETH
 OR N.INRNDPLACE<>T.INRNDPLACE
 OR N.SEPARATE_RATESET<>T.SEPARATE_RATESET
 OR N.DUAL_CCY<>T.DUAL_CCY
 OR N.COUPON_CCY<>T.COUPON_CCY
 OR N.COUPON_FV<>T.COUPON_FV
 OR N.EXCH_RATE<>T.EXCH_RATE
 OR N.DATED_DATE<>T.DATED_DATE
 OR N.FNL_PRD_METHOD<>T.FNL_PRD_METHOD
 OR N.FPP_EARLY_DISCOUNT<>T.FPP_EARLY_DISCOUNT
 OR N.FPP_ADJ_MATURITY<>T.FPP_ADJ_MATURITY
 OR N.FPP_NO_PPH_ROUNDING<>T.FPP_NO_PPH_ROUNDING
 OR N.FPP_DAYS_BASIS<>T.FPP_DAYS_BASIS
 OR N.FIRST_COUPON_DATE<>T.FIRST_COUPON_DATE
 OR N.INCOME_ACCRUAL_BASIS<>T.INCOME_ACCRUAL_BASIS
 OR N.ODD_FIRST_COUPON<>T.ODD_FIRST_COUPON
 OR N.ODD_LAST_COUPON<>T.ODD_LAST_COUPON
 OR N.PENULTIMATE_COUPON_DATE<>T.PENULTIMATE_COUPON_DATE
 OR N.YIELD_METHOD<>T.YIELD_METHOD
 OR N.YIELD_COMPOUND_FREQ<>T.YIELD_COMPOUND_FREQ
 OR N.YIELD_NETT_OF_TAX<>T.YIELD_NETT_OF_TAX
 OR N.DISCOUNT_DAYS_BASIS<>T.DISCOUNT_DAYS_BASIS
 OR N.NO_COUPON_ON_MATURITY<>T.NO_COUPON_ON_MATURITY
 OR N.GEN_STOCK_FLOW<>T.GEN_STOCK_FLOW
 OR N.OPTTYPE<>T.OPTTYPE
 OR N.EXSTYLE<>T.EXSTYLE
 OR N.STRIKPRICE<>T.STRIKPRICE
 OR N.YIELD_TO_FIRST_EXERCISE<>T.YIELD_TO_FIRST_EXERCISE
 OR N.PREM_ACRLP<>T.PREM_ACRLP
 OR N.COUPON_DAYS_BASIS<>T.COUPON_DAYS_BASIS
 OR N.ANALYSE01<>T.ANALYSE01
 OR N.ANALYSE02<>T.ANALYSE02
 OR N.ANALYSE03<>T.ANALYSE03
 OR N.ANALYSE04<>T.ANALYSE04
 OR N.ANALYSE05<>T.ANALYSE05
 OR N.ANALYSE06<>T.ANALYSE06
 OR N.ANALYSE07<>T.ANALYSE07
 OR N.ANALYSE08<>T.ANALYSE08
 OR N.ANALYSE09<>T.ANALYSE09
 OR N.ANALYSE10<>T.ANALYSE10
 OR N.CAPITAL_ACCRUAL_METHOD<>T.CAPITAL_ACCRUAL_METHOD
 OR N.ISSUE_FEE_ACCRUAL_METHOD<>T.ISSUE_FEE_ACCRUAL_METHOD
 OR N.ISSUE_FEE<>T.ISSUE_FEE
 OR N.ISSUE_FEE_PAYMENT_TYPE<>T.ISSUE_FEE_PAYMENT_TYPE
 OR N.ISSUE_FEE_ACRL_TRANS_DT<>T.ISSUE_FEE_ACRL_TRANS_DT
 OR N.AMORT_COST_CALENDAR_ID<>T.AMORT_COST_CALENDAR_ID
 OR N.USE_DP_BASIS_PRICING<>T.USE_DP_BASIS_PRICING
 OR N.ACRL_SL_DAYS_RULE<>T.ACRL_SL_DAYS_RULE
 OR N.DO_CONTINGENT_SETTLEMENT<>T.DO_CONTINGENT_SETTLEMENT
 OR N.CONTINGENT_SETTLEMENT_METHOD<>T.CONTINGENT_SETTLEMENT_METHOD
 OR N.DO_CONTINGENT_MATURITY<>T.DO_CONTINGENT_MATURITY
 OR N.CONTINGENT_MATURITY_METHOD<>T.CONTINGENT_MATURITY_METHOD
 OR N.INT_ACCR_AMORT<>T.INT_ACCR_AMORT
 OR N.FV_INDEX_ACCRUAL_METHOD<>T.FV_INDEX_ACCRUAL_METHOD
 OR N.FV_INDEX_ACRL_TRANS_DT<>T.FV_INDEX_ACRL_TRANS_DT
 OR N.DEFAULT_IPA_FROM_CPARTY<>T.DEFAULT_IPA_FROM_CPARTY
 OR N.USE_SECISSUE_FOR_DEFAULTING<>T.USE_SECISSUE_FOR_DEFAULTING
 OR N.STAMP<>T.STAMP
 OR N.ALLOW_MULTIPLE_RATESETS<>T.ALLOW_MULTIPLE_RATESETS
;

--Step3:
UPDATE dw_sdata.COS_000_MMDEALS P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_156
WHERE P.End_Dt=DATE('2100-12-31')
AND P.DEAL_NO=T_156.DEAL_NO
;

--Step4:
INSERT  INTO dw_sdata.COS_000_MMDEALS SELECT * FROM T_156;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
