#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.COS_000_DEALS WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.COS_000_DEALS SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_152 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.COS_000_DEALS WHERE 1=0;

--Step2:
INSERT  INTO T_152 (
  DEAL_NO,
  DEALTYPE,
  AUDIT_NO,
  IMAGE_NO,
  TRANS_TYPE,
  SECTYPE,
  MODIFIABLE,
  CCY,
  CCY2,
  BASE_CCY,
  BASE_RATE,
  BASE_RATE2,
  FACE_VALUE,
  FACE_VALU2,
  DEAL_DT,
  SETTLE_DT,
  MATURE_DT,
  CUR_MAT_DT,
  EFF_MAT_DT,
  ACT_MAT_DT,
  INPUT_DT,
  DEALER,
  ENTITY,
  CPARTY,
  CP_DEALER,
  CP_DLR_KEY,
  CP_REF,
  FAC_OWNER,
  FACILITY,
  STRATEGY,
  TICKET_NO,
  CMT_NO,
  CLOSEOUT,
  DO_ACCR,
  DO_ADHOC,
  REV_ACCR,
  DO_MKT_RV,
  REV_MKT_RV,
  DO_CAPITAL,
  RV_EN_DT,
  LA_RV_DT,
  LA_RV_AMT,
  LA_RV_AMT2,
  LA_RV_MARG,
  LA_RV_CAP,
  ACRL_ST_DT,
  ACRL_EN_DT,
  LA_ACRL_DT,
  ACL_CAP_DT,
  ACL_CAP_EN_DT,
  LA_POST_DT,
  LA_EXFL_DT,
  EXFL_COMPLETE_TO_DT,
  ACCR_AMT,
  ACCR_AMT2,
  ACCR_CAP,
  ACCR_CAP2,
  ACCR_TAX,
  ACCR_TAX2,
  ACCR_CAPT,
  ACCR_CAPT2,
  CONFO_NO,
  CNFSTATUS,
  APPROVED,
  CUSTOMISED,
  CHANGED,
  ADVPRINTED,
  ADVTIME,
  APSTUS1,
  APUSR1,
  APSTUS2,
  APUSR2,
  POSTUNREAL,
  FV_OR_NET,
  MARGIN_ACT,
  INTERNAL,
  QUOTENO,
  SECISSUE,
  DASET_KEY,
  ANALYSE01,
  ANALYSE02,
  ANALYSE03,
  ANALYSE04,
  ANALYSE05,
  ANALYSE06,
  ANALYSE07,
  ANALYSE08,
  ANALYSE09,
  ANALYSE10,
  ANALYSE11,
  ANALYSE12,
  ANALYSE13,
  ANALYSE14,
  ANALYSE15,
  ANALYSE16,
  ANALYSE17,
  ANALYSE18,
  ANALYSE19,
  ANALYSE20,
  ACCR_EXCH,
  ACCR_CLEAR,
  ACCR_BROK,
  LA_INDX_DT,
  NOTIONAL,
  IN_USE,
  MOD_FLAGS,
  SHOW_BROK,
  BROK_REQ,
  BROKER,
  BANKREC,
  NON_BUS_DEALS,
  DEAL_SET_ID,
  OWNER_TYPE,
  OWNER_NAME,
  EXTERNAL_REF_ID,
  EXTERNAL_REF_TEXT,
  CCY_RND_OVERRIDE_METH,
  CCY2_RND_OVERRIDE_METH,
  SCHEDULE_STATUS,
  DO_ISSUE_FEE,
  ISSUE_FEE_LAST_ACRL_DATE,
  ISSUE_FEE_ACRL_END_DATE,
  PROFILED,
  DO_CCYTRANS,
  DO_CCYTRANS_SUM,
  DO_FV_INDEX_ACCRUAL,
  FV_INDEX_LAST_ACRL_DT,
  FV_INDEX_ACRL_END_DATE,
  STAMP,
  DEAL_DATETIME,
  start_dt,
  end_dt)
SELECT
  N.DEAL_NO,
  N.DEALTYPE,
  N.AUDIT_NO,
  N.IMAGE_NO,
  N.TRANS_TYPE,
  N.SECTYPE,
  N.MODIFIABLE,
  N.CCY,
  N.CCY2,
  N.BASE_CCY,
  N.BASE_RATE,
  N.BASE_RATE2,
  N.FACE_VALUE,
  N.FACE_VALU2,
  N.DEAL_DT,
  N.SETTLE_DT,
  N.MATURE_DT,
  N.CUR_MAT_DT,
  N.EFF_MAT_DT,
  N.ACT_MAT_DT,
  N.INPUT_DT,
  N.DEALER,
  N.ENTITY,
  N.CPARTY,
  N.CP_DEALER,
  N.CP_DLR_KEY,
  N.CP_REF,
  N.FAC_OWNER,
  N.FACILITY,
  N.STRATEGY,
  N.TICKET_NO,
  N.CMT_NO,
  N.CLOSEOUT,
  N.DO_ACCR,
  N.DO_ADHOC,
  N.REV_ACCR,
  N.DO_MKT_RV,
  N.REV_MKT_RV,
  N.DO_CAPITAL,
  N.RV_EN_DT,
  N.LA_RV_DT,
  N.LA_RV_AMT,
  N.LA_RV_AMT2,
  N.LA_RV_MARG,
  N.LA_RV_CAP,
  N.ACRL_ST_DT,
  N.ACRL_EN_DT,
  N.LA_ACRL_DT,
  N.ACL_CAP_DT,
  N.ACL_CAP_EN_DT,
  N.LA_POST_DT,
  N.LA_EXFL_DT,
  N.EXFL_COMPLETE_TO_DT,
  N.ACCR_AMT,
  N.ACCR_AMT2,
  N.ACCR_CAP,
  N.ACCR_CAP2,
  N.ACCR_TAX,
  N.ACCR_TAX2,
  N.ACCR_CAPT,
  N.ACCR_CAPT2,
  N.CONFO_NO,
  N.CNFSTATUS,
  N.APPROVED,
  N.CUSTOMISED,
  N.CHANGED,
  N.ADVPRINTED,
  N.ADVTIME,
  N.APSTUS1,
  N.APUSR1,
  N.APSTUS2,
  N.APUSR2,
  N.POSTUNREAL,
  N.FV_OR_NET,
  N.MARGIN_ACT,
  N.INTERNAL,
  N.QUOTENO,
  N.SECISSUE,
  N.DASET_KEY,
  N.ANALYSE01,
  N.ANALYSE02,
  N.ANALYSE03,
  N.ANALYSE04,
  N.ANALYSE05,
  N.ANALYSE06,
  N.ANALYSE07,
  N.ANALYSE08,
  N.ANALYSE09,
  N.ANALYSE10,
  N.ANALYSE11,
  N.ANALYSE12,
  N.ANALYSE13,
  N.ANALYSE14,
  N.ANALYSE15,
  N.ANALYSE16,
  N.ANALYSE17,
  N.ANALYSE18,
  N.ANALYSE19,
  N.ANALYSE20,
  N.ACCR_EXCH,
  N.ACCR_CLEAR,
  N.ACCR_BROK,
  N.LA_INDX_DT,
  N.NOTIONAL,
  N.IN_USE,
  N.MOD_FLAGS,
  N.SHOW_BROK,
  N.BROK_REQ,
  N.BROKER,
  N.BANKREC,
  N.NON_BUS_DEALS,
  N.DEAL_SET_ID,
  N.OWNER_TYPE,
  N.OWNER_NAME,
  N.EXTERNAL_REF_ID,
  N.EXTERNAL_REF_TEXT,
  N.CCY_RND_OVERRIDE_METH,
  N.CCY2_RND_OVERRIDE_METH,
  N.SCHEDULE_STATUS,
  N.DO_ISSUE_FEE,
  N.ISSUE_FEE_LAST_ACRL_DATE,
  N.ISSUE_FEE_ACRL_END_DATE,
  N.PROFILED,
  N.DO_CCYTRANS,
  N.DO_CCYTRANS_SUM,
  N.DO_FV_INDEX_ACCRUAL,
  N.FV_INDEX_LAST_ACRL_DT,
  N.FV_INDEX_ACRL_END_DATE,
  N.STAMP,
  N.DEAL_DATETIME,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(DEAL_NO, 0 ) AS DEAL_NO ,
  COALESCE(DEALTYPE, '' ) AS DEALTYPE ,
  COALESCE(AUDIT_NO, 0 ) AS AUDIT_NO ,
  COALESCE(IMAGE_NO, 0 ) AS IMAGE_NO ,
  COALESCE(TRANS_TYPE, '' ) AS TRANS_TYPE ,
  COALESCE(SECTYPE, '' ) AS SECTYPE ,
  COALESCE(MODIFIABLE, '' ) AS MODIFIABLE ,
  COALESCE(CCY, '' ) AS CCY ,
  COALESCE(CCY2, '' ) AS CCY2 ,
  COALESCE(BASE_CCY, '' ) AS BASE_CCY ,
  COALESCE(BASE_RATE, 0 ) AS BASE_RATE ,
  COALESCE(BASE_RATE2, 0 ) AS BASE_RATE2 ,
  COALESCE(FACE_VALUE, 0 ) AS FACE_VALUE ,
  COALESCE(FACE_VALU2, 0 ) AS FACE_VALU2 ,
  COALESCE(DEAL_DT, '' ) AS DEAL_DT ,
  COALESCE(SETTLE_DT, '' ) AS SETTLE_DT ,
  COALESCE(MATURE_DT, '' ) AS MATURE_DT ,
  COALESCE(CUR_MAT_DT, '' ) AS CUR_MAT_DT ,
  COALESCE(EFF_MAT_DT, '' ) AS EFF_MAT_DT ,
  COALESCE(ACT_MAT_DT, '' ) AS ACT_MAT_DT ,
  COALESCE(INPUT_DT, '' ) AS INPUT_DT ,
  COALESCE(DEALER, '' ) AS DEALER ,
  COALESCE(ENTITY, '' ) AS ENTITY ,
  COALESCE(CPARTY, '' ) AS CPARTY ,
  COALESCE(CP_DEALER, '' ) AS CP_DEALER ,
  COALESCE(CP_DLR_KEY, '' ) AS CP_DLR_KEY ,
  COALESCE(CP_REF, '' ) AS CP_REF ,
  COALESCE(FAC_OWNER, '' ) AS FAC_OWNER ,
  COALESCE(FACILITY, '' ) AS FACILITY ,
  COALESCE(STRATEGY, '' ) AS STRATEGY ,
  COALESCE(TICKET_NO, '' ) AS TICKET_NO ,
  COALESCE(CMT_NO, 0 ) AS CMT_NO ,
  COALESCE(CLOSEOUT, '' ) AS CLOSEOUT ,
  COALESCE(DO_ACCR, '' ) AS DO_ACCR ,
  COALESCE(DO_ADHOC, '' ) AS DO_ADHOC ,
  COALESCE(REV_ACCR, '' ) AS REV_ACCR ,
  COALESCE(DO_MKT_RV, '' ) AS DO_MKT_RV ,
  COALESCE(REV_MKT_RV, '' ) AS REV_MKT_RV ,
  COALESCE(DO_CAPITAL, '' ) AS DO_CAPITAL ,
  COALESCE(RV_EN_DT, '' ) AS RV_EN_DT ,
  COALESCE(LA_RV_DT, '' ) AS LA_RV_DT ,
  COALESCE(LA_RV_AMT, 0 ) AS LA_RV_AMT ,
  COALESCE(LA_RV_AMT2, 0 ) AS LA_RV_AMT2 ,
  COALESCE(LA_RV_MARG, 0 ) AS LA_RV_MARG ,
  COALESCE(LA_RV_CAP, 0 ) AS LA_RV_CAP ,
  COALESCE(ACRL_ST_DT, '' ) AS ACRL_ST_DT ,
  COALESCE(ACRL_EN_DT, '' ) AS ACRL_EN_DT ,
  COALESCE(LA_ACRL_DT, '' ) AS LA_ACRL_DT ,
  COALESCE(ACL_CAP_DT, '' ) AS ACL_CAP_DT ,
  COALESCE(ACL_CAP_EN_DT, '' ) AS ACL_CAP_EN_DT ,
  COALESCE(LA_POST_DT, '' ) AS LA_POST_DT ,
  COALESCE(LA_EXFL_DT, '' ) AS LA_EXFL_DT ,
  COALESCE(EXFL_COMPLETE_TO_DT, '' ) AS EXFL_COMPLETE_TO_DT ,
  COALESCE(ACCR_AMT, 0 ) AS ACCR_AMT ,
  COALESCE(ACCR_AMT2, 0 ) AS ACCR_AMT2 ,
  COALESCE(ACCR_CAP, 0 ) AS ACCR_CAP ,
  COALESCE(ACCR_CAP2, 0 ) AS ACCR_CAP2 ,
  COALESCE(ACCR_TAX, 0 ) AS ACCR_TAX ,
  COALESCE(ACCR_TAX2, 0 ) AS ACCR_TAX2 ,
  COALESCE(ACCR_CAPT, 0 ) AS ACCR_CAPT ,
  COALESCE(ACCR_CAPT2, 0 ) AS ACCR_CAPT2 ,
  COALESCE(CONFO_NO, '' ) AS CONFO_NO ,
  COALESCE(CNFSTATUS, '' ) AS CNFSTATUS ,
  COALESCE(APPROVED, '' ) AS APPROVED ,
  COALESCE(CUSTOMISED, '' ) AS CUSTOMISED ,
  COALESCE(CHANGED, '' ) AS CHANGED ,
  COALESCE(ADVPRINTED, '' ) AS ADVPRINTED ,
  COALESCE(ADVTIME, '' ) AS ADVTIME ,
  COALESCE(APSTUS1, '' ) AS APSTUS1 ,
  COALESCE(APUSR1, '' ) AS APUSR1 ,
  COALESCE(APSTUS2, '' ) AS APSTUS2 ,
  COALESCE(APUSR2, '' ) AS APUSR2 ,
  COALESCE(POSTUNREAL, '' ) AS POSTUNREAL ,
  COALESCE(FV_OR_NET, '' ) AS FV_OR_NET ,
  COALESCE(MARGIN_ACT, '' ) AS MARGIN_ACT ,
  COALESCE(INTERNAL, '' ) AS INTERNAL ,
  COALESCE(QUOTENO, 0 ) AS QUOTENO ,
  COALESCE(SECISSUE, '' ) AS SECISSUE ,
  COALESCE(DASET_KEY, 0 ) AS DASET_KEY ,
  COALESCE(ANALYSE01, '' ) AS ANALYSE01 ,
  COALESCE(ANALYSE02, '' ) AS ANALYSE02 ,
  COALESCE(ANALYSE03, '' ) AS ANALYSE03 ,
  COALESCE(ANALYSE04, '' ) AS ANALYSE04 ,
  COALESCE(ANALYSE05, '' ) AS ANALYSE05 ,
  COALESCE(ANALYSE06, '' ) AS ANALYSE06 ,
  COALESCE(ANALYSE07, '' ) AS ANALYSE07 ,
  COALESCE(ANALYSE08, '' ) AS ANALYSE08 ,
  COALESCE(ANALYSE09, '' ) AS ANALYSE09 ,
  COALESCE(ANALYSE10, '' ) AS ANALYSE10 ,
  COALESCE(ANALYSE11, '' ) AS ANALYSE11 ,
  COALESCE(ANALYSE12, '' ) AS ANALYSE12 ,
  COALESCE(ANALYSE13, '' ) AS ANALYSE13 ,
  COALESCE(ANALYSE14, '' ) AS ANALYSE14 ,
  COALESCE(ANALYSE15, '' ) AS ANALYSE15 ,
  COALESCE(ANALYSE16, '' ) AS ANALYSE16 ,
  COALESCE(ANALYSE17, '' ) AS ANALYSE17 ,
  COALESCE(ANALYSE18, '' ) AS ANALYSE18 ,
  COALESCE(ANALYSE19, '' ) AS ANALYSE19 ,
  COALESCE(ANALYSE20, '' ) AS ANALYSE20 ,
  COALESCE(ACCR_EXCH, 0 ) AS ACCR_EXCH ,
  COALESCE(ACCR_CLEAR, 0 ) AS ACCR_CLEAR ,
  COALESCE(ACCR_BROK, 0 ) AS ACCR_BROK ,
  COALESCE(LA_INDX_DT, '' ) AS LA_INDX_DT ,
  COALESCE(NOTIONAL, '' ) AS NOTIONAL ,
  COALESCE(IN_USE, '' ) AS IN_USE ,
  COALESCE(MOD_FLAGS, '' ) AS MOD_FLAGS ,
  COALESCE(SHOW_BROK, '' ) AS SHOW_BROK ,
  COALESCE(BROK_REQ, '' ) AS BROK_REQ ,
  COALESCE(BROKER, '' ) AS BROKER ,
  COALESCE(BANKREC, '' ) AS BANKREC ,
  COALESCE(NON_BUS_DEALS, 0 ) AS NON_BUS_DEALS ,
  COALESCE(DEAL_SET_ID, 0 ) AS DEAL_SET_ID ,
  COALESCE(OWNER_TYPE, 0 ) AS OWNER_TYPE ,
  COALESCE(OWNER_NAME, '' ) AS OWNER_NAME ,
  COALESCE(EXTERNAL_REF_ID, 0 ) AS EXTERNAL_REF_ID ,
  COALESCE(EXTERNAL_REF_TEXT, '' ) AS EXTERNAL_REF_TEXT ,
  COALESCE(CCY_RND_OVERRIDE_METH, 0 ) AS CCY_RND_OVERRIDE_METH ,
  COALESCE(CCY2_RND_OVERRIDE_METH, 0 ) AS CCY2_RND_OVERRIDE_METH ,
  COALESCE(SCHEDULE_STATUS, 0 ) AS SCHEDULE_STATUS ,
  COALESCE(DO_ISSUE_FEE, 0 ) AS DO_ISSUE_FEE ,
  COALESCE(ISSUE_FEE_LAST_ACRL_DATE, '' ) AS ISSUE_FEE_LAST_ACRL_DATE ,
  COALESCE(ISSUE_FEE_ACRL_END_DATE, '' ) AS ISSUE_FEE_ACRL_END_DATE ,
  COALESCE(PROFILED, '' ) AS PROFILED ,
  COALESCE(DO_CCYTRANS, 0 ) AS DO_CCYTRANS ,
  COALESCE(DO_CCYTRANS_SUM, 0 ) AS DO_CCYTRANS_SUM ,
  COALESCE(DO_FV_INDEX_ACCRUAL, 0 ) AS DO_FV_INDEX_ACCRUAL ,
  COALESCE(FV_INDEX_LAST_ACRL_DT, '' ) AS FV_INDEX_LAST_ACRL_DT ,
  COALESCE(FV_INDEX_ACRL_END_DATE, '' ) AS FV_INDEX_ACRL_END_DATE ,
  COALESCE(STAMP, 0 ) AS STAMP ,
  COALESCE(DEAL_DATETIME, '' ) AS DEAL_DATETIME 
 FROM  dw_tdata.COS_000_DEALS_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  DEAL_NO ,
  DEALTYPE ,
  AUDIT_NO ,
  IMAGE_NO ,
  TRANS_TYPE ,
  SECTYPE ,
  MODIFIABLE ,
  CCY ,
  CCY2 ,
  BASE_CCY ,
  BASE_RATE ,
  BASE_RATE2 ,
  FACE_VALUE ,
  FACE_VALU2 ,
  DEAL_DT ,
  SETTLE_DT ,
  MATURE_DT ,
  CUR_MAT_DT ,
  EFF_MAT_DT ,
  ACT_MAT_DT ,
  INPUT_DT ,
  DEALER ,
  ENTITY ,
  CPARTY ,
  CP_DEALER ,
  CP_DLR_KEY ,
  CP_REF ,
  FAC_OWNER ,
  FACILITY ,
  STRATEGY ,
  TICKET_NO ,
  CMT_NO ,
  CLOSEOUT ,
  DO_ACCR ,
  DO_ADHOC ,
  REV_ACCR ,
  DO_MKT_RV ,
  REV_MKT_RV ,
  DO_CAPITAL ,
  RV_EN_DT ,
  LA_RV_DT ,
  LA_RV_AMT ,
  LA_RV_AMT2 ,
  LA_RV_MARG ,
  LA_RV_CAP ,
  ACRL_ST_DT ,
  ACRL_EN_DT ,
  LA_ACRL_DT ,
  ACL_CAP_DT ,
  ACL_CAP_EN_DT ,
  LA_POST_DT ,
  LA_EXFL_DT ,
  EXFL_COMPLETE_TO_DT ,
  ACCR_AMT ,
  ACCR_AMT2 ,
  ACCR_CAP ,
  ACCR_CAP2 ,
  ACCR_TAX ,
  ACCR_TAX2 ,
  ACCR_CAPT ,
  ACCR_CAPT2 ,
  CONFO_NO ,
  CNFSTATUS ,
  APPROVED ,
  CUSTOMISED ,
  CHANGED ,
  ADVPRINTED ,
  ADVTIME ,
  APSTUS1 ,
  APUSR1 ,
  APSTUS2 ,
  APUSR2 ,
  POSTUNREAL ,
  FV_OR_NET ,
  MARGIN_ACT ,
  INTERNAL ,
  QUOTENO ,
  SECISSUE ,
  DASET_KEY ,
  ANALYSE01 ,
  ANALYSE02 ,
  ANALYSE03 ,
  ANALYSE04 ,
  ANALYSE05 ,
  ANALYSE06 ,
  ANALYSE07 ,
  ANALYSE08 ,
  ANALYSE09 ,
  ANALYSE10 ,
  ANALYSE11 ,
  ANALYSE12 ,
  ANALYSE13 ,
  ANALYSE14 ,
  ANALYSE15 ,
  ANALYSE16 ,
  ANALYSE17 ,
  ANALYSE18 ,
  ANALYSE19 ,
  ANALYSE20 ,
  ACCR_EXCH ,
  ACCR_CLEAR ,
  ACCR_BROK ,
  LA_INDX_DT ,
  NOTIONAL ,
  IN_USE ,
  MOD_FLAGS ,
  SHOW_BROK ,
  BROK_REQ ,
  BROKER ,
  BANKREC ,
  NON_BUS_DEALS ,
  DEAL_SET_ID ,
  OWNER_TYPE ,
  OWNER_NAME ,
  EXTERNAL_REF_ID ,
  EXTERNAL_REF_TEXT ,
  CCY_RND_OVERRIDE_METH ,
  CCY2_RND_OVERRIDE_METH ,
  SCHEDULE_STATUS ,
  DO_ISSUE_FEE ,
  ISSUE_FEE_LAST_ACRL_DATE ,
  ISSUE_FEE_ACRL_END_DATE ,
  PROFILED ,
  DO_CCYTRANS ,
  DO_CCYTRANS_SUM ,
  DO_FV_INDEX_ACCRUAL ,
  FV_INDEX_LAST_ACRL_DT ,
  FV_INDEX_ACRL_END_DATE ,
  STAMP ,
  DEAL_DATETIME 
 FROM dw_sdata.COS_000_DEALS 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.DEAL_NO = T.DEAL_NO
WHERE
(T.DEAL_NO IS NULL)
 OR N.DEALTYPE<>T.DEALTYPE
 OR N.AUDIT_NO<>T.AUDIT_NO
 OR N.IMAGE_NO<>T.IMAGE_NO
 OR N.TRANS_TYPE<>T.TRANS_TYPE
 OR N.SECTYPE<>T.SECTYPE
 OR N.MODIFIABLE<>T.MODIFIABLE
 OR N.CCY<>T.CCY
 OR N.CCY2<>T.CCY2
 OR N.BASE_CCY<>T.BASE_CCY
 OR N.BASE_RATE<>T.BASE_RATE
 OR N.BASE_RATE2<>T.BASE_RATE2
 OR N.FACE_VALUE<>T.FACE_VALUE
 OR N.FACE_VALU2<>T.FACE_VALU2
 OR N.DEAL_DT<>T.DEAL_DT
 OR N.SETTLE_DT<>T.SETTLE_DT
 OR N.MATURE_DT<>T.MATURE_DT
 OR N.CUR_MAT_DT<>T.CUR_MAT_DT
 OR N.EFF_MAT_DT<>T.EFF_MAT_DT
 OR N.ACT_MAT_DT<>T.ACT_MAT_DT
 OR N.INPUT_DT<>T.INPUT_DT
 OR N.DEALER<>T.DEALER
 OR N.ENTITY<>T.ENTITY
 OR N.CPARTY<>T.CPARTY
 OR N.CP_DEALER<>T.CP_DEALER
 OR N.CP_DLR_KEY<>T.CP_DLR_KEY
 OR N.CP_REF<>T.CP_REF
 OR N.FAC_OWNER<>T.FAC_OWNER
 OR N.FACILITY<>T.FACILITY
 OR N.STRATEGY<>T.STRATEGY
 OR N.TICKET_NO<>T.TICKET_NO
 OR N.CMT_NO<>T.CMT_NO
 OR N.CLOSEOUT<>T.CLOSEOUT
 OR N.DO_ACCR<>T.DO_ACCR
 OR N.DO_ADHOC<>T.DO_ADHOC
 OR N.REV_ACCR<>T.REV_ACCR
 OR N.DO_MKT_RV<>T.DO_MKT_RV
 OR N.REV_MKT_RV<>T.REV_MKT_RV
 OR N.DO_CAPITAL<>T.DO_CAPITAL
 OR N.RV_EN_DT<>T.RV_EN_DT
 OR N.LA_RV_DT<>T.LA_RV_DT
 OR N.LA_RV_AMT<>T.LA_RV_AMT
 OR N.LA_RV_AMT2<>T.LA_RV_AMT2
 OR N.LA_RV_MARG<>T.LA_RV_MARG
 OR N.LA_RV_CAP<>T.LA_RV_CAP
 OR N.ACRL_ST_DT<>T.ACRL_ST_DT
 OR N.ACRL_EN_DT<>T.ACRL_EN_DT
 OR N.LA_ACRL_DT<>T.LA_ACRL_DT
 OR N.ACL_CAP_DT<>T.ACL_CAP_DT
 OR N.ACL_CAP_EN_DT<>T.ACL_CAP_EN_DT
 OR N.LA_POST_DT<>T.LA_POST_DT
 OR N.LA_EXFL_DT<>T.LA_EXFL_DT
 OR N.EXFL_COMPLETE_TO_DT<>T.EXFL_COMPLETE_TO_DT
 OR N.ACCR_AMT<>T.ACCR_AMT
 OR N.ACCR_AMT2<>T.ACCR_AMT2
 OR N.ACCR_CAP<>T.ACCR_CAP
 OR N.ACCR_CAP2<>T.ACCR_CAP2
 OR N.ACCR_TAX<>T.ACCR_TAX
 OR N.ACCR_TAX2<>T.ACCR_TAX2
 OR N.ACCR_CAPT<>T.ACCR_CAPT
 OR N.ACCR_CAPT2<>T.ACCR_CAPT2
 OR N.CONFO_NO<>T.CONFO_NO
 OR N.CNFSTATUS<>T.CNFSTATUS
 OR N.APPROVED<>T.APPROVED
 OR N.CUSTOMISED<>T.CUSTOMISED
 OR N.CHANGED<>T.CHANGED
 OR N.ADVPRINTED<>T.ADVPRINTED
 OR N.ADVTIME<>T.ADVTIME
 OR N.APSTUS1<>T.APSTUS1
 OR N.APUSR1<>T.APUSR1
 OR N.APSTUS2<>T.APSTUS2
 OR N.APUSR2<>T.APUSR2
 OR N.POSTUNREAL<>T.POSTUNREAL
 OR N.FV_OR_NET<>T.FV_OR_NET
 OR N.MARGIN_ACT<>T.MARGIN_ACT
 OR N.INTERNAL<>T.INTERNAL
 OR N.QUOTENO<>T.QUOTENO
 OR N.SECISSUE<>T.SECISSUE
 OR N.DASET_KEY<>T.DASET_KEY
 OR N.ANALYSE01<>T.ANALYSE01
 OR N.ANALYSE02<>T.ANALYSE02
 OR N.ANALYSE03<>T.ANALYSE03
 OR N.ANALYSE04<>T.ANALYSE04
 OR N.ANALYSE05<>T.ANALYSE05
 OR N.ANALYSE06<>T.ANALYSE06
 OR N.ANALYSE07<>T.ANALYSE07
 OR N.ANALYSE08<>T.ANALYSE08
 OR N.ANALYSE09<>T.ANALYSE09
 OR N.ANALYSE10<>T.ANALYSE10
 OR N.ANALYSE11<>T.ANALYSE11
 OR N.ANALYSE12<>T.ANALYSE12
 OR N.ANALYSE13<>T.ANALYSE13
 OR N.ANALYSE14<>T.ANALYSE14
 OR N.ANALYSE15<>T.ANALYSE15
 OR N.ANALYSE16<>T.ANALYSE16
 OR N.ANALYSE17<>T.ANALYSE17
 OR N.ANALYSE18<>T.ANALYSE18
 OR N.ANALYSE19<>T.ANALYSE19
 OR N.ANALYSE20<>T.ANALYSE20
 OR N.ACCR_EXCH<>T.ACCR_EXCH
 OR N.ACCR_CLEAR<>T.ACCR_CLEAR
 OR N.ACCR_BROK<>T.ACCR_BROK
 OR N.LA_INDX_DT<>T.LA_INDX_DT
 OR N.NOTIONAL<>T.NOTIONAL
 OR N.IN_USE<>T.IN_USE
 OR N.MOD_FLAGS<>T.MOD_FLAGS
 OR N.SHOW_BROK<>T.SHOW_BROK
 OR N.BROK_REQ<>T.BROK_REQ
 OR N.BROKER<>T.BROKER
 OR N.BANKREC<>T.BANKREC
 OR N.NON_BUS_DEALS<>T.NON_BUS_DEALS
 OR N.DEAL_SET_ID<>T.DEAL_SET_ID
 OR N.OWNER_TYPE<>T.OWNER_TYPE
 OR N.OWNER_NAME<>T.OWNER_NAME
 OR N.EXTERNAL_REF_ID<>T.EXTERNAL_REF_ID
 OR N.EXTERNAL_REF_TEXT<>T.EXTERNAL_REF_TEXT
 OR N.CCY_RND_OVERRIDE_METH<>T.CCY_RND_OVERRIDE_METH
 OR N.CCY2_RND_OVERRIDE_METH<>T.CCY2_RND_OVERRIDE_METH
 OR N.SCHEDULE_STATUS<>T.SCHEDULE_STATUS
 OR N.DO_ISSUE_FEE<>T.DO_ISSUE_FEE
 OR N.ISSUE_FEE_LAST_ACRL_DATE<>T.ISSUE_FEE_LAST_ACRL_DATE
 OR N.ISSUE_FEE_ACRL_END_DATE<>T.ISSUE_FEE_ACRL_END_DATE
 OR N.PROFILED<>T.PROFILED
 OR N.DO_CCYTRANS<>T.DO_CCYTRANS
 OR N.DO_CCYTRANS_SUM<>T.DO_CCYTRANS_SUM
 OR N.DO_FV_INDEX_ACCRUAL<>T.DO_FV_INDEX_ACCRUAL
 OR N.FV_INDEX_LAST_ACRL_DT<>T.FV_INDEX_LAST_ACRL_DT
 OR N.FV_INDEX_ACRL_END_DATE<>T.FV_INDEX_ACRL_END_DATE
 OR N.STAMP<>T.STAMP
 OR N.DEAL_DATETIME<>T.DEAL_DATETIME
;

--Step3:
UPDATE dw_sdata.COS_000_DEALS P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_152
WHERE P.End_Dt=DATE('2100-12-31')
AND P.DEAL_NO=T_152.DEAL_NO
;

--Step4:
INSERT  INTO dw_sdata.COS_000_DEALS SELECT * FROM T_152;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
