#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.COS_000_BANKACC WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.COS_000_BANKACC SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_147 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.COS_000_BANKACC WHERE 1=0;

--Step2:
INSERT  INTO T_147 (
  THEKEY,
  CPARTY,
  ACC_NO,
  ACC_NAME,
  IBAN_ACC_FORMAT,
  CHARGES_INCOME_CODE,
  CHARGES_EXPENSE_CODE,
  SENDER_CHARGES_CCY,
  SENDER_CHARGES_AMT,
  RECEIVER_CHARGES_CCY,
  RECEIVER_CHARGES_AMT,
  CHARGES_RATETYPE_ID,
  CHARGES_COMMENTS,
  ENTITY,
  TX_ENTITY,
  CCY,
  BAL_DATE,
  INT_DATE,
  TPI_DATE,
  ACCR_DATE,
  ACCR_DATET,
  ACCR_REV,
  ACCR_L_AMT,
  ACCR_R_AMT,
  ACCR_AMT_T,
  CP_OWNER,
  GL_OWNER,
  COA_CODE,
  BAL_GLCODE,
  INT_INC,
  INT_EXP,
  ACCR_INC,
  ACCR_EXP,
  INT_GROUP,
  DEF_METHOD,
  OWNER,
  THELEVEL,
  INSTRUCT,
  FACNAME,
  FAC_OWNER,
  SORT_CODE,
  INT_NAME,
  INT_ADDR,
  USAGE,
  INT_INC_T,
  INT_EXP_T,
  ACCR_INC_T,
  ACCR_EXP_T,
  UPLOAD_KEY,
  BANKACC_MODE,
  VOSTRO_CP,
  VOSTRO_ACC,
  INT_BIC,
  INT_SORT,
  STMTNO,
  CLEAR01,
  CLEAR02,
  CLEAR03,
  CLEAR04,
  CLEAR05,
  I_CLEAR01,
  I_CLEAR02,
  I_CLEAR03,
  I_CLEAR04,
  I_CLEAR05,
  EXT_BAL_DT,
  BFL_BAL_DT,
  IN_USE,
  TAX_GLCODE,
  STAMP,
  ANALYSE01,
  ANALYSE02,
  ANALYSE03,
  ANALYSE04,
  ANALYSE05,
  ANALYSE06,
  ANALYSE07,
  ANALYSE08,
  ANALYSE09,
  ANALYSE10,
  ANALYSE11,
  ANALYSE12,
  ANALYSE13,
  ANALYSE14,
  ANALYSE15,
  ANALYSE16,
  ANALYSE17,
  ANALYSE18,
  ANALYSE19,
  ANALYSE20,
  OBAL_AOD,
  OBAL_PD,
  BA_TBAL,
  TBAL_AMT,
  WS_NON_BUS_DAYS,
  BA_CSH_CON,
  CON_PHASE,
  CON_BANK,
  CON_BA,
  CON_TRF,
  CON_SECTYP,
  CON_ORIG_CPARTY,
  CON_CONC_CPARTY,
  SUR_SEL,
  DEF_SEL,
  SUR_THRSLD,
  DEF_THRSLD,
  IM_GLCODE,
  IM_CONTRA,
  INTERCOMP,
  BTREE_LOW,
  BTREE_HIGH,
  RECMETHOD,
  SWIFT_UNIQUE_IDENT,
  WTAX_INC_COA,
  PRESERVE_INTEREST,
  ACCOUNT_TYPE,
  DEF_ROUND_FACTOR,
  DEF_ROUND_DIRECTION,
  SUR_ROUND_FACTOR,
  SUR_ROUND_DIRECTION,
  start_dt,
  end_dt)
SELECT
  N.THEKEY,
  N.CPARTY,
  N.ACC_NO,
  N.ACC_NAME,
  N.IBAN_ACC_FORMAT,
  N.CHARGES_INCOME_CODE,
  N.CHARGES_EXPENSE_CODE,
  N.SENDER_CHARGES_CCY,
  N.SENDER_CHARGES_AMT,
  N.RECEIVER_CHARGES_CCY,
  N.RECEIVER_CHARGES_AMT,
  N.CHARGES_RATETYPE_ID,
  N.CHARGES_COMMENTS,
  N.ENTITY,
  N.TX_ENTITY,
  N.CCY,
  N.BAL_DATE,
  N.INT_DATE,
  N.TPI_DATE,
  N.ACCR_DATE,
  N.ACCR_DATET,
  N.ACCR_REV,
  N.ACCR_L_AMT,
  N.ACCR_R_AMT,
  N.ACCR_AMT_T,
  N.CP_OWNER,
  N.GL_OWNER,
  N.COA_CODE,
  N.BAL_GLCODE,
  N.INT_INC,
  N.INT_EXP,
  N.ACCR_INC,
  N.ACCR_EXP,
  N.INT_GROUP,
  N.DEF_METHOD,
  N.OWNER,
  N.THELEVEL,
  N.INSTRUCT,
  N.FACNAME,
  N.FAC_OWNER,
  N.SORT_CODE,
  N.INT_NAME,
  N.INT_ADDR,
  N.USAGE,
  N.INT_INC_T,
  N.INT_EXP_T,
  N.ACCR_INC_T,
  N.ACCR_EXP_T,
  N.UPLOAD_KEY,
  N.BANKACC_MODE,
  N.VOSTRO_CP,
  N.VOSTRO_ACC,
  N.INT_BIC,
  N.INT_SORT,
  N.STMTNO,
  N.CLEAR01,
  N.CLEAR02,
  N.CLEAR03,
  N.CLEAR04,
  N.CLEAR05,
  N.I_CLEAR01,
  N.I_CLEAR02,
  N.I_CLEAR03,
  N.I_CLEAR04,
  N.I_CLEAR05,
  N.EXT_BAL_DT,
  N.BFL_BAL_DT,
  N.IN_USE,
  N.TAX_GLCODE,
  N.STAMP,
  N.ANALYSE01,
  N.ANALYSE02,
  N.ANALYSE03,
  N.ANALYSE04,
  N.ANALYSE05,
  N.ANALYSE06,
  N.ANALYSE07,
  N.ANALYSE08,
  N.ANALYSE09,
  N.ANALYSE10,
  N.ANALYSE11,
  N.ANALYSE12,
  N.ANALYSE13,
  N.ANALYSE14,
  N.ANALYSE15,
  N.ANALYSE16,
  N.ANALYSE17,
  N.ANALYSE18,
  N.ANALYSE19,
  N.ANALYSE20,
  N.OBAL_AOD,
  N.OBAL_PD,
  N.BA_TBAL,
  N.TBAL_AMT,
  N.WS_NON_BUS_DAYS,
  N.BA_CSH_CON,
  N.CON_PHASE,
  N.CON_BANK,
  N.CON_BA,
  N.CON_TRF,
  N.CON_SECTYP,
  N.CON_ORIG_CPARTY,
  N.CON_CONC_CPARTY,
  N.SUR_SEL,
  N.DEF_SEL,
  N.SUR_THRSLD,
  N.DEF_THRSLD,
  N.IM_GLCODE,
  N.IM_CONTRA,
  N.INTERCOMP,
  N.BTREE_LOW,
  N.BTREE_HIGH,
  N.RECMETHOD,
  N.SWIFT_UNIQUE_IDENT,
  N.WTAX_INC_COA,
  N.PRESERVE_INTEREST,
  N.ACCOUNT_TYPE,
  N.DEF_ROUND_FACTOR,
  N.DEF_ROUND_DIRECTION,
  N.SUR_ROUND_FACTOR,
  N.SUR_ROUND_DIRECTION,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(THEKEY, '' ) AS THEKEY ,
  COALESCE(CPARTY, '' ) AS CPARTY ,
  COALESCE(ACC_NO, '' ) AS ACC_NO ,
  COALESCE(ACC_NAME, '' ) AS ACC_NAME ,
  COALESCE(IBAN_ACC_FORMAT, '' ) AS IBAN_ACC_FORMAT ,
  COALESCE(CHARGES_INCOME_CODE, 0 ) AS CHARGES_INCOME_CODE ,
  COALESCE(CHARGES_EXPENSE_CODE, 0 ) AS CHARGES_EXPENSE_CODE ,
  COALESCE(SENDER_CHARGES_CCY, '' ) AS SENDER_CHARGES_CCY ,
  COALESCE(SENDER_CHARGES_AMT, 0 ) AS SENDER_CHARGES_AMT ,
  COALESCE(RECEIVER_CHARGES_CCY, '' ) AS RECEIVER_CHARGES_CCY ,
  COALESCE(RECEIVER_CHARGES_AMT, 0 ) AS RECEIVER_CHARGES_AMT ,
  COALESCE(CHARGES_RATETYPE_ID, 0 ) AS CHARGES_RATETYPE_ID ,
  COALESCE(CHARGES_COMMENTS, '' ) AS CHARGES_COMMENTS ,
  COALESCE(ENTITY, '' ) AS ENTITY ,
  COALESCE(TX_ENTITY, '' ) AS TX_ENTITY ,
  COALESCE(CCY, '' ) AS CCY ,
  COALESCE(BAL_DATE, '' ) AS BAL_DATE ,
  COALESCE(INT_DATE, '' ) AS INT_DATE ,
  COALESCE(TPI_DATE, '' ) AS TPI_DATE ,
  COALESCE(ACCR_DATE, '' ) AS ACCR_DATE ,
  COALESCE(ACCR_DATET, '' ) AS ACCR_DATET ,
  COALESCE(ACCR_REV, '' ) AS ACCR_REV ,
  COALESCE(ACCR_L_AMT, 0 ) AS ACCR_L_AMT ,
  COALESCE(ACCR_R_AMT, 0 ) AS ACCR_R_AMT ,
  COALESCE(ACCR_AMT_T, 0 ) AS ACCR_AMT_T ,
  COALESCE(CP_OWNER, '' ) AS CP_OWNER ,
  COALESCE(GL_OWNER, '' ) AS GL_OWNER ,
  COALESCE(COA_CODE, 0 ) AS COA_CODE ,
  COALESCE(BAL_GLCODE, 0 ) AS BAL_GLCODE ,
  COALESCE(INT_INC, 0 ) AS INT_INC ,
  COALESCE(INT_EXP, 0 ) AS INT_EXP ,
  COALESCE(ACCR_INC, 0 ) AS ACCR_INC ,
  COALESCE(ACCR_EXP, 0 ) AS ACCR_EXP ,
  COALESCE(INT_GROUP, '' ) AS INT_GROUP ,
  COALESCE(DEF_METHOD, '' ) AS DEF_METHOD ,
  COALESCE(OWNER, '' ) AS OWNER ,
  COALESCE(THELEVEL, '' ) AS THELEVEL ,
  COALESCE(INSTRUCT, '' ) AS INSTRUCT ,
  COALESCE(FACNAME, '' ) AS FACNAME ,
  COALESCE(FAC_OWNER, '' ) AS FAC_OWNER ,
  COALESCE(SORT_CODE, '' ) AS SORT_CODE ,
  COALESCE(INT_NAME, '' ) AS INT_NAME ,
  COALESCE(INT_ADDR, '' ) AS INT_ADDR ,
  COALESCE(USAGE, 0 ) AS USAGE ,
  COALESCE(INT_INC_T, 0 ) AS INT_INC_T ,
  COALESCE(INT_EXP_T, 0 ) AS INT_EXP_T ,
  COALESCE(ACCR_INC_T, 0 ) AS ACCR_INC_T ,
  COALESCE(ACCR_EXP_T, 0 ) AS ACCR_EXP_T ,
  COALESCE(UPLOAD_KEY, '' ) AS UPLOAD_KEY ,
  COALESCE(BANKACC_MODE, 0 ) AS BANKACC_MODE ,
  COALESCE(VOSTRO_CP, '' ) AS VOSTRO_CP ,
  COALESCE(VOSTRO_ACC, '' ) AS VOSTRO_ACC ,
  COALESCE(INT_BIC, '' ) AS INT_BIC ,
  COALESCE(INT_SORT, '' ) AS INT_SORT ,
  COALESCE(STMTNO, '' ) AS STMTNO ,
  COALESCE(CLEAR01, '' ) AS CLEAR01 ,
  COALESCE(CLEAR02, '' ) AS CLEAR02 ,
  COALESCE(CLEAR03, '' ) AS CLEAR03 ,
  COALESCE(CLEAR04, '' ) AS CLEAR04 ,
  COALESCE(CLEAR05, '' ) AS CLEAR05 ,
  COALESCE(I_CLEAR01, '' ) AS I_CLEAR01 ,
  COALESCE(I_CLEAR02, '' ) AS I_CLEAR02 ,
  COALESCE(I_CLEAR03, '' ) AS I_CLEAR03 ,
  COALESCE(I_CLEAR04, '' ) AS I_CLEAR04 ,
  COALESCE(I_CLEAR05, '' ) AS I_CLEAR05 ,
  COALESCE(EXT_BAL_DT, '' ) AS EXT_BAL_DT ,
  COALESCE(BFL_BAL_DT, '' ) AS BFL_BAL_DT ,
  COALESCE(IN_USE, '' ) AS IN_USE ,
  COALESCE(TAX_GLCODE, 0 ) AS TAX_GLCODE ,
  COALESCE(STAMP, 0 ) AS STAMP ,
  COALESCE(ANALYSE01, '' ) AS ANALYSE01 ,
  COALESCE(ANALYSE02, '' ) AS ANALYSE02 ,
  COALESCE(ANALYSE03, '' ) AS ANALYSE03 ,
  COALESCE(ANALYSE04, '' ) AS ANALYSE04 ,
  COALESCE(ANALYSE05, '' ) AS ANALYSE05 ,
  COALESCE(ANALYSE06, '' ) AS ANALYSE06 ,
  COALESCE(ANALYSE07, '' ) AS ANALYSE07 ,
  COALESCE(ANALYSE08, '' ) AS ANALYSE08 ,
  COALESCE(ANALYSE09, '' ) AS ANALYSE09 ,
  COALESCE(ANALYSE10, '' ) AS ANALYSE10 ,
  COALESCE(ANALYSE11, '' ) AS ANALYSE11 ,
  COALESCE(ANALYSE12, '' ) AS ANALYSE12 ,
  COALESCE(ANALYSE13, '' ) AS ANALYSE13 ,
  COALESCE(ANALYSE14, '' ) AS ANALYSE14 ,
  COALESCE(ANALYSE15, '' ) AS ANALYSE15 ,
  COALESCE(ANALYSE16, '' ) AS ANALYSE16 ,
  COALESCE(ANALYSE17, '' ) AS ANALYSE17 ,
  COALESCE(ANALYSE18, '' ) AS ANALYSE18 ,
  COALESCE(ANALYSE19, '' ) AS ANALYSE19 ,
  COALESCE(ANALYSE20, '' ) AS ANALYSE20 ,
  COALESCE(OBAL_AOD, 0 ) AS OBAL_AOD ,
  COALESCE(OBAL_PD, 0 ) AS OBAL_PD ,
  COALESCE(BA_TBAL, '' ) AS BA_TBAL ,
  COALESCE(TBAL_AMT, 0 ) AS TBAL_AMT ,
  COALESCE(WS_NON_BUS_DAYS, 0 ) AS WS_NON_BUS_DAYS ,
  COALESCE(BA_CSH_CON, '' ) AS BA_CSH_CON ,
  COALESCE(CON_PHASE, 0 ) AS CON_PHASE ,
  COALESCE(CON_BANK, '' ) AS CON_BANK ,
  COALESCE(CON_BA, '' ) AS CON_BA ,
  COALESCE(CON_TRF, '' ) AS CON_TRF ,
  COALESCE(CON_SECTYP, '' ) AS CON_SECTYP ,
  COALESCE(CON_ORIG_CPARTY, '' ) AS CON_ORIG_CPARTY ,
  COALESCE(CON_CONC_CPARTY, '' ) AS CON_CONC_CPARTY ,
  COALESCE(SUR_SEL, '' ) AS SUR_SEL ,
  COALESCE(DEF_SEL, '' ) AS DEF_SEL ,
  COALESCE(SUR_THRSLD, 0 ) AS SUR_THRSLD ,
  COALESCE(DEF_THRSLD, 0 ) AS DEF_THRSLD ,
  COALESCE(IM_GLCODE, 0 ) AS IM_GLCODE ,
  COALESCE(IM_CONTRA, 0 ) AS IM_CONTRA ,
  COALESCE(INTERCOMP, '' ) AS INTERCOMP ,
  COALESCE(BTREE_LOW, 0 ) AS BTREE_LOW ,
  COALESCE(BTREE_HIGH, 0 ) AS BTREE_HIGH ,
  COALESCE(RECMETHOD, '' ) AS RECMETHOD ,
  COALESCE(SWIFT_UNIQUE_IDENT, '' ) AS SWIFT_UNIQUE_IDENT ,
  COALESCE(WTAX_INC_COA, 0 ) AS WTAX_INC_COA ,
  COALESCE(PRESERVE_INTEREST, 0 ) AS PRESERVE_INTEREST ,
  COALESCE(ACCOUNT_TYPE, 0 ) AS ACCOUNT_TYPE ,
  COALESCE(DEF_ROUND_FACTOR, 0 ) AS DEF_ROUND_FACTOR ,
  COALESCE(DEF_ROUND_DIRECTION, 0 ) AS DEF_ROUND_DIRECTION ,
  COALESCE(SUR_ROUND_FACTOR, 0 ) AS SUR_ROUND_FACTOR ,
  COALESCE(SUR_ROUND_DIRECTION, 0 ) AS SUR_ROUND_DIRECTION 
 FROM  dw_tdata.COS_000_BANKACC_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  THEKEY ,
  CPARTY ,
  ACC_NO ,
  ACC_NAME ,
  IBAN_ACC_FORMAT ,
  CHARGES_INCOME_CODE ,
  CHARGES_EXPENSE_CODE ,
  SENDER_CHARGES_CCY ,
  SENDER_CHARGES_AMT ,
  RECEIVER_CHARGES_CCY ,
  RECEIVER_CHARGES_AMT ,
  CHARGES_RATETYPE_ID ,
  CHARGES_COMMENTS ,
  ENTITY ,
  TX_ENTITY ,
  CCY ,
  BAL_DATE ,
  INT_DATE ,
  TPI_DATE ,
  ACCR_DATE ,
  ACCR_DATET ,
  ACCR_REV ,
  ACCR_L_AMT ,
  ACCR_R_AMT ,
  ACCR_AMT_T ,
  CP_OWNER ,
  GL_OWNER ,
  COA_CODE ,
  BAL_GLCODE ,
  INT_INC ,
  INT_EXP ,
  ACCR_INC ,
  ACCR_EXP ,
  INT_GROUP ,
  DEF_METHOD ,
  OWNER ,
  THELEVEL ,
  INSTRUCT ,
  FACNAME ,
  FAC_OWNER ,
  SORT_CODE ,
  INT_NAME ,
  INT_ADDR ,
  USAGE ,
  INT_INC_T ,
  INT_EXP_T ,
  ACCR_INC_T ,
  ACCR_EXP_T ,
  UPLOAD_KEY ,
  BANKACC_MODE ,
  VOSTRO_CP ,
  VOSTRO_ACC ,
  INT_BIC ,
  INT_SORT ,
  STMTNO ,
  CLEAR01 ,
  CLEAR02 ,
  CLEAR03 ,
  CLEAR04 ,
  CLEAR05 ,
  I_CLEAR01 ,
  I_CLEAR02 ,
  I_CLEAR03 ,
  I_CLEAR04 ,
  I_CLEAR05 ,
  EXT_BAL_DT ,
  BFL_BAL_DT ,
  IN_USE ,
  TAX_GLCODE ,
  STAMP ,
  ANALYSE01 ,
  ANALYSE02 ,
  ANALYSE03 ,
  ANALYSE04 ,
  ANALYSE05 ,
  ANALYSE06 ,
  ANALYSE07 ,
  ANALYSE08 ,
  ANALYSE09 ,
  ANALYSE10 ,
  ANALYSE11 ,
  ANALYSE12 ,
  ANALYSE13 ,
  ANALYSE14 ,
  ANALYSE15 ,
  ANALYSE16 ,
  ANALYSE17 ,
  ANALYSE18 ,
  ANALYSE19 ,
  ANALYSE20 ,
  OBAL_AOD ,
  OBAL_PD ,
  BA_TBAL ,
  TBAL_AMT ,
  WS_NON_BUS_DAYS ,
  BA_CSH_CON ,
  CON_PHASE ,
  CON_BANK ,
  CON_BA ,
  CON_TRF ,
  CON_SECTYP ,
  CON_ORIG_CPARTY ,
  CON_CONC_CPARTY ,
  SUR_SEL ,
  DEF_SEL ,
  SUR_THRSLD ,
  DEF_THRSLD ,
  IM_GLCODE ,
  IM_CONTRA ,
  INTERCOMP ,
  BTREE_LOW ,
  BTREE_HIGH ,
  RECMETHOD ,
  SWIFT_UNIQUE_IDENT ,
  WTAX_INC_COA ,
  PRESERVE_INTEREST ,
  ACCOUNT_TYPE ,
  DEF_ROUND_FACTOR ,
  DEF_ROUND_DIRECTION ,
  SUR_ROUND_FACTOR ,
  SUR_ROUND_DIRECTION 
 FROM dw_sdata.COS_000_BANKACC 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.THEKEY = T.THEKEY
WHERE
(T.THEKEY IS NULL)
 OR N.CPARTY<>T.CPARTY
 OR N.ACC_NO<>T.ACC_NO
 OR N.ACC_NAME<>T.ACC_NAME
 OR N.IBAN_ACC_FORMAT<>T.IBAN_ACC_FORMAT
 OR N.CHARGES_INCOME_CODE<>T.CHARGES_INCOME_CODE
 OR N.CHARGES_EXPENSE_CODE<>T.CHARGES_EXPENSE_CODE
 OR N.SENDER_CHARGES_CCY<>T.SENDER_CHARGES_CCY
 OR N.SENDER_CHARGES_AMT<>T.SENDER_CHARGES_AMT
 OR N.RECEIVER_CHARGES_CCY<>T.RECEIVER_CHARGES_CCY
 OR N.RECEIVER_CHARGES_AMT<>T.RECEIVER_CHARGES_AMT
 OR N.CHARGES_RATETYPE_ID<>T.CHARGES_RATETYPE_ID
 OR N.CHARGES_COMMENTS<>T.CHARGES_COMMENTS
 OR N.ENTITY<>T.ENTITY
 OR N.TX_ENTITY<>T.TX_ENTITY
 OR N.CCY<>T.CCY
 OR N.BAL_DATE<>T.BAL_DATE
 OR N.INT_DATE<>T.INT_DATE
 OR N.TPI_DATE<>T.TPI_DATE
 OR N.ACCR_DATE<>T.ACCR_DATE
 OR N.ACCR_DATET<>T.ACCR_DATET
 OR N.ACCR_REV<>T.ACCR_REV
 OR N.ACCR_L_AMT<>T.ACCR_L_AMT
 OR N.ACCR_R_AMT<>T.ACCR_R_AMT
 OR N.ACCR_AMT_T<>T.ACCR_AMT_T
 OR N.CP_OWNER<>T.CP_OWNER
 OR N.GL_OWNER<>T.GL_OWNER
 OR N.COA_CODE<>T.COA_CODE
 OR N.BAL_GLCODE<>T.BAL_GLCODE
 OR N.INT_INC<>T.INT_INC
 OR N.INT_EXP<>T.INT_EXP
 OR N.ACCR_INC<>T.ACCR_INC
 OR N.ACCR_EXP<>T.ACCR_EXP
 OR N.INT_GROUP<>T.INT_GROUP
 OR N.DEF_METHOD<>T.DEF_METHOD
 OR N.OWNER<>T.OWNER
 OR N.THELEVEL<>T.THELEVEL
 OR N.INSTRUCT<>T.INSTRUCT
 OR N.FACNAME<>T.FACNAME
 OR N.FAC_OWNER<>T.FAC_OWNER
 OR N.SORT_CODE<>T.SORT_CODE
 OR N.INT_NAME<>T.INT_NAME
 OR N.INT_ADDR<>T.INT_ADDR
 OR N.USAGE<>T.USAGE
 OR N.INT_INC_T<>T.INT_INC_T
 OR N.INT_EXP_T<>T.INT_EXP_T
 OR N.ACCR_INC_T<>T.ACCR_INC_T
 OR N.ACCR_EXP_T<>T.ACCR_EXP_T
 OR N.UPLOAD_KEY<>T.UPLOAD_KEY
 OR N.BANKACC_MODE<>T.BANKACC_MODE
 OR N.VOSTRO_CP<>T.VOSTRO_CP
 OR N.VOSTRO_ACC<>T.VOSTRO_ACC
 OR N.INT_BIC<>T.INT_BIC
 OR N.INT_SORT<>T.INT_SORT
 OR N.STMTNO<>T.STMTNO
 OR N.CLEAR01<>T.CLEAR01
 OR N.CLEAR02<>T.CLEAR02
 OR N.CLEAR03<>T.CLEAR03
 OR N.CLEAR04<>T.CLEAR04
 OR N.CLEAR05<>T.CLEAR05
 OR N.I_CLEAR01<>T.I_CLEAR01
 OR N.I_CLEAR02<>T.I_CLEAR02
 OR N.I_CLEAR03<>T.I_CLEAR03
 OR N.I_CLEAR04<>T.I_CLEAR04
 OR N.I_CLEAR05<>T.I_CLEAR05
 OR N.EXT_BAL_DT<>T.EXT_BAL_DT
 OR N.BFL_BAL_DT<>T.BFL_BAL_DT
 OR N.IN_USE<>T.IN_USE
 OR N.TAX_GLCODE<>T.TAX_GLCODE
 OR N.STAMP<>T.STAMP
 OR N.ANALYSE01<>T.ANALYSE01
 OR N.ANALYSE02<>T.ANALYSE02
 OR N.ANALYSE03<>T.ANALYSE03
 OR N.ANALYSE04<>T.ANALYSE04
 OR N.ANALYSE05<>T.ANALYSE05
 OR N.ANALYSE06<>T.ANALYSE06
 OR N.ANALYSE07<>T.ANALYSE07
 OR N.ANALYSE08<>T.ANALYSE08
 OR N.ANALYSE09<>T.ANALYSE09
 OR N.ANALYSE10<>T.ANALYSE10
 OR N.ANALYSE11<>T.ANALYSE11
 OR N.ANALYSE12<>T.ANALYSE12
 OR N.ANALYSE13<>T.ANALYSE13
 OR N.ANALYSE14<>T.ANALYSE14
 OR N.ANALYSE15<>T.ANALYSE15
 OR N.ANALYSE16<>T.ANALYSE16
 OR N.ANALYSE17<>T.ANALYSE17
 OR N.ANALYSE18<>T.ANALYSE18
 OR N.ANALYSE19<>T.ANALYSE19
 OR N.ANALYSE20<>T.ANALYSE20
 OR N.OBAL_AOD<>T.OBAL_AOD
 OR N.OBAL_PD<>T.OBAL_PD
 OR N.BA_TBAL<>T.BA_TBAL
 OR N.TBAL_AMT<>T.TBAL_AMT
 OR N.WS_NON_BUS_DAYS<>T.WS_NON_BUS_DAYS
 OR N.BA_CSH_CON<>T.BA_CSH_CON
 OR N.CON_PHASE<>T.CON_PHASE
 OR N.CON_BANK<>T.CON_BANK
 OR N.CON_BA<>T.CON_BA
 OR N.CON_TRF<>T.CON_TRF
 OR N.CON_SECTYP<>T.CON_SECTYP
 OR N.CON_ORIG_CPARTY<>T.CON_ORIG_CPARTY
 OR N.CON_CONC_CPARTY<>T.CON_CONC_CPARTY
 OR N.SUR_SEL<>T.SUR_SEL
 OR N.DEF_SEL<>T.DEF_SEL
 OR N.SUR_THRSLD<>T.SUR_THRSLD
 OR N.DEF_THRSLD<>T.DEF_THRSLD
 OR N.IM_GLCODE<>T.IM_GLCODE
 OR N.IM_CONTRA<>T.IM_CONTRA
 OR N.INTERCOMP<>T.INTERCOMP
 OR N.BTREE_LOW<>T.BTREE_LOW
 OR N.BTREE_HIGH<>T.BTREE_HIGH
 OR N.RECMETHOD<>T.RECMETHOD
 OR N.SWIFT_UNIQUE_IDENT<>T.SWIFT_UNIQUE_IDENT
 OR N.WTAX_INC_COA<>T.WTAX_INC_COA
 OR N.PRESERVE_INTEREST<>T.PRESERVE_INTEREST
 OR N.ACCOUNT_TYPE<>T.ACCOUNT_TYPE
 OR N.DEF_ROUND_FACTOR<>T.DEF_ROUND_FACTOR
 OR N.DEF_ROUND_DIRECTION<>T.DEF_ROUND_DIRECTION
 OR N.SUR_ROUND_FACTOR<>T.SUR_ROUND_FACTOR
 OR N.SUR_ROUND_DIRECTION<>T.SUR_ROUND_DIRECTION
;

--Step3:
UPDATE dw_sdata.COS_000_BANKACC P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_147
WHERE P.End_Dt=DATE('2100-12-31')
AND P.THEKEY=T_147.THEKEY
;

--Step4:
INSERT  INTO dw_sdata.COS_000_BANKACC SELECT * FROM T_147;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
