#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.FRS_000_APP_TPDM_RST_FTP WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.FRS_000_APP_TPDM_RST_FTP SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_173 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.FRS_000_APP_TPDM_RST_FTP WHERE 1=0;

--Step2:
INSERT  INTO T_173 (
  ACCOUNT_NUMBER,
  T_ACCOUNT_NUMBER,
  AS_OF_DATE,
  COMMON_COA_ID,
  XD_PRODUCT_ID,
  CORE_PRODUCT_ID,
  INDUSTRY_ID,
  DEPARTMENT_ID,
  FM_CORP_SIZE,
  CLASSIFY,
  GL_ACCOUNT_ID,
  ISO_CURRENCY_CD,
  ORG_UNIT_ID,
  ORG_UNIT_ID_A,
  ORG_UNIT_ID_O,
  AL_TYPE,
  ORIGINATION_DATE,
  MATURITY_DATE,
  ORG_TERM,
  CLOSE_DATE,
  DATA_SOURCE,
  CUR_BOOK_BAL,
  CUR_NET_RATE,
  ACCRUAL_BASIS_CD,
  OFSA_TRANSFER_RATE,
  OFSA_FTP_INT_DAY,
  OFSA_FTP_INT_YEAR,
  OFSA_FTP_INT_QUAR,
  OFSA_FTP_INT_MONTH,
  AJUST0,
  AJUST0_BAL_DAY,
  AJUST0_BAL_MONTH,
  AJUST0_BAL_QUAR,
  AJUST0_BAL_YEAR,
  AJUST1,
  AJUST1_BAL_DAY,
  AJUST1_BAL_MONTH,
  AJUST1_BAL_QUAR,
  AJUST1_BAL_YEAR,
  AJUST2,
  AJUST2_BAL_DAY,
  AJUST2_BAL_MONTH,
  AJUST2_BAL_QUAR,
  AJUST2_BAL_YEAR,
  AJUST3,
  AJUST3_BAL_DAY,
  AJUST3_BAL_MONTH,
  AJUST3_BAL_QUAR,
  AJUST3_BAL_YEAR,
  AJUST4,
  AJUST4_BAL_DAY,
  AJUST4_BAL_MONTH,
  AJUST4_BAL_QUAR,
  AJUST4_BAL_YEAR,
  AJUST5,
  AJUST5_BAL_DAY,
  AJUST5_BAL_MONTH,
  AJUST5_BAL_QUAR,
  AJUST5_BAL_YEAR,
  AJUST6,
  AJUST6_BAL_DAY,
  AJUST6_BAL_MONTH,
  AJUST6_BAL_QUAR,
  AJUST6_BAL_YEAR,
  AJUST7,
  AJUST7_BAL_DAY,
  AJUST7_BAL_MONTH,
  AJUST7_BAL_QUAR,
  AJUST7_BAL_YEAR,
  AJUST8,
  AJUST8_BAL_DAY,
  AJUST8_BAL_MONTH,
  AJUST8_BAL_QUAR,
  AJUST8_BAL_YEAR,
  AJUST9,
  AJUST9_BAL_DAY,
  AJUST9_BAL_MONTH,
  AJUST9_BAL_QUAR,
  AJUST9_BAL_YEAR,
  AJUST10,
  AJUST10_BAL_DAY,
  AJUST10_BAL_MONTH,
  AJUST10_BAL_QUAR,
  AJUST10_BAL_YEAR,
  AJUST11,
  AJUST11_BAL_DAY,
  AJUST11_BAL_MONTH,
  AJUST11_BAL_QUAR,
  AJUST11_BAL_YEAR,
  AJUST12,
  AJUST12_BAL_DAY,
  AJUST12_BAL_MONTH,
  AJUST12_BAL_QUAR,
  AJUST12_BAL_YEAR,
  AJUST13,
  AJUST13_BAL_DAY,
  AJUST13_BAL_MONTH,
  AJUST13_BAL_QUAR,
  AJUST13_BAL_YEAR,
  FTP_RATE,
  FTP_INT_DAY,
  FTP_INT_YEAR,
  FTP_INT_QUAR,
  FTP_INT_MONTH,
  TRANSFER_RATE_AJUST,
  AGG_BAL_YEAR,
  AGG_BAL_QUAR,
  AGG_BAL_MONTH,
  ACC_INT_DAY,
  ACC_INT_YEAR,
  ACC_INT_QUAR,
  ACC_INT_MONTH,
  ACC_INT_DAY_AJUST,
  ACC_INT_YEAR_AJUST,
  ACC_INT_QUAR_AJUST,
  ACC_INT_MONTH_AJUST,
  INC_PRIC_SPRED_DAY,
  INC_PRIC_SPRED_YEAR,
  INC_PRIC_SPRED_QUAR,
  INC_PRIC_SPRED_MONTH,
  FTP_INT_DAY_AJUST,
  FTP_INT_YEAR_AJUST,
  FTP_INT_QUAR_AJUST,
  FTP_INT_MONTH_AJUST,
  PAY_INT_FLAG,
  SECID,
  PORFOLIO,
  P_FACEAMT,
  P_CLEAN_PRICE,
  S_FACEAMT,
  S_CLEAN_PRICE,
  REMAIN_FACEAMT,
  REMAIN_CLEAN_PRICE,
  PRODUCT_ID,
  CIF_CLIENT_TYPE,
  CIF_KEY,
  LOCK_SPREAD,
  BOND_TYPE_ID,
  FTP_PRODUCT_ID,
  IFLOCK,
  VOUCHTYPE,
  INC_PRIC_SPRED_EXT_DAY,
  INC_PRIC_SPRED_EXT_YEAR,
  INC_PRIC_SPRED_EXT_QUAR,
  INC_PRIC_SPRED_EXT_MONTH,
  GYJZ_BAL_DAY,
  GYJZ_BAL_YEAR,
  GYJZ_BAL_QUAR,
  GYJZ_BAL_MONTH,
  LXTZ_BAL_DAY,
  LXTZ_BAL_YEAR,
  LXTZ_BAL_QUAR,
  LXTZ_BAL_MONTH,
  ACCT_NATURE,
  EXCHANGE_TO_USD_RATE,
  EXCHANGE_TO_CNY_RATE,
  GL_ACCOUNT_ID_O,
  REPRICE_TERM,
  REMAIN_TERM,
  FTP_SCENARION,
  OVERDUE_FLAG,
  TAB_SOURCE,
  ACC_INT_DAY_AJUST_A,
  ACC_INT_YEAR_AJUST_A,
  ACC_INT_QUAR_AJUST_A,
  ACC_INT_MONTH_AJUST_A,
  start_dt,
  end_dt)
SELECT
  N.ACCOUNT_NUMBER,
  N.T_ACCOUNT_NUMBER,
  N.AS_OF_DATE,
  N.COMMON_COA_ID,
  N.XD_PRODUCT_ID,
  N.CORE_PRODUCT_ID,
  N.INDUSTRY_ID,
  N.DEPARTMENT_ID,
  N.FM_CORP_SIZE,
  N.CLASSIFY,
  N.GL_ACCOUNT_ID,
  N.ISO_CURRENCY_CD,
  N.ORG_UNIT_ID,
  N.ORG_UNIT_ID_A,
  N.ORG_UNIT_ID_O,
  N.AL_TYPE,
  N.ORIGINATION_DATE,
  N.MATURITY_DATE,
  N.ORG_TERM,
  N.CLOSE_DATE,
  N.DATA_SOURCE,
  N.CUR_BOOK_BAL,
  N.CUR_NET_RATE,
  N.ACCRUAL_BASIS_CD,
  N.OFSA_TRANSFER_RATE,
  N.OFSA_FTP_INT_DAY,
  N.OFSA_FTP_INT_YEAR,
  N.OFSA_FTP_INT_QUAR,
  N.OFSA_FTP_INT_MONTH,
  N.AJUST0,
  N.AJUST0_BAL_DAY,
  N.AJUST0_BAL_MONTH,
  N.AJUST0_BAL_QUAR,
  N.AJUST0_BAL_YEAR,
  N.AJUST1,
  N.AJUST1_BAL_DAY,
  N.AJUST1_BAL_MONTH,
  N.AJUST1_BAL_QUAR,
  N.AJUST1_BAL_YEAR,
  N.AJUST2,
  N.AJUST2_BAL_DAY,
  N.AJUST2_BAL_MONTH,
  N.AJUST2_BAL_QUAR,
  N.AJUST2_BAL_YEAR,
  N.AJUST3,
  N.AJUST3_BAL_DAY,
  N.AJUST3_BAL_MONTH,
  N.AJUST3_BAL_QUAR,
  N.AJUST3_BAL_YEAR,
  N.AJUST4,
  N.AJUST4_BAL_DAY,
  N.AJUST4_BAL_MONTH,
  N.AJUST4_BAL_QUAR,
  N.AJUST4_BAL_YEAR,
  N.AJUST5,
  N.AJUST5_BAL_DAY,
  N.AJUST5_BAL_MONTH,
  N.AJUST5_BAL_QUAR,
  N.AJUST5_BAL_YEAR,
  N.AJUST6,
  N.AJUST6_BAL_DAY,
  N.AJUST6_BAL_MONTH,
  N.AJUST6_BAL_QUAR,
  N.AJUST6_BAL_YEAR,
  N.AJUST7,
  N.AJUST7_BAL_DAY,
  N.AJUST7_BAL_MONTH,
  N.AJUST7_BAL_QUAR,
  N.AJUST7_BAL_YEAR,
  N.AJUST8,
  N.AJUST8_BAL_DAY,
  N.AJUST8_BAL_MONTH,
  N.AJUST8_BAL_QUAR,
  N.AJUST8_BAL_YEAR,
  N.AJUST9,
  N.AJUST9_BAL_DAY,
  N.AJUST9_BAL_MONTH,
  N.AJUST9_BAL_QUAR,
  N.AJUST9_BAL_YEAR,
  N.AJUST10,
  N.AJUST10_BAL_DAY,
  N.AJUST10_BAL_MONTH,
  N.AJUST10_BAL_QUAR,
  N.AJUST10_BAL_YEAR,
  N.AJUST11,
  N.AJUST11_BAL_DAY,
  N.AJUST11_BAL_MONTH,
  N.AJUST11_BAL_QUAR,
  N.AJUST11_BAL_YEAR,
  N.AJUST12,
  N.AJUST12_BAL_DAY,
  N.AJUST12_BAL_MONTH,
  N.AJUST12_BAL_QUAR,
  N.AJUST12_BAL_YEAR,
  N.AJUST13,
  N.AJUST13_BAL_DAY,
  N.AJUST13_BAL_MONTH,
  N.AJUST13_BAL_QUAR,
  N.AJUST13_BAL_YEAR,
  N.FTP_RATE,
  N.FTP_INT_DAY,
  N.FTP_INT_YEAR,
  N.FTP_INT_QUAR,
  N.FTP_INT_MONTH,
  N.TRANSFER_RATE_AJUST,
  N.AGG_BAL_YEAR,
  N.AGG_BAL_QUAR,
  N.AGG_BAL_MONTH,
  N.ACC_INT_DAY,
  N.ACC_INT_YEAR,
  N.ACC_INT_QUAR,
  N.ACC_INT_MONTH,
  N.ACC_INT_DAY_AJUST,
  N.ACC_INT_YEAR_AJUST,
  N.ACC_INT_QUAR_AJUST,
  N.ACC_INT_MONTH_AJUST,
  N.INC_PRIC_SPRED_DAY,
  N.INC_PRIC_SPRED_YEAR,
  N.INC_PRIC_SPRED_QUAR,
  N.INC_PRIC_SPRED_MONTH,
  N.FTP_INT_DAY_AJUST,
  N.FTP_INT_YEAR_AJUST,
  N.FTP_INT_QUAR_AJUST,
  N.FTP_INT_MONTH_AJUST,
  N.PAY_INT_FLAG,
  N.SECID,
  N.PORFOLIO,
  N.P_FACEAMT,
  N.P_CLEAN_PRICE,
  N.S_FACEAMT,
  N.S_CLEAN_PRICE,
  N.REMAIN_FACEAMT,
  N.REMAIN_CLEAN_PRICE,
  N.PRODUCT_ID,
  N.CIF_CLIENT_TYPE,
  N.CIF_KEY,
  N.LOCK_SPREAD,
  N.BOND_TYPE_ID,
  N.FTP_PRODUCT_ID,
  N.IFLOCK,
  N.VOUCHTYPE,
  N.INC_PRIC_SPRED_EXT_DAY,
  N.INC_PRIC_SPRED_EXT_YEAR,
  N.INC_PRIC_SPRED_EXT_QUAR,
  N.INC_PRIC_SPRED_EXT_MONTH,
  N.GYJZ_BAL_DAY,
  N.GYJZ_BAL_YEAR,
  N.GYJZ_BAL_QUAR,
  N.GYJZ_BAL_MONTH,
  N.LXTZ_BAL_DAY,
  N.LXTZ_BAL_YEAR,
  N.LXTZ_BAL_QUAR,
  N.LXTZ_BAL_MONTH,
  N.ACCT_NATURE,
  N.EXCHANGE_TO_USD_RATE,
  N.EXCHANGE_TO_CNY_RATE,
  N.GL_ACCOUNT_ID_O,
  N.REPRICE_TERM,
  N.REMAIN_TERM,
  N.FTP_SCENARION,
  N.OVERDUE_FLAG,
  N.TAB_SOURCE,
  N.ACC_INT_DAY_AJUST_A,
  N.ACC_INT_YEAR_AJUST_A,
  N.ACC_INT_QUAR_AJUST_A,
  N.ACC_INT_MONTH_AJUST_A,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ACCOUNT_NUMBER, '' ) AS ACCOUNT_NUMBER ,
  COALESCE(T_ACCOUNT_NUMBER, '' ) AS T_ACCOUNT_NUMBER ,
  COALESCE(AS_OF_DATE,DATE('4999-12-31') ) AS AS_OF_DATE ,
  COALESCE(COMMON_COA_ID, '' ) AS COMMON_COA_ID ,
  COALESCE(XD_PRODUCT_ID, '' ) AS XD_PRODUCT_ID ,
  COALESCE(CORE_PRODUCT_ID, '' ) AS CORE_PRODUCT_ID ,
  COALESCE(INDUSTRY_ID, '' ) AS INDUSTRY_ID ,
  COALESCE(DEPARTMENT_ID, '' ) AS DEPARTMENT_ID ,
  COALESCE(FM_CORP_SIZE, '' ) AS FM_CORP_SIZE ,
  COALESCE(CLASSIFY, '' ) AS CLASSIFY ,
  COALESCE(GL_ACCOUNT_ID, '' ) AS GL_ACCOUNT_ID ,
  COALESCE(ISO_CURRENCY_CD, '' ) AS ISO_CURRENCY_CD ,
  COALESCE(ORG_UNIT_ID, '' ) AS ORG_UNIT_ID ,
  COALESCE(ORG_UNIT_ID_A, '' ) AS ORG_UNIT_ID_A ,
  COALESCE(ORG_UNIT_ID_O, '' ) AS ORG_UNIT_ID_O ,
  COALESCE(AL_TYPE, '' ) AS AL_TYPE ,
  COALESCE(ORIGINATION_DATE,DATE('4999-12-31') ) AS ORIGINATION_DATE ,
  COALESCE(MATURITY_DATE,DATE('4999-12-31') ) AS MATURITY_DATE ,
  COALESCE(ORG_TERM, 0 ) AS ORG_TERM ,
  COALESCE(CLOSE_DATE,DATE('4999-12-31') ) AS CLOSE_DATE ,
  COALESCE(DATA_SOURCE, '' ) AS DATA_SOURCE ,
  COALESCE(CUR_BOOK_BAL, 0 ) AS CUR_BOOK_BAL ,
  COALESCE(CUR_NET_RATE, 0 ) AS CUR_NET_RATE ,
  COALESCE(ACCRUAL_BASIS_CD, 0 ) AS ACCRUAL_BASIS_CD ,
  COALESCE(OFSA_TRANSFER_RATE, 0 ) AS OFSA_TRANSFER_RATE ,
  COALESCE(OFSA_FTP_INT_DAY, 0 ) AS OFSA_FTP_INT_DAY ,
  COALESCE(OFSA_FTP_INT_YEAR, 0 ) AS OFSA_FTP_INT_YEAR ,
  COALESCE(OFSA_FTP_INT_QUAR, 0 ) AS OFSA_FTP_INT_QUAR ,
  COALESCE(OFSA_FTP_INT_MONTH, 0 ) AS OFSA_FTP_INT_MONTH ,
  COALESCE(AJUST0, 0 ) AS AJUST0 ,
  COALESCE(AJUST0_BAL_DAY, 0 ) AS AJUST0_BAL_DAY ,
  COALESCE(AJUST0_BAL_MONTH, 0 ) AS AJUST0_BAL_MONTH ,
  COALESCE(AJUST0_BAL_QUAR, 0 ) AS AJUST0_BAL_QUAR ,
  COALESCE(AJUST0_BAL_YEAR, 0 ) AS AJUST0_BAL_YEAR ,
  COALESCE(AJUST1, 0 ) AS AJUST1 ,
  COALESCE(AJUST1_BAL_DAY, 0 ) AS AJUST1_BAL_DAY ,
  COALESCE(AJUST1_BAL_MONTH, 0 ) AS AJUST1_BAL_MONTH ,
  COALESCE(AJUST1_BAL_QUAR, 0 ) AS AJUST1_BAL_QUAR ,
  COALESCE(AJUST1_BAL_YEAR, 0 ) AS AJUST1_BAL_YEAR ,
  COALESCE(AJUST2, 0 ) AS AJUST2 ,
  COALESCE(AJUST2_BAL_DAY, 0 ) AS AJUST2_BAL_DAY ,
  COALESCE(AJUST2_BAL_MONTH, 0 ) AS AJUST2_BAL_MONTH ,
  COALESCE(AJUST2_BAL_QUAR, 0 ) AS AJUST2_BAL_QUAR ,
  COALESCE(AJUST2_BAL_YEAR, 0 ) AS AJUST2_BAL_YEAR ,
  COALESCE(AJUST3, 0 ) AS AJUST3 ,
  COALESCE(AJUST3_BAL_DAY, 0 ) AS AJUST3_BAL_DAY ,
  COALESCE(AJUST3_BAL_MONTH, 0 ) AS AJUST3_BAL_MONTH ,
  COALESCE(AJUST3_BAL_QUAR, 0 ) AS AJUST3_BAL_QUAR ,
  COALESCE(AJUST3_BAL_YEAR, 0 ) AS AJUST3_BAL_YEAR ,
  COALESCE(AJUST4, 0 ) AS AJUST4 ,
  COALESCE(AJUST4_BAL_DAY, 0 ) AS AJUST4_BAL_DAY ,
  COALESCE(AJUST4_BAL_MONTH, 0 ) AS AJUST4_BAL_MONTH ,
  COALESCE(AJUST4_BAL_QUAR, 0 ) AS AJUST4_BAL_QUAR ,
  COALESCE(AJUST4_BAL_YEAR, 0 ) AS AJUST4_BAL_YEAR ,
  COALESCE(AJUST5, 0 ) AS AJUST5 ,
  COALESCE(AJUST5_BAL_DAY, 0 ) AS AJUST5_BAL_DAY ,
  COALESCE(AJUST5_BAL_MONTH, 0 ) AS AJUST5_BAL_MONTH ,
  COALESCE(AJUST5_BAL_QUAR, 0 ) AS AJUST5_BAL_QUAR ,
  COALESCE(AJUST5_BAL_YEAR, 0 ) AS AJUST5_BAL_YEAR ,
  COALESCE(AJUST6, 0 ) AS AJUST6 ,
  COALESCE(AJUST6_BAL_DAY, 0 ) AS AJUST6_BAL_DAY ,
  COALESCE(AJUST6_BAL_MONTH, 0 ) AS AJUST6_BAL_MONTH ,
  COALESCE(AJUST6_BAL_QUAR, 0 ) AS AJUST6_BAL_QUAR ,
  COALESCE(AJUST6_BAL_YEAR, 0 ) AS AJUST6_BAL_YEAR ,
  COALESCE(AJUST7, 0 ) AS AJUST7 ,
  COALESCE(AJUST7_BAL_DAY, 0 ) AS AJUST7_BAL_DAY ,
  COALESCE(AJUST7_BAL_MONTH, 0 ) AS AJUST7_BAL_MONTH ,
  COALESCE(AJUST7_BAL_QUAR, 0 ) AS AJUST7_BAL_QUAR ,
  COALESCE(AJUST7_BAL_YEAR, 0 ) AS AJUST7_BAL_YEAR ,
  COALESCE(AJUST8, 0 ) AS AJUST8 ,
  COALESCE(AJUST8_BAL_DAY, 0 ) AS AJUST8_BAL_DAY ,
  COALESCE(AJUST8_BAL_MONTH, 0 ) AS AJUST8_BAL_MONTH ,
  COALESCE(AJUST8_BAL_QUAR, 0 ) AS AJUST8_BAL_QUAR ,
  COALESCE(AJUST8_BAL_YEAR, 0 ) AS AJUST8_BAL_YEAR ,
  COALESCE(AJUST9, 0 ) AS AJUST9 ,
  COALESCE(AJUST9_BAL_DAY, 0 ) AS AJUST9_BAL_DAY ,
  COALESCE(AJUST9_BAL_MONTH, 0 ) AS AJUST9_BAL_MONTH ,
  COALESCE(AJUST9_BAL_QUAR, 0 ) AS AJUST9_BAL_QUAR ,
  COALESCE(AJUST9_BAL_YEAR, 0 ) AS AJUST9_BAL_YEAR ,
  COALESCE(AJUST10, 0 ) AS AJUST10 ,
  COALESCE(AJUST10_BAL_DAY, 0 ) AS AJUST10_BAL_DAY ,
  COALESCE(AJUST10_BAL_MONTH, 0 ) AS AJUST10_BAL_MONTH ,
  COALESCE(AJUST10_BAL_QUAR, 0 ) AS AJUST10_BAL_QUAR ,
  COALESCE(AJUST10_BAL_YEAR, 0 ) AS AJUST10_BAL_YEAR ,
  COALESCE(AJUST11, 0 ) AS AJUST11 ,
  COALESCE(AJUST11_BAL_DAY, 0 ) AS AJUST11_BAL_DAY ,
  COALESCE(AJUST11_BAL_MONTH, 0 ) AS AJUST11_BAL_MONTH ,
  COALESCE(AJUST11_BAL_QUAR, 0 ) AS AJUST11_BAL_QUAR ,
  COALESCE(AJUST11_BAL_YEAR, 0 ) AS AJUST11_BAL_YEAR ,
  COALESCE(AJUST12, 0 ) AS AJUST12 ,
  COALESCE(AJUST12_BAL_DAY, 0 ) AS AJUST12_BAL_DAY ,
  COALESCE(AJUST12_BAL_MONTH, 0 ) AS AJUST12_BAL_MONTH ,
  COALESCE(AJUST12_BAL_QUAR, 0 ) AS AJUST12_BAL_QUAR ,
  COALESCE(AJUST12_BAL_YEAR, 0 ) AS AJUST12_BAL_YEAR ,
  COALESCE(AJUST13, 0 ) AS AJUST13 ,
  COALESCE(AJUST13_BAL_DAY, 0 ) AS AJUST13_BAL_DAY ,
  COALESCE(AJUST13_BAL_MONTH, 0 ) AS AJUST13_BAL_MONTH ,
  COALESCE(AJUST13_BAL_QUAR, 0 ) AS AJUST13_BAL_QUAR ,
  COALESCE(AJUST13_BAL_YEAR, 0 ) AS AJUST13_BAL_YEAR ,
  COALESCE(FTP_RATE, 0 ) AS FTP_RATE ,
  COALESCE(FTP_INT_DAY, 0 ) AS FTP_INT_DAY ,
  COALESCE(FTP_INT_YEAR, 0 ) AS FTP_INT_YEAR ,
  COALESCE(FTP_INT_QUAR, 0 ) AS FTP_INT_QUAR ,
  COALESCE(FTP_INT_MONTH, 0 ) AS FTP_INT_MONTH ,
  COALESCE(TRANSFER_RATE_AJUST, 0 ) AS TRANSFER_RATE_AJUST ,
  COALESCE(AGG_BAL_YEAR, 0 ) AS AGG_BAL_YEAR ,
  COALESCE(AGG_BAL_QUAR, 0 ) AS AGG_BAL_QUAR ,
  COALESCE(AGG_BAL_MONTH, 0 ) AS AGG_BAL_MONTH ,
  COALESCE(ACC_INT_DAY, 0 ) AS ACC_INT_DAY ,
  COALESCE(ACC_INT_YEAR, 0 ) AS ACC_INT_YEAR ,
  COALESCE(ACC_INT_QUAR, 0 ) AS ACC_INT_QUAR ,
  COALESCE(ACC_INT_MONTH, 0 ) AS ACC_INT_MONTH ,
  COALESCE(ACC_INT_DAY_AJUST, 0 ) AS ACC_INT_DAY_AJUST ,
  COALESCE(ACC_INT_YEAR_AJUST, 0 ) AS ACC_INT_YEAR_AJUST ,
  COALESCE(ACC_INT_QUAR_AJUST, 0 ) AS ACC_INT_QUAR_AJUST ,
  COALESCE(ACC_INT_MONTH_AJUST, 0 ) AS ACC_INT_MONTH_AJUST ,
  COALESCE(INC_PRIC_SPRED_DAY, 0 ) AS INC_PRIC_SPRED_DAY ,
  COALESCE(INC_PRIC_SPRED_YEAR, 0 ) AS INC_PRIC_SPRED_YEAR ,
  COALESCE(INC_PRIC_SPRED_QUAR, 0 ) AS INC_PRIC_SPRED_QUAR ,
  COALESCE(INC_PRIC_SPRED_MONTH, 0 ) AS INC_PRIC_SPRED_MONTH ,
  COALESCE(FTP_INT_DAY_AJUST, 0 ) AS FTP_INT_DAY_AJUST ,
  COALESCE(FTP_INT_YEAR_AJUST, 0 ) AS FTP_INT_YEAR_AJUST ,
  COALESCE(FTP_INT_QUAR_AJUST, 0 ) AS FTP_INT_QUAR_AJUST ,
  COALESCE(FTP_INT_MONTH_AJUST, 0 ) AS FTP_INT_MONTH_AJUST ,
  COALESCE(PAY_INT_FLAG, 0 ) AS PAY_INT_FLAG ,
  COALESCE(SECID, '' ) AS SECID ,
  COALESCE(PORFOLIO, '' ) AS PORFOLIO ,
  COALESCE(P_FACEAMT, 0 ) AS P_FACEAMT ,
  COALESCE(P_CLEAN_PRICE, 0 ) AS P_CLEAN_PRICE ,
  COALESCE(S_FACEAMT, 0 ) AS S_FACEAMT ,
  COALESCE(S_CLEAN_PRICE, 0 ) AS S_CLEAN_PRICE ,
  COALESCE(REMAIN_FACEAMT, 0 ) AS REMAIN_FACEAMT ,
  COALESCE(REMAIN_CLEAN_PRICE, 0 ) AS REMAIN_CLEAN_PRICE ,
  COALESCE(PRODUCT_ID, 0 ) AS PRODUCT_ID ,
  COALESCE(CIF_CLIENT_TYPE, '' ) AS CIF_CLIENT_TYPE ,
  COALESCE(CIF_KEY, '' ) AS CIF_KEY ,
  COALESCE(LOCK_SPREAD, 0 ) AS LOCK_SPREAD ,
  COALESCE(BOND_TYPE_ID, '' ) AS BOND_TYPE_ID ,
  COALESCE(FTP_PRODUCT_ID, '' ) AS FTP_PRODUCT_ID ,
  COALESCE(IFLOCK, '' ) AS IFLOCK ,
  COALESCE(VOUCHTYPE, '' ) AS VOUCHTYPE ,
  COALESCE(INC_PRIC_SPRED_EXT_DAY, 0 ) AS INC_PRIC_SPRED_EXT_DAY ,
  COALESCE(INC_PRIC_SPRED_EXT_YEAR, 0 ) AS INC_PRIC_SPRED_EXT_YEAR ,
  COALESCE(INC_PRIC_SPRED_EXT_QUAR, 0 ) AS INC_PRIC_SPRED_EXT_QUAR ,
  COALESCE(INC_PRIC_SPRED_EXT_MONTH, 0 ) AS INC_PRIC_SPRED_EXT_MONTH ,
  COALESCE(GYJZ_BAL_DAY, 0 ) AS GYJZ_BAL_DAY ,
  COALESCE(GYJZ_BAL_YEAR, 0 ) AS GYJZ_BAL_YEAR ,
  COALESCE(GYJZ_BAL_QUAR, 0 ) AS GYJZ_BAL_QUAR ,
  COALESCE(GYJZ_BAL_MONTH, 0 ) AS GYJZ_BAL_MONTH ,
  COALESCE(LXTZ_BAL_DAY, 0 ) AS LXTZ_BAL_DAY ,
  COALESCE(LXTZ_BAL_YEAR, 0 ) AS LXTZ_BAL_YEAR ,
  COALESCE(LXTZ_BAL_QUAR, 0 ) AS LXTZ_BAL_QUAR ,
  COALESCE(LXTZ_BAL_MONTH, 0 ) AS LXTZ_BAL_MONTH ,
  COALESCE(ACCT_NATURE, '' ) AS ACCT_NATURE ,
  COALESCE(EXCHANGE_TO_USD_RATE, 0 ) AS EXCHANGE_TO_USD_RATE ,
  COALESCE(EXCHANGE_TO_CNY_RATE, 0 ) AS EXCHANGE_TO_CNY_RATE ,
  COALESCE(GL_ACCOUNT_ID_O, '' ) AS GL_ACCOUNT_ID_O ,
  COALESCE(REPRICE_TERM, 0 ) AS REPRICE_TERM ,
  COALESCE(REMAIN_TERM, 0 ) AS REMAIN_TERM ,
  COALESCE(FTP_SCENARION, '' ) AS FTP_SCENARION ,
  COALESCE(OVERDUE_FLAG, 0 ) AS OVERDUE_FLAG ,
  COALESCE(TAB_SOURCE, '' ) AS TAB_SOURCE ,
  COALESCE(ACC_INT_DAY_AJUST_A, 0 ) AS ACC_INT_DAY_AJUST_A ,
  COALESCE(ACC_INT_YEAR_AJUST_A, 0 ) AS ACC_INT_YEAR_AJUST_A ,
  COALESCE(ACC_INT_QUAR_AJUST_A, 0 ) AS ACC_INT_QUAR_AJUST_A ,
  COALESCE(ACC_INT_MONTH_AJUST_A, 0 ) AS ACC_INT_MONTH_AJUST_A 
 FROM  dw_tdata.FRS_000_APP_TPDM_RST_FTP_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ACCOUNT_NUMBER ,
  T_ACCOUNT_NUMBER ,
  AS_OF_DATE ,
  COMMON_COA_ID ,
  XD_PRODUCT_ID ,
  CORE_PRODUCT_ID ,
  INDUSTRY_ID ,
  DEPARTMENT_ID ,
  FM_CORP_SIZE ,
  CLASSIFY ,
  GL_ACCOUNT_ID ,
  ISO_CURRENCY_CD ,
  ORG_UNIT_ID ,
  ORG_UNIT_ID_A ,
  ORG_UNIT_ID_O ,
  AL_TYPE ,
  ORIGINATION_DATE ,
  MATURITY_DATE ,
  ORG_TERM ,
  CLOSE_DATE ,
  DATA_SOURCE ,
  CUR_BOOK_BAL ,
  CUR_NET_RATE ,
  ACCRUAL_BASIS_CD ,
  OFSA_TRANSFER_RATE ,
  OFSA_FTP_INT_DAY ,
  OFSA_FTP_INT_YEAR ,
  OFSA_FTP_INT_QUAR ,
  OFSA_FTP_INT_MONTH ,
  AJUST0 ,
  AJUST0_BAL_DAY ,
  AJUST0_BAL_MONTH ,
  AJUST0_BAL_QUAR ,
  AJUST0_BAL_YEAR ,
  AJUST1 ,
  AJUST1_BAL_DAY ,
  AJUST1_BAL_MONTH ,
  AJUST1_BAL_QUAR ,
  AJUST1_BAL_YEAR ,
  AJUST2 ,
  AJUST2_BAL_DAY ,
  AJUST2_BAL_MONTH ,
  AJUST2_BAL_QUAR ,
  AJUST2_BAL_YEAR ,
  AJUST3 ,
  AJUST3_BAL_DAY ,
  AJUST3_BAL_MONTH ,
  AJUST3_BAL_QUAR ,
  AJUST3_BAL_YEAR ,
  AJUST4 ,
  AJUST4_BAL_DAY ,
  AJUST4_BAL_MONTH ,
  AJUST4_BAL_QUAR ,
  AJUST4_BAL_YEAR ,
  AJUST5 ,
  AJUST5_BAL_DAY ,
  AJUST5_BAL_MONTH ,
  AJUST5_BAL_QUAR ,
  AJUST5_BAL_YEAR ,
  AJUST6 ,
  AJUST6_BAL_DAY ,
  AJUST6_BAL_MONTH ,
  AJUST6_BAL_QUAR ,
  AJUST6_BAL_YEAR ,
  AJUST7 ,
  AJUST7_BAL_DAY ,
  AJUST7_BAL_MONTH ,
  AJUST7_BAL_QUAR ,
  AJUST7_BAL_YEAR ,
  AJUST8 ,
  AJUST8_BAL_DAY ,
  AJUST8_BAL_MONTH ,
  AJUST8_BAL_QUAR ,
  AJUST8_BAL_YEAR ,
  AJUST9 ,
  AJUST9_BAL_DAY ,
  AJUST9_BAL_MONTH ,
  AJUST9_BAL_QUAR ,
  AJUST9_BAL_YEAR ,
  AJUST10 ,
  AJUST10_BAL_DAY ,
  AJUST10_BAL_MONTH ,
  AJUST10_BAL_QUAR ,
  AJUST10_BAL_YEAR ,
  AJUST11 ,
  AJUST11_BAL_DAY ,
  AJUST11_BAL_MONTH ,
  AJUST11_BAL_QUAR ,
  AJUST11_BAL_YEAR ,
  AJUST12 ,
  AJUST12_BAL_DAY ,
  AJUST12_BAL_MONTH ,
  AJUST12_BAL_QUAR ,
  AJUST12_BAL_YEAR ,
  AJUST13 ,
  AJUST13_BAL_DAY ,
  AJUST13_BAL_MONTH ,
  AJUST13_BAL_QUAR ,
  AJUST13_BAL_YEAR ,
  FTP_RATE ,
  FTP_INT_DAY ,
  FTP_INT_YEAR ,
  FTP_INT_QUAR ,
  FTP_INT_MONTH ,
  TRANSFER_RATE_AJUST ,
  AGG_BAL_YEAR ,
  AGG_BAL_QUAR ,
  AGG_BAL_MONTH ,
  ACC_INT_DAY ,
  ACC_INT_YEAR ,
  ACC_INT_QUAR ,
  ACC_INT_MONTH ,
  ACC_INT_DAY_AJUST ,
  ACC_INT_YEAR_AJUST ,
  ACC_INT_QUAR_AJUST ,
  ACC_INT_MONTH_AJUST ,
  INC_PRIC_SPRED_DAY ,
  INC_PRIC_SPRED_YEAR ,
  INC_PRIC_SPRED_QUAR ,
  INC_PRIC_SPRED_MONTH ,
  FTP_INT_DAY_AJUST ,
  FTP_INT_YEAR_AJUST ,
  FTP_INT_QUAR_AJUST ,
  FTP_INT_MONTH_AJUST ,
  PAY_INT_FLAG ,
  SECID ,
  PORFOLIO ,
  P_FACEAMT ,
  P_CLEAN_PRICE ,
  S_FACEAMT ,
  S_CLEAN_PRICE ,
  REMAIN_FACEAMT ,
  REMAIN_CLEAN_PRICE ,
  PRODUCT_ID ,
  CIF_CLIENT_TYPE ,
  CIF_KEY ,
  LOCK_SPREAD ,
  BOND_TYPE_ID ,
  FTP_PRODUCT_ID ,
  IFLOCK ,
  VOUCHTYPE ,
  INC_PRIC_SPRED_EXT_DAY ,
  INC_PRIC_SPRED_EXT_YEAR ,
  INC_PRIC_SPRED_EXT_QUAR ,
  INC_PRIC_SPRED_EXT_MONTH ,
  GYJZ_BAL_DAY ,
  GYJZ_BAL_YEAR ,
  GYJZ_BAL_QUAR ,
  GYJZ_BAL_MONTH ,
  LXTZ_BAL_DAY ,
  LXTZ_BAL_YEAR ,
  LXTZ_BAL_QUAR ,
  LXTZ_BAL_MONTH ,
  ACCT_NATURE ,
  EXCHANGE_TO_USD_RATE ,
  EXCHANGE_TO_CNY_RATE ,
  GL_ACCOUNT_ID_O ,
  REPRICE_TERM ,
  REMAIN_TERM ,
  FTP_SCENARION ,
  OVERDUE_FLAG ,
  TAB_SOURCE ,
  ACC_INT_DAY_AJUST_A ,
  ACC_INT_YEAR_AJUST_A ,
  ACC_INT_QUAR_AJUST_A ,
  ACC_INT_MONTH_AJUST_A 
 FROM dw_sdata.FRS_000_APP_TPDM_RST_FTP 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ACCOUNT_NUMBER = T.ACCOUNT_NUMBER AND N.AS_OF_DATE = T.AS_OF_DATE AND N.GL_ACCOUNT_ID = T.GL_ACCOUNT_ID
WHERE
(T.ACCOUNT_NUMBER IS NULL AND T.AS_OF_DATE IS NULL AND T.GL_ACCOUNT_ID IS NULL)
 OR N.T_ACCOUNT_NUMBER<>T.T_ACCOUNT_NUMBER
 OR N.COMMON_COA_ID<>T.COMMON_COA_ID
 OR N.XD_PRODUCT_ID<>T.XD_PRODUCT_ID
 OR N.CORE_PRODUCT_ID<>T.CORE_PRODUCT_ID
 OR N.INDUSTRY_ID<>T.INDUSTRY_ID
 OR N.DEPARTMENT_ID<>T.DEPARTMENT_ID
 OR N.FM_CORP_SIZE<>T.FM_CORP_SIZE
 OR N.CLASSIFY<>T.CLASSIFY
 OR N.ISO_CURRENCY_CD<>T.ISO_CURRENCY_CD
 OR N.ORG_UNIT_ID<>T.ORG_UNIT_ID
 OR N.ORG_UNIT_ID_A<>T.ORG_UNIT_ID_A
 OR N.ORG_UNIT_ID_O<>T.ORG_UNIT_ID_O
 OR N.AL_TYPE<>T.AL_TYPE
 OR N.ORIGINATION_DATE<>T.ORIGINATION_DATE
 OR N.MATURITY_DATE<>T.MATURITY_DATE
 OR N.ORG_TERM<>T.ORG_TERM
 OR N.CLOSE_DATE<>T.CLOSE_DATE
 OR N.DATA_SOURCE<>T.DATA_SOURCE
 OR N.CUR_BOOK_BAL<>T.CUR_BOOK_BAL
 OR N.CUR_NET_RATE<>T.CUR_NET_RATE
 OR N.ACCRUAL_BASIS_CD<>T.ACCRUAL_BASIS_CD
 OR N.OFSA_TRANSFER_RATE<>T.OFSA_TRANSFER_RATE
 OR N.OFSA_FTP_INT_DAY<>T.OFSA_FTP_INT_DAY
 OR N.OFSA_FTP_INT_YEAR<>T.OFSA_FTP_INT_YEAR
 OR N.OFSA_FTP_INT_QUAR<>T.OFSA_FTP_INT_QUAR
 OR N.OFSA_FTP_INT_MONTH<>T.OFSA_FTP_INT_MONTH
 OR N.AJUST0<>T.AJUST0
 OR N.AJUST0_BAL_DAY<>T.AJUST0_BAL_DAY
 OR N.AJUST0_BAL_MONTH<>T.AJUST0_BAL_MONTH
 OR N.AJUST0_BAL_QUAR<>T.AJUST0_BAL_QUAR
 OR N.AJUST0_BAL_YEAR<>T.AJUST0_BAL_YEAR
 OR N.AJUST1<>T.AJUST1
 OR N.AJUST1_BAL_DAY<>T.AJUST1_BAL_DAY
 OR N.AJUST1_BAL_MONTH<>T.AJUST1_BAL_MONTH
 OR N.AJUST1_BAL_QUAR<>T.AJUST1_BAL_QUAR
 OR N.AJUST1_BAL_YEAR<>T.AJUST1_BAL_YEAR
 OR N.AJUST2<>T.AJUST2
 OR N.AJUST2_BAL_DAY<>T.AJUST2_BAL_DAY
 OR N.AJUST2_BAL_MONTH<>T.AJUST2_BAL_MONTH
 OR N.AJUST2_BAL_QUAR<>T.AJUST2_BAL_QUAR
 OR N.AJUST2_BAL_YEAR<>T.AJUST2_BAL_YEAR
 OR N.AJUST3<>T.AJUST3
 OR N.AJUST3_BAL_DAY<>T.AJUST3_BAL_DAY
 OR N.AJUST3_BAL_MONTH<>T.AJUST3_BAL_MONTH
 OR N.AJUST3_BAL_QUAR<>T.AJUST3_BAL_QUAR
 OR N.AJUST3_BAL_YEAR<>T.AJUST3_BAL_YEAR
 OR N.AJUST4<>T.AJUST4
 OR N.AJUST4_BAL_DAY<>T.AJUST4_BAL_DAY
 OR N.AJUST4_BAL_MONTH<>T.AJUST4_BAL_MONTH
 OR N.AJUST4_BAL_QUAR<>T.AJUST4_BAL_QUAR
 OR N.AJUST4_BAL_YEAR<>T.AJUST4_BAL_YEAR
 OR N.AJUST5<>T.AJUST5
 OR N.AJUST5_BAL_DAY<>T.AJUST5_BAL_DAY
 OR N.AJUST5_BAL_MONTH<>T.AJUST5_BAL_MONTH
 OR N.AJUST5_BAL_QUAR<>T.AJUST5_BAL_QUAR
 OR N.AJUST5_BAL_YEAR<>T.AJUST5_BAL_YEAR
 OR N.AJUST6<>T.AJUST6
 OR N.AJUST6_BAL_DAY<>T.AJUST6_BAL_DAY
 OR N.AJUST6_BAL_MONTH<>T.AJUST6_BAL_MONTH
 OR N.AJUST6_BAL_QUAR<>T.AJUST6_BAL_QUAR
 OR N.AJUST6_BAL_YEAR<>T.AJUST6_BAL_YEAR
 OR N.AJUST7<>T.AJUST7
 OR N.AJUST7_BAL_DAY<>T.AJUST7_BAL_DAY
 OR N.AJUST7_BAL_MONTH<>T.AJUST7_BAL_MONTH
 OR N.AJUST7_BAL_QUAR<>T.AJUST7_BAL_QUAR
 OR N.AJUST7_BAL_YEAR<>T.AJUST7_BAL_YEAR
 OR N.AJUST8<>T.AJUST8
 OR N.AJUST8_BAL_DAY<>T.AJUST8_BAL_DAY
 OR N.AJUST8_BAL_MONTH<>T.AJUST8_BAL_MONTH
 OR N.AJUST8_BAL_QUAR<>T.AJUST8_BAL_QUAR
 OR N.AJUST8_BAL_YEAR<>T.AJUST8_BAL_YEAR
 OR N.AJUST9<>T.AJUST9
 OR N.AJUST9_BAL_DAY<>T.AJUST9_BAL_DAY
 OR N.AJUST9_BAL_MONTH<>T.AJUST9_BAL_MONTH
 OR N.AJUST9_BAL_QUAR<>T.AJUST9_BAL_QUAR
 OR N.AJUST9_BAL_YEAR<>T.AJUST9_BAL_YEAR
 OR N.AJUST10<>T.AJUST10
 OR N.AJUST10_BAL_DAY<>T.AJUST10_BAL_DAY
 OR N.AJUST10_BAL_MONTH<>T.AJUST10_BAL_MONTH
 OR N.AJUST10_BAL_QUAR<>T.AJUST10_BAL_QUAR
 OR N.AJUST10_BAL_YEAR<>T.AJUST10_BAL_YEAR
 OR N.AJUST11<>T.AJUST11
 OR N.AJUST11_BAL_DAY<>T.AJUST11_BAL_DAY
 OR N.AJUST11_BAL_MONTH<>T.AJUST11_BAL_MONTH
 OR N.AJUST11_BAL_QUAR<>T.AJUST11_BAL_QUAR
 OR N.AJUST11_BAL_YEAR<>T.AJUST11_BAL_YEAR
 OR N.AJUST12<>T.AJUST12
 OR N.AJUST12_BAL_DAY<>T.AJUST12_BAL_DAY
 OR N.AJUST12_BAL_MONTH<>T.AJUST12_BAL_MONTH
 OR N.AJUST12_BAL_QUAR<>T.AJUST12_BAL_QUAR
 OR N.AJUST12_BAL_YEAR<>T.AJUST12_BAL_YEAR
 OR N.AJUST13<>T.AJUST13
 OR N.AJUST13_BAL_DAY<>T.AJUST13_BAL_DAY
 OR N.AJUST13_BAL_MONTH<>T.AJUST13_BAL_MONTH
 OR N.AJUST13_BAL_QUAR<>T.AJUST13_BAL_QUAR
 OR N.AJUST13_BAL_YEAR<>T.AJUST13_BAL_YEAR
 OR N.FTP_RATE<>T.FTP_RATE
 OR N.FTP_INT_DAY<>T.FTP_INT_DAY
 OR N.FTP_INT_YEAR<>T.FTP_INT_YEAR
 OR N.FTP_INT_QUAR<>T.FTP_INT_QUAR
 OR N.FTP_INT_MONTH<>T.FTP_INT_MONTH
 OR N.TRANSFER_RATE_AJUST<>T.TRANSFER_RATE_AJUST
 OR N.AGG_BAL_YEAR<>T.AGG_BAL_YEAR
 OR N.AGG_BAL_QUAR<>T.AGG_BAL_QUAR
 OR N.AGG_BAL_MONTH<>T.AGG_BAL_MONTH
 OR N.ACC_INT_DAY<>T.ACC_INT_DAY
 OR N.ACC_INT_YEAR<>T.ACC_INT_YEAR
 OR N.ACC_INT_QUAR<>T.ACC_INT_QUAR
 OR N.ACC_INT_MONTH<>T.ACC_INT_MONTH
 OR N.ACC_INT_DAY_AJUST<>T.ACC_INT_DAY_AJUST
 OR N.ACC_INT_YEAR_AJUST<>T.ACC_INT_YEAR_AJUST
 OR N.ACC_INT_QUAR_AJUST<>T.ACC_INT_QUAR_AJUST
 OR N.ACC_INT_MONTH_AJUST<>T.ACC_INT_MONTH_AJUST
 OR N.INC_PRIC_SPRED_DAY<>T.INC_PRIC_SPRED_DAY
 OR N.INC_PRIC_SPRED_YEAR<>T.INC_PRIC_SPRED_YEAR
 OR N.INC_PRIC_SPRED_QUAR<>T.INC_PRIC_SPRED_QUAR
 OR N.INC_PRIC_SPRED_MONTH<>T.INC_PRIC_SPRED_MONTH
 OR N.FTP_INT_DAY_AJUST<>T.FTP_INT_DAY_AJUST
 OR N.FTP_INT_YEAR_AJUST<>T.FTP_INT_YEAR_AJUST
 OR N.FTP_INT_QUAR_AJUST<>T.FTP_INT_QUAR_AJUST
 OR N.FTP_INT_MONTH_AJUST<>T.FTP_INT_MONTH_AJUST
 OR N.PAY_INT_FLAG<>T.PAY_INT_FLAG
 OR N.SECID<>T.SECID
 OR N.PORFOLIO<>T.PORFOLIO
 OR N.P_FACEAMT<>T.P_FACEAMT
 OR N.P_CLEAN_PRICE<>T.P_CLEAN_PRICE
 OR N.S_FACEAMT<>T.S_FACEAMT
 OR N.S_CLEAN_PRICE<>T.S_CLEAN_PRICE
 OR N.REMAIN_FACEAMT<>T.REMAIN_FACEAMT
 OR N.REMAIN_CLEAN_PRICE<>T.REMAIN_CLEAN_PRICE
 OR N.PRODUCT_ID<>T.PRODUCT_ID
 OR N.CIF_CLIENT_TYPE<>T.CIF_CLIENT_TYPE
 OR N.CIF_KEY<>T.CIF_KEY
 OR N.LOCK_SPREAD<>T.LOCK_SPREAD
 OR N.BOND_TYPE_ID<>T.BOND_TYPE_ID
 OR N.FTP_PRODUCT_ID<>T.FTP_PRODUCT_ID
 OR N.IFLOCK<>T.IFLOCK
 OR N.VOUCHTYPE<>T.VOUCHTYPE
 OR N.INC_PRIC_SPRED_EXT_DAY<>T.INC_PRIC_SPRED_EXT_DAY
 OR N.INC_PRIC_SPRED_EXT_YEAR<>T.INC_PRIC_SPRED_EXT_YEAR
 OR N.INC_PRIC_SPRED_EXT_QUAR<>T.INC_PRIC_SPRED_EXT_QUAR
 OR N.INC_PRIC_SPRED_EXT_MONTH<>T.INC_PRIC_SPRED_EXT_MONTH
 OR N.GYJZ_BAL_DAY<>T.GYJZ_BAL_DAY
 OR N.GYJZ_BAL_YEAR<>T.GYJZ_BAL_YEAR
 OR N.GYJZ_BAL_QUAR<>T.GYJZ_BAL_QUAR
 OR N.GYJZ_BAL_MONTH<>T.GYJZ_BAL_MONTH
 OR N.LXTZ_BAL_DAY<>T.LXTZ_BAL_DAY
 OR N.LXTZ_BAL_YEAR<>T.LXTZ_BAL_YEAR
 OR N.LXTZ_BAL_QUAR<>T.LXTZ_BAL_QUAR
 OR N.LXTZ_BAL_MONTH<>T.LXTZ_BAL_MONTH
 OR N.ACCT_NATURE<>T.ACCT_NATURE
 OR N.EXCHANGE_TO_USD_RATE<>T.EXCHANGE_TO_USD_RATE
 OR N.EXCHANGE_TO_CNY_RATE<>T.EXCHANGE_TO_CNY_RATE
 OR N.GL_ACCOUNT_ID_O<>T.GL_ACCOUNT_ID_O
 OR N.REPRICE_TERM<>T.REPRICE_TERM
 OR N.REMAIN_TERM<>T.REMAIN_TERM
 OR N.FTP_SCENARION<>T.FTP_SCENARION
 OR N.OVERDUE_FLAG<>T.OVERDUE_FLAG
 OR N.TAB_SOURCE<>T.TAB_SOURCE
 OR N.ACC_INT_DAY_AJUST_A<>T.ACC_INT_DAY_AJUST_A
 OR N.ACC_INT_YEAR_AJUST_A<>T.ACC_INT_YEAR_AJUST_A
 OR N.ACC_INT_QUAR_AJUST_A<>T.ACC_INT_QUAR_AJUST_A
 OR N.ACC_INT_MONTH_AJUST_A<>T.ACC_INT_MONTH_AJUST_A
;

--Step3:
UPDATE dw_sdata.FRS_000_APP_TPDM_RST_FTP P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_173
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ACCOUNT_NUMBER=T_173.ACCOUNT_NUMBER
AND P.AS_OF_DATE=T_173.AS_OF_DATE
AND P.GL_ACCOUNT_ID=T_173.GL_ACCOUNT_ID
;

--Step4:
INSERT  INTO dw_sdata.FRS_000_APP_TPDM_RST_FTP SELECT * FROM T_173;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
