#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.FSS_001_FD_CUSTOMERINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.FSS_001_FD_CUSTOMERINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_190 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.FSS_001_FD_CUSTOMERINFO WHERE 1=0;

--Step2:
INSERT  INTO T_190 (
  CUSTOMERID,
  CUSTOMERMGRCODE,
  ORGANCODE,
  CUSTOMERKIND,
  CERTIFICATEKIND,
  CERTIFICATECODE,
  CUSTOMERNAME,
  CUSTOMERSEX,
  CORPADDR,
  CORPPHONE,
  HANDLEKIND,
  HANDLECODE,
  HANDLEMODE,
  HANDLENAME,
  HANDLESEX,
  CORPZIPCODE,
  CUSTOMERADDR,
  CUSTOMERZIPCODE,
  CUSTOMERPHONE,
  EMAIL,
  LEGALPERSONNAME,
  ACCTSTATE,
  ELISORDOCCODE,
  PASSWORDTRADEFLAG,
  RECENTCHANGEDATE,
  BATCHSERIAL,
  PUBLISHNO,
  PASSWORDFLAG,
  IDPASSWORD,
  AUTOAGENTFLAG,
  MODIFYDATE,
  MODIFYORGAN,
  MODIFYOPER,
  LEGALPERSONSEX,
  LEGALPERSONKIND,
  LEGALPERSONCODE,
  CUSTOMERMOBILE,
  CUSTOMERBP,
  CUSTOMEREDU,
  RECORDDATE,
  FAX,
  POSTBILLFLAG_OLD,
  NOTEFLAG,
  CUSTOMEROPEREVA,
  CUSTOMEREVA,
  CUSTOMERMOBILE2,
  QUEPASSWORD,
  POSTBILLFLAG,
  NETTRADEFLAG,
  CERTBEGINDATE,
  CERTENDDATE,
  NATIONALITY,
  PROFESSION,
  POSTTIMES,
  HANDLEPHONE,
  HANDLEMOBILE,
  HANDLEKIND2,
  HANDLECODE2,
  HANDLENAME2,
  HANDLEPHONE2,
  HANDLEMOBILE2,
  HANDLECERTBEGINDATE,
  HANDLECERTENDDATE,
  HANDLECERTBEGINDATE2,
  HANDLECERTENDDATE2,
  SCOPEOFBUSINESS,
  ORGANIZATIONCODE,
  TAXREGNUMBER,
  STOCKHOLDER,
  MODIFYMGRDATE,
  MODIFYRISKDATE,
  ECIFCUSTOMERNO,
  FLAG,
  CUSTOMERTYPE,
  CUSTOMERLEVEL,
  CARTYPE,
  CHNLNO,
  BRANCHEVAFLAG,
  PRIVBANKINGCLIENTSFLAG,
  HIGHNETWORTHCLIENTSFLAG,
  RISKSCORE,
  RISKCHNLNO,
  start_dt,
  end_dt)
SELECT
  N.CUSTOMERID,
  N.CUSTOMERMGRCODE,
  N.ORGANCODE,
  N.CUSTOMERKIND,
  N.CERTIFICATEKIND,
  N.CERTIFICATECODE,
  N.CUSTOMERNAME,
  N.CUSTOMERSEX,
  N.CORPADDR,
  N.CORPPHONE,
  N.HANDLEKIND,
  N.HANDLECODE,
  N.HANDLEMODE,
  N.HANDLENAME,
  N.HANDLESEX,
  N.CORPZIPCODE,
  N.CUSTOMERADDR,
  N.CUSTOMERZIPCODE,
  N.CUSTOMERPHONE,
  N.EMAIL,
  N.LEGALPERSONNAME,
  N.ACCTSTATE,
  N.ELISORDOCCODE,
  N.PASSWORDTRADEFLAG,
  N.RECENTCHANGEDATE,
  N.BATCHSERIAL,
  N.PUBLISHNO,
  N.PASSWORDFLAG,
  N.IDPASSWORD,
  N.AUTOAGENTFLAG,
  N.MODIFYDATE,
  N.MODIFYORGAN,
  N.MODIFYOPER,
  N.LEGALPERSONSEX,
  N.LEGALPERSONKIND,
  N.LEGALPERSONCODE,
  N.CUSTOMERMOBILE,
  N.CUSTOMERBP,
  N.CUSTOMEREDU,
  N.RECORDDATE,
  N.FAX,
  N.POSTBILLFLAG_OLD,
  N.NOTEFLAG,
  N.CUSTOMEROPEREVA,
  N.CUSTOMEREVA,
  N.CUSTOMERMOBILE2,
  N.QUEPASSWORD,
  N.POSTBILLFLAG,
  N.NETTRADEFLAG,
  N.CERTBEGINDATE,
  N.CERTENDDATE,
  N.NATIONALITY,
  N.PROFESSION,
  N.POSTTIMES,
  N.HANDLEPHONE,
  N.HANDLEMOBILE,
  N.HANDLEKIND2,
  N.HANDLECODE2,
  N.HANDLENAME2,
  N.HANDLEPHONE2,
  N.HANDLEMOBILE2,
  N.HANDLECERTBEGINDATE,
  N.HANDLECERTENDDATE,
  N.HANDLECERTBEGINDATE2,
  N.HANDLECERTENDDATE2,
  N.SCOPEOFBUSINESS,
  N.ORGANIZATIONCODE,
  N.TAXREGNUMBER,
  N.STOCKHOLDER,
  N.MODIFYMGRDATE,
  N.MODIFYRISKDATE,
  N.ECIFCUSTOMERNO,
  N.FLAG,
  N.CUSTOMERTYPE,
  N.CUSTOMERLEVEL,
  N.CARTYPE,
  N.CHNLNO,
  N.BRANCHEVAFLAG,
  N.PRIVBANKINGCLIENTSFLAG,
  N.HIGHNETWORTHCLIENTSFLAG,
  N.RISKSCORE,
  N.RISKCHNLNO,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(CUSTOMERID, '' ) AS CUSTOMERID ,
  COALESCE(CUSTOMERMGRCODE, '' ) AS CUSTOMERMGRCODE ,
  COALESCE(ORGANCODE, '' ) AS ORGANCODE ,
  COALESCE(CUSTOMERKIND, '' ) AS CUSTOMERKIND ,
  COALESCE(CERTIFICATEKIND, '' ) AS CERTIFICATEKIND ,
  COALESCE(CERTIFICATECODE, '' ) AS CERTIFICATECODE ,
  COALESCE(CUSTOMERNAME, '' ) AS CUSTOMERNAME ,
  COALESCE(CUSTOMERSEX, '' ) AS CUSTOMERSEX ,
  COALESCE(CORPADDR, '' ) AS CORPADDR ,
  COALESCE(CORPPHONE, '' ) AS CORPPHONE ,
  COALESCE(HANDLEKIND, '' ) AS HANDLEKIND ,
  COALESCE(HANDLECODE, '' ) AS HANDLECODE ,
  COALESCE(HANDLEMODE, '' ) AS HANDLEMODE ,
  COALESCE(HANDLENAME, '' ) AS HANDLENAME ,
  COALESCE(HANDLESEX, '' ) AS HANDLESEX ,
  COALESCE(CORPZIPCODE, '' ) AS CORPZIPCODE ,
  COALESCE(CUSTOMERADDR, '' ) AS CUSTOMERADDR ,
  COALESCE(CUSTOMERZIPCODE, '' ) AS CUSTOMERZIPCODE ,
  COALESCE(CUSTOMERPHONE, '' ) AS CUSTOMERPHONE ,
  COALESCE(EMAIL, '' ) AS EMAIL ,
  COALESCE(LEGALPERSONNAME, '' ) AS LEGALPERSONNAME ,
  COALESCE(ACCTSTATE, '' ) AS ACCTSTATE ,
  COALESCE(ELISORDOCCODE, '' ) AS ELISORDOCCODE ,
  COALESCE(PASSWORDTRADEFLAG, '' ) AS PASSWORDTRADEFLAG ,
  COALESCE(RECENTCHANGEDATE, '' ) AS RECENTCHANGEDATE ,
  COALESCE(BATCHSERIAL, '' ) AS BATCHSERIAL ,
  COALESCE(PUBLISHNO, '' ) AS PUBLISHNO ,
  COALESCE(PASSWORDFLAG, '' ) AS PASSWORDFLAG ,
  COALESCE(IDPASSWORD, '' ) AS IDPASSWORD ,
  COALESCE(AUTOAGENTFLAG, '' ) AS AUTOAGENTFLAG ,
  COALESCE(MODIFYDATE, '' ) AS MODIFYDATE ,
  COALESCE(MODIFYORGAN, '' ) AS MODIFYORGAN ,
  COALESCE(MODIFYOPER, '' ) AS MODIFYOPER ,
  COALESCE(LEGALPERSONSEX, '' ) AS LEGALPERSONSEX ,
  COALESCE(LEGALPERSONKIND, '' ) AS LEGALPERSONKIND ,
  COALESCE(LEGALPERSONCODE, '' ) AS LEGALPERSONCODE ,
  COALESCE(CUSTOMERMOBILE, '' ) AS CUSTOMERMOBILE ,
  COALESCE(CUSTOMERBP, '' ) AS CUSTOMERBP ,
  COALESCE(CUSTOMEREDU, '' ) AS CUSTOMEREDU ,
  COALESCE(RECORDDATE, '' ) AS RECORDDATE ,
  COALESCE(FAX, '' ) AS FAX ,
  COALESCE(POSTBILLFLAG_OLD, '' ) AS POSTBILLFLAG_OLD ,
  COALESCE(NOTEFLAG, '' ) AS NOTEFLAG ,
  COALESCE(CUSTOMEROPEREVA, '' ) AS CUSTOMEROPEREVA ,
  COALESCE(CUSTOMEREVA, '' ) AS CUSTOMEREVA ,
  COALESCE(CUSTOMERMOBILE2, '' ) AS CUSTOMERMOBILE2 ,
  COALESCE(QUEPASSWORD, '' ) AS QUEPASSWORD ,
  COALESCE(POSTBILLFLAG, '' ) AS POSTBILLFLAG ,
  COALESCE(NETTRADEFLAG, '' ) AS NETTRADEFLAG ,
  COALESCE(CERTBEGINDATE, '' ) AS CERTBEGINDATE ,
  COALESCE(CERTENDDATE, '' ) AS CERTENDDATE ,
  COALESCE(NATIONALITY, '' ) AS NATIONALITY ,
  COALESCE(PROFESSION, '' ) AS PROFESSION ,
  COALESCE(POSTTIMES, '' ) AS POSTTIMES ,
  COALESCE(HANDLEPHONE, '' ) AS HANDLEPHONE ,
  COALESCE(HANDLEMOBILE, '' ) AS HANDLEMOBILE ,
  COALESCE(HANDLEKIND2, '' ) AS HANDLEKIND2 ,
  COALESCE(HANDLECODE2, '' ) AS HANDLECODE2 ,
  COALESCE(HANDLENAME2, '' ) AS HANDLENAME2 ,
  COALESCE(HANDLEPHONE2, '' ) AS HANDLEPHONE2 ,
  COALESCE(HANDLEMOBILE2, '' ) AS HANDLEMOBILE2 ,
  COALESCE(HANDLECERTBEGINDATE, '' ) AS HANDLECERTBEGINDATE ,
  COALESCE(HANDLECERTENDDATE, '' ) AS HANDLECERTENDDATE ,
  COALESCE(HANDLECERTBEGINDATE2, '' ) AS HANDLECERTBEGINDATE2 ,
  COALESCE(HANDLECERTENDDATE2, '' ) AS HANDLECERTENDDATE2 ,
  COALESCE(SCOPEOFBUSINESS, '' ) AS SCOPEOFBUSINESS ,
  COALESCE(ORGANIZATIONCODE, '' ) AS ORGANIZATIONCODE ,
  COALESCE(TAXREGNUMBER, '' ) AS TAXREGNUMBER ,
  COALESCE(STOCKHOLDER, '' ) AS STOCKHOLDER ,
  COALESCE(MODIFYMGRDATE, '' ) AS MODIFYMGRDATE ,
  COALESCE(MODIFYRISKDATE, '' ) AS MODIFYRISKDATE ,
  COALESCE(ECIFCUSTOMERNO, '' ) AS ECIFCUSTOMERNO ,
  COALESCE(FLAG, '' ) AS FLAG ,
  COALESCE(CUSTOMERTYPE, '' ) AS CUSTOMERTYPE ,
  COALESCE(CUSTOMERLEVEL, '' ) AS CUSTOMERLEVEL ,
  COALESCE(CARTYPE, '' ) AS CARTYPE ,
  COALESCE(CHNLNO, '' ) AS CHNLNO ,
  COALESCE(BRANCHEVAFLAG, '' ) AS BRANCHEVAFLAG ,
  COALESCE(PRIVBANKINGCLIENTSFLAG, '' ) AS PRIVBANKINGCLIENTSFLAG ,
  COALESCE(HIGHNETWORTHCLIENTSFLAG, '' ) AS HIGHNETWORTHCLIENTSFLAG ,
  COALESCE(RISKSCORE, '' ) AS RISKSCORE ,
  COALESCE(RISKCHNLNO, '' ) AS RISKCHNLNO 
 FROM  dw_tdata.FSS_001_FD_CUSTOMERINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  CUSTOMERID ,
  CUSTOMERMGRCODE ,
  ORGANCODE ,
  CUSTOMERKIND ,
  CERTIFICATEKIND ,
  CERTIFICATECODE ,
  CUSTOMERNAME ,
  CUSTOMERSEX ,
  CORPADDR ,
  CORPPHONE ,
  HANDLEKIND ,
  HANDLECODE ,
  HANDLEMODE ,
  HANDLENAME ,
  HANDLESEX ,
  CORPZIPCODE ,
  CUSTOMERADDR ,
  CUSTOMERZIPCODE ,
  CUSTOMERPHONE ,
  EMAIL ,
  LEGALPERSONNAME ,
  ACCTSTATE ,
  ELISORDOCCODE ,
  PASSWORDTRADEFLAG ,
  RECENTCHANGEDATE ,
  BATCHSERIAL ,
  PUBLISHNO ,
  PASSWORDFLAG ,
  IDPASSWORD ,
  AUTOAGENTFLAG ,
  MODIFYDATE ,
  MODIFYORGAN ,
  MODIFYOPER ,
  LEGALPERSONSEX ,
  LEGALPERSONKIND ,
  LEGALPERSONCODE ,
  CUSTOMERMOBILE ,
  CUSTOMERBP ,
  CUSTOMEREDU ,
  RECORDDATE ,
  FAX ,
  POSTBILLFLAG_OLD ,
  NOTEFLAG ,
  CUSTOMEROPEREVA ,
  CUSTOMEREVA ,
  CUSTOMERMOBILE2 ,
  QUEPASSWORD ,
  POSTBILLFLAG ,
  NETTRADEFLAG ,
  CERTBEGINDATE ,
  CERTENDDATE ,
  NATIONALITY ,
  PROFESSION ,
  POSTTIMES ,
  HANDLEPHONE ,
  HANDLEMOBILE ,
  HANDLEKIND2 ,
  HANDLECODE2 ,
  HANDLENAME2 ,
  HANDLEPHONE2 ,
  HANDLEMOBILE2 ,
  HANDLECERTBEGINDATE ,
  HANDLECERTENDDATE ,
  HANDLECERTBEGINDATE2 ,
  HANDLECERTENDDATE2 ,
  SCOPEOFBUSINESS ,
  ORGANIZATIONCODE ,
  TAXREGNUMBER ,
  STOCKHOLDER ,
  MODIFYMGRDATE ,
  MODIFYRISKDATE ,
  ECIFCUSTOMERNO ,
  FLAG ,
  CUSTOMERTYPE ,
  CUSTOMERLEVEL ,
  CARTYPE ,
  CHNLNO ,
  BRANCHEVAFLAG ,
  PRIVBANKINGCLIENTSFLAG ,
  HIGHNETWORTHCLIENTSFLAG ,
  RISKSCORE ,
  RISKCHNLNO 
 FROM dw_sdata.FSS_001_FD_CUSTOMERINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.CUSTOMERID = T.CUSTOMERID
WHERE
(T.CUSTOMERID IS NULL)
 OR N.CUSTOMERMGRCODE<>T.CUSTOMERMGRCODE
 OR N.ORGANCODE<>T.ORGANCODE
 OR N.CUSTOMERKIND<>T.CUSTOMERKIND
 OR N.CERTIFICATEKIND<>T.CERTIFICATEKIND
 OR N.CERTIFICATECODE<>T.CERTIFICATECODE
 OR N.CUSTOMERNAME<>T.CUSTOMERNAME
 OR N.CUSTOMERSEX<>T.CUSTOMERSEX
 OR N.CORPADDR<>T.CORPADDR
 OR N.CORPPHONE<>T.CORPPHONE
 OR N.HANDLEKIND<>T.HANDLEKIND
 OR N.HANDLECODE<>T.HANDLECODE
 OR N.HANDLEMODE<>T.HANDLEMODE
 OR N.HANDLENAME<>T.HANDLENAME
 OR N.HANDLESEX<>T.HANDLESEX
 OR N.CORPZIPCODE<>T.CORPZIPCODE
 OR N.CUSTOMERADDR<>T.CUSTOMERADDR
 OR N.CUSTOMERZIPCODE<>T.CUSTOMERZIPCODE
 OR N.CUSTOMERPHONE<>T.CUSTOMERPHONE
 OR N.EMAIL<>T.EMAIL
 OR N.LEGALPERSONNAME<>T.LEGALPERSONNAME
 OR N.ACCTSTATE<>T.ACCTSTATE
 OR N.ELISORDOCCODE<>T.ELISORDOCCODE
 OR N.PASSWORDTRADEFLAG<>T.PASSWORDTRADEFLAG
 OR N.RECENTCHANGEDATE<>T.RECENTCHANGEDATE
 OR N.BATCHSERIAL<>T.BATCHSERIAL
 OR N.PUBLISHNO<>T.PUBLISHNO
 OR N.PASSWORDFLAG<>T.PASSWORDFLAG
 OR N.IDPASSWORD<>T.IDPASSWORD
 OR N.AUTOAGENTFLAG<>T.AUTOAGENTFLAG
 OR N.MODIFYDATE<>T.MODIFYDATE
 OR N.MODIFYORGAN<>T.MODIFYORGAN
 OR N.MODIFYOPER<>T.MODIFYOPER
 OR N.LEGALPERSONSEX<>T.LEGALPERSONSEX
 OR N.LEGALPERSONKIND<>T.LEGALPERSONKIND
 OR N.LEGALPERSONCODE<>T.LEGALPERSONCODE
 OR N.CUSTOMERMOBILE<>T.CUSTOMERMOBILE
 OR N.CUSTOMERBP<>T.CUSTOMERBP
 OR N.CUSTOMEREDU<>T.CUSTOMEREDU
 OR N.RECORDDATE<>T.RECORDDATE
 OR N.FAX<>T.FAX
 OR N.POSTBILLFLAG_OLD<>T.POSTBILLFLAG_OLD
 OR N.NOTEFLAG<>T.NOTEFLAG
 OR N.CUSTOMEROPEREVA<>T.CUSTOMEROPEREVA
 OR N.CUSTOMEREVA<>T.CUSTOMEREVA
 OR N.CUSTOMERMOBILE2<>T.CUSTOMERMOBILE2
 OR N.QUEPASSWORD<>T.QUEPASSWORD
 OR N.POSTBILLFLAG<>T.POSTBILLFLAG
 OR N.NETTRADEFLAG<>T.NETTRADEFLAG
 OR N.CERTBEGINDATE<>T.CERTBEGINDATE
 OR N.CERTENDDATE<>T.CERTENDDATE
 OR N.NATIONALITY<>T.NATIONALITY
 OR N.PROFESSION<>T.PROFESSION
 OR N.POSTTIMES<>T.POSTTIMES
 OR N.HANDLEPHONE<>T.HANDLEPHONE
 OR N.HANDLEMOBILE<>T.HANDLEMOBILE
 OR N.HANDLEKIND2<>T.HANDLEKIND2
 OR N.HANDLECODE2<>T.HANDLECODE2
 OR N.HANDLENAME2<>T.HANDLENAME2
 OR N.HANDLEPHONE2<>T.HANDLEPHONE2
 OR N.HANDLEMOBILE2<>T.HANDLEMOBILE2
 OR N.HANDLECERTBEGINDATE<>T.HANDLECERTBEGINDATE
 OR N.HANDLECERTENDDATE<>T.HANDLECERTENDDATE
 OR N.HANDLECERTBEGINDATE2<>T.HANDLECERTBEGINDATE2
 OR N.HANDLECERTENDDATE2<>T.HANDLECERTENDDATE2
 OR N.SCOPEOFBUSINESS<>T.SCOPEOFBUSINESS
 OR N.ORGANIZATIONCODE<>T.ORGANIZATIONCODE
 OR N.TAXREGNUMBER<>T.TAXREGNUMBER
 OR N.STOCKHOLDER<>T.STOCKHOLDER
 OR N.MODIFYMGRDATE<>T.MODIFYMGRDATE
 OR N.MODIFYRISKDATE<>T.MODIFYRISKDATE
 OR N.ECIFCUSTOMERNO<>T.ECIFCUSTOMERNO
 OR N.FLAG<>T.FLAG
 OR N.CUSTOMERTYPE<>T.CUSTOMERTYPE
 OR N.CUSTOMERLEVEL<>T.CUSTOMERLEVEL
 OR N.CARTYPE<>T.CARTYPE
 OR N.CHNLNO<>T.CHNLNO
 OR N.BRANCHEVAFLAG<>T.BRANCHEVAFLAG
 OR N.PRIVBANKINGCLIENTSFLAG<>T.PRIVBANKINGCLIENTSFLAG
 OR N.HIGHNETWORTHCLIENTSFLAG<>T.HIGHNETWORTHCLIENTSFLAG
 OR N.RISKSCORE<>T.RISKSCORE
 OR N.RISKCHNLNO<>T.RISKCHNLNO
;

--Step3:
UPDATE dw_sdata.FSS_001_FD_CUSTOMERINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_190
WHERE P.End_Dt=DATE('2100-12-31')
AND P.CUSTOMERID=T_190.CUSTOMERID
;

--Step4:
INSERT  INTO dw_sdata.FSS_001_FD_CUSTOMERINFO SELECT * FROM T_190;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
