#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

DELETE FROM dw_sdata.IBS_001_T_PUB_JNL_COM WHERE etl_dt=DATE('${TX_DATE_YYYYMMDD}');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
INSERT  INTO dw_sdata.IBS_001_T_PUB_JNL_COM(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  TRAN_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CLT_SEQNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SERINO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  STAT ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TOTAL_JNL ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_NO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SUB_CODE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_INST ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  OP_INST1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  OP_INST2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  REMIT_INST ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CHNL_NO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  EXT_INST ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PCODE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TLR_NO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AUTH_TLR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  HOST_SEQNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_TIME ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BGN_INT_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  OLD_TRAN_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  OLD_CLT_SEQNO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  OLD_BGN_INT_DATE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  TRAN_ABBR ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  FLAG1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  FLAG2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  EX_FLAG1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  EX_FLAG2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CSTM_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CSTM_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  INST_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  INST_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT_CODE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT_FLAG ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC3 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC4 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC5 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC6 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC7 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC8 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE3 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE4 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE5 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE6 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE7 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CURR_TYPE8 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT3 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT4 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT5 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT6 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT7 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  AMT8 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT3 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT4 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT5 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT6 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT7 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CORR_AMT8 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SUMM_NO ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SUMM ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SVT_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  SVT_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ONEBK_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ONEBK_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ONEBK_SERNO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ONEBK_SERNO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BUSI_TYPE ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BUSI_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  BUSI_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC_NAME1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  ACC_NAME2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CERT_TYPE1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CERT_TYPE2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CERT_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  CERT_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PAPER_TYPE1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PAPER_TYPE2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PAPER_NO1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  PAPER_NO2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  REMARK1 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  REMARK2 ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  RESERVED ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  etl_dt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
SELECT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  COALESCE(TRAN_DATE, 0 ) AS TRAN_DATE ,
  COALESCE(CLT_SEQNO, '' ) AS CLT_SEQNO ,
  COALESCE(SERINO, 0 ) AS SERINO ,
  COALESCE(STAT, '' ) AS STAT ,
  COALESCE(TOTAL_JNL, 0 ) AS TOTAL_JNL ,
  COALESCE(TRAN_NO, '' ) AS TRAN_NO ,
  COALESCE(SUB_CODE, '' ) AS SUB_CODE ,
  COALESCE(TRAN_INST, '' ) AS TRAN_INST ,
  COALESCE(OP_INST1, '' ) AS OP_INST1 ,
  COALESCE(OP_INST2, '' ) AS OP_INST2 ,
  COALESCE(REMIT_INST, '' ) AS REMIT_INST ,
  COALESCE(CHNL_NO, '' ) AS CHNL_NO ,
  COALESCE(EXT_INST, '' ) AS EXT_INST ,
  COALESCE(PCODE, '' ) AS PCODE ,
  COALESCE(TLR_NO, '' ) AS TLR_NO ,
  COALESCE(AUTH_TLR, '' ) AS AUTH_TLR ,
  COALESCE(HOST_SEQNO, 0 ) AS HOST_SEQNO ,
  COALESCE(TRAN_TIME, '' ) AS TRAN_TIME ,
  COALESCE(BGN_INT_DATE, 0 ) AS BGN_INT_DATE ,
  COALESCE(OLD_TRAN_DATE, 0 ) AS OLD_TRAN_DATE ,
  COALESCE(OLD_CLT_SEQNO, '' ) AS OLD_CLT_SEQNO ,
  COALESCE(OLD_BGN_INT_DATE, 0 ) AS OLD_BGN_INT_DATE ,
  COALESCE(TRAN_ABBR, '' ) AS TRAN_ABBR ,
  COALESCE(FLAG1, '' ) AS FLAG1 ,
  COALESCE(FLAG2, '' ) AS FLAG2 ,
  COALESCE(EX_FLAG1, '' ) AS EX_FLAG1 ,
  COALESCE(EX_FLAG2, '' ) AS EX_FLAG2 ,
  COALESCE(CSTM_NO1, '' ) AS CSTM_NO1 ,
  COALESCE(CSTM_NO2, '' ) AS CSTM_NO2 ,
  COALESCE(INST_NO1, '' ) AS INST_NO1 ,
  COALESCE(INST_NO2, '' ) AS INST_NO2 ,
  COALESCE(AMT_CODE, '' ) AS AMT_CODE ,
  COALESCE(AMT_FLAG, '' ) AS AMT_FLAG ,
  COALESCE(ACC1, '' ) AS ACC1 ,
  COALESCE(ACC2, '' ) AS ACC2 ,
  COALESCE(ACC3, '' ) AS ACC3 ,
  COALESCE(ACC4, '' ) AS ACC4 ,
  COALESCE(ACC5, '' ) AS ACC5 ,
  COALESCE(ACC6, '' ) AS ACC6 ,
  COALESCE(ACC7, '' ) AS ACC7 ,
  COALESCE(ACC8, '' ) AS ACC8 ,
  COALESCE(CURR_TYPE1, '' ) AS CURR_TYPE1 ,
  COALESCE(CURR_TYPE2, '' ) AS CURR_TYPE2 ,
  COALESCE(CURR_TYPE3, '' ) AS CURR_TYPE3 ,
  COALESCE(CURR_TYPE4, '' ) AS CURR_TYPE4 ,
  COALESCE(CURR_TYPE5, '' ) AS CURR_TYPE5 ,
  COALESCE(CURR_TYPE6, '' ) AS CURR_TYPE6 ,
  COALESCE(CURR_TYPE7, '' ) AS CURR_TYPE7 ,
  COALESCE(CURR_TYPE8, '' ) AS CURR_TYPE8 ,
  COALESCE(AMT1, 0 ) AS AMT1 ,
  COALESCE(AMT2, 0 ) AS AMT2 ,
  COALESCE(AMT3, 0 ) AS AMT3 ,
  COALESCE(AMT4, 0 ) AS AMT4 ,
  COALESCE(AMT5, 0 ) AS AMT5 ,
  COALESCE(AMT6, 0 ) AS AMT6 ,
  COALESCE(AMT7, 0 ) AS AMT7 ,
  COALESCE(AMT8, 0 ) AS AMT8 ,
  COALESCE(CORR_AMT1, 0 ) AS CORR_AMT1 ,
  COALESCE(CORR_AMT2, 0 ) AS CORR_AMT2 ,
  COALESCE(CORR_AMT3, 0 ) AS CORR_AMT3 ,
  COALESCE(CORR_AMT4, 0 ) AS CORR_AMT4 ,
  COALESCE(CORR_AMT5, 0 ) AS CORR_AMT5 ,
  COALESCE(CORR_AMT6, 0 ) AS CORR_AMT6 ,
  COALESCE(CORR_AMT7, 0 ) AS CORR_AMT7 ,
  COALESCE(CORR_AMT8, 0 ) AS CORR_AMT8 ,
  COALESCE(SUMM_NO, 0 ) AS SUMM_NO ,
  COALESCE(SUMM, '' ) AS SUMM ,
  COALESCE(SVT_NO1, '' ) AS SVT_NO1 ,
  COALESCE(SVT_NO2, '' ) AS SVT_NO2 ,
  COALESCE(ONEBK_NO1, '' ) AS ONEBK_NO1 ,
  COALESCE(ONEBK_NO2, '' ) AS ONEBK_NO2 ,
  COALESCE(ONEBK_SERNO1, 0 ) AS ONEBK_SERNO1 ,
  COALESCE(ONEBK_SERNO2, 0 ) AS ONEBK_SERNO2 ,
  COALESCE(BUSI_TYPE, '' ) AS BUSI_TYPE ,
  COALESCE(BUSI_NO1, '' ) AS BUSI_NO1 ,
  COALESCE(BUSI_NO2, '' ) AS BUSI_NO2 ,
  COALESCE(ACC_NAME1, '' ) AS ACC_NAME1 ,
  COALESCE(ACC_NAME2, '' ) AS ACC_NAME2 ,
  COALESCE(CERT_TYPE1, '' ) AS CERT_TYPE1 ,
  COALESCE(CERT_TYPE2, '' ) AS CERT_TYPE2 ,
  COALESCE(CERT_NO1, '' ) AS CERT_NO1 ,
  COALESCE(CERT_NO2, '' ) AS CERT_NO2 ,
  COALESCE(PAPER_TYPE1, '' ) AS PAPER_TYPE1 ,
  COALESCE(PAPER_TYPE2, '' ) AS PAPER_TYPE2 ,
  COALESCE(PAPER_NO1, '' ) AS PAPER_NO1 ,
  COALESCE(PAPER_NO2, '' ) AS PAPER_NO2 ,
  COALESCE(REMARK1, '' ) AS REMARK1 ,
  COALESCE(REMARK2, '' ) AS REMARK2 ,
  COALESCE(RESERVED, '' ) AS RESERVED ,
  DATE('${TX_DATE_YYYYMMDD}')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
FROM  dw_tdata.IBS_001_T_PUB_JNL_COM_${TX_DATE_YYYYMMDD}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
COMMIT;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
