#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ISS_001_IM_ICINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ISS_001_IM_ICINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_239 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ISS_001_IM_ICINFO WHERE 1=0;

--Step2:
INSERT  INTO T_239 (
  ICNO,
  TXNSERIALNO,
  AMENDTIMES,
  ICTYPE,
  ISAGENTIC,
  AGENTBKNO,
  AGENTBKSWFCODE,
  AGENTBKNAMEADDR,
  AGENTICNO,
  DRAFTCURSIGN,
  DRAFTAMT,
  PAYTERMS,
  PAYTDAYS,
  TENORTYPE,
  USTARTDATE,
  MATURITYDATE,
  DOCMAILDATE,
  DOCARRIVALDATE,
  DELAYPAYINTRATE,
  REMITBKSCHG,
  REMITBKSCHGFLAG,
  HSCODE,
  COMMODITY,
  BILLNO,
  BILLTYPE,
  ADVICEDOCTYPE,
  INVOICENO,
  DRAWERNO,
  DRAWERNAMEADDR,
  DRAWEENO,
  DRAWEENAMEADDR,
  CONTRACTNO,
  CONTRACTAMT,
  REMITBKNO,
  REMITBKSWFCODE,
  REMITBKNAMEADDR,
  OCNO,
  ACKFLAG,
  FORMFLAG,
  TRANSMITBKNO,
  TRANSMITBKSWFCODE,
  TRANSMITBKNAMEADDR,
  TRANSMITBKREFNO,
  TRANSMITBKACNO,
  TRANSMITBKACBKNAME,
  TRANSMITFEECURSIGN,
  TRANSMITFEEAMT,
  PRESENTBKNO,
  PRESENTBKSWFCODE,
  PRESENTBKNAMEADDR,
  TRANSMITORDERBY,
  OURACBKNO,
  OURACBKSWFCODE,
  OURACBKNAMEADDR,
  OURACNO,
  COUNTRYCODE,
  FIRSTABDATE,
  SECONDABDATE,
  PAYMENTDATE,
  ACCEPTANCEDATE,
  ISCLOSE,
  AMENDDATE,
  ISACCEPT,
  ACCEPTAMT,
  ISPAYMENT,
  PAYMENTAMT,
  ISREJECTPAY,
  REJECTPAYAMT,
  SENDBKNO,
  SENDBKSWFCODE,
  SENDBKNAMEADDR,
  DRAFTDAYSDESCR,
  DRAWEECNNAME,
  REJECTEDDATE,
  ACCEPTEDDATE,
  PAYEDDATE,
  CHARGEUNDERTAKER,
  BLNO,
  BLDATE,
  INSTEADOFPAYMENT,
  PAYMENTTIMES,
  ISAGENTSWIFT,
  AGENTSWIFT,
  DRAWERNAME,
  OPPPARTYCLASS,
  INOUTFLAG,
  INVOICEDATE,
  BILLDATE,
  MAILNO,
  DRAFTNO,
  ISDF,
  start_dt,
  end_dt)
SELECT
  N.ICNO,
  N.TXNSERIALNO,
  N.AMENDTIMES,
  N.ICTYPE,
  N.ISAGENTIC,
  N.AGENTBKNO,
  N.AGENTBKSWFCODE,
  N.AGENTBKNAMEADDR,
  N.AGENTICNO,
  N.DRAFTCURSIGN,
  N.DRAFTAMT,
  N.PAYTERMS,
  N.PAYTDAYS,
  N.TENORTYPE,
  N.USTARTDATE,
  N.MATURITYDATE,
  N.DOCMAILDATE,
  N.DOCARRIVALDATE,
  N.DELAYPAYINTRATE,
  N.REMITBKSCHG,
  N.REMITBKSCHGFLAG,
  N.HSCODE,
  N.COMMODITY,
  N.BILLNO,
  N.BILLTYPE,
  N.ADVICEDOCTYPE,
  N.INVOICENO,
  N.DRAWERNO,
  N.DRAWERNAMEADDR,
  N.DRAWEENO,
  N.DRAWEENAMEADDR,
  N.CONTRACTNO,
  N.CONTRACTAMT,
  N.REMITBKNO,
  N.REMITBKSWFCODE,
  N.REMITBKNAMEADDR,
  N.OCNO,
  N.ACKFLAG,
  N.FORMFLAG,
  N.TRANSMITBKNO,
  N.TRANSMITBKSWFCODE,
  N.TRANSMITBKNAMEADDR,
  N.TRANSMITBKREFNO,
  N.TRANSMITBKACNO,
  N.TRANSMITBKACBKNAME,
  N.TRANSMITFEECURSIGN,
  N.TRANSMITFEEAMT,
  N.PRESENTBKNO,
  N.PRESENTBKSWFCODE,
  N.PRESENTBKNAMEADDR,
  N.TRANSMITORDERBY,
  N.OURACBKNO,
  N.OURACBKSWFCODE,
  N.OURACBKNAMEADDR,
  N.OURACNO,
  N.COUNTRYCODE,
  N.FIRSTABDATE,
  N.SECONDABDATE,
  N.PAYMENTDATE,
  N.ACCEPTANCEDATE,
  N.ISCLOSE,
  N.AMENDDATE,
  N.ISACCEPT,
  N.ACCEPTAMT,
  N.ISPAYMENT,
  N.PAYMENTAMT,
  N.ISREJECTPAY,
  N.REJECTPAYAMT,
  N.SENDBKNO,
  N.SENDBKSWFCODE,
  N.SENDBKNAMEADDR,
  N.DRAFTDAYSDESCR,
  N.DRAWEECNNAME,
  N.REJECTEDDATE,
  N.ACCEPTEDDATE,
  N.PAYEDDATE,
  N.CHARGEUNDERTAKER,
  N.BLNO,
  N.BLDATE,
  N.INSTEADOFPAYMENT,
  N.PAYMENTTIMES,
  N.ISAGENTSWIFT,
  N.AGENTSWIFT,
  N.DRAWERNAME,
  N.OPPPARTYCLASS,
  N.INOUTFLAG,
  N.INVOICEDATE,
  N.BILLDATE,
  N.MAILNO,
  N.DRAFTNO,
  N.ISDF,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ICNO, '' ) AS ICNO ,
  COALESCE(TXNSERIALNO, '' ) AS TXNSERIALNO ,
  COALESCE(AMENDTIMES, 0 ) AS AMENDTIMES ,
  COALESCE(ICTYPE, '' ) AS ICTYPE ,
  COALESCE(ISAGENTIC, '' ) AS ISAGENTIC ,
  COALESCE(AGENTBKNO, '' ) AS AGENTBKNO ,
  COALESCE(AGENTBKSWFCODE, '' ) AS AGENTBKSWFCODE ,
  COALESCE(AGENTBKNAMEADDR, '' ) AS AGENTBKNAMEADDR ,
  COALESCE(AGENTICNO, '' ) AS AGENTICNO ,
  COALESCE(DRAFTCURSIGN, '' ) AS DRAFTCURSIGN ,
  COALESCE(DRAFTAMT, 0 ) AS DRAFTAMT ,
  COALESCE(PAYTERMS, '' ) AS PAYTERMS ,
  COALESCE(PAYTDAYS, 0 ) AS PAYTDAYS ,
  COALESCE(TENORTYPE, '' ) AS TENORTYPE ,
  COALESCE(USTARTDATE,DATE('4999-12-31') ) AS USTARTDATE ,
  COALESCE(MATURITYDATE,DATE('4999-12-31') ) AS MATURITYDATE ,
  COALESCE(DOCMAILDATE,DATE('4999-12-31') ) AS DOCMAILDATE ,
  COALESCE(DOCARRIVALDATE,DATE('4999-12-31') ) AS DOCARRIVALDATE ,
  COALESCE(DELAYPAYINTRATE, 0 ) AS DELAYPAYINTRATE ,
  COALESCE(REMITBKSCHG, 0 ) AS REMITBKSCHG ,
  COALESCE(REMITBKSCHGFLAG, '' ) AS REMITBKSCHGFLAG ,
  COALESCE(HSCODE, '' ) AS HSCODE ,
  COALESCE(COMMODITY, '' ) AS COMMODITY ,
  COALESCE(BILLNO, '' ) AS BILLNO ,
  COALESCE(BILLTYPE, '' ) AS BILLTYPE ,
  COALESCE(ADVICEDOCTYPE, '' ) AS ADVICEDOCTYPE ,
  COALESCE(INVOICENO, '' ) AS INVOICENO ,
  COALESCE(DRAWERNO, '' ) AS DRAWERNO ,
  COALESCE(DRAWERNAMEADDR, '' ) AS DRAWERNAMEADDR ,
  COALESCE(DRAWEENO, '' ) AS DRAWEENO ,
  COALESCE(DRAWEENAMEADDR, '' ) AS DRAWEENAMEADDR ,
  COALESCE(CONTRACTNO, '' ) AS CONTRACTNO ,
  COALESCE(CONTRACTAMT, 0 ) AS CONTRACTAMT ,
  COALESCE(REMITBKNO, '' ) AS REMITBKNO ,
  COALESCE(REMITBKSWFCODE, '' ) AS REMITBKSWFCODE ,
  COALESCE(REMITBKNAMEADDR, '' ) AS REMITBKNAMEADDR ,
  COALESCE(OCNO, '' ) AS OCNO ,
  COALESCE(ACKFLAG, '' ) AS ACKFLAG ,
  COALESCE(FORMFLAG, '' ) AS FORMFLAG ,
  COALESCE(TRANSMITBKNO, '' ) AS TRANSMITBKNO ,
  COALESCE(TRANSMITBKSWFCODE, '' ) AS TRANSMITBKSWFCODE ,
  COALESCE(TRANSMITBKNAMEADDR, '' ) AS TRANSMITBKNAMEADDR ,
  COALESCE(TRANSMITBKREFNO, '' ) AS TRANSMITBKREFNO ,
  COALESCE(TRANSMITBKACNO, '' ) AS TRANSMITBKACNO ,
  COALESCE(TRANSMITBKACBKNAME, '' ) AS TRANSMITBKACBKNAME ,
  COALESCE(TRANSMITFEECURSIGN, '' ) AS TRANSMITFEECURSIGN ,
  COALESCE(TRANSMITFEEAMT, 0 ) AS TRANSMITFEEAMT ,
  COALESCE(PRESENTBKNO, '' ) AS PRESENTBKNO ,
  COALESCE(PRESENTBKSWFCODE, '' ) AS PRESENTBKSWFCODE ,
  COALESCE(PRESENTBKNAMEADDR, '' ) AS PRESENTBKNAMEADDR ,
  COALESCE(TRANSMITORDERBY, '' ) AS TRANSMITORDERBY ,
  COALESCE(OURACBKNO, '' ) AS OURACBKNO ,
  COALESCE(OURACBKSWFCODE, '' ) AS OURACBKSWFCODE ,
  COALESCE(OURACBKNAMEADDR, '' ) AS OURACBKNAMEADDR ,
  COALESCE(OURACNO, '' ) AS OURACNO ,
  COALESCE(COUNTRYCODE, '' ) AS COUNTRYCODE ,
  COALESCE(FIRSTABDATE,DATE('4999-12-31') ) AS FIRSTABDATE ,
  COALESCE(SECONDABDATE,DATE('4999-12-31') ) AS SECONDABDATE ,
  COALESCE(PAYMENTDATE,DATE('4999-12-31') ) AS PAYMENTDATE ,
  COALESCE(ACCEPTANCEDATE,DATE('4999-12-31') ) AS ACCEPTANCEDATE ,
  COALESCE(ISCLOSE, '' ) AS ISCLOSE ,
  COALESCE(AMENDDATE,DATE('4999-12-31') ) AS AMENDDATE ,
  COALESCE(ISACCEPT, '' ) AS ISACCEPT ,
  COALESCE(ACCEPTAMT, 0 ) AS ACCEPTAMT ,
  COALESCE(ISPAYMENT, '' ) AS ISPAYMENT ,
  COALESCE(PAYMENTAMT, 0 ) AS PAYMENTAMT ,
  COALESCE(ISREJECTPAY, '' ) AS ISREJECTPAY ,
  COALESCE(REJECTPAYAMT, 0 ) AS REJECTPAYAMT ,
  COALESCE(SENDBKNO, '' ) AS SENDBKNO ,
  COALESCE(SENDBKSWFCODE, '' ) AS SENDBKSWFCODE ,
  COALESCE(SENDBKNAMEADDR, '' ) AS SENDBKNAMEADDR ,
  COALESCE(DRAFTDAYSDESCR, '' ) AS DRAFTDAYSDESCR ,
  COALESCE(DRAWEECNNAME, '' ) AS DRAWEECNNAME ,
  COALESCE(REJECTEDDATE,DATE('4999-12-31') ) AS REJECTEDDATE ,
  COALESCE(ACCEPTEDDATE,DATE('4999-12-31') ) AS ACCEPTEDDATE ,
  COALESCE(PAYEDDATE,DATE('4999-12-31') ) AS PAYEDDATE ,
  COALESCE(CHARGEUNDERTAKER, '' ) AS CHARGEUNDERTAKER ,
  COALESCE(BLNO, '' ) AS BLNO ,
  COALESCE(BLDATE,DATE('4999-12-31') ) AS BLDATE ,
  COALESCE(INSTEADOFPAYMENT, '' ) AS INSTEADOFPAYMENT ,
  COALESCE(PAYMENTTIMES, 0 ) AS PAYMENTTIMES ,
  COALESCE(ISAGENTSWIFT, '' ) AS ISAGENTSWIFT ,
  COALESCE(AGENTSWIFT, '' ) AS AGENTSWIFT ,
  COALESCE(DRAWERNAME, '' ) AS DRAWERNAME ,
  COALESCE(OPPPARTYCLASS, '' ) AS OPPPARTYCLASS ,
  COALESCE(INOUTFLAG, '' ) AS INOUTFLAG ,
  COALESCE(INVOICEDATE,DATE('4999-12-31') ) AS INVOICEDATE ,
  COALESCE(BILLDATE,DATE('4999-12-31') ) AS BILLDATE ,
  COALESCE(MAILNO, '' ) AS MAILNO ,
  COALESCE(DRAFTNO, '' ) AS DRAFTNO ,
  COALESCE(ISDF, '' ) AS ISDF 
 FROM  dw_tdata.ISS_001_IM_ICINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ICNO ,
  TXNSERIALNO ,
  AMENDTIMES ,
  ICTYPE ,
  ISAGENTIC ,
  AGENTBKNO ,
  AGENTBKSWFCODE ,
  AGENTBKNAMEADDR ,
  AGENTICNO ,
  DRAFTCURSIGN ,
  DRAFTAMT ,
  PAYTERMS ,
  PAYTDAYS ,
  TENORTYPE ,
  USTARTDATE ,
  MATURITYDATE ,
  DOCMAILDATE ,
  DOCARRIVALDATE ,
  DELAYPAYINTRATE ,
  REMITBKSCHG ,
  REMITBKSCHGFLAG ,
  HSCODE ,
  COMMODITY ,
  BILLNO ,
  BILLTYPE ,
  ADVICEDOCTYPE ,
  INVOICENO ,
  DRAWERNO ,
  DRAWERNAMEADDR ,
  DRAWEENO ,
  DRAWEENAMEADDR ,
  CONTRACTNO ,
  CONTRACTAMT ,
  REMITBKNO ,
  REMITBKSWFCODE ,
  REMITBKNAMEADDR ,
  OCNO ,
  ACKFLAG ,
  FORMFLAG ,
  TRANSMITBKNO ,
  TRANSMITBKSWFCODE ,
  TRANSMITBKNAMEADDR ,
  TRANSMITBKREFNO ,
  TRANSMITBKACNO ,
  TRANSMITBKACBKNAME ,
  TRANSMITFEECURSIGN ,
  TRANSMITFEEAMT ,
  PRESENTBKNO ,
  PRESENTBKSWFCODE ,
  PRESENTBKNAMEADDR ,
  TRANSMITORDERBY ,
  OURACBKNO ,
  OURACBKSWFCODE ,
  OURACBKNAMEADDR ,
  OURACNO ,
  COUNTRYCODE ,
  FIRSTABDATE ,
  SECONDABDATE ,
  PAYMENTDATE ,
  ACCEPTANCEDATE ,
  ISCLOSE ,
  AMENDDATE ,
  ISACCEPT ,
  ACCEPTAMT ,
  ISPAYMENT ,
  PAYMENTAMT ,
  ISREJECTPAY ,
  REJECTPAYAMT ,
  SENDBKNO ,
  SENDBKSWFCODE ,
  SENDBKNAMEADDR ,
  DRAFTDAYSDESCR ,
  DRAWEECNNAME ,
  REJECTEDDATE ,
  ACCEPTEDDATE ,
  PAYEDDATE ,
  CHARGEUNDERTAKER ,
  BLNO ,
  BLDATE ,
  INSTEADOFPAYMENT ,
  PAYMENTTIMES ,
  ISAGENTSWIFT ,
  AGENTSWIFT ,
  DRAWERNAME ,
  OPPPARTYCLASS ,
  INOUTFLAG ,
  INVOICEDATE ,
  BILLDATE ,
  MAILNO ,
  DRAFTNO ,
  ISDF 
 FROM dw_sdata.ISS_001_IM_ICINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ICNO = T.ICNO
WHERE
(T.ICNO IS NULL)
 OR N.TXNSERIALNO<>T.TXNSERIALNO
 OR N.AMENDTIMES<>T.AMENDTIMES
 OR N.ICTYPE<>T.ICTYPE
 OR N.ISAGENTIC<>T.ISAGENTIC
 OR N.AGENTBKNO<>T.AGENTBKNO
 OR N.AGENTBKSWFCODE<>T.AGENTBKSWFCODE
 OR N.AGENTBKNAMEADDR<>T.AGENTBKNAMEADDR
 OR N.AGENTICNO<>T.AGENTICNO
 OR N.DRAFTCURSIGN<>T.DRAFTCURSIGN
 OR N.DRAFTAMT<>T.DRAFTAMT
 OR N.PAYTERMS<>T.PAYTERMS
 OR N.PAYTDAYS<>T.PAYTDAYS
 OR N.TENORTYPE<>T.TENORTYPE
 OR N.USTARTDATE<>T.USTARTDATE
 OR N.MATURITYDATE<>T.MATURITYDATE
 OR N.DOCMAILDATE<>T.DOCMAILDATE
 OR N.DOCARRIVALDATE<>T.DOCARRIVALDATE
 OR N.DELAYPAYINTRATE<>T.DELAYPAYINTRATE
 OR N.REMITBKSCHG<>T.REMITBKSCHG
 OR N.REMITBKSCHGFLAG<>T.REMITBKSCHGFLAG
 OR N.HSCODE<>T.HSCODE
 OR N.COMMODITY<>T.COMMODITY
 OR N.BILLNO<>T.BILLNO
 OR N.BILLTYPE<>T.BILLTYPE
 OR N.ADVICEDOCTYPE<>T.ADVICEDOCTYPE
 OR N.INVOICENO<>T.INVOICENO
 OR N.DRAWERNO<>T.DRAWERNO
 OR N.DRAWERNAMEADDR<>T.DRAWERNAMEADDR
 OR N.DRAWEENO<>T.DRAWEENO
 OR N.DRAWEENAMEADDR<>T.DRAWEENAMEADDR
 OR N.CONTRACTNO<>T.CONTRACTNO
 OR N.CONTRACTAMT<>T.CONTRACTAMT
 OR N.REMITBKNO<>T.REMITBKNO
 OR N.REMITBKSWFCODE<>T.REMITBKSWFCODE
 OR N.REMITBKNAMEADDR<>T.REMITBKNAMEADDR
 OR N.OCNO<>T.OCNO
 OR N.ACKFLAG<>T.ACKFLAG
 OR N.FORMFLAG<>T.FORMFLAG
 OR N.TRANSMITBKNO<>T.TRANSMITBKNO
 OR N.TRANSMITBKSWFCODE<>T.TRANSMITBKSWFCODE
 OR N.TRANSMITBKNAMEADDR<>T.TRANSMITBKNAMEADDR
 OR N.TRANSMITBKREFNO<>T.TRANSMITBKREFNO
 OR N.TRANSMITBKACNO<>T.TRANSMITBKACNO
 OR N.TRANSMITBKACBKNAME<>T.TRANSMITBKACBKNAME
 OR N.TRANSMITFEECURSIGN<>T.TRANSMITFEECURSIGN
 OR N.TRANSMITFEEAMT<>T.TRANSMITFEEAMT
 OR N.PRESENTBKNO<>T.PRESENTBKNO
 OR N.PRESENTBKSWFCODE<>T.PRESENTBKSWFCODE
 OR N.PRESENTBKNAMEADDR<>T.PRESENTBKNAMEADDR
 OR N.TRANSMITORDERBY<>T.TRANSMITORDERBY
 OR N.OURACBKNO<>T.OURACBKNO
 OR N.OURACBKSWFCODE<>T.OURACBKSWFCODE
 OR N.OURACBKNAMEADDR<>T.OURACBKNAMEADDR
 OR N.OURACNO<>T.OURACNO
 OR N.COUNTRYCODE<>T.COUNTRYCODE
 OR N.FIRSTABDATE<>T.FIRSTABDATE
 OR N.SECONDABDATE<>T.SECONDABDATE
 OR N.PAYMENTDATE<>T.PAYMENTDATE
 OR N.ACCEPTANCEDATE<>T.ACCEPTANCEDATE
 OR N.ISCLOSE<>T.ISCLOSE
 OR N.AMENDDATE<>T.AMENDDATE
 OR N.ISACCEPT<>T.ISACCEPT
 OR N.ACCEPTAMT<>T.ACCEPTAMT
 OR N.ISPAYMENT<>T.ISPAYMENT
 OR N.PAYMENTAMT<>T.PAYMENTAMT
 OR N.ISREJECTPAY<>T.ISREJECTPAY
 OR N.REJECTPAYAMT<>T.REJECTPAYAMT
 OR N.SENDBKNO<>T.SENDBKNO
 OR N.SENDBKSWFCODE<>T.SENDBKSWFCODE
 OR N.SENDBKNAMEADDR<>T.SENDBKNAMEADDR
 OR N.DRAFTDAYSDESCR<>T.DRAFTDAYSDESCR
 OR N.DRAWEECNNAME<>T.DRAWEECNNAME
 OR N.REJECTEDDATE<>T.REJECTEDDATE
 OR N.ACCEPTEDDATE<>T.ACCEPTEDDATE
 OR N.PAYEDDATE<>T.PAYEDDATE
 OR N.CHARGEUNDERTAKER<>T.CHARGEUNDERTAKER
 OR N.BLNO<>T.BLNO
 OR N.BLDATE<>T.BLDATE
 OR N.INSTEADOFPAYMENT<>T.INSTEADOFPAYMENT
 OR N.PAYMENTTIMES<>T.PAYMENTTIMES
 OR N.ISAGENTSWIFT<>T.ISAGENTSWIFT
 OR N.AGENTSWIFT<>T.AGENTSWIFT
 OR N.DRAWERNAME<>T.DRAWERNAME
 OR N.OPPPARTYCLASS<>T.OPPPARTYCLASS
 OR N.INOUTFLAG<>T.INOUTFLAG
 OR N.INVOICEDATE<>T.INVOICEDATE
 OR N.BILLDATE<>T.BILLDATE
 OR N.MAILNO<>T.MAILNO
 OR N.DRAFTNO<>T.DRAFTNO
 OR N.ISDF<>T.ISDF
;

--Step3:
UPDATE dw_sdata.ISS_001_IM_ICINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_239
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ICNO=T_239.ICNO
;

--Step4:
INSERT  INTO dw_sdata.ISS_001_IM_ICINFO SELECT * FROM T_239;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
