#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.PCS_005_TB_SUP_ACCOUNT_INFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.PCS_005_TB_SUP_ACCOUNT_INFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_317 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.PCS_005_TB_SUP_ACCOUNT_INFO WHERE 1=0;

--Step2:
INSERT  INTO T_317 (
  PRV_COD,
  OPN_DEP,
  TAL_DEP,
  CUS_NO,
  DUE_NUM,
  DUE_NUM_SUN,
  BRW_NAME,
  CURR_COD,
  NOR_BAL_ZZ,
  BUS_COD,
  PRM_CLS,
  AST_CLS,
  RES_NOR,
  NOR_BAL_01,
  NOR_OTD_01,
  NOR_FLG_01,
  NOR_ITR_01,
  NOR_PNS_ITR_01,
  DVL_BAL_02,
  DVL_OTD_02,
  DVL_FLG_02,
  DVL_ITR_02,
  DVL_PNS_ITR_02,
  IN_NOR_BAL_06,
  IN_NOR_OTD_06,
  IN_NOR_FLG_06,
  IN_NOR_ITR_06,
  IN_NOR_PNS_ITR_06,
  OUT_NOR_BAL_09,
  OUT_NOR_OTD_09,
  OUT_NOR_FLG_09,
  OUT_NOR_ITR_09,
  OUT_NOR_PNS_ITR_09,
  IN_DFT_BAL_07,
  IN_DFT_OTD_07,
  IN_DFT_FLG_07,
  IN_DFT_PNS_ITR_07,
  OUT_DFT_BAL_10,
  OUT_DFT_OTD_10,
  OUT_DFT_FLG_10,
  OUT_DFT_PNS_ITR_10,
  IN_PNS_BAL_08,
  OUT_PNS_BAL_11,
  NOR_ITR_ADJ_BAL_03,
  DVL_ITR_ADJ_BAL_04,
  IN_ACR_ITR_BAL_05,
  OUT_ACR_ITR_BAL_20,
  IPR_PVS_BAL_14,
  IPR_LOS_BAL_15,
  ITR_ICM_BAL_16,
  OFT_PRN_BAL_12,
  OFT_PRN_ITR_12,
  OFT_ITR_BAL_13,
  OFT_ACR_ITR_BAL_24,
  FRE_ICM_BAL_17,
  PNT_ICM_BAL_25,
  PFT_LOS_BAL_23,
  IN_DUT_BAL_22,
  RCV_BAD_DBT_26,
  RCV_BAD_DBT_LOS_27,
  RPS_AST_28,
  RPS_AST_LOS_29,
  RPS_AST_DIM_30,
  RPS_AST_FRE_31,
  RPS_AST_EXP_32,
  PRO_PFT_LOS_33,
  RPS_AST_RCV_34,
  OUT_DUT_BAL_35,
  RMK_BAL_36,
  RMK_BAL_37,
  RMK_BAL_38,
  RMK_BAL_39,
  RMK_BAL_40,
  RMK_BAL_41,
  RMK_BAL_42,
  RMK_BAL_43,
  RMK_BAL_44,
  RMK_BAL_45,
  RMK_BAL_46,
  RMK_BAL_47,
  RMK_BAL_48,
  RMK_BAL_49,
  RMK_BAL_50,
  RMK_BAL_51,
  RMK_BAL_52,
  RMK_BAL_53,
  RMK_BAL_54,
  RMK_BAL_55,
  STOP_ITR_BAL,
  MOVE_SUBD_BAL,
  ART_COST,
  ART_COST_OTD,
  DLY_PRN_PNS_ITR,
  DLY_IN_BAL_PNS_ITR,
  DLY_OUT_BAL_PNS_ITR,
  ACC_CTL,
  RMK1,
  RMK2,
  RMK3,
  BUS_LST_DATE,
  start_dt,
  end_dt)
SELECT
  N.PRV_COD,
  N.OPN_DEP,
  N.TAL_DEP,
  N.CUS_NO,
  N.DUE_NUM,
  N.DUE_NUM_SUN,
  N.BRW_NAME,
  N.CURR_COD,
  N.NOR_BAL_ZZ,
  N.BUS_COD,
  N.PRM_CLS,
  N.AST_CLS,
  N.RES_NOR,
  N.NOR_BAL_01,
  N.NOR_OTD_01,
  N.NOR_FLG_01,
  N.NOR_ITR_01,
  N.NOR_PNS_ITR_01,
  N.DVL_BAL_02,
  N.DVL_OTD_02,
  N.DVL_FLG_02,
  N.DVL_ITR_02,
  N.DVL_PNS_ITR_02,
  N.IN_NOR_BAL_06,
  N.IN_NOR_OTD_06,
  N.IN_NOR_FLG_06,
  N.IN_NOR_ITR_06,
  N.IN_NOR_PNS_ITR_06,
  N.OUT_NOR_BAL_09,
  N.OUT_NOR_OTD_09,
  N.OUT_NOR_FLG_09,
  N.OUT_NOR_ITR_09,
  N.OUT_NOR_PNS_ITR_09,
  N.IN_DFT_BAL_07,
  N.IN_DFT_OTD_07,
  N.IN_DFT_FLG_07,
  N.IN_DFT_PNS_ITR_07,
  N.OUT_DFT_BAL_10,
  N.OUT_DFT_OTD_10,
  N.OUT_DFT_FLG_10,
  N.OUT_DFT_PNS_ITR_10,
  N.IN_PNS_BAL_08,
  N.OUT_PNS_BAL_11,
  N.NOR_ITR_ADJ_BAL_03,
  N.DVL_ITR_ADJ_BAL_04,
  N.IN_ACR_ITR_BAL_05,
  N.OUT_ACR_ITR_BAL_20,
  N.IPR_PVS_BAL_14,
  N.IPR_LOS_BAL_15,
  N.ITR_ICM_BAL_16,
  N.OFT_PRN_BAL_12,
  N.OFT_PRN_ITR_12,
  N.OFT_ITR_BAL_13,
  N.OFT_ACR_ITR_BAL_24,
  N.FRE_ICM_BAL_17,
  N.PNT_ICM_BAL_25,
  N.PFT_LOS_BAL_23,
  N.IN_DUT_BAL_22,
  N.RCV_BAD_DBT_26,
  N.RCV_BAD_DBT_LOS_27,
  N.RPS_AST_28,
  N.RPS_AST_LOS_29,
  N.RPS_AST_DIM_30,
  N.RPS_AST_FRE_31,
  N.RPS_AST_EXP_32,
  N.PRO_PFT_LOS_33,
  N.RPS_AST_RCV_34,
  N.OUT_DUT_BAL_35,
  N.RMK_BAL_36,
  N.RMK_BAL_37,
  N.RMK_BAL_38,
  N.RMK_BAL_39,
  N.RMK_BAL_40,
  N.RMK_BAL_41,
  N.RMK_BAL_42,
  N.RMK_BAL_43,
  N.RMK_BAL_44,
  N.RMK_BAL_45,
  N.RMK_BAL_46,
  N.RMK_BAL_47,
  N.RMK_BAL_48,
  N.RMK_BAL_49,
  N.RMK_BAL_50,
  N.RMK_BAL_51,
  N.RMK_BAL_52,
  N.RMK_BAL_53,
  N.RMK_BAL_54,
  N.RMK_BAL_55,
  N.STOP_ITR_BAL,
  N.MOVE_SUBD_BAL,
  N.ART_COST,
  N.ART_COST_OTD,
  N.DLY_PRN_PNS_ITR,
  N.DLY_IN_BAL_PNS_ITR,
  N.DLY_OUT_BAL_PNS_ITR,
  N.ACC_CTL,
  N.RMK1,
  N.RMK2,
  N.RMK3,
  N.BUS_LST_DATE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PRV_COD, '' ) AS PRV_COD ,
  COALESCE(OPN_DEP, '' ) AS OPN_DEP ,
  COALESCE(TAL_DEP, '' ) AS TAL_DEP ,
  COALESCE(CUS_NO, '' ) AS CUS_NO ,
  COALESCE(DUE_NUM, '' ) AS DUE_NUM ,
  COALESCE(DUE_NUM_SUN, '' ) AS DUE_NUM_SUN ,
  COALESCE(BRW_NAME, '' ) AS BRW_NAME ,
  COALESCE(CURR_COD, '' ) AS CURR_COD ,
  COALESCE(NOR_BAL_ZZ, 0 ) AS NOR_BAL_ZZ ,
  COALESCE(BUS_COD, '' ) AS BUS_COD ,
  COALESCE(PRM_CLS, '' ) AS PRM_CLS ,
  COALESCE(AST_CLS, '' ) AS AST_CLS ,
  COALESCE(RES_NOR, 0 ) AS RES_NOR ,
  COALESCE(NOR_BAL_01, 0 ) AS NOR_BAL_01 ,
  COALESCE(NOR_OTD_01, 0 ) AS NOR_OTD_01 ,
  COALESCE(NOR_FLG_01, '' ) AS NOR_FLG_01 ,
  COALESCE(NOR_ITR_01, 0 ) AS NOR_ITR_01 ,
  COALESCE(NOR_PNS_ITR_01, 0 ) AS NOR_PNS_ITR_01 ,
  COALESCE(DVL_BAL_02, 0 ) AS DVL_BAL_02 ,
  COALESCE(DVL_OTD_02, 0 ) AS DVL_OTD_02 ,
  COALESCE(DVL_FLG_02, '' ) AS DVL_FLG_02 ,
  COALESCE(DVL_ITR_02, 0 ) AS DVL_ITR_02 ,
  COALESCE(DVL_PNS_ITR_02, 0 ) AS DVL_PNS_ITR_02 ,
  COALESCE(IN_NOR_BAL_06, 0 ) AS IN_NOR_BAL_06 ,
  COALESCE(IN_NOR_OTD_06, 0 ) AS IN_NOR_OTD_06 ,
  COALESCE(IN_NOR_FLG_06, '' ) AS IN_NOR_FLG_06 ,
  COALESCE(IN_NOR_ITR_06, 0 ) AS IN_NOR_ITR_06 ,
  COALESCE(IN_NOR_PNS_ITR_06, 0 ) AS IN_NOR_PNS_ITR_06 ,
  COALESCE(OUT_NOR_BAL_09, 0 ) AS OUT_NOR_BAL_09 ,
  COALESCE(OUT_NOR_OTD_09, 0 ) AS OUT_NOR_OTD_09 ,
  COALESCE(OUT_NOR_FLG_09, '' ) AS OUT_NOR_FLG_09 ,
  COALESCE(OUT_NOR_ITR_09, 0 ) AS OUT_NOR_ITR_09 ,
  COALESCE(OUT_NOR_PNS_ITR_09, 0 ) AS OUT_NOR_PNS_ITR_09 ,
  COALESCE(IN_DFT_BAL_07, 0 ) AS IN_DFT_BAL_07 ,
  COALESCE(IN_DFT_OTD_07, 0 ) AS IN_DFT_OTD_07 ,
  COALESCE(IN_DFT_FLG_07, '' ) AS IN_DFT_FLG_07 ,
  COALESCE(IN_DFT_PNS_ITR_07, 0 ) AS IN_DFT_PNS_ITR_07 ,
  COALESCE(OUT_DFT_BAL_10, 0 ) AS OUT_DFT_BAL_10 ,
  COALESCE(OUT_DFT_OTD_10, 0 ) AS OUT_DFT_OTD_10 ,
  COALESCE(OUT_DFT_FLG_10, '' ) AS OUT_DFT_FLG_10 ,
  COALESCE(OUT_DFT_PNS_ITR_10, 0 ) AS OUT_DFT_PNS_ITR_10 ,
  COALESCE(IN_PNS_BAL_08, 0 ) AS IN_PNS_BAL_08 ,
  COALESCE(OUT_PNS_BAL_11, 0 ) AS OUT_PNS_BAL_11 ,
  COALESCE(NOR_ITR_ADJ_BAL_03, 0 ) AS NOR_ITR_ADJ_BAL_03 ,
  COALESCE(DVL_ITR_ADJ_BAL_04, 0 ) AS DVL_ITR_ADJ_BAL_04 ,
  COALESCE(IN_ACR_ITR_BAL_05, 0 ) AS IN_ACR_ITR_BAL_05 ,
  COALESCE(OUT_ACR_ITR_BAL_20, 0 ) AS OUT_ACR_ITR_BAL_20 ,
  COALESCE(IPR_PVS_BAL_14, 0 ) AS IPR_PVS_BAL_14 ,
  COALESCE(IPR_LOS_BAL_15, 0 ) AS IPR_LOS_BAL_15 ,
  COALESCE(ITR_ICM_BAL_16, 0 ) AS ITR_ICM_BAL_16 ,
  COALESCE(OFT_PRN_BAL_12, 0 ) AS OFT_PRN_BAL_12 ,
  COALESCE(OFT_PRN_ITR_12, 0 ) AS OFT_PRN_ITR_12 ,
  COALESCE(OFT_ITR_BAL_13, 0 ) AS OFT_ITR_BAL_13 ,
  COALESCE(OFT_ACR_ITR_BAL_24, 0 ) AS OFT_ACR_ITR_BAL_24 ,
  COALESCE(FRE_ICM_BAL_17, 0 ) AS FRE_ICM_BAL_17 ,
  COALESCE(PNT_ICM_BAL_25, 0 ) AS PNT_ICM_BAL_25 ,
  COALESCE(PFT_LOS_BAL_23, 0 ) AS PFT_LOS_BAL_23 ,
  COALESCE(IN_DUT_BAL_22, 0 ) AS IN_DUT_BAL_22 ,
  COALESCE(RCV_BAD_DBT_26, 0 ) AS RCV_BAD_DBT_26 ,
  COALESCE(RCV_BAD_DBT_LOS_27, 0 ) AS RCV_BAD_DBT_LOS_27 ,
  COALESCE(RPS_AST_28, 0 ) AS RPS_AST_28 ,
  COALESCE(RPS_AST_LOS_29, 0 ) AS RPS_AST_LOS_29 ,
  COALESCE(RPS_AST_DIM_30, 0 ) AS RPS_AST_DIM_30 ,
  COALESCE(RPS_AST_FRE_31, 0 ) AS RPS_AST_FRE_31 ,
  COALESCE(RPS_AST_EXP_32, 0 ) AS RPS_AST_EXP_32 ,
  COALESCE(PRO_PFT_LOS_33, 0 ) AS PRO_PFT_LOS_33 ,
  COALESCE(RPS_AST_RCV_34, 0 ) AS RPS_AST_RCV_34 ,
  COALESCE(OUT_DUT_BAL_35, 0 ) AS OUT_DUT_BAL_35 ,
  COALESCE(RMK_BAL_36, 0 ) AS RMK_BAL_36 ,
  COALESCE(RMK_BAL_37, 0 ) AS RMK_BAL_37 ,
  COALESCE(RMK_BAL_38, 0 ) AS RMK_BAL_38 ,
  COALESCE(RMK_BAL_39, 0 ) AS RMK_BAL_39 ,
  COALESCE(RMK_BAL_40, 0 ) AS RMK_BAL_40 ,
  COALESCE(RMK_BAL_41, 0 ) AS RMK_BAL_41 ,
  COALESCE(RMK_BAL_42, 0 ) AS RMK_BAL_42 ,
  COALESCE(RMK_BAL_43, 0 ) AS RMK_BAL_43 ,
  COALESCE(RMK_BAL_44, 0 ) AS RMK_BAL_44 ,
  COALESCE(RMK_BAL_45, 0 ) AS RMK_BAL_45 ,
  COALESCE(RMK_BAL_46, 0 ) AS RMK_BAL_46 ,
  COALESCE(RMK_BAL_47, 0 ) AS RMK_BAL_47 ,
  COALESCE(RMK_BAL_48, 0 ) AS RMK_BAL_48 ,
  COALESCE(RMK_BAL_49, 0 ) AS RMK_BAL_49 ,
  COALESCE(RMK_BAL_50, 0 ) AS RMK_BAL_50 ,
  COALESCE(RMK_BAL_51, 0 ) AS RMK_BAL_51 ,
  COALESCE(RMK_BAL_52, 0 ) AS RMK_BAL_52 ,
  COALESCE(RMK_BAL_53, 0 ) AS RMK_BAL_53 ,
  COALESCE(RMK_BAL_54, 0 ) AS RMK_BAL_54 ,
  COALESCE(RMK_BAL_55, 0 ) AS RMK_BAL_55 ,
  COALESCE(STOP_ITR_BAL, 0 ) AS STOP_ITR_BAL ,
  COALESCE(MOVE_SUBD_BAL, 0 ) AS MOVE_SUBD_BAL ,
  COALESCE(ART_COST, 0 ) AS ART_COST ,
  COALESCE(ART_COST_OTD, 0 ) AS ART_COST_OTD ,
  COALESCE(DLY_PRN_PNS_ITR, 0 ) AS DLY_PRN_PNS_ITR ,
  COALESCE(DLY_IN_BAL_PNS_ITR, 0 ) AS DLY_IN_BAL_PNS_ITR ,
  COALESCE(DLY_OUT_BAL_PNS_ITR, 0 ) AS DLY_OUT_BAL_PNS_ITR ,
  COALESCE(ACC_CTL, '' ) AS ACC_CTL ,
  COALESCE(RMK1, '' ) AS RMK1 ,
  COALESCE(RMK2, '' ) AS RMK2 ,
  COALESCE(RMK3, '' ) AS RMK3 ,
  COALESCE(BUS_LST_DATE, '' ) AS BUS_LST_DATE 
 FROM  dw_tdata.PCS_005_TB_SUP_ACCOUNT_INFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PRV_COD ,
  OPN_DEP ,
  TAL_DEP ,
  CUS_NO ,
  DUE_NUM ,
  DUE_NUM_SUN ,
  BRW_NAME ,
  CURR_COD ,
  NOR_BAL_ZZ ,
  BUS_COD ,
  PRM_CLS ,
  AST_CLS ,
  RES_NOR ,
  NOR_BAL_01 ,
  NOR_OTD_01 ,
  NOR_FLG_01 ,
  NOR_ITR_01 ,
  NOR_PNS_ITR_01 ,
  DVL_BAL_02 ,
  DVL_OTD_02 ,
  DVL_FLG_02 ,
  DVL_ITR_02 ,
  DVL_PNS_ITR_02 ,
  IN_NOR_BAL_06 ,
  IN_NOR_OTD_06 ,
  IN_NOR_FLG_06 ,
  IN_NOR_ITR_06 ,
  IN_NOR_PNS_ITR_06 ,
  OUT_NOR_BAL_09 ,
  OUT_NOR_OTD_09 ,
  OUT_NOR_FLG_09 ,
  OUT_NOR_ITR_09 ,
  OUT_NOR_PNS_ITR_09 ,
  IN_DFT_BAL_07 ,
  IN_DFT_OTD_07 ,
  IN_DFT_FLG_07 ,
  IN_DFT_PNS_ITR_07 ,
  OUT_DFT_BAL_10 ,
  OUT_DFT_OTD_10 ,
  OUT_DFT_FLG_10 ,
  OUT_DFT_PNS_ITR_10 ,
  IN_PNS_BAL_08 ,
  OUT_PNS_BAL_11 ,
  NOR_ITR_ADJ_BAL_03 ,
  DVL_ITR_ADJ_BAL_04 ,
  IN_ACR_ITR_BAL_05 ,
  OUT_ACR_ITR_BAL_20 ,
  IPR_PVS_BAL_14 ,
  IPR_LOS_BAL_15 ,
  ITR_ICM_BAL_16 ,
  OFT_PRN_BAL_12 ,
  OFT_PRN_ITR_12 ,
  OFT_ITR_BAL_13 ,
  OFT_ACR_ITR_BAL_24 ,
  FRE_ICM_BAL_17 ,
  PNT_ICM_BAL_25 ,
  PFT_LOS_BAL_23 ,
  IN_DUT_BAL_22 ,
  RCV_BAD_DBT_26 ,
  RCV_BAD_DBT_LOS_27 ,
  RPS_AST_28 ,
  RPS_AST_LOS_29 ,
  RPS_AST_DIM_30 ,
  RPS_AST_FRE_31 ,
  RPS_AST_EXP_32 ,
  PRO_PFT_LOS_33 ,
  RPS_AST_RCV_34 ,
  OUT_DUT_BAL_35 ,
  RMK_BAL_36 ,
  RMK_BAL_37 ,
  RMK_BAL_38 ,
  RMK_BAL_39 ,
  RMK_BAL_40 ,
  RMK_BAL_41 ,
  RMK_BAL_42 ,
  RMK_BAL_43 ,
  RMK_BAL_44 ,
  RMK_BAL_45 ,
  RMK_BAL_46 ,
  RMK_BAL_47 ,
  RMK_BAL_48 ,
  RMK_BAL_49 ,
  RMK_BAL_50 ,
  RMK_BAL_51 ,
  RMK_BAL_52 ,
  RMK_BAL_53 ,
  RMK_BAL_54 ,
  RMK_BAL_55 ,
  STOP_ITR_BAL ,
  MOVE_SUBD_BAL ,
  ART_COST ,
  ART_COST_OTD ,
  DLY_PRN_PNS_ITR ,
  DLY_IN_BAL_PNS_ITR ,
  DLY_OUT_BAL_PNS_ITR ,
  ACC_CTL ,
  RMK1 ,
  RMK2 ,
  RMK3 ,
  BUS_LST_DATE 
 FROM dw_sdata.PCS_005_TB_SUP_ACCOUNT_INFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.DUE_NUM = T.DUE_NUM
WHERE
(T.DUE_NUM IS NULL)
 OR N.PRV_COD<>T.PRV_COD
 OR N.OPN_DEP<>T.OPN_DEP
 OR N.TAL_DEP<>T.TAL_DEP
 OR N.CUS_NO<>T.CUS_NO
 OR N.DUE_NUM_SUN<>T.DUE_NUM_SUN
 OR N.BRW_NAME<>T.BRW_NAME
 OR N.CURR_COD<>T.CURR_COD
 OR N.NOR_BAL_ZZ<>T.NOR_BAL_ZZ
 OR N.BUS_COD<>T.BUS_COD
 OR N.PRM_CLS<>T.PRM_CLS
 OR N.AST_CLS<>T.AST_CLS
 OR N.RES_NOR<>T.RES_NOR
 OR N.NOR_BAL_01<>T.NOR_BAL_01
 OR N.NOR_OTD_01<>T.NOR_OTD_01
 OR N.NOR_FLG_01<>T.NOR_FLG_01
 OR N.NOR_ITR_01<>T.NOR_ITR_01
 OR N.NOR_PNS_ITR_01<>T.NOR_PNS_ITR_01
 OR N.DVL_BAL_02<>T.DVL_BAL_02
 OR N.DVL_OTD_02<>T.DVL_OTD_02
 OR N.DVL_FLG_02<>T.DVL_FLG_02
 OR N.DVL_ITR_02<>T.DVL_ITR_02
 OR N.DVL_PNS_ITR_02<>T.DVL_PNS_ITR_02
 OR N.IN_NOR_BAL_06<>T.IN_NOR_BAL_06
 OR N.IN_NOR_OTD_06<>T.IN_NOR_OTD_06
 OR N.IN_NOR_FLG_06<>T.IN_NOR_FLG_06
 OR N.IN_NOR_ITR_06<>T.IN_NOR_ITR_06
 OR N.IN_NOR_PNS_ITR_06<>T.IN_NOR_PNS_ITR_06
 OR N.OUT_NOR_BAL_09<>T.OUT_NOR_BAL_09
 OR N.OUT_NOR_OTD_09<>T.OUT_NOR_OTD_09
 OR N.OUT_NOR_FLG_09<>T.OUT_NOR_FLG_09
 OR N.OUT_NOR_ITR_09<>T.OUT_NOR_ITR_09
 OR N.OUT_NOR_PNS_ITR_09<>T.OUT_NOR_PNS_ITR_09
 OR N.IN_DFT_BAL_07<>T.IN_DFT_BAL_07
 OR N.IN_DFT_OTD_07<>T.IN_DFT_OTD_07
 OR N.IN_DFT_FLG_07<>T.IN_DFT_FLG_07
 OR N.IN_DFT_PNS_ITR_07<>T.IN_DFT_PNS_ITR_07
 OR N.OUT_DFT_BAL_10<>T.OUT_DFT_BAL_10
 OR N.OUT_DFT_OTD_10<>T.OUT_DFT_OTD_10
 OR N.OUT_DFT_FLG_10<>T.OUT_DFT_FLG_10
 OR N.OUT_DFT_PNS_ITR_10<>T.OUT_DFT_PNS_ITR_10
 OR N.IN_PNS_BAL_08<>T.IN_PNS_BAL_08
 OR N.OUT_PNS_BAL_11<>T.OUT_PNS_BAL_11
 OR N.NOR_ITR_ADJ_BAL_03<>T.NOR_ITR_ADJ_BAL_03
 OR N.DVL_ITR_ADJ_BAL_04<>T.DVL_ITR_ADJ_BAL_04
 OR N.IN_ACR_ITR_BAL_05<>T.IN_ACR_ITR_BAL_05
 OR N.OUT_ACR_ITR_BAL_20<>T.OUT_ACR_ITR_BAL_20
 OR N.IPR_PVS_BAL_14<>T.IPR_PVS_BAL_14
 OR N.IPR_LOS_BAL_15<>T.IPR_LOS_BAL_15
 OR N.ITR_ICM_BAL_16<>T.ITR_ICM_BAL_16
 OR N.OFT_PRN_BAL_12<>T.OFT_PRN_BAL_12
 OR N.OFT_PRN_ITR_12<>T.OFT_PRN_ITR_12
 OR N.OFT_ITR_BAL_13<>T.OFT_ITR_BAL_13
 OR N.OFT_ACR_ITR_BAL_24<>T.OFT_ACR_ITR_BAL_24
 OR N.FRE_ICM_BAL_17<>T.FRE_ICM_BAL_17
 OR N.PNT_ICM_BAL_25<>T.PNT_ICM_BAL_25
 OR N.PFT_LOS_BAL_23<>T.PFT_LOS_BAL_23
 OR N.IN_DUT_BAL_22<>T.IN_DUT_BAL_22
 OR N.RCV_BAD_DBT_26<>T.RCV_BAD_DBT_26
 OR N.RCV_BAD_DBT_LOS_27<>T.RCV_BAD_DBT_LOS_27
 OR N.RPS_AST_28<>T.RPS_AST_28
 OR N.RPS_AST_LOS_29<>T.RPS_AST_LOS_29
 OR N.RPS_AST_DIM_30<>T.RPS_AST_DIM_30
 OR N.RPS_AST_FRE_31<>T.RPS_AST_FRE_31
 OR N.RPS_AST_EXP_32<>T.RPS_AST_EXP_32
 OR N.PRO_PFT_LOS_33<>T.PRO_PFT_LOS_33
 OR N.RPS_AST_RCV_34<>T.RPS_AST_RCV_34
 OR N.OUT_DUT_BAL_35<>T.OUT_DUT_BAL_35
 OR N.RMK_BAL_36<>T.RMK_BAL_36
 OR N.RMK_BAL_37<>T.RMK_BAL_37
 OR N.RMK_BAL_38<>T.RMK_BAL_38
 OR N.RMK_BAL_39<>T.RMK_BAL_39
 OR N.RMK_BAL_40<>T.RMK_BAL_40
 OR N.RMK_BAL_41<>T.RMK_BAL_41
 OR N.RMK_BAL_42<>T.RMK_BAL_42
 OR N.RMK_BAL_43<>T.RMK_BAL_43
 OR N.RMK_BAL_44<>T.RMK_BAL_44
 OR N.RMK_BAL_45<>T.RMK_BAL_45
 OR N.RMK_BAL_46<>T.RMK_BAL_46
 OR N.RMK_BAL_47<>T.RMK_BAL_47
 OR N.RMK_BAL_48<>T.RMK_BAL_48
 OR N.RMK_BAL_49<>T.RMK_BAL_49
 OR N.RMK_BAL_50<>T.RMK_BAL_50
 OR N.RMK_BAL_51<>T.RMK_BAL_51
 OR N.RMK_BAL_52<>T.RMK_BAL_52
 OR N.RMK_BAL_53<>T.RMK_BAL_53
 OR N.RMK_BAL_54<>T.RMK_BAL_54
 OR N.RMK_BAL_55<>T.RMK_BAL_55
 OR N.STOP_ITR_BAL<>T.STOP_ITR_BAL
 OR N.MOVE_SUBD_BAL<>T.MOVE_SUBD_BAL
 OR N.ART_COST<>T.ART_COST
 OR N.ART_COST_OTD<>T.ART_COST_OTD
 OR N.DLY_PRN_PNS_ITR<>T.DLY_PRN_PNS_ITR
 OR N.DLY_IN_BAL_PNS_ITR<>T.DLY_IN_BAL_PNS_ITR
 OR N.DLY_OUT_BAL_PNS_ITR<>T.DLY_OUT_BAL_PNS_ITR
 OR N.ACC_CTL<>T.ACC_CTL
 OR N.RMK1<>T.RMK1
 OR N.RMK2<>T.RMK2
 OR N.RMK3<>T.RMK3
 OR N.BUS_LST_DATE<>T.BUS_LST_DATE
;

--Step3:
UPDATE dw_sdata.PCS_005_TB_SUP_ACCOUNT_INFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_317
WHERE P.End_Dt=DATE('2100-12-31')
AND P.DUE_NUM=T_317.DUE_NUM
;

--Step4:
INSERT  INTO dw_sdata.PCS_005_TB_SUP_ACCOUNT_INFO SELECT * FROM T_317;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
