#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.PCS_006_TB_LON_LOAN WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.PCS_006_TB_LON_LOAN SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_336 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.PCS_006_TB_LON_LOAN WHERE 1=0;

--Step2:
INSERT  INTO T_336 (
  LOAN_ID,
  LOAN_CONTRACT_ID,
  CUS_ID,
  LOAN_LEVEL_FOUR_CLASS,
  LOAN_LEVEL_FIVE_CLASS,
  CLOSE_FLAG,
  CURRENCY,
  LOAN_PURPOSE,
  SECURITY_KIND,
  LOAN_LENGTH,
  LOAN_BEGIN_DATE,
  LOAN_END_DATE,
  LOAN_TYPE,
  LOAN_RISKNESS,
  LAW_SUIT_FLAG,
  EXTENSION_FLAG,
  EXTENSION_DATE,
  OVERDUE_RATE,
  ACCOUNT_NAME,
  ACCOUNT_NO,
  REPAY_NAME,
  REPAY_NO,
  IS_CARD_REPAY,
  LOAN_AMOUNT,
  LOAN_CONTRACT_AMOUNT,
  LOAN_BALANCE,
  TOTAL_REPAY_CAPITAL,
  CANCEL_CAPITAL,
  CANCEL_CAPITAL_BALANCE,
  INTEREST_AMOUNT,
  IN_SHEET_INTEREST_BALANCE,
  IN_SHEET_OVERDUE_BALANCE,
  OFF_SHEET_INTEREST_BALANCE,
  CANCEL_IN_SHEET_BALANCE,
  CANCEL_OFF_SHEET_BALANCE,
  CANCEL_INSHEET_INTEREST_BALANC,
  CANCEL_OFFSHEET_INTEREST_BALAN,
  APP_OP_ID,
  IS_GET_PREREPAY_FORFEIT,
  IS_LINE_ROLL_BACK,
  HAND_OVER_FLAG,
  RECORD_FLAG,
  LAW_SUIT_VALIDITY,
  LAW_SUIT_ENFORCE_VALIDITY,
  LOSS_TYPE,
  ADVANCE_FLAG,
  ADVANCE_AMOUNT,
  ADVANCE_BALANCE,
  EXTENSION_CONTRACT_NO,
  ROLL_BACK_AMOUNT,
  OVERDUE_DAYS,
  COM_SECURITY_KIND,
  COUNT_OVERDUE_TERM,
  CURRENT_OVERDUE_TERM,
  MAX_OVERDUE_TERM,
  OVERDUE_AMOUNT,
  OVERDUE_RATE_AMOUNT,
  OVERDUE_TOTAL,
  IS_PAYEE,
  PAYEE_NO,
  PAYEE_NAME,
  IS_LAW_STOP_INTEREST_FLAG,
  IS_STOP_INTEREST_FLAG,
  CLOSE_DATE,
  CANCLE_FLAG,
  CANCLE_DATE,
  ARBITRATE_FLAG,
  OVERDUE_COLLECTION_STATUS,
  REPAY_KIND,
  REPAY_KIND_APPEND_FUNCTION,
  NORMAL_IN_SHEET_INTEREST,
  NORMAL_OFF_SHEET_INTEREST,
  OVERDUE_IN_SHEET_INTEREST,
  OVERDUE_OFF_SHEET_INTEREST,
  DEFAULT_IN_SHEET_INTEREST,
  DEFAULT_OFF_SHEET_INTEREST,
  CANCEL_INTEREST,
  CANCEL_ACCRUED_INTEREST,
  RATE_ACCORD_KIND,
  OVERDUE_REPAY_KIND,
  PROVINCE_NUM,
  OVERDUE_FLOATING_RATIO,
  DIVERT_FLOATING_RATIO,
  VALIDITY_LENGTH,
  CONTRACT_NUMS,
  PAYMENT_WAY,
  NORMAL_PAYMENT_AMOUNT,
  ENTRUST_PAYMENT_AMOUNT,
  SPECIAL_PAYMENT_AMOUNT,
  REPAY_DAY,
  LOAN_RATE,
  PRODUCT_RATE,
  BASE_RATE,
  RATE_PRICE_KIND,
  IS_AUTO_CHG_FA,
  IS_AUTO_CHG_FV,
  FLOATING_VALUE,
  FLOATING_RATIO,
  ALLOW_MAX_OVERDUE_DAY,
  INTEREST_CLEAN_KIND,
  NEW_ADD_AMOUNT,
  CONTINUE_ADD_AMOUNT,
  RECOMPOSE_AMOUNT,
  RATE_ADJUST_KIND,
  IS_DESIGN_LOAN,
  IS_DISCOUNT,
  ADVANCE_REPAY_AMOUNT,
  IS_HOLIDAY_POSTPONE,
  IS_FARMER,
  IS_TOGETHER_BORROWER,
  IS_REASERCH,
  PREPAYMENT_BEGIN_MONTH,
  SUB_LOAN_KIND,
  IS_IN_TOWN,
  IS_FREE_TAX,
  LOAN_PURPOSE_KIND,
  IS_ONLY_ONE_LOAN_PURPOSE,
  IS_CARVE_OUT_LOAN,
  EVERY_MONTH_REPAY_AMOUNT,
  MONTH_PAYMENT_LENGTH,
  BEGIN_REPAY_CAPITAL_TERM,
  COUNT_GRACE_LENGTH,
  LOAN_FORM,
  EXTENSION_NUM,
  RECORDER_USER_ID,
  TRANSACTOR_USER_ID,
  FINAL_APPROVE_USER_ID,
  LOAN_CONTRACT_NO,
  IS_CARD_LOAN,
  INTEREST_CLEAN_CYCLE,
  GROUP_SECURITY_TYPE,
  NEXT_CLEAN_INT_RULE,
  EXCHANG_ERATE,
  DELFLAG,
  CREATE_TIME,
  UPDATE_TIME,
  TRUNC_NO,
  APPLICATION_DATE,
  IS_FIT_FARMER_STAND,
  CHARACTERISTIC_APP_TYPE,
  SELF_FINAL,
  BIZ_CHANNEL_KIND,
  BIZ_CHANNEL_SUB_KIND,
  QUICK_LOAN_FLAG,
  OLD_CLASS_WAY,
  LAST_MANUAL_DATE,
  start_dt,
  end_dt)
SELECT
  N.LOAN_ID,
  N.LOAN_CONTRACT_ID,
  N.CUS_ID,
  N.LOAN_LEVEL_FOUR_CLASS,
  N.LOAN_LEVEL_FIVE_CLASS,
  N.CLOSE_FLAG,
  N.CURRENCY,
  N.LOAN_PURPOSE,
  N.SECURITY_KIND,
  N.LOAN_LENGTH,
  N.LOAN_BEGIN_DATE,
  N.LOAN_END_DATE,
  N.LOAN_TYPE,
  N.LOAN_RISKNESS,
  N.LAW_SUIT_FLAG,
  N.EXTENSION_FLAG,
  N.EXTENSION_DATE,
  N.OVERDUE_RATE,
  N.ACCOUNT_NAME,
  N.ACCOUNT_NO,
  N.REPAY_NAME,
  N.REPAY_NO,
  N.IS_CARD_REPAY,
  N.LOAN_AMOUNT,
  N.LOAN_CONTRACT_AMOUNT,
  N.LOAN_BALANCE,
  N.TOTAL_REPAY_CAPITAL,
  N.CANCEL_CAPITAL,
  N.CANCEL_CAPITAL_BALANCE,
  N.INTEREST_AMOUNT,
  N.IN_SHEET_INTEREST_BALANCE,
  N.IN_SHEET_OVERDUE_BALANCE,
  N.OFF_SHEET_INTEREST_BALANCE,
  N.CANCEL_IN_SHEET_BALANCE,
  N.CANCEL_OFF_SHEET_BALANCE,
  N.CANCEL_INSHEET_INTEREST_BALANC,
  N.CANCEL_OFFSHEET_INTEREST_BALAN,
  N.APP_OP_ID,
  N.IS_GET_PREREPAY_FORFEIT,
  N.IS_LINE_ROLL_BACK,
  N.HAND_OVER_FLAG,
  N.RECORD_FLAG,
  N.LAW_SUIT_VALIDITY,
  N.LAW_SUIT_ENFORCE_VALIDITY,
  N.LOSS_TYPE,
  N.ADVANCE_FLAG,
  N.ADVANCE_AMOUNT,
  N.ADVANCE_BALANCE,
  N.EXTENSION_CONTRACT_NO,
  N.ROLL_BACK_AMOUNT,
  N.OVERDUE_DAYS,
  N.COM_SECURITY_KIND,
  N.COUNT_OVERDUE_TERM,
  N.CURRENT_OVERDUE_TERM,
  N.MAX_OVERDUE_TERM,
  N.OVERDUE_AMOUNT,
  N.OVERDUE_RATE_AMOUNT,
  N.OVERDUE_TOTAL,
  N.IS_PAYEE,
  N.PAYEE_NO,
  N.PAYEE_NAME,
  N.IS_LAW_STOP_INTEREST_FLAG,
  N.IS_STOP_INTEREST_FLAG,
  N.CLOSE_DATE,
  N.CANCLE_FLAG,
  N.CANCLE_DATE,
  N.ARBITRATE_FLAG,
  N.OVERDUE_COLLECTION_STATUS,
  N.REPAY_KIND,
  N.REPAY_KIND_APPEND_FUNCTION,
  N.NORMAL_IN_SHEET_INTEREST,
  N.NORMAL_OFF_SHEET_INTEREST,
  N.OVERDUE_IN_SHEET_INTEREST,
  N.OVERDUE_OFF_SHEET_INTEREST,
  N.DEFAULT_IN_SHEET_INTEREST,
  N.DEFAULT_OFF_SHEET_INTEREST,
  N.CANCEL_INTEREST,
  N.CANCEL_ACCRUED_INTEREST,
  N.RATE_ACCORD_KIND,
  N.OVERDUE_REPAY_KIND,
  N.PROVINCE_NUM,
  N.OVERDUE_FLOATING_RATIO,
  N.DIVERT_FLOATING_RATIO,
  N.VALIDITY_LENGTH,
  N.CONTRACT_NUMS,
  N.PAYMENT_WAY,
  N.NORMAL_PAYMENT_AMOUNT,
  N.ENTRUST_PAYMENT_AMOUNT,
  N.SPECIAL_PAYMENT_AMOUNT,
  N.REPAY_DAY,
  N.LOAN_RATE,
  N.PRODUCT_RATE,
  N.BASE_RATE,
  N.RATE_PRICE_KIND,
  N.IS_AUTO_CHG_FA,
  N.IS_AUTO_CHG_FV,
  N.FLOATING_VALUE,
  N.FLOATING_RATIO,
  N.ALLOW_MAX_OVERDUE_DAY,
  N.INTEREST_CLEAN_KIND,
  N.NEW_ADD_AMOUNT,
  N.CONTINUE_ADD_AMOUNT,
  N.RECOMPOSE_AMOUNT,
  N.RATE_ADJUST_KIND,
  N.IS_DESIGN_LOAN,
  N.IS_DISCOUNT,
  N.ADVANCE_REPAY_AMOUNT,
  N.IS_HOLIDAY_POSTPONE,
  N.IS_FARMER,
  N.IS_TOGETHER_BORROWER,
  N.IS_REASERCH,
  N.PREPAYMENT_BEGIN_MONTH,
  N.SUB_LOAN_KIND,
  N.IS_IN_TOWN,
  N.IS_FREE_TAX,
  N.LOAN_PURPOSE_KIND,
  N.IS_ONLY_ONE_LOAN_PURPOSE,
  N.IS_CARVE_OUT_LOAN,
  N.EVERY_MONTH_REPAY_AMOUNT,
  N.MONTH_PAYMENT_LENGTH,
  N.BEGIN_REPAY_CAPITAL_TERM,
  N.COUNT_GRACE_LENGTH,
  N.LOAN_FORM,
  N.EXTENSION_NUM,
  N.RECORDER_USER_ID,
  N.TRANSACTOR_USER_ID,
  N.FINAL_APPROVE_USER_ID,
  N.LOAN_CONTRACT_NO,
  N.IS_CARD_LOAN,
  N.INTEREST_CLEAN_CYCLE,
  N.GROUP_SECURITY_TYPE,
  N.NEXT_CLEAN_INT_RULE,
  N.EXCHANG_ERATE,
  N.DELFLAG,
  N.CREATE_TIME,
  N.UPDATE_TIME,
  N.TRUNC_NO,
  N.APPLICATION_DATE,
  N.IS_FIT_FARMER_STAND,
  N.CHARACTERISTIC_APP_TYPE,
  N.SELF_FINAL,
  N.BIZ_CHANNEL_KIND,
  N.BIZ_CHANNEL_SUB_KIND,
  N.QUICK_LOAN_FLAG,
  N.OLD_CLASS_WAY,
  N.LAST_MANUAL_DATE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(LOAN_ID, '' ) AS LOAN_ID ,
  COALESCE(LOAN_CONTRACT_ID, '' ) AS LOAN_CONTRACT_ID ,
  COALESCE(CUS_ID, '' ) AS CUS_ID ,
  COALESCE(LOAN_LEVEL_FOUR_CLASS, '' ) AS LOAN_LEVEL_FOUR_CLASS ,
  COALESCE(LOAN_LEVEL_FIVE_CLASS, '' ) AS LOAN_LEVEL_FIVE_CLASS ,
  COALESCE(CLOSE_FLAG, '' ) AS CLOSE_FLAG ,
  COALESCE(CURRENCY, '' ) AS CURRENCY ,
  COALESCE(LOAN_PURPOSE, '' ) AS LOAN_PURPOSE ,
  COALESCE(SECURITY_KIND, '' ) AS SECURITY_KIND ,
  COALESCE(LOAN_LENGTH, '' ) AS LOAN_LENGTH ,
  COALESCE(LOAN_BEGIN_DATE,DATE('4999-12-31') ) AS LOAN_BEGIN_DATE ,
  COALESCE(LOAN_END_DATE,DATE('4999-12-31') ) AS LOAN_END_DATE ,
  COALESCE(LOAN_TYPE, '' ) AS LOAN_TYPE ,
  COALESCE(LOAN_RISKNESS, 0 ) AS LOAN_RISKNESS ,
  COALESCE(LAW_SUIT_FLAG, '' ) AS LAW_SUIT_FLAG ,
  COALESCE(EXTENSION_FLAG, '' ) AS EXTENSION_FLAG ,
  COALESCE(EXTENSION_DATE,DATE('4999-12-31') ) AS EXTENSION_DATE ,
  COALESCE(OVERDUE_RATE, 0 ) AS OVERDUE_RATE ,
  COALESCE(ACCOUNT_NAME, '' ) AS ACCOUNT_NAME ,
  COALESCE(ACCOUNT_NO, '' ) AS ACCOUNT_NO ,
  COALESCE(REPAY_NAME, '' ) AS REPAY_NAME ,
  COALESCE(REPAY_NO, '' ) AS REPAY_NO ,
  COALESCE(IS_CARD_REPAY, '' ) AS IS_CARD_REPAY ,
  COALESCE(LOAN_AMOUNT, 0 ) AS LOAN_AMOUNT ,
  COALESCE(LOAN_CONTRACT_AMOUNT, 0 ) AS LOAN_CONTRACT_AMOUNT ,
  COALESCE(LOAN_BALANCE, 0 ) AS LOAN_BALANCE ,
  COALESCE(TOTAL_REPAY_CAPITAL, 0 ) AS TOTAL_REPAY_CAPITAL ,
  COALESCE(CANCEL_CAPITAL, 0 ) AS CANCEL_CAPITAL ,
  COALESCE(CANCEL_CAPITAL_BALANCE, 0 ) AS CANCEL_CAPITAL_BALANCE ,
  COALESCE(INTEREST_AMOUNT, 0 ) AS INTEREST_AMOUNT ,
  COALESCE(IN_SHEET_INTEREST_BALANCE, 0 ) AS IN_SHEET_INTEREST_BALANCE ,
  COALESCE(IN_SHEET_OVERDUE_BALANCE, 0 ) AS IN_SHEET_OVERDUE_BALANCE ,
  COALESCE(OFF_SHEET_INTEREST_BALANCE, 0 ) AS OFF_SHEET_INTEREST_BALANCE ,
  COALESCE(CANCEL_IN_SHEET_BALANCE, 0 ) AS CANCEL_IN_SHEET_BALANCE ,
  COALESCE(CANCEL_OFF_SHEET_BALANCE, 0 ) AS CANCEL_OFF_SHEET_BALANCE ,
  COALESCE(CANCEL_INSHEET_INTEREST_BALANC, 0 ) AS CANCEL_INSHEET_INTEREST_BALANC ,
  COALESCE(CANCEL_OFFSHEET_INTEREST_BALAN, 0 ) AS CANCEL_OFFSHEET_INTEREST_BALAN ,
  COALESCE(APP_OP_ID, '' ) AS APP_OP_ID ,
  COALESCE(IS_GET_PREREPAY_FORFEIT, '' ) AS IS_GET_PREREPAY_FORFEIT ,
  COALESCE(IS_LINE_ROLL_BACK, '' ) AS IS_LINE_ROLL_BACK ,
  COALESCE(HAND_OVER_FLAG, '' ) AS HAND_OVER_FLAG ,
  COALESCE(RECORD_FLAG, '' ) AS RECORD_FLAG ,
  COALESCE(LAW_SUIT_VALIDITY,DATE('4999-12-31') ) AS LAW_SUIT_VALIDITY ,
  COALESCE(LAW_SUIT_ENFORCE_VALIDITY,DATE('4999-12-31') ) AS LAW_SUIT_ENFORCE_VALIDITY ,
  COALESCE(LOSS_TYPE, '' ) AS LOSS_TYPE ,
  COALESCE(ADVANCE_FLAG, '' ) AS ADVANCE_FLAG ,
  COALESCE(ADVANCE_AMOUNT, 0 ) AS ADVANCE_AMOUNT ,
  COALESCE(ADVANCE_BALANCE, 0 ) AS ADVANCE_BALANCE ,
  COALESCE(EXTENSION_CONTRACT_NO, '' ) AS EXTENSION_CONTRACT_NO ,
  COALESCE(ROLL_BACK_AMOUNT, 0 ) AS ROLL_BACK_AMOUNT ,
  COALESCE(OVERDUE_DAYS, 0 ) AS OVERDUE_DAYS ,
  COALESCE(COM_SECURITY_KIND, '' ) AS COM_SECURITY_KIND ,
  COALESCE(COUNT_OVERDUE_TERM, '' ) AS COUNT_OVERDUE_TERM ,
  COALESCE(CURRENT_OVERDUE_TERM, '' ) AS CURRENT_OVERDUE_TERM ,
  COALESCE(MAX_OVERDUE_TERM, '' ) AS MAX_OVERDUE_TERM ,
  COALESCE(OVERDUE_AMOUNT, 0 ) AS OVERDUE_AMOUNT ,
  COALESCE(OVERDUE_RATE_AMOUNT, 0 ) AS OVERDUE_RATE_AMOUNT ,
  COALESCE(OVERDUE_TOTAL, 0 ) AS OVERDUE_TOTAL ,
  COALESCE(IS_PAYEE, '' ) AS IS_PAYEE ,
  COALESCE(PAYEE_NO, '' ) AS PAYEE_NO ,
  COALESCE(PAYEE_NAME, '' ) AS PAYEE_NAME ,
  COALESCE(IS_LAW_STOP_INTEREST_FLAG, '' ) AS IS_LAW_STOP_INTEREST_FLAG ,
  COALESCE(IS_STOP_INTEREST_FLAG, '' ) AS IS_STOP_INTEREST_FLAG ,
  COALESCE(CLOSE_DATE,DATE('4999-12-31') ) AS CLOSE_DATE ,
  COALESCE(CANCLE_FLAG, '' ) AS CANCLE_FLAG ,
  COALESCE(CANCLE_DATE,DATE('4999-12-31') ) AS CANCLE_DATE ,
  COALESCE(ARBITRATE_FLAG, '' ) AS ARBITRATE_FLAG ,
  COALESCE(OVERDUE_COLLECTION_STATUS, '' ) AS OVERDUE_COLLECTION_STATUS ,
  COALESCE(REPAY_KIND, '' ) AS REPAY_KIND ,
  COALESCE(REPAY_KIND_APPEND_FUNCTION, '' ) AS REPAY_KIND_APPEND_FUNCTION ,
  COALESCE(NORMAL_IN_SHEET_INTEREST, 0 ) AS NORMAL_IN_SHEET_INTEREST ,
  COALESCE(NORMAL_OFF_SHEET_INTEREST, 0 ) AS NORMAL_OFF_SHEET_INTEREST ,
  COALESCE(OVERDUE_IN_SHEET_INTEREST, 0 ) AS OVERDUE_IN_SHEET_INTEREST ,
  COALESCE(OVERDUE_OFF_SHEET_INTEREST, 0 ) AS OVERDUE_OFF_SHEET_INTEREST ,
  COALESCE(DEFAULT_IN_SHEET_INTEREST, 0 ) AS DEFAULT_IN_SHEET_INTEREST ,
  COALESCE(DEFAULT_OFF_SHEET_INTEREST, 0 ) AS DEFAULT_OFF_SHEET_INTEREST ,
  COALESCE(CANCEL_INTEREST, 0 ) AS CANCEL_INTEREST ,
  COALESCE(CANCEL_ACCRUED_INTEREST, 0 ) AS CANCEL_ACCRUED_INTEREST ,
  COALESCE(RATE_ACCORD_KIND, '' ) AS RATE_ACCORD_KIND ,
  COALESCE(OVERDUE_REPAY_KIND, '' ) AS OVERDUE_REPAY_KIND ,
  COALESCE(PROVINCE_NUM, '' ) AS PROVINCE_NUM ,
  COALESCE(OVERDUE_FLOATING_RATIO, 0 ) AS OVERDUE_FLOATING_RATIO ,
  COALESCE(DIVERT_FLOATING_RATIO, 0 ) AS DIVERT_FLOATING_RATIO ,
  COALESCE(VALIDITY_LENGTH, '' ) AS VALIDITY_LENGTH ,
  COALESCE(CONTRACT_NUMS, 0 ) AS CONTRACT_NUMS ,
  COALESCE(PAYMENT_WAY, '' ) AS PAYMENT_WAY ,
  COALESCE(NORMAL_PAYMENT_AMOUNT, 0 ) AS NORMAL_PAYMENT_AMOUNT ,
  COALESCE(ENTRUST_PAYMENT_AMOUNT, 0 ) AS ENTRUST_PAYMENT_AMOUNT ,
  COALESCE(SPECIAL_PAYMENT_AMOUNT, 0 ) AS SPECIAL_PAYMENT_AMOUNT ,
  COALESCE(REPAY_DAY, '' ) AS REPAY_DAY ,
  COALESCE(LOAN_RATE, 0 ) AS LOAN_RATE ,
  COALESCE(PRODUCT_RATE, 0 ) AS PRODUCT_RATE ,
  COALESCE(BASE_RATE, 0 ) AS BASE_RATE ,
  COALESCE(RATE_PRICE_KIND, '' ) AS RATE_PRICE_KIND ,
  COALESCE(IS_AUTO_CHG_FA, '' ) AS IS_AUTO_CHG_FA ,
  COALESCE(IS_AUTO_CHG_FV, '' ) AS IS_AUTO_CHG_FV ,
  COALESCE(FLOATING_VALUE, 0 ) AS FLOATING_VALUE ,
  COALESCE(FLOATING_RATIO, 0 ) AS FLOATING_RATIO ,
  COALESCE(ALLOW_MAX_OVERDUE_DAY, 0 ) AS ALLOW_MAX_OVERDUE_DAY ,
  COALESCE(INTEREST_CLEAN_KIND, '' ) AS INTEREST_CLEAN_KIND ,
  COALESCE(NEW_ADD_AMOUNT, 0 ) AS NEW_ADD_AMOUNT ,
  COALESCE(CONTINUE_ADD_AMOUNT, 0 ) AS CONTINUE_ADD_AMOUNT ,
  COALESCE(RECOMPOSE_AMOUNT, 0 ) AS RECOMPOSE_AMOUNT ,
  COALESCE(RATE_ADJUST_KIND, '' ) AS RATE_ADJUST_KIND ,
  COALESCE(IS_DESIGN_LOAN, '' ) AS IS_DESIGN_LOAN ,
  COALESCE(IS_DISCOUNT, '' ) AS IS_DISCOUNT ,
  COALESCE(ADVANCE_REPAY_AMOUNT, 0 ) AS ADVANCE_REPAY_AMOUNT ,
  COALESCE(IS_HOLIDAY_POSTPONE, '' ) AS IS_HOLIDAY_POSTPONE ,
  COALESCE(IS_FARMER, '' ) AS IS_FARMER ,
  COALESCE(IS_TOGETHER_BORROWER, '' ) AS IS_TOGETHER_BORROWER ,
  COALESCE(IS_REASERCH, '' ) AS IS_REASERCH ,
  COALESCE(PREPAYMENT_BEGIN_MONTH, '' ) AS PREPAYMENT_BEGIN_MONTH ,
  COALESCE(SUB_LOAN_KIND, '' ) AS SUB_LOAN_KIND ,
  COALESCE(IS_IN_TOWN, '' ) AS IS_IN_TOWN ,
  COALESCE(IS_FREE_TAX, '' ) AS IS_FREE_TAX ,
  COALESCE(LOAN_PURPOSE_KIND, '' ) AS LOAN_PURPOSE_KIND ,
  COALESCE(IS_ONLY_ONE_LOAN_PURPOSE, '' ) AS IS_ONLY_ONE_LOAN_PURPOSE ,
  COALESCE(IS_CARVE_OUT_LOAN, '' ) AS IS_CARVE_OUT_LOAN ,
  COALESCE(EVERY_MONTH_REPAY_AMOUNT, 0 ) AS EVERY_MONTH_REPAY_AMOUNT ,
  COALESCE(MONTH_PAYMENT_LENGTH, '' ) AS MONTH_PAYMENT_LENGTH ,
  COALESCE(BEGIN_REPAY_CAPITAL_TERM, '' ) AS BEGIN_REPAY_CAPITAL_TERM ,
  COALESCE(COUNT_GRACE_LENGTH, '' ) AS COUNT_GRACE_LENGTH ,
  COALESCE(LOAN_FORM, '' ) AS LOAN_FORM ,
  COALESCE(EXTENSION_NUM, 0 ) AS EXTENSION_NUM ,
  COALESCE(RECORDER_USER_ID, '' ) AS RECORDER_USER_ID ,
  COALESCE(TRANSACTOR_USER_ID, '' ) AS TRANSACTOR_USER_ID ,
  COALESCE(FINAL_APPROVE_USER_ID, '' ) AS FINAL_APPROVE_USER_ID ,
  COALESCE(LOAN_CONTRACT_NO, '' ) AS LOAN_CONTRACT_NO ,
  COALESCE(IS_CARD_LOAN, '' ) AS IS_CARD_LOAN ,
  COALESCE(INTEREST_CLEAN_CYCLE, '' ) AS INTEREST_CLEAN_CYCLE ,
  COALESCE(GROUP_SECURITY_TYPE, '' ) AS GROUP_SECURITY_TYPE ,
  COALESCE(NEXT_CLEAN_INT_RULE, '' ) AS NEXT_CLEAN_INT_RULE ,
  COALESCE(EXCHANG_ERATE, 0 ) AS EXCHANG_ERATE ,
  COALESCE(DELFLAG, '' ) AS DELFLAG ,
  COALESCE(CREATE_TIME,'4999-12-31 00:00:00' ) AS CREATE_TIME ,
  COALESCE(UPDATE_TIME,'4999-12-31 00:00:00' ) AS UPDATE_TIME ,
  COALESCE(TRUNC_NO, 0 ) AS TRUNC_NO ,
  COALESCE(APPLICATION_DATE,DATE('4999-12-31') ) AS APPLICATION_DATE ,
  COALESCE(IS_FIT_FARMER_STAND, '' ) AS IS_FIT_FARMER_STAND ,
  COALESCE(CHARACTERISTIC_APP_TYPE, '' ) AS CHARACTERISTIC_APP_TYPE ,
  COALESCE(SELF_FINAL, '' ) AS SELF_FINAL ,
  COALESCE(BIZ_CHANNEL_KIND, '' ) AS BIZ_CHANNEL_KIND ,
  COALESCE(BIZ_CHANNEL_SUB_KIND, '' ) AS BIZ_CHANNEL_SUB_KIND ,
  COALESCE(QUICK_LOAN_FLAG, '' ) AS QUICK_LOAN_FLAG ,
  COALESCE(OLD_CLASS_WAY, '' ) AS OLD_CLASS_WAY ,
  COALESCE(LAST_MANUAL_DATE,DATE('4999-12-31') ) AS LAST_MANUAL_DATE 
 FROM  dw_tdata.PCS_006_TB_LON_LOAN_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  LOAN_ID ,
  LOAN_CONTRACT_ID ,
  CUS_ID ,
  LOAN_LEVEL_FOUR_CLASS ,
  LOAN_LEVEL_FIVE_CLASS ,
  CLOSE_FLAG ,
  CURRENCY ,
  LOAN_PURPOSE ,
  SECURITY_KIND ,
  LOAN_LENGTH ,
  LOAN_BEGIN_DATE ,
  LOAN_END_DATE ,
  LOAN_TYPE ,
  LOAN_RISKNESS ,
  LAW_SUIT_FLAG ,
  EXTENSION_FLAG ,
  EXTENSION_DATE ,
  OVERDUE_RATE ,
  ACCOUNT_NAME ,
  ACCOUNT_NO ,
  REPAY_NAME ,
  REPAY_NO ,
  IS_CARD_REPAY ,
  LOAN_AMOUNT ,
  LOAN_CONTRACT_AMOUNT ,
  LOAN_BALANCE ,
  TOTAL_REPAY_CAPITAL ,
  CANCEL_CAPITAL ,
  CANCEL_CAPITAL_BALANCE ,
  INTEREST_AMOUNT ,
  IN_SHEET_INTEREST_BALANCE ,
  IN_SHEET_OVERDUE_BALANCE ,
  OFF_SHEET_INTEREST_BALANCE ,
  CANCEL_IN_SHEET_BALANCE ,
  CANCEL_OFF_SHEET_BALANCE ,
  CANCEL_INSHEET_INTEREST_BALANC ,
  CANCEL_OFFSHEET_INTEREST_BALAN ,
  APP_OP_ID ,
  IS_GET_PREREPAY_FORFEIT ,
  IS_LINE_ROLL_BACK ,
  HAND_OVER_FLAG ,
  RECORD_FLAG ,
  LAW_SUIT_VALIDITY ,
  LAW_SUIT_ENFORCE_VALIDITY ,
  LOSS_TYPE ,
  ADVANCE_FLAG ,
  ADVANCE_AMOUNT ,
  ADVANCE_BALANCE ,
  EXTENSION_CONTRACT_NO ,
  ROLL_BACK_AMOUNT ,
  OVERDUE_DAYS ,
  COM_SECURITY_KIND ,
  COUNT_OVERDUE_TERM ,
  CURRENT_OVERDUE_TERM ,
  MAX_OVERDUE_TERM ,
  OVERDUE_AMOUNT ,
  OVERDUE_RATE_AMOUNT ,
  OVERDUE_TOTAL ,
  IS_PAYEE ,
  PAYEE_NO ,
  PAYEE_NAME ,
  IS_LAW_STOP_INTEREST_FLAG ,
  IS_STOP_INTEREST_FLAG ,
  CLOSE_DATE ,
  CANCLE_FLAG ,
  CANCLE_DATE ,
  ARBITRATE_FLAG ,
  OVERDUE_COLLECTION_STATUS ,
  REPAY_KIND ,
  REPAY_KIND_APPEND_FUNCTION ,
  NORMAL_IN_SHEET_INTEREST ,
  NORMAL_OFF_SHEET_INTEREST ,
  OVERDUE_IN_SHEET_INTEREST ,
  OVERDUE_OFF_SHEET_INTEREST ,
  DEFAULT_IN_SHEET_INTEREST ,
  DEFAULT_OFF_SHEET_INTEREST ,
  CANCEL_INTEREST ,
  CANCEL_ACCRUED_INTEREST ,
  RATE_ACCORD_KIND ,
  OVERDUE_REPAY_KIND ,
  PROVINCE_NUM ,
  OVERDUE_FLOATING_RATIO ,
  DIVERT_FLOATING_RATIO ,
  VALIDITY_LENGTH ,
  CONTRACT_NUMS ,
  PAYMENT_WAY ,
  NORMAL_PAYMENT_AMOUNT ,
  ENTRUST_PAYMENT_AMOUNT ,
  SPECIAL_PAYMENT_AMOUNT ,
  REPAY_DAY ,
  LOAN_RATE ,
  PRODUCT_RATE ,
  BASE_RATE ,
  RATE_PRICE_KIND ,
  IS_AUTO_CHG_FA ,
  IS_AUTO_CHG_FV ,
  FLOATING_VALUE ,
  FLOATING_RATIO ,
  ALLOW_MAX_OVERDUE_DAY ,
  INTEREST_CLEAN_KIND ,
  NEW_ADD_AMOUNT ,
  CONTINUE_ADD_AMOUNT ,
  RECOMPOSE_AMOUNT ,
  RATE_ADJUST_KIND ,
  IS_DESIGN_LOAN ,
  IS_DISCOUNT ,
  ADVANCE_REPAY_AMOUNT ,
  IS_HOLIDAY_POSTPONE ,
  IS_FARMER ,
  IS_TOGETHER_BORROWER ,
  IS_REASERCH ,
  PREPAYMENT_BEGIN_MONTH ,
  SUB_LOAN_KIND ,
  IS_IN_TOWN ,
  IS_FREE_TAX ,
  LOAN_PURPOSE_KIND ,
  IS_ONLY_ONE_LOAN_PURPOSE ,
  IS_CARVE_OUT_LOAN ,
  EVERY_MONTH_REPAY_AMOUNT ,
  MONTH_PAYMENT_LENGTH ,
  BEGIN_REPAY_CAPITAL_TERM ,
  COUNT_GRACE_LENGTH ,
  LOAN_FORM ,
  EXTENSION_NUM ,
  RECORDER_USER_ID ,
  TRANSACTOR_USER_ID ,
  FINAL_APPROVE_USER_ID ,
  LOAN_CONTRACT_NO ,
  IS_CARD_LOAN ,
  INTEREST_CLEAN_CYCLE ,
  GROUP_SECURITY_TYPE ,
  NEXT_CLEAN_INT_RULE ,
  EXCHANG_ERATE ,
  DELFLAG ,
  CREATE_TIME ,
  UPDATE_TIME ,
  TRUNC_NO ,
  APPLICATION_DATE ,
  IS_FIT_FARMER_STAND ,
  CHARACTERISTIC_APP_TYPE ,
  SELF_FINAL ,
  BIZ_CHANNEL_KIND ,
  BIZ_CHANNEL_SUB_KIND ,
  QUICK_LOAN_FLAG ,
  OLD_CLASS_WAY ,
  LAST_MANUAL_DATE 
 FROM dw_sdata.PCS_006_TB_LON_LOAN 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.LOAN_ID = T.LOAN_ID
WHERE
(T.LOAN_ID IS NULL)
 OR N.LOAN_CONTRACT_ID<>T.LOAN_CONTRACT_ID
 OR N.CUS_ID<>T.CUS_ID
 OR N.LOAN_LEVEL_FOUR_CLASS<>T.LOAN_LEVEL_FOUR_CLASS
 OR N.LOAN_LEVEL_FIVE_CLASS<>T.LOAN_LEVEL_FIVE_CLASS
 OR N.CLOSE_FLAG<>T.CLOSE_FLAG
 OR N.CURRENCY<>T.CURRENCY
 OR N.LOAN_PURPOSE<>T.LOAN_PURPOSE
 OR N.SECURITY_KIND<>T.SECURITY_KIND
 OR N.LOAN_LENGTH<>T.LOAN_LENGTH
 OR N.LOAN_BEGIN_DATE<>T.LOAN_BEGIN_DATE
 OR N.LOAN_END_DATE<>T.LOAN_END_DATE
 OR N.LOAN_TYPE<>T.LOAN_TYPE
 OR N.LOAN_RISKNESS<>T.LOAN_RISKNESS
 OR N.LAW_SUIT_FLAG<>T.LAW_SUIT_FLAG
 OR N.EXTENSION_FLAG<>T.EXTENSION_FLAG
 OR N.EXTENSION_DATE<>T.EXTENSION_DATE
 OR N.OVERDUE_RATE<>T.OVERDUE_RATE
 OR N.ACCOUNT_NAME<>T.ACCOUNT_NAME
 OR N.ACCOUNT_NO<>T.ACCOUNT_NO
 OR N.REPAY_NAME<>T.REPAY_NAME
 OR N.REPAY_NO<>T.REPAY_NO
 OR N.IS_CARD_REPAY<>T.IS_CARD_REPAY
 OR N.LOAN_AMOUNT<>T.LOAN_AMOUNT
 OR N.LOAN_CONTRACT_AMOUNT<>T.LOAN_CONTRACT_AMOUNT
 OR N.LOAN_BALANCE<>T.LOAN_BALANCE
 OR N.TOTAL_REPAY_CAPITAL<>T.TOTAL_REPAY_CAPITAL
 OR N.CANCEL_CAPITAL<>T.CANCEL_CAPITAL
 OR N.CANCEL_CAPITAL_BALANCE<>T.CANCEL_CAPITAL_BALANCE
 OR N.INTEREST_AMOUNT<>T.INTEREST_AMOUNT
 OR N.IN_SHEET_INTEREST_BALANCE<>T.IN_SHEET_INTEREST_BALANCE
 OR N.IN_SHEET_OVERDUE_BALANCE<>T.IN_SHEET_OVERDUE_BALANCE
 OR N.OFF_SHEET_INTEREST_BALANCE<>T.OFF_SHEET_INTEREST_BALANCE
 OR N.CANCEL_IN_SHEET_BALANCE<>T.CANCEL_IN_SHEET_BALANCE
 OR N.CANCEL_OFF_SHEET_BALANCE<>T.CANCEL_OFF_SHEET_BALANCE
 OR N.CANCEL_INSHEET_INTEREST_BALANC<>T.CANCEL_INSHEET_INTEREST_BALANC
 OR N.CANCEL_OFFSHEET_INTEREST_BALAN<>T.CANCEL_OFFSHEET_INTEREST_BALAN
 OR N.APP_OP_ID<>T.APP_OP_ID
 OR N.IS_GET_PREREPAY_FORFEIT<>T.IS_GET_PREREPAY_FORFEIT
 OR N.IS_LINE_ROLL_BACK<>T.IS_LINE_ROLL_BACK
 OR N.HAND_OVER_FLAG<>T.HAND_OVER_FLAG
 OR N.RECORD_FLAG<>T.RECORD_FLAG
 OR N.LAW_SUIT_VALIDITY<>T.LAW_SUIT_VALIDITY
 OR N.LAW_SUIT_ENFORCE_VALIDITY<>T.LAW_SUIT_ENFORCE_VALIDITY
 OR N.LOSS_TYPE<>T.LOSS_TYPE
 OR N.ADVANCE_FLAG<>T.ADVANCE_FLAG
 OR N.ADVANCE_AMOUNT<>T.ADVANCE_AMOUNT
 OR N.ADVANCE_BALANCE<>T.ADVANCE_BALANCE
 OR N.EXTENSION_CONTRACT_NO<>T.EXTENSION_CONTRACT_NO
 OR N.ROLL_BACK_AMOUNT<>T.ROLL_BACK_AMOUNT
 OR N.OVERDUE_DAYS<>T.OVERDUE_DAYS
 OR N.COM_SECURITY_KIND<>T.COM_SECURITY_KIND
 OR N.COUNT_OVERDUE_TERM<>T.COUNT_OVERDUE_TERM
 OR N.CURRENT_OVERDUE_TERM<>T.CURRENT_OVERDUE_TERM
 OR N.MAX_OVERDUE_TERM<>T.MAX_OVERDUE_TERM
 OR N.OVERDUE_AMOUNT<>T.OVERDUE_AMOUNT
 OR N.OVERDUE_RATE_AMOUNT<>T.OVERDUE_RATE_AMOUNT
 OR N.OVERDUE_TOTAL<>T.OVERDUE_TOTAL
 OR N.IS_PAYEE<>T.IS_PAYEE
 OR N.PAYEE_NO<>T.PAYEE_NO
 OR N.PAYEE_NAME<>T.PAYEE_NAME
 OR N.IS_LAW_STOP_INTEREST_FLAG<>T.IS_LAW_STOP_INTEREST_FLAG
 OR N.IS_STOP_INTEREST_FLAG<>T.IS_STOP_INTEREST_FLAG
 OR N.CLOSE_DATE<>T.CLOSE_DATE
 OR N.CANCLE_FLAG<>T.CANCLE_FLAG
 OR N.CANCLE_DATE<>T.CANCLE_DATE
 OR N.ARBITRATE_FLAG<>T.ARBITRATE_FLAG
 OR N.OVERDUE_COLLECTION_STATUS<>T.OVERDUE_COLLECTION_STATUS
 OR N.REPAY_KIND<>T.REPAY_KIND
 OR N.REPAY_KIND_APPEND_FUNCTION<>T.REPAY_KIND_APPEND_FUNCTION
 OR N.NORMAL_IN_SHEET_INTEREST<>T.NORMAL_IN_SHEET_INTEREST
 OR N.NORMAL_OFF_SHEET_INTEREST<>T.NORMAL_OFF_SHEET_INTEREST
 OR N.OVERDUE_IN_SHEET_INTEREST<>T.OVERDUE_IN_SHEET_INTEREST
 OR N.OVERDUE_OFF_SHEET_INTEREST<>T.OVERDUE_OFF_SHEET_INTEREST
 OR N.DEFAULT_IN_SHEET_INTEREST<>T.DEFAULT_IN_SHEET_INTEREST
 OR N.DEFAULT_OFF_SHEET_INTEREST<>T.DEFAULT_OFF_SHEET_INTEREST
 OR N.CANCEL_INTEREST<>T.CANCEL_INTEREST
 OR N.CANCEL_ACCRUED_INTEREST<>T.CANCEL_ACCRUED_INTEREST
 OR N.RATE_ACCORD_KIND<>T.RATE_ACCORD_KIND
 OR N.OVERDUE_REPAY_KIND<>T.OVERDUE_REPAY_KIND
 OR N.PROVINCE_NUM<>T.PROVINCE_NUM
 OR N.OVERDUE_FLOATING_RATIO<>T.OVERDUE_FLOATING_RATIO
 OR N.DIVERT_FLOATING_RATIO<>T.DIVERT_FLOATING_RATIO
 OR N.VALIDITY_LENGTH<>T.VALIDITY_LENGTH
 OR N.CONTRACT_NUMS<>T.CONTRACT_NUMS
 OR N.PAYMENT_WAY<>T.PAYMENT_WAY
 OR N.NORMAL_PAYMENT_AMOUNT<>T.NORMAL_PAYMENT_AMOUNT
 OR N.ENTRUST_PAYMENT_AMOUNT<>T.ENTRUST_PAYMENT_AMOUNT
 OR N.SPECIAL_PAYMENT_AMOUNT<>T.SPECIAL_PAYMENT_AMOUNT
 OR N.REPAY_DAY<>T.REPAY_DAY
 OR N.LOAN_RATE<>T.LOAN_RATE
 OR N.PRODUCT_RATE<>T.PRODUCT_RATE
 OR N.BASE_RATE<>T.BASE_RATE
 OR N.RATE_PRICE_KIND<>T.RATE_PRICE_KIND
 OR N.IS_AUTO_CHG_FA<>T.IS_AUTO_CHG_FA
 OR N.IS_AUTO_CHG_FV<>T.IS_AUTO_CHG_FV
 OR N.FLOATING_VALUE<>T.FLOATING_VALUE
 OR N.FLOATING_RATIO<>T.FLOATING_RATIO
 OR N.ALLOW_MAX_OVERDUE_DAY<>T.ALLOW_MAX_OVERDUE_DAY
 OR N.INTEREST_CLEAN_KIND<>T.INTEREST_CLEAN_KIND
 OR N.NEW_ADD_AMOUNT<>T.NEW_ADD_AMOUNT
 OR N.CONTINUE_ADD_AMOUNT<>T.CONTINUE_ADD_AMOUNT
 OR N.RECOMPOSE_AMOUNT<>T.RECOMPOSE_AMOUNT
 OR N.RATE_ADJUST_KIND<>T.RATE_ADJUST_KIND
 OR N.IS_DESIGN_LOAN<>T.IS_DESIGN_LOAN
 OR N.IS_DISCOUNT<>T.IS_DISCOUNT
 OR N.ADVANCE_REPAY_AMOUNT<>T.ADVANCE_REPAY_AMOUNT
 OR N.IS_HOLIDAY_POSTPONE<>T.IS_HOLIDAY_POSTPONE
 OR N.IS_FARMER<>T.IS_FARMER
 OR N.IS_TOGETHER_BORROWER<>T.IS_TOGETHER_BORROWER
 OR N.IS_REASERCH<>T.IS_REASERCH
 OR N.PREPAYMENT_BEGIN_MONTH<>T.PREPAYMENT_BEGIN_MONTH
 OR N.SUB_LOAN_KIND<>T.SUB_LOAN_KIND
 OR N.IS_IN_TOWN<>T.IS_IN_TOWN
 OR N.IS_FREE_TAX<>T.IS_FREE_TAX
 OR N.LOAN_PURPOSE_KIND<>T.LOAN_PURPOSE_KIND
 OR N.IS_ONLY_ONE_LOAN_PURPOSE<>T.IS_ONLY_ONE_LOAN_PURPOSE
 OR N.IS_CARVE_OUT_LOAN<>T.IS_CARVE_OUT_LOAN
 OR N.EVERY_MONTH_REPAY_AMOUNT<>T.EVERY_MONTH_REPAY_AMOUNT
 OR N.MONTH_PAYMENT_LENGTH<>T.MONTH_PAYMENT_LENGTH
 OR N.BEGIN_REPAY_CAPITAL_TERM<>T.BEGIN_REPAY_CAPITAL_TERM
 OR N.COUNT_GRACE_LENGTH<>T.COUNT_GRACE_LENGTH
 OR N.LOAN_FORM<>T.LOAN_FORM
 OR N.EXTENSION_NUM<>T.EXTENSION_NUM
 OR N.RECORDER_USER_ID<>T.RECORDER_USER_ID
 OR N.TRANSACTOR_USER_ID<>T.TRANSACTOR_USER_ID
 OR N.FINAL_APPROVE_USER_ID<>T.FINAL_APPROVE_USER_ID
 OR N.LOAN_CONTRACT_NO<>T.LOAN_CONTRACT_NO
 OR N.IS_CARD_LOAN<>T.IS_CARD_LOAN
 OR N.INTEREST_CLEAN_CYCLE<>T.INTEREST_CLEAN_CYCLE
 OR N.GROUP_SECURITY_TYPE<>T.GROUP_SECURITY_TYPE
 OR N.NEXT_CLEAN_INT_RULE<>T.NEXT_CLEAN_INT_RULE
 OR N.EXCHANG_ERATE<>T.EXCHANG_ERATE
 OR N.DELFLAG<>T.DELFLAG
 OR N.CREATE_TIME<>T.CREATE_TIME
 OR N.UPDATE_TIME<>T.UPDATE_TIME
 OR N.TRUNC_NO<>T.TRUNC_NO
 OR N.APPLICATION_DATE<>T.APPLICATION_DATE
 OR N.IS_FIT_FARMER_STAND<>T.IS_FIT_FARMER_STAND
 OR N.CHARACTERISTIC_APP_TYPE<>T.CHARACTERISTIC_APP_TYPE
 OR N.SELF_FINAL<>T.SELF_FINAL
 OR N.BIZ_CHANNEL_KIND<>T.BIZ_CHANNEL_KIND
 OR N.BIZ_CHANNEL_SUB_KIND<>T.BIZ_CHANNEL_SUB_KIND
 OR N.QUICK_LOAN_FLAG<>T.QUICK_LOAN_FLAG
 OR N.OLD_CLASS_WAY<>T.OLD_CLASS_WAY
 OR N.LAST_MANUAL_DATE<>T.LAST_MANUAL_DATE
;

--Step3:
UPDATE dw_sdata.PCS_006_TB_LON_LOAN P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_336
WHERE P.End_Dt=DATE('2100-12-31')
AND P.LOAN_ID=T_336.LOAN_ID
;

--Step4:
INSERT  INTO dw_sdata.PCS_006_TB_LON_LOAN SELECT * FROM T_336;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
