#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.PCS_005_TB_SUP_LOAN_INFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.PCS_005_TB_SUP_LOAN_INFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_320 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.PCS_005_TB_SUP_LOAN_INFO WHERE 1=0;

--Step2:
INSERT  INTO T_320 (
  PRV_COD,
  RLS_DEP,
  OPN_DEP,
  TAL_DEP,
  DUE_NUM,
  TRAN_FROM,
  CRD_CENT,
  CERT_TYPE,
  CERT_NUM,
  CUS_NO,
  CON_NO,
  DUE_NUM_SUN,
  BRW_NAME,
  AMT,
  BEG_DATE,
  END_DATE,
  BEG_ITR_DATE,
  BEG_PLAN_DATE,
  STS,
  CURR_COD,
  PRM_CLS,
  AST_CLS,
  BUS_COD,
  CASPAN,
  PRM_PAY_TYP,
  AST_PAY_TYP,
  SPEC_PAYMENT_DATE,
  DIST_DAYS,
  ITR_RATE_WAY,
  NOR_ITR_RATE,
  DEL_ITR_RATE,
  REL_ITR_RATE,
  PRIM_ACCT_TYP,
  PRIM_ACCT_FLG,
  PRIM_ACCT,
  PRIM_OPEN_DEP,
  PRIM_AST_ACCT,
  PRIM_ACCT_NAME,
  PAY_PRIM_ACCT_TYP,
  PAY_PRIM_ACCT_FLG,
  PAY_PRIM_ACCT,
  PAY_OPEN_DEP,
  PAY_PRIM_NAME,
  DISC_TYPE,
  DISC_STOP_FLG,
  DISC_END_DATE,
  DISC_ADV_EXP_AMT,
  DISC_ADV_AMT,
  DISC_SUBD_EXP_AMT,
  DISC_SUBD_AMT,
  ITR_CAL_RULE,
  FORW_PROV_DATE,
  NEXT_PROV_DATE,
  ITR_FRE_FLG,
  ITR_FRE_CYL,
  CEAS_FLG,
  CEAS_DATE,
  ITR_FRE_TERM,
  OVER_DATE,
  CLASSIFY_FLG,
  DEVA_STS,
  DEVA_DATE,
  CLOSE_DATE,
  STG_FIRST_MON,
  STG_FIRST_DATE,
  STUD_PERD,
  BALL_MTH_END_PERD,
  FRE_PAY_METH_DAY,
  FRE_PAY_METH_PAY_AMT,
  PRN_SETT_ACC,
  PRN_SETT_ACC_NAME,
  PRN_SETT_ACC_TYP,
  ITR_SETT_ACC,
  ITR_SETT_ACC_NAME,
  ITR_SETT_ACC_TYP,
  AGY_BUS_ACC,
  AGY_BUS_ACC_NAME,
  AGY_BUS_ACC_DEP,
  AGY_BUS_ITR_ACC,
  AGY_BUS_ITR_ACC_NAME,
  AGY_BUS_ITR_ACC_DEP,
  AGY_BUS_NUM,
  AGY_BUS_PROP,
  HOLIDAY_FLG,
  PRE_ITR_AMT,
  PROVD_FUND_ACC,
  PROVD_FUND_ACC_DEP,
  BAT_FLG,
  RECALL_FLG,
  COUNTER_FLG,
  LAST_DATE,
  LAST_STAN,
  CHG_PAY_DAY_FLG,
  CON_PERI_NUM,
  NUM_BASE_PERI,
  BASE_AMT,
  CURR_PERI,
  EFF_CURR_PERI,
  BEG_TERM,
  CHG_TERM,
  ADD_AMT,
  PROP,
  BRU_NUM,
  BRU_NUM_SND,
  ACC_OTD_DATE,
  RMK1,
  RMK2,
  RMK3,
  RMK4,
  RMK1_BAL,
  RMK2_BAL,
  RMK3_BAL,
  start_dt,
  end_dt)
SELECT
  N.PRV_COD,
  N.RLS_DEP,
  N.OPN_DEP,
  N.TAL_DEP,
  N.DUE_NUM,
  N.TRAN_FROM,
  N.CRD_CENT,
  N.CERT_TYPE,
  N.CERT_NUM,
  N.CUS_NO,
  N.CON_NO,
  N.DUE_NUM_SUN,
  N.BRW_NAME,
  N.AMT,
  N.BEG_DATE,
  N.END_DATE,
  N.BEG_ITR_DATE,
  N.BEG_PLAN_DATE,
  N.STS,
  N.CURR_COD,
  N.PRM_CLS,
  N.AST_CLS,
  N.BUS_COD,
  N.CASPAN,
  N.PRM_PAY_TYP,
  N.AST_PAY_TYP,
  N.SPEC_PAYMENT_DATE,
  N.DIST_DAYS,
  N.ITR_RATE_WAY,
  N.NOR_ITR_RATE,
  N.DEL_ITR_RATE,
  N.REL_ITR_RATE,
  N.PRIM_ACCT_TYP,
  N.PRIM_ACCT_FLG,
  N.PRIM_ACCT,
  N.PRIM_OPEN_DEP,
  N.PRIM_AST_ACCT,
  N.PRIM_ACCT_NAME,
  N.PAY_PRIM_ACCT_TYP,
  N.PAY_PRIM_ACCT_FLG,
  N.PAY_PRIM_ACCT,
  N.PAY_OPEN_DEP,
  N.PAY_PRIM_NAME,
  N.DISC_TYPE,
  N.DISC_STOP_FLG,
  N.DISC_END_DATE,
  N.DISC_ADV_EXP_AMT,
  N.DISC_ADV_AMT,
  N.DISC_SUBD_EXP_AMT,
  N.DISC_SUBD_AMT,
  N.ITR_CAL_RULE,
  N.FORW_PROV_DATE,
  N.NEXT_PROV_DATE,
  N.ITR_FRE_FLG,
  N.ITR_FRE_CYL,
  N.CEAS_FLG,
  N.CEAS_DATE,
  N.ITR_FRE_TERM,
  N.OVER_DATE,
  N.CLASSIFY_FLG,
  N.DEVA_STS,
  N.DEVA_DATE,
  N.CLOSE_DATE,
  N.STG_FIRST_MON,
  N.STG_FIRST_DATE,
  N.STUD_PERD,
  N.BALL_MTH_END_PERD,
  N.FRE_PAY_METH_DAY,
  N.FRE_PAY_METH_PAY_AMT,
  N.PRN_SETT_ACC,
  N.PRN_SETT_ACC_NAME,
  N.PRN_SETT_ACC_TYP,
  N.ITR_SETT_ACC,
  N.ITR_SETT_ACC_NAME,
  N.ITR_SETT_ACC_TYP,
  N.AGY_BUS_ACC,
  N.AGY_BUS_ACC_NAME,
  N.AGY_BUS_ACC_DEP,
  N.AGY_BUS_ITR_ACC,
  N.AGY_BUS_ITR_ACC_NAME,
  N.AGY_BUS_ITR_ACC_DEP,
  N.AGY_BUS_NUM,
  N.AGY_BUS_PROP,
  N.HOLIDAY_FLG,
  N.PRE_ITR_AMT,
  N.PROVD_FUND_ACC,
  N.PROVD_FUND_ACC_DEP,
  N.BAT_FLG,
  N.RECALL_FLG,
  N.COUNTER_FLG,
  N.LAST_DATE,
  N.LAST_STAN,
  N.CHG_PAY_DAY_FLG,
  N.CON_PERI_NUM,
  N.NUM_BASE_PERI,
  N.BASE_AMT,
  N.CURR_PERI,
  N.EFF_CURR_PERI,
  N.BEG_TERM,
  N.CHG_TERM,
  N.ADD_AMT,
  N.PROP,
  N.BRU_NUM,
  N.BRU_NUM_SND,
  N.ACC_OTD_DATE,
  N.RMK1,
  N.RMK2,
  N.RMK3,
  N.RMK4,
  N.RMK1_BAL,
  N.RMK2_BAL,
  N.RMK3_BAL,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PRV_COD, '' ) AS PRV_COD ,
  COALESCE(RLS_DEP, '' ) AS RLS_DEP ,
  COALESCE(OPN_DEP, '' ) AS OPN_DEP ,
  COALESCE(TAL_DEP, '' ) AS TAL_DEP ,
  COALESCE(DUE_NUM, '' ) AS DUE_NUM ,
  COALESCE(TRAN_FROM, '' ) AS TRAN_FROM ,
  COALESCE(CRD_CENT, '' ) AS CRD_CENT ,
  COALESCE(CERT_TYPE, '' ) AS CERT_TYPE ,
  COALESCE(CERT_NUM, '' ) AS CERT_NUM ,
  COALESCE(CUS_NO, '' ) AS CUS_NO ,
  COALESCE(CON_NO, '' ) AS CON_NO ,
  COALESCE(DUE_NUM_SUN, '' ) AS DUE_NUM_SUN ,
  COALESCE(BRW_NAME, '' ) AS BRW_NAME ,
  COALESCE(AMT, 0 ) AS AMT ,
  COALESCE(BEG_DATE, '' ) AS BEG_DATE ,
  COALESCE(END_DATE, '' ) AS END_DATE ,
  COALESCE(BEG_ITR_DATE, '' ) AS BEG_ITR_DATE ,
  COALESCE(BEG_PLAN_DATE, '' ) AS BEG_PLAN_DATE ,
  COALESCE(STS, '' ) AS STS ,
  COALESCE(CURR_COD, '' ) AS CURR_COD ,
  COALESCE(PRM_CLS, '' ) AS PRM_CLS ,
  COALESCE(AST_CLS, '' ) AS AST_CLS ,
  COALESCE(BUS_COD, '' ) AS BUS_COD ,
  COALESCE(CASPAN, '' ) AS CASPAN ,
  COALESCE(PRM_PAY_TYP, '' ) AS PRM_PAY_TYP ,
  COALESCE(AST_PAY_TYP, '' ) AS AST_PAY_TYP ,
  COALESCE(SPEC_PAYMENT_DATE, '' ) AS SPEC_PAYMENT_DATE ,
  COALESCE(DIST_DAYS, 0 ) AS DIST_DAYS ,
  COALESCE(ITR_RATE_WAY, '' ) AS ITR_RATE_WAY ,
  COALESCE(NOR_ITR_RATE, 0 ) AS NOR_ITR_RATE ,
  COALESCE(DEL_ITR_RATE, 0 ) AS DEL_ITR_RATE ,
  COALESCE(REL_ITR_RATE, 0 ) AS REL_ITR_RATE ,
  COALESCE(PRIM_ACCT_TYP, '' ) AS PRIM_ACCT_TYP ,
  COALESCE(PRIM_ACCT_FLG, '' ) AS PRIM_ACCT_FLG ,
  COALESCE(PRIM_ACCT, '' ) AS PRIM_ACCT ,
  COALESCE(PRIM_OPEN_DEP, '' ) AS PRIM_OPEN_DEP ,
  COALESCE(PRIM_AST_ACCT, '' ) AS PRIM_AST_ACCT ,
  COALESCE(PRIM_ACCT_NAME, '' ) AS PRIM_ACCT_NAME ,
  COALESCE(PAY_PRIM_ACCT_TYP, '' ) AS PAY_PRIM_ACCT_TYP ,
  COALESCE(PAY_PRIM_ACCT_FLG, '' ) AS PAY_PRIM_ACCT_FLG ,
  COALESCE(PAY_PRIM_ACCT, '' ) AS PAY_PRIM_ACCT ,
  COALESCE(PAY_OPEN_DEP, '' ) AS PAY_OPEN_DEP ,
  COALESCE(PAY_PRIM_NAME, '' ) AS PAY_PRIM_NAME ,
  COALESCE(DISC_TYPE, '' ) AS DISC_TYPE ,
  COALESCE(DISC_STOP_FLG, '' ) AS DISC_STOP_FLG ,
  COALESCE(DISC_END_DATE, '' ) AS DISC_END_DATE ,
  COALESCE(DISC_ADV_EXP_AMT, 0 ) AS DISC_ADV_EXP_AMT ,
  COALESCE(DISC_ADV_AMT, 0 ) AS DISC_ADV_AMT ,
  COALESCE(DISC_SUBD_EXP_AMT, 0 ) AS DISC_SUBD_EXP_AMT ,
  COALESCE(DISC_SUBD_AMT, 0 ) AS DISC_SUBD_AMT ,
  COALESCE(ITR_CAL_RULE, '' ) AS ITR_CAL_RULE ,
  COALESCE(FORW_PROV_DATE, '' ) AS FORW_PROV_DATE ,
  COALESCE(NEXT_PROV_DATE, '' ) AS NEXT_PROV_DATE ,
  COALESCE(ITR_FRE_FLG, '' ) AS ITR_FRE_FLG ,
  COALESCE(ITR_FRE_CYL, 0 ) AS ITR_FRE_CYL ,
  COALESCE(CEAS_FLG, '' ) AS CEAS_FLG ,
  COALESCE(CEAS_DATE, '' ) AS CEAS_DATE ,
  COALESCE(ITR_FRE_TERM, 0 ) AS ITR_FRE_TERM ,
  COALESCE(OVER_DATE, '' ) AS OVER_DATE ,
  COALESCE(CLASSIFY_FLG, '' ) AS CLASSIFY_FLG ,
  COALESCE(DEVA_STS, '' ) AS DEVA_STS ,
  COALESCE(DEVA_DATE, '' ) AS DEVA_DATE ,
  COALESCE(CLOSE_DATE, '' ) AS CLOSE_DATE ,
  COALESCE(STG_FIRST_MON, 0 ) AS STG_FIRST_MON ,
  COALESCE(STG_FIRST_DATE, '' ) AS STG_FIRST_DATE ,
  COALESCE(STUD_PERD, '' ) AS STUD_PERD ,
  COALESCE(BALL_MTH_END_PERD, '' ) AS BALL_MTH_END_PERD ,
  COALESCE(FRE_PAY_METH_DAY, 0 ) AS FRE_PAY_METH_DAY ,
  COALESCE(FRE_PAY_METH_PAY_AMT, 0 ) AS FRE_PAY_METH_PAY_AMT ,
  COALESCE(PRN_SETT_ACC, '' ) AS PRN_SETT_ACC ,
  COALESCE(PRN_SETT_ACC_NAME, '' ) AS PRN_SETT_ACC_NAME ,
  COALESCE(PRN_SETT_ACC_TYP, '' ) AS PRN_SETT_ACC_TYP ,
  COALESCE(ITR_SETT_ACC, '' ) AS ITR_SETT_ACC ,
  COALESCE(ITR_SETT_ACC_NAME, '' ) AS ITR_SETT_ACC_NAME ,
  COALESCE(ITR_SETT_ACC_TYP, '' ) AS ITR_SETT_ACC_TYP ,
  COALESCE(AGY_BUS_ACC, '' ) AS AGY_BUS_ACC ,
  COALESCE(AGY_BUS_ACC_NAME, '' ) AS AGY_BUS_ACC_NAME ,
  COALESCE(AGY_BUS_ACC_DEP, '' ) AS AGY_BUS_ACC_DEP ,
  COALESCE(AGY_BUS_ITR_ACC, '' ) AS AGY_BUS_ITR_ACC ,
  COALESCE(AGY_BUS_ITR_ACC_NAME, '' ) AS AGY_BUS_ITR_ACC_NAME ,
  COALESCE(AGY_BUS_ITR_ACC_DEP, '' ) AS AGY_BUS_ITR_ACC_DEP ,
  COALESCE(AGY_BUS_NUM, '' ) AS AGY_BUS_NUM ,
  COALESCE(AGY_BUS_PROP, 0 ) AS AGY_BUS_PROP ,
  COALESCE(HOLIDAY_FLG, '' ) AS HOLIDAY_FLG ,
  COALESCE(PRE_ITR_AMT, 0 ) AS PRE_ITR_AMT ,
  COALESCE(PROVD_FUND_ACC, '' ) AS PROVD_FUND_ACC ,
  COALESCE(PROVD_FUND_ACC_DEP, '' ) AS PROVD_FUND_ACC_DEP ,
  COALESCE(BAT_FLG, '' ) AS BAT_FLG ,
  COALESCE(RECALL_FLG, '' ) AS RECALL_FLG ,
  COALESCE(COUNTER_FLG, '' ) AS COUNTER_FLG ,
  COALESCE(LAST_DATE, '' ) AS LAST_DATE ,
  COALESCE(LAST_STAN, 0 ) AS LAST_STAN ,
  COALESCE(CHG_PAY_DAY_FLG, '' ) AS CHG_PAY_DAY_FLG ,
  COALESCE(CON_PERI_NUM, 0 ) AS CON_PERI_NUM ,
  COALESCE(NUM_BASE_PERI, 0 ) AS NUM_BASE_PERI ,
  COALESCE(BASE_AMT, 0 ) AS BASE_AMT ,
  COALESCE(CURR_PERI, 0 ) AS CURR_PERI ,
  COALESCE(EFF_CURR_PERI, 0 ) AS EFF_CURR_PERI ,
  COALESCE(BEG_TERM, 0 ) AS BEG_TERM ,
  COALESCE(CHG_TERM, 0 ) AS CHG_TERM ,
  COALESCE(ADD_AMT, 0 ) AS ADD_AMT ,
  COALESCE(PROP, 0 ) AS PROP ,
  COALESCE(BRU_NUM, '' ) AS BRU_NUM ,
  COALESCE(BRU_NUM_SND, '' ) AS BRU_NUM_SND ,
  COALESCE(ACC_OTD_DATE, '' ) AS ACC_OTD_DATE ,
  COALESCE(RMK1, '' ) AS RMK1 ,
  COALESCE(RMK2, '' ) AS RMK2 ,
  COALESCE(RMK3, '' ) AS RMK3 ,
  COALESCE(RMK4, '' ) AS RMK4 ,
  COALESCE(RMK1_BAL, 0 ) AS RMK1_BAL ,
  COALESCE(RMK2_BAL, 0 ) AS RMK2_BAL ,
  COALESCE(RMK3_BAL, 0 ) AS RMK3_BAL 
 FROM  dw_tdata.PCS_005_TB_SUP_LOAN_INFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PRV_COD ,
  RLS_DEP ,
  OPN_DEP ,
  TAL_DEP ,
  DUE_NUM ,
  TRAN_FROM ,
  CRD_CENT ,
  CERT_TYPE ,
  CERT_NUM ,
  CUS_NO ,
  CON_NO ,
  DUE_NUM_SUN ,
  BRW_NAME ,
  AMT ,
  BEG_DATE ,
  END_DATE ,
  BEG_ITR_DATE ,
  BEG_PLAN_DATE ,
  STS ,
  CURR_COD ,
  PRM_CLS ,
  AST_CLS ,
  BUS_COD ,
  CASPAN ,
  PRM_PAY_TYP ,
  AST_PAY_TYP ,
  SPEC_PAYMENT_DATE ,
  DIST_DAYS ,
  ITR_RATE_WAY ,
  NOR_ITR_RATE ,
  DEL_ITR_RATE ,
  REL_ITR_RATE ,
  PRIM_ACCT_TYP ,
  PRIM_ACCT_FLG ,
  PRIM_ACCT ,
  PRIM_OPEN_DEP ,
  PRIM_AST_ACCT ,
  PRIM_ACCT_NAME ,
  PAY_PRIM_ACCT_TYP ,
  PAY_PRIM_ACCT_FLG ,
  PAY_PRIM_ACCT ,
  PAY_OPEN_DEP ,
  PAY_PRIM_NAME ,
  DISC_TYPE ,
  DISC_STOP_FLG ,
  DISC_END_DATE ,
  DISC_ADV_EXP_AMT ,
  DISC_ADV_AMT ,
  DISC_SUBD_EXP_AMT ,
  DISC_SUBD_AMT ,
  ITR_CAL_RULE ,
  FORW_PROV_DATE ,
  NEXT_PROV_DATE ,
  ITR_FRE_FLG ,
  ITR_FRE_CYL ,
  CEAS_FLG ,
  CEAS_DATE ,
  ITR_FRE_TERM ,
  OVER_DATE ,
  CLASSIFY_FLG ,
  DEVA_STS ,
  DEVA_DATE ,
  CLOSE_DATE ,
  STG_FIRST_MON ,
  STG_FIRST_DATE ,
  STUD_PERD ,
  BALL_MTH_END_PERD ,
  FRE_PAY_METH_DAY ,
  FRE_PAY_METH_PAY_AMT ,
  PRN_SETT_ACC ,
  PRN_SETT_ACC_NAME ,
  PRN_SETT_ACC_TYP ,
  ITR_SETT_ACC ,
  ITR_SETT_ACC_NAME ,
  ITR_SETT_ACC_TYP ,
  AGY_BUS_ACC ,
  AGY_BUS_ACC_NAME ,
  AGY_BUS_ACC_DEP ,
  AGY_BUS_ITR_ACC ,
  AGY_BUS_ITR_ACC_NAME ,
  AGY_BUS_ITR_ACC_DEP ,
  AGY_BUS_NUM ,
  AGY_BUS_PROP ,
  HOLIDAY_FLG ,
  PRE_ITR_AMT ,
  PROVD_FUND_ACC ,
  PROVD_FUND_ACC_DEP ,
  BAT_FLG ,
  RECALL_FLG ,
  COUNTER_FLG ,
  LAST_DATE ,
  LAST_STAN ,
  CHG_PAY_DAY_FLG ,
  CON_PERI_NUM ,
  NUM_BASE_PERI ,
  BASE_AMT ,
  CURR_PERI ,
  EFF_CURR_PERI ,
  BEG_TERM ,
  CHG_TERM ,
  ADD_AMT ,
  PROP ,
  BRU_NUM ,
  BRU_NUM_SND ,
  ACC_OTD_DATE ,
  RMK1 ,
  RMK2 ,
  RMK3 ,
  RMK4 ,
  RMK1_BAL ,
  RMK2_BAL ,
  RMK3_BAL 
 FROM dw_sdata.PCS_005_TB_SUP_LOAN_INFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.DUE_NUM = T.DUE_NUM
WHERE
(T.DUE_NUM IS NULL)
 OR N.PRV_COD<>T.PRV_COD
 OR N.RLS_DEP<>T.RLS_DEP
 OR N.OPN_DEP<>T.OPN_DEP
 OR N.TAL_DEP<>T.TAL_DEP
 OR N.TRAN_FROM<>T.TRAN_FROM
 OR N.CRD_CENT<>T.CRD_CENT
 OR N.CERT_TYPE<>T.CERT_TYPE
 OR N.CERT_NUM<>T.CERT_NUM
 OR N.CUS_NO<>T.CUS_NO
 OR N.CON_NO<>T.CON_NO
 OR N.DUE_NUM_SUN<>T.DUE_NUM_SUN
 OR N.BRW_NAME<>T.BRW_NAME
 OR N.AMT<>T.AMT
 OR N.BEG_DATE<>T.BEG_DATE
 OR N.END_DATE<>T.END_DATE
 OR N.BEG_ITR_DATE<>T.BEG_ITR_DATE
 OR N.BEG_PLAN_DATE<>T.BEG_PLAN_DATE
 OR N.STS<>T.STS
 OR N.CURR_COD<>T.CURR_COD
 OR N.PRM_CLS<>T.PRM_CLS
 OR N.AST_CLS<>T.AST_CLS
 OR N.BUS_COD<>T.BUS_COD
 OR N.CASPAN<>T.CASPAN
 OR N.PRM_PAY_TYP<>T.PRM_PAY_TYP
 OR N.AST_PAY_TYP<>T.AST_PAY_TYP
 OR N.SPEC_PAYMENT_DATE<>T.SPEC_PAYMENT_DATE
 OR N.DIST_DAYS<>T.DIST_DAYS
 OR N.ITR_RATE_WAY<>T.ITR_RATE_WAY
 OR N.NOR_ITR_RATE<>T.NOR_ITR_RATE
 OR N.DEL_ITR_RATE<>T.DEL_ITR_RATE
 OR N.REL_ITR_RATE<>T.REL_ITR_RATE
 OR N.PRIM_ACCT_TYP<>T.PRIM_ACCT_TYP
 OR N.PRIM_ACCT_FLG<>T.PRIM_ACCT_FLG
 OR N.PRIM_ACCT<>T.PRIM_ACCT
 OR N.PRIM_OPEN_DEP<>T.PRIM_OPEN_DEP
 OR N.PRIM_AST_ACCT<>T.PRIM_AST_ACCT
 OR N.PRIM_ACCT_NAME<>T.PRIM_ACCT_NAME
 OR N.PAY_PRIM_ACCT_TYP<>T.PAY_PRIM_ACCT_TYP
 OR N.PAY_PRIM_ACCT_FLG<>T.PAY_PRIM_ACCT_FLG
 OR N.PAY_PRIM_ACCT<>T.PAY_PRIM_ACCT
 OR N.PAY_OPEN_DEP<>T.PAY_OPEN_DEP
 OR N.PAY_PRIM_NAME<>T.PAY_PRIM_NAME
 OR N.DISC_TYPE<>T.DISC_TYPE
 OR N.DISC_STOP_FLG<>T.DISC_STOP_FLG
 OR N.DISC_END_DATE<>T.DISC_END_DATE
 OR N.DISC_ADV_EXP_AMT<>T.DISC_ADV_EXP_AMT
 OR N.DISC_ADV_AMT<>T.DISC_ADV_AMT
 OR N.DISC_SUBD_EXP_AMT<>T.DISC_SUBD_EXP_AMT
 OR N.DISC_SUBD_AMT<>T.DISC_SUBD_AMT
 OR N.ITR_CAL_RULE<>T.ITR_CAL_RULE
 OR N.FORW_PROV_DATE<>T.FORW_PROV_DATE
 OR N.NEXT_PROV_DATE<>T.NEXT_PROV_DATE
 OR N.ITR_FRE_FLG<>T.ITR_FRE_FLG
 OR N.ITR_FRE_CYL<>T.ITR_FRE_CYL
 OR N.CEAS_FLG<>T.CEAS_FLG
 OR N.CEAS_DATE<>T.CEAS_DATE
 OR N.ITR_FRE_TERM<>T.ITR_FRE_TERM
 OR N.OVER_DATE<>T.OVER_DATE
 OR N.CLASSIFY_FLG<>T.CLASSIFY_FLG
 OR N.DEVA_STS<>T.DEVA_STS
 OR N.DEVA_DATE<>T.DEVA_DATE
 OR N.CLOSE_DATE<>T.CLOSE_DATE
 OR N.STG_FIRST_MON<>T.STG_FIRST_MON
 OR N.STG_FIRST_DATE<>T.STG_FIRST_DATE
 OR N.STUD_PERD<>T.STUD_PERD
 OR N.BALL_MTH_END_PERD<>T.BALL_MTH_END_PERD
 OR N.FRE_PAY_METH_DAY<>T.FRE_PAY_METH_DAY
 OR N.FRE_PAY_METH_PAY_AMT<>T.FRE_PAY_METH_PAY_AMT
 OR N.PRN_SETT_ACC<>T.PRN_SETT_ACC
 OR N.PRN_SETT_ACC_NAME<>T.PRN_SETT_ACC_NAME
 OR N.PRN_SETT_ACC_TYP<>T.PRN_SETT_ACC_TYP
 OR N.ITR_SETT_ACC<>T.ITR_SETT_ACC
 OR N.ITR_SETT_ACC_NAME<>T.ITR_SETT_ACC_NAME
 OR N.ITR_SETT_ACC_TYP<>T.ITR_SETT_ACC_TYP
 OR N.AGY_BUS_ACC<>T.AGY_BUS_ACC
 OR N.AGY_BUS_ACC_NAME<>T.AGY_BUS_ACC_NAME
 OR N.AGY_BUS_ACC_DEP<>T.AGY_BUS_ACC_DEP
 OR N.AGY_BUS_ITR_ACC<>T.AGY_BUS_ITR_ACC
 OR N.AGY_BUS_ITR_ACC_NAME<>T.AGY_BUS_ITR_ACC_NAME
 OR N.AGY_BUS_ITR_ACC_DEP<>T.AGY_BUS_ITR_ACC_DEP
 OR N.AGY_BUS_NUM<>T.AGY_BUS_NUM
 OR N.AGY_BUS_PROP<>T.AGY_BUS_PROP
 OR N.HOLIDAY_FLG<>T.HOLIDAY_FLG
 OR N.PRE_ITR_AMT<>T.PRE_ITR_AMT
 OR N.PROVD_FUND_ACC<>T.PROVD_FUND_ACC
 OR N.PROVD_FUND_ACC_DEP<>T.PROVD_FUND_ACC_DEP
 OR N.BAT_FLG<>T.BAT_FLG
 OR N.RECALL_FLG<>T.RECALL_FLG
 OR N.COUNTER_FLG<>T.COUNTER_FLG
 OR N.LAST_DATE<>T.LAST_DATE
 OR N.LAST_STAN<>T.LAST_STAN
 OR N.CHG_PAY_DAY_FLG<>T.CHG_PAY_DAY_FLG
 OR N.CON_PERI_NUM<>T.CON_PERI_NUM
 OR N.NUM_BASE_PERI<>T.NUM_BASE_PERI
 OR N.BASE_AMT<>T.BASE_AMT
 OR N.CURR_PERI<>T.CURR_PERI
 OR N.EFF_CURR_PERI<>T.EFF_CURR_PERI
 OR N.BEG_TERM<>T.BEG_TERM
 OR N.CHG_TERM<>T.CHG_TERM
 OR N.ADD_AMT<>T.ADD_AMT
 OR N.PROP<>T.PROP
 OR N.BRU_NUM<>T.BRU_NUM
 OR N.BRU_NUM_SND<>T.BRU_NUM_SND
 OR N.ACC_OTD_DATE<>T.ACC_OTD_DATE
 OR N.RMK1<>T.RMK1
 OR N.RMK2<>T.RMK2
 OR N.RMK3<>T.RMK3
 OR N.RMK4<>T.RMK4
 OR N.RMK1_BAL<>T.RMK1_BAL
 OR N.RMK2_BAL<>T.RMK2_BAL
 OR N.RMK3_BAL<>T.RMK3_BAL
;

--Step3:
UPDATE dw_sdata.PCS_005_TB_SUP_LOAN_INFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_320
WHERE P.End_Dt=DATE('2100-12-31')
AND P.DUE_NUM=T_320.DUE_NUM
;

--Step4:
INSERT  INTO dw_sdata.PCS_005_TB_SUP_LOAN_INFO SELECT * FROM T_320;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
