#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ACC_003_T_ACC_INN_LEDGER WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ACC_003_T_ACC_INN_LEDGER SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_21 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ACC_003_T_ACC_INN_LEDGER WHERE 1=0;

--Step2:
INSERT  INTO T_21 (
  INN_ACC,
  ACC_NAME,
  OP_INST,
  ACC_INST,
  CURR_TYPE,
  ACC_INDEX,
  DR_BAL,
  CR_BAL,
  DR_NUM_BAL,
  CR_NUM_BAL,
  LST_BAL,
  LST_TRAN_DATE,
  ITM_NO,
  ACC_TYPE,
  INT_FLAG,
  INT_WAY_FLAG,
  BGN_INT_DATE,
  INT_DATE_FLAG,
  PROVISION_CYCLE,
  PROVISION_DATE,
  INT_TYPE,
  INT_CYCLE,
  INT_DATE,
  PAY_INT_TYPE,
  PAY_INT_ACC,
  RATE_FLAG,
  NOM_RATE1,
  NOM_RATE2,
  NOM_RATE3,
  NOM_RATE4,
  NOM_RATE5,
  NOM_RATE_NO1,
  NOM_RATE_NO2,
  NOM_RATE_NO3,
  NOM_RATE_NO4,
  NOM_RATE_NO5,
  RATE_RANGE1,
  RATE_RANGE2,
  RATE_RANGE3,
  RATE_RANGE4,
  RATE_RANGE5,
  INT_SEC_FLAG,
  INT_SEC_RATION1,
  INT_SEC_RATION2,
  INT_SEC_RATION3,
  INT_SEC_RATION4,
  DEADLINE,
  OP_DATE,
  START_DATE,
  DUE_DATE,
  CLS_DATE,
  OVDF_FLAG,
  OVDF_RATE1,
  OVDF_RATE2,
  OVDF_DATE_LIMIT,
  OVDF_RATE_NO1,
  OVDF_RATE_NO2,
  OVDF_RATE_FLAG,
  FUND_UP_LIMIT,
  FUND_DOWN_LIMIT,
  OUT_ACC_FLAG,
  HOLIDAY_FLAG,
  AVAL_BAL_FLAG,
  OPEN_DRV_TYPE,
  BANKACC_FLAG,
  SAVEINT_UP_LIMIT,
  SAVEINT_DOWN_LIMIT,
  STAT,
  SYS_CODE,
  ACC_SET,
  EXPAND_1,
  EXPAND_2,
  EXPAND_3,
  EXPAND_4,
  EXPAND_5,
  start_dt,
  end_dt)
SELECT
  N.INN_ACC,
  N.ACC_NAME,
  N.OP_INST,
  N.ACC_INST,
  N.CURR_TYPE,
  N.ACC_INDEX,
  N.DR_BAL,
  N.CR_BAL,
  N.DR_NUM_BAL,
  N.CR_NUM_BAL,
  N.LST_BAL,
  N.LST_TRAN_DATE,
  N.ITM_NO,
  N.ACC_TYPE,
  N.INT_FLAG,
  N.INT_WAY_FLAG,
  N.BGN_INT_DATE,
  N.INT_DATE_FLAG,
  N.PROVISION_CYCLE,
  N.PROVISION_DATE,
  N.INT_TYPE,
  N.INT_CYCLE,
  N.INT_DATE,
  N.PAY_INT_TYPE,
  N.PAY_INT_ACC,
  N.RATE_FLAG,
  N.NOM_RATE1,
  N.NOM_RATE2,
  N.NOM_RATE3,
  N.NOM_RATE4,
  N.NOM_RATE5,
  N.NOM_RATE_NO1,
  N.NOM_RATE_NO2,
  N.NOM_RATE_NO3,
  N.NOM_RATE_NO4,
  N.NOM_RATE_NO5,
  N.RATE_RANGE1,
  N.RATE_RANGE2,
  N.RATE_RANGE3,
  N.RATE_RANGE4,
  N.RATE_RANGE5,
  N.INT_SEC_FLAG,
  N.INT_SEC_RATION1,
  N.INT_SEC_RATION2,
  N.INT_SEC_RATION3,
  N.INT_SEC_RATION4,
  N.DEADLINE,
  N.OP_DATE,
  N.START_DATE,
  N.DUE_DATE,
  N.CLS_DATE,
  N.OVDF_FLAG,
  N.OVDF_RATE1,
  N.OVDF_RATE2,
  N.OVDF_DATE_LIMIT,
  N.OVDF_RATE_NO1,
  N.OVDF_RATE_NO2,
  N.OVDF_RATE_FLAG,
  N.FUND_UP_LIMIT,
  N.FUND_DOWN_LIMIT,
  N.OUT_ACC_FLAG,
  N.HOLIDAY_FLAG,
  N.AVAL_BAL_FLAG,
  N.OPEN_DRV_TYPE,
  N.BANKACC_FLAG,
  N.SAVEINT_UP_LIMIT,
  N.SAVEINT_DOWN_LIMIT,
  N.STAT,
  N.SYS_CODE,
  N.ACC_SET,
  N.EXPAND_1,
  N.EXPAND_2,
  N.EXPAND_3,
  N.EXPAND_4,
  N.EXPAND_5,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(INN_ACC, '' ) AS INN_ACC ,
  COALESCE(ACC_NAME, '' ) AS ACC_NAME ,
  COALESCE(OP_INST, '' ) AS OP_INST ,
  COALESCE(ACC_INST, '' ) AS ACC_INST ,
  COALESCE(CURR_TYPE, '' ) AS CURR_TYPE ,
  COALESCE(ACC_INDEX, '' ) AS ACC_INDEX ,
  COALESCE(DR_BAL, 0 ) AS DR_BAL ,
  COALESCE(CR_BAL, 0 ) AS CR_BAL ,
  COALESCE(DR_NUM_BAL, 0 ) AS DR_NUM_BAL ,
  COALESCE(CR_NUM_BAL, 0 ) AS CR_NUM_BAL ,
  COALESCE(LST_BAL, 0 ) AS LST_BAL ,
  COALESCE(LST_TRAN_DATE, '' ) AS LST_TRAN_DATE ,
  COALESCE(ITM_NO, '' ) AS ITM_NO ,
  COALESCE(ACC_TYPE, '' ) AS ACC_TYPE ,
  COALESCE(INT_FLAG, '' ) AS INT_FLAG ,
  COALESCE(INT_WAY_FLAG, '' ) AS INT_WAY_FLAG ,
  COALESCE(BGN_INT_DATE, '' ) AS BGN_INT_DATE ,
  COALESCE(INT_DATE_FLAG, '' ) AS INT_DATE_FLAG ,
  COALESCE(PROVISION_CYCLE, '' ) AS PROVISION_CYCLE ,
  COALESCE(PROVISION_DATE, '' ) AS PROVISION_DATE ,
  COALESCE(INT_TYPE, '' ) AS INT_TYPE ,
  COALESCE(INT_CYCLE, '' ) AS INT_CYCLE ,
  COALESCE(INT_DATE, '' ) AS INT_DATE ,
  COALESCE(PAY_INT_TYPE, '' ) AS PAY_INT_TYPE ,
  COALESCE(PAY_INT_ACC, '' ) AS PAY_INT_ACC ,
  COALESCE(RATE_FLAG, '' ) AS RATE_FLAG ,
  COALESCE(NOM_RATE1, 0 ) AS NOM_RATE1 ,
  COALESCE(NOM_RATE2, 0 ) AS NOM_RATE2 ,
  COALESCE(NOM_RATE3, 0 ) AS NOM_RATE3 ,
  COALESCE(NOM_RATE4, 0 ) AS NOM_RATE4 ,
  COALESCE(NOM_RATE5, 0 ) AS NOM_RATE5 ,
  COALESCE(NOM_RATE_NO1, '' ) AS NOM_RATE_NO1 ,
  COALESCE(NOM_RATE_NO2, '' ) AS NOM_RATE_NO2 ,
  COALESCE(NOM_RATE_NO3, '' ) AS NOM_RATE_NO3 ,
  COALESCE(NOM_RATE_NO4, '' ) AS NOM_RATE_NO4 ,
  COALESCE(NOM_RATE_NO5, '' ) AS NOM_RATE_NO5 ,
  COALESCE(RATE_RANGE1, 0 ) AS RATE_RANGE1 ,
  COALESCE(RATE_RANGE2, 0 ) AS RATE_RANGE2 ,
  COALESCE(RATE_RANGE3, 0 ) AS RATE_RANGE3 ,
  COALESCE(RATE_RANGE4, 0 ) AS RATE_RANGE4 ,
  COALESCE(RATE_RANGE5, 0 ) AS RATE_RANGE5 ,
  COALESCE(INT_SEC_FLAG, '' ) AS INT_SEC_FLAG ,
  COALESCE(INT_SEC_RATION1, 0 ) AS INT_SEC_RATION1 ,
  COALESCE(INT_SEC_RATION2, 0 ) AS INT_SEC_RATION2 ,
  COALESCE(INT_SEC_RATION3, 0 ) AS INT_SEC_RATION3 ,
  COALESCE(INT_SEC_RATION4, 0 ) AS INT_SEC_RATION4 ,
  COALESCE(DEADLINE, '' ) AS DEADLINE ,
  COALESCE(OP_DATE, '' ) AS OP_DATE ,
  COALESCE(START_DATE, '' ) AS START_DATE ,
  COALESCE(DUE_DATE, '' ) AS DUE_DATE ,
  COALESCE(CLS_DATE, '' ) AS CLS_DATE ,
  COALESCE(OVDF_FLAG, '' ) AS OVDF_FLAG ,
  COALESCE(OVDF_RATE1, 0 ) AS OVDF_RATE1 ,
  COALESCE(OVDF_RATE2, 0 ) AS OVDF_RATE2 ,
  COALESCE(OVDF_DATE_LIMIT, 0 ) AS OVDF_DATE_LIMIT ,
  COALESCE(OVDF_RATE_NO1, '' ) AS OVDF_RATE_NO1 ,
  COALESCE(OVDF_RATE_NO2, '' ) AS OVDF_RATE_NO2 ,
  COALESCE(OVDF_RATE_FLAG, '' ) AS OVDF_RATE_FLAG ,
  COALESCE(FUND_UP_LIMIT, 0 ) AS FUND_UP_LIMIT ,
  COALESCE(FUND_DOWN_LIMIT, 0 ) AS FUND_DOWN_LIMIT ,
  COALESCE(OUT_ACC_FLAG, '' ) AS OUT_ACC_FLAG ,
  COALESCE(HOLIDAY_FLAG, '' ) AS HOLIDAY_FLAG ,
  COALESCE(AVAL_BAL_FLAG, '' ) AS AVAL_BAL_FLAG ,
  COALESCE(OPEN_DRV_TYPE, '' ) AS OPEN_DRV_TYPE ,
  COALESCE(BANKACC_FLAG, '' ) AS BANKACC_FLAG ,
  COALESCE(SAVEINT_UP_LIMIT, 0 ) AS SAVEINT_UP_LIMIT ,
  COALESCE(SAVEINT_DOWN_LIMIT, 0 ) AS SAVEINT_DOWN_LIMIT ,
  COALESCE(STAT, '' ) AS STAT ,
  COALESCE(SYS_CODE, '' ) AS SYS_CODE ,
  COALESCE(ACC_SET, '' ) AS ACC_SET ,
  COALESCE(EXPAND_1, '' ) AS EXPAND_1 ,
  COALESCE(EXPAND_2, '' ) AS EXPAND_2 ,
  COALESCE(EXPAND_3, '' ) AS EXPAND_3 ,
  COALESCE(EXPAND_4, '' ) AS EXPAND_4 ,
  COALESCE(EXPAND_5, 0 ) AS EXPAND_5 
 FROM  dw_tdata.ACC_003_T_ACC_INN_LEDGER_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  INN_ACC ,
  ACC_NAME ,
  OP_INST ,
  ACC_INST ,
  CURR_TYPE ,
  ACC_INDEX ,
  DR_BAL ,
  CR_BAL ,
  DR_NUM_BAL ,
  CR_NUM_BAL ,
  LST_BAL ,
  LST_TRAN_DATE ,
  ITM_NO ,
  ACC_TYPE ,
  INT_FLAG ,
  INT_WAY_FLAG ,
  BGN_INT_DATE ,
  INT_DATE_FLAG ,
  PROVISION_CYCLE ,
  PROVISION_DATE ,
  INT_TYPE ,
  INT_CYCLE ,
  INT_DATE ,
  PAY_INT_TYPE ,
  PAY_INT_ACC ,
  RATE_FLAG ,
  NOM_RATE1 ,
  NOM_RATE2 ,
  NOM_RATE3 ,
  NOM_RATE4 ,
  NOM_RATE5 ,
  NOM_RATE_NO1 ,
  NOM_RATE_NO2 ,
  NOM_RATE_NO3 ,
  NOM_RATE_NO4 ,
  NOM_RATE_NO5 ,
  RATE_RANGE1 ,
  RATE_RANGE2 ,
  RATE_RANGE3 ,
  RATE_RANGE4 ,
  RATE_RANGE5 ,
  INT_SEC_FLAG ,
  INT_SEC_RATION1 ,
  INT_SEC_RATION2 ,
  INT_SEC_RATION3 ,
  INT_SEC_RATION4 ,
  DEADLINE ,
  OP_DATE ,
  START_DATE ,
  DUE_DATE ,
  CLS_DATE ,
  OVDF_FLAG ,
  OVDF_RATE1 ,
  OVDF_RATE2 ,
  OVDF_DATE_LIMIT ,
  OVDF_RATE_NO1 ,
  OVDF_RATE_NO2 ,
  OVDF_RATE_FLAG ,
  FUND_UP_LIMIT ,
  FUND_DOWN_LIMIT ,
  OUT_ACC_FLAG ,
  HOLIDAY_FLAG ,
  AVAL_BAL_FLAG ,
  OPEN_DRV_TYPE ,
  BANKACC_FLAG ,
  SAVEINT_UP_LIMIT ,
  SAVEINT_DOWN_LIMIT ,
  STAT ,
  SYS_CODE ,
  ACC_SET ,
  EXPAND_1 ,
  EXPAND_2 ,
  EXPAND_3 ,
  EXPAND_4 ,
  EXPAND_5 
 FROM dw_sdata.ACC_003_T_ACC_INN_LEDGER 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.INN_ACC = T.INN_ACC AND N.SYS_CODE = T.SYS_CODE
WHERE
(T.INN_ACC IS NULL AND T.SYS_CODE IS NULL)
 OR N.ACC_NAME<>T.ACC_NAME
 OR N.OP_INST<>T.OP_INST
 OR N.ACC_INST<>T.ACC_INST
 OR N.CURR_TYPE<>T.CURR_TYPE
 OR N.ACC_INDEX<>T.ACC_INDEX
 OR N.DR_BAL<>T.DR_BAL
 OR N.CR_BAL<>T.CR_BAL
 OR N.DR_NUM_BAL<>T.DR_NUM_BAL
 OR N.CR_NUM_BAL<>T.CR_NUM_BAL
 OR N.LST_BAL<>T.LST_BAL
 OR N.LST_TRAN_DATE<>T.LST_TRAN_DATE
 OR N.ITM_NO<>T.ITM_NO
 OR N.ACC_TYPE<>T.ACC_TYPE
 OR N.INT_FLAG<>T.INT_FLAG
 OR N.INT_WAY_FLAG<>T.INT_WAY_FLAG
 OR N.BGN_INT_DATE<>T.BGN_INT_DATE
 OR N.INT_DATE_FLAG<>T.INT_DATE_FLAG
 OR N.PROVISION_CYCLE<>T.PROVISION_CYCLE
 OR N.PROVISION_DATE<>T.PROVISION_DATE
 OR N.INT_TYPE<>T.INT_TYPE
 OR N.INT_CYCLE<>T.INT_CYCLE
 OR N.INT_DATE<>T.INT_DATE
 OR N.PAY_INT_TYPE<>T.PAY_INT_TYPE
 OR N.PAY_INT_ACC<>T.PAY_INT_ACC
 OR N.RATE_FLAG<>T.RATE_FLAG
 OR N.NOM_RATE1<>T.NOM_RATE1
 OR N.NOM_RATE2<>T.NOM_RATE2
 OR N.NOM_RATE3<>T.NOM_RATE3
 OR N.NOM_RATE4<>T.NOM_RATE4
 OR N.NOM_RATE5<>T.NOM_RATE5
 OR N.NOM_RATE_NO1<>T.NOM_RATE_NO1
 OR N.NOM_RATE_NO2<>T.NOM_RATE_NO2
 OR N.NOM_RATE_NO3<>T.NOM_RATE_NO3
 OR N.NOM_RATE_NO4<>T.NOM_RATE_NO4
 OR N.NOM_RATE_NO5<>T.NOM_RATE_NO5
 OR N.RATE_RANGE1<>T.RATE_RANGE1
 OR N.RATE_RANGE2<>T.RATE_RANGE2
 OR N.RATE_RANGE3<>T.RATE_RANGE3
 OR N.RATE_RANGE4<>T.RATE_RANGE4
 OR N.RATE_RANGE5<>T.RATE_RANGE5
 OR N.INT_SEC_FLAG<>T.INT_SEC_FLAG
 OR N.INT_SEC_RATION1<>T.INT_SEC_RATION1
 OR N.INT_SEC_RATION2<>T.INT_SEC_RATION2
 OR N.INT_SEC_RATION3<>T.INT_SEC_RATION3
 OR N.INT_SEC_RATION4<>T.INT_SEC_RATION4
 OR N.DEADLINE<>T.DEADLINE
 OR N.OP_DATE<>T.OP_DATE
 OR N.START_DATE<>T.START_DATE
 OR N.DUE_DATE<>T.DUE_DATE
 OR N.CLS_DATE<>T.CLS_DATE
 OR N.OVDF_FLAG<>T.OVDF_FLAG
 OR N.OVDF_RATE1<>T.OVDF_RATE1
 OR N.OVDF_RATE2<>T.OVDF_RATE2
 OR N.OVDF_DATE_LIMIT<>T.OVDF_DATE_LIMIT
 OR N.OVDF_RATE_NO1<>T.OVDF_RATE_NO1
 OR N.OVDF_RATE_NO2<>T.OVDF_RATE_NO2
 OR N.OVDF_RATE_FLAG<>T.OVDF_RATE_FLAG
 OR N.FUND_UP_LIMIT<>T.FUND_UP_LIMIT
 OR N.FUND_DOWN_LIMIT<>T.FUND_DOWN_LIMIT
 OR N.OUT_ACC_FLAG<>T.OUT_ACC_FLAG
 OR N.HOLIDAY_FLAG<>T.HOLIDAY_FLAG
 OR N.AVAL_BAL_FLAG<>T.AVAL_BAL_FLAG
 OR N.OPEN_DRV_TYPE<>T.OPEN_DRV_TYPE
 OR N.BANKACC_FLAG<>T.BANKACC_FLAG
 OR N.SAVEINT_UP_LIMIT<>T.SAVEINT_UP_LIMIT
 OR N.SAVEINT_DOWN_LIMIT<>T.SAVEINT_DOWN_LIMIT
 OR N.STAT<>T.STAT
 OR N.ACC_SET<>T.ACC_SET
 OR N.EXPAND_1<>T.EXPAND_1
 OR N.EXPAND_2<>T.EXPAND_2
 OR N.EXPAND_3<>T.EXPAND_3
 OR N.EXPAND_4<>T.EXPAND_4
 OR N.EXPAND_5<>T.EXPAND_5
;

--Step3:
UPDATE dw_sdata.ACC_003_T_ACC_INN_LEDGER P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_21
WHERE P.End_Dt=DATE('2100-12-31')
AND P.INN_ACC=T_21.INN_ACC
AND P.SYS_CODE=T_21.SYS_CODE
;

--Step4:
INSERT  INTO dw_sdata.ACC_003_T_ACC_INN_LEDGER SELECT * FROM T_21;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
