#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.BBS_001_ACCEPT_DUE_PAY WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.BBS_001_ACCEPT_DUE_PAY SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_34 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.BBS_001_ACCEPT_DUE_PAY WHERE 1=0;

--Step2:
INSERT  INTO T_34 (
  ID,
  BRANCH_ID,
  DRAFT_ID,
  ISSE_CURCD,
  ISSE_AMT,
  MESG_TYPE,
  APPLY_DATE,
  OVRDUE_RSN,
  APPLY_CURCD,
  APPLY_AMT,
  STTLM_MK,
  VOC_CNT,
  DRFT_HLDR_ROLE,
  DRFT_HLDR_CMONID,
  DRFT_HLDR_NAME,
  DRFT_HLDR_ACTNO,
  DRFT_HLDR_UBANK,
  DRFT_HLDR_AGCY_UBANK,
  ACCEPT_DATE,
  ACCEPT_CURCD,
  ACCEPT_AMOUNT,
  RETURN_CUSTOMER_NAME,
  CUSTOMER_ACCOUNT,
  RECEIVE_DATE,
  REPLY_DATE,
  OPERATOR_ID,
  REPAY_SIG_MK,
  DISH_CODE,
  DISH_RSN,
  APPSTATUS,
  ACPAY_STATUS,
  ENDST_DATE,
  SIG_MK,
  CM_STATUS,
  CM_ERR_PROCD,
  ACCOUNT_FLAG,
  SWT_BIZ_ID,
  ENTITY_REGSTAT,
  ENTITY_REG_ID,
  APPNO,
  MISC,
  LAST_UPD_OPER_ID,
  LAST_UPD_TIME,
  REQ_REMARK,
  RCV_REMARK,
  ECDS_PRC_MSG,
  REQ_PRXY_PROP_STN,
  RCV_PRXY_SGNTR,
  ACCOUNT_DATE,
  CANCEL_DATE,
  ACTLOG_ID,
  TRF_ID,
  TRF_REF,
  IF_SIGN,
  PAY_MODE,
  SWITCH_OR_BANK_NO,
  SWITCH_CASE_NO,
  OPPONENT_NAME,
  OPPONENT_ACCT,
  TRANSFER_STATUS,
  PRINT_COUNT,
  FLAG_PRINT,
  FLAG_PHOTO,
  FLAG_UPLOAD,
  start_dt,
  end_dt)
SELECT
  N.ID,
  N.BRANCH_ID,
  N.DRAFT_ID,
  N.ISSE_CURCD,
  N.ISSE_AMT,
  N.MESG_TYPE,
  N.APPLY_DATE,
  N.OVRDUE_RSN,
  N.APPLY_CURCD,
  N.APPLY_AMT,
  N.STTLM_MK,
  N.VOC_CNT,
  N.DRFT_HLDR_ROLE,
  N.DRFT_HLDR_CMONID,
  N.DRFT_HLDR_NAME,
  N.DRFT_HLDR_ACTNO,
  N.DRFT_HLDR_UBANK,
  N.DRFT_HLDR_AGCY_UBANK,
  N.ACCEPT_DATE,
  N.ACCEPT_CURCD,
  N.ACCEPT_AMOUNT,
  N.RETURN_CUSTOMER_NAME,
  N.CUSTOMER_ACCOUNT,
  N.RECEIVE_DATE,
  N.REPLY_DATE,
  N.OPERATOR_ID,
  N.REPAY_SIG_MK,
  N.DISH_CODE,
  N.DISH_RSN,
  N.APPSTATUS,
  N.ACPAY_STATUS,
  N.ENDST_DATE,
  N.SIG_MK,
  N.CM_STATUS,
  N.CM_ERR_PROCD,
  N.ACCOUNT_FLAG,
  N.SWT_BIZ_ID,
  N.ENTITY_REGSTAT,
  N.ENTITY_REG_ID,
  N.APPNO,
  N.MISC,
  N.LAST_UPD_OPER_ID,
  N.LAST_UPD_TIME,
  N.REQ_REMARK,
  N.RCV_REMARK,
  N.ECDS_PRC_MSG,
  N.REQ_PRXY_PROP_STN,
  N.RCV_PRXY_SGNTR,
  N.ACCOUNT_DATE,
  N.CANCEL_DATE,
  N.ACTLOG_ID,
  N.TRF_ID,
  N.TRF_REF,
  N.IF_SIGN,
  N.PAY_MODE,
  N.SWITCH_OR_BANK_NO,
  N.SWITCH_CASE_NO,
  N.OPPONENT_NAME,
  N.OPPONENT_ACCT,
  N.TRANSFER_STATUS,
  N.PRINT_COUNT,
  N.FLAG_PRINT,
  N.FLAG_PHOTO,
  N.FLAG_UPLOAD,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ID, 0 ) AS ID ,
  COALESCE(BRANCH_ID, 0 ) AS BRANCH_ID ,
  COALESCE(DRAFT_ID, 0 ) AS DRAFT_ID ,
  COALESCE(ISSE_CURCD, '' ) AS ISSE_CURCD ,
  COALESCE(ISSE_AMT, 0 ) AS ISSE_AMT ,
  COALESCE(MESG_TYPE, '' ) AS MESG_TYPE ,
  COALESCE(APPLY_DATE, '' ) AS APPLY_DATE ,
  COALESCE(OVRDUE_RSN, '' ) AS OVRDUE_RSN ,
  COALESCE(APPLY_CURCD, '' ) AS APPLY_CURCD ,
  COALESCE(APPLY_AMT, 0 ) AS APPLY_AMT ,
  COALESCE(STTLM_MK, '' ) AS STTLM_MK ,
  COALESCE(VOC_CNT, 0 ) AS VOC_CNT ,
  COALESCE(DRFT_HLDR_ROLE, '' ) AS DRFT_HLDR_ROLE ,
  COALESCE(DRFT_HLDR_CMONID, '' ) AS DRFT_HLDR_CMONID ,
  COALESCE(DRFT_HLDR_NAME, '' ) AS DRFT_HLDR_NAME ,
  COALESCE(DRFT_HLDR_ACTNO, '' ) AS DRFT_HLDR_ACTNO ,
  COALESCE(DRFT_HLDR_UBANK, '' ) AS DRFT_HLDR_UBANK ,
  COALESCE(DRFT_HLDR_AGCY_UBANK, '' ) AS DRFT_HLDR_AGCY_UBANK ,
  COALESCE(ACCEPT_DATE, '' ) AS ACCEPT_DATE ,
  COALESCE(ACCEPT_CURCD, '' ) AS ACCEPT_CURCD ,
  COALESCE(ACCEPT_AMOUNT, 0 ) AS ACCEPT_AMOUNT ,
  COALESCE(RETURN_CUSTOMER_NAME, '' ) AS RETURN_CUSTOMER_NAME ,
  COALESCE(CUSTOMER_ACCOUNT, '' ) AS CUSTOMER_ACCOUNT ,
  COALESCE(RECEIVE_DATE, '' ) AS RECEIVE_DATE ,
  COALESCE(REPLY_DATE, '' ) AS REPLY_DATE ,
  COALESCE(OPERATOR_ID, 0 ) AS OPERATOR_ID ,
  COALESCE(REPAY_SIG_MK, '' ) AS REPAY_SIG_MK ,
  COALESCE(DISH_CODE, '' ) AS DISH_CODE ,
  COALESCE(DISH_RSN, '' ) AS DISH_RSN ,
  COALESCE(APPSTATUS, '' ) AS APPSTATUS ,
  COALESCE(ACPAY_STATUS, '' ) AS ACPAY_STATUS ,
  COALESCE(ENDST_DATE, '' ) AS ENDST_DATE ,
  COALESCE(SIG_MK, '' ) AS SIG_MK ,
  COALESCE(CM_STATUS, '' ) AS CM_STATUS ,
  COALESCE(CM_ERR_PROCD, '' ) AS CM_ERR_PROCD ,
  COALESCE(ACCOUNT_FLAG, '' ) AS ACCOUNT_FLAG ,
  COALESCE(SWT_BIZ_ID, 0 ) AS SWT_BIZ_ID ,
  COALESCE(ENTITY_REGSTAT, '' ) AS ENTITY_REGSTAT ,
  COALESCE(ENTITY_REG_ID, 0 ) AS ENTITY_REG_ID ,
  COALESCE(APPNO, '' ) AS APPNO ,
  COALESCE(MISC, '' ) AS MISC ,
  COALESCE(LAST_UPD_OPER_ID, 0 ) AS LAST_UPD_OPER_ID ,
  COALESCE(LAST_UPD_TIME, '' ) AS LAST_UPD_TIME ,
  COALESCE(REQ_REMARK, '' ) AS REQ_REMARK ,
  COALESCE(RCV_REMARK, '' ) AS RCV_REMARK ,
  COALESCE(ECDS_PRC_MSG, '' ) AS ECDS_PRC_MSG ,
  COALESCE(REQ_PRXY_PROP_STN, '' ) AS REQ_PRXY_PROP_STN ,
  COALESCE(RCV_PRXY_SGNTR, '' ) AS RCV_PRXY_SGNTR ,
  COALESCE(ACCOUNT_DATE, '' ) AS ACCOUNT_DATE ,
  COALESCE(CANCEL_DATE, '' ) AS CANCEL_DATE ,
  COALESCE(ACTLOG_ID, 0 ) AS ACTLOG_ID ,
  COALESCE(TRF_ID, '' ) AS TRF_ID ,
  COALESCE(TRF_REF, '' ) AS TRF_REF ,
  COALESCE(IF_SIGN, '' ) AS IF_SIGN ,
  COALESCE(PAY_MODE, '' ) AS PAY_MODE ,
  COALESCE(SWITCH_OR_BANK_NO, '' ) AS SWITCH_OR_BANK_NO ,
  COALESCE(SWITCH_CASE_NO, '' ) AS SWITCH_CASE_NO ,
  COALESCE(OPPONENT_NAME, '' ) AS OPPONENT_NAME ,
  COALESCE(OPPONENT_ACCT, '' ) AS OPPONENT_ACCT ,
  COALESCE(TRANSFER_STATUS, '' ) AS TRANSFER_STATUS ,
  COALESCE(PRINT_COUNT, '' ) AS PRINT_COUNT ,
  COALESCE(FLAG_PRINT, '' ) AS FLAG_PRINT ,
  COALESCE(FLAG_PHOTO, '' ) AS FLAG_PHOTO ,
  COALESCE(FLAG_UPLOAD, '' ) AS FLAG_UPLOAD 
 FROM  dw_tdata.BBS_001_ACCEPT_DUE_PAY_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ID ,
  BRANCH_ID ,
  DRAFT_ID ,
  ISSE_CURCD ,
  ISSE_AMT ,
  MESG_TYPE ,
  APPLY_DATE ,
  OVRDUE_RSN ,
  APPLY_CURCD ,
  APPLY_AMT ,
  STTLM_MK ,
  VOC_CNT ,
  DRFT_HLDR_ROLE ,
  DRFT_HLDR_CMONID ,
  DRFT_HLDR_NAME ,
  DRFT_HLDR_ACTNO ,
  DRFT_HLDR_UBANK ,
  DRFT_HLDR_AGCY_UBANK ,
  ACCEPT_DATE ,
  ACCEPT_CURCD ,
  ACCEPT_AMOUNT ,
  RETURN_CUSTOMER_NAME ,
  CUSTOMER_ACCOUNT ,
  RECEIVE_DATE ,
  REPLY_DATE ,
  OPERATOR_ID ,
  REPAY_SIG_MK ,
  DISH_CODE ,
  DISH_RSN ,
  APPSTATUS ,
  ACPAY_STATUS ,
  ENDST_DATE ,
  SIG_MK ,
  CM_STATUS ,
  CM_ERR_PROCD ,
  ACCOUNT_FLAG ,
  SWT_BIZ_ID ,
  ENTITY_REGSTAT ,
  ENTITY_REG_ID ,
  APPNO ,
  MISC ,
  LAST_UPD_OPER_ID ,
  LAST_UPD_TIME ,
  REQ_REMARK ,
  RCV_REMARK ,
  ECDS_PRC_MSG ,
  REQ_PRXY_PROP_STN ,
  RCV_PRXY_SGNTR ,
  ACCOUNT_DATE ,
  CANCEL_DATE ,
  ACTLOG_ID ,
  TRF_ID ,
  TRF_REF ,
  IF_SIGN ,
  PAY_MODE ,
  SWITCH_OR_BANK_NO ,
  SWITCH_CASE_NO ,
  OPPONENT_NAME ,
  OPPONENT_ACCT ,
  TRANSFER_STATUS ,
  PRINT_COUNT ,
  FLAG_PRINT ,
  FLAG_PHOTO ,
  FLAG_UPLOAD 
 FROM dw_sdata.BBS_001_ACCEPT_DUE_PAY 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ID = T.ID
WHERE
(T.ID IS NULL)
 OR N.BRANCH_ID<>T.BRANCH_ID
 OR N.DRAFT_ID<>T.DRAFT_ID
 OR N.ISSE_CURCD<>T.ISSE_CURCD
 OR N.ISSE_AMT<>T.ISSE_AMT
 OR N.MESG_TYPE<>T.MESG_TYPE
 OR N.APPLY_DATE<>T.APPLY_DATE
 OR N.OVRDUE_RSN<>T.OVRDUE_RSN
 OR N.APPLY_CURCD<>T.APPLY_CURCD
 OR N.APPLY_AMT<>T.APPLY_AMT
 OR N.STTLM_MK<>T.STTLM_MK
 OR N.VOC_CNT<>T.VOC_CNT
 OR N.DRFT_HLDR_ROLE<>T.DRFT_HLDR_ROLE
 OR N.DRFT_HLDR_CMONID<>T.DRFT_HLDR_CMONID
 OR N.DRFT_HLDR_NAME<>T.DRFT_HLDR_NAME
 OR N.DRFT_HLDR_ACTNO<>T.DRFT_HLDR_ACTNO
 OR N.DRFT_HLDR_UBANK<>T.DRFT_HLDR_UBANK
 OR N.DRFT_HLDR_AGCY_UBANK<>T.DRFT_HLDR_AGCY_UBANK
 OR N.ACCEPT_DATE<>T.ACCEPT_DATE
 OR N.ACCEPT_CURCD<>T.ACCEPT_CURCD
 OR N.ACCEPT_AMOUNT<>T.ACCEPT_AMOUNT
 OR N.RETURN_CUSTOMER_NAME<>T.RETURN_CUSTOMER_NAME
 OR N.CUSTOMER_ACCOUNT<>T.CUSTOMER_ACCOUNT
 OR N.RECEIVE_DATE<>T.RECEIVE_DATE
 OR N.REPLY_DATE<>T.REPLY_DATE
 OR N.OPERATOR_ID<>T.OPERATOR_ID
 OR N.REPAY_SIG_MK<>T.REPAY_SIG_MK
 OR N.DISH_CODE<>T.DISH_CODE
 OR N.DISH_RSN<>T.DISH_RSN
 OR N.APPSTATUS<>T.APPSTATUS
 OR N.ACPAY_STATUS<>T.ACPAY_STATUS
 OR N.ENDST_DATE<>T.ENDST_DATE
 OR N.SIG_MK<>T.SIG_MK
 OR N.CM_STATUS<>T.CM_STATUS
 OR N.CM_ERR_PROCD<>T.CM_ERR_PROCD
 OR N.ACCOUNT_FLAG<>T.ACCOUNT_FLAG
 OR N.SWT_BIZ_ID<>T.SWT_BIZ_ID
 OR N.ENTITY_REGSTAT<>T.ENTITY_REGSTAT
 OR N.ENTITY_REG_ID<>T.ENTITY_REG_ID
 OR N.APPNO<>T.APPNO
 OR N.MISC<>T.MISC
 OR N.LAST_UPD_OPER_ID<>T.LAST_UPD_OPER_ID
 OR N.LAST_UPD_TIME<>T.LAST_UPD_TIME
 OR N.REQ_REMARK<>T.REQ_REMARK
 OR N.RCV_REMARK<>T.RCV_REMARK
 OR N.ECDS_PRC_MSG<>T.ECDS_PRC_MSG
 OR N.REQ_PRXY_PROP_STN<>T.REQ_PRXY_PROP_STN
 OR N.RCV_PRXY_SGNTR<>T.RCV_PRXY_SGNTR
 OR N.ACCOUNT_DATE<>T.ACCOUNT_DATE
 OR N.CANCEL_DATE<>T.CANCEL_DATE
 OR N.ACTLOG_ID<>T.ACTLOG_ID
 OR N.TRF_ID<>T.TRF_ID
 OR N.TRF_REF<>T.TRF_REF
 OR N.IF_SIGN<>T.IF_SIGN
 OR N.PAY_MODE<>T.PAY_MODE
 OR N.SWITCH_OR_BANK_NO<>T.SWITCH_OR_BANK_NO
 OR N.SWITCH_CASE_NO<>T.SWITCH_CASE_NO
 OR N.OPPONENT_NAME<>T.OPPONENT_NAME
 OR N.OPPONENT_ACCT<>T.OPPONENT_ACCT
 OR N.TRANSFER_STATUS<>T.TRANSFER_STATUS
 OR N.PRINT_COUNT<>T.PRINT_COUNT
 OR N.FLAG_PRINT<>T.FLAG_PRINT
 OR N.FLAG_PHOTO<>T.FLAG_PHOTO
 OR N.FLAG_UPLOAD<>T.FLAG_UPLOAD
;

--Step3:
UPDATE dw_sdata.BBS_001_ACCEPT_DUE_PAY P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_34
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ID=T_34.ID
;

--Step4:
INSERT  INTO dw_sdata.BBS_001_ACCEPT_DUE_PAY SELECT * FROM T_34;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
