#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.BBS_001_BUY_CONTRACT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.BBS_001_BUY_CONTRACT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_40 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.BBS_001_BUY_CONTRACT WHERE 1=0;

--Step2:
INSERT  INTO T_40 (
  ID,
  BRANCH_ID,
  ACCT_BRANCH_ID,
  TASK_TYPE,
  BUY_TYPE,
  BUYBIZ_TYPE,
  CENTRAL_BANKFLG,
  BUY_SIG_MK,
  BUSINESS_NO,
  DRAFT_TYPE,
  DRAFT_ATTR,
  CUSTOMER_ID,
  CUSTOMER_CUSTNO,
  CUSTOMER_NAME,
  CUSTOMER_BANK_NO,
  CUSTOMER_ACCOUNT,
  RATE,
  RATE_TYPE,
  RERATE,
  RERATE_TYPE,
  BUY_DATE,
  STTLM_MK,
  POSTPONE_TYPE,
  TWO_WAY_DATE,
  BUY_SELL_DATE,
  BUY_BACK_BEGIN_DATE,
  BUY_BACK_END_DATE,
  INNER_FLAG,
  VIRTUAL_FLAG,
  RISK_SCALE,
  PAY_TYPE,
  INNER_CUST_FLAG,
  PAYER_NAME,
  PAYER_BANK_NAME,
  PAYER_ACCOUNT,
  PAYER_SCALE,
  AGENT_NAME,
  MANAGER_ID,
  DEPART_ID,
  DISCOUNT_FIRST_FLAG,
  MEND_FLAG,
  ADD_LAST_DATE,
  ACTURALLY_INDUSTY,
  OPERATOR_ID,
  TXN_DATE,
  LOGIC_CHECK_STATUS,
  RISK_CHECK_STATUS,
  CREDIT_CHECK_STATUS,
  AUDIT_STATUS,
  CALC_STATUS,
  ACCOUNT_STATUS,
  MATURITY_STATUS,
  DISAFFIRM_STATUS,
  INTEREST_STATUS,
  AGENT_RATE,
  AGENT_RATE_TYPE,
  PROFIT_ASSIGN_STATUS,
  MISC,
  APPNO,
  LAST_UPD_OPER_ID,
  LAST_UPD_TIME,
  BIGSMALL_FLAG,
  CUSTOMER_ACCWAY,
  DROPDOWN_FLAG,
  CHANGE_BANKNO,
  CHANGE_FIELDNO,
  BANK_TYPECODE,
  ACCOUNT_NAME,
  PAYER_ACCOUNT_NAME,
  RATE_VALUE,
  RATE_NEW,
  CREDIT_USE_TYPE,
  IS_FIRST_AUDIT,
  FIRST_AUDIT_DATE,
  REDUCE_ACCOUNT,
  PARENT_BANK_ID,
  FINANCE_DISCOUNT,
  BAIL_ACCOUNT,
  BAIL_CHILD_ACCOUNT,
  VOLUME_OCCUPANT,
  RESELL_RATE,
  TRADE_WAY,
  RELATED_CONTRACT_NO,
  GROUP_BUSINESS,
  FINANCE_FLAG,
  PAYER_ACC_TYPE,
  COLLATERAL_SCALE,
  BAIL_PERSON_SCALE,
  STRADDLE_SELF,
  FUND_COST,
  COLLATERAL_STATUS,
  CUST_ACCESS,
  start_dt,
  end_dt)
SELECT
  N.ID,
  N.BRANCH_ID,
  N.ACCT_BRANCH_ID,
  N.TASK_TYPE,
  N.BUY_TYPE,
  N.BUYBIZ_TYPE,
  N.CENTRAL_BANKFLG,
  N.BUY_SIG_MK,
  N.BUSINESS_NO,
  N.DRAFT_TYPE,
  N.DRAFT_ATTR,
  N.CUSTOMER_ID,
  N.CUSTOMER_CUSTNO,
  N.CUSTOMER_NAME,
  N.CUSTOMER_BANK_NO,
  N.CUSTOMER_ACCOUNT,
  N.RATE,
  N.RATE_TYPE,
  N.RERATE,
  N.RERATE_TYPE,
  N.BUY_DATE,
  N.STTLM_MK,
  N.POSTPONE_TYPE,
  N.TWO_WAY_DATE,
  N.BUY_SELL_DATE,
  N.BUY_BACK_BEGIN_DATE,
  N.BUY_BACK_END_DATE,
  N.INNER_FLAG,
  N.VIRTUAL_FLAG,
  N.RISK_SCALE,
  N.PAY_TYPE,
  N.INNER_CUST_FLAG,
  N.PAYER_NAME,
  N.PAYER_BANK_NAME,
  N.PAYER_ACCOUNT,
  N.PAYER_SCALE,
  N.AGENT_NAME,
  N.MANAGER_ID,
  N.DEPART_ID,
  N.DISCOUNT_FIRST_FLAG,
  N.MEND_FLAG,
  N.ADD_LAST_DATE,
  N.ACTURALLY_INDUSTY,
  N.OPERATOR_ID,
  N.TXN_DATE,
  N.LOGIC_CHECK_STATUS,
  N.RISK_CHECK_STATUS,
  N.CREDIT_CHECK_STATUS,
  N.AUDIT_STATUS,
  N.CALC_STATUS,
  N.ACCOUNT_STATUS,
  N.MATURITY_STATUS,
  N.DISAFFIRM_STATUS,
  N.INTEREST_STATUS,
  N.AGENT_RATE,
  N.AGENT_RATE_TYPE,
  N.PROFIT_ASSIGN_STATUS,
  N.MISC,
  N.APPNO,
  N.LAST_UPD_OPER_ID,
  N.LAST_UPD_TIME,
  N.BIGSMALL_FLAG,
  N.CUSTOMER_ACCWAY,
  N.DROPDOWN_FLAG,
  N.CHANGE_BANKNO,
  N.CHANGE_FIELDNO,
  N.BANK_TYPECODE,
  N.ACCOUNT_NAME,
  N.PAYER_ACCOUNT_NAME,
  N.RATE_VALUE,
  N.RATE_NEW,
  N.CREDIT_USE_TYPE,
  N.IS_FIRST_AUDIT,
  N.FIRST_AUDIT_DATE,
  N.REDUCE_ACCOUNT,
  N.PARENT_BANK_ID,
  N.FINANCE_DISCOUNT,
  N.BAIL_ACCOUNT,
  N.BAIL_CHILD_ACCOUNT,
  N.VOLUME_OCCUPANT,
  N.RESELL_RATE,
  N.TRADE_WAY,
  N.RELATED_CONTRACT_NO,
  N.GROUP_BUSINESS,
  N.FINANCE_FLAG,
  N.PAYER_ACC_TYPE,
  N.COLLATERAL_SCALE,
  N.BAIL_PERSON_SCALE,
  N.STRADDLE_SELF,
  N.FUND_COST,
  N.COLLATERAL_STATUS,
  N.CUST_ACCESS,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ID, 0 ) AS ID ,
  COALESCE(BRANCH_ID, 0 ) AS BRANCH_ID ,
  COALESCE(ACCT_BRANCH_ID, 0 ) AS ACCT_BRANCH_ID ,
  COALESCE(TASK_TYPE, '' ) AS TASK_TYPE ,
  COALESCE(BUY_TYPE, '' ) AS BUY_TYPE ,
  COALESCE(BUYBIZ_TYPE, '' ) AS BUYBIZ_TYPE ,
  COALESCE(CENTRAL_BANKFLG, '' ) AS CENTRAL_BANKFLG ,
  COALESCE(BUY_SIG_MK, '' ) AS BUY_SIG_MK ,
  COALESCE(BUSINESS_NO, '' ) AS BUSINESS_NO ,
  COALESCE(DRAFT_TYPE, '' ) AS DRAFT_TYPE ,
  COALESCE(DRAFT_ATTR, '' ) AS DRAFT_ATTR ,
  COALESCE(CUSTOMER_ID, 0 ) AS CUSTOMER_ID ,
  COALESCE(CUSTOMER_CUSTNO, '' ) AS CUSTOMER_CUSTNO ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(CUSTOMER_BANK_NO, 0 ) AS CUSTOMER_BANK_NO ,
  COALESCE(CUSTOMER_ACCOUNT, '' ) AS CUSTOMER_ACCOUNT ,
  COALESCE(RATE, 0 ) AS RATE ,
  COALESCE(RATE_TYPE, '' ) AS RATE_TYPE ,
  COALESCE(RERATE, 0 ) AS RERATE ,
  COALESCE(RERATE_TYPE, '' ) AS RERATE_TYPE ,
  COALESCE(BUY_DATE, '' ) AS BUY_DATE ,
  COALESCE(STTLM_MK, '' ) AS STTLM_MK ,
  COALESCE(POSTPONE_TYPE, '' ) AS POSTPONE_TYPE ,
  COALESCE(TWO_WAY_DATE, '' ) AS TWO_WAY_DATE ,
  COALESCE(BUY_SELL_DATE, '' ) AS BUY_SELL_DATE ,
  COALESCE(BUY_BACK_BEGIN_DATE, '' ) AS BUY_BACK_BEGIN_DATE ,
  COALESCE(BUY_BACK_END_DATE, '' ) AS BUY_BACK_END_DATE ,
  COALESCE(INNER_FLAG, '' ) AS INNER_FLAG ,
  COALESCE(VIRTUAL_FLAG, '' ) AS VIRTUAL_FLAG ,
  COALESCE(RISK_SCALE, 0 ) AS RISK_SCALE ,
  COALESCE(PAY_TYPE, '' ) AS PAY_TYPE ,
  COALESCE(INNER_CUST_FLAG, '' ) AS INNER_CUST_FLAG ,
  COALESCE(PAYER_NAME, '' ) AS PAYER_NAME ,
  COALESCE(PAYER_BANK_NAME, '' ) AS PAYER_BANK_NAME ,
  COALESCE(PAYER_ACCOUNT, '' ) AS PAYER_ACCOUNT ,
  COALESCE(PAYER_SCALE, 0 ) AS PAYER_SCALE ,
  COALESCE(AGENT_NAME, '' ) AS AGENT_NAME ,
  COALESCE(MANAGER_ID, 0 ) AS MANAGER_ID ,
  COALESCE(DEPART_ID, 0 ) AS DEPART_ID ,
  COALESCE(DISCOUNT_FIRST_FLAG, '' ) AS DISCOUNT_FIRST_FLAG ,
  COALESCE(MEND_FLAG, '' ) AS MEND_FLAG ,
  COALESCE(ADD_LAST_DATE, '' ) AS ADD_LAST_DATE ,
  COALESCE(ACTURALLY_INDUSTY, '' ) AS ACTURALLY_INDUSTY ,
  COALESCE(OPERATOR_ID, 0 ) AS OPERATOR_ID ,
  COALESCE(TXN_DATE, '' ) AS TXN_DATE ,
  COALESCE(LOGIC_CHECK_STATUS, '' ) AS LOGIC_CHECK_STATUS ,
  COALESCE(RISK_CHECK_STATUS, '' ) AS RISK_CHECK_STATUS ,
  COALESCE(CREDIT_CHECK_STATUS, '' ) AS CREDIT_CHECK_STATUS ,
  COALESCE(AUDIT_STATUS, '' ) AS AUDIT_STATUS ,
  COALESCE(CALC_STATUS, '' ) AS CALC_STATUS ,
  COALESCE(ACCOUNT_STATUS, '' ) AS ACCOUNT_STATUS ,
  COALESCE(MATURITY_STATUS, '' ) AS MATURITY_STATUS ,
  COALESCE(DISAFFIRM_STATUS, '' ) AS DISAFFIRM_STATUS ,
  COALESCE(INTEREST_STATUS, '' ) AS INTEREST_STATUS ,
  COALESCE(AGENT_RATE, 0 ) AS AGENT_RATE ,
  COALESCE(AGENT_RATE_TYPE, '' ) AS AGENT_RATE_TYPE ,
  COALESCE(PROFIT_ASSIGN_STATUS, '' ) AS PROFIT_ASSIGN_STATUS ,
  COALESCE(MISC, '' ) AS MISC ,
  COALESCE(APPNO, '' ) AS APPNO ,
  COALESCE(LAST_UPD_OPER_ID, 0 ) AS LAST_UPD_OPER_ID ,
  COALESCE(LAST_UPD_TIME, '' ) AS LAST_UPD_TIME ,
  COALESCE(BIGSMALL_FLAG, '' ) AS BIGSMALL_FLAG ,
  COALESCE(CUSTOMER_ACCWAY, '' ) AS CUSTOMER_ACCWAY ,
  COALESCE(DROPDOWN_FLAG, '' ) AS DROPDOWN_FLAG ,
  COALESCE(CHANGE_BANKNO, '' ) AS CHANGE_BANKNO ,
  COALESCE(CHANGE_FIELDNO, '' ) AS CHANGE_FIELDNO ,
  COALESCE(BANK_TYPECODE, '' ) AS BANK_TYPECODE ,
  COALESCE(ACCOUNT_NAME, '' ) AS ACCOUNT_NAME ,
  COALESCE(PAYER_ACCOUNT_NAME, '' ) AS PAYER_ACCOUNT_NAME ,
  COALESCE(RATE_VALUE, 0 ) AS RATE_VALUE ,
  COALESCE(RATE_NEW, '' ) AS RATE_NEW ,
  COALESCE(CREDIT_USE_TYPE, '' ) AS CREDIT_USE_TYPE ,
  COALESCE(IS_FIRST_AUDIT, '' ) AS IS_FIRST_AUDIT ,
  COALESCE(FIRST_AUDIT_DATE, '' ) AS FIRST_AUDIT_DATE ,
  COALESCE(REDUCE_ACCOUNT, '' ) AS REDUCE_ACCOUNT ,
  COALESCE(PARENT_BANK_ID, 0 ) AS PARENT_BANK_ID ,
  COALESCE(FINANCE_DISCOUNT, '' ) AS FINANCE_DISCOUNT ,
  COALESCE(BAIL_ACCOUNT, '' ) AS BAIL_ACCOUNT ,
  COALESCE(BAIL_CHILD_ACCOUNT, '' ) AS BAIL_CHILD_ACCOUNT ,
  COALESCE(VOLUME_OCCUPANT, '' ) AS VOLUME_OCCUPANT ,
  COALESCE(RESELL_RATE, '' ) AS RESELL_RATE ,
  COALESCE(TRADE_WAY, '' ) AS TRADE_WAY ,
  COALESCE(RELATED_CONTRACT_NO, '' ) AS RELATED_CONTRACT_NO ,
  COALESCE(GROUP_BUSINESS, '' ) AS GROUP_BUSINESS ,
  COALESCE(FINANCE_FLAG, '' ) AS FINANCE_FLAG ,
  COALESCE(PAYER_ACC_TYPE, '' ) AS PAYER_ACC_TYPE ,
  COALESCE(COLLATERAL_SCALE, 0 ) AS COLLATERAL_SCALE ,
  COALESCE(BAIL_PERSON_SCALE, 0 ) AS BAIL_PERSON_SCALE ,
  COALESCE(STRADDLE_SELF, '' ) AS STRADDLE_SELF ,
  COALESCE(FUND_COST, '' ) AS FUND_COST ,
  COALESCE(COLLATERAL_STATUS, '' ) AS COLLATERAL_STATUS ,
  COALESCE(CUST_ACCESS, '' ) AS CUST_ACCESS 
 FROM  dw_tdata.BBS_001_BUY_CONTRACT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ID ,
  BRANCH_ID ,
  ACCT_BRANCH_ID ,
  TASK_TYPE ,
  BUY_TYPE ,
  BUYBIZ_TYPE ,
  CENTRAL_BANKFLG ,
  BUY_SIG_MK ,
  BUSINESS_NO ,
  DRAFT_TYPE ,
  DRAFT_ATTR ,
  CUSTOMER_ID ,
  CUSTOMER_CUSTNO ,
  CUSTOMER_NAME ,
  CUSTOMER_BANK_NO ,
  CUSTOMER_ACCOUNT ,
  RATE ,
  RATE_TYPE ,
  RERATE ,
  RERATE_TYPE ,
  BUY_DATE ,
  STTLM_MK ,
  POSTPONE_TYPE ,
  TWO_WAY_DATE ,
  BUY_SELL_DATE ,
  BUY_BACK_BEGIN_DATE ,
  BUY_BACK_END_DATE ,
  INNER_FLAG ,
  VIRTUAL_FLAG ,
  RISK_SCALE ,
  PAY_TYPE ,
  INNER_CUST_FLAG ,
  PAYER_NAME ,
  PAYER_BANK_NAME ,
  PAYER_ACCOUNT ,
  PAYER_SCALE ,
  AGENT_NAME ,
  MANAGER_ID ,
  DEPART_ID ,
  DISCOUNT_FIRST_FLAG ,
  MEND_FLAG ,
  ADD_LAST_DATE ,
  ACTURALLY_INDUSTY ,
  OPERATOR_ID ,
  TXN_DATE ,
  LOGIC_CHECK_STATUS ,
  RISK_CHECK_STATUS ,
  CREDIT_CHECK_STATUS ,
  AUDIT_STATUS ,
  CALC_STATUS ,
  ACCOUNT_STATUS ,
  MATURITY_STATUS ,
  DISAFFIRM_STATUS ,
  INTEREST_STATUS ,
  AGENT_RATE ,
  AGENT_RATE_TYPE ,
  PROFIT_ASSIGN_STATUS ,
  MISC ,
  APPNO ,
  LAST_UPD_OPER_ID ,
  LAST_UPD_TIME ,
  BIGSMALL_FLAG ,
  CUSTOMER_ACCWAY ,
  DROPDOWN_FLAG ,
  CHANGE_BANKNO ,
  CHANGE_FIELDNO ,
  BANK_TYPECODE ,
  ACCOUNT_NAME ,
  PAYER_ACCOUNT_NAME ,
  RATE_VALUE ,
  RATE_NEW ,
  CREDIT_USE_TYPE ,
  IS_FIRST_AUDIT ,
  FIRST_AUDIT_DATE ,
  REDUCE_ACCOUNT ,
  PARENT_BANK_ID ,
  FINANCE_DISCOUNT ,
  BAIL_ACCOUNT ,
  BAIL_CHILD_ACCOUNT ,
  VOLUME_OCCUPANT ,
  RESELL_RATE ,
  TRADE_WAY ,
  RELATED_CONTRACT_NO ,
  GROUP_BUSINESS ,
  FINANCE_FLAG ,
  PAYER_ACC_TYPE ,
  COLLATERAL_SCALE ,
  BAIL_PERSON_SCALE ,
  STRADDLE_SELF ,
  FUND_COST ,
  COLLATERAL_STATUS ,
  CUST_ACCESS 
 FROM dw_sdata.BBS_001_BUY_CONTRACT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ID = T.ID
WHERE
(T.ID IS NULL)
 OR N.BRANCH_ID<>T.BRANCH_ID
 OR N.ACCT_BRANCH_ID<>T.ACCT_BRANCH_ID
 OR N.TASK_TYPE<>T.TASK_TYPE
 OR N.BUY_TYPE<>T.BUY_TYPE
 OR N.BUYBIZ_TYPE<>T.BUYBIZ_TYPE
 OR N.CENTRAL_BANKFLG<>T.CENTRAL_BANKFLG
 OR N.BUY_SIG_MK<>T.BUY_SIG_MK
 OR N.BUSINESS_NO<>T.BUSINESS_NO
 OR N.DRAFT_TYPE<>T.DRAFT_TYPE
 OR N.DRAFT_ATTR<>T.DRAFT_ATTR
 OR N.CUSTOMER_ID<>T.CUSTOMER_ID
 OR N.CUSTOMER_CUSTNO<>T.CUSTOMER_CUSTNO
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.CUSTOMER_BANK_NO<>T.CUSTOMER_BANK_NO
 OR N.CUSTOMER_ACCOUNT<>T.CUSTOMER_ACCOUNT
 OR N.RATE<>T.RATE
 OR N.RATE_TYPE<>T.RATE_TYPE
 OR N.RERATE<>T.RERATE
 OR N.RERATE_TYPE<>T.RERATE_TYPE
 OR N.BUY_DATE<>T.BUY_DATE
 OR N.STTLM_MK<>T.STTLM_MK
 OR N.POSTPONE_TYPE<>T.POSTPONE_TYPE
 OR N.TWO_WAY_DATE<>T.TWO_WAY_DATE
 OR N.BUY_SELL_DATE<>T.BUY_SELL_DATE
 OR N.BUY_BACK_BEGIN_DATE<>T.BUY_BACK_BEGIN_DATE
 OR N.BUY_BACK_END_DATE<>T.BUY_BACK_END_DATE
 OR N.INNER_FLAG<>T.INNER_FLAG
 OR N.VIRTUAL_FLAG<>T.VIRTUAL_FLAG
 OR N.RISK_SCALE<>T.RISK_SCALE
 OR N.PAY_TYPE<>T.PAY_TYPE
 OR N.INNER_CUST_FLAG<>T.INNER_CUST_FLAG
 OR N.PAYER_NAME<>T.PAYER_NAME
 OR N.PAYER_BANK_NAME<>T.PAYER_BANK_NAME
 OR N.PAYER_ACCOUNT<>T.PAYER_ACCOUNT
 OR N.PAYER_SCALE<>T.PAYER_SCALE
 OR N.AGENT_NAME<>T.AGENT_NAME
 OR N.MANAGER_ID<>T.MANAGER_ID
 OR N.DEPART_ID<>T.DEPART_ID
 OR N.DISCOUNT_FIRST_FLAG<>T.DISCOUNT_FIRST_FLAG
 OR N.MEND_FLAG<>T.MEND_FLAG
 OR N.ADD_LAST_DATE<>T.ADD_LAST_DATE
 OR N.ACTURALLY_INDUSTY<>T.ACTURALLY_INDUSTY
 OR N.OPERATOR_ID<>T.OPERATOR_ID
 OR N.TXN_DATE<>T.TXN_DATE
 OR N.LOGIC_CHECK_STATUS<>T.LOGIC_CHECK_STATUS
 OR N.RISK_CHECK_STATUS<>T.RISK_CHECK_STATUS
 OR N.CREDIT_CHECK_STATUS<>T.CREDIT_CHECK_STATUS
 OR N.AUDIT_STATUS<>T.AUDIT_STATUS
 OR N.CALC_STATUS<>T.CALC_STATUS
 OR N.ACCOUNT_STATUS<>T.ACCOUNT_STATUS
 OR N.MATURITY_STATUS<>T.MATURITY_STATUS
 OR N.DISAFFIRM_STATUS<>T.DISAFFIRM_STATUS
 OR N.INTEREST_STATUS<>T.INTEREST_STATUS
 OR N.AGENT_RATE<>T.AGENT_RATE
 OR N.AGENT_RATE_TYPE<>T.AGENT_RATE_TYPE
 OR N.PROFIT_ASSIGN_STATUS<>T.PROFIT_ASSIGN_STATUS
 OR N.MISC<>T.MISC
 OR N.APPNO<>T.APPNO
 OR N.LAST_UPD_OPER_ID<>T.LAST_UPD_OPER_ID
 OR N.LAST_UPD_TIME<>T.LAST_UPD_TIME
 OR N.BIGSMALL_FLAG<>T.BIGSMALL_FLAG
 OR N.CUSTOMER_ACCWAY<>T.CUSTOMER_ACCWAY
 OR N.DROPDOWN_FLAG<>T.DROPDOWN_FLAG
 OR N.CHANGE_BANKNO<>T.CHANGE_BANKNO
 OR N.CHANGE_FIELDNO<>T.CHANGE_FIELDNO
 OR N.BANK_TYPECODE<>T.BANK_TYPECODE
 OR N.ACCOUNT_NAME<>T.ACCOUNT_NAME
 OR N.PAYER_ACCOUNT_NAME<>T.PAYER_ACCOUNT_NAME
 OR N.RATE_VALUE<>T.RATE_VALUE
 OR N.RATE_NEW<>T.RATE_NEW
 OR N.CREDIT_USE_TYPE<>T.CREDIT_USE_TYPE
 OR N.IS_FIRST_AUDIT<>T.IS_FIRST_AUDIT
 OR N.FIRST_AUDIT_DATE<>T.FIRST_AUDIT_DATE
 OR N.REDUCE_ACCOUNT<>T.REDUCE_ACCOUNT
 OR N.PARENT_BANK_ID<>T.PARENT_BANK_ID
 OR N.FINANCE_DISCOUNT<>T.FINANCE_DISCOUNT
 OR N.BAIL_ACCOUNT<>T.BAIL_ACCOUNT
 OR N.BAIL_CHILD_ACCOUNT<>T.BAIL_CHILD_ACCOUNT
 OR N.VOLUME_OCCUPANT<>T.VOLUME_OCCUPANT
 OR N.RESELL_RATE<>T.RESELL_RATE
 OR N.TRADE_WAY<>T.TRADE_WAY
 OR N.RELATED_CONTRACT_NO<>T.RELATED_CONTRACT_NO
 OR N.GROUP_BUSINESS<>T.GROUP_BUSINESS
 OR N.FINANCE_FLAG<>T.FINANCE_FLAG
 OR N.PAYER_ACC_TYPE<>T.PAYER_ACC_TYPE
 OR N.COLLATERAL_SCALE<>T.COLLATERAL_SCALE
 OR N.BAIL_PERSON_SCALE<>T.BAIL_PERSON_SCALE
 OR N.STRADDLE_SELF<>T.STRADDLE_SELF
 OR N.FUND_COST<>T.FUND_COST
 OR N.COLLATERAL_STATUS<>T.COLLATERAL_STATUS
 OR N.CUST_ACCESS<>T.CUST_ACCESS
;

--Step3:
UPDATE dw_sdata.BBS_001_BUY_CONTRACT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_40
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ID=T_40.ID
;

--Step4:
INSERT  INTO dw_sdata.BBS_001_BUY_CONTRACT SELECT * FROM T_40;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
