#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCB_000_APMA WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCB_000_APMA SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_87 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCB_000_APMA WHERE 1=0;

--Step2:
INSERT  INTO T_87 (
  BANK,
  APP_JDAY,
  APP_SEQ,
  APP_DAY,
  APPDEC_DAY,
  CATEGORY,
  PRODUCT,
  ACCOUNT,
  AB_BRANCH,
  AB_USER,
  AB_NAME,
  AB_ACCESS,
  ACC_TYPE,
  ADDL_CARD,
  APP_SOURCE,
  APP_BATCH,
  APPDEC_EMP,
  BANKACCT1,
  BANKACCT2,
  BANKACCT3,
  BANKACCT4,
  BANKCODE1,
  BANKCODE2,
  BANKCODE3,
  BANKCODE4,
  BASE_CARD,
  BRANCH,
  BUSINESS,
  CRDLMT_REQ,
  CRED_LIMIT,
  CREDLIM_X,
  CRLM_X_REQ,
  CUST_COUNT,
  CYCLE_NBR,
  DECCAN_CDE,
  DECCAN_LET,
  DECCAN_REA,
  DECCAN_SUP,
  EMBOSS_CPY,
  GTOC,
  INSUR_CODE,
  INT_CODE,
  LANG_CODE,
  MICROFILM,
  MONTR_CODE,
  MP_LIMIT,
  MPLMT_REQ,
  REPAY_AMT,
  REPAY_AMTX,
  REPAY_CODE,
  REPAY_CODX,
  REPAY_DAY,
  REPAY_PCT,
  REPAY_PCTX,
  RUSH_APP,
  RUSH_FEE,
  SCR_LIMIT,
  SCR_REPLY,
  SCR_SCORE,
  STM_CODE,
  APP_STATUS,
  NEWAC_FLAG,
  CHK_FLAG,
  EXCH_CODE,
  EXCH_FLAG,
  EXCH_PERC,
  EXCH_RTDT,
  FIX_EXAMT,
  LYFEE_FLAG,
  LYSRV_FLAG,
  SMS_YN,
  RISK_CODE,
  CARLICENSE,
  DECCAN_EMP,
  APP_GIFTNO,
  APP_GIFTN2,
  OVERSEA_YN,
  DECCAN_SU2,
  DECCAN_SU3,
  PRMAG_CODE,
  PBC_BRNCH,
  CRED_LMT2,
  UNION_CODE,
  FINANCE_CODE,
  MP_L_LMT,
  XREFCRLMT4,
  SIGN_CHK,
  start_dt,
  end_dt)
SELECT
  N.BANK,
  N.APP_JDAY,
  N.APP_SEQ,
  N.APP_DAY,
  N.APPDEC_DAY,
  N.CATEGORY,
  N.PRODUCT,
  N.ACCOUNT,
  N.AB_BRANCH,
  N.AB_USER,
  N.AB_NAME,
  N.AB_ACCESS,
  N.ACC_TYPE,
  N.ADDL_CARD,
  N.APP_SOURCE,
  N.APP_BATCH,
  N.APPDEC_EMP,
  N.BANKACCT1,
  N.BANKACCT2,
  N.BANKACCT3,
  N.BANKACCT4,
  N.BANKCODE1,
  N.BANKCODE2,
  N.BANKCODE3,
  N.BANKCODE4,
  N.BASE_CARD,
  N.BRANCH,
  N.BUSINESS,
  N.CRDLMT_REQ,
  N.CRED_LIMIT,
  N.CREDLIM_X,
  N.CRLM_X_REQ,
  N.CUST_COUNT,
  N.CYCLE_NBR,
  N.DECCAN_CDE,
  N.DECCAN_LET,
  N.DECCAN_REA,
  N.DECCAN_SUP,
  N.EMBOSS_CPY,
  N.GTOC,
  N.INSUR_CODE,
  N.INT_CODE,
  N.LANG_CODE,
  N.MICROFILM,
  N.MONTR_CODE,
  N.MP_LIMIT,
  N.MPLMT_REQ,
  N.REPAY_AMT,
  N.REPAY_AMTX,
  N.REPAY_CODE,
  N.REPAY_CODX,
  N.REPAY_DAY,
  N.REPAY_PCT,
  N.REPAY_PCTX,
  N.RUSH_APP,
  N.RUSH_FEE,
  N.SCR_LIMIT,
  N.SCR_REPLY,
  N.SCR_SCORE,
  N.STM_CODE,
  N.APP_STATUS,
  N.NEWAC_FLAG,
  N.CHK_FLAG,
  N.EXCH_CODE,
  N.EXCH_FLAG,
  N.EXCH_PERC,
  N.EXCH_RTDT,
  N.FIX_EXAMT,
  N.LYFEE_FLAG,
  N.LYSRV_FLAG,
  N.SMS_YN,
  N.RISK_CODE,
  N.CARLICENSE,
  N.DECCAN_EMP,
  N.APP_GIFTNO,
  N.APP_GIFTN2,
  N.OVERSEA_YN,
  N.DECCAN_SU2,
  N.DECCAN_SU3,
  N.PRMAG_CODE,
  N.PBC_BRNCH,
  N.CRED_LMT2,
  N.UNION_CODE,
  N.FINANCE_CODE,
  N.MP_L_LMT,
  N.XREFCRLMT4,
  N.SIGN_CHK,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(BANK, 0 ) AS BANK ,
  COALESCE(APP_JDAY, 0 ) AS APP_JDAY ,
  COALESCE(APP_SEQ, 0 ) AS APP_SEQ ,
  COALESCE(APP_DAY, 0 ) AS APP_DAY ,
  COALESCE(APPDEC_DAY, 0 ) AS APPDEC_DAY ,
  COALESCE(CATEGORY, 0 ) AS CATEGORY ,
  COALESCE(PRODUCT, 0 ) AS PRODUCT ,
  COALESCE(ACCOUNT, 0 ) AS ACCOUNT ,
  COALESCE(AB_BRANCH, 0 ) AS AB_BRANCH ,
  COALESCE(AB_USER, '' ) AS AB_USER ,
  COALESCE(AB_NAME, '' ) AS AB_NAME ,
  COALESCE(AB_ACCESS, '' ) AS AB_ACCESS ,
  COALESCE(ACC_TYPE, '' ) AS ACC_TYPE ,
  COALESCE(ADDL_CARD, '' ) AS ADDL_CARD ,
  COALESCE(APP_SOURCE, '' ) AS APP_SOURCE ,
  COALESCE(APP_BATCH, '' ) AS APP_BATCH ,
  COALESCE(APPDEC_EMP, 0 ) AS APPDEC_EMP ,
  COALESCE(BANKACCT1, '' ) AS BANKACCT1 ,
  COALESCE(BANKACCT2, '' ) AS BANKACCT2 ,
  COALESCE(BANKACCT3, '' ) AS BANKACCT3 ,
  COALESCE(BANKACCT4, '' ) AS BANKACCT4 ,
  COALESCE(BANKCODE1, '' ) AS BANKCODE1 ,
  COALESCE(BANKCODE2, '' ) AS BANKCODE2 ,
  COALESCE(BANKCODE3, '' ) AS BANKCODE3 ,
  COALESCE(BANKCODE4, '' ) AS BANKCODE4 ,
  COALESCE(BASE_CARD, '' ) AS BASE_CARD ,
  COALESCE(BRANCH, 0 ) AS BRANCH ,
  COALESCE(BUSINESS, '' ) AS BUSINESS ,
  COALESCE(CRDLMT_REQ, 0 ) AS CRDLMT_REQ ,
  COALESCE(CRED_LIMIT, 0 ) AS CRED_LIMIT ,
  COALESCE(CREDLIM_X, 0 ) AS CREDLIM_X ,
  COALESCE(CRLM_X_REQ, 0 ) AS CRLM_X_REQ ,
  COALESCE(CUST_COUNT, 0 ) AS CUST_COUNT ,
  COALESCE(CYCLE_NBR, 0 ) AS CYCLE_NBR ,
  COALESCE(DECCAN_CDE, '' ) AS DECCAN_CDE ,
  COALESCE(DECCAN_LET, '' ) AS DECCAN_LET ,
  COALESCE(DECCAN_REA, 0 ) AS DECCAN_REA ,
  COALESCE(DECCAN_SUP, '' ) AS DECCAN_SUP ,
  COALESCE(EMBOSS_CPY, '' ) AS EMBOSS_CPY ,
  COALESCE(GTOC, '' ) AS GTOC ,
  COALESCE(INSUR_CODE, '' ) AS INSUR_CODE ,
  COALESCE(INT_CODE, 0 ) AS INT_CODE ,
  COALESCE(LANG_CODE, 0 ) AS LANG_CODE ,
  COALESCE(MICROFILM, '' ) AS MICROFILM ,
  COALESCE(MONTR_CODE, '' ) AS MONTR_CODE ,
  COALESCE(MP_LIMIT, 0 ) AS MP_LIMIT ,
  COALESCE(MPLMT_REQ, 0 ) AS MPLMT_REQ ,
  COALESCE(REPAY_AMT, 0 ) AS REPAY_AMT ,
  COALESCE(REPAY_AMTX, 0 ) AS REPAY_AMTX ,
  COALESCE(REPAY_CODE, '' ) AS REPAY_CODE ,
  COALESCE(REPAY_CODX, '' ) AS REPAY_CODX ,
  COALESCE(REPAY_DAY, 0 ) AS REPAY_DAY ,
  COALESCE(REPAY_PCT, 0 ) AS REPAY_PCT ,
  COALESCE(REPAY_PCTX, 0 ) AS REPAY_PCTX ,
  COALESCE(RUSH_APP, '' ) AS RUSH_APP ,
  COALESCE(RUSH_FEE, '' ) AS RUSH_FEE ,
  COALESCE(SCR_LIMIT, 0 ) AS SCR_LIMIT ,
  COALESCE(SCR_REPLY, '' ) AS SCR_REPLY ,
  COALESCE(SCR_SCORE, 0 ) AS SCR_SCORE ,
  COALESCE(STM_CODE, '' ) AS STM_CODE ,
  COALESCE(APP_STATUS, 0 ) AS APP_STATUS ,
  COALESCE(NEWAC_FLAG, '' ) AS NEWAC_FLAG ,
  COALESCE(CHK_FLAG, 0 ) AS CHK_FLAG ,
  COALESCE(EXCH_CODE, '' ) AS EXCH_CODE ,
  COALESCE(EXCH_FLAG, '' ) AS EXCH_FLAG ,
  COALESCE(EXCH_PERC, 0 ) AS EXCH_PERC ,
  COALESCE(EXCH_RTDT, 0 ) AS EXCH_RTDT ,
  COALESCE(FIX_EXAMT, 0 ) AS FIX_EXAMT ,
  COALESCE(LYFEE_FLAG, '' ) AS LYFEE_FLAG ,
  COALESCE(LYSRV_FLAG, '' ) AS LYSRV_FLAG ,
  COALESCE(SMS_YN, '' ) AS SMS_YN ,
  COALESCE(RISK_CODE, '' ) AS RISK_CODE ,
  COALESCE(CARLICENSE, '' ) AS CARLICENSE ,
  COALESCE(DECCAN_EMP, 0 ) AS DECCAN_EMP ,
  COALESCE(APP_GIFTNO, '' ) AS APP_GIFTNO ,
  COALESCE(APP_GIFTN2, '' ) AS APP_GIFTN2 ,
  COALESCE(OVERSEA_YN, '' ) AS OVERSEA_YN ,
  COALESCE(DECCAN_SU2, '' ) AS DECCAN_SU2 ,
  COALESCE(DECCAN_SU3, '' ) AS DECCAN_SU3 ,
  COALESCE(PRMAG_CODE, '' ) AS PRMAG_CODE ,
  COALESCE(PBC_BRNCH, '' ) AS PBC_BRNCH ,
  COALESCE(CRED_LMT2, 0 ) AS CRED_LMT2 ,
  COALESCE(UNION_CODE, '' ) AS UNION_CODE ,
  COALESCE(FINANCE_CODE, '' ) AS FINANCE_CODE ,
  COALESCE(MP_L_LMT, 0 ) AS MP_L_LMT ,
  COALESCE(XREFCRLMT4, 0 ) AS XREFCRLMT4,
  COALESCE(SIGN_CHK,'') AS SIGN_CHK 
 FROM  dw_tdata.CCB_000_APMA_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  BANK ,
  APP_JDAY ,
  APP_SEQ ,
  APP_DAY ,
  APPDEC_DAY ,
  CATEGORY ,
  PRODUCT ,
  ACCOUNT ,
  AB_BRANCH ,
  AB_USER ,
  AB_NAME ,
  AB_ACCESS ,
  ACC_TYPE ,
  ADDL_CARD ,
  APP_SOURCE ,
  APP_BATCH ,
  APPDEC_EMP ,
  BANKACCT1 ,
  BANKACCT2 ,
  BANKACCT3 ,
  BANKACCT4 ,
  BANKCODE1 ,
  BANKCODE2 ,
  BANKCODE3 ,
  BANKCODE4 ,
  BASE_CARD ,
  BRANCH ,
  BUSINESS ,
  CRDLMT_REQ ,
  CRED_LIMIT ,
  CREDLIM_X ,
  CRLM_X_REQ ,
  CUST_COUNT ,
  CYCLE_NBR ,
  DECCAN_CDE ,
  DECCAN_LET ,
  DECCAN_REA ,
  DECCAN_SUP ,
  EMBOSS_CPY ,
  GTOC ,
  INSUR_CODE ,
  INT_CODE ,
  LANG_CODE ,
  MICROFILM ,
  MONTR_CODE ,
  MP_LIMIT ,
  MPLMT_REQ ,
  REPAY_AMT ,
  REPAY_AMTX ,
  REPAY_CODE ,
  REPAY_CODX ,
  REPAY_DAY ,
  REPAY_PCT ,
  REPAY_PCTX ,
  RUSH_APP ,
  RUSH_FEE ,
  SCR_LIMIT ,
  SCR_REPLY ,
  SCR_SCORE ,
  STM_CODE ,
  APP_STATUS ,
  NEWAC_FLAG ,
  CHK_FLAG ,
  EXCH_CODE ,
  EXCH_FLAG ,
  EXCH_PERC ,
  EXCH_RTDT ,
  FIX_EXAMT ,
  LYFEE_FLAG ,
  LYSRV_FLAG ,
  SMS_YN ,
  RISK_CODE ,
  CARLICENSE ,
  DECCAN_EMP ,
  APP_GIFTNO ,
  APP_GIFTN2 ,
  OVERSEA_YN ,
  DECCAN_SU2 ,
  DECCAN_SU3 ,
  PRMAG_CODE ,
  PBC_BRNCH ,
  CRED_LMT2 ,
  UNION_CODE ,
  FINANCE_CODE ,
  MP_L_LMT ,
  XREFCRLMT4,
  SIGN_CHK 
 FROM dw_sdata.CCB_000_APMA 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.BANK = T.BANK AND N.APP_SEQ = T.APP_SEQ AND N.APP_DAY = T.APP_DAY
WHERE
(T.BANK IS NULL AND T.APP_SEQ IS NULL AND T.APP_DAY IS NULL)
 OR N.APP_JDAY<>T.APP_JDAY
 OR N.APPDEC_DAY<>T.APPDEC_DAY
 OR N.CATEGORY<>T.CATEGORY
 OR N.PRODUCT<>T.PRODUCT
 OR N.ACCOUNT<>T.ACCOUNT
 OR N.AB_BRANCH<>T.AB_BRANCH
 OR N.AB_USER<>T.AB_USER
 OR N.AB_NAME<>T.AB_NAME
 OR N.AB_ACCESS<>T.AB_ACCESS
 OR N.ACC_TYPE<>T.ACC_TYPE
 OR N.ADDL_CARD<>T.ADDL_CARD
 OR N.APP_SOURCE<>T.APP_SOURCE
 OR N.APP_BATCH<>T.APP_BATCH
 OR N.APPDEC_EMP<>T.APPDEC_EMP
 OR N.BANKACCT1<>T.BANKACCT1
 OR N.BANKACCT2<>T.BANKACCT2
 OR N.BANKACCT3<>T.BANKACCT3
 OR N.BANKACCT4<>T.BANKACCT4
 OR N.BANKCODE1<>T.BANKCODE1
 OR N.BANKCODE2<>T.BANKCODE2
 OR N.BANKCODE3<>T.BANKCODE3
 OR N.BANKCODE4<>T.BANKCODE4
 OR N.BASE_CARD<>T.BASE_CARD
 OR N.BRANCH<>T.BRANCH
 OR N.BUSINESS<>T.BUSINESS
 OR N.CRDLMT_REQ<>T.CRDLMT_REQ
 OR N.CRED_LIMIT<>T.CRED_LIMIT
 OR N.CREDLIM_X<>T.CREDLIM_X
 OR N.CRLM_X_REQ<>T.CRLM_X_REQ
 OR N.CUST_COUNT<>T.CUST_COUNT
 OR N.CYCLE_NBR<>T.CYCLE_NBR
 OR N.DECCAN_CDE<>T.DECCAN_CDE
 OR N.DECCAN_LET<>T.DECCAN_LET
 OR N.DECCAN_REA<>T.DECCAN_REA
 OR N.DECCAN_SUP<>T.DECCAN_SUP
 OR N.EMBOSS_CPY<>T.EMBOSS_CPY
 OR N.GTOC<>T.GTOC
 OR N.INSUR_CODE<>T.INSUR_CODE
 OR N.INT_CODE<>T.INT_CODE
 OR N.LANG_CODE<>T.LANG_CODE
 OR N.MICROFILM<>T.MICROFILM
 OR N.MONTR_CODE<>T.MONTR_CODE
 OR N.MP_LIMIT<>T.MP_LIMIT
 OR N.MPLMT_REQ<>T.MPLMT_REQ
 OR N.REPAY_AMT<>T.REPAY_AMT
 OR N.REPAY_AMTX<>T.REPAY_AMTX
 OR N.REPAY_CODE<>T.REPAY_CODE
 OR N.REPAY_CODX<>T.REPAY_CODX
 OR N.REPAY_DAY<>T.REPAY_DAY
 OR N.REPAY_PCT<>T.REPAY_PCT
 OR N.REPAY_PCTX<>T.REPAY_PCTX
 OR N.RUSH_APP<>T.RUSH_APP
 OR N.RUSH_FEE<>T.RUSH_FEE
 OR N.SCR_LIMIT<>T.SCR_LIMIT
 OR N.SCR_REPLY<>T.SCR_REPLY
 OR N.SCR_SCORE<>T.SCR_SCORE
 OR N.STM_CODE<>T.STM_CODE
 OR N.APP_STATUS<>T.APP_STATUS
 OR N.NEWAC_FLAG<>T.NEWAC_FLAG
 OR N.CHK_FLAG<>T.CHK_FLAG
 OR N.EXCH_CODE<>T.EXCH_CODE
 OR N.EXCH_FLAG<>T.EXCH_FLAG
 OR N.EXCH_PERC<>T.EXCH_PERC
 OR N.EXCH_RTDT<>T.EXCH_RTDT
 OR N.FIX_EXAMT<>T.FIX_EXAMT
 OR N.LYFEE_FLAG<>T.LYFEE_FLAG
 OR N.LYSRV_FLAG<>T.LYSRV_FLAG
 OR N.SMS_YN<>T.SMS_YN
 OR N.RISK_CODE<>T.RISK_CODE
 OR N.CARLICENSE<>T.CARLICENSE
 OR N.DECCAN_EMP<>T.DECCAN_EMP
 OR N.APP_GIFTNO<>T.APP_GIFTNO
 OR N.APP_GIFTN2<>T.APP_GIFTN2
 OR N.OVERSEA_YN<>T.OVERSEA_YN
 OR N.DECCAN_SU2<>T.DECCAN_SU2
 OR N.DECCAN_SU3<>T.DECCAN_SU3
 OR N.PRMAG_CODE<>T.PRMAG_CODE
 OR N.PBC_BRNCH<>T.PBC_BRNCH
 OR N.CRED_LMT2<>T.CRED_LMT2
 OR N.UNION_CODE<>T.UNION_CODE
 OR N.FINANCE_CODE<>T.FINANCE_CODE
 OR N.MP_L_LMT<>T.MP_L_LMT
 OR N.XREFCRLMT4<>T.XREFCRLMT4
 OR N.SIGN_CHK<>T.SIGN_CHK
;

--Step3:
UPDATE dw_sdata.CCB_000_APMA P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_87
WHERE P.End_Dt=DATE('2100-12-31')
AND P.BANK=T_87.BANK
AND P.APP_SEQ=T_87.APP_SEQ
AND P.APP_DAY=T_87.APP_DAY
;

--Step4:
INSERT  INTO dw_sdata.CCB_000_APMA SELECT * FROM T_87;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
