#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_CRD_PRODUCT_LIMIT WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_CRD_PRODUCT_LIMIT SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_118 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_CRD_PRODUCT_LIMIT WHERE 1=0;

--Step2:
INSERT  INTO T_118 (
  PRODUCT_LIMIT_ID,
  CREDIT_LIMIT_NUM,
  PRODUCT_CD,
  CURRENCY,
  PRODUCT_CREDIT_LIMIT,
  ADJUSTMENT_FACTOR,
  START_DATE,
  END_DATE,
  TERM,
  APPROVE_CREDIT_LIMIT,
  EXCHANGE_RATE,
  TERM_UNIT_CD,
  FREEZED_LIMIT,
  CIRCULAR,
  INTER_CHANGABLE,
  INTER_CHANGE_GROUP,
  LIMIT_ID,
  GRACE_PERIOD,
  GRACE_PERIOD_UNIT,
  APPROVED_LIMIT,
  APPROVED_FREE_LIMIT,
  APPROVED_USED_LIMIT,
  PRODUCT_LEVEL,
  PRE_OCCUPATION_AMT,
  SUPER_PRODUCT_CD,
  CREDIT_TERM,
  CREDIT_TERM_CD,
  IS_COMPANY_SPECIAL_LIMIT,
  USED_CURRENCY_CD,
  STATE,
  INVALIDDATE,
  IS_SPECIAL_CREDIT,
  LIMIT_MODE,
  SPECIAL_TYPE,
  USED_CURRENCY_NAME,
  FROZEN,
  CREDIT_RISK_LIMIT,
  CREDIT_APPROVE_RISK_LIMIT,
  AVAILABLE_RISK_LIMIT,
  OCCU_RISK_LIMIT,
  GUARANTY_TYPE_APPL,
  GUARANTY_TYPE_APPR,
  TERM_APPL,
  TERM_UNIT_CD_APPL,
  CIRCULAR_APPL,
  IS_SPECIAL_CREDIT_APPL,
  CURRENCY_APPL,
  INTER_CHANGABLE_APPL,
  PRE_OCCUPY_RISK_LIMIT,
  USED_CURRENCY_NAME_APPR,
  USED_GUARANTY_NAME_APPL,
  USED_GUARANTY_NAME_APPR,
  CONST_CREDIT_LIMIT_NUM,
  IS_OLD,
  APPROVED_LIMIT_OLD,
  FXBS_TIME_MARK,
  CORE_ENTERPRISE_DUTY_CD,
  IF_DIRECT_CREDIT_FLAG,
  BUYER_SELLER_FLAG,
  OLD_PRODUCT_LIMIT_ID,
  OLD_CUR_LIMIT_APPROVED_LIMIT,
  BATCH_APPROVED_USED_AMT,
  OLD_CUR_LIMIT_RISK_LIMIT,
  start_dt,
  end_dt)
SELECT
  N.PRODUCT_LIMIT_ID,
  N.CREDIT_LIMIT_NUM,
  N.PRODUCT_CD,
  N.CURRENCY,
  N.PRODUCT_CREDIT_LIMIT,
  N.ADJUSTMENT_FACTOR,
  N.START_DATE,
  N.END_DATE,
  N.TERM,
  N.APPROVE_CREDIT_LIMIT,
  N.EXCHANGE_RATE,
  N.TERM_UNIT_CD,
  N.FREEZED_LIMIT,
  N.CIRCULAR,
  N.INTER_CHANGABLE,
  N.INTER_CHANGE_GROUP,
  N.LIMIT_ID,
  N.GRACE_PERIOD,
  N.GRACE_PERIOD_UNIT,
  N.APPROVED_LIMIT,
  N.APPROVED_FREE_LIMIT,
  N.APPROVED_USED_LIMIT,
  N.PRODUCT_LEVEL,
  N.PRE_OCCUPATION_AMT,
  N.SUPER_PRODUCT_CD,
  N.CREDIT_TERM,
  N.CREDIT_TERM_CD,
  N.IS_COMPANY_SPECIAL_LIMIT,
  N.USED_CURRENCY_CD,
  N.STATE,
  N.INVALIDDATE,
  N.IS_SPECIAL_CREDIT,
  N.LIMIT_MODE,
  N.SPECIAL_TYPE,
  N.USED_CURRENCY_NAME,
  N.FROZEN,
  N.CREDIT_RISK_LIMIT,
  N.CREDIT_APPROVE_RISK_LIMIT,
  N.AVAILABLE_RISK_LIMIT,
  N.OCCU_RISK_LIMIT,
  N.GUARANTY_TYPE_APPL,
  N.GUARANTY_TYPE_APPR,
  N.TERM_APPL,
  N.TERM_UNIT_CD_APPL,
  N.CIRCULAR_APPL,
  N.IS_SPECIAL_CREDIT_APPL,
  N.CURRENCY_APPL,
  N.INTER_CHANGABLE_APPL,
  N.PRE_OCCUPY_RISK_LIMIT,
  N.USED_CURRENCY_NAME_APPR,
  N.USED_GUARANTY_NAME_APPL,
  N.USED_GUARANTY_NAME_APPR,
  N.CONST_CREDIT_LIMIT_NUM,
  N.IS_OLD,
  N.APPROVED_LIMIT_OLD,
  N.FXBS_TIME_MARK,
  N.CORE_ENTERPRISE_DUTY_CD,
  N.IF_DIRECT_CREDIT_FLAG,
  N.BUYER_SELLER_FLAG,
  N.OLD_PRODUCT_LIMIT_ID,
  N.OLD_CUR_LIMIT_APPROVED_LIMIT,
  N.BATCH_APPROVED_USED_AMT,
  N.OLD_CUR_LIMIT_RISK_LIMIT,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PRODUCT_LIMIT_ID, '' ) AS PRODUCT_LIMIT_ID ,
  COALESCE(CREDIT_LIMIT_NUM, '' ) AS CREDIT_LIMIT_NUM ,
  COALESCE(PRODUCT_CD, '' ) AS PRODUCT_CD ,
  COALESCE(CURRENCY, '' ) AS CURRENCY ,
  COALESCE(PRODUCT_CREDIT_LIMIT, 0 ) AS PRODUCT_CREDIT_LIMIT ,
  COALESCE(ADJUSTMENT_FACTOR, 0 ) AS ADJUSTMENT_FACTOR ,
  COALESCE(START_DATE,'4999-12-31 00:00:00' ) AS START_DATE ,
  COALESCE(END_DATE,'4999-12-31 00:00:00' ) AS END_DATE ,
  COALESCE(TERM, 0 ) AS TERM ,
  COALESCE(APPROVE_CREDIT_LIMIT, 0 ) AS APPROVE_CREDIT_LIMIT ,
  COALESCE(EXCHANGE_RATE, 0 ) AS EXCHANGE_RATE ,
  COALESCE(TERM_UNIT_CD, '' ) AS TERM_UNIT_CD ,
  COALESCE(FREEZED_LIMIT, 0 ) AS FREEZED_LIMIT ,
  COALESCE(CIRCULAR, '' ) AS CIRCULAR ,
  COALESCE(INTER_CHANGABLE, '' ) AS INTER_CHANGABLE ,
  COALESCE(INTER_CHANGE_GROUP, '' ) AS INTER_CHANGE_GROUP ,
  COALESCE(LIMIT_ID, '' ) AS LIMIT_ID ,
  COALESCE(GRACE_PERIOD, 0 ) AS GRACE_PERIOD ,
  COALESCE(GRACE_PERIOD_UNIT, '' ) AS GRACE_PERIOD_UNIT ,
  COALESCE(APPROVED_LIMIT, 0 ) AS APPROVED_LIMIT ,
  COALESCE(APPROVED_FREE_LIMIT, 0 ) AS APPROVED_FREE_LIMIT ,
  COALESCE(APPROVED_USED_LIMIT, 0 ) AS APPROVED_USED_LIMIT ,
  COALESCE(PRODUCT_LEVEL, '' ) AS PRODUCT_LEVEL ,
  COALESCE(PRE_OCCUPATION_AMT, 0 ) AS PRE_OCCUPATION_AMT ,
  COALESCE(SUPER_PRODUCT_CD, '' ) AS SUPER_PRODUCT_CD ,
  COALESCE(CREDIT_TERM, 0 ) AS CREDIT_TERM ,
  COALESCE(CREDIT_TERM_CD, '' ) AS CREDIT_TERM_CD ,
  COALESCE(IS_COMPANY_SPECIAL_LIMIT, '' ) AS IS_COMPANY_SPECIAL_LIMIT ,
  COALESCE(USED_CURRENCY_CD, '' ) AS USED_CURRENCY_CD ,
  COALESCE(STATE, '' ) AS STATE ,
  COALESCE(INVALIDDATE,'4999-12-31 00:00:00' ) AS INVALIDDATE ,
  COALESCE(IS_SPECIAL_CREDIT, '' ) AS IS_SPECIAL_CREDIT ,
  COALESCE(LIMIT_MODE, '' ) AS LIMIT_MODE ,
  COALESCE(SPECIAL_TYPE, '' ) AS SPECIAL_TYPE ,
  COALESCE(USED_CURRENCY_NAME, '' ) AS USED_CURRENCY_NAME ,
  COALESCE(FROZEN, '' ) AS FROZEN ,
  COALESCE(CREDIT_RISK_LIMIT, 0 ) AS CREDIT_RISK_LIMIT ,
  COALESCE(CREDIT_APPROVE_RISK_LIMIT, 0 ) AS CREDIT_APPROVE_RISK_LIMIT ,
  COALESCE(AVAILABLE_RISK_LIMIT, 0 ) AS AVAILABLE_RISK_LIMIT ,
  COALESCE(OCCU_RISK_LIMIT, 0 ) AS OCCU_RISK_LIMIT ,
  COALESCE(GUARANTY_TYPE_APPL, '' ) AS GUARANTY_TYPE_APPL ,
  COALESCE(GUARANTY_TYPE_APPR, '' ) AS GUARANTY_TYPE_APPR ,
  COALESCE(TERM_APPL, 0 ) AS TERM_APPL ,
  COALESCE(TERM_UNIT_CD_APPL, '' ) AS TERM_UNIT_CD_APPL ,
  COALESCE(CIRCULAR_APPL, '' ) AS CIRCULAR_APPL ,
  COALESCE(IS_SPECIAL_CREDIT_APPL, '' ) AS IS_SPECIAL_CREDIT_APPL ,
  COALESCE(CURRENCY_APPL, '' ) AS CURRENCY_APPL ,
  COALESCE(INTER_CHANGABLE_APPL, '' ) AS INTER_CHANGABLE_APPL ,
  COALESCE(PRE_OCCUPY_RISK_LIMIT, 0 ) AS PRE_OCCUPY_RISK_LIMIT ,
  COALESCE(USED_CURRENCY_NAME_APPR, '' ) AS USED_CURRENCY_NAME_APPR ,
  COALESCE(USED_GUARANTY_NAME_APPL, '' ) AS USED_GUARANTY_NAME_APPL ,
  COALESCE(USED_GUARANTY_NAME_APPR, '' ) AS USED_GUARANTY_NAME_APPR ,
  COALESCE(CONST_CREDIT_LIMIT_NUM, '' ) AS CONST_CREDIT_LIMIT_NUM ,
  COALESCE(IS_OLD, '' ) AS IS_OLD ,
  COALESCE(APPROVED_LIMIT_OLD, 0 ) AS APPROVED_LIMIT_OLD ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(CORE_ENTERPRISE_DUTY_CD, '' ) AS CORE_ENTERPRISE_DUTY_CD ,
  COALESCE(IF_DIRECT_CREDIT_FLAG, '' ) AS IF_DIRECT_CREDIT_FLAG ,
  COALESCE(BUYER_SELLER_FLAG, '' ) AS BUYER_SELLER_FLAG ,
  COALESCE(OLD_PRODUCT_LIMIT_ID, '' ) AS OLD_PRODUCT_LIMIT_ID ,
  COALESCE(OLD_CUR_LIMIT_APPROVED_LIMIT, 0 ) AS OLD_CUR_LIMIT_APPROVED_LIMIT ,
  COALESCE(BATCH_APPROVED_USED_AMT, 0 ) AS BATCH_APPROVED_USED_AMT ,
  COALESCE(OLD_CUR_LIMIT_RISK_LIMIT, 0 ) AS OLD_CUR_LIMIT_RISK_LIMIT 
 FROM  dw_tdata.CCS_004_TB_CRD_PRODUCT_LIMIT_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PRODUCT_LIMIT_ID ,
  CREDIT_LIMIT_NUM ,
  PRODUCT_CD ,
  CURRENCY ,
  PRODUCT_CREDIT_LIMIT ,
  ADJUSTMENT_FACTOR ,
  START_DATE ,
  END_DATE ,
  TERM ,
  APPROVE_CREDIT_LIMIT ,
  EXCHANGE_RATE ,
  TERM_UNIT_CD ,
  FREEZED_LIMIT ,
  CIRCULAR ,
  INTER_CHANGABLE ,
  INTER_CHANGE_GROUP ,
  LIMIT_ID ,
  GRACE_PERIOD ,
  GRACE_PERIOD_UNIT ,
  APPROVED_LIMIT ,
  APPROVED_FREE_LIMIT ,
  APPROVED_USED_LIMIT ,
  PRODUCT_LEVEL ,
  PRE_OCCUPATION_AMT ,
  SUPER_PRODUCT_CD ,
  CREDIT_TERM ,
  CREDIT_TERM_CD ,
  IS_COMPANY_SPECIAL_LIMIT ,
  USED_CURRENCY_CD ,
  STATE ,
  INVALIDDATE ,
  IS_SPECIAL_CREDIT ,
  LIMIT_MODE ,
  SPECIAL_TYPE ,
  USED_CURRENCY_NAME ,
  FROZEN ,
  CREDIT_RISK_LIMIT ,
  CREDIT_APPROVE_RISK_LIMIT ,
  AVAILABLE_RISK_LIMIT ,
  OCCU_RISK_LIMIT ,
  GUARANTY_TYPE_APPL ,
  GUARANTY_TYPE_APPR ,
  TERM_APPL ,
  TERM_UNIT_CD_APPL ,
  CIRCULAR_APPL ,
  IS_SPECIAL_CREDIT_APPL ,
  CURRENCY_APPL ,
  INTER_CHANGABLE_APPL ,
  PRE_OCCUPY_RISK_LIMIT ,
  USED_CURRENCY_NAME_APPR ,
  USED_GUARANTY_NAME_APPL ,
  USED_GUARANTY_NAME_APPR ,
  CONST_CREDIT_LIMIT_NUM ,
  IS_OLD ,
  APPROVED_LIMIT_OLD ,
  FXBS_TIME_MARK ,
  CORE_ENTERPRISE_DUTY_CD ,
  IF_DIRECT_CREDIT_FLAG ,
  BUYER_SELLER_FLAG ,
  OLD_PRODUCT_LIMIT_ID ,
  OLD_CUR_LIMIT_APPROVED_LIMIT ,
  BATCH_APPROVED_USED_AMT ,
  OLD_CUR_LIMIT_RISK_LIMIT 
 FROM dw_sdata.CCS_004_TB_CRD_PRODUCT_LIMIT 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.PRODUCT_LIMIT_ID = T.PRODUCT_LIMIT_ID
WHERE
(T.PRODUCT_LIMIT_ID IS NULL)
 OR N.CREDIT_LIMIT_NUM<>T.CREDIT_LIMIT_NUM
 OR N.PRODUCT_CD<>T.PRODUCT_CD
 OR N.CURRENCY<>T.CURRENCY
 OR N.PRODUCT_CREDIT_LIMIT<>T.PRODUCT_CREDIT_LIMIT
 OR N.ADJUSTMENT_FACTOR<>T.ADJUSTMENT_FACTOR
 OR N.START_DATE<>T.START_DATE
 OR N.END_DATE<>T.END_DATE
 OR N.TERM<>T.TERM
 OR N.APPROVE_CREDIT_LIMIT<>T.APPROVE_CREDIT_LIMIT
 OR N.EXCHANGE_RATE<>T.EXCHANGE_RATE
 OR N.TERM_UNIT_CD<>T.TERM_UNIT_CD
 OR N.FREEZED_LIMIT<>T.FREEZED_LIMIT
 OR N.CIRCULAR<>T.CIRCULAR
 OR N.INTER_CHANGABLE<>T.INTER_CHANGABLE
 OR N.INTER_CHANGE_GROUP<>T.INTER_CHANGE_GROUP
 OR N.LIMIT_ID<>T.LIMIT_ID
 OR N.GRACE_PERIOD<>T.GRACE_PERIOD
 OR N.GRACE_PERIOD_UNIT<>T.GRACE_PERIOD_UNIT
 OR N.APPROVED_LIMIT<>T.APPROVED_LIMIT
 OR N.APPROVED_FREE_LIMIT<>T.APPROVED_FREE_LIMIT
 OR N.APPROVED_USED_LIMIT<>T.APPROVED_USED_LIMIT
 OR N.PRODUCT_LEVEL<>T.PRODUCT_LEVEL
 OR N.PRE_OCCUPATION_AMT<>T.PRE_OCCUPATION_AMT
 OR N.SUPER_PRODUCT_CD<>T.SUPER_PRODUCT_CD
 OR N.CREDIT_TERM<>T.CREDIT_TERM
 OR N.CREDIT_TERM_CD<>T.CREDIT_TERM_CD
 OR N.IS_COMPANY_SPECIAL_LIMIT<>T.IS_COMPANY_SPECIAL_LIMIT
 OR N.USED_CURRENCY_CD<>T.USED_CURRENCY_CD
 OR N.STATE<>T.STATE
 OR N.INVALIDDATE<>T.INVALIDDATE
 OR N.IS_SPECIAL_CREDIT<>T.IS_SPECIAL_CREDIT
 OR N.LIMIT_MODE<>T.LIMIT_MODE
 OR N.SPECIAL_TYPE<>T.SPECIAL_TYPE
 OR N.USED_CURRENCY_NAME<>T.USED_CURRENCY_NAME
 OR N.FROZEN<>T.FROZEN
 OR N.CREDIT_RISK_LIMIT<>T.CREDIT_RISK_LIMIT
 OR N.CREDIT_APPROVE_RISK_LIMIT<>T.CREDIT_APPROVE_RISK_LIMIT
 OR N.AVAILABLE_RISK_LIMIT<>T.AVAILABLE_RISK_LIMIT
 OR N.OCCU_RISK_LIMIT<>T.OCCU_RISK_LIMIT
 OR N.GUARANTY_TYPE_APPL<>T.GUARANTY_TYPE_APPL
 OR N.GUARANTY_TYPE_APPR<>T.GUARANTY_TYPE_APPR
 OR N.TERM_APPL<>T.TERM_APPL
 OR N.TERM_UNIT_CD_APPL<>T.TERM_UNIT_CD_APPL
 OR N.CIRCULAR_APPL<>T.CIRCULAR_APPL
 OR N.IS_SPECIAL_CREDIT_APPL<>T.IS_SPECIAL_CREDIT_APPL
 OR N.CURRENCY_APPL<>T.CURRENCY_APPL
 OR N.INTER_CHANGABLE_APPL<>T.INTER_CHANGABLE_APPL
 OR N.PRE_OCCUPY_RISK_LIMIT<>T.PRE_OCCUPY_RISK_LIMIT
 OR N.USED_CURRENCY_NAME_APPR<>T.USED_CURRENCY_NAME_APPR
 OR N.USED_GUARANTY_NAME_APPL<>T.USED_GUARANTY_NAME_APPL
 OR N.USED_GUARANTY_NAME_APPR<>T.USED_GUARANTY_NAME_APPR
 OR N.CONST_CREDIT_LIMIT_NUM<>T.CONST_CREDIT_LIMIT_NUM
 OR N.IS_OLD<>T.IS_OLD
 OR N.APPROVED_LIMIT_OLD<>T.APPROVED_LIMIT_OLD
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.CORE_ENTERPRISE_DUTY_CD<>T.CORE_ENTERPRISE_DUTY_CD
 OR N.IF_DIRECT_CREDIT_FLAG<>T.IF_DIRECT_CREDIT_FLAG
 OR N.BUYER_SELLER_FLAG<>T.BUYER_SELLER_FLAG
 OR N.OLD_PRODUCT_LIMIT_ID<>T.OLD_PRODUCT_LIMIT_ID
 OR N.OLD_CUR_LIMIT_APPROVED_LIMIT<>T.OLD_CUR_LIMIT_APPROVED_LIMIT
 OR N.BATCH_APPROVED_USED_AMT<>T.BATCH_APPROVED_USED_AMT
 OR N.OLD_CUR_LIMIT_RISK_LIMIT<>T.OLD_CUR_LIMIT_RISK_LIMIT
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_CRD_PRODUCT_LIMIT P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_118
WHERE P.End_Dt=DATE('2100-12-31')
AND P.PRODUCT_LIMIT_ID=T_118.PRODUCT_LIMIT_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_CRD_PRODUCT_LIMIT SELECT * FROM T_118;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
