#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_006_RAPFN0 WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_006_RAPFN0 SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_141 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_006_RAPFN0 WHERE 1=0;

--Step2:
INSERT  INTO T_141 (
  RAN0PRE,
  RAN0DPNOK,
  RAN0DPNOA,
  RAN0TRFROM,
  RAN0CONTNO,
  RAN0DUEBNO,
  RAN0AMT,
  RAN0DATEB,
  RAN0DATEE,
  RAN0STAT,
  RAN0CUR,
  RAN0LNCLS,
  RAN0LNCATG,
  RAN0TERM,
  RAN0TOTCNT,
  RAN0CASPAN,
  RAN0CATYPE,
  RAN0PAYTYP,
  RAN0LNTYPE,
  RAN0TERMD,
  RAN0ITRTDP,
  RAN0USEFLG,
  RAN0ITRTN,
  RAN0ITRTO,
  RAN0NOITRT,
  RAN0ACNOT,
  RAN0ACIDP,
  RAN0NAME,
  RAN0HNAME,
  RAN0SICOD,
  RAN0TXITRT,
  RAN0ENDATE,
  RAN0DATEPR,
  RAN0DATECA,
  RAN0JTDATE,
  RAN0NXDATE,
  RAN0STOPC,
  RAN0DATESC,
  RAN0TTCNT,
  RAN0CID,
  RAN0DATES,
  RAN0CHGPRB,
  RAN0BGDATE,
  RAN0YQBAL,
  RAN0FIVECL,
  RAN0STATD,
  RAN0SUDATE,
  RAN0SXDATE,
  RAN0DATED,
  RAN0TAMT1,
  RAN0TAMT2,
  RAN0ACIDN,
  RAN0ACIDO,
  RAN0ACIDD,
  RAN0ACIDBD,
  RAN0ACIDIN,
  RAN0ACIDOT,
  RAN0ACIDSI,
  RAN0ACIDO1,
  RAN0ACIDXP,
  RAN0ACIDXA,
  RAN0ACIDYA,
  RAN0ACIDYB,
  RAN0XACIDX,
  RAN0ZACIDZ,
  RAN0YACIDY,
  RAN0ACIDYC,
  RAN0ACIDYD,
  RAN0ACIDYE,
  RAN0ACIDYF,
  RAN0WACIDW,
  RAN0ACIDYG,
  RAN0ACIDYH,
  RAN0ACIDYJ,
  RAN0ACIDYK,
  RAN0BL,
  RAN0TXACNO,
  RAN0YQNO,
  RAN0XTNO,
  RAN0ACNOB,
  RAN0XYNO,
  RAN0JRBZ,
  RAN0PRCODE,
  RAN0BL1,
  RAN0BL2,
  RAN0BL3,
  RAN0BL4,
  RAN0BL5,
  RAN0WAMT2,
  RAN0WAMT1,
  RAN0WAMT3,
  RAN0WAMT4,
  RAN0WAMT5,
  RAN0DATELA,
  RAN0DPNOS,
  RAN0OPR,
  RAN0STAN,
  RAN0ASFLAG,
  RAN0ARFLAG,
  RAN0RLFLAG,
  RAN0WDPAC,
  RAN0FNAME,
  RAN0DSNAME,
  RAN0CUSNO,
  RAN0FRDATE,
  RAN0ACIDXL,
  RAN0ACIDXF,
  RAN0TYDATE,
  start_dt,
  end_dt)
SELECT
  N.RAN0PRE,
  N.RAN0DPNOK,
  N.RAN0DPNOA,
  N.RAN0TRFROM,
  N.RAN0CONTNO,
  N.RAN0DUEBNO,
  N.RAN0AMT,
  N.RAN0DATEB,
  N.RAN0DATEE,
  N.RAN0STAT,
  N.RAN0CUR,
  N.RAN0LNCLS,
  N.RAN0LNCATG,
  N.RAN0TERM,
  N.RAN0TOTCNT,
  N.RAN0CASPAN,
  N.RAN0CATYPE,
  N.RAN0PAYTYP,
  N.RAN0LNTYPE,
  N.RAN0TERMD,
  N.RAN0ITRTDP,
  N.RAN0USEFLG,
  N.RAN0ITRTN,
  N.RAN0ITRTO,
  N.RAN0NOITRT,
  N.RAN0ACNOT,
  N.RAN0ACIDP,
  N.RAN0NAME,
  N.RAN0HNAME,
  N.RAN0SICOD,
  N.RAN0TXITRT,
  N.RAN0ENDATE,
  N.RAN0DATEPR,
  N.RAN0DATECA,
  N.RAN0JTDATE,
  N.RAN0NXDATE,
  N.RAN0STOPC,
  N.RAN0DATESC,
  N.RAN0TTCNT,
  N.RAN0CID,
  N.RAN0DATES,
  N.RAN0CHGPRB,
  N.RAN0BGDATE,
  N.RAN0YQBAL,
  N.RAN0FIVECL,
  N.RAN0STATD,
  N.RAN0SUDATE,
  N.RAN0SXDATE,
  N.RAN0DATED,
  N.RAN0TAMT1,
  N.RAN0TAMT2,
  N.RAN0ACIDN,
  N.RAN0ACIDO,
  N.RAN0ACIDD,
  N.RAN0ACIDBD,
  N.RAN0ACIDIN,
  N.RAN0ACIDOT,
  N.RAN0ACIDSI,
  N.RAN0ACIDO1,
  N.RAN0ACIDXP,
  N.RAN0ACIDXA,
  N.RAN0ACIDYA,
  N.RAN0ACIDYB,
  N.RAN0XACIDX,
  N.RAN0ZACIDZ,
  N.RAN0YACIDY,
  N.RAN0ACIDYC,
  N.RAN0ACIDYD,
  N.RAN0ACIDYE,
  N.RAN0ACIDYF,
  N.RAN0WACIDW,
  N.RAN0ACIDYG,
  N.RAN0ACIDYH,
  N.RAN0ACIDYJ,
  N.RAN0ACIDYK,
  N.RAN0BL,
  N.RAN0TXACNO,
  N.RAN0YQNO,
  N.RAN0XTNO,
  N.RAN0ACNOB,
  N.RAN0XYNO,
  N.RAN0JRBZ,
  N.RAN0PRCODE,
  N.RAN0BL1,
  N.RAN0BL2,
  N.RAN0BL3,
  N.RAN0BL4,
  N.RAN0BL5,
  N.RAN0WAMT2,
  N.RAN0WAMT1,
  N.RAN0WAMT3,
  N.RAN0WAMT4,
  N.RAN0WAMT5,
  N.RAN0DATELA,
  N.RAN0DPNOS,
  N.RAN0OPR,
  N.RAN0STAN,
  N.RAN0ASFLAG,
  N.RAN0ARFLAG,
  N.RAN0RLFLAG,
  N.RAN0WDPAC,
  N.RAN0FNAME,
  N.RAN0DSNAME,
  N.RAN0CUSNO,
  N.RAN0FRDATE,
  N.RAN0ACIDXL,
  N.RAN0ACIDXF,
  N.RAN0TYDATE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(RAN0PRE, '' ) AS RAN0PRE ,
  COALESCE(RAN0DPNOK, '' ) AS RAN0DPNOK ,
  COALESCE(RAN0DPNOA, '' ) AS RAN0DPNOA ,
  COALESCE(RAN0TRFROM, '' ) AS RAN0TRFROM ,
  COALESCE(RAN0CONTNO, '' ) AS RAN0CONTNO ,
  COALESCE(RAN0DUEBNO, '' ) AS RAN0DUEBNO ,
  COALESCE(RAN0AMT, 0 ) AS RAN0AMT ,
  COALESCE(RAN0DATEB, '' ) AS RAN0DATEB ,
  COALESCE(RAN0DATEE, '' ) AS RAN0DATEE ,
  COALESCE(RAN0STAT, '' ) AS RAN0STAT ,
  COALESCE(RAN0CUR, '' ) AS RAN0CUR ,
  COALESCE(RAN0LNCLS, '' ) AS RAN0LNCLS ,
  COALESCE(RAN0LNCATG, '' ) AS RAN0LNCATG ,
  COALESCE(RAN0TERM, 0 ) AS RAN0TERM ,
  COALESCE(RAN0TOTCNT, 0 ) AS RAN0TOTCNT ,
  COALESCE(RAN0CASPAN, '' ) AS RAN0CASPAN ,
  COALESCE(RAN0CATYPE, '' ) AS RAN0CATYPE ,
  COALESCE(RAN0PAYTYP, '' ) AS RAN0PAYTYP ,
  COALESCE(RAN0LNTYPE, '' ) AS RAN0LNTYPE ,
  COALESCE(RAN0TERMD, '' ) AS RAN0TERMD ,
  COALESCE(RAN0ITRTDP, '' ) AS RAN0ITRTDP ,
  COALESCE(RAN0USEFLG, '' ) AS RAN0USEFLG ,
  COALESCE(RAN0ITRTN, 0 ) AS RAN0ITRTN ,
  COALESCE(RAN0ITRTO, 0 ) AS RAN0ITRTO ,
  COALESCE(RAN0NOITRT, 0 ) AS RAN0NOITRT ,
  COALESCE(RAN0ACNOT, '' ) AS RAN0ACNOT ,
  COALESCE(RAN0ACIDP, '' ) AS RAN0ACIDP ,
  COALESCE(RAN0NAME, '' ) AS RAN0NAME ,
  COALESCE(RAN0HNAME, '' ) AS RAN0HNAME ,
  COALESCE(RAN0SICOD, '' ) AS RAN0SICOD ,
  COALESCE(RAN0TXITRT, 0 ) AS RAN0TXITRT ,
  COALESCE(RAN0ENDATE, '' ) AS RAN0ENDATE ,
  COALESCE(RAN0DATEPR, '' ) AS RAN0DATEPR ,
  COALESCE(RAN0DATECA, '' ) AS RAN0DATECA ,
  COALESCE(RAN0JTDATE, '' ) AS RAN0JTDATE ,
  COALESCE(RAN0NXDATE, '' ) AS RAN0NXDATE ,
  COALESCE(RAN0STOPC, '' ) AS RAN0STOPC ,
  COALESCE(RAN0DATESC, '' ) AS RAN0DATESC ,
  COALESCE(RAN0TTCNT, 0 ) AS RAN0TTCNT ,
  COALESCE(RAN0CID, 0 ) AS RAN0CID ,
  COALESCE(RAN0DATES, '' ) AS RAN0DATES ,
  COALESCE(RAN0CHGPRB, '' ) AS RAN0CHGPRB ,
  COALESCE(RAN0BGDATE, '' ) AS RAN0BGDATE ,
  COALESCE(RAN0YQBAL, 0 ) AS RAN0YQBAL ,
  COALESCE(RAN0FIVECL, '' ) AS RAN0FIVECL ,
  COALESCE(RAN0STATD, '' ) AS RAN0STATD ,
  COALESCE(RAN0SUDATE, '' ) AS RAN0SUDATE ,
  COALESCE(RAN0SXDATE, '' ) AS RAN0SXDATE ,
  COALESCE(RAN0DATED, '' ) AS RAN0DATED ,
  COALESCE(RAN0TAMT1, 0 ) AS RAN0TAMT1 ,
  COALESCE(RAN0TAMT2, 0 ) AS RAN0TAMT2 ,
  COALESCE(RAN0ACIDN, 0 ) AS RAN0ACIDN ,
  COALESCE(RAN0ACIDO, 0 ) AS RAN0ACIDO ,
  COALESCE(RAN0ACIDD, 0 ) AS RAN0ACIDD ,
  COALESCE(RAN0ACIDBD, 0 ) AS RAN0ACIDBD ,
  COALESCE(RAN0ACIDIN, 0 ) AS RAN0ACIDIN ,
  COALESCE(RAN0ACIDOT, 0 ) AS RAN0ACIDOT ,
  COALESCE(RAN0ACIDSI, 0 ) AS RAN0ACIDSI ,
  COALESCE(RAN0ACIDO1, 0 ) AS RAN0ACIDO1 ,
  COALESCE(RAN0ACIDXP, 0 ) AS RAN0ACIDXP ,
  COALESCE(RAN0ACIDXA, 0 ) AS RAN0ACIDXA ,
  COALESCE(RAN0ACIDYA, 0 ) AS RAN0ACIDYA ,
  COALESCE(RAN0ACIDYB, 0 ) AS RAN0ACIDYB ,
  COALESCE(RAN0XACIDX, 0 ) AS RAN0XACIDX ,
  COALESCE(RAN0ZACIDZ, 0 ) AS RAN0ZACIDZ ,
  COALESCE(RAN0YACIDY, 0 ) AS RAN0YACIDY ,
  COALESCE(RAN0ACIDYC, 0 ) AS RAN0ACIDYC ,
  COALESCE(RAN0ACIDYD, 0 ) AS RAN0ACIDYD ,
  COALESCE(RAN0ACIDYE, 0 ) AS RAN0ACIDYE ,
  COALESCE(RAN0ACIDYF, 0 ) AS RAN0ACIDYF ,
  COALESCE(RAN0WACIDW, 0 ) AS RAN0WACIDW ,
  COALESCE(RAN0ACIDYG, 0 ) AS RAN0ACIDYG ,
  COALESCE(RAN0ACIDYH, 0 ) AS RAN0ACIDYH ,
  COALESCE(RAN0ACIDYJ, 0 ) AS RAN0ACIDYJ ,
  COALESCE(RAN0ACIDYK, 0 ) AS RAN0ACIDYK ,
  COALESCE(RAN0BL, 0 ) AS RAN0BL ,
  COALESCE(RAN0TXACNO, '' ) AS RAN0TXACNO ,
  COALESCE(RAN0YQNO, '' ) AS RAN0YQNO ,
  COALESCE(RAN0XTNO, '' ) AS RAN0XTNO ,
  COALESCE(RAN0ACNOB, '' ) AS RAN0ACNOB ,
  COALESCE(RAN0XYNO, '' ) AS RAN0XYNO ,
  COALESCE(RAN0JRBZ, '' ) AS RAN0JRBZ ,
  COALESCE(RAN0PRCODE, '' ) AS RAN0PRCODE ,
  COALESCE(RAN0BL1, '' ) AS RAN0BL1 ,
  COALESCE(RAN0BL2, '' ) AS RAN0BL2 ,
  COALESCE(RAN0BL3, '' ) AS RAN0BL3 ,
  COALESCE(RAN0BL4, '' ) AS RAN0BL4 ,
  COALESCE(RAN0BL5, '' ) AS RAN0BL5 ,
  COALESCE(RAN0WAMT2, 0 ) AS RAN0WAMT2 ,
  COALESCE(RAN0WAMT1, 0 ) AS RAN0WAMT1 ,
  COALESCE(RAN0WAMT3, 0 ) AS RAN0WAMT3 ,
  COALESCE(RAN0WAMT4, 0 ) AS RAN0WAMT4 ,
  COALESCE(RAN0WAMT5, 0 ) AS RAN0WAMT5 ,
  COALESCE(RAN0DATELA, '' ) AS RAN0DATELA ,
  COALESCE(RAN0DPNOS, '' ) AS RAN0DPNOS ,
  COALESCE(RAN0OPR, '' ) AS RAN0OPR ,
  COALESCE(RAN0STAN, 0 ) AS RAN0STAN ,
  COALESCE(RAN0ASFLAG, '' ) AS RAN0ASFLAG ,
  COALESCE(RAN0ARFLAG, '' ) AS RAN0ARFLAG ,
  COALESCE(RAN0RLFLAG, '' ) AS RAN0RLFLAG ,
  COALESCE(RAN0WDPAC, '' ) AS RAN0WDPAC ,
  COALESCE(RAN0FNAME, '' ) AS RAN0FNAME ,
  COALESCE(RAN0DSNAME, '' ) AS RAN0DSNAME ,
  COALESCE(RAN0CUSNO, '' ) AS RAN0CUSNO ,
  COALESCE(RAN0FRDATE, '' ) AS RAN0FRDATE ,
  COALESCE(RAN0ACIDXL, 0 ) AS RAN0ACIDXL ,
  COALESCE(RAN0ACIDXF, 0 ) AS RAN0ACIDXF ,
  COALESCE(RAN0TYDATE, '' ) AS RAN0TYDATE 
 FROM  dw_tdata.CCS_006_RAPFN0_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  RAN0PRE ,
  RAN0DPNOK ,
  RAN0DPNOA ,
  RAN0TRFROM ,
  RAN0CONTNO ,
  RAN0DUEBNO ,
  RAN0AMT ,
  RAN0DATEB ,
  RAN0DATEE ,
  RAN0STAT ,
  RAN0CUR ,
  RAN0LNCLS ,
  RAN0LNCATG ,
  RAN0TERM ,
  RAN0TOTCNT ,
  RAN0CASPAN ,
  RAN0CATYPE ,
  RAN0PAYTYP ,
  RAN0LNTYPE ,
  RAN0TERMD ,
  RAN0ITRTDP ,
  RAN0USEFLG ,
  RAN0ITRTN ,
  RAN0ITRTO ,
  RAN0NOITRT ,
  RAN0ACNOT ,
  RAN0ACIDP ,
  RAN0NAME ,
  RAN0HNAME ,
  RAN0SICOD ,
  RAN0TXITRT ,
  RAN0ENDATE ,
  RAN0DATEPR ,
  RAN0DATECA ,
  RAN0JTDATE ,
  RAN0NXDATE ,
  RAN0STOPC ,
  RAN0DATESC ,
  RAN0TTCNT ,
  RAN0CID ,
  RAN0DATES ,
  RAN0CHGPRB ,
  RAN0BGDATE ,
  RAN0YQBAL ,
  RAN0FIVECL ,
  RAN0STATD ,
  RAN0SUDATE ,
  RAN0SXDATE ,
  RAN0DATED ,
  RAN0TAMT1 ,
  RAN0TAMT2 ,
  RAN0ACIDN ,
  RAN0ACIDO ,
  RAN0ACIDD ,
  RAN0ACIDBD ,
  RAN0ACIDIN ,
  RAN0ACIDOT ,
  RAN0ACIDSI ,
  RAN0ACIDO1 ,
  RAN0ACIDXP ,
  RAN0ACIDXA ,
  RAN0ACIDYA ,
  RAN0ACIDYB ,
  RAN0XACIDX ,
  RAN0ZACIDZ ,
  RAN0YACIDY ,
  RAN0ACIDYC ,
  RAN0ACIDYD ,
  RAN0ACIDYE ,
  RAN0ACIDYF ,
  RAN0WACIDW ,
  RAN0ACIDYG ,
  RAN0ACIDYH ,
  RAN0ACIDYJ ,
  RAN0ACIDYK ,
  RAN0BL ,
  RAN0TXACNO ,
  RAN0YQNO ,
  RAN0XTNO ,
  RAN0ACNOB ,
  RAN0XYNO ,
  RAN0JRBZ ,
  RAN0PRCODE ,
  RAN0BL1 ,
  RAN0BL2 ,
  RAN0BL3 ,
  RAN0BL4 ,
  RAN0BL5 ,
  RAN0WAMT2 ,
  RAN0WAMT1 ,
  RAN0WAMT3 ,
  RAN0WAMT4 ,
  RAN0WAMT5 ,
  RAN0DATELA ,
  RAN0DPNOS ,
  RAN0OPR ,
  RAN0STAN ,
  RAN0ASFLAG ,
  RAN0ARFLAG ,
  RAN0RLFLAG ,
  RAN0WDPAC ,
  RAN0FNAME ,
  RAN0DSNAME ,
  RAN0CUSNO ,
  RAN0FRDATE ,
  RAN0ACIDXL ,
  RAN0ACIDXF ,
  RAN0TYDATE 
 FROM dw_sdata.CCS_006_RAPFN0 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.RAN0DUEBNO = T.RAN0DUEBNO
WHERE
(T.RAN0DUEBNO IS NULL)
 OR N.RAN0PRE<>T.RAN0PRE
 OR N.RAN0DPNOK<>T.RAN0DPNOK
 OR N.RAN0DPNOA<>T.RAN0DPNOA
 OR N.RAN0TRFROM<>T.RAN0TRFROM
 OR N.RAN0CONTNO<>T.RAN0CONTNO
 OR N.RAN0AMT<>T.RAN0AMT
 OR N.RAN0DATEB<>T.RAN0DATEB
 OR N.RAN0DATEE<>T.RAN0DATEE
 OR N.RAN0STAT<>T.RAN0STAT
 OR N.RAN0CUR<>T.RAN0CUR
 OR N.RAN0LNCLS<>T.RAN0LNCLS
 OR N.RAN0LNCATG<>T.RAN0LNCATG
 OR N.RAN0TERM<>T.RAN0TERM
 OR N.RAN0TOTCNT<>T.RAN0TOTCNT
 OR N.RAN0CASPAN<>T.RAN0CASPAN
 OR N.RAN0CATYPE<>T.RAN0CATYPE
 OR N.RAN0PAYTYP<>T.RAN0PAYTYP
 OR N.RAN0LNTYPE<>T.RAN0LNTYPE
 OR N.RAN0TERMD<>T.RAN0TERMD
 OR N.RAN0ITRTDP<>T.RAN0ITRTDP
 OR N.RAN0USEFLG<>T.RAN0USEFLG
 OR N.RAN0ITRTN<>T.RAN0ITRTN
 OR N.RAN0ITRTO<>T.RAN0ITRTO
 OR N.RAN0NOITRT<>T.RAN0NOITRT
 OR N.RAN0ACNOT<>T.RAN0ACNOT
 OR N.RAN0ACIDP<>T.RAN0ACIDP
 OR N.RAN0NAME<>T.RAN0NAME
 OR N.RAN0HNAME<>T.RAN0HNAME
 OR N.RAN0SICOD<>T.RAN0SICOD
 OR N.RAN0TXITRT<>T.RAN0TXITRT
 OR N.RAN0ENDATE<>T.RAN0ENDATE
 OR N.RAN0DATEPR<>T.RAN0DATEPR
 OR N.RAN0DATECA<>T.RAN0DATECA
 OR N.RAN0JTDATE<>T.RAN0JTDATE
 OR N.RAN0NXDATE<>T.RAN0NXDATE
 OR N.RAN0STOPC<>T.RAN0STOPC
 OR N.RAN0DATESC<>T.RAN0DATESC
 OR N.RAN0TTCNT<>T.RAN0TTCNT
 OR N.RAN0CID<>T.RAN0CID
 OR N.RAN0DATES<>T.RAN0DATES
 OR N.RAN0CHGPRB<>T.RAN0CHGPRB
 OR N.RAN0BGDATE<>T.RAN0BGDATE
 OR N.RAN0YQBAL<>T.RAN0YQBAL
 OR N.RAN0FIVECL<>T.RAN0FIVECL
 OR N.RAN0STATD<>T.RAN0STATD
 OR N.RAN0SUDATE<>T.RAN0SUDATE
 OR N.RAN0SXDATE<>T.RAN0SXDATE
 OR N.RAN0DATED<>T.RAN0DATED
 OR N.RAN0TAMT1<>T.RAN0TAMT1
 OR N.RAN0TAMT2<>T.RAN0TAMT2
 OR N.RAN0ACIDN<>T.RAN0ACIDN
 OR N.RAN0ACIDO<>T.RAN0ACIDO
 OR N.RAN0ACIDD<>T.RAN0ACIDD
 OR N.RAN0ACIDBD<>T.RAN0ACIDBD
 OR N.RAN0ACIDIN<>T.RAN0ACIDIN
 OR N.RAN0ACIDOT<>T.RAN0ACIDOT
 OR N.RAN0ACIDSI<>T.RAN0ACIDSI
 OR N.RAN0ACIDO1<>T.RAN0ACIDO1
 OR N.RAN0ACIDXP<>T.RAN0ACIDXP
 OR N.RAN0ACIDXA<>T.RAN0ACIDXA
 OR N.RAN0ACIDYA<>T.RAN0ACIDYA
 OR N.RAN0ACIDYB<>T.RAN0ACIDYB
 OR N.RAN0XACIDX<>T.RAN0XACIDX
 OR N.RAN0ZACIDZ<>T.RAN0ZACIDZ
 OR N.RAN0YACIDY<>T.RAN0YACIDY
 OR N.RAN0ACIDYC<>T.RAN0ACIDYC
 OR N.RAN0ACIDYD<>T.RAN0ACIDYD
 OR N.RAN0ACIDYE<>T.RAN0ACIDYE
 OR N.RAN0ACIDYF<>T.RAN0ACIDYF
 OR N.RAN0WACIDW<>T.RAN0WACIDW
 OR N.RAN0ACIDYG<>T.RAN0ACIDYG
 OR N.RAN0ACIDYH<>T.RAN0ACIDYH
 OR N.RAN0ACIDYJ<>T.RAN0ACIDYJ
 OR N.RAN0ACIDYK<>T.RAN0ACIDYK
 OR N.RAN0BL<>T.RAN0BL
 OR N.RAN0TXACNO<>T.RAN0TXACNO
 OR N.RAN0YQNO<>T.RAN0YQNO
 OR N.RAN0XTNO<>T.RAN0XTNO
 OR N.RAN0ACNOB<>T.RAN0ACNOB
 OR N.RAN0XYNO<>T.RAN0XYNO
 OR N.RAN0JRBZ<>T.RAN0JRBZ
 OR N.RAN0PRCODE<>T.RAN0PRCODE
 OR N.RAN0BL1<>T.RAN0BL1
 OR N.RAN0BL2<>T.RAN0BL2
 OR N.RAN0BL3<>T.RAN0BL3
 OR N.RAN0BL4<>T.RAN0BL4
 OR N.RAN0BL5<>T.RAN0BL5
 OR N.RAN0WAMT2<>T.RAN0WAMT2
 OR N.RAN0WAMT1<>T.RAN0WAMT1
 OR N.RAN0WAMT3<>T.RAN0WAMT3
 OR N.RAN0WAMT4<>T.RAN0WAMT4
 OR N.RAN0WAMT5<>T.RAN0WAMT5
 OR N.RAN0DATELA<>T.RAN0DATELA
 OR N.RAN0DPNOS<>T.RAN0DPNOS
 OR N.RAN0OPR<>T.RAN0OPR
 OR N.RAN0STAN<>T.RAN0STAN
 OR N.RAN0ASFLAG<>T.RAN0ASFLAG
 OR N.RAN0ARFLAG<>T.RAN0ARFLAG
 OR N.RAN0RLFLAG<>T.RAN0RLFLAG
 OR N.RAN0WDPAC<>T.RAN0WDPAC
 OR N.RAN0FNAME<>T.RAN0FNAME
 OR N.RAN0DSNAME<>T.RAN0DSNAME
 OR N.RAN0CUSNO<>T.RAN0CUSNO
 OR N.RAN0FRDATE<>T.RAN0FRDATE
 OR N.RAN0ACIDXL<>T.RAN0ACIDXL
 OR N.RAN0ACIDXF<>T.RAN0ACIDXF
 OR N.RAN0TYDATE<>T.RAN0TYDATE
;

--Step3:
UPDATE dw_sdata.CCS_006_RAPFN0 P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_141
WHERE P.End_Dt=DATE('2100-12-31')
AND P.RAN0DUEBNO=T_141.RAN0DUEBNO
;

--Step4:
INSERT  INTO dw_sdata.CCS_006_RAPFN0 SELECT * FROM T_141;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
