#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.CCS_004_TB_GRT_COLLATERAL WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.CCS_004_TB_GRT_COLLATERAL SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_121 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.CCS_004_TB_GRT_COLLATERAL WHERE 1=0;

--Step2:
INSERT  INTO T_121 (
  GUARANTY_ID,
  COLLATERAL_TYPE_CD,
  PARTY_TYPE_CD,
  COLLATERAL_NUM,
  COLLATERAL_STATUS_CD,
  COLLATERAL_NAME,
  BOOK_VALUE,
  BOOK_NET_VALUE,
  MARKET_VALUE,
  EVAL_VALUE_CURRENCY_CD,
  EVAL_VALUE,
  CCB_ASSESSED_VALUE_CURRENCY_CD,
  CCB_ASSESSED_VALUE,
  ACQUIRE_WAY_OF_COLLATERAL_CD,
  COMMON_ASSETS_IND,
  COMMON_OWNER_NAME,
  WAY_GUARANTY_EFFECTIVE_CD,
  COLLATERAL_SETUP_IND,
  SET_GUARANTY_AMT_IN_CCB,
  RENTED_LICENSED_IND,
  RENTER_NAME,
  SET_GUARANTY_AMT_OUT_CCB,
  LEASE_EXPIRATION_DATE,
  CUSTOMER_NUM,
  SUBMITTING_DATE,
  CURRENCY_CD,
  COLLATERAL_DISPOSE,
  OTHER_NOTE,
  SET_GUARANTY_AMT,
  PROVINCE_CD,
  CITY_CD,
  DISTRICT_CD,
  STREET_ADDRESS,
  NATIONALITY_CD,
  MERCHANDISE_TYPE,
  RIGHT_CERT_TYPE_CD,
  RIGHT_CERTIFICATION_NUM,
  SYS_UPDATE_TIME,
  COLLATERAL_CATALOG_CD,
  DATA_CREAT_USER_NUM,
  DATA_CREATOR_ORG_CD,
  LAST_UPDATE_USER_NUM,
  LAST_UPDATE_ORG_CD,
  TAKEOVER_IND,
  ALL_PLEDGE_IND,
  FORBID_CIRCULATE_IND,
  NATIONALISATION_IND,
  PROPERTY_DISPUTED_IND,
  INVALID_IND,
  BLEMISH_IND,
  BLEMISH_NOTE,
  HANDOVER_DATE,
  K75ZCMS,
  KEEP_SPECIAL_REQ,
  VALUATOR,
  EVALUATE_DATE,
  ASSET_STATUS,
  CUSTOMER_TYPE,
  SETTLED_ASSETS_IND,
  TIME_MARK,
  IMPAWN_AMOUNT,
  IMPAWN_AMOUNT_CD,
  IMPAWN_EXPIRE_DATE,
  IMPAWN_GET_DATE,
  REGISTER_IND,
  COLLATERAL_CARD_DEPARTMENT,
  CUSTOMER_NAME,
  RATE_OF_DISCOUNT,
  PLEDGE_TYPE_CD,
  OUT_REASON,
  IF_OUT,
  OWNER_RATE,
  PAYOUT_SEND_NUM,
  VALUECHANGE_SEND_NUM,
  RSP_CODE,
  RSP_TIME,
  FXBS_TIME_MARK,
  COLL_MODEL,
  start_dt,
  end_dt)
SELECT
  N.GUARANTY_ID,
  N.COLLATERAL_TYPE_CD,
  N.PARTY_TYPE_CD,
  N.COLLATERAL_NUM,
  N.COLLATERAL_STATUS_CD,
  N.COLLATERAL_NAME,
  N.BOOK_VALUE,
  N.BOOK_NET_VALUE,
  N.MARKET_VALUE,
  N.EVAL_VALUE_CURRENCY_CD,
  N.EVAL_VALUE,
  N.CCB_ASSESSED_VALUE_CURRENCY_CD,
  N.CCB_ASSESSED_VALUE,
  N.ACQUIRE_WAY_OF_COLLATERAL_CD,
  N.COMMON_ASSETS_IND,
  N.COMMON_OWNER_NAME,
  N.WAY_GUARANTY_EFFECTIVE_CD,
  N.COLLATERAL_SETUP_IND,
  N.SET_GUARANTY_AMT_IN_CCB,
  N.RENTED_LICENSED_IND,
  N.RENTER_NAME,
  N.SET_GUARANTY_AMT_OUT_CCB,
  N.LEASE_EXPIRATION_DATE,
  N.CUSTOMER_NUM,
  N.SUBMITTING_DATE,
  N.CURRENCY_CD,
  N.COLLATERAL_DISPOSE,
  N.OTHER_NOTE,
  N.SET_GUARANTY_AMT,
  N.PROVINCE_CD,
  N.CITY_CD,
  N.DISTRICT_CD,
  N.STREET_ADDRESS,
  N.NATIONALITY_CD,
  N.MERCHANDISE_TYPE,
  N.RIGHT_CERT_TYPE_CD,
  N.RIGHT_CERTIFICATION_NUM,
  N.SYS_UPDATE_TIME,
  N.COLLATERAL_CATALOG_CD,
  N.DATA_CREAT_USER_NUM,
  N.DATA_CREATOR_ORG_CD,
  N.LAST_UPDATE_USER_NUM,
  N.LAST_UPDATE_ORG_CD,
  N.TAKEOVER_IND,
  N.ALL_PLEDGE_IND,
  N.FORBID_CIRCULATE_IND,
  N.NATIONALISATION_IND,
  N.PROPERTY_DISPUTED_IND,
  N.INVALID_IND,
  N.BLEMISH_IND,
  N.BLEMISH_NOTE,
  N.HANDOVER_DATE,
  N.K75ZCMS,
  N.KEEP_SPECIAL_REQ,
  N.VALUATOR,
  N.EVALUATE_DATE,
  N.ASSET_STATUS,
  N.CUSTOMER_TYPE,
  N.SETTLED_ASSETS_IND,
  N.TIME_MARK,
  N.IMPAWN_AMOUNT,
  N.IMPAWN_AMOUNT_CD,
  N.IMPAWN_EXPIRE_DATE,
  N.IMPAWN_GET_DATE,
  N.REGISTER_IND,
  N.COLLATERAL_CARD_DEPARTMENT,
  N.CUSTOMER_NAME,
  N.RATE_OF_DISCOUNT,
  N.PLEDGE_TYPE_CD,
  N.OUT_REASON,
  N.IF_OUT,
  N.OWNER_RATE,
  N.PAYOUT_SEND_NUM,
  N.VALUECHANGE_SEND_NUM,
  N.RSP_CODE,
  N.RSP_TIME,
  N.FXBS_TIME_MARK,
  N.COLL_MODEL,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(GUARANTY_ID, '' ) AS GUARANTY_ID ,
  COALESCE(COLLATERAL_TYPE_CD, '' ) AS COLLATERAL_TYPE_CD ,
  COALESCE(PARTY_TYPE_CD, '' ) AS PARTY_TYPE_CD ,
  COALESCE(COLLATERAL_NUM, '' ) AS COLLATERAL_NUM ,
  COALESCE(COLLATERAL_STATUS_CD, '' ) AS COLLATERAL_STATUS_CD ,
  COALESCE(COLLATERAL_NAME, '' ) AS COLLATERAL_NAME ,
  COALESCE(BOOK_VALUE, 0 ) AS BOOK_VALUE ,
  COALESCE(BOOK_NET_VALUE, 0 ) AS BOOK_NET_VALUE ,
  COALESCE(MARKET_VALUE, 0 ) AS MARKET_VALUE ,
  COALESCE(EVAL_VALUE_CURRENCY_CD, '' ) AS EVAL_VALUE_CURRENCY_CD ,
  COALESCE(EVAL_VALUE, 0 ) AS EVAL_VALUE ,
  COALESCE(CCB_ASSESSED_VALUE_CURRENCY_CD, '' ) AS CCB_ASSESSED_VALUE_CURRENCY_CD ,
  COALESCE(CCB_ASSESSED_VALUE, 0 ) AS CCB_ASSESSED_VALUE ,
  COALESCE(ACQUIRE_WAY_OF_COLLATERAL_CD, '' ) AS ACQUIRE_WAY_OF_COLLATERAL_CD ,
  COALESCE(COMMON_ASSETS_IND, '' ) AS COMMON_ASSETS_IND ,
  COALESCE(COMMON_OWNER_NAME, '' ) AS COMMON_OWNER_NAME ,
  COALESCE(WAY_GUARANTY_EFFECTIVE_CD, '' ) AS WAY_GUARANTY_EFFECTIVE_CD ,
  COALESCE(COLLATERAL_SETUP_IND, '' ) AS COLLATERAL_SETUP_IND ,
  COALESCE(SET_GUARANTY_AMT_IN_CCB, 0 ) AS SET_GUARANTY_AMT_IN_CCB ,
  COALESCE(RENTED_LICENSED_IND, '' ) AS RENTED_LICENSED_IND ,
  COALESCE(RENTER_NAME, '' ) AS RENTER_NAME ,
  COALESCE(SET_GUARANTY_AMT_OUT_CCB, 0 ) AS SET_GUARANTY_AMT_OUT_CCB ,
  COALESCE(LEASE_EXPIRATION_DATE,'4999-12-31 00:00:00' ) AS LEASE_EXPIRATION_DATE ,
  COALESCE(CUSTOMER_NUM, '' ) AS CUSTOMER_NUM ,
  COALESCE(SUBMITTING_DATE,'4999-12-31 00:00:00' ) AS SUBMITTING_DATE ,
  COALESCE(CURRENCY_CD, '' ) AS CURRENCY_CD ,
  COALESCE(COLLATERAL_DISPOSE, '' ) AS COLLATERAL_DISPOSE ,
  COALESCE(OTHER_NOTE, '' ) AS OTHER_NOTE ,
  COALESCE(SET_GUARANTY_AMT, 0 ) AS SET_GUARANTY_AMT ,
  COALESCE(PROVINCE_CD, '' ) AS PROVINCE_CD ,
  COALESCE(CITY_CD, '' ) AS CITY_CD ,
  COALESCE(DISTRICT_CD, '' ) AS DISTRICT_CD ,
  COALESCE(STREET_ADDRESS, '' ) AS STREET_ADDRESS ,
  COALESCE(NATIONALITY_CD, '' ) AS NATIONALITY_CD ,
  COALESCE(MERCHANDISE_TYPE, '' ) AS MERCHANDISE_TYPE ,
  COALESCE(RIGHT_CERT_TYPE_CD, '' ) AS RIGHT_CERT_TYPE_CD ,
  COALESCE(RIGHT_CERTIFICATION_NUM, '' ) AS RIGHT_CERTIFICATION_NUM ,
  COALESCE(SYS_UPDATE_TIME,'4999-12-31 00:00:00' ) AS SYS_UPDATE_TIME ,
  COALESCE(COLLATERAL_CATALOG_CD, '' ) AS COLLATERAL_CATALOG_CD ,
  COALESCE(DATA_CREAT_USER_NUM, '' ) AS DATA_CREAT_USER_NUM ,
  COALESCE(DATA_CREATOR_ORG_CD, '' ) AS DATA_CREATOR_ORG_CD ,
  COALESCE(LAST_UPDATE_USER_NUM, '' ) AS LAST_UPDATE_USER_NUM ,
  COALESCE(LAST_UPDATE_ORG_CD, '' ) AS LAST_UPDATE_ORG_CD ,
  COALESCE(TAKEOVER_IND, '' ) AS TAKEOVER_IND ,
  COALESCE(ALL_PLEDGE_IND, '' ) AS ALL_PLEDGE_IND ,
  COALESCE(FORBID_CIRCULATE_IND, '' ) AS FORBID_CIRCULATE_IND ,
  COALESCE(NATIONALISATION_IND, '' ) AS NATIONALISATION_IND ,
  COALESCE(PROPERTY_DISPUTED_IND, '' ) AS PROPERTY_DISPUTED_IND ,
  COALESCE(INVALID_IND, '' ) AS INVALID_IND ,
  COALESCE(BLEMISH_IND, '' ) AS BLEMISH_IND ,
  COALESCE(BLEMISH_NOTE, '' ) AS BLEMISH_NOTE ,
  COALESCE(HANDOVER_DATE,'4999-12-31 00:00:00' ) AS HANDOVER_DATE ,
  COALESCE(K75ZCMS, '' ) AS K75ZCMS ,
  COALESCE(KEEP_SPECIAL_REQ, '' ) AS KEEP_SPECIAL_REQ ,
  COALESCE(VALUATOR, '' ) AS VALUATOR ,
  COALESCE(EVALUATE_DATE,'4999-12-31 00:00:00' ) AS EVALUATE_DATE ,
  COALESCE(ASSET_STATUS, '' ) AS ASSET_STATUS ,
  COALESCE(CUSTOMER_TYPE, '' ) AS CUSTOMER_TYPE ,
  COALESCE(SETTLED_ASSETS_IND, '' ) AS SETTLED_ASSETS_IND ,
  COALESCE(TIME_MARK,'4999-12-31 00:00:00' ) AS TIME_MARK ,
  COALESCE(IMPAWN_AMOUNT, 0 ) AS IMPAWN_AMOUNT ,
  COALESCE(IMPAWN_AMOUNT_CD, '' ) AS IMPAWN_AMOUNT_CD ,
  COALESCE(IMPAWN_EXPIRE_DATE,'4999-12-31 00:00:00' ) AS IMPAWN_EXPIRE_DATE ,
  COALESCE(IMPAWN_GET_DATE,'4999-12-31 00:00:00' ) AS IMPAWN_GET_DATE ,
  COALESCE(REGISTER_IND, '' ) AS REGISTER_IND ,
  COALESCE(COLLATERAL_CARD_DEPARTMENT, '' ) AS COLLATERAL_CARD_DEPARTMENT ,
  COALESCE(CUSTOMER_NAME, '' ) AS CUSTOMER_NAME ,
  COALESCE(RATE_OF_DISCOUNT, 0 ) AS RATE_OF_DISCOUNT ,
  COALESCE(PLEDGE_TYPE_CD, '' ) AS PLEDGE_TYPE_CD ,
  COALESCE(OUT_REASON, '' ) AS OUT_REASON ,
  COALESCE(IF_OUT, '' ) AS IF_OUT ,
  COALESCE(OWNER_RATE, 0 ) AS OWNER_RATE ,
  COALESCE(PAYOUT_SEND_NUM, '' ) AS PAYOUT_SEND_NUM ,
  COALESCE(VALUECHANGE_SEND_NUM, '' ) AS VALUECHANGE_SEND_NUM ,
  COALESCE(RSP_CODE, '' ) AS RSP_CODE ,
  COALESCE(RSP_TIME,'4999-12-31 00:00:00' ) AS RSP_TIME ,
  COALESCE(FXBS_TIME_MARK,'4999-12-31 00:00:00' ) AS FXBS_TIME_MARK ,
  COALESCE(COLL_MODEL, '' ) AS COLL_MODEL 
 FROM  dw_tdata.CCS_004_TB_GRT_COLLATERAL_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  GUARANTY_ID ,
  COLLATERAL_TYPE_CD ,
  PARTY_TYPE_CD ,
  COLLATERAL_NUM ,
  COLLATERAL_STATUS_CD ,
  COLLATERAL_NAME ,
  BOOK_VALUE ,
  BOOK_NET_VALUE ,
  MARKET_VALUE ,
  EVAL_VALUE_CURRENCY_CD ,
  EVAL_VALUE ,
  CCB_ASSESSED_VALUE_CURRENCY_CD ,
  CCB_ASSESSED_VALUE ,
  ACQUIRE_WAY_OF_COLLATERAL_CD ,
  COMMON_ASSETS_IND ,
  COMMON_OWNER_NAME ,
  WAY_GUARANTY_EFFECTIVE_CD ,
  COLLATERAL_SETUP_IND ,
  SET_GUARANTY_AMT_IN_CCB ,
  RENTED_LICENSED_IND ,
  RENTER_NAME ,
  SET_GUARANTY_AMT_OUT_CCB ,
  LEASE_EXPIRATION_DATE ,
  CUSTOMER_NUM ,
  SUBMITTING_DATE ,
  CURRENCY_CD ,
  COLLATERAL_DISPOSE ,
  OTHER_NOTE ,
  SET_GUARANTY_AMT ,
  PROVINCE_CD ,
  CITY_CD ,
  DISTRICT_CD ,
  STREET_ADDRESS ,
  NATIONALITY_CD ,
  MERCHANDISE_TYPE ,
  RIGHT_CERT_TYPE_CD ,
  RIGHT_CERTIFICATION_NUM ,
  SYS_UPDATE_TIME ,
  COLLATERAL_CATALOG_CD ,
  DATA_CREAT_USER_NUM ,
  DATA_CREATOR_ORG_CD ,
  LAST_UPDATE_USER_NUM ,
  LAST_UPDATE_ORG_CD ,
  TAKEOVER_IND ,
  ALL_PLEDGE_IND ,
  FORBID_CIRCULATE_IND ,
  NATIONALISATION_IND ,
  PROPERTY_DISPUTED_IND ,
  INVALID_IND ,
  BLEMISH_IND ,
  BLEMISH_NOTE ,
  HANDOVER_DATE ,
  K75ZCMS ,
  KEEP_SPECIAL_REQ ,
  VALUATOR ,
  EVALUATE_DATE ,
  ASSET_STATUS ,
  CUSTOMER_TYPE ,
  SETTLED_ASSETS_IND ,
  TIME_MARK ,
  IMPAWN_AMOUNT ,
  IMPAWN_AMOUNT_CD ,
  IMPAWN_EXPIRE_DATE ,
  IMPAWN_GET_DATE ,
  REGISTER_IND ,
  COLLATERAL_CARD_DEPARTMENT ,
  CUSTOMER_NAME ,
  RATE_OF_DISCOUNT ,
  PLEDGE_TYPE_CD ,
  OUT_REASON ,
  IF_OUT ,
  OWNER_RATE ,
  PAYOUT_SEND_NUM ,
  VALUECHANGE_SEND_NUM ,
  RSP_CODE ,
  RSP_TIME ,
  FXBS_TIME_MARK ,
  COLL_MODEL 
 FROM dw_sdata.CCS_004_TB_GRT_COLLATERAL 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.GUARANTY_ID = T.GUARANTY_ID
WHERE
(T.GUARANTY_ID IS NULL)
 OR N.COLLATERAL_TYPE_CD<>T.COLLATERAL_TYPE_CD
 OR N.PARTY_TYPE_CD<>T.PARTY_TYPE_CD
 OR N.COLLATERAL_NUM<>T.COLLATERAL_NUM
 OR N.COLLATERAL_STATUS_CD<>T.COLLATERAL_STATUS_CD
 OR N.COLLATERAL_NAME<>T.COLLATERAL_NAME
 OR N.BOOK_VALUE<>T.BOOK_VALUE
 OR N.BOOK_NET_VALUE<>T.BOOK_NET_VALUE
 OR N.MARKET_VALUE<>T.MARKET_VALUE
 OR N.EVAL_VALUE_CURRENCY_CD<>T.EVAL_VALUE_CURRENCY_CD
 OR N.EVAL_VALUE<>T.EVAL_VALUE
 OR N.CCB_ASSESSED_VALUE_CURRENCY_CD<>T.CCB_ASSESSED_VALUE_CURRENCY_CD
 OR N.CCB_ASSESSED_VALUE<>T.CCB_ASSESSED_VALUE
 OR N.ACQUIRE_WAY_OF_COLLATERAL_CD<>T.ACQUIRE_WAY_OF_COLLATERAL_CD
 OR N.COMMON_ASSETS_IND<>T.COMMON_ASSETS_IND
 OR N.COMMON_OWNER_NAME<>T.COMMON_OWNER_NAME
 OR N.WAY_GUARANTY_EFFECTIVE_CD<>T.WAY_GUARANTY_EFFECTIVE_CD
 OR N.COLLATERAL_SETUP_IND<>T.COLLATERAL_SETUP_IND
 OR N.SET_GUARANTY_AMT_IN_CCB<>T.SET_GUARANTY_AMT_IN_CCB
 OR N.RENTED_LICENSED_IND<>T.RENTED_LICENSED_IND
 OR N.RENTER_NAME<>T.RENTER_NAME
 OR N.SET_GUARANTY_AMT_OUT_CCB<>T.SET_GUARANTY_AMT_OUT_CCB
 OR N.LEASE_EXPIRATION_DATE<>T.LEASE_EXPIRATION_DATE
 OR N.CUSTOMER_NUM<>T.CUSTOMER_NUM
 OR N.SUBMITTING_DATE<>T.SUBMITTING_DATE
 OR N.CURRENCY_CD<>T.CURRENCY_CD
 OR N.COLLATERAL_DISPOSE<>T.COLLATERAL_DISPOSE
 OR N.OTHER_NOTE<>T.OTHER_NOTE
 OR N.SET_GUARANTY_AMT<>T.SET_GUARANTY_AMT
 OR N.PROVINCE_CD<>T.PROVINCE_CD
 OR N.CITY_CD<>T.CITY_CD
 OR N.DISTRICT_CD<>T.DISTRICT_CD
 OR N.STREET_ADDRESS<>T.STREET_ADDRESS
 OR N.NATIONALITY_CD<>T.NATIONALITY_CD
 OR N.MERCHANDISE_TYPE<>T.MERCHANDISE_TYPE
 OR N.RIGHT_CERT_TYPE_CD<>T.RIGHT_CERT_TYPE_CD
 OR N.RIGHT_CERTIFICATION_NUM<>T.RIGHT_CERTIFICATION_NUM
 OR N.SYS_UPDATE_TIME<>T.SYS_UPDATE_TIME
 OR N.COLLATERAL_CATALOG_CD<>T.COLLATERAL_CATALOG_CD
 OR N.DATA_CREAT_USER_NUM<>T.DATA_CREAT_USER_NUM
 OR N.DATA_CREATOR_ORG_CD<>T.DATA_CREATOR_ORG_CD
 OR N.LAST_UPDATE_USER_NUM<>T.LAST_UPDATE_USER_NUM
 OR N.LAST_UPDATE_ORG_CD<>T.LAST_UPDATE_ORG_CD
 OR N.TAKEOVER_IND<>T.TAKEOVER_IND
 OR N.ALL_PLEDGE_IND<>T.ALL_PLEDGE_IND
 OR N.FORBID_CIRCULATE_IND<>T.FORBID_CIRCULATE_IND
 OR N.NATIONALISATION_IND<>T.NATIONALISATION_IND
 OR N.PROPERTY_DISPUTED_IND<>T.PROPERTY_DISPUTED_IND
 OR N.INVALID_IND<>T.INVALID_IND
 OR N.BLEMISH_IND<>T.BLEMISH_IND
 OR N.BLEMISH_NOTE<>T.BLEMISH_NOTE
 OR N.HANDOVER_DATE<>T.HANDOVER_DATE
 OR N.K75ZCMS<>T.K75ZCMS
 OR N.KEEP_SPECIAL_REQ<>T.KEEP_SPECIAL_REQ
 OR N.VALUATOR<>T.VALUATOR
 OR N.EVALUATE_DATE<>T.EVALUATE_DATE
 OR N.ASSET_STATUS<>T.ASSET_STATUS
 OR N.CUSTOMER_TYPE<>T.CUSTOMER_TYPE
 OR N.SETTLED_ASSETS_IND<>T.SETTLED_ASSETS_IND
 OR N.TIME_MARK<>T.TIME_MARK
 OR N.IMPAWN_AMOUNT<>T.IMPAWN_AMOUNT
 OR N.IMPAWN_AMOUNT_CD<>T.IMPAWN_AMOUNT_CD
 OR N.IMPAWN_EXPIRE_DATE<>T.IMPAWN_EXPIRE_DATE
 OR N.IMPAWN_GET_DATE<>T.IMPAWN_GET_DATE
 OR N.REGISTER_IND<>T.REGISTER_IND
 OR N.COLLATERAL_CARD_DEPARTMENT<>T.COLLATERAL_CARD_DEPARTMENT
 OR N.CUSTOMER_NAME<>T.CUSTOMER_NAME
 OR N.RATE_OF_DISCOUNT<>T.RATE_OF_DISCOUNT
 OR N.PLEDGE_TYPE_CD<>T.PLEDGE_TYPE_CD
 OR N.OUT_REASON<>T.OUT_REASON
 OR N.IF_OUT<>T.IF_OUT
 OR N.OWNER_RATE<>T.OWNER_RATE
 OR N.PAYOUT_SEND_NUM<>T.PAYOUT_SEND_NUM
 OR N.VALUECHANGE_SEND_NUM<>T.VALUECHANGE_SEND_NUM
 OR N.RSP_CODE<>T.RSP_CODE
 OR N.RSP_TIME<>T.RSP_TIME
 OR N.FXBS_TIME_MARK<>T.FXBS_TIME_MARK
 OR N.COLL_MODEL<>T.COLL_MODEL
;

--Step3:
UPDATE dw_sdata.CCS_004_TB_GRT_COLLATERAL P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_121
WHERE P.End_Dt=DATE('2100-12-31')
AND P.GUARANTY_ID=T_121.GUARANTY_ID
;

--Step4:
INSERT  INTO dw_sdata.CCS_004_TB_GRT_COLLATERAL SELECT * FROM T_121;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
