#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.COS_000_CPARTY WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.COS_000_CPARTY SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_151 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.COS_000_CPARTY WHERE 1=0;

--Step2:
INSERT  INTO T_151 (
  THEKEY,
  NAME,
  CODE,
  EXT_NAME,
  PHONE,
  TELEX,
  FAX,
  POST_ADD,
  STREET_ADD,
  COUNTRY,
  LOCATION,
  OWNER,
  THELEVEL,
  CPTYPE,
  BANK_INT,
  BANK_EXT,
  DEAL_INT,
  DEAL_EXT,
  DEBT_CRED,
  ISSUER,
  TAXOR,
  SWIFT_FI,
  BANK_SETTL,
  BIC_CODE,
  EX_LIMIT,
  EX_LIM_CCY,
  NETTFLOWS,
  FU_CLR_BRO,
  FU_EXE_BRO,
  IS_STOCK_AGENT,
  IS_ISS_PAY_AGENT,
  SWIFT_DATA_SOURCE_SCHEME,
  ANALYSE01,
  ANALYSE02,
  ANALYSE03,
  ANALYSE04,
  ANALYSE05,
  ANALYSE06,
  ANALYSE07,
  ANALYSE08,
  ANALYSE09,
  ANALYSE10,
  ANALYSE11,
  ANALYSE12,
  ANALYSE13,
  ANALYSE14,
  ANALYSE15,
  ANALYSE16,
  ANALYSE17,
  ANALYSE18,
  ANALYSE19,
  ANALYSE20,
  USAGE,
  IN_USE,
  BTREE_LOW,
  BTREE_HIGH,
  STAMP,
  EXCHANGE,
  INDUSTRY,
  IS_FUND_MANAGER,
  start_dt,
  end_dt)
SELECT
  N.THEKEY,
  N.NAME,
  N.CODE,
  N.EXT_NAME,
  N.PHONE,
  N.TELEX,
  N.FAX,
  N.POST_ADD,
  N.STREET_ADD,
  N.COUNTRY,
  N.LOCATION,
  N.OWNER,
  N.THELEVEL,
  N.CPTYPE,
  N.BANK_INT,
  N.BANK_EXT,
  N.DEAL_INT,
  N.DEAL_EXT,
  N.DEBT_CRED,
  N.ISSUER,
  N.TAXOR,
  N.SWIFT_FI,
  N.BANK_SETTL,
  N.BIC_CODE,
  N.EX_LIMIT,
  N.EX_LIM_CCY,
  N.NETTFLOWS,
  N.FU_CLR_BRO,
  N.FU_EXE_BRO,
  N.IS_STOCK_AGENT,
  N.IS_ISS_PAY_AGENT,
  N.SWIFT_DATA_SOURCE_SCHEME,
  N.ANALYSE01,
  N.ANALYSE02,
  N.ANALYSE03,
  N.ANALYSE04,
  N.ANALYSE05,
  N.ANALYSE06,
  N.ANALYSE07,
  N.ANALYSE08,
  N.ANALYSE09,
  N.ANALYSE10,
  N.ANALYSE11,
  N.ANALYSE12,
  N.ANALYSE13,
  N.ANALYSE14,
  N.ANALYSE15,
  N.ANALYSE16,
  N.ANALYSE17,
  N.ANALYSE18,
  N.ANALYSE19,
  N.ANALYSE20,
  N.USAGE,
  N.IN_USE,
  N.BTREE_LOW,
  N.BTREE_HIGH,
  N.STAMP,
  N.EXCHANGE,
  N.INDUSTRY,
  N.IS_FUND_MANAGER,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(THEKEY, '' ) AS THEKEY ,
  COALESCE(NAME, '' ) AS NAME ,
  COALESCE(CODE, '' ) AS CODE ,
  COALESCE(EXT_NAME, '' ) AS EXT_NAME ,
  COALESCE(PHONE, '' ) AS PHONE ,
  COALESCE(TELEX, '' ) AS TELEX ,
  COALESCE(FAX, '' ) AS FAX ,
  COALESCE(POST_ADD, '' ) AS POST_ADD ,
  COALESCE(STREET_ADD, '' ) AS STREET_ADD ,
  COALESCE(COUNTRY, '' ) AS COUNTRY ,
  COALESCE(LOCATION, '' ) AS LOCATION ,
  COALESCE(OWNER, '' ) AS OWNER ,
  COALESCE(THELEVEL, '' ) AS THELEVEL ,
  COALESCE(CPTYPE, '' ) AS CPTYPE ,
  COALESCE(BANK_INT, '' ) AS BANK_INT ,
  COALESCE(BANK_EXT, '' ) AS BANK_EXT ,
  COALESCE(DEAL_INT, '' ) AS DEAL_INT ,
  COALESCE(DEAL_EXT, '' ) AS DEAL_EXT ,
  COALESCE(DEBT_CRED, '' ) AS DEBT_CRED ,
  COALESCE(ISSUER, '' ) AS ISSUER ,
  COALESCE(TAXOR, '' ) AS TAXOR ,
  COALESCE(SWIFT_FI, '' ) AS SWIFT_FI ,
  COALESCE(BANK_SETTL, '' ) AS BANK_SETTL ,
  COALESCE(BIC_CODE, '' ) AS BIC_CODE ,
  COALESCE(EX_LIMIT, 0 ) AS EX_LIMIT ,
  COALESCE(EX_LIM_CCY, '' ) AS EX_LIM_CCY ,
  COALESCE(NETTFLOWS, '' ) AS NETTFLOWS ,
  COALESCE(FU_CLR_BRO, '' ) AS FU_CLR_BRO ,
  COALESCE(FU_EXE_BRO, '' ) AS FU_EXE_BRO ,
  COALESCE(IS_STOCK_AGENT, 0 ) AS IS_STOCK_AGENT ,
  COALESCE(IS_ISS_PAY_AGENT, 0 ) AS IS_ISS_PAY_AGENT ,
  COALESCE(SWIFT_DATA_SOURCE_SCHEME, '' ) AS SWIFT_DATA_SOURCE_SCHEME ,
  COALESCE(ANALYSE01, '' ) AS ANALYSE01 ,
  COALESCE(ANALYSE02, '' ) AS ANALYSE02 ,
  COALESCE(ANALYSE03, '' ) AS ANALYSE03 ,
  COALESCE(ANALYSE04, '' ) AS ANALYSE04 ,
  COALESCE(ANALYSE05, '' ) AS ANALYSE05 ,
  COALESCE(ANALYSE06, '' ) AS ANALYSE06 ,
  COALESCE(ANALYSE07, '' ) AS ANALYSE07 ,
  COALESCE(ANALYSE08, '' ) AS ANALYSE08 ,
  COALESCE(ANALYSE09, '' ) AS ANALYSE09 ,
  COALESCE(ANALYSE10, '' ) AS ANALYSE10 ,
  COALESCE(ANALYSE11, '' ) AS ANALYSE11 ,
  COALESCE(ANALYSE12, '' ) AS ANALYSE12 ,
  COALESCE(ANALYSE13, '' ) AS ANALYSE13 ,
  COALESCE(ANALYSE14, '' ) AS ANALYSE14 ,
  COALESCE(ANALYSE15, '' ) AS ANALYSE15 ,
  COALESCE(ANALYSE16, '' ) AS ANALYSE16 ,
  COALESCE(ANALYSE17, '' ) AS ANALYSE17 ,
  COALESCE(ANALYSE18, '' ) AS ANALYSE18 ,
  COALESCE(ANALYSE19, '' ) AS ANALYSE19 ,
  COALESCE(ANALYSE20, '' ) AS ANALYSE20 ,
  COALESCE(USAGE, 0 ) AS USAGE ,
  COALESCE(IN_USE, '' ) AS IN_USE ,
  COALESCE(BTREE_LOW, 0 ) AS BTREE_LOW ,
  COALESCE(BTREE_HIGH, 0 ) AS BTREE_HIGH ,
  COALESCE(STAMP, 0 ) AS STAMP ,
  COALESCE(EXCHANGE, '' ) AS EXCHANGE ,
  COALESCE(INDUSTRY, '' ) AS INDUSTRY ,
  COALESCE(IS_FUND_MANAGER, 0 ) AS IS_FUND_MANAGER 
 FROM  dw_tdata.COS_000_CPARTY_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  THEKEY ,
  NAME ,
  CODE ,
  EXT_NAME ,
  PHONE ,
  TELEX ,
  FAX ,
  POST_ADD ,
  STREET_ADD ,
  COUNTRY ,
  LOCATION ,
  OWNER ,
  THELEVEL ,
  CPTYPE ,
  BANK_INT ,
  BANK_EXT ,
  DEAL_INT ,
  DEAL_EXT ,
  DEBT_CRED ,
  ISSUER ,
  TAXOR ,
  SWIFT_FI ,
  BANK_SETTL ,
  BIC_CODE ,
  EX_LIMIT ,
  EX_LIM_CCY ,
  NETTFLOWS ,
  FU_CLR_BRO ,
  FU_EXE_BRO ,
  IS_STOCK_AGENT ,
  IS_ISS_PAY_AGENT ,
  SWIFT_DATA_SOURCE_SCHEME ,
  ANALYSE01 ,
  ANALYSE02 ,
  ANALYSE03 ,
  ANALYSE04 ,
  ANALYSE05 ,
  ANALYSE06 ,
  ANALYSE07 ,
  ANALYSE08 ,
  ANALYSE09 ,
  ANALYSE10 ,
  ANALYSE11 ,
  ANALYSE12 ,
  ANALYSE13 ,
  ANALYSE14 ,
  ANALYSE15 ,
  ANALYSE16 ,
  ANALYSE17 ,
  ANALYSE18 ,
  ANALYSE19 ,
  ANALYSE20 ,
  USAGE ,
  IN_USE ,
  BTREE_LOW ,
  BTREE_HIGH ,
  STAMP ,
  EXCHANGE ,
  INDUSTRY ,
  IS_FUND_MANAGER 
 FROM dw_sdata.COS_000_CPARTY 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.THEKEY = T.THEKEY
WHERE
(T.THEKEY IS NULL)
 OR N.NAME<>T.NAME
 OR N.CODE<>T.CODE
 OR N.EXT_NAME<>T.EXT_NAME
 OR N.PHONE<>T.PHONE
 OR N.TELEX<>T.TELEX
 OR N.FAX<>T.FAX
 OR N.POST_ADD<>T.POST_ADD
 OR N.STREET_ADD<>T.STREET_ADD
 OR N.COUNTRY<>T.COUNTRY
 OR N.LOCATION<>T.LOCATION
 OR N.OWNER<>T.OWNER
 OR N.THELEVEL<>T.THELEVEL
 OR N.CPTYPE<>T.CPTYPE
 OR N.BANK_INT<>T.BANK_INT
 OR N.BANK_EXT<>T.BANK_EXT
 OR N.DEAL_INT<>T.DEAL_INT
 OR N.DEAL_EXT<>T.DEAL_EXT
 OR N.DEBT_CRED<>T.DEBT_CRED
 OR N.ISSUER<>T.ISSUER
 OR N.TAXOR<>T.TAXOR
 OR N.SWIFT_FI<>T.SWIFT_FI
 OR N.BANK_SETTL<>T.BANK_SETTL
 OR N.BIC_CODE<>T.BIC_CODE
 OR N.EX_LIMIT<>T.EX_LIMIT
 OR N.EX_LIM_CCY<>T.EX_LIM_CCY
 OR N.NETTFLOWS<>T.NETTFLOWS
 OR N.FU_CLR_BRO<>T.FU_CLR_BRO
 OR N.FU_EXE_BRO<>T.FU_EXE_BRO
 OR N.IS_STOCK_AGENT<>T.IS_STOCK_AGENT
 OR N.IS_ISS_PAY_AGENT<>T.IS_ISS_PAY_AGENT
 OR N.SWIFT_DATA_SOURCE_SCHEME<>T.SWIFT_DATA_SOURCE_SCHEME
 OR N.ANALYSE01<>T.ANALYSE01
 OR N.ANALYSE02<>T.ANALYSE02
 OR N.ANALYSE03<>T.ANALYSE03
 OR N.ANALYSE04<>T.ANALYSE04
 OR N.ANALYSE05<>T.ANALYSE05
 OR N.ANALYSE06<>T.ANALYSE06
 OR N.ANALYSE07<>T.ANALYSE07
 OR N.ANALYSE08<>T.ANALYSE08
 OR N.ANALYSE09<>T.ANALYSE09
 OR N.ANALYSE10<>T.ANALYSE10
 OR N.ANALYSE11<>T.ANALYSE11
 OR N.ANALYSE12<>T.ANALYSE12
 OR N.ANALYSE13<>T.ANALYSE13
 OR N.ANALYSE14<>T.ANALYSE14
 OR N.ANALYSE15<>T.ANALYSE15
 OR N.ANALYSE16<>T.ANALYSE16
 OR N.ANALYSE17<>T.ANALYSE17
 OR N.ANALYSE18<>T.ANALYSE18
 OR N.ANALYSE19<>T.ANALYSE19
 OR N.ANALYSE20<>T.ANALYSE20
 OR N.USAGE<>T.USAGE
 OR N.IN_USE<>T.IN_USE
 OR N.BTREE_LOW<>T.BTREE_LOW
 OR N.BTREE_HIGH<>T.BTREE_HIGH
 OR N.STAMP<>T.STAMP
 OR N.EXCHANGE<>T.EXCHANGE
 OR N.INDUSTRY<>T.INDUSTRY
 OR N.IS_FUND_MANAGER<>T.IS_FUND_MANAGER
;

--Step3:
UPDATE dw_sdata.COS_000_CPARTY P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_151
WHERE P.End_Dt=DATE('2100-12-31')
AND P.THEKEY=T_151.THEKEY
;

--Step4:
INSERT  INTO dw_sdata.COS_000_CPARTY SELECT * FROM T_151;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
