#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.COS_000_SWDEALS WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.COS_000_SWDEALS SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_160 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.COS_000_SWDEALS WHERE 1=0;

--Step2:
INSERT  INTO T_160 (
  DEAL_NO,
  START_DATE,
  CROSS_CCY,
  ACCOUNTING,
  CONTINGENT,
  OPTION_DEAL_NO,
  PRINC_EXCH,
  EXCH_RATE,
  ASSET_LIAB,
  REVAL_CCY,
  ASYMM_CUR_HOL,
  P_FORMULA,
  P_TIMING,
  P_FT_KEY,
  P_FIXFLOAT,
  P_RATE,
  P_MARGIN,
  P_INT_CALC_LOC,
  P_INT_DAYS,
  P_YIELD,
  P_BASIS,
  P_BASIS_FQ,
  P_REVAL,
  P_REVIEW_F,
  P_REVIEW_1,
  P_RATE_OFF,
  P_FREQ,
  P_1ST_DT,
  P_PREV_DT,
  P_DT_CYCLE,
  P_COUP_TYP,
  P_NOM_EFF,
  P_COMP_FRQ,
  P_CDI_DISC,
  P_CD_SELCT,
  P_RD_SELCT,
  P_ED_SELCT,
  P_PRICE_M,
  P_FPP_METD,
  P_FPP_DATE,
  P_EX_DAYS,
  P_PPH_RND,
  P_PPH_CAP,
  P_PPH_INC,
  P_PPH_CAPITAL_METHOD,
  P_PPH_CAPITAL_DP,
  P_PPH_INCOME_METHOD,
  P_PPH_INCOME_DP,
  P_PPH_SETTLE_METHOD,
  P_PPH_SETTLE_DP,
  P_PPH_DRV,
  P_PPH_AFT,
  P_FUFTDAYS,
  P_MOD_MASK,
  P_MND_MASK,
  P_SHW_MASK,
  P_BOND_PRI,
  P_RNDMETH,
  P_RNDPLACE,
  P_SEPARATE_RATESET,
  P_DUAL_CCY,
  P_CPN_CCY,
  P_CPN_FV,
  P_EXCH_RTE,
  P_FRAC_UNIT,
  P_DATED_DATE,
  P_FNL_PRD_METHOD,
  P_FPP_EARLY_DISCOUNT,
  P_FPP_ADJ_MATURITY,
  P_FPP_NO_PPH_ROUNDING,
  P_FPP_DAYS_BASIS,
  P_FIRST_COUPON_DATE,
  P_INCOME_ACCRUAL_BASIS,
  P_ODD_FIRST_COUPON,
  P_ODD_LAST_COUPON,
  P_PENULTIMATE_COUPON_DATE,
  P_DISCOUNT_DAYS_BASIS,
  P_NO_COUPON_ON_MATURITY,
  P_YIELD_CONVENTION_ID,
  P_COUPON_DAYS_BASIS,
  P_USE_DP_BASIS_PRICING,
  P_PAY_RECEIVE_TYPE,
  R_FORMULA,
  R_TIMING,
  R_FT_KEY,
  R_FIXFLOAT,
  R_RATE,
  R_MARGIN,
  R_INT_CALC_LOC,
  R_INT_DAYS,
  R_YIELD,
  R_BASIS,
  R_BASIS_FQ,
  R_REVAL,
  R_REVIEW_F,
  R_REVIEW_1,
  R_RATE_OFF,
  R_FREQ,
  R_1ST_DT,
  R_PREV_DT,
  R_DT_CYCLE,
  R_COUP_TYP,
  R_NOM_EFF,
  R_COMP_FRQ,
  R_CDI_DISC,
  R_CD_SELCT,
  R_RD_SELCT,
  R_ED_SELCT,
  R_PRICE_M,
  R_FPP_METD,
  R_FPP_DATE,
  R_EX_DAYS,
  R_PPH_RND,
  R_PPH_CAP,
  R_PPH_INC,
  R_PPH_CAPITAL_METHOD,
  R_PPH_CAPITAL_DP,
  R_PPH_INCOME_METHOD,
  R_PPH_INCOME_DP,
  R_PPH_SETTLE_METHOD,
  R_PPH_SETTLE_DP,
  R_PPH_DRV,
  R_PPH_AFT,
  R_FUFTDAYS,
  R_MOD_MASK,
  R_MND_MASK,
  R_SHW_MASK,
  R_BOND_PRI,
  R_RNDMETH,
  R_RNDPLACE,
  R_SEPARATE_RATESET,
  R_DUAL_CCY,
  R_CPN_CCY,
  R_CPN_FV,
  R_EXCH_RTE,
  R_FRAC_UNIT,
  R_DATED_DATE,
  R_FNL_PRD_METHOD,
  R_FPP_EARLY_DISCOUNT,
  R_FPP_ADJ_MATURITY,
  R_FPP_NO_PPH_ROUNDING,
  R_FPP_DAYS_BASIS,
  R_FIRST_COUPON_DATE,
  R_INCOME_ACCRUAL_BASIS,
  R_ODD_FIRST_COUPON,
  R_ODD_LAST_COUPON,
  R_PENULTIMATE_COUPON_DATE,
  R_DISCOUNT_DAYS_BASIS,
  R_NO_COUPON_ON_MATURITY,
  R_YIELD_CONVENTION_ID,
  R_COUPON_DAYS_BASIS,
  R_USE_DP_BASIS_PRICING,
  R_PAY_RECEIVE_TYPE,
  REMAIN_FV,
  REMAIN_FV2,
  ANALYSE01,
  ANALYSE02,
  ANALYSE03,
  ANALYSE04,
  ANALYSE05,
  ANALYSE06,
  ANALYSE07,
  ANALYSE08,
  ANALYSE09,
  ANALYSE10,
  STAMP,
  ACRL_SL_DAYS_RULE,
  start_dt,
  end_dt)
SELECT
  N.DEAL_NO,
  N.START_DATE,
  N.CROSS_CCY,
  N.ACCOUNTING,
  N.CONTINGENT,
  N.OPTION_DEAL_NO,
  N.PRINC_EXCH,
  N.EXCH_RATE,
  N.ASSET_LIAB,
  N.REVAL_CCY,
  N.ASYMM_CUR_HOL,
  N.P_FORMULA,
  N.P_TIMING,
  N.P_FT_KEY,
  N.P_FIXFLOAT,
  N.P_RATE,
  N.P_MARGIN,
  N.P_INT_CALC_LOC,
  N.P_INT_DAYS,
  N.P_YIELD,
  N.P_BASIS,
  N.P_BASIS_FQ,
  N.P_REVAL,
  N.P_REVIEW_F,
  N.P_REVIEW_1,
  N.P_RATE_OFF,
  N.P_FREQ,
  N.P_1ST_DT,
  N.P_PREV_DT,
  N.P_DT_CYCLE,
  N.P_COUP_TYP,
  N.P_NOM_EFF,
  N.P_COMP_FRQ,
  N.P_CDI_DISC,
  N.P_CD_SELCT,
  N.P_RD_SELCT,
  N.P_ED_SELCT,
  N.P_PRICE_M,
  N.P_FPP_METD,
  N.P_FPP_DATE,
  N.P_EX_DAYS,
  N.P_PPH_RND,
  N.P_PPH_CAP,
  N.P_PPH_INC,
  N.P_PPH_CAPITAL_METHOD,
  N.P_PPH_CAPITAL_DP,
  N.P_PPH_INCOME_METHOD,
  N.P_PPH_INCOME_DP,
  N.P_PPH_SETTLE_METHOD,
  N.P_PPH_SETTLE_DP,
  N.P_PPH_DRV,
  N.P_PPH_AFT,
  N.P_FUFTDAYS,
  N.P_MOD_MASK,
  N.P_MND_MASK,
  N.P_SHW_MASK,
  N.P_BOND_PRI,
  N.P_RNDMETH,
  N.P_RNDPLACE,
  N.P_SEPARATE_RATESET,
  N.P_DUAL_CCY,
  N.P_CPN_CCY,
  N.P_CPN_FV,
  N.P_EXCH_RTE,
  N.P_FRAC_UNIT,
  N.P_DATED_DATE,
  N.P_FNL_PRD_METHOD,
  N.P_FPP_EARLY_DISCOUNT,
  N.P_FPP_ADJ_MATURITY,
  N.P_FPP_NO_PPH_ROUNDING,
  N.P_FPP_DAYS_BASIS,
  N.P_FIRST_COUPON_DATE,
  N.P_INCOME_ACCRUAL_BASIS,
  N.P_ODD_FIRST_COUPON,
  N.P_ODD_LAST_COUPON,
  N.P_PENULTIMATE_COUPON_DATE,
  N.P_DISCOUNT_DAYS_BASIS,
  N.P_NO_COUPON_ON_MATURITY,
  N.P_YIELD_CONVENTION_ID,
  N.P_COUPON_DAYS_BASIS,
  N.P_USE_DP_BASIS_PRICING,
  N.P_PAY_RECEIVE_TYPE,
  N.R_FORMULA,
  N.R_TIMING,
  N.R_FT_KEY,
  N.R_FIXFLOAT,
  N.R_RATE,
  N.R_MARGIN,
  N.R_INT_CALC_LOC,
  N.R_INT_DAYS,
  N.R_YIELD,
  N.R_BASIS,
  N.R_BASIS_FQ,
  N.R_REVAL,
  N.R_REVIEW_F,
  N.R_REVIEW_1,
  N.R_RATE_OFF,
  N.R_FREQ,
  N.R_1ST_DT,
  N.R_PREV_DT,
  N.R_DT_CYCLE,
  N.R_COUP_TYP,
  N.R_NOM_EFF,
  N.R_COMP_FRQ,
  N.R_CDI_DISC,
  N.R_CD_SELCT,
  N.R_RD_SELCT,
  N.R_ED_SELCT,
  N.R_PRICE_M,
  N.R_FPP_METD,
  N.R_FPP_DATE,
  N.R_EX_DAYS,
  N.R_PPH_RND,
  N.R_PPH_CAP,
  N.R_PPH_INC,
  N.R_PPH_CAPITAL_METHOD,
  N.R_PPH_CAPITAL_DP,
  N.R_PPH_INCOME_METHOD,
  N.R_PPH_INCOME_DP,
  N.R_PPH_SETTLE_METHOD,
  N.R_PPH_SETTLE_DP,
  N.R_PPH_DRV,
  N.R_PPH_AFT,
  N.R_FUFTDAYS,
  N.R_MOD_MASK,
  N.R_MND_MASK,
  N.R_SHW_MASK,
  N.R_BOND_PRI,
  N.R_RNDMETH,
  N.R_RNDPLACE,
  N.R_SEPARATE_RATESET,
  N.R_DUAL_CCY,
  N.R_CPN_CCY,
  N.R_CPN_FV,
  N.R_EXCH_RTE,
  N.R_FRAC_UNIT,
  N.R_DATED_DATE,
  N.R_FNL_PRD_METHOD,
  N.R_FPP_EARLY_DISCOUNT,
  N.R_FPP_ADJ_MATURITY,
  N.R_FPP_NO_PPH_ROUNDING,
  N.R_FPP_DAYS_BASIS,
  N.R_FIRST_COUPON_DATE,
  N.R_INCOME_ACCRUAL_BASIS,
  N.R_ODD_FIRST_COUPON,
  N.R_ODD_LAST_COUPON,
  N.R_PENULTIMATE_COUPON_DATE,
  N.R_DISCOUNT_DAYS_BASIS,
  N.R_NO_COUPON_ON_MATURITY,
  N.R_YIELD_CONVENTION_ID,
  N.R_COUPON_DAYS_BASIS,
  N.R_USE_DP_BASIS_PRICING,
  N.R_PAY_RECEIVE_TYPE,
  N.REMAIN_FV,
  N.REMAIN_FV2,
  N.ANALYSE01,
  N.ANALYSE02,
  N.ANALYSE03,
  N.ANALYSE04,
  N.ANALYSE05,
  N.ANALYSE06,
  N.ANALYSE07,
  N.ANALYSE08,
  N.ANALYSE09,
  N.ANALYSE10,
  N.STAMP,
  N.ACRL_SL_DAYS_RULE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(DEAL_NO, 0 ) AS DEAL_NO ,
  COALESCE(START_DATE, '' ) AS START_DATE ,
  COALESCE(CROSS_CCY, '' ) AS CROSS_CCY ,
  COALESCE(ACCOUNTING, '' ) AS ACCOUNTING ,
  COALESCE(CONTINGENT, '' ) AS CONTINGENT ,
  COALESCE(OPTION_DEAL_NO, 0 ) AS OPTION_DEAL_NO ,
  COALESCE(PRINC_EXCH, '' ) AS PRINC_EXCH ,
  COALESCE(EXCH_RATE, 0 ) AS EXCH_RATE ,
  COALESCE(ASSET_LIAB, '' ) AS ASSET_LIAB ,
  COALESCE(REVAL_CCY, '' ) AS REVAL_CCY ,
  COALESCE(ASYMM_CUR_HOL, '' ) AS ASYMM_CUR_HOL ,
  COALESCE(P_FORMULA, '' ) AS P_FORMULA ,
  COALESCE(P_TIMING, '' ) AS P_TIMING ,
  COALESCE(P_FT_KEY, 0 ) AS P_FT_KEY ,
  COALESCE(P_FIXFLOAT, '' ) AS P_FIXFLOAT ,
  COALESCE(P_RATE, 0 ) AS P_RATE ,
  COALESCE(P_MARGIN, 0 ) AS P_MARGIN ,
  COALESCE(P_INT_CALC_LOC, 0 ) AS P_INT_CALC_LOC ,
  COALESCE(P_INT_DAYS, '' ) AS P_INT_DAYS ,
  COALESCE(P_YIELD, 0 ) AS P_YIELD ,
  COALESCE(P_BASIS, '' ) AS P_BASIS ,
  COALESCE(P_BASIS_FQ, '' ) AS P_BASIS_FQ ,
  COALESCE(P_REVAL, '' ) AS P_REVAL ,
  COALESCE(P_REVIEW_F, '' ) AS P_REVIEW_F ,
  COALESCE(P_REVIEW_1, '' ) AS P_REVIEW_1 ,
  COALESCE(P_RATE_OFF, 0 ) AS P_RATE_OFF ,
  COALESCE(P_FREQ, '' ) AS P_FREQ ,
  COALESCE(P_1ST_DT, '' ) AS P_1ST_DT ,
  COALESCE(P_PREV_DT, '' ) AS P_PREV_DT ,
  COALESCE(P_DT_CYCLE, '' ) AS P_DT_CYCLE ,
  COALESCE(P_COUP_TYP, '' ) AS P_COUP_TYP ,
  COALESCE(P_NOM_EFF, '' ) AS P_NOM_EFF ,
  COALESCE(P_COMP_FRQ, '' ) AS P_COMP_FRQ ,
  COALESCE(P_CDI_DISC, 0 ) AS P_CDI_DISC ,
  COALESCE(P_CD_SELCT, '' ) AS P_CD_SELCT ,
  COALESCE(P_RD_SELCT, '' ) AS P_RD_SELCT ,
  COALESCE(P_ED_SELCT, '' ) AS P_ED_SELCT ,
  COALESCE(P_PRICE_M, '' ) AS P_PRICE_M ,
  COALESCE(P_FPP_METD, '' ) AS P_FPP_METD ,
  COALESCE(P_FPP_DATE, '' ) AS P_FPP_DATE ,
  COALESCE(P_EX_DAYS, '' ) AS P_EX_DAYS ,
  COALESCE(P_PPH_RND, '' ) AS P_PPH_RND ,
  COALESCE(P_PPH_CAP, '' ) AS P_PPH_CAP ,
  COALESCE(P_PPH_INC, '' ) AS P_PPH_INC ,
  COALESCE(P_PPH_CAPITAL_METHOD, 0 ) AS P_PPH_CAPITAL_METHOD ,
  COALESCE(P_PPH_CAPITAL_DP, 0 ) AS P_PPH_CAPITAL_DP ,
  COALESCE(P_PPH_INCOME_METHOD, 0 ) AS P_PPH_INCOME_METHOD ,
  COALESCE(P_PPH_INCOME_DP, 0 ) AS P_PPH_INCOME_DP ,
  COALESCE(P_PPH_SETTLE_METHOD, 0 ) AS P_PPH_SETTLE_METHOD ,
  COALESCE(P_PPH_SETTLE_DP, 0 ) AS P_PPH_SETTLE_DP ,
  COALESCE(P_PPH_DRV, '' ) AS P_PPH_DRV ,
  COALESCE(P_PPH_AFT, '' ) AS P_PPH_AFT ,
  COALESCE(P_FUFTDAYS, '' ) AS P_FUFTDAYS ,
  COALESCE(P_MOD_MASK, '' ) AS P_MOD_MASK ,
  COALESCE(P_MND_MASK, '' ) AS P_MND_MASK ,
  COALESCE(P_SHW_MASK, '' ) AS P_SHW_MASK ,
  COALESCE(P_BOND_PRI, 0 ) AS P_BOND_PRI ,
  COALESCE(P_RNDMETH, '' ) AS P_RNDMETH ,
  COALESCE(P_RNDPLACE, 0 ) AS P_RNDPLACE ,
  COALESCE(P_SEPARATE_RATESET, '' ) AS P_SEPARATE_RATESET ,
  COALESCE(P_DUAL_CCY, '' ) AS P_DUAL_CCY ,
  COALESCE(P_CPN_CCY, '' ) AS P_CPN_CCY ,
  COALESCE(P_CPN_FV, 0 ) AS P_CPN_FV ,
  COALESCE(P_EXCH_RTE, 0 ) AS P_EXCH_RTE ,
  COALESCE(P_FRAC_UNIT, 0 ) AS P_FRAC_UNIT ,
  COALESCE(P_DATED_DATE, '' ) AS P_DATED_DATE ,
  COALESCE(P_FNL_PRD_METHOD, 0 ) AS P_FNL_PRD_METHOD ,
  COALESCE(P_FPP_EARLY_DISCOUNT, 0 ) AS P_FPP_EARLY_DISCOUNT ,
  COALESCE(P_FPP_ADJ_MATURITY, 0 ) AS P_FPP_ADJ_MATURITY ,
  COALESCE(P_FPP_NO_PPH_ROUNDING, 0 ) AS P_FPP_NO_PPH_ROUNDING ,
  COALESCE(P_FPP_DAYS_BASIS, 0 ) AS P_FPP_DAYS_BASIS ,
  COALESCE(P_FIRST_COUPON_DATE, '' ) AS P_FIRST_COUPON_DATE ,
  COALESCE(P_INCOME_ACCRUAL_BASIS, 0 ) AS P_INCOME_ACCRUAL_BASIS ,
  COALESCE(P_ODD_FIRST_COUPON, 0 ) AS P_ODD_FIRST_COUPON ,
  COALESCE(P_ODD_LAST_COUPON, 0 ) AS P_ODD_LAST_COUPON ,
  COALESCE(P_PENULTIMATE_COUPON_DATE, '' ) AS P_PENULTIMATE_COUPON_DATE ,
  COALESCE(P_DISCOUNT_DAYS_BASIS, 0 ) AS P_DISCOUNT_DAYS_BASIS ,
  COALESCE(P_NO_COUPON_ON_MATURITY, 0 ) AS P_NO_COUPON_ON_MATURITY ,
  COALESCE(P_YIELD_CONVENTION_ID, 0 ) AS P_YIELD_CONVENTION_ID ,
  COALESCE(P_COUPON_DAYS_BASIS, 0 ) AS P_COUPON_DAYS_BASIS ,
  COALESCE(P_USE_DP_BASIS_PRICING, 0 ) AS P_USE_DP_BASIS_PRICING ,
  COALESCE(P_PAY_RECEIVE_TYPE, 0 ) AS P_PAY_RECEIVE_TYPE ,
  COALESCE(R_FORMULA, '' ) AS R_FORMULA ,
  COALESCE(R_TIMING, '' ) AS R_TIMING ,
  COALESCE(R_FT_KEY, 0 ) AS R_FT_KEY ,
  COALESCE(R_FIXFLOAT, '' ) AS R_FIXFLOAT ,
  COALESCE(R_RATE, 0 ) AS R_RATE ,
  COALESCE(R_MARGIN, 0 ) AS R_MARGIN ,
  COALESCE(R_INT_CALC_LOC, 0 ) AS R_INT_CALC_LOC ,
  COALESCE(R_INT_DAYS, '' ) AS R_INT_DAYS ,
  COALESCE(R_YIELD, 0 ) AS R_YIELD ,
  COALESCE(R_BASIS, '' ) AS R_BASIS ,
  COALESCE(R_BASIS_FQ, '' ) AS R_BASIS_FQ ,
  COALESCE(R_REVAL, '' ) AS R_REVAL ,
  COALESCE(R_REVIEW_F, '' ) AS R_REVIEW_F ,
  COALESCE(R_REVIEW_1, '' ) AS R_REVIEW_1 ,
  COALESCE(R_RATE_OFF, 0 ) AS R_RATE_OFF ,
  COALESCE(R_FREQ, '' ) AS R_FREQ ,
  COALESCE(R_1ST_DT, '' ) AS R_1ST_DT ,
  COALESCE(R_PREV_DT, '' ) AS R_PREV_DT ,
  COALESCE(R_DT_CYCLE, '' ) AS R_DT_CYCLE ,
  COALESCE(R_COUP_TYP, '' ) AS R_COUP_TYP ,
  COALESCE(R_NOM_EFF, '' ) AS R_NOM_EFF ,
  COALESCE(R_COMP_FRQ, '' ) AS R_COMP_FRQ ,
  COALESCE(R_CDI_DISC, 0 ) AS R_CDI_DISC ,
  COALESCE(R_CD_SELCT, '' ) AS R_CD_SELCT ,
  COALESCE(R_RD_SELCT, '' ) AS R_RD_SELCT ,
  COALESCE(R_ED_SELCT, '' ) AS R_ED_SELCT ,
  COALESCE(R_PRICE_M, '' ) AS R_PRICE_M ,
  COALESCE(R_FPP_METD, '' ) AS R_FPP_METD ,
  COALESCE(R_FPP_DATE, '' ) AS R_FPP_DATE ,
  COALESCE(R_EX_DAYS, '' ) AS R_EX_DAYS ,
  COALESCE(R_PPH_RND, '' ) AS R_PPH_RND ,
  COALESCE(R_PPH_CAP, '' ) AS R_PPH_CAP ,
  COALESCE(R_PPH_INC, '' ) AS R_PPH_INC ,
  COALESCE(R_PPH_CAPITAL_METHOD, 0 ) AS R_PPH_CAPITAL_METHOD ,
  COALESCE(R_PPH_CAPITAL_DP, 0 ) AS R_PPH_CAPITAL_DP ,
  COALESCE(R_PPH_INCOME_METHOD, 0 ) AS R_PPH_INCOME_METHOD ,
  COALESCE(R_PPH_INCOME_DP, 0 ) AS R_PPH_INCOME_DP ,
  COALESCE(R_PPH_SETTLE_METHOD, 0 ) AS R_PPH_SETTLE_METHOD ,
  COALESCE(R_PPH_SETTLE_DP, 0 ) AS R_PPH_SETTLE_DP ,
  COALESCE(R_PPH_DRV, '' ) AS R_PPH_DRV ,
  COALESCE(R_PPH_AFT, '' ) AS R_PPH_AFT ,
  COALESCE(R_FUFTDAYS, '' ) AS R_FUFTDAYS ,
  COALESCE(R_MOD_MASK, '' ) AS R_MOD_MASK ,
  COALESCE(R_MND_MASK, '' ) AS R_MND_MASK ,
  COALESCE(R_SHW_MASK, '' ) AS R_SHW_MASK ,
  COALESCE(R_BOND_PRI, 0 ) AS R_BOND_PRI ,
  COALESCE(R_RNDMETH, '' ) AS R_RNDMETH ,
  COALESCE(R_RNDPLACE, 0 ) AS R_RNDPLACE ,
  COALESCE(R_SEPARATE_RATESET, '' ) AS R_SEPARATE_RATESET ,
  COALESCE(R_DUAL_CCY, '' ) AS R_DUAL_CCY ,
  COALESCE(R_CPN_CCY, '' ) AS R_CPN_CCY ,
  COALESCE(R_CPN_FV, 0 ) AS R_CPN_FV ,
  COALESCE(R_EXCH_RTE, 0 ) AS R_EXCH_RTE ,
  COALESCE(R_FRAC_UNIT, 0 ) AS R_FRAC_UNIT ,
  COALESCE(R_DATED_DATE, '' ) AS R_DATED_DATE ,
  COALESCE(R_FNL_PRD_METHOD, 0 ) AS R_FNL_PRD_METHOD ,
  COALESCE(R_FPP_EARLY_DISCOUNT, 0 ) AS R_FPP_EARLY_DISCOUNT ,
  COALESCE(R_FPP_ADJ_MATURITY, 0 ) AS R_FPP_ADJ_MATURITY ,
  COALESCE(R_FPP_NO_PPH_ROUNDING, 0 ) AS R_FPP_NO_PPH_ROUNDING ,
  COALESCE(R_FPP_DAYS_BASIS, 0 ) AS R_FPP_DAYS_BASIS ,
  COALESCE(R_FIRST_COUPON_DATE, '' ) AS R_FIRST_COUPON_DATE ,
  COALESCE(R_INCOME_ACCRUAL_BASIS, 0 ) AS R_INCOME_ACCRUAL_BASIS ,
  COALESCE(R_ODD_FIRST_COUPON, 0 ) AS R_ODD_FIRST_COUPON ,
  COALESCE(R_ODD_LAST_COUPON, 0 ) AS R_ODD_LAST_COUPON ,
  COALESCE(R_PENULTIMATE_COUPON_DATE, '' ) AS R_PENULTIMATE_COUPON_DATE ,
  COALESCE(R_DISCOUNT_DAYS_BASIS, 0 ) AS R_DISCOUNT_DAYS_BASIS ,
  COALESCE(R_NO_COUPON_ON_MATURITY, 0 ) AS R_NO_COUPON_ON_MATURITY ,
  COALESCE(R_YIELD_CONVENTION_ID, 0 ) AS R_YIELD_CONVENTION_ID ,
  COALESCE(R_COUPON_DAYS_BASIS, 0 ) AS R_COUPON_DAYS_BASIS ,
  COALESCE(R_USE_DP_BASIS_PRICING, 0 ) AS R_USE_DP_BASIS_PRICING ,
  COALESCE(R_PAY_RECEIVE_TYPE, 0 ) AS R_PAY_RECEIVE_TYPE ,
  COALESCE(REMAIN_FV, 0 ) AS REMAIN_FV ,
  COALESCE(REMAIN_FV2, 0 ) AS REMAIN_FV2 ,
  COALESCE(ANALYSE01, '' ) AS ANALYSE01 ,
  COALESCE(ANALYSE02, '' ) AS ANALYSE02 ,
  COALESCE(ANALYSE03, '' ) AS ANALYSE03 ,
  COALESCE(ANALYSE04, '' ) AS ANALYSE04 ,
  COALESCE(ANALYSE05, '' ) AS ANALYSE05 ,
  COALESCE(ANALYSE06, '' ) AS ANALYSE06 ,
  COALESCE(ANALYSE07, '' ) AS ANALYSE07 ,
  COALESCE(ANALYSE08, '' ) AS ANALYSE08 ,
  COALESCE(ANALYSE09, '' ) AS ANALYSE09 ,
  COALESCE(ANALYSE10, '' ) AS ANALYSE10 ,
  COALESCE(STAMP, 0 ) AS STAMP ,
  COALESCE(ACRL_SL_DAYS_RULE, 0 ) AS ACRL_SL_DAYS_RULE 
 FROM  dw_tdata.COS_000_SWDEALS_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  DEAL_NO ,
  START_DATE ,
  CROSS_CCY ,
  ACCOUNTING ,
  CONTINGENT ,
  OPTION_DEAL_NO ,
  PRINC_EXCH ,
  EXCH_RATE ,
  ASSET_LIAB ,
  REVAL_CCY ,
  ASYMM_CUR_HOL ,
  P_FORMULA ,
  P_TIMING ,
  P_FT_KEY ,
  P_FIXFLOAT ,
  P_RATE ,
  P_MARGIN ,
  P_INT_CALC_LOC ,
  P_INT_DAYS ,
  P_YIELD ,
  P_BASIS ,
  P_BASIS_FQ ,
  P_REVAL ,
  P_REVIEW_F ,
  P_REVIEW_1 ,
  P_RATE_OFF ,
  P_FREQ ,
  P_1ST_DT ,
  P_PREV_DT ,
  P_DT_CYCLE ,
  P_COUP_TYP ,
  P_NOM_EFF ,
  P_COMP_FRQ ,
  P_CDI_DISC ,
  P_CD_SELCT ,
  P_RD_SELCT ,
  P_ED_SELCT ,
  P_PRICE_M ,
  P_FPP_METD ,
  P_FPP_DATE ,
  P_EX_DAYS ,
  P_PPH_RND ,
  P_PPH_CAP ,
  P_PPH_INC ,
  P_PPH_CAPITAL_METHOD ,
  P_PPH_CAPITAL_DP ,
  P_PPH_INCOME_METHOD ,
  P_PPH_INCOME_DP ,
  P_PPH_SETTLE_METHOD ,
  P_PPH_SETTLE_DP ,
  P_PPH_DRV ,
  P_PPH_AFT ,
  P_FUFTDAYS ,
  P_MOD_MASK ,
  P_MND_MASK ,
  P_SHW_MASK ,
  P_BOND_PRI ,
  P_RNDMETH ,
  P_RNDPLACE ,
  P_SEPARATE_RATESET ,
  P_DUAL_CCY ,
  P_CPN_CCY ,
  P_CPN_FV ,
  P_EXCH_RTE ,
  P_FRAC_UNIT ,
  P_DATED_DATE ,
  P_FNL_PRD_METHOD ,
  P_FPP_EARLY_DISCOUNT ,
  P_FPP_ADJ_MATURITY ,
  P_FPP_NO_PPH_ROUNDING ,
  P_FPP_DAYS_BASIS ,
  P_FIRST_COUPON_DATE ,
  P_INCOME_ACCRUAL_BASIS ,
  P_ODD_FIRST_COUPON ,
  P_ODD_LAST_COUPON ,
  P_PENULTIMATE_COUPON_DATE ,
  P_DISCOUNT_DAYS_BASIS ,
  P_NO_COUPON_ON_MATURITY ,
  P_YIELD_CONVENTION_ID ,
  P_COUPON_DAYS_BASIS ,
  P_USE_DP_BASIS_PRICING ,
  P_PAY_RECEIVE_TYPE ,
  R_FORMULA ,
  R_TIMING ,
  R_FT_KEY ,
  R_FIXFLOAT ,
  R_RATE ,
  R_MARGIN ,
  R_INT_CALC_LOC ,
  R_INT_DAYS ,
  R_YIELD ,
  R_BASIS ,
  R_BASIS_FQ ,
  R_REVAL ,
  R_REVIEW_F ,
  R_REVIEW_1 ,
  R_RATE_OFF ,
  R_FREQ ,
  R_1ST_DT ,
  R_PREV_DT ,
  R_DT_CYCLE ,
  R_COUP_TYP ,
  R_NOM_EFF ,
  R_COMP_FRQ ,
  R_CDI_DISC ,
  R_CD_SELCT ,
  R_RD_SELCT ,
  R_ED_SELCT ,
  R_PRICE_M ,
  R_FPP_METD ,
  R_FPP_DATE ,
  R_EX_DAYS ,
  R_PPH_RND ,
  R_PPH_CAP ,
  R_PPH_INC ,
  R_PPH_CAPITAL_METHOD ,
  R_PPH_CAPITAL_DP ,
  R_PPH_INCOME_METHOD ,
  R_PPH_INCOME_DP ,
  R_PPH_SETTLE_METHOD ,
  R_PPH_SETTLE_DP ,
  R_PPH_DRV ,
  R_PPH_AFT ,
  R_FUFTDAYS ,
  R_MOD_MASK ,
  R_MND_MASK ,
  R_SHW_MASK ,
  R_BOND_PRI ,
  R_RNDMETH ,
  R_RNDPLACE ,
  R_SEPARATE_RATESET ,
  R_DUAL_CCY ,
  R_CPN_CCY ,
  R_CPN_FV ,
  R_EXCH_RTE ,
  R_FRAC_UNIT ,
  R_DATED_DATE ,
  R_FNL_PRD_METHOD ,
  R_FPP_EARLY_DISCOUNT ,
  R_FPP_ADJ_MATURITY ,
  R_FPP_NO_PPH_ROUNDING ,
  R_FPP_DAYS_BASIS ,
  R_FIRST_COUPON_DATE ,
  R_INCOME_ACCRUAL_BASIS ,
  R_ODD_FIRST_COUPON ,
  R_ODD_LAST_COUPON ,
  R_PENULTIMATE_COUPON_DATE ,
  R_DISCOUNT_DAYS_BASIS ,
  R_NO_COUPON_ON_MATURITY ,
  R_YIELD_CONVENTION_ID ,
  R_COUPON_DAYS_BASIS ,
  R_USE_DP_BASIS_PRICING ,
  R_PAY_RECEIVE_TYPE ,
  REMAIN_FV ,
  REMAIN_FV2 ,
  ANALYSE01 ,
  ANALYSE02 ,
  ANALYSE03 ,
  ANALYSE04 ,
  ANALYSE05 ,
  ANALYSE06 ,
  ANALYSE07 ,
  ANALYSE08 ,
  ANALYSE09 ,
  ANALYSE10 ,
  STAMP ,
  ACRL_SL_DAYS_RULE 
 FROM dw_sdata.COS_000_SWDEALS 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.DEAL_NO = T.DEAL_NO
WHERE
(T.DEAL_NO IS NULL)
 OR N.START_DATE<>T.START_DATE
 OR N.CROSS_CCY<>T.CROSS_CCY
 OR N.ACCOUNTING<>T.ACCOUNTING
 OR N.CONTINGENT<>T.CONTINGENT
 OR N.OPTION_DEAL_NO<>T.OPTION_DEAL_NO
 OR N.PRINC_EXCH<>T.PRINC_EXCH
 OR N.EXCH_RATE<>T.EXCH_RATE
 OR N.ASSET_LIAB<>T.ASSET_LIAB
 OR N.REVAL_CCY<>T.REVAL_CCY
 OR N.ASYMM_CUR_HOL<>T.ASYMM_CUR_HOL
 OR N.P_FORMULA<>T.P_FORMULA
 OR N.P_TIMING<>T.P_TIMING
 OR N.P_FT_KEY<>T.P_FT_KEY
 OR N.P_FIXFLOAT<>T.P_FIXFLOAT
 OR N.P_RATE<>T.P_RATE
 OR N.P_MARGIN<>T.P_MARGIN
 OR N.P_INT_CALC_LOC<>T.P_INT_CALC_LOC
 OR N.P_INT_DAYS<>T.P_INT_DAYS
 OR N.P_YIELD<>T.P_YIELD
 OR N.P_BASIS<>T.P_BASIS
 OR N.P_BASIS_FQ<>T.P_BASIS_FQ
 OR N.P_REVAL<>T.P_REVAL
 OR N.P_REVIEW_F<>T.P_REVIEW_F
 OR N.P_REVIEW_1<>T.P_REVIEW_1
 OR N.P_RATE_OFF<>T.P_RATE_OFF
 OR N.P_FREQ<>T.P_FREQ
 OR N.P_1ST_DT<>T.P_1ST_DT
 OR N.P_PREV_DT<>T.P_PREV_DT
 OR N.P_DT_CYCLE<>T.P_DT_CYCLE
 OR N.P_COUP_TYP<>T.P_COUP_TYP
 OR N.P_NOM_EFF<>T.P_NOM_EFF
 OR N.P_COMP_FRQ<>T.P_COMP_FRQ
 OR N.P_CDI_DISC<>T.P_CDI_DISC
 OR N.P_CD_SELCT<>T.P_CD_SELCT
 OR N.P_RD_SELCT<>T.P_RD_SELCT
 OR N.P_ED_SELCT<>T.P_ED_SELCT
 OR N.P_PRICE_M<>T.P_PRICE_M
 OR N.P_FPP_METD<>T.P_FPP_METD
 OR N.P_FPP_DATE<>T.P_FPP_DATE
 OR N.P_EX_DAYS<>T.P_EX_DAYS
 OR N.P_PPH_RND<>T.P_PPH_RND
 OR N.P_PPH_CAP<>T.P_PPH_CAP
 OR N.P_PPH_INC<>T.P_PPH_INC
 OR N.P_PPH_CAPITAL_METHOD<>T.P_PPH_CAPITAL_METHOD
 OR N.P_PPH_CAPITAL_DP<>T.P_PPH_CAPITAL_DP
 OR N.P_PPH_INCOME_METHOD<>T.P_PPH_INCOME_METHOD
 OR N.P_PPH_INCOME_DP<>T.P_PPH_INCOME_DP
 OR N.P_PPH_SETTLE_METHOD<>T.P_PPH_SETTLE_METHOD
 OR N.P_PPH_SETTLE_DP<>T.P_PPH_SETTLE_DP
 OR N.P_PPH_DRV<>T.P_PPH_DRV
 OR N.P_PPH_AFT<>T.P_PPH_AFT
 OR N.P_FUFTDAYS<>T.P_FUFTDAYS
 OR N.P_MOD_MASK<>T.P_MOD_MASK
 OR N.P_MND_MASK<>T.P_MND_MASK
 OR N.P_SHW_MASK<>T.P_SHW_MASK
 OR N.P_BOND_PRI<>T.P_BOND_PRI
 OR N.P_RNDMETH<>T.P_RNDMETH
 OR N.P_RNDPLACE<>T.P_RNDPLACE
 OR N.P_SEPARATE_RATESET<>T.P_SEPARATE_RATESET
 OR N.P_DUAL_CCY<>T.P_DUAL_CCY
 OR N.P_CPN_CCY<>T.P_CPN_CCY
 OR N.P_CPN_FV<>T.P_CPN_FV
 OR N.P_EXCH_RTE<>T.P_EXCH_RTE
 OR N.P_FRAC_UNIT<>T.P_FRAC_UNIT
 OR N.P_DATED_DATE<>T.P_DATED_DATE
 OR N.P_FNL_PRD_METHOD<>T.P_FNL_PRD_METHOD
 OR N.P_FPP_EARLY_DISCOUNT<>T.P_FPP_EARLY_DISCOUNT
 OR N.P_FPP_ADJ_MATURITY<>T.P_FPP_ADJ_MATURITY
 OR N.P_FPP_NO_PPH_ROUNDING<>T.P_FPP_NO_PPH_ROUNDING
 OR N.P_FPP_DAYS_BASIS<>T.P_FPP_DAYS_BASIS
 OR N.P_FIRST_COUPON_DATE<>T.P_FIRST_COUPON_DATE
 OR N.P_INCOME_ACCRUAL_BASIS<>T.P_INCOME_ACCRUAL_BASIS
 OR N.P_ODD_FIRST_COUPON<>T.P_ODD_FIRST_COUPON
 OR N.P_ODD_LAST_COUPON<>T.P_ODD_LAST_COUPON
 OR N.P_PENULTIMATE_COUPON_DATE<>T.P_PENULTIMATE_COUPON_DATE
 OR N.P_DISCOUNT_DAYS_BASIS<>T.P_DISCOUNT_DAYS_BASIS
 OR N.P_NO_COUPON_ON_MATURITY<>T.P_NO_COUPON_ON_MATURITY
 OR N.P_YIELD_CONVENTION_ID<>T.P_YIELD_CONVENTION_ID
 OR N.P_COUPON_DAYS_BASIS<>T.P_COUPON_DAYS_BASIS
 OR N.P_USE_DP_BASIS_PRICING<>T.P_USE_DP_BASIS_PRICING
 OR N.P_PAY_RECEIVE_TYPE<>T.P_PAY_RECEIVE_TYPE
 OR N.R_FORMULA<>T.R_FORMULA
 OR N.R_TIMING<>T.R_TIMING
 OR N.R_FT_KEY<>T.R_FT_KEY
 OR N.R_FIXFLOAT<>T.R_FIXFLOAT
 OR N.R_RATE<>T.R_RATE
 OR N.R_MARGIN<>T.R_MARGIN
 OR N.R_INT_CALC_LOC<>T.R_INT_CALC_LOC
 OR N.R_INT_DAYS<>T.R_INT_DAYS
 OR N.R_YIELD<>T.R_YIELD
 OR N.R_BASIS<>T.R_BASIS
 OR N.R_BASIS_FQ<>T.R_BASIS_FQ
 OR N.R_REVAL<>T.R_REVAL
 OR N.R_REVIEW_F<>T.R_REVIEW_F
 OR N.R_REVIEW_1<>T.R_REVIEW_1
 OR N.R_RATE_OFF<>T.R_RATE_OFF
 OR N.R_FREQ<>T.R_FREQ
 OR N.R_1ST_DT<>T.R_1ST_DT
 OR N.R_PREV_DT<>T.R_PREV_DT
 OR N.R_DT_CYCLE<>T.R_DT_CYCLE
 OR N.R_COUP_TYP<>T.R_COUP_TYP
 OR N.R_NOM_EFF<>T.R_NOM_EFF
 OR N.R_COMP_FRQ<>T.R_COMP_FRQ
 OR N.R_CDI_DISC<>T.R_CDI_DISC
 OR N.R_CD_SELCT<>T.R_CD_SELCT
 OR N.R_RD_SELCT<>T.R_RD_SELCT
 OR N.R_ED_SELCT<>T.R_ED_SELCT
 OR N.R_PRICE_M<>T.R_PRICE_M
 OR N.R_FPP_METD<>T.R_FPP_METD
 OR N.R_FPP_DATE<>T.R_FPP_DATE
 OR N.R_EX_DAYS<>T.R_EX_DAYS
 OR N.R_PPH_RND<>T.R_PPH_RND
 OR N.R_PPH_CAP<>T.R_PPH_CAP
 OR N.R_PPH_INC<>T.R_PPH_INC
 OR N.R_PPH_CAPITAL_METHOD<>T.R_PPH_CAPITAL_METHOD
 OR N.R_PPH_CAPITAL_DP<>T.R_PPH_CAPITAL_DP
 OR N.R_PPH_INCOME_METHOD<>T.R_PPH_INCOME_METHOD
 OR N.R_PPH_INCOME_DP<>T.R_PPH_INCOME_DP
 OR N.R_PPH_SETTLE_METHOD<>T.R_PPH_SETTLE_METHOD
 OR N.R_PPH_SETTLE_DP<>T.R_PPH_SETTLE_DP
 OR N.R_PPH_DRV<>T.R_PPH_DRV
 OR N.R_PPH_AFT<>T.R_PPH_AFT
 OR N.R_FUFTDAYS<>T.R_FUFTDAYS
 OR N.R_MOD_MASK<>T.R_MOD_MASK
 OR N.R_MND_MASK<>T.R_MND_MASK
 OR N.R_SHW_MASK<>T.R_SHW_MASK
 OR N.R_BOND_PRI<>T.R_BOND_PRI
 OR N.R_RNDMETH<>T.R_RNDMETH
 OR N.R_RNDPLACE<>T.R_RNDPLACE
 OR N.R_SEPARATE_RATESET<>T.R_SEPARATE_RATESET
 OR N.R_DUAL_CCY<>T.R_DUAL_CCY
 OR N.R_CPN_CCY<>T.R_CPN_CCY
 OR N.R_CPN_FV<>T.R_CPN_FV
 OR N.R_EXCH_RTE<>T.R_EXCH_RTE
 OR N.R_FRAC_UNIT<>T.R_FRAC_UNIT
 OR N.R_DATED_DATE<>T.R_DATED_DATE
 OR N.R_FNL_PRD_METHOD<>T.R_FNL_PRD_METHOD
 OR N.R_FPP_EARLY_DISCOUNT<>T.R_FPP_EARLY_DISCOUNT
 OR N.R_FPP_ADJ_MATURITY<>T.R_FPP_ADJ_MATURITY
 OR N.R_FPP_NO_PPH_ROUNDING<>T.R_FPP_NO_PPH_ROUNDING
 OR N.R_FPP_DAYS_BASIS<>T.R_FPP_DAYS_BASIS
 OR N.R_FIRST_COUPON_DATE<>T.R_FIRST_COUPON_DATE
 OR N.R_INCOME_ACCRUAL_BASIS<>T.R_INCOME_ACCRUAL_BASIS
 OR N.R_ODD_FIRST_COUPON<>T.R_ODD_FIRST_COUPON
 OR N.R_ODD_LAST_COUPON<>T.R_ODD_LAST_COUPON
 OR N.R_PENULTIMATE_COUPON_DATE<>T.R_PENULTIMATE_COUPON_DATE
 OR N.R_DISCOUNT_DAYS_BASIS<>T.R_DISCOUNT_DAYS_BASIS
 OR N.R_NO_COUPON_ON_MATURITY<>T.R_NO_COUPON_ON_MATURITY
 OR N.R_YIELD_CONVENTION_ID<>T.R_YIELD_CONVENTION_ID
 OR N.R_COUPON_DAYS_BASIS<>T.R_COUPON_DAYS_BASIS
 OR N.R_USE_DP_BASIS_PRICING<>T.R_USE_DP_BASIS_PRICING
 OR N.R_PAY_RECEIVE_TYPE<>T.R_PAY_RECEIVE_TYPE
 OR N.REMAIN_FV<>T.REMAIN_FV
 OR N.REMAIN_FV2<>T.REMAIN_FV2
 OR N.ANALYSE01<>T.ANALYSE01
 OR N.ANALYSE02<>T.ANALYSE02
 OR N.ANALYSE03<>T.ANALYSE03
 OR N.ANALYSE04<>T.ANALYSE04
 OR N.ANALYSE05<>T.ANALYSE05
 OR N.ANALYSE06<>T.ANALYSE06
 OR N.ANALYSE07<>T.ANALYSE07
 OR N.ANALYSE08<>T.ANALYSE08
 OR N.ANALYSE09<>T.ANALYSE09
 OR N.ANALYSE10<>T.ANALYSE10
 OR N.STAMP<>T.STAMP
 OR N.ACRL_SL_DAYS_RULE<>T.ACRL_SL_DAYS_RULE
;

--Step3:
UPDATE dw_sdata.COS_000_SWDEALS P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_160
WHERE P.End_Dt=DATE('2100-12-31')
AND P.DEAL_NO=T_160.DEAL_NO
;

--Step4:
INSERT  INTO dw_sdata.COS_000_SWDEALS SELECT * FROM T_160;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
