#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ECF_002_T01_CUST_INFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ECF_002_T01_CUST_INFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_166 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ECF_002_T01_CUST_INFO WHERE 1=0;

--Step2:
INSERT  INTO T_166 (
  PARTY_ID,
  ECIF_CUST_NO,
  CERT_TYPE,
  CERT_NO,
  ORG_CODE,
  BUSINESS_LICENSE_NO,
  SPE_INST_CODE,
  PARTY_NAME,
  CUST_SHORTNAME,
  GOVN_EXPD_DATE,
  UNIT_STDCODE_EXPDATE,
  CUSTOMER_TYPE_CD,
  CUST_ENNAME,
  CUST_SHORT_ENNAME,
  UNIT_CREDIT_CODE,
  TAX_REG_NO,
  TAX_AREA_NO,
  ORG_START_DATE,
  REG_CPTL_CURR,
  REG_CPTL,
  REG_RECEIVE_RATE,
  COUNTRY,
  COUNT_TYPE,
  PROVINCE_R,
  PROVINCE_M,
  REGISTERED_TYPE_CD,
  CORP_REG_NO,
  CORP_CODE,
  ORG_TYPE,
  ORG_SIZ,
  ADMN_TYPE,
  EMP_NUM,
  INDUSTRY_TYPE,
  OWNERSHIP_TYPE_CODE,
  MANG_DEPT,
  LIST_FLAG,
  HOLDING_NAME,
  ACTUAL_CONTROLLER,
  LEGALINCHARGE_TYPE,
  LGPS_NAME,
  LGPS_CERT_TYPE,
  LGPS_CERT_NO,
  CLOSE_DATE,
  SUP_FLAG,
  LGPS_CONTACT,
  FIN_CONNTR,
  FIN_CONTACT,
  FIN_CERT_TYPE,
  FIN_CERT_NO,
  AGENT_CUST_NAME,
  AGENT_PAPER_TYPE,
  AGENT_PAPER_NO,
  VALID_BEG_DATE,
  VALID_END_DATE,
  HANDLE_NAME,
  HANDLE_PAPER_TYPE,
  HANDLE_PAPER_NO,
  HLD_DATE,
  HAND_FLAG,
  HOLDING_TYPE,
  OPERATE_AREA,
  OPERATE_OWNERSHIP_CD,
  IMEX_MANA_IND,
  BASIC_CUSTOMER_IND,
  BSSAV_ACC_NO,
  BASIC_AC_OPEN_BNK,
  BAS_ACBANK_NO,
  BAS_OPEN_PERMIT_NO,
  ACCT_LIC_NO,
  LOAN_CARD_NO,
  LOAN_CARD_CHECK_DATE,
  OPEN_ORG,
  OWN_ORG,
  CUST_MAINT_STAT_CODE,
  RM_TEAM_NO,
  GROUPACCT_SIGN_FLAG,
  BANK_REL_ENTRPS_FLAG,
  COPER_AGR_CUST_FLAG,
  DEBT_TRSF_STOCK_CUST,
  GROUPCUS_FLAG,
  GROUP_CUST_NAME,
  GOV_FLAG,
  NRA_FLAG,
  CUST_FORE_EXCH_ATTR,
  ECON_NATURE,
  FORE_EXCH_ICCARD_NO,
  IMP_DIRE,
  T_CUSTOMER_TYPE,
  FIRST_NAME,
  SECOND_NAME,
  BUSI_SITE_FLAG,
  RES_COUNTRY,
  FORE_INV_COUNTRY,
  SPE_ECON_INST,
  SPE_ECON_INST_FLAG,
  FORE_CODE,
  FORE_INDUSTRY_ATTR,
  FORE_ECON_TYPE,
  CUST_LEVEL,
  ENTP_CRDG_LEVEL,
  NEW_EVAL_RESULT,
  CORP_IMP_LEVEL,
  INTER_CTL_CUST_FLAG,
  BANK_CRET_CUST_FLAG,
  CREDIT_POLICY_CD,
  CREDIT_INDUSTRY_TYPE,
  FIRLN_DATE,
  STRP_BAD_ASST_CUST,
  OUR_BANK_NPL_RECORD,
  OTHER_BANK_NPL_RECORD,
  STATUS_FLAG,
  CREDIT_CUST_FLAG,
  CUST_STATE,
  LAST_UPDATED_TE,
  LAST_UPDATED_ORG,
  CREATED_TS,
  UPDATED_TS,
  INIT_SYSTEM_ID,
  INIT_CREATED_TS,
  LAST_SYSTEM_ID,
  LAST_UPDATED_TS,
  INDUSTRY_TYPE_INNER,
  TAXPAYER_TYPE,
  start_dt,
  end_dt)
SELECT
  N.PARTY_ID,
  N.ECIF_CUST_NO,
  N.CERT_TYPE,
  N.CERT_NO,
  N.ORG_CODE,
  N.BUSINESS_LICENSE_NO,
  N.SPE_INST_CODE,
  N.PARTY_NAME,
  N.CUST_SHORTNAME,
  N.GOVN_EXPD_DATE,
  N.UNIT_STDCODE_EXPDATE,
  N.CUSTOMER_TYPE_CD,
  N.CUST_ENNAME,
  N.CUST_SHORT_ENNAME,
  N.UNIT_CREDIT_CODE,
  N.TAX_REG_NO,
  N.TAX_AREA_NO,
  N.ORG_START_DATE,
  N.REG_CPTL_CURR,
  N.REG_CPTL,
  N.REG_RECEIVE_RATE,
  N.COUNTRY,
  N.COUNT_TYPE,
  N.PROVINCE_R,
  N.PROVINCE_M,
  N.REGISTERED_TYPE_CD,
  N.CORP_REG_NO,
  N.CORP_CODE,
  N.ORG_TYPE,
  N.ORG_SIZ,
  N.ADMN_TYPE,
  N.EMP_NUM,
  N.INDUSTRY_TYPE,
  N.OWNERSHIP_TYPE_CODE,
  N.MANG_DEPT,
  N.LIST_FLAG,
  N.HOLDING_NAME,
  N.ACTUAL_CONTROLLER,
  N.LEGALINCHARGE_TYPE,
  N.LGPS_NAME,
  N.LGPS_CERT_TYPE,
  N.LGPS_CERT_NO,
  N.CLOSE_DATE,
  N.SUP_FLAG,
  N.LGPS_CONTACT,
  N.FIN_CONNTR,
  N.FIN_CONTACT,
  N.FIN_CERT_TYPE,
  N.FIN_CERT_NO,
  N.AGENT_CUST_NAME,
  N.AGENT_PAPER_TYPE,
  N.AGENT_PAPER_NO,
  N.VALID_BEG_DATE,
  N.VALID_END_DATE,
  N.HANDLE_NAME,
  N.HANDLE_PAPER_TYPE,
  N.HANDLE_PAPER_NO,
  N.HLD_DATE,
  N.HAND_FLAG,
  N.HOLDING_TYPE,
  N.OPERATE_AREA,
  N.OPERATE_OWNERSHIP_CD,
  N.IMEX_MANA_IND,
  N.BASIC_CUSTOMER_IND,
  N.BSSAV_ACC_NO,
  N.BASIC_AC_OPEN_BNK,
  N.BAS_ACBANK_NO,
  N.BAS_OPEN_PERMIT_NO,
  N.ACCT_LIC_NO,
  N.LOAN_CARD_NO,
  N.LOAN_CARD_CHECK_DATE,
  N.OPEN_ORG,
  N.OWN_ORG,
  N.CUST_MAINT_STAT_CODE,
  N.RM_TEAM_NO,
  N.GROUPACCT_SIGN_FLAG,
  N.BANK_REL_ENTRPS_FLAG,
  N.COPER_AGR_CUST_FLAG,
  N.DEBT_TRSF_STOCK_CUST,
  N.GROUPCUS_FLAG,
  N.GROUP_CUST_NAME,
  N.GOV_FLAG,
  N.NRA_FLAG,
  N.CUST_FORE_EXCH_ATTR,
  N.ECON_NATURE,
  N.FORE_EXCH_ICCARD_NO,
  N.IMP_DIRE,
  N.T_CUSTOMER_TYPE,
  N.FIRST_NAME,
  N.SECOND_NAME,
  N.BUSI_SITE_FLAG,
  N.RES_COUNTRY,
  N.FORE_INV_COUNTRY,
  N.SPE_ECON_INST,
  N.SPE_ECON_INST_FLAG,
  N.FORE_CODE,
  N.FORE_INDUSTRY_ATTR,
  N.FORE_ECON_TYPE,
  N.CUST_LEVEL,
  N.ENTP_CRDG_LEVEL,
  N.NEW_EVAL_RESULT,
  N.CORP_IMP_LEVEL,
  N.INTER_CTL_CUST_FLAG,
  N.BANK_CRET_CUST_FLAG,
  N.CREDIT_POLICY_CD,
  N.CREDIT_INDUSTRY_TYPE,
  N.FIRLN_DATE,
  N.STRP_BAD_ASST_CUST,
  N.OUR_BANK_NPL_RECORD,
  N.OTHER_BANK_NPL_RECORD,
  N.STATUS_FLAG,
  N.CREDIT_CUST_FLAG,
  N.CUST_STATE,
  N.LAST_UPDATED_TE,
  N.LAST_UPDATED_ORG,
  N.CREATED_TS,
  N.UPDATED_TS,
  N.INIT_SYSTEM_ID,
  N.INIT_CREATED_TS,
  N.LAST_SYSTEM_ID,
  N.LAST_UPDATED_TS,
  N.INDUSTRY_TYPE_INNER,
  N.TAXPAYER_TYPE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PARTY_ID, '' ) AS PARTY_ID ,
  COALESCE(ECIF_CUST_NO, '' ) AS ECIF_CUST_NO ,
  COALESCE(CERT_TYPE, '' ) AS CERT_TYPE ,
  COALESCE(CERT_NO, '' ) AS CERT_NO ,
  COALESCE(ORG_CODE, '' ) AS ORG_CODE ,
  COALESCE(BUSINESS_LICENSE_NO, '' ) AS BUSINESS_LICENSE_NO ,
  COALESCE(SPE_INST_CODE, '' ) AS SPE_INST_CODE ,
  COALESCE(PARTY_NAME, '' ) AS PARTY_NAME ,
  COALESCE(CUST_SHORTNAME, '' ) AS CUST_SHORTNAME ,
  COALESCE(GOVN_EXPD_DATE, '' ) AS GOVN_EXPD_DATE ,
  COALESCE(UNIT_STDCODE_EXPDATE, '' ) AS UNIT_STDCODE_EXPDATE ,
  COALESCE(CUSTOMER_TYPE_CD, '' ) AS CUSTOMER_TYPE_CD ,
  COALESCE(CUST_ENNAME, '' ) AS CUST_ENNAME ,
  COALESCE(CUST_SHORT_ENNAME, '' ) AS CUST_SHORT_ENNAME ,
  COALESCE(UNIT_CREDIT_CODE, '' ) AS UNIT_CREDIT_CODE ,
  COALESCE(TAX_REG_NO, '' ) AS TAX_REG_NO ,
  COALESCE(TAX_AREA_NO, '' ) AS TAX_AREA_NO ,
  COALESCE(ORG_START_DATE, '' ) AS ORG_START_DATE ,
  COALESCE(REG_CPTL_CURR, '' ) AS REG_CPTL_CURR ,
  COALESCE(REG_CPTL, 0 ) AS REG_CPTL ,
  COALESCE(REG_RECEIVE_RATE, '' ) AS REG_RECEIVE_RATE ,
  COALESCE(COUNTRY, '' ) AS COUNTRY ,
  COALESCE(COUNT_TYPE, '' ) AS COUNT_TYPE ,
  COALESCE(PROVINCE_R, '' ) AS PROVINCE_R ,
  COALESCE(PROVINCE_M, '' ) AS PROVINCE_M ,
  COALESCE(REGISTERED_TYPE_CD, '' ) AS REGISTERED_TYPE_CD ,
  COALESCE(CORP_REG_NO, '' ) AS CORP_REG_NO ,
  COALESCE(CORP_CODE, '' ) AS CORP_CODE ,
  COALESCE(ORG_TYPE, '' ) AS ORG_TYPE ,
  COALESCE(ORG_SIZ, '' ) AS ORG_SIZ ,
  COALESCE(ADMN_TYPE, '' ) AS ADMN_TYPE ,
  COALESCE(EMP_NUM, 0 ) AS EMP_NUM ,
  COALESCE(INDUSTRY_TYPE, '' ) AS INDUSTRY_TYPE ,
  COALESCE(OWNERSHIP_TYPE_CODE, '' ) AS OWNERSHIP_TYPE_CODE ,
  COALESCE(MANG_DEPT, '' ) AS MANG_DEPT ,
  COALESCE(LIST_FLAG, '' ) AS LIST_FLAG ,
  COALESCE(HOLDING_NAME, '' ) AS HOLDING_NAME ,
  COALESCE(ACTUAL_CONTROLLER, '' ) AS ACTUAL_CONTROLLER ,
  COALESCE(LEGALINCHARGE_TYPE, '' ) AS LEGALINCHARGE_TYPE ,
  COALESCE(LGPS_NAME, '' ) AS LGPS_NAME ,
  COALESCE(LGPS_CERT_TYPE, '' ) AS LGPS_CERT_TYPE ,
  COALESCE(LGPS_CERT_NO, '' ) AS LGPS_CERT_NO ,
  COALESCE(CLOSE_DATE, '' ) AS CLOSE_DATE ,
  COALESCE(SUP_FLAG, '' ) AS SUP_FLAG ,
  COALESCE(LGPS_CONTACT, '' ) AS LGPS_CONTACT ,
  COALESCE(FIN_CONNTR, '' ) AS FIN_CONNTR ,
  COALESCE(FIN_CONTACT, '' ) AS FIN_CONTACT ,
  COALESCE(FIN_CERT_TYPE, '' ) AS FIN_CERT_TYPE ,
  COALESCE(FIN_CERT_NO, '' ) AS FIN_CERT_NO ,
  COALESCE(AGENT_CUST_NAME, '' ) AS AGENT_CUST_NAME ,
  COALESCE(AGENT_PAPER_TYPE, '' ) AS AGENT_PAPER_TYPE ,
  COALESCE(AGENT_PAPER_NO, '' ) AS AGENT_PAPER_NO ,
  COALESCE(VALID_BEG_DATE, '' ) AS VALID_BEG_DATE ,
  COALESCE(VALID_END_DATE, '' ) AS VALID_END_DATE ,
  COALESCE(HANDLE_NAME, '' ) AS HANDLE_NAME ,
  COALESCE(HANDLE_PAPER_TYPE, '' ) AS HANDLE_PAPER_TYPE ,
  COALESCE(HANDLE_PAPER_NO, '' ) AS HANDLE_PAPER_NO ,
  COALESCE(HLD_DATE, '' ) AS HLD_DATE ,
  COALESCE(HAND_FLAG, '' ) AS HAND_FLAG ,
  COALESCE(HOLDING_TYPE, '' ) AS HOLDING_TYPE ,
  COALESCE(OPERATE_AREA, 0 ) AS OPERATE_AREA ,
  COALESCE(OPERATE_OWNERSHIP_CD, '' ) AS OPERATE_OWNERSHIP_CD ,
  COALESCE(IMEX_MANA_IND, '' ) AS IMEX_MANA_IND ,
  COALESCE(BASIC_CUSTOMER_IND, '' ) AS BASIC_CUSTOMER_IND ,
  COALESCE(BSSAV_ACC_NO, '' ) AS BSSAV_ACC_NO ,
  COALESCE(BASIC_AC_OPEN_BNK, '' ) AS BASIC_AC_OPEN_BNK ,
  COALESCE(BAS_ACBANK_NO, '' ) AS BAS_ACBANK_NO ,
  COALESCE(BAS_OPEN_PERMIT_NO, '' ) AS BAS_OPEN_PERMIT_NO ,
  COALESCE(ACCT_LIC_NO, '' ) AS ACCT_LIC_NO ,
  COALESCE(LOAN_CARD_NO, '' ) AS LOAN_CARD_NO ,
  COALESCE(LOAN_CARD_CHECK_DATE, '' ) AS LOAN_CARD_CHECK_DATE ,
  COALESCE(OPEN_ORG, '' ) AS OPEN_ORG ,
  COALESCE(OWN_ORG, '' ) AS OWN_ORG ,
  COALESCE(CUST_MAINT_STAT_CODE, '' ) AS CUST_MAINT_STAT_CODE ,
  COALESCE(RM_TEAM_NO, '' ) AS RM_TEAM_NO ,
  COALESCE(GROUPACCT_SIGN_FLAG, '' ) AS GROUPACCT_SIGN_FLAG ,
  COALESCE(BANK_REL_ENTRPS_FLAG, '' ) AS BANK_REL_ENTRPS_FLAG ,
  COALESCE(COPER_AGR_CUST_FLAG, '' ) AS COPER_AGR_CUST_FLAG ,
  COALESCE(DEBT_TRSF_STOCK_CUST, '' ) AS DEBT_TRSF_STOCK_CUST ,
  COALESCE(GROUPCUS_FLAG, '' ) AS GROUPCUS_FLAG ,
  COALESCE(GROUP_CUST_NAME, '' ) AS GROUP_CUST_NAME ,
  COALESCE(GOV_FLAG, '' ) AS GOV_FLAG ,
  COALESCE(NRA_FLAG, '' ) AS NRA_FLAG ,
  COALESCE(CUST_FORE_EXCH_ATTR, '' ) AS CUST_FORE_EXCH_ATTR ,
  COALESCE(ECON_NATURE, '' ) AS ECON_NATURE ,
  COALESCE(FORE_EXCH_ICCARD_NO, '' ) AS FORE_EXCH_ICCARD_NO ,
  COALESCE(IMP_DIRE, '' ) AS IMP_DIRE ,
  COALESCE(T_CUSTOMER_TYPE, '' ) AS T_CUSTOMER_TYPE ,
  COALESCE(FIRST_NAME, '' ) AS FIRST_NAME ,
  COALESCE(SECOND_NAME, '' ) AS SECOND_NAME ,
  COALESCE(BUSI_SITE_FLAG, '' ) AS BUSI_SITE_FLAG ,
  COALESCE(RES_COUNTRY, '' ) AS RES_COUNTRY ,
  COALESCE(FORE_INV_COUNTRY, '' ) AS FORE_INV_COUNTRY ,
  COALESCE(SPE_ECON_INST, '' ) AS SPE_ECON_INST ,
  COALESCE(SPE_ECON_INST_FLAG, '' ) AS SPE_ECON_INST_FLAG ,
  COALESCE(FORE_CODE, '' ) AS FORE_CODE ,
  COALESCE(FORE_INDUSTRY_ATTR, '' ) AS FORE_INDUSTRY_ATTR ,
  COALESCE(FORE_ECON_TYPE, '' ) AS FORE_ECON_TYPE ,
  COALESCE(CUST_LEVEL, '' ) AS CUST_LEVEL ,
  COALESCE(ENTP_CRDG_LEVEL, '' ) AS ENTP_CRDG_LEVEL ,
  COALESCE(NEW_EVAL_RESULT, '' ) AS NEW_EVAL_RESULT ,
  COALESCE(CORP_IMP_LEVEL, '' ) AS CORP_IMP_LEVEL ,
  COALESCE(INTER_CTL_CUST_FLAG, '' ) AS INTER_CTL_CUST_FLAG ,
  COALESCE(BANK_CRET_CUST_FLAG, '' ) AS BANK_CRET_CUST_FLAG ,
  COALESCE(CREDIT_POLICY_CD, '' ) AS CREDIT_POLICY_CD ,
  COALESCE(CREDIT_INDUSTRY_TYPE, '' ) AS CREDIT_INDUSTRY_TYPE ,
  COALESCE(FIRLN_DATE, '' ) AS FIRLN_DATE ,
  COALESCE(STRP_BAD_ASST_CUST, '' ) AS STRP_BAD_ASST_CUST ,
  COALESCE(OUR_BANK_NPL_RECORD, '' ) AS OUR_BANK_NPL_RECORD ,
  COALESCE(OTHER_BANK_NPL_RECORD, '' ) AS OTHER_BANK_NPL_RECORD ,
  COALESCE(STATUS_FLAG, '' ) AS STATUS_FLAG ,
  COALESCE(CREDIT_CUST_FLAG, '' ) AS CREDIT_CUST_FLAG ,
  COALESCE(CUST_STATE, '' ) AS CUST_STATE ,
  COALESCE(LAST_UPDATED_TE, '' ) AS LAST_UPDATED_TE ,
  COALESCE(LAST_UPDATED_ORG, '' ) AS LAST_UPDATED_ORG ,
  COALESCE(CREATED_TS,'4999-12-31 00:00:00' ) AS CREATED_TS ,
  COALESCE(UPDATED_TS,'4999-12-31 00:00:00' ) AS UPDATED_TS ,
  COALESCE(INIT_SYSTEM_ID, '' ) AS INIT_SYSTEM_ID ,
  COALESCE(INIT_CREATED_TS,'4999-12-31 00:00:00' ) AS INIT_CREATED_TS ,
  COALESCE(LAST_SYSTEM_ID, '' ) AS LAST_SYSTEM_ID ,
  COALESCE(LAST_UPDATED_TS,'4999-12-31 00:00:00' ) AS LAST_UPDATED_TS ,
  COALESCE(INDUSTRY_TYPE_INNER, '' ) AS INDUSTRY_TYPE_INNER ,
  COALESCE(TAXPAYER_TYPE, '' ) AS TAXPAYER_TYPE 
 FROM  dw_tdata.ECF_002_T01_CUST_INFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PARTY_ID ,
  ECIF_CUST_NO ,
  CERT_TYPE ,
  CERT_NO ,
  ORG_CODE ,
  BUSINESS_LICENSE_NO ,
  SPE_INST_CODE ,
  PARTY_NAME ,
  CUST_SHORTNAME ,
  GOVN_EXPD_DATE ,
  UNIT_STDCODE_EXPDATE ,
  CUSTOMER_TYPE_CD ,
  CUST_ENNAME ,
  CUST_SHORT_ENNAME ,
  UNIT_CREDIT_CODE ,
  TAX_REG_NO ,
  TAX_AREA_NO ,
  ORG_START_DATE ,
  REG_CPTL_CURR ,
  REG_CPTL ,
  REG_RECEIVE_RATE ,
  COUNTRY ,
  COUNT_TYPE ,
  PROVINCE_R ,
  PROVINCE_M ,
  REGISTERED_TYPE_CD ,
  CORP_REG_NO ,
  CORP_CODE ,
  ORG_TYPE ,
  ORG_SIZ ,
  ADMN_TYPE ,
  EMP_NUM ,
  INDUSTRY_TYPE ,
  OWNERSHIP_TYPE_CODE ,
  MANG_DEPT ,
  LIST_FLAG ,
  HOLDING_NAME ,
  ACTUAL_CONTROLLER ,
  LEGALINCHARGE_TYPE ,
  LGPS_NAME ,
  LGPS_CERT_TYPE ,
  LGPS_CERT_NO ,
  CLOSE_DATE ,
  SUP_FLAG ,
  LGPS_CONTACT ,
  FIN_CONNTR ,
  FIN_CONTACT ,
  FIN_CERT_TYPE ,
  FIN_CERT_NO ,
  AGENT_CUST_NAME ,
  AGENT_PAPER_TYPE ,
  AGENT_PAPER_NO ,
  VALID_BEG_DATE ,
  VALID_END_DATE ,
  HANDLE_NAME ,
  HANDLE_PAPER_TYPE ,
  HANDLE_PAPER_NO ,
  HLD_DATE ,
  HAND_FLAG ,
  HOLDING_TYPE ,
  OPERATE_AREA ,
  OPERATE_OWNERSHIP_CD ,
  IMEX_MANA_IND ,
  BASIC_CUSTOMER_IND ,
  BSSAV_ACC_NO ,
  BASIC_AC_OPEN_BNK ,
  BAS_ACBANK_NO ,
  BAS_OPEN_PERMIT_NO ,
  ACCT_LIC_NO ,
  LOAN_CARD_NO ,
  LOAN_CARD_CHECK_DATE ,
  OPEN_ORG ,
  OWN_ORG ,
  CUST_MAINT_STAT_CODE ,
  RM_TEAM_NO ,
  GROUPACCT_SIGN_FLAG ,
  BANK_REL_ENTRPS_FLAG ,
  COPER_AGR_CUST_FLAG ,
  DEBT_TRSF_STOCK_CUST ,
  GROUPCUS_FLAG ,
  GROUP_CUST_NAME ,
  GOV_FLAG ,
  NRA_FLAG ,
  CUST_FORE_EXCH_ATTR ,
  ECON_NATURE ,
  FORE_EXCH_ICCARD_NO ,
  IMP_DIRE ,
  T_CUSTOMER_TYPE ,
  FIRST_NAME ,
  SECOND_NAME ,
  BUSI_SITE_FLAG ,
  RES_COUNTRY ,
  FORE_INV_COUNTRY ,
  SPE_ECON_INST ,
  SPE_ECON_INST_FLAG ,
  FORE_CODE ,
  FORE_INDUSTRY_ATTR ,
  FORE_ECON_TYPE ,
  CUST_LEVEL ,
  ENTP_CRDG_LEVEL ,
  NEW_EVAL_RESULT ,
  CORP_IMP_LEVEL ,
  INTER_CTL_CUST_FLAG ,
  BANK_CRET_CUST_FLAG ,
  CREDIT_POLICY_CD ,
  CREDIT_INDUSTRY_TYPE ,
  FIRLN_DATE ,
  STRP_BAD_ASST_CUST ,
  OUR_BANK_NPL_RECORD ,
  OTHER_BANK_NPL_RECORD ,
  STATUS_FLAG ,
  CREDIT_CUST_FLAG ,
  CUST_STATE ,
  LAST_UPDATED_TE ,
  LAST_UPDATED_ORG ,
  CREATED_TS ,
  UPDATED_TS ,
  INIT_SYSTEM_ID ,
  INIT_CREATED_TS ,
  LAST_SYSTEM_ID ,
  LAST_UPDATED_TS ,
  INDUSTRY_TYPE_INNER ,
  TAXPAYER_TYPE 
 FROM dw_sdata.ECF_002_T01_CUST_INFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.PARTY_ID = T.PARTY_ID
WHERE
(T.PARTY_ID IS NULL)
 OR N.ECIF_CUST_NO<>T.ECIF_CUST_NO
 OR N.CERT_TYPE<>T.CERT_TYPE
 OR N.CERT_NO<>T.CERT_NO
 OR N.ORG_CODE<>T.ORG_CODE
 OR N.BUSINESS_LICENSE_NO<>T.BUSINESS_LICENSE_NO
 OR N.SPE_INST_CODE<>T.SPE_INST_CODE
 OR N.PARTY_NAME<>T.PARTY_NAME
 OR N.CUST_SHORTNAME<>T.CUST_SHORTNAME
 OR N.GOVN_EXPD_DATE<>T.GOVN_EXPD_DATE
 OR N.UNIT_STDCODE_EXPDATE<>T.UNIT_STDCODE_EXPDATE
 OR N.CUSTOMER_TYPE_CD<>T.CUSTOMER_TYPE_CD
 OR N.CUST_ENNAME<>T.CUST_ENNAME
 OR N.CUST_SHORT_ENNAME<>T.CUST_SHORT_ENNAME
 OR N.UNIT_CREDIT_CODE<>T.UNIT_CREDIT_CODE
 OR N.TAX_REG_NO<>T.TAX_REG_NO
 OR N.TAX_AREA_NO<>T.TAX_AREA_NO
 OR N.ORG_START_DATE<>T.ORG_START_DATE
 OR N.REG_CPTL_CURR<>T.REG_CPTL_CURR
 OR N.REG_CPTL<>T.REG_CPTL
 OR N.REG_RECEIVE_RATE<>T.REG_RECEIVE_RATE
 OR N.COUNTRY<>T.COUNTRY
 OR N.COUNT_TYPE<>T.COUNT_TYPE
 OR N.PROVINCE_R<>T.PROVINCE_R
 OR N.PROVINCE_M<>T.PROVINCE_M
 OR N.REGISTERED_TYPE_CD<>T.REGISTERED_TYPE_CD
 OR N.CORP_REG_NO<>T.CORP_REG_NO
 OR N.CORP_CODE<>T.CORP_CODE
 OR N.ORG_TYPE<>T.ORG_TYPE
 OR N.ORG_SIZ<>T.ORG_SIZ
 OR N.ADMN_TYPE<>T.ADMN_TYPE
 OR N.EMP_NUM<>T.EMP_NUM
 OR N.INDUSTRY_TYPE<>T.INDUSTRY_TYPE
 OR N.OWNERSHIP_TYPE_CODE<>T.OWNERSHIP_TYPE_CODE
 OR N.MANG_DEPT<>T.MANG_DEPT
 OR N.LIST_FLAG<>T.LIST_FLAG
 OR N.HOLDING_NAME<>T.HOLDING_NAME
 OR N.ACTUAL_CONTROLLER<>T.ACTUAL_CONTROLLER
 OR N.LEGALINCHARGE_TYPE<>T.LEGALINCHARGE_TYPE
 OR N.LGPS_NAME<>T.LGPS_NAME
 OR N.LGPS_CERT_TYPE<>T.LGPS_CERT_TYPE
 OR N.LGPS_CERT_NO<>T.LGPS_CERT_NO
 OR N.CLOSE_DATE<>T.CLOSE_DATE
 OR N.SUP_FLAG<>T.SUP_FLAG
 OR N.LGPS_CONTACT<>T.LGPS_CONTACT
 OR N.FIN_CONNTR<>T.FIN_CONNTR
 OR N.FIN_CONTACT<>T.FIN_CONTACT
 OR N.FIN_CERT_TYPE<>T.FIN_CERT_TYPE
 OR N.FIN_CERT_NO<>T.FIN_CERT_NO
 OR N.AGENT_CUST_NAME<>T.AGENT_CUST_NAME
 OR N.AGENT_PAPER_TYPE<>T.AGENT_PAPER_TYPE
 OR N.AGENT_PAPER_NO<>T.AGENT_PAPER_NO
 OR N.VALID_BEG_DATE<>T.VALID_BEG_DATE
 OR N.VALID_END_DATE<>T.VALID_END_DATE
 OR N.HANDLE_NAME<>T.HANDLE_NAME
 OR N.HANDLE_PAPER_TYPE<>T.HANDLE_PAPER_TYPE
 OR N.HANDLE_PAPER_NO<>T.HANDLE_PAPER_NO
 OR N.HLD_DATE<>T.HLD_DATE
 OR N.HAND_FLAG<>T.HAND_FLAG
 OR N.HOLDING_TYPE<>T.HOLDING_TYPE
 OR N.OPERATE_AREA<>T.OPERATE_AREA
 OR N.OPERATE_OWNERSHIP_CD<>T.OPERATE_OWNERSHIP_CD
 OR N.IMEX_MANA_IND<>T.IMEX_MANA_IND
 OR N.BASIC_CUSTOMER_IND<>T.BASIC_CUSTOMER_IND
 OR N.BSSAV_ACC_NO<>T.BSSAV_ACC_NO
 OR N.BASIC_AC_OPEN_BNK<>T.BASIC_AC_OPEN_BNK
 OR N.BAS_ACBANK_NO<>T.BAS_ACBANK_NO
 OR N.BAS_OPEN_PERMIT_NO<>T.BAS_OPEN_PERMIT_NO
 OR N.ACCT_LIC_NO<>T.ACCT_LIC_NO
 OR N.LOAN_CARD_NO<>T.LOAN_CARD_NO
 OR N.LOAN_CARD_CHECK_DATE<>T.LOAN_CARD_CHECK_DATE
 OR N.OPEN_ORG<>T.OPEN_ORG
 OR N.OWN_ORG<>T.OWN_ORG
 OR N.CUST_MAINT_STAT_CODE<>T.CUST_MAINT_STAT_CODE
 OR N.RM_TEAM_NO<>T.RM_TEAM_NO
 OR N.GROUPACCT_SIGN_FLAG<>T.GROUPACCT_SIGN_FLAG
 OR N.BANK_REL_ENTRPS_FLAG<>T.BANK_REL_ENTRPS_FLAG
 OR N.COPER_AGR_CUST_FLAG<>T.COPER_AGR_CUST_FLAG
 OR N.DEBT_TRSF_STOCK_CUST<>T.DEBT_TRSF_STOCK_CUST
 OR N.GROUPCUS_FLAG<>T.GROUPCUS_FLAG
 OR N.GROUP_CUST_NAME<>T.GROUP_CUST_NAME
 OR N.GOV_FLAG<>T.GOV_FLAG
 OR N.NRA_FLAG<>T.NRA_FLAG
 OR N.CUST_FORE_EXCH_ATTR<>T.CUST_FORE_EXCH_ATTR
 OR N.ECON_NATURE<>T.ECON_NATURE
 OR N.FORE_EXCH_ICCARD_NO<>T.FORE_EXCH_ICCARD_NO
 OR N.IMP_DIRE<>T.IMP_DIRE
 OR N.T_CUSTOMER_TYPE<>T.T_CUSTOMER_TYPE
 OR N.FIRST_NAME<>T.FIRST_NAME
 OR N.SECOND_NAME<>T.SECOND_NAME
 OR N.BUSI_SITE_FLAG<>T.BUSI_SITE_FLAG
 OR N.RES_COUNTRY<>T.RES_COUNTRY
 OR N.FORE_INV_COUNTRY<>T.FORE_INV_COUNTRY
 OR N.SPE_ECON_INST<>T.SPE_ECON_INST
 OR N.SPE_ECON_INST_FLAG<>T.SPE_ECON_INST_FLAG
 OR N.FORE_CODE<>T.FORE_CODE
 OR N.FORE_INDUSTRY_ATTR<>T.FORE_INDUSTRY_ATTR
 OR N.FORE_ECON_TYPE<>T.FORE_ECON_TYPE
 OR N.CUST_LEVEL<>T.CUST_LEVEL
 OR N.ENTP_CRDG_LEVEL<>T.ENTP_CRDG_LEVEL
 OR N.NEW_EVAL_RESULT<>T.NEW_EVAL_RESULT
 OR N.CORP_IMP_LEVEL<>T.CORP_IMP_LEVEL
 OR N.INTER_CTL_CUST_FLAG<>T.INTER_CTL_CUST_FLAG
 OR N.BANK_CRET_CUST_FLAG<>T.BANK_CRET_CUST_FLAG
 OR N.CREDIT_POLICY_CD<>T.CREDIT_POLICY_CD
 OR N.CREDIT_INDUSTRY_TYPE<>T.CREDIT_INDUSTRY_TYPE
 OR N.FIRLN_DATE<>T.FIRLN_DATE
 OR N.STRP_BAD_ASST_CUST<>T.STRP_BAD_ASST_CUST
 OR N.OUR_BANK_NPL_RECORD<>T.OUR_BANK_NPL_RECORD
 OR N.OTHER_BANK_NPL_RECORD<>T.OTHER_BANK_NPL_RECORD
 OR N.STATUS_FLAG<>T.STATUS_FLAG
 OR N.CREDIT_CUST_FLAG<>T.CREDIT_CUST_FLAG
 OR N.CUST_STATE<>T.CUST_STATE
 OR N.LAST_UPDATED_TE<>T.LAST_UPDATED_TE
 OR N.LAST_UPDATED_ORG<>T.LAST_UPDATED_ORG
 OR N.CREATED_TS<>T.CREATED_TS
 OR N.UPDATED_TS<>T.UPDATED_TS
 OR N.INIT_SYSTEM_ID<>T.INIT_SYSTEM_ID
 OR N.INIT_CREATED_TS<>T.INIT_CREATED_TS
 OR N.LAST_SYSTEM_ID<>T.LAST_SYSTEM_ID
 OR N.LAST_UPDATED_TS<>T.LAST_UPDATED_TS
 OR N.INDUSTRY_TYPE_INNER<>T.INDUSTRY_TYPE_INNER
 OR N.TAXPAYER_TYPE<>T.TAXPAYER_TYPE
;

--Step3:
UPDATE dw_sdata.ECF_002_T01_CUST_INFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_166
WHERE P.End_Dt=DATE('2100-12-31')
AND P.PARTY_ID=T_166.PARTY_ID
;

--Step4:
INSERT  INTO dw_sdata.ECF_002_T01_CUST_INFO SELECT * FROM T_166;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
