#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.FSS_001_FD_FUNDAFFIRM WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.FSS_001_FD_FUNDAFFIRM SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_193 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.FSS_001_FD_FUNDAFFIRM WHERE 1=0;

--Step2:
INSERT  INTO T_193 (
  TRADEDATE,
  ORGANCODE,
  OPERCODE,
  ACCTSERIAL,
  TRADETIME,
  AGENTCORPCODE,
  CREATEFLAG,
  CANCELFLAG,
  BUSINESSKINDCODE,
  TRADECODE,
  TAACCT,
  CUSTOMERID,
  AFFIRMQUOTIENT,
  AFFIRMAMT,
  AFFIRMDATE,
  BOOKINGFLAG,
  BOOKINGDATE,
  SUCCESSFULQUOTIENT,
  QUOTIENTMODE,
  BONUSMODE,
  CONTINUEFLAG,
  OTHERCUSTOMERID,
  OTHERORGANCODE,
  APPLYKIND,
  CORPSERIAL,
  CORPRESPCODE,
  CHARGEMODE,
  SALECODE,
  AFFIRMFLAG,
  SENDFLAG,
  SECONDKINDCODE,
  SECONDORGANCODE,
  STOPNO,
  ORIACCTSERIAL,
  CUSTOMERMGRCODE,
  TABELONG,
  FUNDTRADECODE,
  FUNDAPPSHEETSERIALNO,
  LARGEREDEMPFLAG,
  DISCOUNTRATE,
  SUCCESSFULAMOUNT,
  RETURNCHARGE,
  TARGETBRANCHCODE,
  NOTESENDFLAG,
  CHNLNO,
  CUSTOMERKIND,
  CONTRACTNO,
  CHULIFLAG,
  PSPFBATCHSERIAL,
  GREENORGAN,
  ORIGINALAPPDATE,
  TARGETTAACCOUNTID,
  HOSTDATE,
  start_dt,
  end_dt)
SELECT
  N.TRADEDATE,
  N.ORGANCODE,
  N.OPERCODE,
  N.ACCTSERIAL,
  N.TRADETIME,
  N.AGENTCORPCODE,
  N.CREATEFLAG,
  N.CANCELFLAG,
  N.BUSINESSKINDCODE,
  N.TRADECODE,
  N.TAACCT,
  N.CUSTOMERID,
  N.AFFIRMQUOTIENT,
  N.AFFIRMAMT,
  N.AFFIRMDATE,
  N.BOOKINGFLAG,
  N.BOOKINGDATE,
  N.SUCCESSFULQUOTIENT,
  N.QUOTIENTMODE,
  N.BONUSMODE,
  N.CONTINUEFLAG,
  N.OTHERCUSTOMERID,
  N.OTHERORGANCODE,
  N.APPLYKIND,
  N.CORPSERIAL,
  N.CORPRESPCODE,
  N.CHARGEMODE,
  N.SALECODE,
  N.AFFIRMFLAG,
  N.SENDFLAG,
  N.SECONDKINDCODE,
  N.SECONDORGANCODE,
  N.STOPNO,
  N.ORIACCTSERIAL,
  N.CUSTOMERMGRCODE,
  N.TABELONG,
  N.FUNDTRADECODE,
  N.FUNDAPPSHEETSERIALNO,
  N.LARGEREDEMPFLAG,
  N.DISCOUNTRATE,
  N.SUCCESSFULAMOUNT,
  N.RETURNCHARGE,
  N.TARGETBRANCHCODE,
  N.NOTESENDFLAG,
  N.CHNLNO,
  N.CUSTOMERKIND,
  N.CONTRACTNO,
  N.CHULIFLAG,
  N.PSPFBATCHSERIAL,
  N.GREENORGAN,
  N.ORIGINALAPPDATE,
  N.TARGETTAACCOUNTID,
  N.HOSTDATE,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(TRADEDATE, '' ) AS TRADEDATE ,
  COALESCE(ORGANCODE, '' ) AS ORGANCODE ,
  COALESCE(OPERCODE, '' ) AS OPERCODE ,
  COALESCE(ACCTSERIAL, 0 ) AS ACCTSERIAL ,
  COALESCE(TRADETIME, '' ) AS TRADETIME ,
  COALESCE(AGENTCORPCODE, '' ) AS AGENTCORPCODE ,
  COALESCE(CREATEFLAG, '' ) AS CREATEFLAG ,
  COALESCE(CANCELFLAG, '' ) AS CANCELFLAG ,
  COALESCE(BUSINESSKINDCODE, '' ) AS BUSINESSKINDCODE ,
  COALESCE(TRADECODE, '' ) AS TRADECODE ,
  COALESCE(TAACCT, '' ) AS TAACCT ,
  COALESCE(CUSTOMERID, '' ) AS CUSTOMERID ,
  COALESCE(AFFIRMQUOTIENT, 0 ) AS AFFIRMQUOTIENT ,
  COALESCE(AFFIRMAMT, 0 ) AS AFFIRMAMT ,
  COALESCE(AFFIRMDATE, '' ) AS AFFIRMDATE ,
  COALESCE(BOOKINGFLAG, '' ) AS BOOKINGFLAG ,
  COALESCE(BOOKINGDATE, '' ) AS BOOKINGDATE ,
  COALESCE(SUCCESSFULQUOTIENT, 0 ) AS SUCCESSFULQUOTIENT ,
  COALESCE(QUOTIENTMODE, '' ) AS QUOTIENTMODE ,
  COALESCE(BONUSMODE, '' ) AS BONUSMODE ,
  COALESCE(CONTINUEFLAG, '' ) AS CONTINUEFLAG ,
  COALESCE(OTHERCUSTOMERID, '' ) AS OTHERCUSTOMERID ,
  COALESCE(OTHERORGANCODE, '' ) AS OTHERORGANCODE ,
  COALESCE(APPLYKIND, '' ) AS APPLYKIND ,
  COALESCE(CORPSERIAL, '' ) AS CORPSERIAL ,
  COALESCE(CORPRESPCODE, '' ) AS CORPRESPCODE ,
  COALESCE(CHARGEMODE, '' ) AS CHARGEMODE ,
  COALESCE(SALECODE, '' ) AS SALECODE ,
  COALESCE(AFFIRMFLAG, '' ) AS AFFIRMFLAG ,
  COALESCE(SENDFLAG, '' ) AS SENDFLAG ,
  COALESCE(SECONDKINDCODE, '' ) AS SECONDKINDCODE ,
  COALESCE(SECONDORGANCODE, '' ) AS SECONDORGANCODE ,
  COALESCE(STOPNO, '' ) AS STOPNO ,
  COALESCE(ORIACCTSERIAL, '' ) AS ORIACCTSERIAL ,
  COALESCE(CUSTOMERMGRCODE, '' ) AS CUSTOMERMGRCODE ,
  COALESCE(TABELONG, '' ) AS TABELONG ,
  COALESCE(FUNDTRADECODE, '' ) AS FUNDTRADECODE ,
  COALESCE(FUNDAPPSHEETSERIALNO, '' ) AS FUNDAPPSHEETSERIALNO ,
  COALESCE(LARGEREDEMPFLAG, '' ) AS LARGEREDEMPFLAG ,
  COALESCE(DISCOUNTRATE, 0 ) AS DISCOUNTRATE ,
  COALESCE(SUCCESSFULAMOUNT, 0 ) AS SUCCESSFULAMOUNT ,
  COALESCE(RETURNCHARGE, 0 ) AS RETURNCHARGE ,
  COALESCE(TARGETBRANCHCODE, '' ) AS TARGETBRANCHCODE ,
  COALESCE(NOTESENDFLAG, '' ) AS NOTESENDFLAG ,
  COALESCE(CHNLNO, '' ) AS CHNLNO ,
  COALESCE(CUSTOMERKIND, '' ) AS CUSTOMERKIND ,
  COALESCE(CONTRACTNO, '' ) AS CONTRACTNO ,
  COALESCE(CHULIFLAG, '' ) AS CHULIFLAG ,
  COALESCE(PSPFBATCHSERIAL, '' ) AS PSPFBATCHSERIAL ,
  COALESCE(GREENORGAN, '' ) AS GREENORGAN ,
  COALESCE(ORIGINALAPPDATE, '' ) AS ORIGINALAPPDATE ,
  COALESCE(TARGETTAACCOUNTID, '' ) AS TARGETTAACCOUNTID ,
  COALESCE(HOSTDATE, '' ) AS HOSTDATE 
 FROM  dw_tdata.FSS_001_FD_FUNDAFFIRM_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  TRADEDATE ,
  ORGANCODE ,
  OPERCODE ,
  ACCTSERIAL ,
  TRADETIME ,
  AGENTCORPCODE ,
  CREATEFLAG ,
  CANCELFLAG ,
  BUSINESSKINDCODE ,
  TRADECODE ,
  TAACCT ,
  CUSTOMERID ,
  AFFIRMQUOTIENT ,
  AFFIRMAMT ,
  AFFIRMDATE ,
  BOOKINGFLAG ,
  BOOKINGDATE ,
  SUCCESSFULQUOTIENT ,
  QUOTIENTMODE ,
  BONUSMODE ,
  CONTINUEFLAG ,
  OTHERCUSTOMERID ,
  OTHERORGANCODE ,
  APPLYKIND ,
  CORPSERIAL ,
  CORPRESPCODE ,
  CHARGEMODE ,
  SALECODE ,
  AFFIRMFLAG ,
  SENDFLAG ,
  SECONDKINDCODE ,
  SECONDORGANCODE ,
  STOPNO ,
  ORIACCTSERIAL ,
  CUSTOMERMGRCODE ,
  TABELONG ,
  FUNDTRADECODE ,
  FUNDAPPSHEETSERIALNO ,
  LARGEREDEMPFLAG ,
  DISCOUNTRATE ,
  SUCCESSFULAMOUNT ,
  RETURNCHARGE ,
  TARGETBRANCHCODE ,
  NOTESENDFLAG ,
  CHNLNO ,
  CUSTOMERKIND ,
  CONTRACTNO ,
  CHULIFLAG ,
  PSPFBATCHSERIAL ,
  GREENORGAN ,
  ORIGINALAPPDATE ,
  TARGETTAACCOUNTID ,
  HOSTDATE 
 FROM dw_sdata.FSS_001_FD_FUNDAFFIRM 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.TRADEDATE = T.TRADEDATE AND N.ORGANCODE = T.ORGANCODE AND N.OPERCODE = T.OPERCODE AND N.ACCTSERIAL = T.ACCTSERIAL
WHERE
(T.TRADEDATE IS NULL AND T.ORGANCODE IS NULL AND T.OPERCODE IS NULL AND T.ACCTSERIAL IS NULL)
 OR N.TRADETIME<>T.TRADETIME
 OR N.AGENTCORPCODE<>T.AGENTCORPCODE
 OR N.CREATEFLAG<>T.CREATEFLAG
 OR N.CANCELFLAG<>T.CANCELFLAG
 OR N.BUSINESSKINDCODE<>T.BUSINESSKINDCODE
 OR N.TRADECODE<>T.TRADECODE
 OR N.TAACCT<>T.TAACCT
 OR N.CUSTOMERID<>T.CUSTOMERID
 OR N.AFFIRMQUOTIENT<>T.AFFIRMQUOTIENT
 OR N.AFFIRMAMT<>T.AFFIRMAMT
 OR N.AFFIRMDATE<>T.AFFIRMDATE
 OR N.BOOKINGFLAG<>T.BOOKINGFLAG
 OR N.BOOKINGDATE<>T.BOOKINGDATE
 OR N.SUCCESSFULQUOTIENT<>T.SUCCESSFULQUOTIENT
 OR N.QUOTIENTMODE<>T.QUOTIENTMODE
 OR N.BONUSMODE<>T.BONUSMODE
 OR N.CONTINUEFLAG<>T.CONTINUEFLAG
 OR N.OTHERCUSTOMERID<>T.OTHERCUSTOMERID
 OR N.OTHERORGANCODE<>T.OTHERORGANCODE
 OR N.APPLYKIND<>T.APPLYKIND
 OR N.CORPSERIAL<>T.CORPSERIAL
 OR N.CORPRESPCODE<>T.CORPRESPCODE
 OR N.CHARGEMODE<>T.CHARGEMODE
 OR N.SALECODE<>T.SALECODE
 OR N.AFFIRMFLAG<>T.AFFIRMFLAG
 OR N.SENDFLAG<>T.SENDFLAG
 OR N.SECONDKINDCODE<>T.SECONDKINDCODE
 OR N.SECONDORGANCODE<>T.SECONDORGANCODE
 OR N.STOPNO<>T.STOPNO
 OR N.ORIACCTSERIAL<>T.ORIACCTSERIAL
 OR N.CUSTOMERMGRCODE<>T.CUSTOMERMGRCODE
 OR N.TABELONG<>T.TABELONG
 OR N.FUNDTRADECODE<>T.FUNDTRADECODE
 OR N.FUNDAPPSHEETSERIALNO<>T.FUNDAPPSHEETSERIALNO
 OR N.LARGEREDEMPFLAG<>T.LARGEREDEMPFLAG
 OR N.DISCOUNTRATE<>T.DISCOUNTRATE
 OR N.SUCCESSFULAMOUNT<>T.SUCCESSFULAMOUNT
 OR N.RETURNCHARGE<>T.RETURNCHARGE
 OR N.TARGETBRANCHCODE<>T.TARGETBRANCHCODE
 OR N.NOTESENDFLAG<>T.NOTESENDFLAG
 OR N.CHNLNO<>T.CHNLNO
 OR N.CUSTOMERKIND<>T.CUSTOMERKIND
 OR N.CONTRACTNO<>T.CONTRACTNO
 OR N.CHULIFLAG<>T.CHULIFLAG
 OR N.PSPFBATCHSERIAL<>T.PSPFBATCHSERIAL
 OR N.GREENORGAN<>T.GREENORGAN
 OR N.ORIGINALAPPDATE<>T.ORIGINALAPPDATE
 OR N.TARGETTAACCOUNTID<>T.TARGETTAACCOUNTID
 OR N.HOSTDATE<>T.HOSTDATE
;

--Step3:
UPDATE dw_sdata.FSS_001_FD_FUNDAFFIRM P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_193
WHERE P.End_Dt=DATE('2100-12-31')
AND P.TRADEDATE=T_193.TRADEDATE
AND P.ORGANCODE=T_193.ORGANCODE
AND P.OPERCODE=T_193.OPERCODE
AND P.ACCTSERIAL=T_193.ACCTSERIAL
;

--Step4:
INSERT  INTO dw_sdata.FSS_001_FD_FUNDAFFIRM SELECT * FROM T_193;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
