#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ISS_001_IM_LGISSUEINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ISS_001_IM_LGISSUEINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_243 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ISS_001_IM_LGISSUEINFO WHERE 1=0;

--Step2:
INSERT  INTO T_243 (
  LGNO,
  TXNSERIALNO,
  LGTYPE,
  ISAGENTLG,
  AGENTBKNO,
  AGENTBKSWFCODE,
  AGENTBKNAMEADDR,
  AGENTLGNO,
  SENDBKNO,
  SENDBKSWFCODE,
  SENDBKNAMEADDR,
  RECIVEBKNO,
  RECIVEBKSWFCODE,
  RECIVEBKNAMEADDR,
  APPNO,
  APPNAMEADDR,
  BENEFNAME,
  LGCURSIGN,
  LGAMT,
  CONTRACTNO,
  ISSUEDATE,
  MATURITYDATE,
  MATURITYFLAG,
  COMMODITY,
  QUANTITY,
  ABTIMES,
  ABAMT,
  PAYMENTAMT,
  AMENDTIMES,
  AMENDDATE,
  BEFORECURSIGN,
  BEFOREAMT,
  VARFLAG,
  VARAMT,
  ADVBKREF,
  DEPSERIALNOS,
  CURRDEPSERIALNOS,
  ISSENDSWIFT,
  ISRETIRE,
  ISCANCEL,
  FURTHERID,
  CONTRACTAMT,
  APPCNNAME,
  CHARGEUNDERTAKER,
  COUNTRYCODE,
  DEPOSITAMT,
  DEPOSITPCT,
  INOUTFLAG,
  BENEFNO,
  ADVBANKSWIFTCODE,
  ADVBANKNAMEADDR,
  ISBACKLC,
  OPPPARTYCLASS,
  AMENDEDCUR,
  ADVBKNO,
  BENEFNAMEADDR,
  APPCODE,
  ISSENDMT700,
  ISSENDMT799,
  PARTIALSHIPMENT,
  TRANSSHIPMENT,
  LOADPORTNAME,
  TRANSPORTNAME,
  LATESTSHIPDATE,
  SHIPMENTPERIOD,
  DEPARTPORT,
  DESTINPORT,
  PRESENTPERIOD,
  CHARGES,
  POSTSCRIPT,
  INSTRUCTION,
  ISSENDMT707,
  DRAFTDAYS,
  TENORTYPE,
  DRAFTDAYSDESCR,
  LCACCEPTAMT,
  APPCODEOTHER,
  ISSENDMT769,
  SENDSWFTYPE,
  ISSUEMODE,
  DEPOSITNO,
  DEPOSITCURSIGN,
  LGAMTTOLERDOWN,
  LGAMTTOLERUP,
  EXPIRYPLACE,
  EXPIRYDATE,
  CREDITINFORMNO,
  ISLG,
  LGISSUEINORNOT,
  start_dt,
  end_dt)
SELECT
  N.LGNO,
  N.TXNSERIALNO,
  N.LGTYPE,
  N.ISAGENTLG,
  N.AGENTBKNO,
  N.AGENTBKSWFCODE,
  N.AGENTBKNAMEADDR,
  N.AGENTLGNO,
  N.SENDBKNO,
  N.SENDBKSWFCODE,
  N.SENDBKNAMEADDR,
  N.RECIVEBKNO,
  N.RECIVEBKSWFCODE,
  N.RECIVEBKNAMEADDR,
  N.APPNO,
  N.APPNAMEADDR,
  N.BENEFNAME,
  N.LGCURSIGN,
  N.LGAMT,
  N.CONTRACTNO,
  N.ISSUEDATE,
  N.MATURITYDATE,
  N.MATURITYFLAG,
  N.COMMODITY,
  N.QUANTITY,
  N.ABTIMES,
  N.ABAMT,
  N.PAYMENTAMT,
  N.AMENDTIMES,
  N.AMENDDATE,
  N.BEFORECURSIGN,
  N.BEFOREAMT,
  N.VARFLAG,
  N.VARAMT,
  N.ADVBKREF,
  N.DEPSERIALNOS,
  N.CURRDEPSERIALNOS,
  N.ISSENDSWIFT,
  N.ISRETIRE,
  N.ISCANCEL,
  N.FURTHERID,
  N.CONTRACTAMT,
  N.APPCNNAME,
  N.CHARGEUNDERTAKER,
  N.COUNTRYCODE,
  N.DEPOSITAMT,
  N.DEPOSITPCT,
  N.INOUTFLAG,
  N.BENEFNO,
  N.ADVBANKSWIFTCODE,
  N.ADVBANKNAMEADDR,
  N.ISBACKLC,
  N.OPPPARTYCLASS,
  N.AMENDEDCUR,
  N.ADVBKNO,
  N.BENEFNAMEADDR,
  N.APPCODE,
  N.ISSENDMT700,
  N.ISSENDMT799,
  N.PARTIALSHIPMENT,
  N.TRANSSHIPMENT,
  N.LOADPORTNAME,
  N.TRANSPORTNAME,
  N.LATESTSHIPDATE,
  N.SHIPMENTPERIOD,
  N.DEPARTPORT,
  N.DESTINPORT,
  N.PRESENTPERIOD,
  N.CHARGES,
  N.POSTSCRIPT,
  N.INSTRUCTION,
  N.ISSENDMT707,
  N.DRAFTDAYS,
  N.TENORTYPE,
  N.DRAFTDAYSDESCR,
  N.LCACCEPTAMT,
  N.APPCODEOTHER,
  N.ISSENDMT769,
  N.SENDSWFTYPE,
  N.ISSUEMODE,
  N.DEPOSITNO,
  N.DEPOSITCURSIGN,
  N.LGAMTTOLERDOWN,
  N.LGAMTTOLERUP,
  N.EXPIRYPLACE,
  N.EXPIRYDATE,
  N.CREDITINFORMNO,
  N.ISLG,
  N.LGISSUEINORNOT,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(LGNO, '' ) AS LGNO ,
  COALESCE(TXNSERIALNO, '' ) AS TXNSERIALNO ,
  COALESCE(LGTYPE, 0 ) AS LGTYPE ,
  COALESCE(ISAGENTLG, '' ) AS ISAGENTLG ,
  COALESCE(AGENTBKNO, '' ) AS AGENTBKNO ,
  COALESCE(AGENTBKSWFCODE, '' ) AS AGENTBKSWFCODE ,
  COALESCE(AGENTBKNAMEADDR, '' ) AS AGENTBKNAMEADDR ,
  COALESCE(AGENTLGNO, '' ) AS AGENTLGNO ,
  COALESCE(SENDBKNO, '' ) AS SENDBKNO ,
  COALESCE(SENDBKSWFCODE, '' ) AS SENDBKSWFCODE ,
  COALESCE(SENDBKNAMEADDR, '' ) AS SENDBKNAMEADDR ,
  COALESCE(RECIVEBKNO, '' ) AS RECIVEBKNO ,
  COALESCE(RECIVEBKSWFCODE, '' ) AS RECIVEBKSWFCODE ,
  COALESCE(RECIVEBKNAMEADDR, '' ) AS RECIVEBKNAMEADDR ,
  COALESCE(APPNO, '' ) AS APPNO ,
  COALESCE(APPNAMEADDR, '' ) AS APPNAMEADDR ,
  COALESCE(BENEFNAME, '' ) AS BENEFNAME ,
  COALESCE(LGCURSIGN, '' ) AS LGCURSIGN ,
  COALESCE(LGAMT, 0 ) AS LGAMT ,
  COALESCE(CONTRACTNO, '' ) AS CONTRACTNO ,
  COALESCE(ISSUEDATE,DATE('4999-12-31') ) AS ISSUEDATE ,
  COALESCE(MATURITYDATE,DATE('4999-12-31') ) AS MATURITYDATE ,
  COALESCE(MATURITYFLAG, '' ) AS MATURITYFLAG ,
  COALESCE(COMMODITY, '' ) AS COMMODITY ,
  COALESCE(QUANTITY, '' ) AS QUANTITY ,
  COALESCE(ABTIMES, 0 ) AS ABTIMES ,
  COALESCE(ABAMT, 0 ) AS ABAMT ,
  COALESCE(PAYMENTAMT, 0 ) AS PAYMENTAMT ,
  COALESCE(AMENDTIMES, 0 ) AS AMENDTIMES ,
  COALESCE(AMENDDATE,DATE('4999-12-31') ) AS AMENDDATE ,
  COALESCE(BEFORECURSIGN, '' ) AS BEFORECURSIGN ,
  COALESCE(BEFOREAMT, 0 ) AS BEFOREAMT ,
  COALESCE(VARFLAG, '' ) AS VARFLAG ,
  COALESCE(VARAMT, 0 ) AS VARAMT ,
  COALESCE(ADVBKREF, '' ) AS ADVBKREF ,
  COALESCE(DEPSERIALNOS, '' ) AS DEPSERIALNOS ,
  COALESCE(CURRDEPSERIALNOS, '' ) AS CURRDEPSERIALNOS ,
  COALESCE(ISSENDSWIFT, '' ) AS ISSENDSWIFT ,
  COALESCE(ISRETIRE, '' ) AS ISRETIRE ,
  COALESCE(ISCANCEL, '' ) AS ISCANCEL ,
  COALESCE(FURTHERID, '' ) AS FURTHERID ,
  COALESCE(CONTRACTAMT, 0 ) AS CONTRACTAMT ,
  COALESCE(APPCNNAME, '' ) AS APPCNNAME ,
  COALESCE(CHARGEUNDERTAKER, '' ) AS CHARGEUNDERTAKER ,
  COALESCE(COUNTRYCODE, '' ) AS COUNTRYCODE ,
  COALESCE(DEPOSITAMT, 0 ) AS DEPOSITAMT ,
  COALESCE(DEPOSITPCT, '' ) AS DEPOSITPCT ,
  COALESCE(INOUTFLAG, '' ) AS INOUTFLAG ,
  COALESCE(BENEFNO, '' ) AS BENEFNO ,
  COALESCE(ADVBANKSWIFTCODE, '' ) AS ADVBANKSWIFTCODE ,
  COALESCE(ADVBANKNAMEADDR, '' ) AS ADVBANKNAMEADDR ,
  COALESCE(ISBACKLC, '' ) AS ISBACKLC ,
  COALESCE(OPPPARTYCLASS, '' ) AS OPPPARTYCLASS ,
  COALESCE(AMENDEDCUR, '' ) AS AMENDEDCUR ,
  COALESCE(ADVBKNO, '' ) AS ADVBKNO ,
  COALESCE(BENEFNAMEADDR, '' ) AS BENEFNAMEADDR ,
  COALESCE(APPCODE, '' ) AS APPCODE ,
  COALESCE(ISSENDMT700, '' ) AS ISSENDMT700 ,
  COALESCE(ISSENDMT799, '' ) AS ISSENDMT799 ,
  COALESCE(PARTIALSHIPMENT, '' ) AS PARTIALSHIPMENT ,
  COALESCE(TRANSSHIPMENT, '' ) AS TRANSSHIPMENT ,
  COALESCE(LOADPORTNAME, '' ) AS LOADPORTNAME ,
  COALESCE(TRANSPORTNAME, '' ) AS TRANSPORTNAME ,
  COALESCE(LATESTSHIPDATE,DATE('4999-12-31') ) AS LATESTSHIPDATE ,
  COALESCE(SHIPMENTPERIOD, '' ) AS SHIPMENTPERIOD ,
  COALESCE(DEPARTPORT, '' ) AS DEPARTPORT ,
  COALESCE(DESTINPORT, '' ) AS DESTINPORT ,
  COALESCE(PRESENTPERIOD, '' ) AS PRESENTPERIOD ,
  COALESCE(CHARGES, '' ) AS CHARGES ,
  COALESCE(POSTSCRIPT, '' ) AS POSTSCRIPT ,
  COALESCE(INSTRUCTION, '' ) AS INSTRUCTION ,
  COALESCE(ISSENDMT707, '' ) AS ISSENDMT707 ,
  COALESCE(DRAFTDAYS, 0 ) AS DRAFTDAYS ,
  COALESCE(TENORTYPE, '' ) AS TENORTYPE ,
  COALESCE(DRAFTDAYSDESCR, '' ) AS DRAFTDAYSDESCR ,
  COALESCE(LCACCEPTAMT, 0 ) AS LCACCEPTAMT ,
  COALESCE(APPCODEOTHER, '' ) AS APPCODEOTHER ,
  COALESCE(ISSENDMT769, '' ) AS ISSENDMT769 ,
  COALESCE(SENDSWFTYPE, '' ) AS SENDSWFTYPE ,
  COALESCE(ISSUEMODE, '' ) AS ISSUEMODE ,
  COALESCE(DEPOSITNO, '' ) AS DEPOSITNO ,
  COALESCE(DEPOSITCURSIGN, '' ) AS DEPOSITCURSIGN ,
  COALESCE(LGAMTTOLERDOWN, 0 ) AS LGAMTTOLERDOWN ,
  COALESCE(LGAMTTOLERUP, 0 ) AS LGAMTTOLERUP ,
  COALESCE(EXPIRYPLACE, '' ) AS EXPIRYPLACE ,
  COALESCE(EXPIRYDATE,DATE('4999-12-31') ) AS EXPIRYDATE ,
  COALESCE(CREDITINFORMNO, '' ) AS CREDITINFORMNO ,
  COALESCE(ISLG, '' ) AS ISLG ,
  COALESCE(LGISSUEINORNOT, '' ) AS LGISSUEINORNOT 
 FROM  dw_tdata.ISS_001_IM_LGISSUEINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  LGNO ,
  TXNSERIALNO ,
  LGTYPE ,
  ISAGENTLG ,
  AGENTBKNO ,
  AGENTBKSWFCODE ,
  AGENTBKNAMEADDR ,
  AGENTLGNO ,
  SENDBKNO ,
  SENDBKSWFCODE ,
  SENDBKNAMEADDR ,
  RECIVEBKNO ,
  RECIVEBKSWFCODE ,
  RECIVEBKNAMEADDR ,
  APPNO ,
  APPNAMEADDR ,
  BENEFNAME ,
  LGCURSIGN ,
  LGAMT ,
  CONTRACTNO ,
  ISSUEDATE ,
  MATURITYDATE ,
  MATURITYFLAG ,
  COMMODITY ,
  QUANTITY ,
  ABTIMES ,
  ABAMT ,
  PAYMENTAMT ,
  AMENDTIMES ,
  AMENDDATE ,
  BEFORECURSIGN ,
  BEFOREAMT ,
  VARFLAG ,
  VARAMT ,
  ADVBKREF ,
  DEPSERIALNOS ,
  CURRDEPSERIALNOS ,
  ISSENDSWIFT ,
  ISRETIRE ,
  ISCANCEL ,
  FURTHERID ,
  CONTRACTAMT ,
  APPCNNAME ,
  CHARGEUNDERTAKER ,
  COUNTRYCODE ,
  DEPOSITAMT ,
  DEPOSITPCT ,
  INOUTFLAG ,
  BENEFNO ,
  ADVBANKSWIFTCODE ,
  ADVBANKNAMEADDR ,
  ISBACKLC ,
  OPPPARTYCLASS ,
  AMENDEDCUR ,
  ADVBKNO ,
  BENEFNAMEADDR ,
  APPCODE ,
  ISSENDMT700 ,
  ISSENDMT799 ,
  PARTIALSHIPMENT ,
  TRANSSHIPMENT ,
  LOADPORTNAME ,
  TRANSPORTNAME ,
  LATESTSHIPDATE ,
  SHIPMENTPERIOD ,
  DEPARTPORT ,
  DESTINPORT ,
  PRESENTPERIOD ,
  CHARGES ,
  POSTSCRIPT ,
  INSTRUCTION ,
  ISSENDMT707 ,
  DRAFTDAYS ,
  TENORTYPE ,
  DRAFTDAYSDESCR ,
  LCACCEPTAMT ,
  APPCODEOTHER ,
  ISSENDMT769 ,
  SENDSWFTYPE ,
  ISSUEMODE ,
  DEPOSITNO ,
  DEPOSITCURSIGN ,
  LGAMTTOLERDOWN ,
  LGAMTTOLERUP ,
  EXPIRYPLACE ,
  EXPIRYDATE ,
  CREDITINFORMNO ,
  ISLG ,
  LGISSUEINORNOT 
 FROM dw_sdata.ISS_001_IM_LGISSUEINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.LGNO = T.LGNO
WHERE
(T.LGNO IS NULL)
 OR N.TXNSERIALNO<>T.TXNSERIALNO
 OR N.LGTYPE<>T.LGTYPE
 OR N.ISAGENTLG<>T.ISAGENTLG
 OR N.AGENTBKNO<>T.AGENTBKNO
 OR N.AGENTBKSWFCODE<>T.AGENTBKSWFCODE
 OR N.AGENTBKNAMEADDR<>T.AGENTBKNAMEADDR
 OR N.AGENTLGNO<>T.AGENTLGNO
 OR N.SENDBKNO<>T.SENDBKNO
 OR N.SENDBKSWFCODE<>T.SENDBKSWFCODE
 OR N.SENDBKNAMEADDR<>T.SENDBKNAMEADDR
 OR N.RECIVEBKNO<>T.RECIVEBKNO
 OR N.RECIVEBKSWFCODE<>T.RECIVEBKSWFCODE
 OR N.RECIVEBKNAMEADDR<>T.RECIVEBKNAMEADDR
 OR N.APPNO<>T.APPNO
 OR N.APPNAMEADDR<>T.APPNAMEADDR
 OR N.BENEFNAME<>T.BENEFNAME
 OR N.LGCURSIGN<>T.LGCURSIGN
 OR N.LGAMT<>T.LGAMT
 OR N.CONTRACTNO<>T.CONTRACTNO
 OR N.ISSUEDATE<>T.ISSUEDATE
 OR N.MATURITYDATE<>T.MATURITYDATE
 OR N.MATURITYFLAG<>T.MATURITYFLAG
 OR N.COMMODITY<>T.COMMODITY
 OR N.QUANTITY<>T.QUANTITY
 OR N.ABTIMES<>T.ABTIMES
 OR N.ABAMT<>T.ABAMT
 OR N.PAYMENTAMT<>T.PAYMENTAMT
 OR N.AMENDTIMES<>T.AMENDTIMES
 OR N.AMENDDATE<>T.AMENDDATE
 OR N.BEFORECURSIGN<>T.BEFORECURSIGN
 OR N.BEFOREAMT<>T.BEFOREAMT
 OR N.VARFLAG<>T.VARFLAG
 OR N.VARAMT<>T.VARAMT
 OR N.ADVBKREF<>T.ADVBKREF
 OR N.DEPSERIALNOS<>T.DEPSERIALNOS
 OR N.CURRDEPSERIALNOS<>T.CURRDEPSERIALNOS
 OR N.ISSENDSWIFT<>T.ISSENDSWIFT
 OR N.ISRETIRE<>T.ISRETIRE
 OR N.ISCANCEL<>T.ISCANCEL
 OR N.FURTHERID<>T.FURTHERID
 OR N.CONTRACTAMT<>T.CONTRACTAMT
 OR N.APPCNNAME<>T.APPCNNAME
 OR N.CHARGEUNDERTAKER<>T.CHARGEUNDERTAKER
 OR N.COUNTRYCODE<>T.COUNTRYCODE
 OR N.DEPOSITAMT<>T.DEPOSITAMT
 OR N.DEPOSITPCT<>T.DEPOSITPCT
 OR N.INOUTFLAG<>T.INOUTFLAG
 OR N.BENEFNO<>T.BENEFNO
 OR N.ADVBANKSWIFTCODE<>T.ADVBANKSWIFTCODE
 OR N.ADVBANKNAMEADDR<>T.ADVBANKNAMEADDR
 OR N.ISBACKLC<>T.ISBACKLC
 OR N.OPPPARTYCLASS<>T.OPPPARTYCLASS
 OR N.AMENDEDCUR<>T.AMENDEDCUR
 OR N.ADVBKNO<>T.ADVBKNO
 OR N.BENEFNAMEADDR<>T.BENEFNAMEADDR
 OR N.APPCODE<>T.APPCODE
 OR N.ISSENDMT700<>T.ISSENDMT700
 OR N.ISSENDMT799<>T.ISSENDMT799
 OR N.PARTIALSHIPMENT<>T.PARTIALSHIPMENT
 OR N.TRANSSHIPMENT<>T.TRANSSHIPMENT
 OR N.LOADPORTNAME<>T.LOADPORTNAME
 OR N.TRANSPORTNAME<>T.TRANSPORTNAME
 OR N.LATESTSHIPDATE<>T.LATESTSHIPDATE
 OR N.SHIPMENTPERIOD<>T.SHIPMENTPERIOD
 OR N.DEPARTPORT<>T.DEPARTPORT
 OR N.DESTINPORT<>T.DESTINPORT
 OR N.PRESENTPERIOD<>T.PRESENTPERIOD
 OR N.CHARGES<>T.CHARGES
 OR N.POSTSCRIPT<>T.POSTSCRIPT
 OR N.INSTRUCTION<>T.INSTRUCTION
 OR N.ISSENDMT707<>T.ISSENDMT707
 OR N.DRAFTDAYS<>T.DRAFTDAYS
 OR N.TENORTYPE<>T.TENORTYPE
 OR N.DRAFTDAYSDESCR<>T.DRAFTDAYSDESCR
 OR N.LCACCEPTAMT<>T.LCACCEPTAMT
 OR N.APPCODEOTHER<>T.APPCODEOTHER
 OR N.ISSENDMT769<>T.ISSENDMT769
 OR N.SENDSWFTYPE<>T.SENDSWFTYPE
 OR N.ISSUEMODE<>T.ISSUEMODE
 OR N.DEPOSITNO<>T.DEPOSITNO
 OR N.DEPOSITCURSIGN<>T.DEPOSITCURSIGN
 OR N.LGAMTTOLERDOWN<>T.LGAMTTOLERDOWN
 OR N.LGAMTTOLERUP<>T.LGAMTTOLERUP
 OR N.EXPIRYPLACE<>T.EXPIRYPLACE
 OR N.EXPIRYDATE<>T.EXPIRYDATE
 OR N.CREDITINFORMNO<>T.CREDITINFORMNO
 OR N.ISLG<>T.ISLG
 OR N.LGISSUEINORNOT<>T.LGISSUEINORNOT
;

--Step3:
UPDATE dw_sdata.ISS_001_IM_LGISSUEINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_243
WHERE P.End_Dt=DATE('2100-12-31')
AND P.LGNO=T_243.LGNO
;

--Step4:
INSERT  INTO dw_sdata.ISS_001_IM_LGISSUEINFO SELECT * FROM T_243;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
