#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ISS_001_IM_LCISSUEINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ISS_001_IM_LCISSUEINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_241 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ISS_001_IM_LCISSUEINFO WHERE 1=0;

--Step2:
INSERT  INTO T_241 (
  LCNO,
  PREADVLCNO,
  TXNSERIALNO,
  ISAGENTLC,
  AGENTBANKNO,
  AGENTBANKSWIFTCODE,
  AGENTBANKNAMEADDR,
  AGENTLCNO,
  AMENDTIMES,
  ABTIMES,
  TRADENO,
  ISVALID,
  SENDBANKNO,
  SENDBANKSWIFTCODE,
  SENDBANKNAMEADDR,
  RECVBANKNO,
  RECVBANKSWIFTCODE,
  RECVBANKNAMEADDR,
  APPBANKNO,
  APPBANKSWIFTCODE,
  APPBANKNAMEADDR,
  APPNO,
  APPNAMEADDR,
  CLIENTNO,
  CLIENTNAMEADDR,
  ADVBANKNO,
  ADVBANKSWIFTCODE,
  ADVBANKNAMEADDR,
  REIMBBANKNO,
  REIMBBANKSWIFTCODE,
  REIMBBANKNAMEADDR,
  REIMBBANKACCTNO,
  REIMBCLAUSE,
  LCCURSIGN,
  LCAMT,
  LCVARAMT,
  LCMAXAMTREPRESENT,
  LCMAXAMT,
  LCADDIAMT,
  LCNOTPAYAMT,
  LCABAMT,
  LCACCEPTAMT,
  LCAMTTOLERDOWN,
  LCAMTTOLERUP,
  LCFORM,
  DRAFTDAYS,
  TENORTYPE,
  DRAFTDAYSDESCR,
  DRAFTINVPCT,
  DRAWEENO,
  DRAWEESWIFTCODE,
  DRAWEENAMEADDR,
  BENEFNO,
  BENEFNAMEADDR,
  LCISSUINGDATE,
  PARTIALSHIPMENT,
  TRANSSHIPMENT,
  EXPIRYPLACE,
  EXPIRYDATE,
  LOADPORTNAME,
  TRANSPORTNAME,
  LATESTSHIPDATE,
  COUNTRYCODE,
  PRESENTPERIOD,
  CONFIRMINSTRUCTION,
  ISSUEMODE,
  ISFREENEGO,
  AVAILBANKPRESENT,
  LCAVAILTYPE,
  NEGOBANKNO,
  NEGOBANKSWIFTCODE,
  NEGOBANKNAMEADDR,
  ISMIXEDPAY,
  MIXEDPAYDETAILS,
  DEFERPAYDETAILS,
  SHIPMENTPERIOD,
  CHARGES,
  INSTRUCTION,
  POSTSCRIPT,
  ISDEPOSIT,
  ISLIMIT,
  ISMT700,
  ISMT740,
  ISCLOSE,
  ISWITHDRAW,
  SPECIALLCTYPE,
  DEPSERIALNOS,
  PARENTTXNSERIALNO,
  CHARGEUNDERTAKER,
  APPCNNAME,
  DEPOSITAMT,
  DEPOSITPCT,
  APPRULES,
  DEPARTPORT,
  DESTINPORT,
  APPCODE,
  ISAGENTSWIFT,
  AGENTSWIFT,
  BENEFNAME,
  OPPPARTYCLASS,
  INOUTFLAG,
  ISCIVILLC,
  REIMBBANKCOUNTRY,
  DEPCURSIGN,
  QUOTAANDGAGEID,
  QUOTAANDGAGECUR,
  QUOTAANDGAGEAMT,
  DEPOSITNO,
  ISDAIKAILC,
  OPENAPPBANKNO,
  OPENAPPBANKSWIFTCODE,
  OPENAPPBANKNAMEADDR,
  OPENAPPLCNO,
  OPENAPPNAMEADDR,
  ISZHUANKAILC,
  start_dt,
  end_dt)
SELECT
  N.LCNO,
  N.PREADVLCNO,
  N.TXNSERIALNO,
  N.ISAGENTLC,
  N.AGENTBANKNO,
  N.AGENTBANKSWIFTCODE,
  N.AGENTBANKNAMEADDR,
  N.AGENTLCNO,
  N.AMENDTIMES,
  N.ABTIMES,
  N.TRADENO,
  N.ISVALID,
  N.SENDBANKNO,
  N.SENDBANKSWIFTCODE,
  N.SENDBANKNAMEADDR,
  N.RECVBANKNO,
  N.RECVBANKSWIFTCODE,
  N.RECVBANKNAMEADDR,
  N.APPBANKNO,
  N.APPBANKSWIFTCODE,
  N.APPBANKNAMEADDR,
  N.APPNO,
  N.APPNAMEADDR,
  N.CLIENTNO,
  N.CLIENTNAMEADDR,
  N.ADVBANKNO,
  N.ADVBANKSWIFTCODE,
  N.ADVBANKNAMEADDR,
  N.REIMBBANKNO,
  N.REIMBBANKSWIFTCODE,
  N.REIMBBANKNAMEADDR,
  N.REIMBBANKACCTNO,
  N.REIMBCLAUSE,
  N.LCCURSIGN,
  N.LCAMT,
  N.LCVARAMT,
  N.LCMAXAMTREPRESENT,
  N.LCMAXAMT,
  N.LCADDIAMT,
  N.LCNOTPAYAMT,
  N.LCABAMT,
  N.LCACCEPTAMT,
  N.LCAMTTOLERDOWN,
  N.LCAMTTOLERUP,
  N.LCFORM,
  N.DRAFTDAYS,
  N.TENORTYPE,
  N.DRAFTDAYSDESCR,
  N.DRAFTINVPCT,
  N.DRAWEENO,
  N.DRAWEESWIFTCODE,
  N.DRAWEENAMEADDR,
  N.BENEFNO,
  N.BENEFNAMEADDR,
  N.LCISSUINGDATE,
  N.PARTIALSHIPMENT,
  N.TRANSSHIPMENT,
  N.EXPIRYPLACE,
  N.EXPIRYDATE,
  N.LOADPORTNAME,
  N.TRANSPORTNAME,
  N.LATESTSHIPDATE,
  N.COUNTRYCODE,
  N.PRESENTPERIOD,
  N.CONFIRMINSTRUCTION,
  N.ISSUEMODE,
  N.ISFREENEGO,
  N.AVAILBANKPRESENT,
  N.LCAVAILTYPE,
  N.NEGOBANKNO,
  N.NEGOBANKSWIFTCODE,
  N.NEGOBANKNAMEADDR,
  N.ISMIXEDPAY,
  N.MIXEDPAYDETAILS,
  N.DEFERPAYDETAILS,
  N.SHIPMENTPERIOD,
  N.CHARGES,
  N.INSTRUCTION,
  N.POSTSCRIPT,
  N.ISDEPOSIT,
  N.ISLIMIT,
  N.ISMT700,
  N.ISMT740,
  N.ISCLOSE,
  N.ISWITHDRAW,
  N.SPECIALLCTYPE,
  N.DEPSERIALNOS,
  N.PARENTTXNSERIALNO,
  N.CHARGEUNDERTAKER,
  N.APPCNNAME,
  N.DEPOSITAMT,
  N.DEPOSITPCT,
  N.APPRULES,
  N.DEPARTPORT,
  N.DESTINPORT,
  N.APPCODE,
  N.ISAGENTSWIFT,
  N.AGENTSWIFT,
  N.BENEFNAME,
  N.OPPPARTYCLASS,
  N.INOUTFLAG,
  N.ISCIVILLC,
  N.REIMBBANKCOUNTRY,
  N.DEPCURSIGN,
  N.QUOTAANDGAGEID,
  N.QUOTAANDGAGECUR,
  N.QUOTAANDGAGEAMT,
  N.DEPOSITNO,
  N.ISDAIKAILC,
  N.OPENAPPBANKNO,
  N.OPENAPPBANKSWIFTCODE,
  N.OPENAPPBANKNAMEADDR,
  N.OPENAPPLCNO,
  N.OPENAPPNAMEADDR,
  N.ISZHUANKAILC,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(LCNO, '' ) AS LCNO ,
  COALESCE(PREADVLCNO, '' ) AS PREADVLCNO ,
  COALESCE(TXNSERIALNO, '' ) AS TXNSERIALNO ,
  COALESCE(ISAGENTLC, '' ) AS ISAGENTLC ,
  COALESCE(AGENTBANKNO, '' ) AS AGENTBANKNO ,
  COALESCE(AGENTBANKSWIFTCODE, '' ) AS AGENTBANKSWIFTCODE ,
  COALESCE(AGENTBANKNAMEADDR, '' ) AS AGENTBANKNAMEADDR ,
  COALESCE(AGENTLCNO, '' ) AS AGENTLCNO ,
  COALESCE(AMENDTIMES, 0 ) AS AMENDTIMES ,
  COALESCE(ABTIMES, 0 ) AS ABTIMES ,
  COALESCE(TRADENO, '' ) AS TRADENO ,
  COALESCE(ISVALID, '' ) AS ISVALID ,
  COALESCE(SENDBANKNO, '' ) AS SENDBANKNO ,
  COALESCE(SENDBANKSWIFTCODE, '' ) AS SENDBANKSWIFTCODE ,
  COALESCE(SENDBANKNAMEADDR, '' ) AS SENDBANKNAMEADDR ,
  COALESCE(RECVBANKNO, '' ) AS RECVBANKNO ,
  COALESCE(RECVBANKSWIFTCODE, '' ) AS RECVBANKSWIFTCODE ,
  COALESCE(RECVBANKNAMEADDR, '' ) AS RECVBANKNAMEADDR ,
  COALESCE(APPBANKNO, '' ) AS APPBANKNO ,
  COALESCE(APPBANKSWIFTCODE, '' ) AS APPBANKSWIFTCODE ,
  COALESCE(APPBANKNAMEADDR, '' ) AS APPBANKNAMEADDR ,
  COALESCE(APPNO, '' ) AS APPNO ,
  COALESCE(APPNAMEADDR, '' ) AS APPNAMEADDR ,
  COALESCE(CLIENTNO, '' ) AS CLIENTNO ,
  COALESCE(CLIENTNAMEADDR, '' ) AS CLIENTNAMEADDR ,
  COALESCE(ADVBANKNO, '' ) AS ADVBANKNO ,
  COALESCE(ADVBANKSWIFTCODE, '' ) AS ADVBANKSWIFTCODE ,
  COALESCE(ADVBANKNAMEADDR, '' ) AS ADVBANKNAMEADDR ,
  COALESCE(REIMBBANKNO, '' ) AS REIMBBANKNO ,
  COALESCE(REIMBBANKSWIFTCODE, '' ) AS REIMBBANKSWIFTCODE ,
  COALESCE(REIMBBANKNAMEADDR, '' ) AS REIMBBANKNAMEADDR ,
  COALESCE(REIMBBANKACCTNO, '' ) AS REIMBBANKACCTNO ,
  COALESCE(REIMBCLAUSE, '' ) AS REIMBCLAUSE ,
  COALESCE(LCCURSIGN, '' ) AS LCCURSIGN ,
  COALESCE(LCAMT, 0 ) AS LCAMT ,
  COALESCE(LCVARAMT, 0 ) AS LCVARAMT ,
  COALESCE(LCMAXAMTREPRESENT, '' ) AS LCMAXAMTREPRESENT ,
  COALESCE(LCMAXAMT, 0 ) AS LCMAXAMT ,
  COALESCE(LCADDIAMT, '' ) AS LCADDIAMT ,
  COALESCE(LCNOTPAYAMT, 0 ) AS LCNOTPAYAMT ,
  COALESCE(LCABAMT, 0 ) AS LCABAMT ,
  COALESCE(LCACCEPTAMT, 0 ) AS LCACCEPTAMT ,
  COALESCE(LCAMTTOLERDOWN, 0 ) AS LCAMTTOLERDOWN ,
  COALESCE(LCAMTTOLERUP, 0 ) AS LCAMTTOLERUP ,
  COALESCE(LCFORM, '' ) AS LCFORM ,
  COALESCE(DRAFTDAYS, 0 ) AS DRAFTDAYS ,
  COALESCE(TENORTYPE, '' ) AS TENORTYPE ,
  COALESCE(DRAFTDAYSDESCR, '' ) AS DRAFTDAYSDESCR ,
  COALESCE(DRAFTINVPCT, '' ) AS DRAFTINVPCT ,
  COALESCE(DRAWEENO, '' ) AS DRAWEENO ,
  COALESCE(DRAWEESWIFTCODE, '' ) AS DRAWEESWIFTCODE ,
  COALESCE(DRAWEENAMEADDR, '' ) AS DRAWEENAMEADDR ,
  COALESCE(BENEFNO, '' ) AS BENEFNO ,
  COALESCE(BENEFNAMEADDR, '' ) AS BENEFNAMEADDR ,
  COALESCE(LCISSUINGDATE,DATE('4999-12-31') ) AS LCISSUINGDATE ,
  COALESCE(PARTIALSHIPMENT, '' ) AS PARTIALSHIPMENT ,
  COALESCE(TRANSSHIPMENT, '' ) AS TRANSSHIPMENT ,
  COALESCE(EXPIRYPLACE, '' ) AS EXPIRYPLACE ,
  COALESCE(EXPIRYDATE,DATE('4999-12-31') ) AS EXPIRYDATE ,
  COALESCE(LOADPORTNAME, '' ) AS LOADPORTNAME ,
  COALESCE(TRANSPORTNAME, '' ) AS TRANSPORTNAME ,
  COALESCE(LATESTSHIPDATE,DATE('4999-12-31') ) AS LATESTSHIPDATE ,
  COALESCE(COUNTRYCODE, '' ) AS COUNTRYCODE ,
  COALESCE(PRESENTPERIOD, '' ) AS PRESENTPERIOD ,
  COALESCE(CONFIRMINSTRUCTION, '' ) AS CONFIRMINSTRUCTION ,
  COALESCE(ISSUEMODE, '' ) AS ISSUEMODE ,
  COALESCE(ISFREENEGO, '' ) AS ISFREENEGO ,
  COALESCE(AVAILBANKPRESENT, '' ) AS AVAILBANKPRESENT ,
  COALESCE(LCAVAILTYPE, '' ) AS LCAVAILTYPE ,
  COALESCE(NEGOBANKNO, '' ) AS NEGOBANKNO ,
  COALESCE(NEGOBANKSWIFTCODE, '' ) AS NEGOBANKSWIFTCODE ,
  COALESCE(NEGOBANKNAMEADDR, '' ) AS NEGOBANKNAMEADDR ,
  COALESCE(ISMIXEDPAY, '' ) AS ISMIXEDPAY ,
  COALESCE(MIXEDPAYDETAILS, '' ) AS MIXEDPAYDETAILS ,
  COALESCE(DEFERPAYDETAILS, '' ) AS DEFERPAYDETAILS ,
  COALESCE(SHIPMENTPERIOD, '' ) AS SHIPMENTPERIOD ,
  COALESCE(CHARGES, '' ) AS CHARGES ,
  COALESCE(INSTRUCTION, '' ) AS INSTRUCTION ,
  COALESCE(POSTSCRIPT, '' ) AS POSTSCRIPT ,
  COALESCE(ISDEPOSIT, '' ) AS ISDEPOSIT ,
  COALESCE(ISLIMIT, '' ) AS ISLIMIT ,
  COALESCE(ISMT700, '' ) AS ISMT700 ,
  COALESCE(ISMT740, '' ) AS ISMT740 ,
  COALESCE(ISCLOSE, '' ) AS ISCLOSE ,
  COALESCE(ISWITHDRAW, '' ) AS ISWITHDRAW ,
  COALESCE(SPECIALLCTYPE, '' ) AS SPECIALLCTYPE ,
  COALESCE(DEPSERIALNOS, '' ) AS DEPSERIALNOS ,
  COALESCE(PARENTTXNSERIALNO, '' ) AS PARENTTXNSERIALNO ,
  COALESCE(CHARGEUNDERTAKER, '' ) AS CHARGEUNDERTAKER ,
  COALESCE(APPCNNAME, '' ) AS APPCNNAME ,
  COALESCE(DEPOSITAMT, 0 ) AS DEPOSITAMT ,
  COALESCE(DEPOSITPCT, '' ) AS DEPOSITPCT ,
  COALESCE(APPRULES, '' ) AS APPRULES ,
  COALESCE(DEPARTPORT, '' ) AS DEPARTPORT ,
  COALESCE(DESTINPORT, '' ) AS DESTINPORT ,
  COALESCE(APPCODE, '' ) AS APPCODE ,
  COALESCE(ISAGENTSWIFT, '' ) AS ISAGENTSWIFT ,
  COALESCE(AGENTSWIFT, '' ) AS AGENTSWIFT ,
  COALESCE(BENEFNAME, '' ) AS BENEFNAME ,
  COALESCE(OPPPARTYCLASS, '' ) AS OPPPARTYCLASS ,
  COALESCE(INOUTFLAG, '' ) AS INOUTFLAG ,
  COALESCE(ISCIVILLC, '' ) AS ISCIVILLC ,
  COALESCE(REIMBBANKCOUNTRY, '' ) AS REIMBBANKCOUNTRY ,
  COALESCE(DEPCURSIGN, '' ) AS DEPCURSIGN ,
  COALESCE(QUOTAANDGAGEID, '' ) AS QUOTAANDGAGEID ,
  COALESCE(QUOTAANDGAGECUR, '' ) AS QUOTAANDGAGECUR ,
  COALESCE(QUOTAANDGAGEAMT, 0 ) AS QUOTAANDGAGEAMT ,
  COALESCE(DEPOSITNO, '' ) AS DEPOSITNO ,
  COALESCE(ISDAIKAILC, '' ) AS ISDAIKAILC ,
  COALESCE(OPENAPPBANKNO, '' ) AS OPENAPPBANKNO ,
  COALESCE(OPENAPPBANKSWIFTCODE, '' ) AS OPENAPPBANKSWIFTCODE ,
  COALESCE(OPENAPPBANKNAMEADDR, '' ) AS OPENAPPBANKNAMEADDR ,
  COALESCE(OPENAPPLCNO, '' ) AS OPENAPPLCNO ,
  COALESCE(OPENAPPNAMEADDR, '' ) AS OPENAPPNAMEADDR ,
  COALESCE(ISZHUANKAILC, '' ) AS ISZHUANKAILC 
 FROM  dw_tdata.ISS_001_IM_LCISSUEINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  LCNO ,
  PREADVLCNO ,
  TXNSERIALNO ,
  ISAGENTLC ,
  AGENTBANKNO ,
  AGENTBANKSWIFTCODE ,
  AGENTBANKNAMEADDR ,
  AGENTLCNO ,
  AMENDTIMES ,
  ABTIMES ,
  TRADENO ,
  ISVALID ,
  SENDBANKNO ,
  SENDBANKSWIFTCODE ,
  SENDBANKNAMEADDR ,
  RECVBANKNO ,
  RECVBANKSWIFTCODE ,
  RECVBANKNAMEADDR ,
  APPBANKNO ,
  APPBANKSWIFTCODE ,
  APPBANKNAMEADDR ,
  APPNO ,
  APPNAMEADDR ,
  CLIENTNO ,
  CLIENTNAMEADDR ,
  ADVBANKNO ,
  ADVBANKSWIFTCODE ,
  ADVBANKNAMEADDR ,
  REIMBBANKNO ,
  REIMBBANKSWIFTCODE ,
  REIMBBANKNAMEADDR ,
  REIMBBANKACCTNO ,
  REIMBCLAUSE ,
  LCCURSIGN ,
  LCAMT ,
  LCVARAMT ,
  LCMAXAMTREPRESENT ,
  LCMAXAMT ,
  LCADDIAMT ,
  LCNOTPAYAMT ,
  LCABAMT ,
  LCACCEPTAMT ,
  LCAMTTOLERDOWN ,
  LCAMTTOLERUP ,
  LCFORM ,
  DRAFTDAYS ,
  TENORTYPE ,
  DRAFTDAYSDESCR ,
  DRAFTINVPCT ,
  DRAWEENO ,
  DRAWEESWIFTCODE ,
  DRAWEENAMEADDR ,
  BENEFNO ,
  BENEFNAMEADDR ,
  LCISSUINGDATE ,
  PARTIALSHIPMENT ,
  TRANSSHIPMENT ,
  EXPIRYPLACE ,
  EXPIRYDATE ,
  LOADPORTNAME ,
  TRANSPORTNAME ,
  LATESTSHIPDATE ,
  COUNTRYCODE ,
  PRESENTPERIOD ,
  CONFIRMINSTRUCTION ,
  ISSUEMODE ,
  ISFREENEGO ,
  AVAILBANKPRESENT ,
  LCAVAILTYPE ,
  NEGOBANKNO ,
  NEGOBANKSWIFTCODE ,
  NEGOBANKNAMEADDR ,
  ISMIXEDPAY ,
  MIXEDPAYDETAILS ,
  DEFERPAYDETAILS ,
  SHIPMENTPERIOD ,
  CHARGES ,
  INSTRUCTION ,
  POSTSCRIPT ,
  ISDEPOSIT ,
  ISLIMIT ,
  ISMT700 ,
  ISMT740 ,
  ISCLOSE ,
  ISWITHDRAW ,
  SPECIALLCTYPE ,
  DEPSERIALNOS ,
  PARENTTXNSERIALNO ,
  CHARGEUNDERTAKER ,
  APPCNNAME ,
  DEPOSITAMT ,
  DEPOSITPCT ,
  APPRULES ,
  DEPARTPORT ,
  DESTINPORT ,
  APPCODE ,
  ISAGENTSWIFT ,
  AGENTSWIFT ,
  BENEFNAME ,
  OPPPARTYCLASS ,
  INOUTFLAG ,
  ISCIVILLC ,
  REIMBBANKCOUNTRY ,
  DEPCURSIGN ,
  QUOTAANDGAGEID ,
  QUOTAANDGAGECUR ,
  QUOTAANDGAGEAMT ,
  DEPOSITNO ,
  ISDAIKAILC ,
  OPENAPPBANKNO ,
  OPENAPPBANKSWIFTCODE ,
  OPENAPPBANKNAMEADDR ,
  OPENAPPLCNO ,
  OPENAPPNAMEADDR ,
  ISZHUANKAILC 
 FROM dw_sdata.ISS_001_IM_LCISSUEINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.LCNO = T.LCNO
WHERE
(T.LCNO IS NULL)
 OR N.PREADVLCNO<>T.PREADVLCNO
 OR N.TXNSERIALNO<>T.TXNSERIALNO
 OR N.ISAGENTLC<>T.ISAGENTLC
 OR N.AGENTBANKNO<>T.AGENTBANKNO
 OR N.AGENTBANKSWIFTCODE<>T.AGENTBANKSWIFTCODE
 OR N.AGENTBANKNAMEADDR<>T.AGENTBANKNAMEADDR
 OR N.AGENTLCNO<>T.AGENTLCNO
 OR N.AMENDTIMES<>T.AMENDTIMES
 OR N.ABTIMES<>T.ABTIMES
 OR N.TRADENO<>T.TRADENO
 OR N.ISVALID<>T.ISVALID
 OR N.SENDBANKNO<>T.SENDBANKNO
 OR N.SENDBANKSWIFTCODE<>T.SENDBANKSWIFTCODE
 OR N.SENDBANKNAMEADDR<>T.SENDBANKNAMEADDR
 OR N.RECVBANKNO<>T.RECVBANKNO
 OR N.RECVBANKSWIFTCODE<>T.RECVBANKSWIFTCODE
 OR N.RECVBANKNAMEADDR<>T.RECVBANKNAMEADDR
 OR N.APPBANKNO<>T.APPBANKNO
 OR N.APPBANKSWIFTCODE<>T.APPBANKSWIFTCODE
 OR N.APPBANKNAMEADDR<>T.APPBANKNAMEADDR
 OR N.APPNO<>T.APPNO
 OR N.APPNAMEADDR<>T.APPNAMEADDR
 OR N.CLIENTNO<>T.CLIENTNO
 OR N.CLIENTNAMEADDR<>T.CLIENTNAMEADDR
 OR N.ADVBANKNO<>T.ADVBANKNO
 OR N.ADVBANKSWIFTCODE<>T.ADVBANKSWIFTCODE
 OR N.ADVBANKNAMEADDR<>T.ADVBANKNAMEADDR
 OR N.REIMBBANKNO<>T.REIMBBANKNO
 OR N.REIMBBANKSWIFTCODE<>T.REIMBBANKSWIFTCODE
 OR N.REIMBBANKNAMEADDR<>T.REIMBBANKNAMEADDR
 OR N.REIMBBANKACCTNO<>T.REIMBBANKACCTNO
 OR N.REIMBCLAUSE<>T.REIMBCLAUSE
 OR N.LCCURSIGN<>T.LCCURSIGN
 OR N.LCAMT<>T.LCAMT
 OR N.LCVARAMT<>T.LCVARAMT
 OR N.LCMAXAMTREPRESENT<>T.LCMAXAMTREPRESENT
 OR N.LCMAXAMT<>T.LCMAXAMT
 OR N.LCADDIAMT<>T.LCADDIAMT
 OR N.LCNOTPAYAMT<>T.LCNOTPAYAMT
 OR N.LCABAMT<>T.LCABAMT
 OR N.LCACCEPTAMT<>T.LCACCEPTAMT
 OR N.LCAMTTOLERDOWN<>T.LCAMTTOLERDOWN
 OR N.LCAMTTOLERUP<>T.LCAMTTOLERUP
 OR N.LCFORM<>T.LCFORM
 OR N.DRAFTDAYS<>T.DRAFTDAYS
 OR N.TENORTYPE<>T.TENORTYPE
 OR N.DRAFTDAYSDESCR<>T.DRAFTDAYSDESCR
 OR N.DRAFTINVPCT<>T.DRAFTINVPCT
 OR N.DRAWEENO<>T.DRAWEENO
 OR N.DRAWEESWIFTCODE<>T.DRAWEESWIFTCODE
 OR N.DRAWEENAMEADDR<>T.DRAWEENAMEADDR
 OR N.BENEFNO<>T.BENEFNO
 OR N.BENEFNAMEADDR<>T.BENEFNAMEADDR
 OR N.LCISSUINGDATE<>T.LCISSUINGDATE
 OR N.PARTIALSHIPMENT<>T.PARTIALSHIPMENT
 OR N.TRANSSHIPMENT<>T.TRANSSHIPMENT
 OR N.EXPIRYPLACE<>T.EXPIRYPLACE
 OR N.EXPIRYDATE<>T.EXPIRYDATE
 OR N.LOADPORTNAME<>T.LOADPORTNAME
 OR N.TRANSPORTNAME<>T.TRANSPORTNAME
 OR N.LATESTSHIPDATE<>T.LATESTSHIPDATE
 OR N.COUNTRYCODE<>T.COUNTRYCODE
 OR N.PRESENTPERIOD<>T.PRESENTPERIOD
 OR N.CONFIRMINSTRUCTION<>T.CONFIRMINSTRUCTION
 OR N.ISSUEMODE<>T.ISSUEMODE
 OR N.ISFREENEGO<>T.ISFREENEGO
 OR N.AVAILBANKPRESENT<>T.AVAILBANKPRESENT
 OR N.LCAVAILTYPE<>T.LCAVAILTYPE
 OR N.NEGOBANKNO<>T.NEGOBANKNO
 OR N.NEGOBANKSWIFTCODE<>T.NEGOBANKSWIFTCODE
 OR N.NEGOBANKNAMEADDR<>T.NEGOBANKNAMEADDR
 OR N.ISMIXEDPAY<>T.ISMIXEDPAY
 OR N.MIXEDPAYDETAILS<>T.MIXEDPAYDETAILS
 OR N.DEFERPAYDETAILS<>T.DEFERPAYDETAILS
 OR N.SHIPMENTPERIOD<>T.SHIPMENTPERIOD
 OR N.CHARGES<>T.CHARGES
 OR N.INSTRUCTION<>T.INSTRUCTION
 OR N.POSTSCRIPT<>T.POSTSCRIPT
 OR N.ISDEPOSIT<>T.ISDEPOSIT
 OR N.ISLIMIT<>T.ISLIMIT
 OR N.ISMT700<>T.ISMT700
 OR N.ISMT740<>T.ISMT740
 OR N.ISCLOSE<>T.ISCLOSE
 OR N.ISWITHDRAW<>T.ISWITHDRAW
 OR N.SPECIALLCTYPE<>T.SPECIALLCTYPE
 OR N.DEPSERIALNOS<>T.DEPSERIALNOS
 OR N.PARENTTXNSERIALNO<>T.PARENTTXNSERIALNO
 OR N.CHARGEUNDERTAKER<>T.CHARGEUNDERTAKER
 OR N.APPCNNAME<>T.APPCNNAME
 OR N.DEPOSITAMT<>T.DEPOSITAMT
 OR N.DEPOSITPCT<>T.DEPOSITPCT
 OR N.APPRULES<>T.APPRULES
 OR N.DEPARTPORT<>T.DEPARTPORT
 OR N.DESTINPORT<>T.DESTINPORT
 OR N.APPCODE<>T.APPCODE
 OR N.ISAGENTSWIFT<>T.ISAGENTSWIFT
 OR N.AGENTSWIFT<>T.AGENTSWIFT
 OR N.BENEFNAME<>T.BENEFNAME
 OR N.OPPPARTYCLASS<>T.OPPPARTYCLASS
 OR N.INOUTFLAG<>T.INOUTFLAG
 OR N.ISCIVILLC<>T.ISCIVILLC
 OR N.REIMBBANKCOUNTRY<>T.REIMBBANKCOUNTRY
 OR N.DEPCURSIGN<>T.DEPCURSIGN
 OR N.QUOTAANDGAGEID<>T.QUOTAANDGAGEID
 OR N.QUOTAANDGAGECUR<>T.QUOTAANDGAGECUR
 OR N.QUOTAANDGAGEAMT<>T.QUOTAANDGAGEAMT
 OR N.DEPOSITNO<>T.DEPOSITNO
 OR N.ISDAIKAILC<>T.ISDAIKAILC
 OR N.OPENAPPBANKNO<>T.OPENAPPBANKNO
 OR N.OPENAPPBANKSWIFTCODE<>T.OPENAPPBANKSWIFTCODE
 OR N.OPENAPPBANKNAMEADDR<>T.OPENAPPBANKNAMEADDR
 OR N.OPENAPPLCNO<>T.OPENAPPLCNO
 OR N.OPENAPPNAMEADDR<>T.OPENAPPNAMEADDR
 OR N.ISZHUANKAILC<>T.ISZHUANKAILC
;

--Step3:
UPDATE dw_sdata.ISS_001_IM_LCISSUEINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_241
WHERE P.End_Dt=DATE('2100-12-31')
AND P.LCNO=T_241.LCNO
;

--Step4:
INSERT  INTO dw_sdata.ISS_001_IM_LCISSUEINFO SELECT * FROM T_241;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
