#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ISS_001_EX_DOCCOLLINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ISS_001_EX_DOCCOLLINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_235 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ISS_001_EX_DOCCOLLINFO WHERE 1=0;

--Step2:
INSERT  INTO T_235 (
  TXNSERIALNO,
  BIZNO,
  OLDTXNSERIALNO,
  ISAGENT,
  AGENTBANKNO,
  AGENTBANKNAME,
  COLLECTINGBANKNO,
  COLLECTINGBANKNAME,
  COLLECTINGSWFCODE,
  DRAWERNO,
  DRAWERNAME,
  COLLTYPE,
  COLTYPE,
  COLSUBTYPE,
  MIXEDDESCR,
  DRAFTCUR,
  DRAFTAMT,
  DRAFTDAYSTYPE,
  DRAFTDAYS,
  DRAFTDAYSDESCR,
  SUFLAG,
  LESSPLUSFLAG,
  LESSPLUSAMT,
  LESSPLUSDESCR,
  COMMISSIONTYPE,
  COMMISSIONPERCENT,
  COMMISSIONAMT,
  SUMAMT,
  MAILTYPE,
  ISSECONDMAILBILL,
  MAILBANK1STMAIL,
  MAILBANK2STMAIL,
  DRAWEENO,
  DRAWEENAME,
  COUNTRYCODE,
  NOSTROBANKNO,
  NOSTROBANKNAME,
  NOSTROBANKSWFCODE,
  NOSTROACCTNO,
  PRESENTBANKNO,
  PRESENTBANKNAME,
  PRESENTBANKSWFCODE,
  COLLDATE,
  MAILDATE,
  BLDATE,
  BEGINDATE,
  MATURITY,
  PAYMENTDATE,
  REIMBURSEMENTTYPE,
  INVOICENO,
  CHECKNO,
  INSTRTOCOLLBANK,
  PAYINSTRUCTION,
  MODIFYFLAG,
  MODIFYAMT,
  MODIFYTYPE,
  OLDCUR,
  OLDAMT,
  CHARGEBY,
  CHARGE,
  CHARGEDESCR,
  OPFLAG,
  ISSENDSWF,
  WAIVECHG,
  ADVICENO,
  REMARK,
  MAILCODE1,
  MAILCODE2,
  ISAGENTSWIFT,
  AGENTSWIFT,
  INVOICEDATE,
  OPPPARTYCLASS,
  OPPNAME,
  LASTSHIPDATE,
  SWIFTTYPE,
  PROCEEDSDEGREE,
  LESSPLUSFLAGMODIFY,
  LESSPLUSAMTMODIFY,
  MAILTIME,
  start_dt,
  end_dt)
SELECT
  N.TXNSERIALNO,
  N.BIZNO,
  N.OLDTXNSERIALNO,
  N.ISAGENT,
  N.AGENTBANKNO,
  N.AGENTBANKNAME,
  N.COLLECTINGBANKNO,
  N.COLLECTINGBANKNAME,
  N.COLLECTINGSWFCODE,
  N.DRAWERNO,
  N.DRAWERNAME,
  N.COLLTYPE,
  N.COLTYPE,
  N.COLSUBTYPE,
  N.MIXEDDESCR,
  N.DRAFTCUR,
  N.DRAFTAMT,
  N.DRAFTDAYSTYPE,
  N.DRAFTDAYS,
  N.DRAFTDAYSDESCR,
  N.SUFLAG,
  N.LESSPLUSFLAG,
  N.LESSPLUSAMT,
  N.LESSPLUSDESCR,
  N.COMMISSIONTYPE,
  N.COMMISSIONPERCENT,
  N.COMMISSIONAMT,
  N.SUMAMT,
  N.MAILTYPE,
  N.ISSECONDMAILBILL,
  N.MAILBANK1STMAIL,
  N.MAILBANK2STMAIL,
  N.DRAWEENO,
  N.DRAWEENAME,
  N.COUNTRYCODE,
  N.NOSTROBANKNO,
  N.NOSTROBANKNAME,
  N.NOSTROBANKSWFCODE,
  N.NOSTROACCTNO,
  N.PRESENTBANKNO,
  N.PRESENTBANKNAME,
  N.PRESENTBANKSWFCODE,
  N.COLLDATE,
  N.MAILDATE,
  N.BLDATE,
  N.BEGINDATE,
  N.MATURITY,
  N.PAYMENTDATE,
  N.REIMBURSEMENTTYPE,
  N.INVOICENO,
  N.CHECKNO,
  N.INSTRTOCOLLBANK,
  N.PAYINSTRUCTION,
  N.MODIFYFLAG,
  N.MODIFYAMT,
  N.MODIFYTYPE,
  N.OLDCUR,
  N.OLDAMT,
  N.CHARGEBY,
  N.CHARGE,
  N.CHARGEDESCR,
  N.OPFLAG,
  N.ISSENDSWF,
  N.WAIVECHG,
  N.ADVICENO,
  N.REMARK,
  N.MAILCODE1,
  N.MAILCODE2,
  N.ISAGENTSWIFT,
  N.AGENTSWIFT,
  N.INVOICEDATE,
  N.OPPPARTYCLASS,
  N.OPPNAME,
  N.LASTSHIPDATE,
  N.SWIFTTYPE,
  N.PROCEEDSDEGREE,
  N.LESSPLUSFLAGMODIFY,
  N.LESSPLUSAMTMODIFY,
  N.MAILTIME,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(TXNSERIALNO, '' ) AS TXNSERIALNO ,
  COALESCE(BIZNO, '' ) AS BIZNO ,
  COALESCE(OLDTXNSERIALNO, '' ) AS OLDTXNSERIALNO ,
  COALESCE(ISAGENT, '' ) AS ISAGENT ,
  COALESCE(AGENTBANKNO, '' ) AS AGENTBANKNO ,
  COALESCE(AGENTBANKNAME, '' ) AS AGENTBANKNAME ,
  COALESCE(COLLECTINGBANKNO, '' ) AS COLLECTINGBANKNO ,
  COALESCE(COLLECTINGBANKNAME, '' ) AS COLLECTINGBANKNAME ,
  COALESCE(COLLECTINGSWFCODE, '' ) AS COLLECTINGSWFCODE ,
  COALESCE(DRAWERNO, '' ) AS DRAWERNO ,
  COALESCE(DRAWERNAME, '' ) AS DRAWERNAME ,
  COALESCE(COLLTYPE, '' ) AS COLLTYPE ,
  COALESCE(COLTYPE, '' ) AS COLTYPE ,
  COALESCE(COLSUBTYPE, '' ) AS COLSUBTYPE ,
  COALESCE(MIXEDDESCR, '' ) AS MIXEDDESCR ,
  COALESCE(DRAFTCUR, '' ) AS DRAFTCUR ,
  COALESCE(DRAFTAMT, 0 ) AS DRAFTAMT ,
  COALESCE(DRAFTDAYSTYPE, '' ) AS DRAFTDAYSTYPE ,
  COALESCE(DRAFTDAYS, 0 ) AS DRAFTDAYS ,
  COALESCE(DRAFTDAYSDESCR, '' ) AS DRAFTDAYSDESCR ,
  COALESCE(SUFLAG, '' ) AS SUFLAG ,
  COALESCE(LESSPLUSFLAG, '' ) AS LESSPLUSFLAG ,
  COALESCE(LESSPLUSAMT, 0 ) AS LESSPLUSAMT ,
  COALESCE(LESSPLUSDESCR, '' ) AS LESSPLUSDESCR ,
  COALESCE(COMMISSIONTYPE, '' ) AS COMMISSIONTYPE ,
  COALESCE(COMMISSIONPERCENT, 0 ) AS COMMISSIONPERCENT ,
  COALESCE(COMMISSIONAMT, 0 ) AS COMMISSIONAMT ,
  COALESCE(SUMAMT, 0 ) AS SUMAMT ,
  COALESCE(MAILTYPE, '' ) AS MAILTYPE ,
  COALESCE(ISSECONDMAILBILL, '' ) AS ISSECONDMAILBILL ,
  COALESCE(MAILBANK1STMAIL, '' ) AS MAILBANK1STMAIL ,
  COALESCE(MAILBANK2STMAIL, '' ) AS MAILBANK2STMAIL ,
  COALESCE(DRAWEENO, '' ) AS DRAWEENO ,
  COALESCE(DRAWEENAME, '' ) AS DRAWEENAME ,
  COALESCE(COUNTRYCODE, '' ) AS COUNTRYCODE ,
  COALESCE(NOSTROBANKNO, '' ) AS NOSTROBANKNO ,
  COALESCE(NOSTROBANKNAME, '' ) AS NOSTROBANKNAME ,
  COALESCE(NOSTROBANKSWFCODE, '' ) AS NOSTROBANKSWFCODE ,
  COALESCE(NOSTROACCTNO, '' ) AS NOSTROACCTNO ,
  COALESCE(PRESENTBANKNO, '' ) AS PRESENTBANKNO ,
  COALESCE(PRESENTBANKNAME, '' ) AS PRESENTBANKNAME ,
  COALESCE(PRESENTBANKSWFCODE, '' ) AS PRESENTBANKSWFCODE ,
  COALESCE(COLLDATE,DATE('4999-12-31') ) AS COLLDATE ,
  COALESCE(MAILDATE,DATE('4999-12-31') ) AS MAILDATE ,
  COALESCE(BLDATE,DATE('4999-12-31') ) AS BLDATE ,
  COALESCE(BEGINDATE,DATE('4999-12-31') ) AS BEGINDATE ,
  COALESCE(MATURITY,DATE('4999-12-31') ) AS MATURITY ,
  COALESCE(PAYMENTDATE,DATE('4999-12-31') ) AS PAYMENTDATE ,
  COALESCE(REIMBURSEMENTTYPE, '' ) AS REIMBURSEMENTTYPE ,
  COALESCE(INVOICENO, '' ) AS INVOICENO ,
  COALESCE(CHECKNO, '' ) AS CHECKNO ,
  COALESCE(INSTRTOCOLLBANK, '' ) AS INSTRTOCOLLBANK ,
  COALESCE(PAYINSTRUCTION, '' ) AS PAYINSTRUCTION ,
  COALESCE(MODIFYFLAG, '' ) AS MODIFYFLAG ,
  COALESCE(MODIFYAMT, 0 ) AS MODIFYAMT ,
  COALESCE(MODIFYTYPE, '' ) AS MODIFYTYPE ,
  COALESCE(OLDCUR, '' ) AS OLDCUR ,
  COALESCE(OLDAMT, 0 ) AS OLDAMT ,
  COALESCE(CHARGEBY, '' ) AS CHARGEBY ,
  COALESCE(CHARGE, 0 ) AS CHARGE ,
  COALESCE(CHARGEDESCR, '' ) AS CHARGEDESCR ,
  COALESCE(OPFLAG, '' ) AS OPFLAG ,
  COALESCE(ISSENDSWF, '' ) AS ISSENDSWF ,
  COALESCE(WAIVECHG, '' ) AS WAIVECHG ,
  COALESCE(ADVICENO, '' ) AS ADVICENO ,
  COALESCE(REMARK, '' ) AS REMARK ,
  COALESCE(MAILCODE1, '' ) AS MAILCODE1 ,
  COALESCE(MAILCODE2, '' ) AS MAILCODE2 ,
  COALESCE(ISAGENTSWIFT, '' ) AS ISAGENTSWIFT ,
  COALESCE(AGENTSWIFT, '' ) AS AGENTSWIFT ,
  COALESCE(INVOICEDATE,DATE('4999-12-31') ) AS INVOICEDATE ,
  COALESCE(OPPPARTYCLASS, '' ) AS OPPPARTYCLASS ,
  COALESCE(OPPNAME, '' ) AS OPPNAME ,
  COALESCE(LASTSHIPDATE,DATE('4999-12-31') ) AS LASTSHIPDATE ,
  COALESCE(SWIFTTYPE, '' ) AS SWIFTTYPE ,
  COALESCE(PROCEEDSDEGREE, '' ) AS PROCEEDSDEGREE ,
  COALESCE(LESSPLUSFLAGMODIFY, '' ) AS LESSPLUSFLAGMODIFY ,
  COALESCE(LESSPLUSAMTMODIFY, 0 ) AS LESSPLUSAMTMODIFY ,
  COALESCE(MAILTIME, 0 ) AS MAILTIME 
 FROM  dw_tdata.ISS_001_EX_DOCCOLLINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  TXNSERIALNO ,
  BIZNO ,
  OLDTXNSERIALNO ,
  ISAGENT ,
  AGENTBANKNO ,
  AGENTBANKNAME ,
  COLLECTINGBANKNO ,
  COLLECTINGBANKNAME ,
  COLLECTINGSWFCODE ,
  DRAWERNO ,
  DRAWERNAME ,
  COLLTYPE ,
  COLTYPE ,
  COLSUBTYPE ,
  MIXEDDESCR ,
  DRAFTCUR ,
  DRAFTAMT ,
  DRAFTDAYSTYPE ,
  DRAFTDAYS ,
  DRAFTDAYSDESCR ,
  SUFLAG ,
  LESSPLUSFLAG ,
  LESSPLUSAMT ,
  LESSPLUSDESCR ,
  COMMISSIONTYPE ,
  COMMISSIONPERCENT ,
  COMMISSIONAMT ,
  SUMAMT ,
  MAILTYPE ,
  ISSECONDMAILBILL ,
  MAILBANK1STMAIL ,
  MAILBANK2STMAIL ,
  DRAWEENO ,
  DRAWEENAME ,
  COUNTRYCODE ,
  NOSTROBANKNO ,
  NOSTROBANKNAME ,
  NOSTROBANKSWFCODE ,
  NOSTROACCTNO ,
  PRESENTBANKNO ,
  PRESENTBANKNAME ,
  PRESENTBANKSWFCODE ,
  COLLDATE ,
  MAILDATE ,
  BLDATE ,
  BEGINDATE ,
  MATURITY ,
  PAYMENTDATE ,
  REIMBURSEMENTTYPE ,
  INVOICENO ,
  CHECKNO ,
  INSTRTOCOLLBANK ,
  PAYINSTRUCTION ,
  MODIFYFLAG ,
  MODIFYAMT ,
  MODIFYTYPE ,
  OLDCUR ,
  OLDAMT ,
  CHARGEBY ,
  CHARGE ,
  CHARGEDESCR ,
  OPFLAG ,
  ISSENDSWF ,
  WAIVECHG ,
  ADVICENO ,
  REMARK ,
  MAILCODE1 ,
  MAILCODE2 ,
  ISAGENTSWIFT ,
  AGENTSWIFT ,
  INVOICEDATE ,
  OPPPARTYCLASS ,
  OPPNAME ,
  LASTSHIPDATE ,
  SWIFTTYPE ,
  PROCEEDSDEGREE ,
  LESSPLUSFLAGMODIFY ,
  LESSPLUSAMTMODIFY ,
  MAILTIME 
 FROM dw_sdata.ISS_001_EX_DOCCOLLINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.BIZNO = T.BIZNO
WHERE
(T.BIZNO IS NULL)
 OR N.TXNSERIALNO<>T.TXNSERIALNO
 OR N.OLDTXNSERIALNO<>T.OLDTXNSERIALNO
 OR N.ISAGENT<>T.ISAGENT
 OR N.AGENTBANKNO<>T.AGENTBANKNO
 OR N.AGENTBANKNAME<>T.AGENTBANKNAME
 OR N.COLLECTINGBANKNO<>T.COLLECTINGBANKNO
 OR N.COLLECTINGBANKNAME<>T.COLLECTINGBANKNAME
 OR N.COLLECTINGSWFCODE<>T.COLLECTINGSWFCODE
 OR N.DRAWERNO<>T.DRAWERNO
 OR N.DRAWERNAME<>T.DRAWERNAME
 OR N.COLLTYPE<>T.COLLTYPE
 OR N.COLTYPE<>T.COLTYPE
 OR N.COLSUBTYPE<>T.COLSUBTYPE
 OR N.MIXEDDESCR<>T.MIXEDDESCR
 OR N.DRAFTCUR<>T.DRAFTCUR
 OR N.DRAFTAMT<>T.DRAFTAMT
 OR N.DRAFTDAYSTYPE<>T.DRAFTDAYSTYPE
 OR N.DRAFTDAYS<>T.DRAFTDAYS
 OR N.DRAFTDAYSDESCR<>T.DRAFTDAYSDESCR
 OR N.SUFLAG<>T.SUFLAG
 OR N.LESSPLUSFLAG<>T.LESSPLUSFLAG
 OR N.LESSPLUSAMT<>T.LESSPLUSAMT
 OR N.LESSPLUSDESCR<>T.LESSPLUSDESCR
 OR N.COMMISSIONTYPE<>T.COMMISSIONTYPE
 OR N.COMMISSIONPERCENT<>T.COMMISSIONPERCENT
 OR N.COMMISSIONAMT<>T.COMMISSIONAMT
 OR N.SUMAMT<>T.SUMAMT
 OR N.MAILTYPE<>T.MAILTYPE
 OR N.ISSECONDMAILBILL<>T.ISSECONDMAILBILL
 OR N.MAILBANK1STMAIL<>T.MAILBANK1STMAIL
 OR N.MAILBANK2STMAIL<>T.MAILBANK2STMAIL
 OR N.DRAWEENO<>T.DRAWEENO
 OR N.DRAWEENAME<>T.DRAWEENAME
 OR N.COUNTRYCODE<>T.COUNTRYCODE
 OR N.NOSTROBANKNO<>T.NOSTROBANKNO
 OR N.NOSTROBANKNAME<>T.NOSTROBANKNAME
 OR N.NOSTROBANKSWFCODE<>T.NOSTROBANKSWFCODE
 OR N.NOSTROACCTNO<>T.NOSTROACCTNO
 OR N.PRESENTBANKNO<>T.PRESENTBANKNO
 OR N.PRESENTBANKNAME<>T.PRESENTBANKNAME
 OR N.PRESENTBANKSWFCODE<>T.PRESENTBANKSWFCODE
 OR N.COLLDATE<>T.COLLDATE
 OR N.MAILDATE<>T.MAILDATE
 OR N.BLDATE<>T.BLDATE
 OR N.BEGINDATE<>T.BEGINDATE
 OR N.MATURITY<>T.MATURITY
 OR N.PAYMENTDATE<>T.PAYMENTDATE
 OR N.REIMBURSEMENTTYPE<>T.REIMBURSEMENTTYPE
 OR N.INVOICENO<>T.INVOICENO
 OR N.CHECKNO<>T.CHECKNO
 OR N.INSTRTOCOLLBANK<>T.INSTRTOCOLLBANK
 OR N.PAYINSTRUCTION<>T.PAYINSTRUCTION
 OR N.MODIFYFLAG<>T.MODIFYFLAG
 OR N.MODIFYAMT<>T.MODIFYAMT
 OR N.MODIFYTYPE<>T.MODIFYTYPE
 OR N.OLDCUR<>T.OLDCUR
 OR N.OLDAMT<>T.OLDAMT
 OR N.CHARGEBY<>T.CHARGEBY
 OR N.CHARGE<>T.CHARGE
 OR N.CHARGEDESCR<>T.CHARGEDESCR
 OR N.OPFLAG<>T.OPFLAG
 OR N.ISSENDSWF<>T.ISSENDSWF
 OR N.WAIVECHG<>T.WAIVECHG
 OR N.ADVICENO<>T.ADVICENO
 OR N.REMARK<>T.REMARK
 OR N.MAILCODE1<>T.MAILCODE1
 OR N.MAILCODE2<>T.MAILCODE2
 OR N.ISAGENTSWIFT<>T.ISAGENTSWIFT
 OR N.AGENTSWIFT<>T.AGENTSWIFT
 OR N.INVOICEDATE<>T.INVOICEDATE
 OR N.OPPPARTYCLASS<>T.OPPPARTYCLASS
 OR N.OPPNAME<>T.OPPNAME
 OR N.LASTSHIPDATE<>T.LASTSHIPDATE
 OR N.SWIFTTYPE<>T.SWIFTTYPE
 OR N.PROCEEDSDEGREE<>T.PROCEEDSDEGREE
 OR N.LESSPLUSFLAGMODIFY<>T.LESSPLUSFLAGMODIFY
 OR N.LESSPLUSAMTMODIFY<>T.LESSPLUSAMTMODIFY
 OR N.MAILTIME<>T.MAILTIME
;

--Step3:
UPDATE dw_sdata.ISS_001_EX_DOCCOLLINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_235
WHERE P.End_Dt=DATE('2100-12-31')
AND P.BIZNO=T_235.BIZNO
;

--Step4:
INSERT  INTO dw_sdata.ISS_001_EX_DOCCOLLINFO SELECT * FROM T_235;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
