#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ISS_001_GN_LCISSUEINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ISS_001_GN_LCISSUEINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_238 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ISS_001_GN_LCISSUEINFO WHERE 1=0;

--Step2:
INSERT  INTO T_238 (
  TXNSERIALNO,
  LCNO,
  PREADVLCNO,
  ADVBANKSWIFTCODE,
  ADVBANKNO,
  ADVBANKNAMEADDR,
  ISMT799,
  APPNO,
  APPNAMEADDR,
  APPACCT,
  APPBANKNAME,
  SENDTYPE,
  LCISSUINGDATE,
  EXPIRYDATE,
  EXPIRYPLACE,
  LCAMT,
  LCAMTTOLERDOWNORUP,
  LCMAXAMT,
  CONTRACTAMT,
  LCFORM,
  LCPAYTYPE,
  LCPAYDAYS,
  NEGOBANKNAMEADDR,
  NEGOBANKNO,
  LCISSUINGDAYS,
  APPCODE,
  OPENAPPBANKNO,
  OPENAPPBANKNAMEADDR,
  BENEFNAME,
  BENEFNAMEADDR,
  BENEFCOUNTRY,
  OPPPARTYCLASS,
  BENEFACCT,
  BENEFBANKNAME,
  PARTIALSHIPMENT,
  TRANSSHIPMENT,
  LOADPORTNAME,
  TRANSPORTNAME,
  LATESTSHIPDATE,
  TRANSTYPE,
  DEPARTPORT,
  DESTINPORT,
  PRESENTPERIOD,
  OPENAPPBANKTEL,
  OPENAPPBANKFAX,
  POSTSCRIPT,
  NEGTYPE,
  DEFPAYMENTDETAILS,
  LCCURSIGN,
  ISCLOSE,
  YULCAMT,
  APPBANKNO,
  LINKNAME,
  LCABAMT,
  LCACCEPTAMT,
  AMENDTIMES,
  ABTIMES,
  TRADENO,
  PARENTTXNSERIALNO,
  TZBABKNO,
  LCMINAMT,
  BENEFBANKNO,
  LCAMTTOLERDOWN,
  DEPOSITAMT,
  DEPOSITPCT,
  APPOINTBANKSWFCODE,
  APPOINTBANKNAMEADDR,
  APPOINTBANKNO,
  start_dt,
  end_dt)
SELECT
  N.TXNSERIALNO,
  N.LCNO,
  N.PREADVLCNO,
  N.ADVBANKSWIFTCODE,
  N.ADVBANKNO,
  N.ADVBANKNAMEADDR,
  N.ISMT799,
  N.APPNO,
  N.APPNAMEADDR,
  N.APPACCT,
  N.APPBANKNAME,
  N.SENDTYPE,
  N.LCISSUINGDATE,
  N.EXPIRYDATE,
  N.EXPIRYPLACE,
  N.LCAMT,
  N.LCAMTTOLERDOWNORUP,
  N.LCMAXAMT,
  N.CONTRACTAMT,
  N.LCFORM,
  N.LCPAYTYPE,
  N.LCPAYDAYS,
  N.NEGOBANKNAMEADDR,
  N.NEGOBANKNO,
  N.LCISSUINGDAYS,
  N.APPCODE,
  N.OPENAPPBANKNO,
  N.OPENAPPBANKNAMEADDR,
  N.BENEFNAME,
  N.BENEFNAMEADDR,
  N.BENEFCOUNTRY,
  N.OPPPARTYCLASS,
  N.BENEFACCT,
  N.BENEFBANKNAME,
  N.PARTIALSHIPMENT,
  N.TRANSSHIPMENT,
  N.LOADPORTNAME,
  N.TRANSPORTNAME,
  N.LATESTSHIPDATE,
  N.TRANSTYPE,
  N.DEPARTPORT,
  N.DESTINPORT,
  N.PRESENTPERIOD,
  N.OPENAPPBANKTEL,
  N.OPENAPPBANKFAX,
  N.POSTSCRIPT,
  N.NEGTYPE,
  N.DEFPAYMENTDETAILS,
  N.LCCURSIGN,
  N.ISCLOSE,
  N.YULCAMT,
  N.APPBANKNO,
  N.LINKNAME,
  N.LCABAMT,
  N.LCACCEPTAMT,
  N.AMENDTIMES,
  N.ABTIMES,
  N.TRADENO,
  N.PARENTTXNSERIALNO,
  N.TZBABKNO,
  N.LCMINAMT,
  N.BENEFBANKNO,
  N.LCAMTTOLERDOWN,
  N.DEPOSITAMT,
  N.DEPOSITPCT,
  N.APPOINTBANKSWFCODE,
  N.APPOINTBANKNAMEADDR,
  N.APPOINTBANKNO,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(TXNSERIALNO, '' ) AS TXNSERIALNO ,
  COALESCE(LCNO, '' ) AS LCNO ,
  COALESCE(PREADVLCNO, '' ) AS PREADVLCNO ,
  COALESCE(ADVBANKSWIFTCODE, '' ) AS ADVBANKSWIFTCODE ,
  COALESCE(ADVBANKNO, '' ) AS ADVBANKNO ,
  COALESCE(ADVBANKNAMEADDR, '' ) AS ADVBANKNAMEADDR ,
  COALESCE(ISMT799, '' ) AS ISMT799 ,
  COALESCE(APPNO, '' ) AS APPNO ,
  COALESCE(APPNAMEADDR, '' ) AS APPNAMEADDR ,
  COALESCE(APPACCT, '' ) AS APPACCT ,
  COALESCE(APPBANKNAME, '' ) AS APPBANKNAME ,
  COALESCE(SENDTYPE, '' ) AS SENDTYPE ,
  COALESCE(LCISSUINGDATE,DATE('4999-12-31') ) AS LCISSUINGDATE ,
  COALESCE(EXPIRYDATE,DATE('4999-12-31') ) AS EXPIRYDATE ,
  COALESCE(EXPIRYPLACE, '' ) AS EXPIRYPLACE ,
  COALESCE(LCAMT, 0 ) AS LCAMT ,
  COALESCE(LCAMTTOLERDOWNORUP, 0 ) AS LCAMTTOLERDOWNORUP ,
  COALESCE(LCMAXAMT, 0 ) AS LCMAXAMT ,
  COALESCE(CONTRACTAMT, 0 ) AS CONTRACTAMT ,
  COALESCE(LCFORM, '' ) AS LCFORM ,
  COALESCE(LCPAYTYPE, '' ) AS LCPAYTYPE ,
  COALESCE(LCPAYDAYS, 0 ) AS LCPAYDAYS ,
  COALESCE(NEGOBANKNAMEADDR, '' ) AS NEGOBANKNAMEADDR ,
  COALESCE(NEGOBANKNO, '' ) AS NEGOBANKNO ,
  COALESCE(LCISSUINGDAYS, 0 ) AS LCISSUINGDAYS ,
  COALESCE(APPCODE, '' ) AS APPCODE ,
  COALESCE(OPENAPPBANKNO, '' ) AS OPENAPPBANKNO ,
  COALESCE(OPENAPPBANKNAMEADDR, '' ) AS OPENAPPBANKNAMEADDR ,
  COALESCE(BENEFNAME, '' ) AS BENEFNAME ,
  COALESCE(BENEFNAMEADDR, '' ) AS BENEFNAMEADDR ,
  COALESCE(BENEFCOUNTRY, '' ) AS BENEFCOUNTRY ,
  COALESCE(OPPPARTYCLASS, '' ) AS OPPPARTYCLASS ,
  COALESCE(BENEFACCT, '' ) AS BENEFACCT ,
  COALESCE(BENEFBANKNAME, '' ) AS BENEFBANKNAME ,
  COALESCE(PARTIALSHIPMENT, '' ) AS PARTIALSHIPMENT ,
  COALESCE(TRANSSHIPMENT, '' ) AS TRANSSHIPMENT ,
  COALESCE(LOADPORTNAME, '' ) AS LOADPORTNAME ,
  COALESCE(TRANSPORTNAME, '' ) AS TRANSPORTNAME ,
  COALESCE(LATESTSHIPDATE,DATE('4999-12-31') ) AS LATESTSHIPDATE ,
  COALESCE(TRANSTYPE, '' ) AS TRANSTYPE ,
  COALESCE(DEPARTPORT, '' ) AS DEPARTPORT ,
  COALESCE(DESTINPORT, '' ) AS DESTINPORT ,
  COALESCE(PRESENTPERIOD, 0 ) AS PRESENTPERIOD ,
  COALESCE(OPENAPPBANKTEL, '' ) AS OPENAPPBANKTEL ,
  COALESCE(OPENAPPBANKFAX, '' ) AS OPENAPPBANKFAX ,
  COALESCE(POSTSCRIPT, '' ) AS POSTSCRIPT ,
  COALESCE(NEGTYPE, '' ) AS NEGTYPE ,
  COALESCE(DEFPAYMENTDETAILS, '' ) AS DEFPAYMENTDETAILS ,
  COALESCE(LCCURSIGN, '' ) AS LCCURSIGN ,
  COALESCE(ISCLOSE, '' ) AS ISCLOSE ,
  COALESCE(YULCAMT, 0 ) AS YULCAMT ,
  COALESCE(APPBANKNO, '' ) AS APPBANKNO ,
  COALESCE(LINKNAME, '' ) AS LINKNAME ,
  COALESCE(LCABAMT, 0 ) AS LCABAMT ,
  COALESCE(LCACCEPTAMT, 0 ) AS LCACCEPTAMT ,
  COALESCE(AMENDTIMES, 0 ) AS AMENDTIMES ,
  COALESCE(ABTIMES, 0 ) AS ABTIMES ,
  COALESCE(TRADENO, '' ) AS TRADENO ,
  COALESCE(PARENTTXNSERIALNO, '' ) AS PARENTTXNSERIALNO ,
  COALESCE(TZBABKNO, '' ) AS TZBABKNO ,
  COALESCE(LCMINAMT, 0 ) AS LCMINAMT ,
  COALESCE(BENEFBANKNO, '' ) AS BENEFBANKNO ,
  COALESCE(LCAMTTOLERDOWN, 0 ) AS LCAMTTOLERDOWN ,
  COALESCE(DEPOSITAMT, 0 ) AS DEPOSITAMT ,
  COALESCE(DEPOSITPCT, '' ) AS DEPOSITPCT ,
  COALESCE(APPOINTBANKSWFCODE, '' ) AS APPOINTBANKSWFCODE ,
  COALESCE(APPOINTBANKNAMEADDR, '' ) AS APPOINTBANKNAMEADDR ,
  COALESCE(APPOINTBANKNO, '' ) AS APPOINTBANKNO 
 FROM  dw_tdata.ISS_001_GN_LCISSUEINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  TXNSERIALNO ,
  LCNO ,
  PREADVLCNO ,
  ADVBANKSWIFTCODE ,
  ADVBANKNO ,
  ADVBANKNAMEADDR ,
  ISMT799 ,
  APPNO ,
  APPNAMEADDR ,
  APPACCT ,
  APPBANKNAME ,
  SENDTYPE ,
  LCISSUINGDATE ,
  EXPIRYDATE ,
  EXPIRYPLACE ,
  LCAMT ,
  LCAMTTOLERDOWNORUP ,
  LCMAXAMT ,
  CONTRACTAMT ,
  LCFORM ,
  LCPAYTYPE ,
  LCPAYDAYS ,
  NEGOBANKNAMEADDR ,
  NEGOBANKNO ,
  LCISSUINGDAYS ,
  APPCODE ,
  OPENAPPBANKNO ,
  OPENAPPBANKNAMEADDR ,
  BENEFNAME ,
  BENEFNAMEADDR ,
  BENEFCOUNTRY ,
  OPPPARTYCLASS ,
  BENEFACCT ,
  BENEFBANKNAME ,
  PARTIALSHIPMENT ,
  TRANSSHIPMENT ,
  LOADPORTNAME ,
  TRANSPORTNAME ,
  LATESTSHIPDATE ,
  TRANSTYPE ,
  DEPARTPORT ,
  DESTINPORT ,
  PRESENTPERIOD ,
  OPENAPPBANKTEL ,
  OPENAPPBANKFAX ,
  POSTSCRIPT ,
  NEGTYPE ,
  DEFPAYMENTDETAILS ,
  LCCURSIGN ,
  ISCLOSE ,
  YULCAMT ,
  APPBANKNO ,
  LINKNAME ,
  LCABAMT ,
  LCACCEPTAMT ,
  AMENDTIMES ,
  ABTIMES ,
  TRADENO ,
  PARENTTXNSERIALNO ,
  TZBABKNO ,
  LCMINAMT ,
  BENEFBANKNO ,
  LCAMTTOLERDOWN ,
  DEPOSITAMT ,
  DEPOSITPCT ,
  APPOINTBANKSWFCODE ,
  APPOINTBANKNAMEADDR ,
  APPOINTBANKNO 
 FROM dw_sdata.ISS_001_GN_LCISSUEINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.TXNSERIALNO = T.TXNSERIALNO
WHERE
(T.TXNSERIALNO IS NULL)
 OR N.LCNO<>T.LCNO
 OR N.PREADVLCNO<>T.PREADVLCNO
 OR N.ADVBANKSWIFTCODE<>T.ADVBANKSWIFTCODE
 OR N.ADVBANKNO<>T.ADVBANKNO
 OR N.ADVBANKNAMEADDR<>T.ADVBANKNAMEADDR
 OR N.ISMT799<>T.ISMT799
 OR N.APPNO<>T.APPNO
 OR N.APPNAMEADDR<>T.APPNAMEADDR
 OR N.APPACCT<>T.APPACCT
 OR N.APPBANKNAME<>T.APPBANKNAME
 OR N.SENDTYPE<>T.SENDTYPE
 OR N.LCISSUINGDATE<>T.LCISSUINGDATE
 OR N.EXPIRYDATE<>T.EXPIRYDATE
 OR N.EXPIRYPLACE<>T.EXPIRYPLACE
 OR N.LCAMT<>T.LCAMT
 OR N.LCAMTTOLERDOWNORUP<>T.LCAMTTOLERDOWNORUP
 OR N.LCMAXAMT<>T.LCMAXAMT
 OR N.CONTRACTAMT<>T.CONTRACTAMT
 OR N.LCFORM<>T.LCFORM
 OR N.LCPAYTYPE<>T.LCPAYTYPE
 OR N.LCPAYDAYS<>T.LCPAYDAYS
 OR N.NEGOBANKNAMEADDR<>T.NEGOBANKNAMEADDR
 OR N.NEGOBANKNO<>T.NEGOBANKNO
 OR N.LCISSUINGDAYS<>T.LCISSUINGDAYS
 OR N.APPCODE<>T.APPCODE
 OR N.OPENAPPBANKNO<>T.OPENAPPBANKNO
 OR N.OPENAPPBANKNAMEADDR<>T.OPENAPPBANKNAMEADDR
 OR N.BENEFNAME<>T.BENEFNAME
 OR N.BENEFNAMEADDR<>T.BENEFNAMEADDR
 OR N.BENEFCOUNTRY<>T.BENEFCOUNTRY
 OR N.OPPPARTYCLASS<>T.OPPPARTYCLASS
 OR N.BENEFACCT<>T.BENEFACCT
 OR N.BENEFBANKNAME<>T.BENEFBANKNAME
 OR N.PARTIALSHIPMENT<>T.PARTIALSHIPMENT
 OR N.TRANSSHIPMENT<>T.TRANSSHIPMENT
 OR N.LOADPORTNAME<>T.LOADPORTNAME
 OR N.TRANSPORTNAME<>T.TRANSPORTNAME
 OR N.LATESTSHIPDATE<>T.LATESTSHIPDATE
 OR N.TRANSTYPE<>T.TRANSTYPE
 OR N.DEPARTPORT<>T.DEPARTPORT
 OR N.DESTINPORT<>T.DESTINPORT
 OR N.PRESENTPERIOD<>T.PRESENTPERIOD
 OR N.OPENAPPBANKTEL<>T.OPENAPPBANKTEL
 OR N.OPENAPPBANKFAX<>T.OPENAPPBANKFAX
 OR N.POSTSCRIPT<>T.POSTSCRIPT
 OR N.NEGTYPE<>T.NEGTYPE
 OR N.DEFPAYMENTDETAILS<>T.DEFPAYMENTDETAILS
 OR N.LCCURSIGN<>T.LCCURSIGN
 OR N.ISCLOSE<>T.ISCLOSE
 OR N.YULCAMT<>T.YULCAMT
 OR N.APPBANKNO<>T.APPBANKNO
 OR N.LINKNAME<>T.LINKNAME
 OR N.LCABAMT<>T.LCABAMT
 OR N.LCACCEPTAMT<>T.LCACCEPTAMT
 OR N.AMENDTIMES<>T.AMENDTIMES
 OR N.ABTIMES<>T.ABTIMES
 OR N.TRADENO<>T.TRADENO
 OR N.PARENTTXNSERIALNO<>T.PARENTTXNSERIALNO
 OR N.TZBABKNO<>T.TZBABKNO
 OR N.LCMINAMT<>T.LCMINAMT
 OR N.BENEFBANKNO<>T.BENEFBANKNO
 OR N.LCAMTTOLERDOWN<>T.LCAMTTOLERDOWN
 OR N.DEPOSITAMT<>T.DEPOSITAMT
 OR N.DEPOSITPCT<>T.DEPOSITPCT
 OR N.APPOINTBANKSWFCODE<>T.APPOINTBANKSWFCODE
 OR N.APPOINTBANKNAMEADDR<>T.APPOINTBANKNAMEADDR
 OR N.APPOINTBANKNO<>T.APPOINTBANKNO
;

--Step3:
UPDATE dw_sdata.ISS_001_GN_LCISSUEINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_238
WHERE P.End_Dt=DATE('2100-12-31')
AND P.TXNSERIALNO=T_238.TXNSERIALNO
;

--Step4:
INSERT  INTO dw_sdata.ISS_001_GN_LCISSUEINFO SELECT * FROM T_238;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
