#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.ISS_001_BU_TRANSACTIONINFO WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.ISS_001_BU_TRANSACTIONINFO SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_230 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.ISS_001_BU_TRANSACTIONINFO WHERE 1=0;

--Step2:
INSERT  INTO T_230 (
  TXNSERIALNO,
  PROCESSNO,
  TRADENO,
  BELONGORGNO,
  TRANSACTORGNO,
  CURRENTBIZNO,
  SECONDARYBIZNO,
  PRIMARYBIZNO,
  LAUNCHMODENO,
  LAUNCHDATE,
  FILENO,
  CURSIGN,
  AMOUNT,
  INTERETDATE,
  ISNEEDDECLARE,
  DECLAREDATE,
  ISNEEDACCOUNT,
  ACCOUNTDATE,
  ISNEEDSWF,
  SWFDATE,
  FINISHEDDATE,
  REVERSEENTRYDATE,
  TRANSTATE,
  MEMO,
  CORPNO,
  HANDLEOPERID,
  CHECKOPERID,
  MANAGERID,
  DEBTNO,
  FAXNOTE,
  COUNTRYCODE,
  CREDITFLAG,
  MIDACCT,
  SPFETYPE,
  CORECUSTNO,
  ISAUTH,
  NETTXNNO,
  APPTXNSERIALNO,
  ISACCEPT,
  MANAGERIDSECOND,
  MANAGERIDTHIRD,
  MARKETINGORGNO,
  FOREIGNCURRENCYORGNO,
  ACCOUNTTOTALORGNO,
  LETTERFLAG,
  BUSINESSORGNO,
  MANAGERIDSECONDNAME,
  MANAGERIDTHIRDNAME,
  APPORGNO,
  LETTERFLAGUSERID,
  BACKTXNSERIALNO,
  BILLORGNO,
  EBILLSORGNO,
  APPBIZNO,
  MANAGERIDNAME,
  REMTSUBTYPE,
  ISNOWCHARGE,
  REMTTYPE,
  JSWLCODEIN,
  JSWLCODEOUT,
  start_dt,
  end_dt)
SELECT
  N.TXNSERIALNO,
  N.PROCESSNO,
  N.TRADENO,
  N.BELONGORGNO,
  N.TRANSACTORGNO,
  N.CURRENTBIZNO,
  N.SECONDARYBIZNO,
  N.PRIMARYBIZNO,
  N.LAUNCHMODENO,
  N.LAUNCHDATE,
  N.FILENO,
  N.CURSIGN,
  N.AMOUNT,
  N.INTERETDATE,
  N.ISNEEDDECLARE,
  N.DECLAREDATE,
  N.ISNEEDACCOUNT,
  N.ACCOUNTDATE,
  N.ISNEEDSWF,
  N.SWFDATE,
  N.FINISHEDDATE,
  N.REVERSEENTRYDATE,
  N.TRANSTATE,
  N.MEMO,
  N.CORPNO,
  N.HANDLEOPERID,
  N.CHECKOPERID,
  N.MANAGERID,
  N.DEBTNO,
  N.FAXNOTE,
  N.COUNTRYCODE,
  N.CREDITFLAG,
  N.MIDACCT,
  N.SPFETYPE,
  N.CORECUSTNO,
  N.ISAUTH,
  N.NETTXNNO,
  N.APPTXNSERIALNO,
  N.ISACCEPT,
  N.MANAGERIDSECOND,
  N.MANAGERIDTHIRD,
  N.MARKETINGORGNO,
  N.FOREIGNCURRENCYORGNO,
  N.ACCOUNTTOTALORGNO,
  N.LETTERFLAG,
  N.BUSINESSORGNO,
  N.MANAGERIDSECONDNAME,
  N.MANAGERIDTHIRDNAME,
  N.APPORGNO,
  N.LETTERFLAGUSERID,
  N.BACKTXNSERIALNO,
  N.BILLORGNO,
  N.EBILLSORGNO,
  N.APPBIZNO,
  N.MANAGERIDNAME,
  N.REMTSUBTYPE,
  N.ISNOWCHARGE,
  N.REMTTYPE,
  N.JSWLCODEIN,
  N.JSWLCODEOUT,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(TXNSERIALNO, '' ) AS TXNSERIALNO ,
  COALESCE(PROCESSNO, 0 ) AS PROCESSNO ,
  COALESCE(TRADENO, '' ) AS TRADENO ,
  COALESCE(BELONGORGNO, '' ) AS BELONGORGNO ,
  COALESCE(TRANSACTORGNO, '' ) AS TRANSACTORGNO ,
  COALESCE(CURRENTBIZNO, '' ) AS CURRENTBIZNO ,
  COALESCE(SECONDARYBIZNO, '' ) AS SECONDARYBIZNO ,
  COALESCE(PRIMARYBIZNO, '' ) AS PRIMARYBIZNO ,
  COALESCE(LAUNCHMODENO, '' ) AS LAUNCHMODENO ,
  COALESCE(LAUNCHDATE,DATE('4999-12-31') ) AS LAUNCHDATE ,
  COALESCE(FILENO, '' ) AS FILENO ,
  COALESCE(CURSIGN, '' ) AS CURSIGN ,
  COALESCE(AMOUNT, 0 ) AS AMOUNT ,
  COALESCE(INTERETDATE,DATE('4999-12-31') ) AS INTERETDATE ,
  COALESCE(ISNEEDDECLARE, '' ) AS ISNEEDDECLARE ,
  COALESCE(DECLAREDATE,DATE('4999-12-31') ) AS DECLAREDATE ,
  COALESCE(ISNEEDACCOUNT, '' ) AS ISNEEDACCOUNT ,
  COALESCE(ACCOUNTDATE,DATE('4999-12-31') ) AS ACCOUNTDATE ,
  COALESCE(ISNEEDSWF, '' ) AS ISNEEDSWF ,
  COALESCE(SWFDATE,DATE('4999-12-31') ) AS SWFDATE ,
  COALESCE(FINISHEDDATE,DATE('4999-12-31') ) AS FINISHEDDATE ,
  COALESCE(REVERSEENTRYDATE,DATE('4999-12-31') ) AS REVERSEENTRYDATE ,
  COALESCE(TRANSTATE, '' ) AS TRANSTATE ,
  COALESCE(MEMO, '' ) AS MEMO ,
  COALESCE(CORPNO, '' ) AS CORPNO ,
  COALESCE(HANDLEOPERID, 0 ) AS HANDLEOPERID ,
  COALESCE(CHECKOPERID, 0 ) AS CHECKOPERID ,
  COALESCE(MANAGERID, '' ) AS MANAGERID ,
  COALESCE(DEBTNO, '' ) AS DEBTNO ,
  COALESCE(FAXNOTE, '' ) AS FAXNOTE ,
  COALESCE(COUNTRYCODE, '' ) AS COUNTRYCODE ,
  COALESCE(CREDITFLAG, '' ) AS CREDITFLAG ,
  COALESCE(MIDACCT, '' ) AS MIDACCT ,
  COALESCE(SPFETYPE, '' ) AS SPFETYPE ,
  COALESCE(CORECUSTNO, '' ) AS CORECUSTNO ,
  COALESCE(ISAUTH, '' ) AS ISAUTH ,
  COALESCE(NETTXNNO, '' ) AS NETTXNNO ,
  COALESCE(APPTXNSERIALNO, '' ) AS APPTXNSERIALNO ,
  COALESCE(ISACCEPT, '' ) AS ISACCEPT ,
  COALESCE(MANAGERIDSECOND, '' ) AS MANAGERIDSECOND ,
  COALESCE(MANAGERIDTHIRD, '' ) AS MANAGERIDTHIRD ,
  COALESCE(MARKETINGORGNO, '' ) AS MARKETINGORGNO ,
  COALESCE(FOREIGNCURRENCYORGNO, '' ) AS FOREIGNCURRENCYORGNO ,
  COALESCE(ACCOUNTTOTALORGNO, '' ) AS ACCOUNTTOTALORGNO ,
  COALESCE(LETTERFLAG, '' ) AS LETTERFLAG ,
  COALESCE(BUSINESSORGNO, '' ) AS BUSINESSORGNO ,
  COALESCE(MANAGERIDSECONDNAME, '' ) AS MANAGERIDSECONDNAME ,
  COALESCE(MANAGERIDTHIRDNAME, '' ) AS MANAGERIDTHIRDNAME ,
  COALESCE(APPORGNO, '' ) AS APPORGNO ,
  COALESCE(LETTERFLAGUSERID, 0 ) AS LETTERFLAGUSERID ,
  COALESCE(BACKTXNSERIALNO, '' ) AS BACKTXNSERIALNO ,
  COALESCE(BILLORGNO, '' ) AS BILLORGNO ,
  COALESCE(EBILLSORGNO, '' ) AS EBILLSORGNO ,
  COALESCE(APPBIZNO, '' ) AS APPBIZNO ,
  COALESCE(MANAGERIDNAME, '' ) AS MANAGERIDNAME ,
  COALESCE(REMTSUBTYPE, '' ) AS REMTSUBTYPE ,
  COALESCE(ISNOWCHARGE, '' ) AS ISNOWCHARGE ,
  COALESCE(REMTTYPE, '' ) AS REMTTYPE ,
  COALESCE(JSWLCODEIN, '' ) AS JSWLCODEIN ,
  COALESCE(JSWLCODEOUT, '' ) AS JSWLCODEOUT 
 FROM  dw_tdata.ISS_001_BU_TRANSACTIONINFO_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  TXNSERIALNO ,
  PROCESSNO ,
  TRADENO ,
  BELONGORGNO ,
  TRANSACTORGNO ,
  CURRENTBIZNO ,
  SECONDARYBIZNO ,
  PRIMARYBIZNO ,
  LAUNCHMODENO ,
  LAUNCHDATE ,
  FILENO ,
  CURSIGN ,
  AMOUNT ,
  INTERETDATE ,
  ISNEEDDECLARE ,
  DECLAREDATE ,
  ISNEEDACCOUNT ,
  ACCOUNTDATE ,
  ISNEEDSWF ,
  SWFDATE ,
  FINISHEDDATE ,
  REVERSEENTRYDATE ,
  TRANSTATE ,
  MEMO ,
  CORPNO ,
  HANDLEOPERID ,
  CHECKOPERID ,
  MANAGERID ,
  DEBTNO ,
  FAXNOTE ,
  COUNTRYCODE ,
  CREDITFLAG ,
  MIDACCT ,
  SPFETYPE ,
  CORECUSTNO ,
  ISAUTH ,
  NETTXNNO ,
  APPTXNSERIALNO ,
  ISACCEPT ,
  MANAGERIDSECOND ,
  MANAGERIDTHIRD ,
  MARKETINGORGNO ,
  FOREIGNCURRENCYORGNO ,
  ACCOUNTTOTALORGNO ,
  LETTERFLAG ,
  BUSINESSORGNO ,
  MANAGERIDSECONDNAME ,
  MANAGERIDTHIRDNAME ,
  APPORGNO ,
  LETTERFLAGUSERID ,
  BACKTXNSERIALNO ,
  BILLORGNO ,
  EBILLSORGNO ,
  APPBIZNO ,
  MANAGERIDNAME ,
  REMTSUBTYPE ,
  ISNOWCHARGE ,
  REMTTYPE ,
  JSWLCODEIN ,
  JSWLCODEOUT 
 FROM dw_sdata.ISS_001_BU_TRANSACTIONINFO 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.TXNSERIALNO = T.TXNSERIALNO
WHERE
(T.TXNSERIALNO IS NULL)
 OR N.PROCESSNO<>T.PROCESSNO
 OR N.TRADENO<>T.TRADENO
 OR N.BELONGORGNO<>T.BELONGORGNO
 OR N.TRANSACTORGNO<>T.TRANSACTORGNO
 OR N.CURRENTBIZNO<>T.CURRENTBIZNO
 OR N.SECONDARYBIZNO<>T.SECONDARYBIZNO
 OR N.PRIMARYBIZNO<>T.PRIMARYBIZNO
 OR N.LAUNCHMODENO<>T.LAUNCHMODENO
 OR N.LAUNCHDATE<>T.LAUNCHDATE
 OR N.FILENO<>T.FILENO
 OR N.CURSIGN<>T.CURSIGN
 OR N.AMOUNT<>T.AMOUNT
 OR N.INTERETDATE<>T.INTERETDATE
 OR N.ISNEEDDECLARE<>T.ISNEEDDECLARE
 OR N.DECLAREDATE<>T.DECLAREDATE
 OR N.ISNEEDACCOUNT<>T.ISNEEDACCOUNT
 OR N.ACCOUNTDATE<>T.ACCOUNTDATE
 OR N.ISNEEDSWF<>T.ISNEEDSWF
 OR N.SWFDATE<>T.SWFDATE
 OR N.FINISHEDDATE<>T.FINISHEDDATE
 OR N.REVERSEENTRYDATE<>T.REVERSEENTRYDATE
 OR N.TRANSTATE<>T.TRANSTATE
 OR N.MEMO<>T.MEMO
 OR N.CORPNO<>T.CORPNO
 OR N.HANDLEOPERID<>T.HANDLEOPERID
 OR N.CHECKOPERID<>T.CHECKOPERID
 OR N.MANAGERID<>T.MANAGERID
 OR N.DEBTNO<>T.DEBTNO
 OR N.FAXNOTE<>T.FAXNOTE
 OR N.COUNTRYCODE<>T.COUNTRYCODE
 OR N.CREDITFLAG<>T.CREDITFLAG
 OR N.MIDACCT<>T.MIDACCT
 OR N.SPFETYPE<>T.SPFETYPE
 OR N.CORECUSTNO<>T.CORECUSTNO
 OR N.ISAUTH<>T.ISAUTH
 OR N.NETTXNNO<>T.NETTXNNO
 OR N.APPTXNSERIALNO<>T.APPTXNSERIALNO
 OR N.ISACCEPT<>T.ISACCEPT
 OR N.MANAGERIDSECOND<>T.MANAGERIDSECOND
 OR N.MANAGERIDTHIRD<>T.MANAGERIDTHIRD
 OR N.MARKETINGORGNO<>T.MARKETINGORGNO
 OR N.FOREIGNCURRENCYORGNO<>T.FOREIGNCURRENCYORGNO
 OR N.ACCOUNTTOTALORGNO<>T.ACCOUNTTOTALORGNO
 OR N.LETTERFLAG<>T.LETTERFLAG
 OR N.BUSINESSORGNO<>T.BUSINESSORGNO
 OR N.MANAGERIDSECONDNAME<>T.MANAGERIDSECONDNAME
 OR N.MANAGERIDTHIRDNAME<>T.MANAGERIDTHIRDNAME
 OR N.APPORGNO<>T.APPORGNO
 OR N.LETTERFLAGUSERID<>T.LETTERFLAGUSERID
 OR N.BACKTXNSERIALNO<>T.BACKTXNSERIALNO
 OR N.BILLORGNO<>T.BILLORGNO
 OR N.EBILLSORGNO<>T.EBILLSORGNO
 OR N.APPBIZNO<>T.APPBIZNO
 OR N.MANAGERIDNAME<>T.MANAGERIDNAME
 OR N.REMTSUBTYPE<>T.REMTSUBTYPE
 OR N.ISNOWCHARGE<>T.ISNOWCHARGE
 OR N.REMTTYPE<>T.REMTTYPE
 OR N.JSWLCODEIN<>T.JSWLCODEIN
 OR N.JSWLCODEOUT<>T.JSWLCODEOUT
;

--Step3:
UPDATE dw_sdata.ISS_001_BU_TRANSACTIONINFO P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_230
WHERE P.End_Dt=DATE('2100-12-31')
AND P.TXNSERIALNO=T_230.TXNSERIALNO
;

--Step4:
INSERT  INTO dw_sdata.ISS_001_BU_TRANSACTIONINFO SELECT * FROM T_230;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
