#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.PCS_005_TB_SUP_DEBT_INFO_N WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.PCS_005_TB_SUP_DEBT_INFO_N SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_318 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.PCS_005_TB_SUP_DEBT_INFO_N WHERE 1=0;

--Step2:
INSERT  INTO T_318 (
  PRV_COD,
  OPN_DEP,
  TAL_DEP,
  DUE_NUM,
  RCV_DATE,
  PRM_CLS,
  AST_CLS,
  TRAN_FROM,
  CURR_PERI,
  BEG_DATE,
  END_DATE,
  CEAS_SYMBOL,
  STAN,
  CURR_COD,
  NOR_ITR_RATE,
  DEL_ITR_RATE,
  FREE_AMT,
  RCV_PRN,
  PAD_UP_PRN,
  RCV_NOR_ITR_IN,
  PAD_UP_NOR_ITR_IN,
  RCV_DFT_ITR_IN,
  PAD_UP_DFT_ITR_IN,
  RCV_PNS_ITR_IN,
  PAD_UP_PNS_ITR_IN,
  RCV_NOR_ITR_OUT,
  PAD_UP_NOR_ITR_OUT,
  RCV_DFT_ITR_OUT,
  PAD_UP_DFT_ITR_OUT,
  RCV_PNS_ITR_OUT,
  PAD_UP_PNS_ITR_OUT,
  DFT_PRN_OTD_ITR,
  DFT_ITR_IN_OTD_ITR,
  DFT_ITR_OUT_OTD_ITR,
  NOR_ITR_IN_OTD_ITR,
  NOR_ITR_OUT_OTD_ITR,
  FORW_PROV_DATE,
  PAY_DATE,
  DLY_PRN_PNS_ITR,
  DLY_IN_BAL_PNS_ITR,
  DLY_OUT_BAL_PNS_ITR,
  RMK1,
  RMK2,
  RMK3,
  RMK1_BAL,
  RMK2_BAL,
  RMK3_BAL,
  HLD_FLG,
  start_dt,
  end_dt)
SELECT
  N.PRV_COD,
  N.OPN_DEP,
  N.TAL_DEP,
  N.DUE_NUM,
  N.RCV_DATE,
  N.PRM_CLS,
  N.AST_CLS,
  N.TRAN_FROM,
  N.CURR_PERI,
  N.BEG_DATE,
  N.END_DATE,
  N.CEAS_SYMBOL,
  N.STAN,
  N.CURR_COD,
  N.NOR_ITR_RATE,
  N.DEL_ITR_RATE,
  N.FREE_AMT,
  N.RCV_PRN,
  N.PAD_UP_PRN,
  N.RCV_NOR_ITR_IN,
  N.PAD_UP_NOR_ITR_IN,
  N.RCV_DFT_ITR_IN,
  N.PAD_UP_DFT_ITR_IN,
  N.RCV_PNS_ITR_IN,
  N.PAD_UP_PNS_ITR_IN,
  N.RCV_NOR_ITR_OUT,
  N.PAD_UP_NOR_ITR_OUT,
  N.RCV_DFT_ITR_OUT,
  N.PAD_UP_DFT_ITR_OUT,
  N.RCV_PNS_ITR_OUT,
  N.PAD_UP_PNS_ITR_OUT,
  N.DFT_PRN_OTD_ITR,
  N.DFT_ITR_IN_OTD_ITR,
  N.DFT_ITR_OUT_OTD_ITR,
  N.NOR_ITR_IN_OTD_ITR,
  N.NOR_ITR_OUT_OTD_ITR,
  N.FORW_PROV_DATE,
  N.PAY_DATE,
  N.DLY_PRN_PNS_ITR,
  N.DLY_IN_BAL_PNS_ITR,
  N.DLY_OUT_BAL_PNS_ITR,
  N.RMK1,
  N.RMK2,
  N.RMK3,
  N.RMK1_BAL,
  N.RMK2_BAL,
  N.RMK3_BAL,
  N.HLD_FLG,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(PRV_COD, '' ) AS PRV_COD ,
  COALESCE(OPN_DEP, '' ) AS OPN_DEP ,
  COALESCE(TAL_DEP, '' ) AS TAL_DEP ,
  COALESCE(DUE_NUM, '' ) AS DUE_NUM ,
  COALESCE(RCV_DATE, '' ) AS RCV_DATE ,
  COALESCE(PRM_CLS, '' ) AS PRM_CLS ,
  COALESCE(AST_CLS, '' ) AS AST_CLS ,
  COALESCE(TRAN_FROM, '' ) AS TRAN_FROM ,
  COALESCE(CURR_PERI, 0 ) AS CURR_PERI ,
  COALESCE(BEG_DATE, '' ) AS BEG_DATE ,
  COALESCE(END_DATE, '' ) AS END_DATE ,
  COALESCE(CEAS_SYMBOL, '' ) AS CEAS_SYMBOL ,
  COALESCE(STAN, 0 ) AS STAN ,
  COALESCE(CURR_COD, '' ) AS CURR_COD ,
  COALESCE(NOR_ITR_RATE, 0 ) AS NOR_ITR_RATE ,
  COALESCE(DEL_ITR_RATE, 0 ) AS DEL_ITR_RATE ,
  COALESCE(FREE_AMT, 0 ) AS FREE_AMT ,
  COALESCE(RCV_PRN, 0 ) AS RCV_PRN ,
  COALESCE(PAD_UP_PRN, 0 ) AS PAD_UP_PRN ,
  COALESCE(RCV_NOR_ITR_IN, 0 ) AS RCV_NOR_ITR_IN ,
  COALESCE(PAD_UP_NOR_ITR_IN, 0 ) AS PAD_UP_NOR_ITR_IN ,
  COALESCE(RCV_DFT_ITR_IN, 0 ) AS RCV_DFT_ITR_IN ,
  COALESCE(PAD_UP_DFT_ITR_IN, 0 ) AS PAD_UP_DFT_ITR_IN ,
  COALESCE(RCV_PNS_ITR_IN, 0 ) AS RCV_PNS_ITR_IN ,
  COALESCE(PAD_UP_PNS_ITR_IN, 0 ) AS PAD_UP_PNS_ITR_IN ,
  COALESCE(RCV_NOR_ITR_OUT, 0 ) AS RCV_NOR_ITR_OUT ,
  COALESCE(PAD_UP_NOR_ITR_OUT, 0 ) AS PAD_UP_NOR_ITR_OUT ,
  COALESCE(RCV_DFT_ITR_OUT, 0 ) AS RCV_DFT_ITR_OUT ,
  COALESCE(PAD_UP_DFT_ITR_OUT, 0 ) AS PAD_UP_DFT_ITR_OUT ,
  COALESCE(RCV_PNS_ITR_OUT, 0 ) AS RCV_PNS_ITR_OUT ,
  COALESCE(PAD_UP_PNS_ITR_OUT, 0 ) AS PAD_UP_PNS_ITR_OUT ,
  COALESCE(DFT_PRN_OTD_ITR, 0 ) AS DFT_PRN_OTD_ITR ,
  COALESCE(DFT_ITR_IN_OTD_ITR, 0 ) AS DFT_ITR_IN_OTD_ITR ,
  COALESCE(DFT_ITR_OUT_OTD_ITR, 0 ) AS DFT_ITR_OUT_OTD_ITR ,
  COALESCE(NOR_ITR_IN_OTD_ITR, 0 ) AS NOR_ITR_IN_OTD_ITR ,
  COALESCE(NOR_ITR_OUT_OTD_ITR, 0 ) AS NOR_ITR_OUT_OTD_ITR ,
  COALESCE(FORW_PROV_DATE, '' ) AS FORW_PROV_DATE ,
  COALESCE(PAY_DATE, '' ) AS PAY_DATE ,
  COALESCE(DLY_PRN_PNS_ITR, 0 ) AS DLY_PRN_PNS_ITR ,
  COALESCE(DLY_IN_BAL_PNS_ITR, 0 ) AS DLY_IN_BAL_PNS_ITR ,
  COALESCE(DLY_OUT_BAL_PNS_ITR, 0 ) AS DLY_OUT_BAL_PNS_ITR ,
  COALESCE(RMK1, '' ) AS RMK1 ,
  COALESCE(RMK2, '' ) AS RMK2 ,
  COALESCE(RMK3, '' ) AS RMK3 ,
  COALESCE(RMK1_BAL, 0 ) AS RMK1_BAL ,
  COALESCE(RMK2_BAL, 0 ) AS RMK2_BAL ,
  COALESCE(RMK3_BAL, 0 ) AS RMK3_BAL ,
  COALESCE(HLD_FLG, '' ) AS HLD_FLG 
 FROM  dw_tdata.PCS_005_TB_SUP_DEBT_INFO_N_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  PRV_COD ,
  OPN_DEP ,
  TAL_DEP ,
  DUE_NUM ,
  RCV_DATE ,
  PRM_CLS ,
  AST_CLS ,
  TRAN_FROM ,
  CURR_PERI ,
  BEG_DATE ,
  END_DATE ,
  CEAS_SYMBOL ,
  STAN ,
  CURR_COD ,
  NOR_ITR_RATE ,
  DEL_ITR_RATE ,
  FREE_AMT ,
  RCV_PRN ,
  PAD_UP_PRN ,
  RCV_NOR_ITR_IN ,
  PAD_UP_NOR_ITR_IN ,
  RCV_DFT_ITR_IN ,
  PAD_UP_DFT_ITR_IN ,
  RCV_PNS_ITR_IN ,
  PAD_UP_PNS_ITR_IN ,
  RCV_NOR_ITR_OUT ,
  PAD_UP_NOR_ITR_OUT ,
  RCV_DFT_ITR_OUT ,
  PAD_UP_DFT_ITR_OUT ,
  RCV_PNS_ITR_OUT ,
  PAD_UP_PNS_ITR_OUT ,
  DFT_PRN_OTD_ITR ,
  DFT_ITR_IN_OTD_ITR ,
  DFT_ITR_OUT_OTD_ITR ,
  NOR_ITR_IN_OTD_ITR ,
  NOR_ITR_OUT_OTD_ITR ,
  FORW_PROV_DATE ,
  PAY_DATE ,
  DLY_PRN_PNS_ITR ,
  DLY_IN_BAL_PNS_ITR ,
  DLY_OUT_BAL_PNS_ITR ,
  RMK1 ,
  RMK2 ,
  RMK3 ,
  RMK1_BAL ,
  RMK2_BAL ,
  RMK3_BAL ,
  HLD_FLG 
 FROM dw_sdata.PCS_005_TB_SUP_DEBT_INFO_N 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.DUE_NUM = T.DUE_NUM AND N.RCV_DATE = T.RCV_DATE
WHERE
(T.DUE_NUM IS NULL AND T.RCV_DATE IS NULL)
 OR N.PRV_COD<>T.PRV_COD
 OR N.OPN_DEP<>T.OPN_DEP
 OR N.TAL_DEP<>T.TAL_DEP
 OR N.PRM_CLS<>T.PRM_CLS
 OR N.AST_CLS<>T.AST_CLS
 OR N.TRAN_FROM<>T.TRAN_FROM
 OR N.CURR_PERI<>T.CURR_PERI
 OR N.BEG_DATE<>T.BEG_DATE
 OR N.END_DATE<>T.END_DATE
 OR N.CEAS_SYMBOL<>T.CEAS_SYMBOL
 OR N.STAN<>T.STAN
 OR N.CURR_COD<>T.CURR_COD
 OR N.NOR_ITR_RATE<>T.NOR_ITR_RATE
 OR N.DEL_ITR_RATE<>T.DEL_ITR_RATE
 OR N.FREE_AMT<>T.FREE_AMT
 OR N.RCV_PRN<>T.RCV_PRN
 OR N.PAD_UP_PRN<>T.PAD_UP_PRN
 OR N.RCV_NOR_ITR_IN<>T.RCV_NOR_ITR_IN
 OR N.PAD_UP_NOR_ITR_IN<>T.PAD_UP_NOR_ITR_IN
 OR N.RCV_DFT_ITR_IN<>T.RCV_DFT_ITR_IN
 OR N.PAD_UP_DFT_ITR_IN<>T.PAD_UP_DFT_ITR_IN
 OR N.RCV_PNS_ITR_IN<>T.RCV_PNS_ITR_IN
 OR N.PAD_UP_PNS_ITR_IN<>T.PAD_UP_PNS_ITR_IN
 OR N.RCV_NOR_ITR_OUT<>T.RCV_NOR_ITR_OUT
 OR N.PAD_UP_NOR_ITR_OUT<>T.PAD_UP_NOR_ITR_OUT
 OR N.RCV_DFT_ITR_OUT<>T.RCV_DFT_ITR_OUT
 OR N.PAD_UP_DFT_ITR_OUT<>T.PAD_UP_DFT_ITR_OUT
 OR N.RCV_PNS_ITR_OUT<>T.RCV_PNS_ITR_OUT
 OR N.PAD_UP_PNS_ITR_OUT<>T.PAD_UP_PNS_ITR_OUT
 OR N.DFT_PRN_OTD_ITR<>T.DFT_PRN_OTD_ITR
 OR N.DFT_ITR_IN_OTD_ITR<>T.DFT_ITR_IN_OTD_ITR
 OR N.DFT_ITR_OUT_OTD_ITR<>T.DFT_ITR_OUT_OTD_ITR
 OR N.NOR_ITR_IN_OTD_ITR<>T.NOR_ITR_IN_OTD_ITR
 OR N.NOR_ITR_OUT_OTD_ITR<>T.NOR_ITR_OUT_OTD_ITR
 OR N.FORW_PROV_DATE<>T.FORW_PROV_DATE
 OR N.PAY_DATE<>T.PAY_DATE
 OR N.DLY_PRN_PNS_ITR<>T.DLY_PRN_PNS_ITR
 OR N.DLY_IN_BAL_PNS_ITR<>T.DLY_IN_BAL_PNS_ITR
 OR N.DLY_OUT_BAL_PNS_ITR<>T.DLY_OUT_BAL_PNS_ITR
 OR N.RMK1<>T.RMK1
 OR N.RMK2<>T.RMK2
 OR N.RMK3<>T.RMK3
 OR N.RMK1_BAL<>T.RMK1_BAL
 OR N.RMK2_BAL<>T.RMK2_BAL
 OR N.RMK3_BAL<>T.RMK3_BAL
 OR N.HLD_FLG<>T.HLD_FLG
;

--Step3:
UPDATE dw_sdata.PCS_005_TB_SUP_DEBT_INFO_N P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_318
WHERE P.End_Dt=DATE('2100-12-31')
AND P.DUE_NUM=T_318.DUE_NUM
AND P.RCV_DATE=T_318.RCV_DATE
;

--Step4:
INSERT  INTO dw_sdata.PCS_005_TB_SUP_DEBT_INFO_N SELECT * FROM T_318;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
