#!/usr/bin/perl

use strict;     # Declare using Perl strict syntax
use DBI;        # If you are using other package, declare here

# ------------ Variable Section ------------
my ${AUTO_HOME} = $ENV{"AUTO_HOME"};

my ${WML_DB} = $ENV{"AUTO_WML_DB"};
if ( !defined(${WML_DB}) ) {
    ${WML_DB} = "WML";
}
my ${WTL_DB} = $ENV{"AUTO_WTL_DB"};
if ( !defined(${WTL_DB}) ) {
    ${WTL_DB} = "WTL";
}
my ${WMLVIEW_DB} = $ENV{"AUTO_WMLVIEW_DB"};
if ( !defined(${WMLVIEW_DB}) ) {
    ${WMLVIEW_DB} = "WMLVIEW";
}
my ${WTLVIEW_DB} = $ENV{"AUTO_WTLVIEW_DB"};
if ( !defined(${WTLVIEW_DB}) ) {
    ${WTLVIEW_DB} = "WTLVIEW";
}

my ${NULL_DATE} = "1900-01-02";
my ${MIN_DATE} = "1900-01-01";
my ${MAX_DATE} = "2100-12-31";

my ${LOGON_FILE} = "${AUTO_HOME}/etc/VERTICA_LOGON";
my ${LOGON_STR};
my ${CONTROL_FILE};
my ${TX_DATE};
my ${TX_DATE_YYYYMMDD};
my ${TX_MON_DAY_MMDD};

# ------------ VSQL function ------------
sub run_vsql_command
{
  #my $rc = open(VSQL, "${LOGON_STR}");
  my $rc = open(VSQL, "|vsql -h 22.224.65.171 -p 5433 -d CPCIMDB_TEST -U dwtrans -w dwtrans2016");

  unless ($rc) {
      print "Could not invoke VSQL command
";
      return -1;
  }

# ------ Below are VSQL scripts ----------
  print VSQL <<ENDOFINPUT;

\\set ON_ERROR_STOP on

--Step0:
DELETE FROM dw_sdata.PCS_006_TB_PUB_GUARANTEE WHERE start_dt>=DATE('${TX_DATE_YYYYMMDD}');
UPDATE dw_sdata.PCS_006_TB_PUB_GUARANTEE SET end_dt=DATE('2100-12-31') WHERE end_dt>=DATE('${TX_DATE_YYYYMMDD}') AND end_dt<>DATE('2100-12-31');

--Step1:
CREATE LOCAL TEMPORARY TABLE  T_340 ON COMMIT PRESERVE ROWS AS SELECT * FROM dw_sdata.PCS_006_TB_PUB_GUARANTEE WHERE 1=0;

--Step2:
INSERT  INTO T_340 (
  ENSURE_ID,
  APP_ID,
  GUARANTEE_ID,
  GUARANTEE_KIND,
  CURRENCY,
  GUARANTEE_AMOUNT,
  GUARANTEE_BEGIN_DATE,
  GUARANTEE_MATURITY_DATE,
  REALMATURE_DATE,
  CANCLE_FLAG,
  EXTERNAL_GUARANTEE_TYPE,
  OVER_GUARANTEE_ASSUBALA,
  BAD_GUARANTEE_ASSUBALA,
  CANCLE_DATE,
  GUARANTEE_CONTRACT_NUM,
  GUARANTEE_STATE,
  GUARANTEE_ALERT_STATE,
  YEARLY_INCOME,
  OTHER_ASSUBALA,
  BANK_ASSUBALA,
  PROVINCE_NUM,
  CREATE_TIME,
  UPDATE_TIME,
  DELFLAG,
  TRUNC_NO,
  start_dt,
  end_dt)
SELECT
  N.ENSURE_ID,
  N.APP_ID,
  N.GUARANTEE_ID,
  N.GUARANTEE_KIND,
  N.CURRENCY,
  N.GUARANTEE_AMOUNT,
  N.GUARANTEE_BEGIN_DATE,
  N.GUARANTEE_MATURITY_DATE,
  N.REALMATURE_DATE,
  N.CANCLE_FLAG,
  N.EXTERNAL_GUARANTEE_TYPE,
  N.OVER_GUARANTEE_ASSUBALA,
  N.BAD_GUARANTEE_ASSUBALA,
  N.CANCLE_DATE,
  N.GUARANTEE_CONTRACT_NUM,
  N.GUARANTEE_STATE,
  N.GUARANTEE_ALERT_STATE,
  N.YEARLY_INCOME,
  N.OTHER_ASSUBALA,
  N.BANK_ASSUBALA,
  N.PROVINCE_NUM,
  N.CREATE_TIME,
  N.UPDATE_TIME,
  N.DELFLAG,
  N.TRUNC_NO,
  DATE('${TX_DATE_YYYYMMDD}'),
  DATE('2100-12-31')
FROM 
 (SELECT
  COALESCE(ENSURE_ID, '' ) AS ENSURE_ID ,
  COALESCE(APP_ID, '' ) AS APP_ID ,
  COALESCE(GUARANTEE_ID, '' ) AS GUARANTEE_ID ,
  COALESCE(GUARANTEE_KIND, '' ) AS GUARANTEE_KIND ,
  COALESCE(CURRENCY, '' ) AS CURRENCY ,
  COALESCE(GUARANTEE_AMOUNT, 0 ) AS GUARANTEE_AMOUNT ,
  COALESCE(GUARANTEE_BEGIN_DATE,DATE('4999-12-31') ) AS GUARANTEE_BEGIN_DATE ,
  COALESCE(GUARANTEE_MATURITY_DATE,DATE('4999-12-31') ) AS GUARANTEE_MATURITY_DATE ,
  COALESCE(REALMATURE_DATE,DATE('4999-12-31') ) AS REALMATURE_DATE ,
  COALESCE(CANCLE_FLAG, '' ) AS CANCLE_FLAG ,
  COALESCE(EXTERNAL_GUARANTEE_TYPE, '' ) AS EXTERNAL_GUARANTEE_TYPE ,
  COALESCE(OVER_GUARANTEE_ASSUBALA, 0 ) AS OVER_GUARANTEE_ASSUBALA ,
  COALESCE(BAD_GUARANTEE_ASSUBALA, 0 ) AS BAD_GUARANTEE_ASSUBALA ,
  COALESCE(CANCLE_DATE,DATE('4999-12-31') ) AS CANCLE_DATE ,
  COALESCE(GUARANTEE_CONTRACT_NUM, '' ) AS GUARANTEE_CONTRACT_NUM ,
  COALESCE(GUARANTEE_STATE, '' ) AS GUARANTEE_STATE ,
  COALESCE(GUARANTEE_ALERT_STATE, '' ) AS GUARANTEE_ALERT_STATE ,
  COALESCE(YEARLY_INCOME, 0 ) AS YEARLY_INCOME ,
  COALESCE(OTHER_ASSUBALA, 0 ) AS OTHER_ASSUBALA ,
  COALESCE(BANK_ASSUBALA, 0 ) AS BANK_ASSUBALA ,
  COALESCE(PROVINCE_NUM, '' ) AS PROVINCE_NUM ,
  COALESCE(CREATE_TIME,'4999-12-31 00:00:00' ) AS CREATE_TIME ,
  COALESCE(UPDATE_TIME,'4999-12-31 00:00:00' ) AS UPDATE_TIME ,
  COALESCE(DELFLAG, '' ) AS DELFLAG ,
  COALESCE(TRUNC_NO, 0 ) AS TRUNC_NO 
 FROM  dw_tdata.PCS_006_TB_PUB_GUARANTEE_${TX_DATE_YYYYMMDD}) N
LEFT JOIN
 (SELECT 
  ENSURE_ID ,
  APP_ID ,
  GUARANTEE_ID ,
  GUARANTEE_KIND ,
  CURRENCY ,
  GUARANTEE_AMOUNT ,
  GUARANTEE_BEGIN_DATE ,
  GUARANTEE_MATURITY_DATE ,
  REALMATURE_DATE ,
  CANCLE_FLAG ,
  EXTERNAL_GUARANTEE_TYPE ,
  OVER_GUARANTEE_ASSUBALA ,
  BAD_GUARANTEE_ASSUBALA ,
  CANCLE_DATE ,
  GUARANTEE_CONTRACT_NUM ,
  GUARANTEE_STATE ,
  GUARANTEE_ALERT_STATE ,
  YEARLY_INCOME ,
  OTHER_ASSUBALA ,
  BANK_ASSUBALA ,
  PROVINCE_NUM ,
  CREATE_TIME ,
  UPDATE_TIME ,
  DELFLAG ,
  TRUNC_NO 
 FROM dw_sdata.PCS_006_TB_PUB_GUARANTEE 
 WHERE END_DT = DATE('2100-12-31') ) T
ON N.ENSURE_ID = T.ENSURE_ID
WHERE
(T.ENSURE_ID IS NULL)
 OR N.APP_ID<>T.APP_ID
 OR N.GUARANTEE_ID<>T.GUARANTEE_ID
 OR N.GUARANTEE_KIND<>T.GUARANTEE_KIND
 OR N.CURRENCY<>T.CURRENCY
 OR N.GUARANTEE_AMOUNT<>T.GUARANTEE_AMOUNT
 OR N.GUARANTEE_BEGIN_DATE<>T.GUARANTEE_BEGIN_DATE
 OR N.GUARANTEE_MATURITY_DATE<>T.GUARANTEE_MATURITY_DATE
 OR N.REALMATURE_DATE<>T.REALMATURE_DATE
 OR N.CANCLE_FLAG<>T.CANCLE_FLAG
 OR N.EXTERNAL_GUARANTEE_TYPE<>T.EXTERNAL_GUARANTEE_TYPE
 OR N.OVER_GUARANTEE_ASSUBALA<>T.OVER_GUARANTEE_ASSUBALA
 OR N.BAD_GUARANTEE_ASSUBALA<>T.BAD_GUARANTEE_ASSUBALA
 OR N.CANCLE_DATE<>T.CANCLE_DATE
 OR N.GUARANTEE_CONTRACT_NUM<>T.GUARANTEE_CONTRACT_NUM
 OR N.GUARANTEE_STATE<>T.GUARANTEE_STATE
 OR N.GUARANTEE_ALERT_STATE<>T.GUARANTEE_ALERT_STATE
 OR N.YEARLY_INCOME<>T.YEARLY_INCOME
 OR N.OTHER_ASSUBALA<>T.OTHER_ASSUBALA
 OR N.BANK_ASSUBALA<>T.BANK_ASSUBALA
 OR N.PROVINCE_NUM<>T.PROVINCE_NUM
 OR N.CREATE_TIME<>T.CREATE_TIME
 OR N.UPDATE_TIME<>T.UPDATE_TIME
 OR N.DELFLAG<>T.DELFLAG
 OR N.TRUNC_NO<>T.TRUNC_NO
;

--Step3:
UPDATE dw_sdata.PCS_006_TB_PUB_GUARANTEE P 
SET End_Dt=DATE('${TX_DATE_YYYYMMDD}')
FROM T_340
WHERE P.End_Dt=DATE('2100-12-31')
AND P.ENSURE_ID=T_340.ENSURE_ID
;

--Step4:
INSERT  INTO dw_sdata.PCS_006_TB_PUB_GUARANTEE SELECT * FROM T_340;

COMMIT;

ENDOFINPUT

  close(VSQL);

  my $RET_CODE = $? >> 8;

  if ( $RET_CODE == 0 ) {
      return 0;
  }
  else {
      return 1;
  }
}

# ------------ main function ------------
sub main
{
   my $ret;
   open(LOGONFILE_H, "${LOGON_FILE}");
   ${LOGON_STR} = <LOGONFILE_H>;
   close(LOGONFILE_H);
   
   # Get the decoded logon string
   my($user,$passwd) = split(',',${LOGON_STR}); 
   #my $decodepasswd = `${AUTO_HOME}/bin/IceCode.exe -d "$passwd" "$user"`;                     
   #${LOGON_STR} = "|vsql -h 192.168.2.44 -p 5433 -d CPCIMDB_TEST -U ".$user." -w ".$decodepasswd;

   # Call vsql command to load data
   $ret = run_vsql_command();

   print "run_vsql_command() = $ret";
   return $ret;
}

# ------------ program section ------------
if ( $#ARGV < 0 ) {
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

# Get the first argument
${CONTROL_FILE} = $ARGV[0];

if (${CONTROL_FILE} =~/[0-9]{8}($|\.)/) {
   ${TX_DATE_YYYYMMDD} = substr($&,0,8);
}
else{
   print "Usage: [perl 程序名 Control_File] (Control_File format: dir.jobnameYYYYMMDD or sysname_jobname_YYYYMMDD.dir) 
";
   print "
";
   exit(1);
}

${TX_MON_DAY_MMDD} = substr(${TX_DATE_YYYYMMDD}, length(${TX_DATE_YYYYMMDD})-4,4);
${TX_DATE} = substr(${TX_DATE_YYYYMMDD}, 0, 4)."-".substr(${TX_DATE_YYYYMMDD}, 4, 2)."-".substr(${TX_DATE_YYYYMMDD}, 6, 2);
open(STDERR, ">&STDOUT");

my $ret = main();

exit($ret);
